# PAL on Colab

## Mount Google Drive

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

## Set project paths

In [2]:
from pathlib import Path
import os

DRIVE_ROOT = Path("/content/drive/MyDrive")
PROJECT_ROOT = DRIVE_ROOT / "BT4222" / "PAL"
DATASET_ROOT = PROJECT_ROOT / "datasets"
MODEL_DIR = PROJECT_ROOT / "models"
RESULTS_DIR = PROJECT_ROOT / "results"
CHECKPOINT_DIR = PROJECT_ROOT / "checkpoints"
LOG_DIR = PROJECT_ROOT / "log"
RUNS_DIR = PROJECT_ROOT / "runs"

for p in [RESULTS_DIR, CHECKPOINT_DIR, LOG_DIR, RUNS_DIR]:
    p.mkdir(parents=True, exist_ok=True)

os.chdir(PROJECT_ROOT)
print("Working directory:", PROJECT_ROOT)
print("models exists:", MODEL_DIR.exists())
print("datasets exists:", DATASET_ROOT.exists())

Working directory: /content/drive/MyDrive/BT4222/PAL
models exists: True
datasets exists: True

## Install dependencies

In [3]:
!pip install -q pyyaml scipy tqdm tensorboard

## Verify required files

In [4]:
required_files = [
    PROJECT_ROOT / "config.yaml",
    PROJECT_ROOT / "utility.py",
    PROJECT_ROOT / "train.py",
    PROJECT_ROOT / "export_explanations.py",
    PROJECT_ROOT / "prepare_steam_pal.py",
    PROJECT_ROOT / "models" / "PAL.py",
]

missing = [str(p) for p in required_files if not p.exists()]
if missing:
    print("Missing files:")
    for p in missing:
        print(" -", p)
else:
    print("All core code files are present.")

All core code files are present.

## Verify SteamDebug dataset files

In [5]:
dataset_name = "SteamDebug"
dataset_dir = DATASET_ROOT / dataset_name

required_dataset_files = [
    dataset_dir / "SteamDebug_data_size.txt",
    dataset_dir / "bundle_item.txt",
    dataset_dir / "user_bundle_train.txt",
    dataset_dir / "user_bundle_tune.txt",
    dataset_dir / "user_bundle_test.txt",
    dataset_dir / "user_item.txt",
]

missing_dataset = [str(p) for p in required_dataset_files if not p.exists()]
if missing_dataset:
    print("Missing dataset files:")
    for p in missing_dataset:
        print(" -", p)
else:
    print("SteamDebug dataset looks complete.")

SteamDebug dataset looks complete.

## Load base configuration

In [6]:
import yaml
import torch

with open(PROJECT_ROOT / "config.yaml", "r", encoding="utf-8") as f:
    full_conf = yaml.safe_load(f)

base_conf = dict(full_conf["SteamDebug"])
base_conf["data_path"] = str(PROJECT_ROOT / "datasets")
base_conf["dataset"] = "SteamDebug"
base_conf["model"] = "PAL"
base_conf["device"] = torch.device("cuda" if torch.cuda.is_available() else "cpu")

print("base_conf loaded")
print("keys:", sorted(base_conf.keys()))
print("batch_size_train =", base_conf["batch_size_train"])
print("batch_size_test  =", base_conf["batch_size_test"])
print("topk             =", base_conf["topk"])
print("data_path        =", base_conf["data_path"])
print("device           =", base_conf["device"])

base_conf loaded
keys: ['attention_dropout', 'attention_hidden_size', 'attention_score_type', 'attention_type', 'aug_type', 'batch_size_test', 'batch_size_train', 'bundle_agg_ratios', 'bundle_level_ratios', 'c_lambdas', 'c_temps', 'data_path', 'dataset', 'device', 'ed_interval', 'embedding_sizes', 'epochs', 'eval_bundle_chunk_size', 'explain_top_items', 'fusion_hidden_size', 'fusion_type', 'item_level_ratios', 'l2_regs', 'lrs', 'model', 'neg_num', 'num_layerss', 'num_workers_test', 'num_workers_train', 'test_interval', 'topk', 'use_item_attention', 'use_view_fusion']
batch_size_train = 64
batch_size_test  = 128
topk             = [1, 2, 5, 10, 20]
data_path        = /content/drive/MyDrive/BT4222/PAL/datasets
device           = cuda

## Smoke test: imports, dataset loading, model initialization, and single-batch forward

In [7]:
import sys

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from utility import Datasets
from models.PAL import PAL

print("Imports OK")

conf_for_data = dict(base_conf)
dataset = Datasets(conf_for_data)

print("num_users:", dataset.num_users)
print("num_bundles:", dataset.num_bundles)
print("num_items:", dataset.num_items)
print("train batches:", len(dataset.train_loader))
print("val batches:", len(dataset.val_loader))
print("test batches:", len(dataset.test_loader))

conf_for_model = dict(conf_for_data)
conf_for_model["num_users"] = dataset.num_users
conf_for_model["num_bundles"] = dataset.num_bundles
conf_for_model["num_items"] = dataset.num_items
conf_for_model["embedding_size"] = conf_for_model["embedding_sizes"][0]
conf_for_model["num_layers"] = conf_for_model["num_layerss"][0]
conf_for_model["l2_reg"] = conf_for_model["l2_regs"][0]
conf_for_model["c_temp"] = conf_for_model["c_temps"][0]
conf_for_model["item_level_ratio"] = conf_for_model["item_level_ratios"][0]
conf_for_model["bundle_level_ratio"] = conf_for_model["bundle_level_ratios"][0]
conf_for_model["bundle_agg_ratio"] = conf_for_model["bundle_agg_ratios"][0]

model = PAL(conf_for_model, dataset.graphs).to(conf_for_model["device"])
print(model.__class__.__name__, "initialized successfully")

batch = next(iter(dataset.train_loader))
batch = [x.to(conf_for_model["device"]) for x in batch]
bpr_loss, c_loss = model(batch, ED_drop=False)

print("bpr_loss =", float(bpr_loss))
print("c_loss   =", float(c_loss))

Imports OK
>>>>>>>>>>B-I statistics>>>>>>>>>>
Average interactions 5.757723808288574
Non-zero rows 0.9967479674796748
Non-zero columns 1.0
Matrix density 0.002042470229597649
>>>>>>>>>>U-I statistics>>>>>>>>>>
Average interactions 30.47064208984375
Non-zero rows 1.0
Non-zero columns 0.5001773678609436
Matrix density 0.010809025126048253
>>>>>>>>>>U-B statistics in train>>>>>>>>>>
Average interactions 1.7729297876358032
Non-zero rows 0.8142673955591551
Non-zero columns 0.3382113821138211
Matrix density 0.0028828125900210205
>>>>>>>>>>U-B statistics in tune>>>>>>>>>>
Average interactions 0.5909765958786011
Non-zero rows 0.41843828035364783
Non-zero columns 0.27479674796747966
Matrix density 0.0009609375300070068
>>>>>>>>>>U-B statistics in test>>>>>>>>>>
Average interactions 0.5909765958786011
Non-zero rows 0.4189782007153945
Non-zero columns 0.2780487804878049
Matrix density 0.0009609375300070068
num_users: 29634
num_bundles: 615
num_items: 2819
train batches: 820
val batches: 232
test batches: 232
PAL initialized successfully
bpr_loss = 0.6561641097068787
c_loss   = 3.8280766010284424

/tmp/ipykernel_1173/1926821644.py:40: UserWarning: Converting a tensor with requires_grad=True to a scalar may lead to unexpected behavior.
Consider using tensor.detach() first. (Triggered internally at /pytorch/torch/csrc/autograd/generated/python_variable_methods.cpp:836.)
  print("bpr_loss =", float(bpr_loss))

## Define notebook training and evaluation utilities

In [8]:
import csv
import json
import pandas as pd
from tqdm import tqdm
import torch
import torch.optim as optim

METRIC_NAMES = ["recall", "precision", "ndcg", "hit_rate", "map", "mrr", "f1"]

def get_topk_metrics(grd, is_hit, topk):
    epsilon = 1e-8
    device = grd.device

    num_pos = grd.sum(dim=1)
    valid_user = num_pos > 0
    denorm = valid_user.sum().item()

    if denorm == 0:
        return {m: [0, 0] for m in METRIC_NAMES}

    is_hit = is_hit.float()
    hit_cnt = is_hit.sum(dim=1)

    recall = hit_cnt / (num_pos + epsilon)
    precision = hit_cnt / topk
    hit_rate = (hit_cnt > 0).float()
    f1 = 2 * precision * recall / (precision + recall + epsilon)

    rank_positions = torch.arange(1, topk + 1, device=device, dtype=torch.float)
    discounts = torch.log2(rank_positions + 1)

    dcg = (is_hit / discounts).sum(dim=1)
    num_pos_at_k = num_pos.clamp(0, topk).to(torch.long)
    ideal_hits = torch.arange(topk, device=device).unsqueeze(0) < num_pos_at_k.unsqueeze(1)
    idcg = (ideal_hits.float() / discounts).sum(dim=1)
    ndcg = dcg / (idcg + epsilon)

    precision_at_rank = is_hit.cumsum(dim=1) / rank_positions
    ap = (precision_at_rank * is_hit).sum(dim=1) / torch.minimum(
        num_pos,
        torch.tensor(topk, device=device, dtype=num_pos.dtype)
    ).clamp(min=1)

    reciprocal_rank = (is_hit / rank_positions).max(dim=1).values

    return {
        "recall": [recall[valid_user].sum().item(), denorm],
        "precision": [precision[valid_user].sum().item(), denorm],
        "ndcg": [ndcg[valid_user].sum().item(), denorm],
        "hit_rate": [hit_rate[valid_user].sum().item(), denorm],
        "map": [ap[valid_user].sum().item(), denorm],
        "mrr": [reciprocal_rank[valid_user].sum().item(), denorm],
        "f1": [f1[valid_user].sum().item(), denorm],
    }


def get_metrics(metrics, grd, pred, topks):
    grd = grd.to(pred.device)

    for topk in topks:
        _, col_indice = torch.topk(pred, topk)
        row_indice = torch.zeros_like(col_indice) + torch.arange(
            pred.shape[0], device=pred.device, dtype=torch.long
        ).view(-1, 1)

        is_hit = grd[row_indice.view(-1), col_indice.view(-1)].view(-1, topk)
        tmp_topk = get_topk_metrics(grd, is_hit, topk)

        for m in METRIC_NAMES:
            metrics[m][topk][0] += tmp_topk[m][0]
            metrics[m][topk][1] += tmp_topk[m][1]

    return metrics


def evaluate_model(model, dataloader, conf):
    device = conf["device"]
    tmp_metrics = {m: {k: [0, 0] for k in conf["topk"]} for m in METRIC_NAMES}

    model.eval()
    with torch.no_grad():
        rs = model.propagate(test=True)
        for users, ground_truth_u_b, train_mask_u_b in dataloader:
            pred_b = model.evaluate(rs, users.to(device))
            pred_b -= 1e8 * train_mask_u_b.to(device)
            tmp_metrics = get_metrics(tmp_metrics, ground_truth_u_b, pred_b, conf["topk"])

    metrics = {
        m: {
            k: (tmp_metrics[m][k][0] / tmp_metrics[m][k][1] if tmp_metrics[m][k][1] else 0.0)
            for k in conf["topk"]
        }
        for m in METRIC_NAMES
    }
    return metrics


def print_metrics_table(metrics, split_name):
    print(f"\n[{split_name}]")
    for metric_name in METRIC_NAMES:
        line = "  ".join([f"{metric_name}@{k}={metrics[metric_name][k]:.6f}" for k in metrics[metric_name]])
        print(line)


def flatten_metrics_for_row(prefix, metrics):
    row = {}
    for metric_name in METRIC_NAMES:
        for k, v in metrics[metric_name].items():
            row[f"{prefix}_{metric_name}@{k}"] = v
    return row


def train_notebook(conf, experiment_name="colab_run"):
    device = conf["device"]

    dataset = Datasets(conf)

    conf = dict(conf)
    conf["num_users"] = dataset.num_users
    conf["num_bundles"] = dataset.num_bundles
    conf["num_items"] = dataset.num_items

    conf["embedding_size"] = conf["embedding_sizes"][0]
    conf["num_layers"] = conf["num_layerss"][0]
    conf["l2_reg"] = conf["l2_regs"][0]
    conf["c_lambda"] = conf["c_lambdas"][0]
    conf["c_temp"] = conf["c_temps"][0]
    conf["item_level_ratio"] = conf["item_level_ratios"][0]
    conf["bundle_level_ratio"] = conf["bundle_level_ratios"][0]
    conf["bundle_agg_ratio"] = conf["bundle_agg_ratios"][0]
    lr = conf["lrs"][0]

    model = PAL(conf, dataset.graphs).to(device)
    optimizer = optim.Adam(model.parameters(), lr=lr, weight_decay=conf["l2_reg"])

    ckpt_dir = PROJECT_ROOT / "checkpoints" / conf["dataset"] / conf["model"] / "model"
    conf_dir = PROJECT_ROOT / "checkpoints" / conf["dataset"] / conf["model"] / "conf"
    result_dir = PROJECT_ROOT / "results"

    ckpt_dir.mkdir(parents=True, exist_ok=True)
    conf_dir.mkdir(parents=True, exist_ok=True)
    result_dir.mkdir(parents=True, exist_ok=True)

    checkpoint_model_path = ckpt_dir / experiment_name
    checkpoint_conf_path = conf_dir / experiment_name
    result_csv = result_dir / f"{conf['dataset']}_{conf['model']}_{experiment_name}_results.csv"

    best_val_recall20 = -1.0
    best_val_ndcg20 = -1.0
    best_epoch = None
    history = []

    for epoch in range(conf["epochs"]):
        model.train()
        pbar = tqdm(dataset.train_loader, desc=f"Epoch {epoch+1}/{conf['epochs']}")

        for batch in pbar:
            batch = [x.to(device) for x in batch]

            optimizer.zero_grad()
            bpr_loss, c_loss = model(batch, ED_drop=False)
            loss = bpr_loss + conf["c_lambda"] * c_loss
            loss.backward()
            optimizer.step()

            pbar.set_postfix(
                loss=float(loss.detach().cpu()),
                bpr=float(bpr_loss.detach().cpu()),
                c=float(c_loss.detach().cpu())
            )

        val_metrics = evaluate_model(model, dataset.val_loader, conf)
        test_metrics = evaluate_model(model, dataset.test_loader, conf)

        print_metrics_table(val_metrics, "VAL")
        print_metrics_table(test_metrics, "TEST")

        row = {"epoch": epoch + 1}
        row.update(flatten_metrics_for_row("val", val_metrics))
        row.update(flatten_metrics_for_row("test", test_metrics))
        history.append(row)

        is_best = (
            val_metrics["recall"].get(20, -1) > best_val_recall20
            and val_metrics["ndcg"].get(20, -1) > best_val_ndcg20
        )

        if is_best:
            best_val_recall20 = val_metrics["recall"][20]
            best_val_ndcg20 = val_metrics["ndcg"][20]
            best_epoch = epoch + 1

            torch.save(model.state_dict(), checkpoint_model_path)

            dump_conf = dict(conf)
            dump_conf["device"] = str(conf["device"])
            with open(checkpoint_conf_path, "w", encoding="utf-8") as f:
                json.dump(dump_conf, f, ensure_ascii=False, indent=2)

            print(f"\nSaved new best checkpoint at epoch {best_epoch}")

    history_df = pd.DataFrame(history)
    history_df.to_csv(result_csv, index=False)

    return {
        "model": model,
        "history": history,
        "history_df": history_df,
        "best_epoch": best_epoch,
        "checkpoint_model_path": str(checkpoint_model_path),
        "checkpoint_conf_path": str(checkpoint_conf_path),
        "result_csv": str(result_csv),
    }

## Define experiment configuration helper

In [9]:
def make_experiment_conf(base_conf, *, attention_type=None, fusion_type=None, epochs=100):
    conf = dict(base_conf)
    conf["epochs"] = epochs

    # attention
    if attention_type == "none":
        conf["use_item_attention"] = False
    elif attention_type in {"global", "user"}:
        conf["use_item_attention"] = True
        conf["attention_type"] = attention_type

    # fusion
    if fusion_type == "none":
        conf["use_view_fusion"] = False
    elif fusion_type in {"global", "user"}:
        conf["use_view_fusion"] = True
        conf["fusion_type"] = fusion_type

    return conf

## Run baseline experiment

In [10]:
baseline_conf = make_experiment_conf(
    base_conf,
    attention_type="none",
    fusion_type="none",
    epochs=100,
)

baseline_output = train_notebook(
    baseline_conf,
    experiment_name="step0_baseline"
)

baseline_output["history_df"]

>>>>>>>>>>B-I statistics>>>>>>>>>>
Average interactions 5.757723808288574
Non-zero rows 0.9967479674796748
Non-zero columns 1.0
Matrix density 0.002042470229597649
>>>>>>>>>>U-I statistics>>>>>>>>>>
Average interactions 30.47064208984375
Non-zero rows 1.0
Non-zero columns 0.5001773678609436
Matrix density 0.010809025126048253
>>>>>>>>>>U-B statistics in train>>>>>>>>>>
Average interactions 1.7729297876358032
Non-zero rows 0.8142673955591551
Non-zero columns 0.3382113821138211
Matrix density 0.0028828125900210205
>>>>>>>>>>U-B statistics in tune>>>>>>>>>>
Average interactions 0.5909765958786011
Non-zero rows 0.41843828035364783
Non-zero columns 0.27479674796747966
Matrix density 0.0009609375300070068
>>>>>>>>>>U-B statistics in test>>>>>>>>>>
Average interactions 0.5909765958786011
Non-zero rows 0.4189782007153945
Non-zero columns 0.2780487804878049
Matrix density 0.0009609375300070068

Epoch 1/100: 100%|██████████| 820/820 [00:11<00:00, 70.78it/s, bpr=0.123, c=3.32, loss=0.256]

[VAL]
recall@1=0.335721  recall@2=0.478756  recall@5=0.817926  recall@10=0.941038  recall@20=0.977361
precision@1=0.434113  precision@2=0.328669  precision@5=0.222935  precision@10=0.129976  precision@20=0.067968
ndcg@1=0.434113  ndcg@2=0.472380  ndcg@5=0.616419  ndcg@10=0.661223  ndcg@20=0.671713
hit_rate@1=0.434113  hit_rate@2=0.557339  hit_rate@5=0.867823  hit_rate@10=0.961613  hit_rate@20=0.986935
map@1=0.434113  map@2=0.447440  map@5=0.535190  map@10=0.559088  map@20=0.563063
mrr@1=0.434113  mrr@2=0.495726  mrr@5=0.573700  mrr@10=0.587159  mrr@20=0.589060
f1@1=0.364598  f1@2=0.372641  f1@5=0.337584  f1@10=0.222291  f1@20=0.124896

[TEST]
recall@1=0.332480  recall@2=0.482460  recall@5=0.820265  recall@10=0.942907  recall@20=0.979150
precision@1=0.431540  precision@2=0.332756  precision@5=0.223454  precision@10=0.130074  precision@20=0.068065
ndcg@1=0.431540  ndcg@2=0.474672  ndcg@5=0.617261  ndcg@10=0.661662  ndcg@20=0.672155
hit_rate@1=0.431540  hit_rate@2=0.560567  hit_rate@5=0.869845  hit_rate@10=0.963273  hit_rate@20=0.987274
map@1=0.431540  map@2=0.449420  map@5=0.535741  map@10=0.559288  map@20=0.563327
mrr@1=0.431540  mrr@2=0.496053  mrr@5=0.573535  mrr@10=0.586829  mrr@20=0.588606
f1@1=0.361516  f1@2=0.376378  f1@5=0.338593  f1@10=0.222602  f1@20=0.125101

Saved new best checkpoint at epoch 1

Epoch 2/100: 100%|██████████| 820/820 [00:10<00:00, 74.58it/s, bpr=0.0773, c=3.06, loss=0.2]

[VAL]
recall@1=0.390247  recall@2=0.546512  recall@5=0.850609  recall@10=0.949690  recall@20=0.979880
precision@1=0.493629  precision@2=0.368427  precision@5=0.231968  precision@10=0.131056  precision@20=0.068206
ndcg@1=0.493629  ndcg@2=0.538163  ndcg@5=0.667255  ndcg@10=0.703182  ndcg@20=0.712071
hit_rate@1=0.493629  hit_rate@2=0.628952  hit_rate@5=0.894839  hit_rate@10=0.969194  hit_rate@20=0.988468
map@1=0.493629  map@2=0.511472  map@5=0.591982  map@10=0.611324  map@20=0.614832
mrr@1=0.493629  mrr@2=0.561290  mrr@5=0.629133  mrr@10=0.639629  mrr@20=0.641077
f1@1=0.420623  f1@2=0.421255  f1@5=0.351167  f1@10=0.224191  f1@20=0.125304

[TEST]
recall@1=0.380225  recall@2=0.540955  recall@5=0.852981  recall@10=0.949890  recall@20=0.980958
precision@1=0.483086  precision@2=0.365697  precision@5=0.232539  precision@10=0.131153  precision@20=0.068226
ndcg@1=0.483086  ndcg@2=0.530780  ndcg@5=0.664158  ndcg@10=0.699425  ndcg@20=0.708469
hit_rate@1=0.483086  hit_rate@2=0.623792  hit_rate@5=0.896263  hit_rate@10=0.967703  hit_rate@20=0.988563
map@1=0.483086  map@2=0.503463  map@5=0.587292  map@10=0.606289  map@20=0.609785
mrr@1=0.483086  mrr@2=0.553439  mrr@5=0.623484  mrr@10=0.633702  mrr@20=0.635284
f1@1=0.410456  f1@2=0.417765  f1@5=0.352196  f1@10=0.224401  f1@20=0.125372

Saved new best checkpoint at epoch 2

Epoch 3/100: 100%|██████████| 820/820 [00:11<00:00, 73.38it/s, bpr=0.0557, c=3, loss=0.176]

[VAL]
recall@1=0.404761  recall@2=0.562623  recall@5=0.857423  recall@10=0.953509  recall@20=0.982531
precision@1=0.508952  precision@2=0.376411  precision@5=0.234048  precision@10=0.131629  precision@20=0.068395
ndcg@1=0.508952  ndcg@2=0.553714  ndcg@5=0.679851  ndcg@10=0.714745  ndcg@20=0.723260
hit_rate@1=0.508952  hit_rate@2=0.645565  hit_rate@5=0.899677  hit_rate@10=0.971855  hit_rate@20=0.990565
map@1=0.508952  map@2=0.526613  map@5=0.606604  map@10=0.625388  map@20=0.628748
mrr@1=0.508952  mrr@2=0.577258  mrr@5=0.642802  mrr@10=0.653084  mrr@20=0.654473
f1@1=0.435375  f1@2=0.431965  f1@5=0.354183  f1@10=0.225132  f1@20=0.125650

[TEST]
recall@1=0.394245  recall@2=0.563994  recall@5=0.860334  recall@10=0.954120  recall@20=0.982003
precision@1=0.498470  precision@2=0.378061  precision@5=0.234601  precision@10=0.131709  precision@20=0.068311
ndcg@1=0.498470  ndcg@2=0.550963  ndcg@5=0.678020  ndcg@10=0.712069  ndcg@20=0.720246
hit_rate@1=0.498470  hit_rate@2=0.646907  hit_rate@5=0.901740  hit_rate@10=0.970844  hit_rate@20=0.989530
map@1=0.498470  map@2=0.522531  map@5=0.603439  map@10=0.621755  map@20=0.624967
mrr@1=0.498470  mrr@2=0.572688  mrr@5=0.638599  mrr@10=0.648392  mrr@20=0.649803
f1@1=0.424901  f1@2=0.433591  f1@5=0.355287  f1@10=0.225359  f1@20=0.125531

Saved new best checkpoint at epoch 3

Epoch 4/100: 100%|██████████| 820/820 [00:11<00:00, 73.94it/s, bpr=0.0679, c=2.69, loss=0.176]

[VAL]
recall@1=0.462694  recall@2=0.633195  recall@5=0.875433  recall@10=0.956241  recall@20=0.982363
precision@1=0.570242  precision@2=0.416008  precision@5=0.239177  precision@10=0.132073  precision@20=0.068395
ndcg@1=0.570242  ndcg@2=0.621426  ndcg@5=0.725347  ndcg@10=0.754773  ndcg@20=0.762465
hit_rate@1=0.570242  hit_rate@2=0.717581  hit_rate@5=0.913871  hit_rate@10=0.973790  hit_rate@20=0.990323
map@1=0.570242  map@2=0.593004  map@5=0.661107  map@10=0.677124  map@20=0.680178
mrr@1=0.570242  mrr@2=0.643911  mrr@5=0.695914  mrr@10=0.704437  mrr@20=0.705675
f1@1=0.494364  f1@2=0.481751  f1@5=0.361845  f1@10=0.225861  f1@20=0.125645

[TEST]
recall@1=0.450674  recall@2=0.635455  recall@5=0.876925  recall@10=0.957794  recall@20=0.982835
precision@1=0.558231  precision@2=0.417244  precision@5=0.239433  precision@10=0.132305  precision@20=0.068396
ndcg@1=0.558231  ndcg@2=0.618291  ndcg@5=0.722277  ndcg@10=0.751704  ndcg@20=0.759034
hit_rate@1=0.558231  hit_rate@2=0.719878  hit_rate@5=0.914626  hit_rate@10=0.973744  hit_rate@20=0.989852
map@1=0.558231  map@2=0.588011  map@5=0.656641  map@10=0.672550  map@20=0.675431
mrr@1=0.558231  mrr@2=0.639054  mrr@5=0.690750  mrr@10=0.699194  mrr@20=0.700408
f1@1=0.482398  f1@2=0.483491  f1@5=0.362461  f1@10=0.226336  f1@20=0.125681

Epoch 5/100: 100%|██████████| 820/820 [00:11<00:00, 73.40it/s, bpr=0.0519, c=2.79, loss=0.163]

[VAL]
recall@1=0.477018  recall@2=0.654747  recall@5=0.883318  recall@10=0.957218  recall@20=0.982886
precision@1=0.585161  precision@2=0.428145  precision@5=0.241032  precision@10=0.132169  precision@20=0.068419
ndcg@1=0.585161  ndcg@2=0.640826  ndcg@5=0.738605  ndcg@10=0.765707  ndcg@20=0.773267
hit_rate@1=0.585161  hit_rate@2=0.739194  hit_rate@5=0.920806  hit_rate@10=0.974516  hit_rate@20=0.990726
map@1=0.585161  map@2=0.611694  map@5=0.676335  map@10=0.691280  map@20=0.694295
mrr@1=0.585161  mrr@2=0.662177  mrr@5=0.710294  mrr@10=0.717981  mrr@20=0.719182
f1@1=0.508875  f1@2=0.496955  f1@5=0.364814  f1@10=0.226059  f1@20=0.125701

[TEST]
recall@1=0.472196  recall@2=0.656269  recall@5=0.884316  recall@10=0.958195  recall@20=0.983482
precision@1=0.579736  precision@2=0.428520  precision@5=0.241302  precision@10=0.132321  precision@20=0.068416
ndcg@1=0.579736  ndcg@2=0.639729  ndcg@5=0.738023  ndcg@10=0.765036  ndcg@20=0.772412
hit_rate@1=0.579736  hit_rate@2=0.741302  hit_rate@5=0.920667  hit_rate@10=0.973824  hit_rate@20=0.990335
map@1=0.579736  map@2=0.609576  map@5=0.675250  map@10=0.690039  map@20=0.692923
mrr@1=0.579736  mrr@2=0.660519  mrr@5=0.708470  mrr@10=0.716102  mrr@20=0.717327
f1@1=0.503921  f1@2=0.497870  f1@5=0.365358  f1@10=0.226384  f1@20=0.125728

Saved new best checkpoint at epoch 5

Epoch 6/100: 100%|██████████| 820/820 [00:11<00:00, 74.47it/s, bpr=0.0322, c=2.78, loss=0.143]

[VAL]
recall@1=0.493723  recall@2=0.671342  recall@5=0.889107  recall@10=0.957486  recall@20=0.984066
precision@1=0.602823  precision@2=0.436815  precision@5=0.242452  precision@10=0.132250  precision@20=0.068516
ndcg@1=0.602823  ndcg@2=0.657665  ndcg@5=0.750904  ndcg@10=0.776180  ndcg@20=0.783993
hit_rate@1=0.602823  hit_rate@2=0.755645  hit_rate@5=0.926371  hit_rate@10=0.974516  hit_rate@20=0.991774
map@1=0.602823  map@2=0.628589  map@5=0.690710  map@10=0.704883  map@20=0.707979
mrr@1=0.602823  mrr@2=0.679234  mrr@5=0.724734  mrr@10=0.731655  mrr@20=0.732934
f1@1=0.525899  f1@2=0.508275  f1@5=0.367008  f1@10=0.226186  f1@20=0.125866

[TEST]
recall@1=0.486211  recall@2=0.675073  recall@5=0.891157  recall@10=0.959580  recall@20=0.984373
precision@1=0.594314  precision@2=0.439312  precision@5=0.242816  precision@10=0.132539  precision@20=0.068500
ndcg@1=0.594314  ndcg@2=0.657300  ndcg@5=0.749927  ndcg@10=0.775230  ndcg@20=0.782461
hit_rate@1=0.594314  hit_rate@2=0.759021  hit_rate@5=0.927110  hit_rate@10=0.974549  hit_rate@20=0.990738
map@1=0.594314  map@2=0.627054  map@5=0.688991  map@10=0.703165  map@20=0.705980
mrr@1=0.594314  mrr@2=0.676667  mrr@5=0.721637  mrr@10=0.728486  mrr@20=0.729689
f1@1=0.518105  f1@2=0.511292  f1@5=0.367844  f1@10=0.226761  f1@20=0.125881

Saved new best checkpoint at epoch 6

Epoch 7/100: 100%|██████████| 820/820 [00:11<00:00, 74.21it/s, bpr=0.0314, c=2.73, loss=0.141]

[VAL]
recall@1=0.510578  recall@2=0.696001  recall@5=0.901064  recall@10=0.959944  recall@20=0.983853
precision@1=0.620000  precision@2=0.450484  precision@5=0.245355  precision@10=0.132565  precision@20=0.068492
ndcg@1=0.620000  ndcg@2=0.679979  ndcg@5=0.767642  ndcg@10=0.789622  ndcg@20=0.796657
hit_rate@1=0.620000  hit_rate@2=0.780000  hit_rate@5=0.936129  hit_rate@10=0.976371  hit_rate@20=0.991452
map@1=0.620000  map@2=0.650262  map@5=0.709299  map@10=0.721896  map@20=0.724704
mrr@1=0.620000  mrr@2=0.700000  mrr@5=0.741902  mrr@10=0.747713  mrr@20=0.748810
f1@1=0.542791  f1@2=0.525566  f1@5=0.371582  f1@10=0.226726  f1@20=0.125832

[TEST]
recall@1=0.507941  recall@2=0.699489  recall@5=0.899294  recall@10=0.961212  recall@20=0.984429
precision@1=0.616704  precision@2=0.452159  precision@5=0.245006  precision@10=0.132740  precision@20=0.068492
ndcg@1=0.616704  ndcg@2=0.681035  ndcg@5=0.767020  ndcg@10=0.790029  ndcg@20=0.796786
hit_rate@1=0.616704  hit_rate@2=0.783183  hit_rate@5=0.933634  hit_rate@10=0.976160  hit_rate@20=0.990979
map@1=0.616704  map@2=0.650612  map@5=0.709233  map@10=0.722297  map@20=0.724921
mrr@1=0.616704  mrr@2=0.699944  mrr@5=0.740614  mrr@10=0.746805  mrr@20=0.747892
f1@1=0.539988  f1@2=0.527984  f1@5=0.371199  f1@10=0.227083  f1@20=0.125854

Epoch 8/100: 100%|██████████| 820/820 [00:11<00:00, 74.08it/s, bpr=0.043, c=2.59, loss=0.147]

[VAL]
recall@1=0.509459  recall@2=0.691617  recall@5=0.901926  recall@10=0.960147  recall@20=0.984091
precision@1=0.618145  precision@2=0.447460  precision@5=0.245694  precision@10=0.132629  precision@20=0.068492
ndcg@1=0.618145  ndcg@2=0.676282  ndcg@5=0.766706  ndcg@10=0.788470  ndcg@20=0.795508
hit_rate@1=0.618145  hit_rate@2=0.775887  hit_rate@5=0.936532  hit_rate@10=0.976210  hit_rate@20=0.991613
map@1=0.618145  map@2=0.646734  map@5=0.707844  map@10=0.720335  map@20=0.723104
mrr@1=0.618145  mrr@2=0.697016  mrr@5=0.740148  mrr@10=0.745909  mrr@20=0.747053
f1@1=0.541549  f1@2=0.522174  f1@5=0.372048  f1@10=0.226817  f1@20=0.125835

[TEST]
recall@1=0.504519  recall@2=0.698778  recall@5=0.903319  recall@10=0.961701  recall@20=0.983629
precision@1=0.613805  precision@2=0.453004  precision@5=0.245747  precision@10=0.132708  precision@20=0.068412
ndcg@1=0.613805  ndcg@2=0.679965  ndcg@5=0.767176  ndcg@10=0.788919  ndcg@20=0.795371
hit_rate@1=0.613805  hit_rate@2=0.781492  hit_rate@5=0.937822  hit_rate@10=0.976724  hit_rate@20=0.990335
map@1=0.613805  map@2=0.649686  map@5=0.708236  map@10=0.720740  map@20=0.723285
mrr@1=0.613805  mrr@2=0.697648  mrr@5=0.739559  mrr@10=0.745111  mrr@20=0.746113
f1@1=0.536683  f1@2=0.528148  f1@5=0.372503  f1@10=0.227114  f1@20=0.125725

Saved new best checkpoint at epoch 8

Epoch 9/100: 100%|██████████| 820/820 [00:11<00:00, 74.44it/s, bpr=0.0383, c=2.64, loss=0.144]

[VAL]
recall@1=0.505354  recall@2=0.697158  recall@5=0.906900  recall@10=0.960819  recall@20=0.984253
precision@1=0.613065  precision@2=0.450927  precision@5=0.246742  precision@10=0.132685  precision@20=0.068536
ndcg@1=0.613065  ndcg@2=0.678590  ndcg@5=0.768277  ndcg@10=0.788562  ndcg@20=0.795478
hit_rate@1=0.613065  hit_rate@2=0.780726  hit_rate@5=0.941532  hit_rate@10=0.977097  hit_rate@20=0.991613
map@1=0.613065  map@2=0.648206  map@5=0.708488  map@10=0.720329  map@20=0.723090
mrr@1=0.613065  mrr@2=0.696895  mrr@5=0.739782  mrr@10=0.744917  mrr@20=0.745984
f1@1=0.537081  f1@2=0.526196  f1@5=0.373762  f1@10=0.226918  f1@20=0.125908

[TEST]
recall@1=0.513026  recall@2=0.704297  recall@5=0.910174  recall@10=0.962385  recall@20=0.984327
precision@1=0.623550  precision@2=0.455743  precision@5=0.247423  precision@10=0.132861  precision@20=0.068472
ndcg@1=0.623550  ndcg@2=0.686563  ndcg@5=0.774469  ndcg@10=0.794045  ndcg@20=0.800465
hit_rate@1=0.623550  hit_rate@2=0.787210  hit_rate@5=0.944588  hit_rate@10=0.976885  hit_rate@20=0.990818
map@1=0.623550  map@2=0.656512  map@5=0.715642  map@10=0.727134  map@20=0.729644
mrr@1=0.623550  mrr@2=0.705380  mrr@5=0.747360  mrr@10=0.751956  mrr@20=0.752979
f1@1=0.545606  f1@2=0.531926  f1@5=0.375078  f1@10=0.227323  f1@20=0.125829

Epoch 10/100: 100%|██████████| 820/820 [00:10<00:00, 74.65it/s, bpr=0.0379, c=2.68, loss=0.145]

[VAL]
recall@1=0.504406  recall@2=0.696293  recall@5=0.906115  recall@10=0.960078  recall@20=0.983166
precision@1=0.612661  precision@2=0.449597  precision@5=0.246339  precision@10=0.132556  precision@20=0.068431
ndcg@1=0.612661  ndcg@2=0.677406  ndcg@5=0.767187  ndcg@10=0.787493  ndcg@20=0.794315
hit_rate@1=0.612661  hit_rate@2=0.781048  hit_rate@5=0.941371  hit_rate@10=0.976774  hit_rate@20=0.991290
map@1=0.612661  map@2=0.646512  map@5=0.706993  map@10=0.718876  map@20=0.721599
mrr@1=0.612661  mrr@2=0.696855  mrr@5=0.739399  mrr@10=0.744488  mrr@20=0.745550
f1@1=0.536225  f1@2=0.525124  f1@5=0.373249  f1@10=0.226705  f1@20=0.125711

[TEST]
recall@1=0.510987  recall@2=0.702581  recall@5=0.908242  recall@10=0.961494  recall@20=0.984021
precision@1=0.620651  precision@2=0.454494  precision@5=0.246827  precision@10=0.132748  precision@20=0.068436
ndcg@1=0.620651  ndcg@2=0.684572  ndcg@5=0.772218  ndcg@10=0.792185  ndcg@20=0.798764
hit_rate@1=0.620651  hit_rate@2=0.786163  hit_rate@5=0.942574  hit_rate@10=0.976724  hit_rate@20=0.991060
map@1=0.620651  map@2=0.654297  map@5=0.713305  map@10=0.724941  map@20=0.727506
mrr@1=0.620651  mrr@2=0.703407  mrr@5=0.744968  mrr@10=0.749821  mrr@20=0.750878
f1@1=0.543279  f1@2=0.530457  f1@5=0.374221  f1@10=0.227114  f1@20=0.125757

Epoch 11/100: 100%|██████████| 820/820 [00:11<00:00, 74.34it/s, bpr=0.0438, c=2.53, loss=0.145]

[VAL]
recall@1=0.510894  recall@2=0.705071  recall@5=0.910790  recall@10=0.961601  recall@20=0.983904
precision@1=0.619274  precision@2=0.454879  precision@5=0.247919  precision@10=0.132685  precision@20=0.068480
ndcg@1=0.619274  ndcg@2=0.685683  ndcg@5=0.773730  ndcg@10=0.792695  ndcg@20=0.799330
hit_rate@1=0.619274  hit_rate@2=0.789355  hit_rate@5=0.944677  hit_rate@10=0.977984  hit_rate@20=0.991532
map@1=0.619274  map@2=0.654798  map@5=0.714481  map@10=0.725515  map@20=0.728188
mrr@1=0.619274  mrr@2=0.704315  mrr@5=0.745633  mrr@10=0.750359  mrr@20=0.751351
f1@1=0.542731  f1@2=0.531502  f1@5=0.375488  f1@10=0.226972  f1@20=0.125813

[TEST]
recall@1=0.510790  recall@2=0.709148  recall@5=0.914048  recall@10=0.962592  recall@20=0.984724
precision@1=0.620490  precision@2=0.458723  precision@5=0.248599  precision@10=0.132901  precision@20=0.068460
ndcg@1=0.620490  ndcg@2=0.688995  ndcg@5=0.776268  ndcg@10=0.794487  ndcg@20=0.800916
hit_rate@1=0.620490  hit_rate@2=0.791318  hit_rate@5=0.946923  hit_rate@10=0.977126  hit_rate@20=0.991463
map@1=0.620490  map@2=0.658404  map@5=0.717217  map@10=0.727887  map@20=0.730377
mrr@1=0.620490  mrr@2=0.705904  mrr@5=0.747186  mrr@10=0.751501  mrr@20=0.752538
f1@1=0.543097  f1@2=0.535454  f1@5=0.376806  f1@10=0.227414  f1@20=0.125829

Epoch 12/100: 100%|██████████| 820/820 [00:10<00:00, 74.78it/s, bpr=0.0563, c=2.66, loss=0.163]

[VAL]
recall@1=0.513516  recall@2=0.707260  recall@5=0.910097  recall@10=0.961524  recall@20=0.983470
precision@1=0.622177  precision@2=0.456694  precision@5=0.247355  precision@10=0.132750  precision@20=0.068448
ndcg@1=0.622177  ndcg@2=0.688271  ndcg@5=0.774520  ndcg@10=0.793888  ndcg@20=0.800359
hit_rate@1=0.622177  hit_rate@2=0.790968  hit_rate@5=0.944677  hit_rate@10=0.977258  hit_rate@20=0.991210
map@1=0.622177  map@2=0.657702  map@5=0.715709  map@10=0.727119  map@20=0.729685
mrr@1=0.622177  mrr@2=0.706573  mrr@5=0.747329  mrr@10=0.751968  mrr@20=0.752977
f1@1=0.545483  f1@2=0.533424  f1@5=0.374816  f1@10=0.227064  f1@20=0.125758

[TEST]
recall@1=0.515535  recall@2=0.712862  recall@5=0.912438  recall@10=0.962246  recall@20=0.984847
precision@1=0.626530  precision@2=0.460776  precision@5=0.248148  precision@10=0.132813  precision@20=0.068500
ndcg@1=0.626530  ndcg@2=0.693302  ndcg@5=0.778102  ndcg@10=0.796752  ndcg@20=0.803371
hit_rate@1=0.626530  hit_rate@2=0.795989  hit_rate@5=0.946198  hit_rate@10=0.977126  hit_rate@20=0.991382
map@1=0.626530  map@2=0.662552  map@5=0.719872  map@10=0.730769  map@20=0.733362
mrr@1=0.626530  mrr@2=0.711260  mrr@5=0.751083  mrr@10=0.755466  mrr@20=0.756503
f1@1=0.548236  f1@2=0.538036  f1@5=0.376121  f1@10=0.227252  f1@20=0.125890

Epoch 13/100: 100%|██████████| 820/820 [00:11<00:00, 73.41it/s, bpr=0.0434, c=2.55, loss=0.145]

[VAL]
recall@1=0.526822  recall@2=0.722928  recall@5=0.914134  recall@10=0.963273  recall@20=0.984226
precision@1=0.636371  precision@2=0.465444  precision@5=0.248629  precision@10=0.133105  precision@20=0.068528
ndcg@1=0.636371  ndcg@2=0.703502  ndcg@5=0.784630  ndcg@10=0.803147  ndcg@20=0.809320
hit_rate@1=0.636371  hit_rate@2=0.807823  hit_rate@5=0.947661  hit_rate@10=0.978387  hit_rate@20=0.991613
map@1=0.636371  map@2=0.672460  map@5=0.727783  map@10=0.738733  map@20=0.741177
mrr@1=0.636371  mrr@2=0.722097  mrr@5=0.759235  mrr@10=0.763619  mrr@20=0.764593
f1@1=0.559080  f1@2=0.544418  f1@5=0.376668  f1@10=0.227612  f1@20=0.125891

[TEST]
recall@1=0.526373  recall@2=0.727708  recall@5=0.915810  recall@10=0.964738  recall@20=0.984569
precision@1=0.636195  precision@2=0.468549  precision@5=0.249001  precision@10=0.133151  precision@20=0.068476
ndcg@1=0.636195  ndcg@2=0.706579  ndcg@5=0.786744  ndcg@10=0.805127  ndcg@20=0.810984
hit_rate@1=0.636195  hit_rate@2=0.810889  hit_rate@5=0.948534  hit_rate@10=0.979140  hit_rate@20=0.991221
map@1=0.636195  map@2=0.675419  map@5=0.730408  map@10=0.741199  map@20=0.743523
mrr@1=0.636195  mrr@2=0.723542  mrr@5=0.760442  mrr@10=0.764800  mrr@20=0.765695
f1@1=0.558765  f1@2=0.548197  f1@5=0.377464  f1@10=0.227845  f1@20=0.125840

Saved new best checkpoint at epoch 13

Epoch 14/100: 100%|██████████| 820/820 [00:11<00:00, 73.96it/s, bpr=0.0442, c=2.66, loss=0.15]

[VAL]
recall@1=0.512506  recall@2=0.705519  recall@5=0.912833  recall@10=0.962032  recall@20=0.985528
precision@1=0.621129  precision@2=0.456129  precision@5=0.248435  precision@10=0.132742  precision@20=0.068633
ndcg@1=0.621129  ndcg@2=0.686893  ndcg@5=0.775148  ndcg@10=0.793535  ndcg@20=0.800511
hit_rate@1=0.621129  hit_rate@2=0.789355  hit_rate@5=0.945968  hit_rate@10=0.978145  hit_rate@20=0.992823
map@1=0.621129  map@2=0.656431  map@5=0.716017  map@10=0.726718  map@20=0.729507
mrr@1=0.621129  mrr@2=0.705242  mrr@5=0.746556  mrr@10=0.751108  mrr@20=0.752175
f1@1=0.544532  f1@2=0.532444  f1@5=0.376267  f1@10=0.227085  f1@20=0.126073

[TEST]
recall@1=0.511772  recall@2=0.712911  recall@5=0.914737  recall@10=0.964095  recall@20=0.985308
precision@1=0.622986  precision@2=0.461380  precision@5=0.248760  precision@10=0.133038  precision@20=0.068504
ndcg@1=0.622986  ndcg@2=0.692116  ndcg@5=0.777550  ndcg@10=0.796025  ndcg@20=0.802273
hit_rate@1=0.622986  hit_rate@2=0.794781  hit_rate@5=0.947568  hit_rate@10=0.979220  hit_rate@20=0.992026
map@1=0.622986  map@2=0.661324  map@5=0.718657  map@10=0.729415  map@20=0.731898
mrr@1=0.622986  mrr@2=0.708884  mrr@5=0.749154  mrr@10=0.753626  mrr@20=0.754565
f1@1=0.544467  f1@2=0.538491  f1@5=0.377060  f1@10=0.227639  f1@20=0.125905

Epoch 15/100: 100%|██████████| 820/820 [00:11<00:00, 73.43it/s, bpr=0.0601, c=2.54, loss=0.162]

[VAL]
recall@1=0.514815  recall@2=0.711326  recall@5=0.915208  recall@10=0.962330  recall@20=0.984188
precision@1=0.623548  precision@2=0.458710  precision@5=0.248903  precision@10=0.132895  precision@20=0.068548
ndcg@1=0.623548  ndcg@2=0.691322  ndcg@5=0.778191  ndcg@10=0.796029  ndcg@20=0.802516
hit_rate@1=0.623548  hit_rate@2=0.794919  hit_rate@5=0.948952  hit_rate@10=0.978145  hit_rate@20=0.991613
map@1=0.623548  map@2=0.660383  map@5=0.718972  map@10=0.729626  map@20=0.732225
mrr@1=0.623548  mrr@2=0.709234  mrr@5=0.750094  mrr@10=0.754260  mrr@20=0.755253
f1@1=0.546866  f1@2=0.536117  f1@5=0.377061  f1@10=0.227277  f1@20=0.125924

[TEST]
recall@1=0.521525  recall@2=0.716746  recall@5=0.916478  recall@10=0.965270  recall@20=0.985424
precision@1=0.632651  precision@2=0.463032  precision@5=0.249114  precision@10=0.133288  precision@20=0.068541
ndcg@1=0.632651  ndcg@2=0.698125  ndcg@5=0.782893  ndcg@10=0.801313  ndcg@20=0.807187
hit_rate@1=0.632651  hit_rate@2=0.799291  hit_rate@5=0.949420  hit_rate@10=0.979220  hit_rate@20=0.992107
map@1=0.632651  map@2=0.667848  map@5=0.725020  map@10=0.735921  map@20=0.738206
mrr@1=0.632651  mrr@2=0.715971  mrr@5=0.755792  mrr@10=0.760064  mrr@20=0.760992
f1@1=0.554269  f1@2=0.540775  f1@5=0.377687  f1@10=0.228066  f1@20=0.125951

Epoch 16/100: 100%|██████████| 820/820 [00:11<00:00, 74.24it/s, bpr=0.0346, c=2.68, loss=0.142]

[VAL]
recall@1=0.502755  recall@2=0.698416  recall@5=0.912334  recall@10=0.961970  recall@20=0.984109
precision@1=0.611855  precision@2=0.451774  precision@5=0.248097  precision@10=0.132823  precision@20=0.068504
ndcg@1=0.611855  ndcg@2=0.678625  ndcg@5=0.769482  ndcg@10=0.788171  ndcg@20=0.794694
hit_rate@1=0.611855  hit_rate@2=0.781694  hit_rate@5=0.946532  hit_rate@10=0.977903  hit_rate@20=0.991532
map@1=0.611855  map@2=0.647742  map@5=0.708335  map@10=0.719374  map@20=0.721980
mrr@1=0.611855  mrr@2=0.696734  mrr@5=0.739895  mrr@10=0.744307  mrr@20=0.745281
f1@1=0.534929  f1@2=0.527157  f1@5=0.375889  f1@10=0.227161  f1@20=0.125857

[TEST]
recall@1=0.505030  recall@2=0.702049  recall@5=0.914343  recall@10=0.964176  recall@20=0.984820
precision@1=0.616382  precision@2=0.454816  precision@5=0.248599  precision@10=0.133054  precision@20=0.068484
ndcg@1=0.616382  ndcg@2=0.682499  ndcg@5=0.772789  ndcg@10=0.791507  ndcg@20=0.797587
hit_rate@1=0.616382  hit_rate@2=0.783908  hit_rate@5=0.947568  hit_rate@10=0.979140  hit_rate@20=0.991704
map@1=0.616382  map@2=0.652001  map@5=0.712358  map@10=0.723302  map@20=0.725731
mrr@1=0.616382  mrr@2=0.700185  mrr@5=0.743265  mrr@10=0.747820  mrr@20=0.748734
f1@1=0.537782  f1@2=0.530496  f1@5=0.376835  f1@10=0.227665  f1@20=0.125858

Epoch 17/100: 100%|██████████| 820/820 [00:11<00:00, 74.13it/s, bpr=0.0305, c=2.69, loss=0.138]

[VAL]
recall@1=0.512030  recall@2=0.705806  recall@5=0.911197  recall@10=0.962216  recall@20=0.985312
precision@1=0.620323  precision@2=0.455645  precision@5=0.247823  precision@10=0.132847  precision@20=0.068613
ndcg@1=0.620323  ndcg@2=0.686690  ndcg@5=0.773909  ndcg@10=0.793102  ndcg@20=0.799927
hit_rate@1=0.620323  hit_rate@2=0.788952  hit_rate@5=0.944758  hit_rate@10=0.978065  hit_rate@20=0.992097
map@1=0.620323  map@2=0.656210  map@5=0.714707  map@10=0.725990  map@20=0.728700
mrr@1=0.620323  mrr@2=0.704637  mrr@5=0.745652  mrr@10=0.750419  mrr@20=0.751448
f1@1=0.543898  f1@2=0.532214  f1@5=0.375483  f1@10=0.227214  f1@20=0.126047

[TEST]
recall@1=0.517107  recall@2=0.712493  recall@5=0.915535  recall@10=0.964861  recall@20=0.985508
precision@1=0.628222  precision@2=0.460817  precision@5=0.249050  precision@10=0.133159  precision@20=0.068512
ndcg@1=0.628222  ndcg@2=0.693757  ndcg@5=0.779833  ndcg@10=0.798250  ndcg@20=0.804324
hit_rate@1=0.628222  hit_rate@2=0.793734  hit_rate@5=0.948051  hit_rate@10=0.979220  hit_rate@20=0.992026
map@1=0.628222  map@2=0.663781  map@5=0.721489  map@10=0.732215  map@20=0.734613
mrr@1=0.628222  mrr@2=0.710978  mrr@5=0.751730  mrr@10=0.756151  mrr@20=0.757100
f1@1=0.549830  f1@2=0.537937  f1@5=0.377463  f1@10=0.227852  f1@20=0.125927

Epoch 18/100: 100%|██████████| 820/820 [00:11<00:00, 74.28it/s, bpr=0.0281, c=2.76, loss=0.139]

[VAL]
recall@1=0.506286  recall@2=0.696464  recall@5=0.909228  recall@10=0.959516  recall@20=0.984046
precision@1=0.614274  precision@2=0.450121  precision@5=0.247113  precision@10=0.132516  precision@20=0.068536
ndcg@1=0.614274  ndcg@2=0.678265  ndcg@5=0.768803  ndcg@10=0.787815  ndcg@20=0.795037
hit_rate@1=0.614274  hit_rate@2=0.778790  hit_rate@5=0.943387  hit_rate@10=0.975887  hit_rate@20=0.991452
map@1=0.614274  map@2=0.648286  map@5=0.708689  map@10=0.719843  map@20=0.722705
mrr@1=0.614274  mrr@2=0.696532  mrr@5=0.739634  mrr@10=0.744327  mrr@20=0.745465
f1@1=0.538093  f1@2=0.525541  f1@5=0.374470  f1@10=0.226597  f1@20=0.125887

[TEST]
recall@1=0.507286  recall@2=0.703259  recall@5=0.910939  recall@10=0.962466  recall@20=0.985073
precision@1=0.617107  precision@2=0.455179  precision@5=0.247664  precision@10=0.132780  precision@20=0.068500
ndcg@1=0.617107  ndcg@2=0.683841  ndcg@5=0.772046  ndcg@10=0.791251  ndcg@20=0.797885
hit_rate@1=0.617107  hit_rate@2=0.784069  hit_rate@5=0.943863  hit_rate@10=0.977851  hit_rate@20=0.991785
map@1=0.617107  map@2=0.653773  map@5=0.712653  map@10=0.723702  map@20=0.726317
mrr@1=0.617107  mrr@2=0.700588  mrr@5=0.742779  mrr@10=0.747606  mrr@20=0.748619
f1@1=0.539591  f1@2=0.531095  f1@5=0.375412  f1@10=0.227237  f1@20=0.125887

Epoch 19/100: 100%|██████████| 820/820 [00:10<00:00, 74.75it/s, bpr=0.0415, c=2.65, loss=0.147]

[VAL]
recall@1=0.519729  recall@2=0.719751  recall@5=0.914891  recall@10=0.962737  recall@20=0.985012
precision@1=0.629677  precision@2=0.463589  precision@5=0.248758  precision@10=0.132887  precision@20=0.068560
ndcg@1=0.629677  ndcg@2=0.698889  ndcg@5=0.781590  ndcg@10=0.799638  ndcg@20=0.806189
hit_rate@1=0.629677  hit_rate@2=0.803790  hit_rate@5=0.948629  hit_rate@10=0.978306  hit_rate@20=0.992177
map@1=0.629677  map@2=0.667500  map@5=0.723412  map@10=0.734191  map@20=0.736764
mrr@1=0.629677  mrr@2=0.716734  mrr@5=0.755138  mrr@10=0.759364  mrr@20=0.760363
f1@1=0.552030  f1@2=0.542144  f1@5=0.376911  f1@10=0.227288  f1@20=0.125953

[TEST]
recall@1=0.524929  recall@2=0.723420  recall@5=0.916499  recall@10=0.964077  recall@20=0.985001
precision@1=0.635470  precision@2=0.466495  precision@5=0.249130  precision@10=0.133046  precision@20=0.068500
ndcg@1=0.635470  ndcg@2=0.703500  ndcg@5=0.785253  ndcg@10=0.803167  ndcg@20=0.809315
hit_rate@1=0.635470  hit_rate@2=0.805251  hit_rate@5=0.949098  hit_rate@10=0.978737  hit_rate@20=0.991704
map@1=0.635470  map@2=0.673043  map@5=0.728348  map@10=0.738936  map@20=0.741358
mrr@1=0.635470  mrr@2=0.720361  mrr@5=0.758447  mrr@10=0.762660  mrr@20=0.763603
f1@1=0.557495  f1@2=0.545388  f1@5=0.377732  f1@10=0.227689  f1@20=0.125886

Epoch 20/100: 100%|██████████| 820/820 [00:11<00:00, 74.39it/s, bpr=0.0222, c=2.71, loss=0.13]

[VAL]
recall@1=0.531058  recall@2=0.735019  recall@5=0.919511  recall@10=0.963651  recall@20=0.985511
precision@1=0.641774  precision@2=0.472742  precision@5=0.250161  precision@10=0.133121  precision@20=0.068621
ndcg@1=0.641774  ndcg@2=0.713274  ndcg@5=0.791871  ndcg@10=0.808663  ndcg@20=0.815060
hit_rate@1=0.641774  hit_rate@2=0.819839  hit_rate@5=0.951694  hit_rate@10=0.978548  hit_rate@20=0.992742
map@1=0.641774  map@2=0.681472  map@5=0.735763  map@10=0.745874  map@20=0.748361
mrr@1=0.641774  mrr@2=0.730806  mrr@5=0.766515  mrr@10=0.770375  mrr@20=0.771396
f1@1=0.563577  f1@2=0.553336  f1@5=0.378964  f1@10=0.227652  f1@20=0.126066

[TEST]
recall@1=0.534188  recall@2=0.739547  recall@5=0.920531  recall@10=0.965630  recall@20=0.985649
precision@1=0.645538  precision@2=0.475757  precision@5=0.250387  precision@10=0.133255  precision@20=0.068541
ndcg@1=0.645538  ndcg@2=0.717541  ndcg@5=0.794733  ndcg@10=0.811707  ndcg@20=0.817568
hit_rate@1=0.645538  hit_rate@2=0.822729  hit_rate@5=0.951595  hit_rate@10=0.980106  hit_rate@20=0.992188
map@1=0.645538  map@2=0.686030  map@5=0.739563  map@10=0.749560  map@20=0.751870
mrr@1=0.645538  mrr@2=0.734133  mrr@5=0.769090  mrr@10=0.773178  mrr@20=0.774027
f1@1=0.567025  f1@2=0.556859  f1@5=0.379574  f1@10=0.228038  f1@20=0.125959

Saved new best checkpoint at epoch 20

Epoch 21/100: 100%|██████████| 820/820 [00:11<00:00, 74.12it/s, bpr=0.0313, c=2.65, loss=0.137]

[VAL]
recall@1=0.521717  recall@2=0.717809  recall@5=0.916777  recall@10=0.962500  recall@20=0.984355
precision@1=0.632419  precision@2=0.462581  precision@5=0.249226  precision@10=0.132895  precision@20=0.068524
ndcg@1=0.632419  ndcg@2=0.698415  ndcg@5=0.783035  ndcg@10=0.800406  ndcg@20=0.806846
hit_rate@1=0.632419  hit_rate@2=0.801532  hit_rate@5=0.950161  hit_rate@10=0.978387  hit_rate@20=0.991935
map@1=0.632419  map@2=0.667520  map@5=0.724796  map@10=0.735188  map@20=0.737748
mrr@1=0.632419  mrr@2=0.716976  mrr@5=0.756560  mrr@10=0.760630  mrr@20=0.761607
f1@1=0.554345  f1@2=0.540808  f1@5=0.377653  f1@10=0.227296  f1@20=0.125880

[TEST]
recall@1=0.520335  recall@2=0.720710  recall@5=0.917662  recall@10=0.964316  recall@20=0.985781
precision@1=0.629913  precision@2=0.464965  precision@5=0.249468  precision@10=0.133135  precision@20=0.068545
ndcg@1=0.629913  ndcg@2=0.699834  ndcg@5=0.783700  ndcg@10=0.801304  ndcg@20=0.807569
hit_rate@1=0.629913  hit_rate@2=0.802755  hit_rate@5=0.950709  hit_rate@10=0.978657  hit_rate@20=0.992268
map@1=0.629913  map@2=0.669076  map@5=0.725826  map@10=0.736295  map@20=0.738745
mrr@1=0.629913  mrr@2=0.716334  mrr@5=0.755689  mrr@10=0.759680  mrr@20=0.760682
f1@1=0.552681  f1@2=0.543507  f1@5=0.378208  f1@10=0.227810  f1@20=0.125977

Epoch 22/100: 100%|██████████| 820/820 [00:11<00:00, 74.19it/s, bpr=0.0347, c=2.55, loss=0.137]

[VAL]
recall@1=0.512558  recall@2=0.708916  recall@5=0.915858  recall@10=0.962739  recall@20=0.983841
precision@1=0.623468  precision@2=0.458468  precision@5=0.248935  precision@10=0.132960  precision@20=0.068456
ndcg@1=0.623468  ndcg@2=0.689642  ndcg@5=0.777324  ndcg@10=0.795170  ndcg@20=0.801325
hit_rate@1=0.623468  hit_rate@2=0.793629  hit_rate@5=0.949435  hit_rate@10=0.977742  hit_rate@20=0.991613
map@1=0.623468  map@2=0.658548  map@5=0.717438  map@10=0.728230  map@20=0.730604
mrr@1=0.623468  mrr@2=0.708548  mrr@5=0.749715  mrr@10=0.753784  mrr@20=0.754775
f1@1=0.545194  f1@2=0.535057  f1@5=0.377226  f1@10=0.227413  f1@20=0.125771

[TEST]
recall@1=0.509805  recall@2=0.710898  recall@5=0.918087  recall@10=0.965526  recall@20=0.984787
precision@1=0.619604  precision@2=0.460011  precision@5=0.249501  precision@10=0.133239  precision@20=0.068468
ndcg@1=0.619604  ndcg@2=0.689866  ndcg@5=0.778081  ndcg@10=0.795918  ndcg@20=0.801578
hit_rate@1=0.619604  hit_rate@2=0.793976  hit_rate@5=0.949984  hit_rate@10=0.979865  hit_rate@20=0.991543
map@1=0.619604  map@2=0.658767  map@5=0.718390  map@10=0.728861  map@20=0.731104
mrr@1=0.619604  mrr@2=0.706790  mrr@5=0.748135  mrr@10=0.752341  mrr@20=0.753179
f1@1=0.542128  f1@2=0.536888  f1@5=0.378293  f1@10=0.228001  f1@20=0.125836

Epoch 23/100: 100%|██████████| 820/820 [00:11<00:00, 73.95it/s, bpr=0.0731, c=2.59, loss=0.177]

[VAL]
recall@1=0.517229  recall@2=0.715471  recall@5=0.915744  recall@10=0.962815  recall@20=0.983985
precision@1=0.628065  precision@2=0.461532  precision@5=0.249113  precision@10=0.132887  precision@20=0.068496
ndcg@1=0.628065  ndcg@2=0.695355  ndcg@5=0.780305  ndcg@10=0.798022  ndcg@20=0.804292
hit_rate@1=0.628065  hit_rate@2=0.799758  hit_rate@5=0.948710  hit_rate@10=0.978468  hit_rate@20=0.991452
map@1=0.628065  map@2=0.664073  map@5=0.721596  map@10=0.732080  map@20=0.734592
mrr@1=0.628065  mrr@2=0.713911  mrr@5=0.753223  mrr@10=0.757425  mrr@20=0.758369
f1@1=0.549866  f1@2=0.539362  f1@5=0.377397  f1@10=0.227304  f1@20=0.125828

[TEST]
recall@1=0.514961  recall@2=0.719706  recall@5=0.918214  recall@10=0.965625  recall@20=0.985374
precision@1=0.624758  precision@2=0.464763  precision@5=0.249646  precision@10=0.133223  precision@20=0.068504
ndcg@1=0.624758  ndcg@2=0.697360  ndcg@5=0.781892  ndcg@10=0.799656  ndcg@20=0.805430
hit_rate@1=0.624758  hit_rate@2=0.802916  hit_rate@5=0.950628  hit_rate@10=0.980026  hit_rate@20=0.992268
map@1=0.624758  map@2=0.665814  map@5=0.723238  map@10=0.733679  map@20=0.735946
mrr@1=0.624758  mrr@2=0.713837  mrr@5=0.753146  mrr@10=0.757293  mrr@20=0.758158
f1@1=0.547304  f1@2=0.543044  f1@5=0.378480  f1@10=0.227997  f1@20=0.125901

Epoch 24/100: 100%|██████████| 820/820 [00:11<00:00, 73.55it/s, bpr=0.076, c=2.6, loss=0.18]

[VAL]
recall@1=0.518346  recall@2=0.714886  recall@5=0.915818  recall@10=0.962501  recall@20=0.985417
precision@1=0.627903  precision@2=0.461169  precision@5=0.249097  precision@10=0.132911  precision@20=0.068653
ndcg@1=0.627903  ndcg@2=0.695193  ndcg@5=0.780561  ndcg@10=0.798220  ndcg@20=0.805001
hit_rate@1=0.627903  hit_rate@2=0.797419  hit_rate@5=0.948710  hit_rate@10=0.977984  hit_rate@20=0.992500
map@1=0.627903  map@2=0.664597  map@5=0.722131  map@10=0.732634  map@20=0.735329
mrr@1=0.627903  mrr@2=0.712661  mrr@5=0.752767  mrr@10=0.756974  mrr@20=0.758040
f1@1=0.550666  f1@2=0.538890  f1@5=0.377353  f1@10=0.227319  f1@20=0.126099

[TEST]
recall@1=0.518241  recall@2=0.720152  recall@5=0.919220  recall@10=0.965028  recall@20=0.985332
precision@1=0.629108  precision@2=0.464441  precision@5=0.249903  precision@10=0.133247  precision@20=0.068512
ndcg@1=0.629108  ndcg@2=0.698833  ndcg@5=0.783742  ndcg@10=0.801023  ndcg@20=0.806961
hit_rate@1=0.629108  hit_rate@2=0.802996  hit_rate@5=0.951836  hit_rate@10=0.979543  hit_rate@20=0.991946
map@1=0.629108  map@2=0.667566  map@5=0.725273  map@10=0.735510  map@20=0.737861
mrr@1=0.629108  mrr@2=0.716052  mrr@5=0.755690  mrr@10=0.759633  mrr@20=0.760547
f1@1=0.550901  f1@2=0.542955  f1@5=0.378857  f1@10=0.227990  f1@20=0.125911

Epoch 25/100: 100%|██████████| 820/820 [00:11<00:00, 74.12it/s, bpr=0.0258, c=2.71, loss=0.134]

[VAL]
recall@1=0.510186  recall@2=0.709939  recall@5=0.913473  recall@10=0.961003  recall@20=0.984139
precision@1=0.618710  precision@2=0.458024  precision@5=0.248484  precision@10=0.132782  precision@20=0.068528
ndcg@1=0.618710  ndcg@2=0.688823  ndcg@5=0.775315  ndcg@10=0.793299  ndcg@20=0.800057
hit_rate@1=0.618710  hit_rate@2=0.793871  hit_rate@5=0.946774  hit_rate@10=0.976855  hit_rate@20=0.991613
map@1=0.618710  map@2=0.657419  map@5=0.715807  map@10=0.726468  map@20=0.729121
mrr@1=0.618710  mrr@2=0.706290  mrr@5=0.746618  mrr@10=0.750923  mrr@20=0.751989
f1@1=0.542122  f1@2=0.535130  f1@5=0.376416  f1@10=0.227038  f1@20=0.125880

[TEST]
recall@1=0.516710  recall@2=0.713041  recall@5=0.916309  recall@10=0.963750  recall@20=0.985758
precision@1=0.628141  precision@2=0.460333  precision@5=0.249259  precision@10=0.133030  precision@20=0.068561
ndcg@1=0.628141  ndcg@2=0.693694  ndcg@5=0.780262  ndcg@10=0.798027  ndcg@20=0.804468
hit_rate@1=0.628141  hit_rate@2=0.795828  hit_rate@5=0.949017  hit_rate@10=0.978979  hit_rate@20=0.992751
map@1=0.628141  map@2=0.663015  map@5=0.721501  map@10=0.731866  map@20=0.734413
mrr@1=0.628141  mrr@2=0.711985  mrr@5=0.752481  mrr@10=0.756728  mrr@20=0.757719
f1@1=0.549543  f1@2=0.537838  f1@5=0.377773  f1@10=0.227627  f1@20=0.125990

Epoch 26/100: 100%|██████████| 820/820 [00:11<00:00, 73.46it/s, bpr=0.032, c=2.74, loss=0.142]

[VAL]
recall@1=0.526068  recall@2=0.729954  recall@5=0.918136  recall@10=0.962778  recall@20=0.984570
precision@1=0.635968  precision@2=0.469556  precision@5=0.249903  precision@10=0.133024  precision@20=0.068544
ndcg@1=0.635968  ndcg@2=0.707888  ndcg@5=0.788135  ndcg@10=0.805060  ndcg@20=0.811420
hit_rate@1=0.635968  hit_rate@2=0.814274  hit_rate@5=0.950645  hit_rate@10=0.977984  hit_rate@20=0.992016
map@1=0.635968  map@2=0.676069  map@5=0.731247  map@10=0.741408  map@20=0.743901
mrr@1=0.635968  mrr@2=0.725121  mrr@5=0.761802  mrr@10=0.765732  mrr@20=0.766737
f1@1=0.558427  f1@2=0.549517  f1@5=0.378494  f1@10=0.227476  f1@20=0.125919

[TEST]
recall@1=0.528576  recall@2=0.733753  recall@5=0.920643  recall@10=0.965550  recall@20=0.985925
precision@1=0.640947  precision@2=0.472294  precision@5=0.250483  precision@10=0.133288  precision@20=0.068565
ndcg@1=0.640947  ndcg@2=0.711794  ndcg@5=0.791455  ndcg@10=0.808340  ndcg@20=0.814261
hit_rate@1=0.640947  hit_rate@2=0.817010  hit_rate@5=0.952159  hit_rate@10=0.979704  hit_rate@20=0.992671
map@1=0.640947  map@2=0.680110  map@5=0.735005  map@10=0.744997  map@20=0.747295
mrr@1=0.640947  mrr@2=0.728979  mrr@5=0.765399  mrr@10=0.769289  mrr@20=0.770198
f1@1=0.561744  f1@2=0.552657  f1@5=0.379642  f1@10=0.228087  f1@20=0.125998

Epoch 27/100: 100%|██████████| 820/820 [00:11<00:00, 74.09it/s, bpr=0.0438, c=2.64, loss=0.149]

[VAL]
recall@1=0.520723  recall@2=0.724485  recall@5=0.916111  recall@10=0.963262  recall@20=0.985260
precision@1=0.630645  precision@2=0.466774  precision@5=0.249161  precision@10=0.132992  precision@20=0.068613
ndcg@1=0.630645  ndcg@2=0.702432  ndcg@5=0.783770  ndcg@10=0.801571  ndcg@20=0.808058
hit_rate@1=0.630645  hit_rate@2=0.809194  hit_rate@5=0.949597  hit_rate@10=0.979032  hit_rate@20=0.992419
map@1=0.630645  map@2=0.670524  map@5=0.725914  map@10=0.736547  map@20=0.739125
mrr@1=0.630645  mrr@2=0.719919  mrr@5=0.757359  mrr@10=0.761561  mrr@20=0.762525
f1@1=0.553112  f1@2=0.545839  f1@5=0.377477  f1@10=0.227468  f1@20=0.126023

[TEST]
recall@1=0.526115  recall@2=0.727570  recall@5=0.916960  recall@10=0.965298  recall@20=0.985451
precision@1=0.638128  precision@2=0.468831  precision@5=0.249259  precision@10=0.133280  precision@20=0.068476
ndcg@1=0.638128  ndcg@2=0.706804  ndcg@5=0.787315  ndcg@10=0.805550  ndcg@20=0.811386
hit_rate@1=0.638128  hit_rate@2=0.810567  hit_rate@5=0.949903  hit_rate@10=0.979784  hit_rate@20=0.992590
map@1=0.638128  map@2=0.675640  map@5=0.730484  map@10=0.741313  map@20=0.743559
mrr@1=0.638128  mrr@2=0.724348  mrr@5=0.761731  mrr@10=0.765991  mrr@20=0.766904
f1@1=0.559097  f1@2=0.548322  f1@5=0.377902  f1@10=0.228033  f1@20=0.125875

Epoch 28/100: 100%|██████████| 820/820 [00:11<00:00, 73.40it/s, bpr=0.0277, c=2.67, loss=0.135]

[VAL]
recall@1=0.517507  recall@2=0.718481  recall@5=0.916508  recall@10=0.963345  recall@20=0.985491
precision@1=0.627258  precision@2=0.463387  precision@5=0.249339  precision@10=0.132992  precision@20=0.068657
ndcg@1=0.627258  ndcg@2=0.697351  ndcg@5=0.781465  ndcg@10=0.799174  ndcg@20=0.805764
hit_rate@1=0.627258  hit_rate@2=0.801935  hit_rate@5=0.949113  hit_rate@10=0.978790  hit_rate@20=0.992419
map@1=0.627258  map@2=0.666028  map@5=0.723032  map@10=0.733538  map@20=0.736194
mrr@1=0.627258  mrr@2=0.714637  mrr@5=0.753715  mrr@10=0.757989  mrr@20=0.759018
f1@1=0.549883  f1@2=0.541563  f1@5=0.377699  f1@10=0.227494  f1@20=0.126099

[TEST]
recall@1=0.517684  recall@2=0.720814  recall@5=0.920341  recall@10=0.965093  recall@20=0.985292
precision@1=0.629430  precision@2=0.465005  precision@5=0.250370  precision@10=0.133280  precision@20=0.068512
ndcg@1=0.629430  ndcg@2=0.699283  ndcg@5=0.784242  ndcg@10=0.801110  ndcg@20=0.806992
hit_rate@1=0.629430  hit_rate@2=0.803077  hit_rate@5=0.951836  hit_rate@10=0.979381  hit_rate@20=0.992188
map@1=0.629430  map@2=0.668029  map@5=0.725677  map@10=0.735649  map@20=0.737958
mrr@1=0.629430  mrr@2=0.716253  mrr@5=0.755772  mrr@10=0.759699  mrr@20=0.760615
f1@1=0.550546  f1@2=0.543519  f1@5=0.379454  f1@10=0.228022  f1@20=0.125915

Epoch 29/100: 100%|██████████| 820/820 [00:11<00:00, 73.99it/s, bpr=0.0373, c=2.68, loss=0.144]

[VAL]
recall@1=0.527314  recall@2=0.723672  recall@5=0.916814  recall@10=0.963612  recall@20=0.985105
precision@1=0.637903  precision@2=0.466250  precision@5=0.249242  precision@10=0.132984  precision@20=0.068569
ndcg@1=0.637903  ndcg@2=0.704348  ndcg@5=0.786286  ndcg@10=0.804016  ndcg@20=0.810376
hit_rate@1=0.637903  hit_rate@2=0.806210  hit_rate@5=0.950161  hit_rate@10=0.979435  hit_rate@20=0.992419
map@1=0.637903  map@2=0.673891  map@5=0.729310  map@10=0.739886  map@20=0.742451
mrr@1=0.637903  mrr@2=0.722056  mrr@5=0.760324  mrr@10=0.764510  mrr@20=0.765438
f1@1=0.559895  f1@2=0.545286  f1@5=0.377674  f1@10=0.227466  f1@20=0.125968

[TEST]
recall@1=0.519953  recall@2=0.725947  recall@5=0.919949  recall@10=0.964771  recall@20=0.986007
precision@1=0.630477  precision@2=0.468549  precision@5=0.250322  precision@10=0.133223  precision@20=0.068569
ndcg@1=0.630477  ndcg@2=0.703696  ndcg@5=0.785997  ndcg@10=0.802851  ndcg@20=0.809006
hit_rate@1=0.630477  hit_rate@2=0.808151  hit_rate@5=0.951434  hit_rate@10=0.979220  hit_rate@20=0.992429
map@1=0.630477  map@2=0.672378  map@5=0.728370  map@10=0.738280  map@20=0.740657
mrr@1=0.630477  mrr@2=0.719314  mrr@5=0.757469  mrr@10=0.761452  mrr@20=0.762402
f1@1=0.552424  f1@2=0.547441  f1@5=0.379385  f1@10=0.227923  f1@20=0.126013

Epoch 30/100: 100%|██████████| 820/820 [00:11<00:00, 73.83it/s, bpr=0.0468, c=2.61, loss=0.151]

[VAL]
recall@1=0.520483  recall@2=0.714132  recall@5=0.914798  recall@10=0.963053  recall@20=0.985266
precision@1=0.630242  precision@2=0.460484  precision@5=0.248806  precision@10=0.133032  precision@20=0.068617
ndcg@1=0.630242  ndcg@2=0.695412  ndcg@5=0.780643  ndcg@10=0.798890  ndcg@20=0.805450
hit_rate@1=0.630242  hit_rate@2=0.797984  hit_rate@5=0.948387  hit_rate@10=0.978145  hit_rate@20=0.992339
map@1=0.630242  map@2=0.664798  map@5=0.722234  map@10=0.733120  map@20=0.735731
mrr@1=0.630242  mrr@2=0.714113  mrr@5=0.753948  mrr@10=0.758214  mrr@20=0.759256
f1@1=0.552838  f1@2=0.538201  f1@5=0.376923  f1@10=0.227511  f1@20=0.126043

[TEST]
recall@1=0.514471  recall@2=0.715586  recall@5=0.916024  recall@10=0.964832  recall@20=0.985607
precision@1=0.624597  precision@2=0.462065  precision@5=0.249114  precision@10=0.133191  precision@20=0.068549
ndcg@1=0.624597  ndcg@2=0.694558  ndcg@5=0.779809  ndcg@10=0.798095  ndcg@20=0.804214
hit_rate@1=0.624597  hit_rate@2=0.798003  hit_rate@5=0.948776  hit_rate@10=0.979381  hit_rate@20=0.992268
map@1=0.624597  map@2=0.663559  map@5=0.721062  map@10=0.731808  map@20=0.734239
mrr@1=0.624597  mrr@2=0.711300  mrr@5=0.751380  mrr@10=0.755715  mrr@20=0.756668
f1@1=0.546860  f1@2=0.539801  f1@5=0.377588  f1@10=0.227869  f1@20=0.125962

Epoch 31/100: 100%|██████████| 820/820 [00:10<00:00, 74.76it/s, bpr=0.0563, c=2.54, loss=0.158]

[VAL]
recall@1=0.525292  recall@2=0.731102  recall@5=0.917815  recall@10=0.963549  recall@20=0.985082
precision@1=0.634516  precision@2=0.470040  precision@5=0.249726  precision@10=0.133073  precision@20=0.068613
ndcg@1=0.634516  ndcg@2=0.708241  ndcg@5=0.787682  ndcg@10=0.804923  ndcg@20=0.811274
hit_rate@1=0.634516  hit_rate@2=0.815161  hit_rate@5=0.950403  hit_rate@10=0.978629  hit_rate@20=0.992339
map@1=0.634516  map@2=0.676290  map@5=0.730782  map@10=0.741036  map@20=0.743566
mrr@1=0.634516  mrr@2=0.724839  mrr@5=0.761132  mrr@10=0.765146  mrr@20=0.766142
f1@1=0.557401  f1@2=0.550217  f1@5=0.378239  f1@10=0.227595  f1@20=0.126023

[TEST]
recall@1=0.530627  recall@2=0.732679  recall@5=0.918994  recall@10=0.966636  recall@20=0.985488
precision@1=0.643041  precision@2=0.472334  precision@5=0.249871  precision@10=0.133473  precision@20=0.068504
ndcg@1=0.643041  ndcg@2=0.712036  ndcg@5=0.791053  ndcg@10=0.808987  ndcg@20=0.814479
hit_rate@1=0.643041  hit_rate@2=0.815561  hit_rate@5=0.951031  hit_rate@10=0.980590  hit_rate@20=0.992268
map@1=0.643041  map@2=0.680976  map@5=0.735050  map@10=0.745645  map@20=0.747789
mrr@1=0.643041  mrr@2=0.729301  mrr@5=0.765634  mrr@10=0.769822  mrr@20=0.770655
f1@1=0.563797  f1@2=0.552331  f1@5=0.378808  f1@10=0.228353  f1@20=0.125913

Epoch 32/100: 100%|██████████| 820/820 [00:11<00:00, 73.54it/s, bpr=0.0394, c=2.58, loss=0.142]

[VAL]
recall@1=0.519502  recall@2=0.723130  recall@5=0.915609  recall@10=0.962485  recall@20=0.984442
precision@1=0.628468  precision@2=0.465887  precision@5=0.248968  precision@10=0.132871  precision@20=0.068536
ndcg@1=0.628468  ndcg@2=0.701025  ndcg@5=0.782469  ndcg@10=0.800166  ndcg@20=0.806622
hit_rate@1=0.628468  hit_rate@2=0.806371  hit_rate@5=0.948790  hit_rate@10=0.977984  hit_rate@20=0.991774
map@1=0.628468  map@2=0.669556  map@5=0.724674  map@10=0.735207  map@20=0.737746
mrr@1=0.628468  mrr@2=0.717419  mrr@5=0.755130  mrr@10=0.759307  mrr@20=0.760301
f1@1=0.551514  f1@2=0.544797  f1@5=0.377159  f1@10=0.227249  f1@20=0.125890

[TEST]
recall@1=0.528163  recall@2=0.725274  recall@5=0.917655  recall@10=0.965104  recall@20=0.985240
precision@1=0.639578  precision@2=0.467461  precision@5=0.249356  precision@10=0.133247  precision@20=0.068492
ndcg@1=0.639578  ndcg@2=0.705920  ndcg@5=0.787736  ndcg@10=0.805612  ndcg@20=0.811486
hit_rate@1=0.639578  hit_rate@2=0.807990  hit_rate@5=0.950789  hit_rate@10=0.979462  hit_rate@20=0.992429
map@1=0.639578  map@2=0.675338  map@5=0.730949  map@10=0.741607  map@20=0.743890
mrr@1=0.639578  mrr@2=0.723784  mrr@5=0.761899  mrr@10=0.765944  mrr@20=0.766871
f1@1=0.561045  f1@2=0.546613  f1@5=0.378099  f1@10=0.227974  f1@20=0.125888

Epoch 33/100: 100%|██████████| 820/820 [00:11<00:00, 73.04it/s, bpr=0.0654, c=2.61, loss=0.17]

[VAL]
recall@1=0.499838  recall@2=0.693528  recall@5=0.911764  recall@10=0.961830  recall@20=0.985480
precision@1=0.607258  precision@2=0.448347  precision@5=0.247855  precision@10=0.132782  precision@20=0.068657
ndcg@1=0.607258  ndcg@2=0.674073  ndcg@5=0.766930  ndcg@10=0.785843  ndcg@20=0.792844
hit_rate@1=0.607258  hit_rate@2=0.776048  hit_rate@5=0.946129  hit_rate@10=0.977661  hit_rate@20=0.992661
map@1=0.607258  map@2=0.643589  map@5=0.705222  map@10=0.716443  map@20=0.719239
mrr@1=0.607258  mrr@2=0.691653  mrr@5=0.736266  mrr@10=0.740808  mrr@20=0.741898
f1@1=0.531409  f1@2=0.523246  f1@5=0.375551  f1@10=0.227107  f1@20=0.126097

[TEST]
recall@1=0.504722  recall@2=0.697015  recall@5=0.914504  recall@10=0.964098  recall@20=0.985833
precision@1=0.615496  precision@2=0.451756  precision@5=0.248454  precision@10=0.133135  precision@20=0.068524
ndcg@1=0.615496  ndcg@2=0.678856  ndcg@5=0.771415  ndcg@10=0.790114  ndcg@20=0.796402
hit_rate@1=0.615496  hit_rate@2=0.778028  hit_rate@5=0.948534  hit_rate@10=0.978576  hit_rate@20=0.992751
map@1=0.615496  map@2=0.649062  map@5=0.710580  map@10=0.721648  map@20=0.724056
mrr@1=0.615496  mrr@2=0.696762  mrr@5=0.741498  mrr@10=0.745755  mrr@20=0.746770
f1@1=0.537374  f1@2=0.526809  f1@5=0.376759  f1@10=0.227789  f1@20=0.125947

Epoch 34/100: 100%|██████████| 820/820 [00:11<00:00, 74.44it/s, bpr=0.0451, c=2.63, loss=0.15]

[VAL]
recall@1=0.531800  recall@2=0.740042  recall@5=0.919100  recall@10=0.965671  recall@20=0.984158
precision@1=0.642984  precision@2=0.475323  precision@5=0.249855  precision@10=0.133403  precision@20=0.068492
ndcg@1=0.642984  ndcg@2=0.716790  ndcg@5=0.792892  ndcg@10=0.810583  ndcg@20=0.816025
hit_rate@1=0.642984  hit_rate@2=0.824355  hit_rate@5=0.951694  hit_rate@10=0.980242  hit_rate@20=0.991935
map@1=0.642984  map@2=0.684476  map@5=0.737086  map@10=0.747693  map@20=0.749849
mrr@1=0.642984  mrr@2=0.733669  mrr@5=0.768242  mrr@10=0.772317  mrr@20=0.773157
f1@1=0.564556  f1@2=0.556643  f1@5=0.378614  f1@10=0.228136  f1@20=0.125823

[TEST]
recall@1=0.541444  recall@2=0.746460  recall@5=0.921828  recall@10=0.967166  recall@20=0.985695
precision@1=0.653109  precision@2=0.478898  precision@5=0.250660  precision@10=0.133586  precision@20=0.068529
ndcg@1=0.653109  ndcg@2=0.724290  ndcg@5=0.799321  ndcg@10=0.816502  ndcg@20=0.821905
hit_rate@1=0.653109  hit_rate@2=0.829897  hit_rate@5=0.952883  hit_rate@10=0.980590  hit_rate@20=0.992268
map@1=0.653109  map@2=0.692635  map@5=0.745193  map@10=0.755460  map@20=0.757550
mrr@1=0.653109  mrr@2=0.741503  mrr@5=0.774906  mrr@10=0.778869  mrr@20=0.779718
f1@1=0.574459  f1@2=0.561437  f1@5=0.380030  f1@10=0.228546  f1@20=0.125960

Epoch 35/100: 100%|██████████| 820/820 [00:11<00:00, 73.22it/s, bpr=0.0423, c=2.67, loss=0.149]

[VAL]
recall@1=0.514317  recall@2=0.714456  recall@5=0.914235  recall@10=0.962643  recall@20=0.984241
precision@1=0.623548  precision@2=0.460927  precision@5=0.248565  precision@10=0.132935  precision@20=0.068524
ndcg@1=0.623548  ndcg@2=0.693478  ndcg@5=0.778261  ndcg@10=0.796642  ndcg@20=0.803013
hit_rate@1=0.623548  hit_rate@2=0.799032  hit_rate@5=0.947742  hit_rate@10=0.978065  hit_rate@20=0.991613
map@1=0.623548  map@2=0.661956  map@5=0.719286  map@10=0.730299  map@20=0.732829
mrr@1=0.623548  mrr@2=0.711290  mrr@5=0.750656  mrr@10=0.755041  mrr@20=0.756033
f1@1=0.546470  f1@2=0.538575  f1@5=0.376607  f1@10=0.227344  f1@20=0.125876

[TEST]
recall@1=0.520221  recall@2=0.719509  recall@5=0.916595  recall@10=0.965034  recall@20=0.986230
precision@1=0.631443  precision@2=0.464642  precision@5=0.249340  precision@10=0.133264  precision@20=0.068573
ndcg@1=0.631443  ndcg@2=0.699535  ndcg@5=0.783250  ndcg@10=0.801434  ndcg@20=0.807598
hit_rate@1=0.631443  hit_rate@2=0.801949  hit_rate@5=0.949420  hit_rate@10=0.979462  hit_rate@20=0.992751
map@1=0.631443  map@2=0.668814  map@5=0.725449  map@10=0.736156  map@20=0.738569
mrr@1=0.631443  mrr@2=0.716696  mrr@5=0.756034  mrr@10=0.760319  mrr@20=0.761263
f1@1=0.552964  f1@2=0.542752  f1@5=0.377904  f1@10=0.228003  f1@20=0.126030

Epoch 36/100: 100%|██████████| 820/820 [00:11<00:00, 73.87it/s, bpr=0.0419, c=2.55, loss=0.144]

[VAL]
recall@1=0.523927  recall@2=0.729042  recall@5=0.917293  recall@10=0.963881  recall@20=0.984508
precision@1=0.633710  precision@2=0.469879  precision@5=0.249468  precision@10=0.133121  precision@20=0.068565
ndcg@1=0.633710  ndcg@2=0.706847  ndcg@5=0.786664  ndcg@10=0.804323  ndcg@20=0.810428
hit_rate@1=0.633710  hit_rate@2=0.812661  hit_rate@5=0.950081  hit_rate@10=0.979113  hit_rate@20=0.992258
map@1=0.633710  map@2=0.675222  map@5=0.729706  map@10=0.740260  map@20=0.742700
mrr@1=0.633710  mrr@2=0.723185  mrr@5=0.759996  mrr@10=0.764155  mrr@20=0.765109
f1@1=0.556274  f1@2=0.549352  f1@5=0.377962  f1@10=0.227653  f1@20=0.125933

[TEST]
recall@1=0.530136  recall@2=0.731083  recall@5=0.920003  recall@10=0.966008  recall@20=0.985746
precision@1=0.642961  precision@2=0.471488  precision@5=0.250419  precision@10=0.133344  precision@20=0.068549
ndcg@1=0.642961  ndcg@2=0.710919  ndcg@5=0.791259  ndcg@10=0.808509  ndcg@20=0.814292
hit_rate@1=0.642961  hit_rate@2=0.812903  hit_rate@5=0.951917  hit_rate@10=0.980267  hit_rate@20=0.992429
map@1=0.642961  map@2=0.680211  map@5=0.735026  map@10=0.745182  map@20=0.747474
mrr@1=0.642961  mrr@2=0.727932  mrr@5=0.765346  mrr@10=0.769404  mrr@20=0.770273
f1@1=0.563470  f1@2=0.551165  f1@5=0.379498  f1@10=0.228184  f1@20=0.125980

Epoch 37/100: 100%|██████████| 820/820 [00:11<00:00, 73.75it/s, bpr=0.0279, c=2.68, loss=0.135]

[VAL]
recall@1=0.527411  recall@2=0.730093  recall@5=0.917128  recall@10=0.963662  recall@20=0.984865
precision@1=0.637984  precision@2=0.470444  precision@5=0.249581  precision@10=0.133129  precision@20=0.068573
ndcg@1=0.637984  ndcg@2=0.708816  ndcg@5=0.788098  ndcg@10=0.805665  ndcg@20=0.811898
hit_rate@1=0.637984  hit_rate@2=0.813871  hit_rate@5=0.950000  hit_rate@10=0.978710  hit_rate@20=0.991935
map@1=0.637984  map@2=0.677440  map@5=0.731519  map@10=0.741975  map@20=0.744440
mrr@1=0.637984  mrr@2=0.725887  mrr@5=0.762422  mrr@10=0.766540  mrr@20=0.767473
f1@1=0.559951  f1@2=0.550131  f1@5=0.378038  f1@10=0.227667  f1@20=0.125970

[TEST]
recall@1=0.532041  recall@2=0.733581  recall@5=0.920202  recall@10=0.965752  recall@20=0.986090
precision@1=0.642880  precision@2=0.472616  precision@5=0.250338  precision@10=0.133352  precision@20=0.068549
ndcg@1=0.642880  ndcg@2=0.712969  ndcg@5=0.792380  ndcg@10=0.809557  ndcg@20=0.815524
hit_rate@1=0.642880  hit_rate@2=0.815883  hit_rate@5=0.952320  hit_rate@10=0.980267  hit_rate@20=0.992671
map@1=0.642880  map@2=0.682184  map@5=0.736491  map@10=0.746705  map@20=0.749086
mrr@1=0.642880  mrr@2=0.729422  mrr@5=0.766238  mrr@10=0.770201  mrr@20=0.771137
f1@1=0.564747  f1@2=0.552777  f1@5=0.379445  f1@10=0.228173  f1@20=0.125991

Epoch 38/100: 100%|██████████| 820/820 [00:11<00:00, 73.49it/s, bpr=0.0589, c=2.62, loss=0.164]

[VAL]
recall@1=0.514955  recall@2=0.713950  recall@5=0.914677  recall@10=0.962514  recall@20=0.984703
precision@1=0.623952  precision@2=0.461411  precision@5=0.248855  precision@10=0.132903  precision@20=0.068573
ndcg@1=0.623952  ndcg@2=0.693722  ndcg@5=0.778551  ndcg@10=0.796571  ndcg@20=0.803133
hit_rate@1=0.623952  hit_rate@2=0.797177  hit_rate@5=0.947903  hit_rate@10=0.978145  hit_rate@20=0.992016
map@1=0.623952  map@2=0.662903  map@5=0.719796  map@10=0.730495  map@20=0.733116
mrr@1=0.623952  mrr@2=0.710565  mrr@5=0.750415  mrr@10=0.754712  mrr@20=0.755725
f1@1=0.546957  f1@2=0.538672  f1@5=0.376981  f1@10=0.227308  f1@20=0.125961

[TEST]
recall@1=0.519040  recall@2=0.717541  recall@5=0.915942  recall@10=0.965046  recall@20=0.985600
precision@1=0.629269  precision@2=0.463434  precision@5=0.249227  precision@10=0.133255  precision@20=0.068516
ndcg@1=0.629269  ndcg@2=0.697570  ndcg@5=0.782030  ndcg@10=0.800422  ndcg@20=0.806408
hit_rate@1=0.629269  hit_rate@2=0.799533  hit_rate@5=0.948454  hit_rate@10=0.979301  hit_rate@20=0.992349
map@1=0.629269  map@2=0.667083  map@5=0.724232  map@10=0.735043  map@20=0.737384
mrr@1=0.629269  mrr@2=0.714401  mrr@5=0.754059  mrr@10=0.758430  mrr@20=0.759370
f1@1=0.551475  f1@2=0.541356  f1@5=0.377708  f1@10=0.227989  f1@20=0.125926

Epoch 39/100: 100%|██████████| 820/820 [00:11<00:00, 73.04it/s, bpr=0.0239, c=2.78, loss=0.135]

[VAL]
recall@1=0.528290  recall@2=0.732731  recall@5=0.917412  recall@10=0.963903  recall@20=0.984541
precision@1=0.639032  precision@2=0.471492  precision@5=0.249629  precision@10=0.133065  precision@20=0.068573
ndcg@1=0.639032  ndcg@2=0.710704  ndcg@5=0.789199  ndcg@10=0.806757  ndcg@20=0.812907
hit_rate@1=0.639032  hit_rate@2=0.816210  hit_rate@5=0.949919  hit_rate@10=0.979435  hit_rate@20=0.992016
map@1=0.639032  map@2=0.679052  map@5=0.732881  map@10=0.743343  map@20=0.745834
mrr@1=0.639032  mrr@2=0.727621  mrr@5=0.763617  mrr@10=0.767831  mrr@20=0.768747
f1@1=0.560990  f1@2=0.551699  f1@5=0.378135  f1@10=0.227598  f1@20=0.125957

[TEST]
recall@1=0.528530  recall@2=0.734922  recall@5=0.920092  recall@10=0.966102  recall@20=0.985901
precision@1=0.640625  precision@2=0.473623  precision@5=0.250161  precision@10=0.133409  precision@20=0.068537
ndcg@1=0.640625  ndcg@2=0.712736  ndcg@5=0.791378  ndcg@10=0.808710  ndcg@20=0.814466
hit_rate@1=0.640625  hit_rate@2=0.818218  hit_rate@5=0.951836  hit_rate@10=0.980187  hit_rate@20=0.992590
map@1=0.640625  map@2=0.681077  map@5=0.735104  map@10=0.745356  map@20=0.747585
mrr@1=0.640625  mrr@2=0.729422  mrr@5=0.765441  mrr@10=0.769467  mrr@20=0.770357
f1@1=0.561570  f1@2=0.553912  f1@5=0.379268  f1@10=0.228279  f1@20=0.125973

Epoch 40/100: 100%|██████████| 820/820 [00:11<00:00, 73.50it/s, bpr=0.0366, c=2.75, loss=0.146]

[VAL]
recall@1=0.520544  recall@2=0.717708  recall@5=0.913449  recall@10=0.962227  recall@20=0.984375
precision@1=0.630968  precision@2=0.463024  precision@5=0.248226  precision@10=0.132790  precision@20=0.068528
ndcg@1=0.630968  ndcg@2=0.698106  ndcg@5=0.780809  ndcg@10=0.799254  ndcg@20=0.805829
hit_rate@1=0.630968  hit_rate@2=0.801452  hit_rate@5=0.947419  hit_rate@10=0.978145  hit_rate@20=0.992097
map@1=0.630968  map@2=0.667198  map@5=0.722925  map@10=0.733917  map@20=0.736540
mrr@1=0.630968  mrr@2=0.716210  mrr@5=0.754798  mrr@10=0.759189  mrr@20=0.760208
f1@1=0.553073  f1@2=0.541041  f1@5=0.376171  f1@10=0.227147  f1@20=0.125888

[TEST]
recall@1=0.518087  recall@2=0.718987  recall@5=0.916272  recall@10=0.964648  recall@20=0.986188
precision@1=0.629108  precision@2=0.464401  precision@5=0.249275  precision@10=0.133135  precision@20=0.068545
ndcg@1=0.629108  ndcg@2=0.698463  ndcg@5=0.782040  ndcg@10=0.800185  ndcg@20=0.806462
hit_rate@1=0.629108  hit_rate@2=0.801224  hit_rate@5=0.949017  hit_rate@10=0.979381  hit_rate@20=0.992912
map@1=0.629108  map@2=0.667647  map@5=0.723944  map@10=0.734622  map@20=0.737071
mrr@1=0.629108  mrr@2=0.715166  mrr@5=0.754506  mrr@10=0.758832  mrr@20=0.759794
f1@1=0.550692  f1@2=0.542425  f1@5=0.377820  f1@10=0.227809  f1@20=0.125986

Epoch 41/100: 100%|██████████| 820/820 [00:11<00:00, 73.56it/s, bpr=0.0486, c=2.72, loss=0.157]

[VAL]
recall@1=0.520972  recall@2=0.719567  recall@5=0.915977  recall@10=0.963380  recall@20=0.985032
precision@1=0.631452  precision@2=0.464073  precision@5=0.248984  precision@10=0.133048  precision@20=0.068569
ndcg@1=0.631452  ndcg@2=0.699396  ndcg@5=0.782773  ndcg@10=0.800754  ndcg@20=0.807108
hit_rate@1=0.631452  hit_rate@2=0.803629  hit_rate@5=0.949597  hit_rate@10=0.978710  hit_rate@20=0.992581
map@1=0.631452  map@2=0.668226  map@5=0.724759  map@10=0.735517  map@20=0.738012
mrr@1=0.631452  mrr@2=0.717540  mrr@5=0.756320  mrr@10=0.760490  mrr@20=0.761492
f1@1=0.553544  f1@2=0.542412  f1@5=0.377285  f1@10=0.227552  f1@20=0.125960

[TEST]
recall@1=0.521489  recall@2=0.725484  recall@5=0.918706  recall@10=0.964833  recall@20=0.985427
precision@1=0.633457  precision@2=0.468750  precision@5=0.249855  precision@10=0.133223  precision@20=0.068488
ndcg@1=0.633457  ndcg@2=0.704286  ndcg@5=0.785835  ndcg@10=0.803254  ndcg@20=0.809258
hit_rate@1=0.633457  hit_rate@2=0.807829  hit_rate@5=0.950709  hit_rate@10=0.979301  hit_rate@20=0.992671
map@1=0.633457  map@2=0.673184  map@5=0.728198  map@10=0.738574  map@20=0.740909
mrr@1=0.633457  mrr@2=0.720643  mrr@5=0.758649  mrr@10=0.762754  mrr@20=0.763724
f1@1=0.554439  f1@2=0.547422  f1@5=0.378734  f1@10=0.227941  f1@20=0.125882

Epoch 42/100: 100%|██████████| 820/820 [00:11<00:00, 73.63it/s, bpr=0.042, c=2.67, loss=0.149]

[VAL]
recall@1=0.522750  recall@2=0.726621  recall@5=0.915299  recall@10=0.963309  recall@20=0.984177
precision@1=0.633790  precision@2=0.468306  precision@5=0.248903  precision@10=0.133040  precision@20=0.068536
ndcg@1=0.633790  ndcg@2=0.704775  ndcg@5=0.784750  ndcg@10=0.802946  ndcg@20=0.809093
hit_rate@1=0.633790  hit_rate@2=0.810242  hit_rate@5=0.948710  hit_rate@10=0.978790  hit_rate@20=0.992016
map@1=0.633790  map@2=0.673145  map@5=0.727653  map@10=0.738478  map@20=0.740915
mrr@1=0.633790  mrr@2=0.722016  mrr@5=0.758952  mrr@10=0.763305  mrr@20=0.764253
f1@1=0.555464  f1@2=0.547573  f1@5=0.377077  f1@10=0.227517  f1@20=0.125880

[TEST]
recall@1=0.521889  recall@2=0.727197  recall@5=0.919057  recall@10=0.964379  recall@20=0.985764
precision@1=0.633698  precision@2=0.469314  precision@5=0.250161  precision@10=0.133159  precision@20=0.068516
ndcg@1=0.633698  ndcg@2=0.705275  ndcg@5=0.786815  ndcg@10=0.803830  ndcg@20=0.810049
hit_rate@1=0.633698  hit_rate@2=0.809923  hit_rate@5=0.950467  hit_rate@10=0.978979  hit_rate@20=0.992751
map@1=0.633698  map@2=0.673828  map@5=0.729489  map@10=0.739516  map@20=0.741928
mrr@1=0.633698  mrr@2=0.721811  mrr@5=0.759446  mrr@10=0.763518  mrr@20=0.764516
f1@1=0.554827  f1@2=0.548435  f1@5=0.379088  f1@10=0.227808  f1@20=0.125933

Epoch 43/100: 100%|██████████| 820/820 [00:11<00:00, 73.67it/s, bpr=0.0294, c=2.71, loss=0.138]

[VAL]
recall@1=0.523835  recall@2=0.724315  recall@5=0.918388  recall@10=0.962740  recall@20=0.983980
precision@1=0.634355  precision@2=0.466935  precision@5=0.249758  precision@10=0.132927  precision@20=0.068512
ndcg@1=0.634355  ndcg@2=0.703701  ndcg@5=0.786060  ndcg@10=0.802828  ndcg@20=0.809089
hit_rate@1=0.634355  hit_rate@2=0.807258  hit_rate@5=0.951210  hit_rate@10=0.978710  hit_rate@20=0.991452
map@1=0.634355  map@2=0.672702  map@5=0.728632  map@10=0.738683  map@20=0.741175
mrr@1=0.634355  mrr@2=0.720806  mrr@5=0.759110  mrr@10=0.762981  mrr@20=0.763890
f1@1=0.556342  f1@2=0.545842  f1@5=0.378382  f1@10=0.227325  f1@20=0.125850

[TEST]
recall@1=0.520937  recall@2=0.725617  recall@5=0.918774  recall@10=0.965438  recall@20=0.985951
precision@1=0.631202  precision@2=0.468307  precision@5=0.249968  precision@10=0.133247  precision@20=0.068577
ndcg@1=0.631202  ndcg@2=0.703710  ndcg@5=0.785962  ndcg@10=0.803473  ndcg@20=0.809499
hit_rate@1=0.631202  hit_rate@2=0.808392  hit_rate@5=0.950548  hit_rate@10=0.979865  hit_rate@20=0.992671
map@1=0.631202  map@2=0.672378  map@5=0.728562  map@10=0.738862  map@20=0.741243
mrr@1=0.631202  mrr@2=0.719797  mrr@5=0.757931  mrr@10=0.762103  mrr@20=0.763019
f1@1=0.553444  f1@2=0.547273  f1@5=0.378842  f1@10=0.228010  f1@20=0.126024

Epoch 44/100: 100%|██████████| 820/820 [00:11<00:00, 74.14it/s, bpr=0.039, c=2.63, loss=0.144]

[VAL]
recall@1=0.526985  recall@2=0.728978  recall@5=0.917856  recall@10=0.964123  recall@20=0.984459
precision@1=0.637419  precision@2=0.469677  precision@5=0.249532  precision@10=0.133153  precision@20=0.068569
ndcg@1=0.637419  ndcg@2=0.707913  ndcg@5=0.787973  ndcg@10=0.805498  ndcg@20=0.811531
hit_rate@1=0.637419  hit_rate@2=0.812419  hit_rate@5=0.950726  hit_rate@10=0.979355  hit_rate@20=0.991694
map@1=0.637419  map@2=0.676694  map@5=0.731287  map@10=0.741770  map@20=0.744193
mrr@1=0.637419  mrr@2=0.724919  mrr@5=0.761915  mrr@10=0.765968  mrr@20=0.766872
f1@1=0.559464  f1@2=0.549237  f1@5=0.378062  f1@10=0.227730  f1@20=0.125948

[TEST]
recall@1=0.528309  recall@2=0.735045  recall@5=0.920181  recall@10=0.965669  recall@20=0.985847
precision@1=0.638773  precision@2=0.473180  precision@5=0.250258  precision@10=0.133328  precision@20=0.068573
ndcg@1=0.638773  ndcg@2=0.712438  ndcg@5=0.791285  ndcg@10=0.808422  ndcg@20=0.814315
hit_rate@1=0.638773  hit_rate@2=0.817332  hit_rate@5=0.951997  hit_rate@10=0.979704  hit_rate@20=0.992590
map@1=0.638773  map@2=0.680976  map@5=0.735146  map@10=0.745289  map@20=0.747605
mrr@1=0.638773  mrr@2=0.728053  mrr@5=0.764371  mrr@10=0.768339  mrr@20=0.769255
f1@1=0.560859  f1@2=0.553624  f1@5=0.379359  f1@10=0.228115  f1@20=0.126012

Epoch 45/100: 100%|██████████| 820/820 [00:11<00:00, 73.96it/s, bpr=0.0492, c=2.62, loss=0.154]

[VAL]
recall@1=0.526532  recall@2=0.730488  recall@5=0.917197  recall@10=0.962825  recall@20=0.984954
precision@1=0.636452  precision@2=0.470282  precision@5=0.249323  precision@10=0.132960  precision@20=0.068609
ndcg@1=0.636452  ndcg@2=0.708627  ndcg@5=0.787791  ndcg@10=0.805142  ndcg@20=0.811699
hit_rate@1=0.636452  hit_rate@2=0.813710  hit_rate@5=0.950081  hit_rate@10=0.978306  hit_rate@20=0.991855
map@1=0.636452  map@2=0.677218  map@5=0.731246  map@10=0.741674  map@20=0.744278
mrr@1=0.636452  mrr@2=0.725081  mrr@5=0.761688  mrr@10=0.765733  mrr@20=0.766737
f1@1=0.558834  f1@2=0.550140  f1@5=0.377803  f1@10=0.227380  f1@20=0.126014

[TEST]
recall@1=0.531645  recall@2=0.734005  recall@5=0.920366  recall@10=0.965381  recall@20=0.985772
precision@1=0.642558  precision@2=0.472858  precision@5=0.250419  precision@10=0.133312  precision@20=0.068557
ndcg@1=0.642558  ndcg@2=0.713055  ndcg@5=0.792352  ndcg@10=0.809241  ndcg@20=0.815202
hit_rate@1=0.642558  hit_rate@2=0.816366  hit_rate@5=0.951595  hit_rate@10=0.979140  hit_rate@20=0.992268
map@1=0.642558  map@2=0.682144  map@5=0.736614  map@10=0.746562  map@20=0.748886
mrr@1=0.642558  mrr@2=0.729462  mrr@5=0.765821  mrr@10=0.769738  mrr@20=0.770689
f1@1=0.564362  f1@2=0.553094  f1@5=0.379523  f1@10=0.228107  f1@20=0.126001

Epoch 46/100: 100%|██████████| 820/820 [00:11<00:00, 73.50it/s, bpr=0.035, c=2.74, loss=0.145]

[VAL]
recall@1=0.525296  recall@2=0.727180  recall@5=0.917093  recall@10=0.963605  recall@20=0.985375
precision@1=0.635968  precision@2=0.468145  precision@5=0.249355  precision@10=0.133089  precision@20=0.068601
ndcg@1=0.635968  ndcg@2=0.705888  ndcg@5=0.786499  ndcg@10=0.804091  ndcg@20=0.810473
hit_rate@1=0.635968  hit_rate@2=0.811452  hit_rate@5=0.950242  hit_rate@10=0.978871  hit_rate@20=0.992823
map@1=0.635968  map@2=0.674274  map@5=0.729262  map@10=0.739788  map@20=0.742287
mrr@1=0.635968  mrr@2=0.723710  mrr@5=0.760672  mrr@10=0.764761  mrr@20=0.765757
f1@1=0.557915  f1@2=0.547631  f1@5=0.377769  f1@10=0.227605  f1@20=0.126025

[TEST]
recall@1=0.528081  recall@2=0.729747  recall@5=0.918845  recall@10=0.965779  recall@20=0.985445
precision@1=0.639014  precision@2=0.470039  precision@5=0.249984  precision@10=0.133384  precision@20=0.068553
ndcg@1=0.639014  ndcg@2=0.708768  ndcg@5=0.789402  ndcg@10=0.807040  ndcg@20=0.812816
hit_rate@1=0.639014  hit_rate@2=0.812500  hit_rate@5=0.950870  hit_rate@10=0.980026  hit_rate@20=0.992107
map@1=0.639014  map@2=0.677694  map@5=0.732939  map@10=0.743324  map@20=0.745601
mrr@1=0.639014  mrr@2=0.725757  mrr@5=0.762991  mrr@10=0.767141  mrr@20=0.768015
f1@1=0.560832  f1@2=0.549878  f1@5=0.378948  f1@10=0.228196  f1@20=0.125978

Epoch 47/100: 100%|██████████| 820/820 [00:11<00:00, 73.47it/s, bpr=0.0501, c=2.66, loss=0.157]

[VAL]
recall@1=0.521599  recall@2=0.723600  recall@5=0.914767  recall@10=0.963182  recall@20=0.984469
precision@1=0.630806  precision@2=0.466290  precision@5=0.248806  precision@10=0.132968  precision@20=0.068528
ndcg@1=0.630806  ndcg@2=0.702113  ndcg@5=0.783294  ndcg@10=0.801579  ndcg@20=0.807839
hit_rate@1=0.630806  hit_rate@2=0.806210  hit_rate@5=0.948226  hit_rate@10=0.978548  hit_rate@20=0.992016
map@1=0.630806  map@2=0.670988  map@5=0.726011  map@10=0.736920  map@20=0.739361
mrr@1=0.630806  mrr@2=0.718508  mrr@5=0.756401  mrr@10=0.760774  mrr@20=0.761737
f1@1=0.553779  f1@2=0.545203  f1@5=0.376893  f1@10=0.227435  f1@20=0.125892

[TEST]
recall@1=0.526427  recall@2=0.728433  recall@5=0.917955  recall@10=0.964422  recall@20=0.985089
precision@1=0.639014  precision@2=0.469274  precision@5=0.249597  precision@10=0.133183  precision@20=0.068512
ndcg@1=0.639014  ndcg@2=0.707557  ndcg@5=0.788236  ndcg@10=0.805757  ndcg@20=0.811790
hit_rate@1=0.639014  hit_rate@2=0.811292  hit_rate@5=0.949903  hit_rate@10=0.978657  hit_rate@20=0.991704
map@1=0.639014  map@2=0.676305  map@5=0.731508  map@10=0.741892  map@20=0.744243
mrr@1=0.639014  mrr@2=0.725153  mrr@5=0.762507  mrr@10=0.766569  mrr@20=0.767510
f1@1=0.559631  f1@2=0.548881  f1@5=0.378398  f1@10=0.227839  f1@20=0.125907

Epoch 48/100: 100%|██████████| 820/820 [00:11<00:00, 73.66it/s, bpr=0.0343, c=2.61, loss=0.139]

[VAL]
recall@1=0.510020  recall@2=0.710472  recall@5=0.914825  recall@10=0.962618  recall@20=0.985142
precision@1=0.618548  precision@2=0.458710  precision@5=0.248677  precision@10=0.132839  precision@20=0.068573
ndcg@1=0.618548  ndcg@2=0.689139  ndcg@5=0.775992  ndcg@10=0.794040  ndcg@20=0.800709
hit_rate@1=0.618548  hit_rate@2=0.792903  hit_rate@5=0.948145  hit_rate@10=0.978387  hit_rate@20=0.992097
map@1=0.618548  map@2=0.658125  map@5=0.716454  map@10=0.727145  map@20=0.729817
mrr@1=0.618548  mrr@2=0.705726  mrr@5=0.746843  mrr@10=0.751144  mrr@20=0.752132
f1@1=0.541922  f1@2=0.535854  f1@5=0.376841  f1@10=0.227241  f1@20=0.125983

[TEST]
recall@1=0.519237  recall@2=0.715121  recall@5=0.918382  recall@10=0.965457  recall@20=0.985854
precision@1=0.630960  precision@2=0.462307  precision@5=0.249823  precision@10=0.133272  precision@20=0.068553
ndcg@1=0.630960  ndcg@2=0.696392  ndcg@5=0.782771  ndcg@10=0.800346  ndcg@20=0.806329
hit_rate@1=0.630960  hit_rate@2=0.796231  hit_rate@5=0.950709  hit_rate@10=0.980187  hit_rate@20=0.992590
map@1=0.630960  map@2=0.666398  map@5=0.724410  map@10=0.734691  map@20=0.737080
mrr@1=0.630960  mrr@2=0.713595  mrr@5=0.754681  mrr@10=0.758787  mrr@20=0.759683
f1@1=0.552108  f1@2=0.539752  f1@5=0.378624  f1@10=0.228012  f1@20=0.125984

Epoch 49/100: 100%|██████████| 820/820 [00:11<00:00, 74.24it/s, bpr=0.0284, c=2.74, loss=0.138]

[VAL]
recall@1=0.511657  recall@2=0.713247  recall@5=0.914864  recall@10=0.962878  recall@20=0.984222
precision@1=0.619758  precision@2=0.459879  precision@5=0.248355  precision@10=0.132927  precision@20=0.068516
ndcg@1=0.619758  ndcg@2=0.691194  ndcg@5=0.776725  ndcg@10=0.795013  ndcg@20=0.801319
hit_rate@1=0.619758  hit_rate@2=0.796694  hit_rate@5=0.949032  hit_rate@10=0.978387  hit_rate@20=0.991371
map@1=0.619758  map@2=0.659698  map@5=0.717152  map@10=0.728167  map@20=0.730691
mrr@1=0.619758  mrr@2=0.708226  mrr@5=0.748263  mrr@10=0.752460  mrr@20=0.753393
f1@1=0.543550  f1@2=0.537643  f1@5=0.376529  f1@10=0.227369  f1@20=0.125870

[TEST]
recall@1=0.521618  recall@2=0.718344  recall@5=0.916622  recall@10=0.964433  recall@20=0.986225
precision@1=0.633296  precision@2=0.463434  precision@5=0.249243  precision@10=0.133119  precision@20=0.068565
ndcg@1=0.633296  ndcg@2=0.699136  ndcg@5=0.783209  ndcg@10=0.801169  ndcg@20=0.807501
hit_rate@1=0.633296  hit_rate@2=0.801385  hit_rate@5=0.948776  hit_rate@10=0.978979  hit_rate@20=0.992751
map@1=0.633296  map@2=0.668472  map@5=0.725370  map@10=0.735905  map@20=0.738381
mrr@1=0.633296  mrr@2=0.717341  mrr@5=0.756336  mrr@10=0.760633  mrr@20=0.761618
f1@1=0.554417  f1@2=0.541623  f1@5=0.377877  f1@10=0.227792  f1@20=0.126017

Epoch 50/100: 100%|██████████| 820/820 [00:11<00:00, 73.41it/s, bpr=0.0436, c=2.62, loss=0.148]

[VAL]
recall@1=0.519489  recall@2=0.726186  recall@5=0.917752  recall@10=0.963188  recall@20=0.985160
precision@1=0.628871  precision@2=0.467621  precision@5=0.249645  precision@10=0.133008  precision@20=0.068613
ndcg@1=0.628871  ndcg@2=0.702944  ndcg@5=0.784737  ndcg@10=0.801932  ndcg@20=0.808426
hit_rate@1=0.628871  hit_rate@2=0.809677  hit_rate@5=0.950806  hit_rate@10=0.978387  hit_rate@20=0.992258
map@1=0.628871  map@2=0.670988  map@5=0.726918  map@10=0.737282  map@20=0.739880
mrr@1=0.628871  mrr@2=0.719315  mrr@5=0.757237  mrr@10=0.761148  mrr@20=0.762175
f1@1=0.551718  f1@2=0.547043  f1@5=0.378211  f1@10=0.227509  f1@20=0.126031

[TEST]
recall@1=0.528232  recall@2=0.732060  recall@5=0.918505  recall@10=0.965218  recall@20=0.985824
precision@1=0.641028  precision@2=0.472455  precision@5=0.249823  precision@10=0.133320  precision@20=0.068569
ndcg@1=0.641028  ndcg@2=0.710892  ndcg@5=0.790141  ndcg@10=0.807757  ndcg@20=0.813747
hit_rate@1=0.641028  hit_rate@2=0.813789  hit_rate@5=0.950145  hit_rate@10=0.979220  hit_rate@20=0.992268
map@1=0.641028  map@2=0.679909  map@5=0.734057  map@10=0.744490  map@20=0.746798
mrr@1=0.641028  mrr@2=0.727368  mrr@5=0.764268  mrr@10=0.768411  mrr@20=0.769321
f1@1=0.561583  f1@2=0.552170  f1@5=0.378719  f1@10=0.228091  f1@20=0.126014

Epoch 51/100: 100%|██████████| 820/820 [00:11<00:00, 73.96it/s, bpr=0.0489, c=2.54, loss=0.15]

[VAL]
recall@1=0.522338  recall@2=0.726142  recall@5=0.918863  recall@10=0.963256  recall@20=0.984524
precision@1=0.631935  precision@2=0.467339  precision@5=0.249806  precision@10=0.133040  precision@20=0.068560
ndcg@1=0.631935  ndcg@2=0.703902  ndcg@5=0.786270  ndcg@10=0.803117  ndcg@20=0.809388
hit_rate@1=0.631935  hit_rate@2=0.809516  hit_rate@5=0.951774  hit_rate@10=0.978548  hit_rate@20=0.991774
map@1=0.631935  map@2=0.672298  map@5=0.728574  map@10=0.738778  map@20=0.741265
mrr@1=0.631935  mrr@2=0.720726  mrr@5=0.759075  mrr@10=0.762853  mrr@20=0.763800
f1@1=0.554584  f1@2=0.546813  f1@5=0.378511  f1@10=0.227553  f1@20=0.125944

[TEST]
recall@1=0.528071  recall@2=0.731535  recall@5=0.920985  recall@10=0.965223  recall@20=0.985932
precision@1=0.639497  precision@2=0.471931  precision@5=0.250677  precision@10=0.133288  precision@20=0.068573
ndcg@1=0.639497  ndcg@2=0.710343  ndcg@5=0.791123  ndcg@10=0.807752  ndcg@20=0.813811
hit_rate@1=0.639497  hit_rate@2=0.814594  hit_rate@5=0.952159  hit_rate@10=0.979381  hit_rate@20=0.992510
map@1=0.639497  map@2=0.679144  map@5=0.734704  map@10=0.744553  map@20=0.746935
mrr@1=0.639497  mrr@2=0.727046  mrr@5=0.764076  mrr@10=0.767948  mrr@20=0.768894
f1@1=0.560955  f1@2=0.551612  f1@5=0.379870  f1@10=0.228043  f1@20=0.126018

Epoch 52/100: 100%|██████████| 820/820 [00:11<00:00, 74.13it/s, bpr=0.0416, c=2.56, loss=0.144]

[VAL]
recall@1=0.526719  recall@2=0.724171  recall@5=0.916501  recall@10=0.962896  recall@20=0.984586
precision@1=0.637016  precision@2=0.466895  precision@5=0.249145  precision@10=0.132935  precision@20=0.068548
ndcg@1=0.637016  ndcg@2=0.704511  ndcg@5=0.786092  ndcg@10=0.803676  ndcg@20=0.810076
hit_rate@1=0.637016  hit_rate@2=0.807903  hit_rate@5=0.949113  hit_rate@10=0.978145  hit_rate@20=0.992016
map@1=0.637016  map@2=0.673669  map@5=0.729069  map@10=0.739594  map@20=0.742120
mrr@1=0.637016  mrr@2=0.722460  mrr@5=0.760188  mrr@10=0.764354  mrr@20=0.765351
f1@1=0.559287  f1@2=0.545824  f1@5=0.377558  f1@10=0.227377  f1@20=0.125926

[TEST]
recall@1=0.520641  recall@2=0.726290  recall@5=0.917951  recall@10=0.965156  recall@20=0.986355
precision@1=0.631202  precision@2=0.468186  precision@5=0.249710  precision@10=0.133223  precision@20=0.068621
ndcg@1=0.631202  ndcg@2=0.703972  ndcg@5=0.785614  ndcg@10=0.803308  ndcg@20=0.809553
hit_rate@1=0.631202  hit_rate@2=0.807587  hit_rate@5=0.950387  hit_rate@10=0.979784  hit_rate@20=0.992912
map@1=0.631202  map@2=0.672781  map@5=0.728323  map@10=0.738721  map@20=0.741211
mrr@1=0.631202  mrr@2=0.719394  mrr@5=0.757815  mrr@10=0.761973  mrr@20=0.762925
f1@1=0.553196  f1@2=0.547351  f1@5=0.378481  f1@10=0.227959  f1@20=0.126092

Epoch 53/100: 100%|██████████| 820/820 [00:11<00:00, 73.48it/s, bpr=0.0307, c=2.68, loss=0.138]

[VAL]
recall@1=0.520644  recall@2=0.722180  recall@5=0.916237  recall@10=0.962096  recall@20=0.983974
precision@1=0.628790  precision@2=0.464758  precision@5=0.249129  precision@10=0.132903  precision@20=0.068484
ndcg@1=0.628790  ndcg@2=0.700506  ndcg@5=0.783110  ndcg@10=0.800483  ndcg@20=0.806875
hit_rate@1=0.628790  hit_rate@2=0.805887  hit_rate@5=0.949597  hit_rate@10=0.977419  hit_rate@20=0.991935
map@1=0.628790  map@2=0.669093  map@5=0.725308  map@10=0.735740  map@20=0.738209
mrr@1=0.628790  mrr@2=0.717339  mrr@5=0.755613  mrr@10=0.759567  mrr@20=0.760619
f1@1=0.552455  f1@2=0.543774  f1@5=0.377458  f1@10=0.227279  f1@20=0.125808

[TEST]
recall@1=0.528076  recall@2=0.726686  recall@5=0.917971  recall@10=0.964064  recall@20=0.985039
precision@1=0.639981  precision@2=0.468992  precision@5=0.249646  precision@10=0.133135  precision@20=0.068484
ndcg@1=0.639981  ndcg@2=0.707310  ndcg@5=0.788416  ndcg@10=0.805778  ndcg@20=0.811884
hit_rate@1=0.639981  hit_rate@2=0.808876  hit_rate@5=0.949742  hit_rate@10=0.978495  hit_rate@20=0.991865
map@1=0.639981  map@2=0.676848  map@5=0.732084  map@10=0.742305  map@20=0.744681
mrr@1=0.639981  mrr@2=0.724428  mrr@5=0.762052  mrr@10=0.766145  mrr@20=0.767117
f1@1=0.561055  f1@2=0.547967  f1@5=0.378429  f1@10=0.227786  f1@20=0.125869

Epoch 54/100: 100%|██████████| 820/820 [00:11<00:00, 73.78it/s, bpr=0.0415, c=2.72, loss=0.15]

[VAL]
recall@1=0.514490  recall@2=0.713299  recall@5=0.915294  recall@10=0.962264  recall@20=0.984110
precision@1=0.623548  precision@2=0.459879  precision@5=0.248855  precision@10=0.132806  precision@20=0.068480
ndcg@1=0.623548  ndcg@2=0.692497  ndcg@5=0.778504  ndcg@10=0.796252  ndcg@20=0.802688
hit_rate@1=0.623548  hit_rate@2=0.797177  hit_rate@5=0.948710  hit_rate@10=0.977661  hit_rate@20=0.991774
map@1=0.623548  map@2=0.661230  map@5=0.719359  map@10=0.730011  map@20=0.732524
mrr@1=0.623548  mrr@2=0.710323  mrr@5=0.750516  mrr@10=0.754620  mrr@20=0.755612
f1@1=0.546602  f1@2=0.537578  f1@5=0.377071  f1@10=0.227190  f1@20=0.125803

[TEST]
recall@1=0.519614  recall@2=0.719451  recall@5=0.918292  recall@10=0.964880  recall@20=0.985468
precision@1=0.631121  precision@2=0.464441  precision@5=0.249565  precision@10=0.133159  precision@20=0.068484
ndcg@1=0.631121  ndcg@2=0.699198  ndcg@5=0.783696  ndcg@10=0.801311  ndcg@20=0.807351
hit_rate@1=0.631121  hit_rate@2=0.802030  hit_rate@5=0.950709  hit_rate@10=0.979704  hit_rate@20=0.992349
map@1=0.631121  map@2=0.668311  map@5=0.725532  map@10=0.735980  map@20=0.738402
mrr@1=0.631121  mrr@2=0.716616  mrr@5=0.756131  mrr@10=0.760247  mrr@20=0.761188
f1@1=0.552479  f1@2=0.542652  f1@5=0.378466  f1@10=0.227869  f1@20=0.125884

Epoch 55/100: 100%|██████████| 820/820 [00:11<00:00, 73.82it/s, bpr=0.0387, c=2.52, loss=0.139]

[VAL]
recall@1=0.523569  recall@2=0.721682  recall@5=0.917490  recall@10=0.962983  recall@20=0.984167
precision@1=0.633468  precision@2=0.465282  precision@5=0.249565  precision@10=0.133016  precision@20=0.068540
ndcg@1=0.633468  ndcg@2=0.701639  ndcg@5=0.784895  ndcg@10=0.802086  ndcg@20=0.808366
hit_rate@1=0.633468  hit_rate@2=0.805161  hit_rate@5=0.950403  hit_rate@10=0.978306  hit_rate@20=0.991532
map@1=0.633468  map@2=0.670746  map@5=0.727316  map@10=0.737594  map@20=0.740116
mrr@1=0.633468  mrr@2=0.719315  mrr@5=0.757906  mrr@10=0.761873  mrr@20=0.762834
f1@1=0.555971  f1@2=0.543916  f1@5=0.378042  f1@10=0.227466  f1@20=0.125909

[TEST]
recall@1=0.521859  recall@2=0.726803  recall@5=0.918824  recall@10=0.964749  recall@20=0.986743
precision@1=0.633296  precision@2=0.469112  precision@5=0.250000  precision@10=0.133191  precision@20=0.068678
ndcg@1=0.633296  ndcg@2=0.704922  ndcg@5=0.786523  ndcg@10=0.803751  ndcg@20=0.810226
hit_rate@1=0.633296  hit_rate@2=0.808795  hit_rate@5=0.950548  hit_rate@10=0.979059  hit_rate@20=0.992832
map@1=0.633296  map@2=0.673707  map@5=0.729254  map@10=0.739397  map@20=0.741975
mrr@1=0.633296  mrr@2=0.721045  mrr@5=0.758999  mrr@10=0.763017  mrr@20=0.764021
f1@1=0.554729  f1@2=0.548234  f1@5=0.378929  f1@10=0.227927  f1@20=0.126191

Epoch 56/100: 100%|██████████| 820/820 [00:11<00:00, 73.50it/s, bpr=0.0588, c=2.43, loss=0.156]

[VAL]
recall@1=0.527481  recall@2=0.726998  recall@5=0.917168  recall@10=0.963409  recall@20=0.984774
precision@1=0.638065  precision@2=0.467702  precision@5=0.249323  precision@10=0.133032  precision@20=0.068560
ndcg@1=0.638065  ndcg@2=0.706350  ndcg@5=0.787170  ndcg@10=0.804649  ndcg@20=0.810943
hit_rate@1=0.638065  hit_rate@2=0.810403  hit_rate@5=0.950242  hit_rate@10=0.978710  hit_rate@20=0.991935
map@1=0.638065  map@2=0.675181  map@5=0.730225  map@10=0.740668  map@20=0.743161
mrr@1=0.638065  mrr@2=0.724234  mrr@5=0.761542  mrr@10=0.765578  mrr@20=0.766533
f1@1=0.560112  f1@2=0.547365  f1@5=0.377756  f1@10=0.227505  f1@20=0.125951

[TEST]
recall@1=0.527589  recall@2=0.733463  recall@5=0.918948  recall@10=0.966297  recall@20=0.985823
precision@1=0.638450  precision@2=0.472817  precision@5=0.249984  precision@10=0.133344  precision@20=0.068508
ndcg@1=0.638450  ndcg@2=0.711283  ndcg@5=0.790002  ndcg@10=0.807744  ndcg@20=0.813482
hit_rate@1=0.638450  hit_rate@2=0.815561  hit_rate@5=0.951273  hit_rate@10=0.980751  hit_rate@20=0.992429
map@1=0.638450  map@2=0.680030  map@5=0.733835  map@10=0.744243  map@20=0.746542
mrr@1=0.638450  mrr@2=0.727005  mrr@5=0.763440  mrr@10=0.767615  mrr@20=0.768461
f1@1=0.560292  f1@2=0.552908  f1@5=0.378935  f1@10=0.228209  f1@20=0.125936

Epoch 57/100: 100%|██████████| 820/820 [00:11<00:00, 73.82it/s, bpr=0.0473, c=2.5, loss=0.147]

[VAL]
recall@1=0.532392  recall@2=0.734936  recall@5=0.920499  recall@10=0.963764  recall@20=0.984163
precision@1=0.643468  precision@2=0.472016  precision@5=0.250306  precision@10=0.133097  precision@20=0.068520
ndcg@1=0.643468  ndcg@2=0.713444  ndcg@5=0.792747  ndcg@10=0.809204  ndcg@20=0.815232
hit_rate@1=0.643468  hit_rate@2=0.817742  hit_rate@5=0.952984  hit_rate@10=0.978952  hit_rate@20=0.991694
map@1=0.643468  map@2=0.682117  map@5=0.736636  map@10=0.746608  map@20=0.749000
mrr@1=0.643468  mrr@2=0.730605  mrr@5=0.767309  mrr@10=0.771014  mrr@20=0.771937
f1@1=0.565076  f1@2=0.552836  f1@5=0.379243  f1@10=0.227652  f1@20=0.125870

[TEST]
recall@1=0.531826  recall@2=0.743200  recall@5=0.921503  recall@10=0.966569  recall@20=0.986380
precision@1=0.644088  precision@2=0.477972  precision@5=0.250644  precision@10=0.133481  precision@20=0.068565
ndcg@1=0.644088  ndcg@2=0.719158  ndcg@5=0.794941  ndcg@10=0.811985  ndcg@20=0.817746
hit_rate@1=0.644088  hit_rate@2=0.826917  hit_rate@5=0.953206  hit_rate@10=0.980590  hit_rate@20=0.992912
map@1=0.644088  map@2=0.686755  map@5=0.739246  map@10=0.749417  map@20=0.751663
mrr@1=0.644088  mrr@2=0.735503  mrr@5=0.769648  mrr@10=0.773572  mrr@20=0.774455
f1@1=0.564968  f1@2=0.559634  f1@5=0.379959  f1@10=0.228370  f1@20=0.126024

Epoch 58/100: 100%|██████████| 820/820 [00:11<00:00, 73.61it/s, bpr=0.0269, c=2.59, loss=0.131]

[VAL]
recall@1=0.517643  recall@2=0.713877  recall@5=0.915180  recall@10=0.963340  recall@20=0.984371
precision@1=0.627742  precision@2=0.460121  precision@5=0.248758  precision@10=0.133000  precision@20=0.068540
ndcg@1=0.627742  ndcg@2=0.694171  ndcg@5=0.779812  ndcg@10=0.798051  ndcg@20=0.804262
hit_rate@1=0.627742  hit_rate@2=0.797016  hit_rate@5=0.948629  hit_rate@10=0.978629  hit_rate@20=0.991935
map@1=0.627742  map@2=0.663347  map@5=0.721142  map@10=0.732018  map@20=0.734462
mrr@1=0.627742  mrr@2=0.712379  mrr@5=0.752554  mrr@10=0.756857  mrr@20=0.757814
f1@1=0.550055  f1@2=0.537913  f1@5=0.376923  f1@10=0.227473  f1@20=0.125901

[TEST]
recall@1=0.515242  recall@2=0.717420  recall@5=0.917260  recall@10=0.965646  recall@20=0.985855
precision@1=0.626128  precision@2=0.463394  precision@5=0.249404  precision@10=0.133288  precision@20=0.068533
ndcg@1=0.626128  ndcg@2=0.696125  ndcg@5=0.781149  ndcg@10=0.799338  ndcg@20=0.805263
hit_rate@1=0.626128  hit_rate@2=0.799372  hit_rate@5=0.950064  hit_rate@10=0.979945  hit_rate@20=0.992671
map@1=0.626128  map@2=0.665110  map@5=0.722563  map@10=0.733256  map@20=0.735606
mrr@1=0.626128  mrr@2=0.712750  mrr@5=0.752768  mrr@10=0.757025  mrr@20=0.757951
f1@1=0.547939  f1@2=0.541335  f1@5=0.378080  f1@10=0.228068  f1@20=0.125956

Epoch 59/100: 100%|██████████| 820/820 [00:11<00:00, 73.58it/s, bpr=0.0442, c=2.77, loss=0.155]

[VAL]
recall@1=0.516436  recall@2=0.712735  recall@5=0.912938  recall@10=0.961753  recall@20=0.983825
precision@1=0.625726  precision@2=0.459637  precision@5=0.248081  precision@10=0.132750  precision@20=0.068504
ndcg@1=0.625726  ndcg@2=0.692871  ndcg@5=0.778039  ndcg@10=0.796516  ndcg@20=0.803060
hit_rate@1=0.625726  hit_rate@2=0.795806  hit_rate@5=0.946774  hit_rate@10=0.977339  hit_rate@20=0.991290
map@1=0.625726  map@2=0.662097  map@5=0.719536  map@10=0.730549  map@20=0.733139
mrr@1=0.625726  mrr@2=0.710766  mrr@5=0.750802  mrr@10=0.755184  mrr@20=0.756211
f1@1=0.548671  f1@2=0.537269  f1@5=0.375962  f1@10=0.227073  f1@20=0.125838

[TEST]
recall@1=0.516186  recall@2=0.716928  recall@5=0.916014  recall@10=0.964136  recall@20=0.984873
precision@1=0.626772  precision@2=0.462870  precision@5=0.249259  precision@10=0.133094  precision@20=0.068480
ndcg@1=0.626772  ndcg@2=0.696112  ndcg@5=0.780890  ndcg@10=0.798904  ndcg@20=0.804969
hit_rate@1=0.626772  hit_rate@2=0.799130  hit_rate@5=0.948776  hit_rate@10=0.978979  hit_rate@20=0.991865
map@1=0.626772  map@2=0.665210  map@5=0.722546  map@10=0.733101  map@20=0.735483
mrr@1=0.626772  mrr@2=0.712951  mrr@5=0.752819  mrr@10=0.757106  mrr@20=0.758036
f1@1=0.548713  f1@2=0.540770  f1@5=0.377758  f1@10=0.227728  f1@20=0.125860

Epoch 60/100: 100%|██████████| 820/820 [00:11<00:00, 73.38it/s, bpr=0.0515, c=2.53, loss=0.153]

[VAL]
recall@1=0.521795  recall@2=0.723348  recall@5=0.913986  recall@10=0.962553  recall@20=0.984537
precision@1=0.630242  precision@2=0.465444  precision@5=0.248452  precision@10=0.132919  precision@20=0.068560
ndcg@1=0.630242  ndcg@2=0.701792  ndcg@5=0.782935  ndcg@10=0.801303  ndcg@20=0.807785
hit_rate@1=0.630242  hit_rate@2=0.806452  hit_rate@5=0.947500  hit_rate@10=0.978145  hit_rate@20=0.991774
map@1=0.630242  map@2=0.670504  map@5=0.725739  map@10=0.736651  map@20=0.739232
mrr@1=0.630242  mrr@2=0.718347  mrr@5=0.756233  mrr@10=0.760602  mrr@20=0.761585
f1@1=0.553723  f1@2=0.544516  f1@5=0.376467  f1@10=0.227325  f1@20=0.125946

[TEST]
recall@1=0.527525  recall@2=0.728897  recall@5=0.916818  recall@10=0.965236  recall@20=0.986164
precision@1=0.639175  precision@2=0.469998  precision@5=0.249452  precision@10=0.133199  precision@20=0.068573
ndcg@1=0.639175  ndcg@2=0.708293  ndcg@5=0.787936  ndcg@10=0.806002  ndcg@20=0.812130
hit_rate@1=0.639175  hit_rate@2=0.810164  hit_rate@5=0.948937  hit_rate@10=0.979945  hit_rate@20=0.992671
map@1=0.639175  map@2=0.677694  map@5=0.731763  map@10=0.742276  map@20=0.744699
mrr@1=0.639175  mrr@2=0.724670  mrr@5=0.761766  mrr@10=0.766151  mrr@20=0.767051
f1@1=0.560443  f1@2=0.549536  f1@5=0.378038  f1@10=0.227927  f1@20=0.126038

Epoch 61/100: 100%|██████████| 820/820 [00:11<00:00, 73.86it/s, bpr=0.0474, c=2.63, loss=0.153]

[VAL]
recall@1=0.526478  recall@2=0.731430  recall@5=0.919177  recall@10=0.963223  recall@20=0.985125
precision@1=0.638226  precision@2=0.470968  precision@5=0.249952  precision@10=0.133048  precision@20=0.068577
ndcg@1=0.638226  ndcg@2=0.709346  ndcg@5=0.789370  ndcg@10=0.806130  ndcg@20=0.812551
hit_rate@1=0.638226  hit_rate@2=0.815242  hit_rate@5=0.952258  hit_rate@10=0.978145  hit_rate@20=0.992177
map@1=0.638226  map@2=0.677520  map@5=0.732368  map@10=0.742537  map@20=0.745068
mrr@1=0.638226  mrr@2=0.726734  mrr@5=0.763840  mrr@10=0.767560  mrr@20=0.768575
f1@1=0.559425  f1@2=0.550920  f1@5=0.378667  f1@10=0.227534  f1@20=0.125976

[TEST]
recall@1=0.529484  recall@2=0.735504  recall@5=0.920312  recall@10=0.966266  recall@20=0.986853
precision@1=0.641350  precision@2=0.473824  precision@5=0.250290  precision@10=0.133449  precision@20=0.068637
ndcg@1=0.641350  ndcg@2=0.713305  ndcg@5=0.791993  ndcg@10=0.809343  ndcg@20=0.815322
hit_rate@1=0.641350  hit_rate@2=0.817896  hit_rate@5=0.951675  hit_rate@10=0.980509  hit_rate@20=0.992993
map@1=0.641350  map@2=0.681862  map@5=0.736030  map@10=0.746272  map@20=0.748603
mrr@1=0.641350  mrr@2=0.729623  mrr@5=0.765723  mrr@10=0.769827  mrr@20=0.770717
f1@1=0.562559  f1@2=0.554265  f1@5=0.379439  f1@10=0.228317  f1@20=0.126144

Epoch 62/100: 100%|██████████| 820/820 [00:11<00:00, 73.46it/s, bpr=0.0508, c=2.54, loss=0.152]

[VAL]
recall@1=0.518328  recall@2=0.719008  recall@5=0.917409  recall@10=0.962742  recall@20=0.983942
precision@1=0.626371  precision@2=0.463185  precision@5=0.249468  precision@10=0.132887  precision@20=0.068516
ndcg@1=0.626371  ndcg@2=0.697586  ndcg@5=0.782136  ndcg@10=0.799306  ndcg@20=0.805628
hit_rate@1=0.626371  hit_rate@2=0.802016  hit_rate@5=0.950323  hit_rate@10=0.978226  hit_rate@20=0.991210
map@1=0.626371  map@2=0.666431  map@5=0.723840  map@10=0.734091  map@20=0.736649
mrr@1=0.626371  mrr@2=0.714194  mrr@5=0.753676  mrr@10=0.757652  mrr@20=0.758614
f1@1=0.550160  f1@2=0.541648  f1@5=0.377960  f1@10=0.227323  f1@20=0.125854

[TEST]
recall@1=0.526994  recall@2=0.723720  recall@5=0.919125  recall@10=0.964976  recall@20=0.985215
precision@1=0.639497  precision@2=0.467300  precision@5=0.250000  precision@10=0.133191  precision@20=0.068496
ndcg@1=0.639497  ndcg@2=0.704946  ndcg@5=0.788060  ndcg@10=0.805291  ndcg@20=0.811231
hit_rate@1=0.639497  hit_rate@2=0.805332  hit_rate@5=0.951192  hit_rate@10=0.979220  hit_rate@20=0.991865
map@1=0.639497  map@2=0.674795  map@5=0.731224  map@10=0.741360  map@20=0.743709
mrr@1=0.639497  mrr@2=0.722415  mrr@5=0.761512  mrr@10=0.765495  mrr@20=0.766412
f1@1=0.560138  f1@2=0.545950  f1@5=0.378964  f1@10=0.227911  f1@20=0.125899

Epoch 63/100: 100%|██████████| 820/820 [00:11<00:00, 73.76it/s, bpr=0.0403, c=2.68, loss=0.147]

[VAL]
recall@1=0.518988  recall@2=0.718479  recall@5=0.916050  recall@10=0.962631  recall@20=0.984280
precision@1=0.628629  precision@2=0.463226  precision@5=0.249274  precision@10=0.132944  precision@20=0.068508
ndcg@1=0.628629  ndcg@2=0.697893  ndcg@5=0.781822  ndcg@10=0.799450  ndcg@20=0.805825
hit_rate@1=0.628629  hit_rate@2=0.802500  hit_rate@5=0.948790  hit_rate@10=0.977903  hit_rate@20=0.991774
map@1=0.628629  map@2=0.666633  map@5=0.723599  map@10=0.734092  map@20=0.736620
mrr@1=0.628629  mrr@2=0.715565  mrr@5=0.754448  mrr@10=0.758666  mrr@20=0.759684
f1@1=0.551244  f1@2=0.541426  f1@5=0.377561  f1@10=0.227368  f1@20=0.125860

[TEST]
recall@1=0.521185  recall@2=0.724156  recall@5=0.919712  recall@10=0.966039  recall@20=0.986230
precision@1=0.632007  precision@2=0.467985  precision@5=0.250113  precision@10=0.133425  precision@20=0.068601
ndcg@1=0.632007  ndcg@2=0.702999  ndcg@5=0.785979  ndcg@10=0.803446  ndcg@20=0.809316
hit_rate@1=0.632007  hit_rate@2=0.805976  hit_rate@5=0.951434  hit_rate@10=0.979945  hit_rate@20=0.992671
map@1=0.632007  map@2=0.672177  map@5=0.728451  map@10=0.738812  map@20=0.741091
mrr@1=0.632007  mrr@2=0.718992  mrr@5=0.757708  mrr@10=0.761764  mrr@20=0.762667
f1@1=0.553850  f1@2=0.546566  f1@5=0.379139  f1@10=0.228259  f1@20=0.126062

Epoch 64/100: 100%|██████████| 820/820 [00:11<00:00, 73.37it/s, bpr=0.0336, c=2.66, loss=0.14]

[VAL]
recall@1=0.528266  recall@2=0.735395  recall@5=0.919724  recall@10=0.963571  recall@20=0.984897
precision@1=0.638952  precision@2=0.473508  precision@5=0.250306  precision@10=0.133073  precision@20=0.068565
ndcg@1=0.638952  ndcg@2=0.712650  ndcg@5=0.790955  ndcg@10=0.807541  ndcg@20=0.813802
hit_rate@1=0.638952  hit_rate@2=0.820323  hit_rate@5=0.951935  hit_rate@10=0.978710  hit_rate@20=0.992419
map@1=0.638952  map@2=0.680484  map@5=0.734456  map@10=0.744398  map@20=0.746873
mrr@1=0.638952  mrr@2=0.729637  mrr@5=0.765164  mrr@10=0.768976  mrr@20=0.769957
f1@1=0.560833  f1@2=0.553898  f1@5=0.379083  f1@10=0.227609  f1@20=0.125957

[TEST]
recall@1=0.535323  recall@2=0.737492  recall@5=0.920884  recall@10=0.966486  recall@20=0.985810
precision@1=0.647149  precision@2=0.474911  precision@5=0.250467  precision@10=0.133433  precision@20=0.068545
ndcg@1=0.647149  ndcg@2=0.716765  ndcg@5=0.794890  ndcg@10=0.812095  ndcg@20=0.817777
hit_rate@1=0.647149  hit_rate@2=0.819990  hit_rate@5=0.952239  hit_rate@10=0.980751  hit_rate@20=0.992510
map@1=0.647149  map@2=0.685849  map@5=0.739731  map@10=0.749932  map@20=0.752190
mrr@1=0.647149  mrr@2=0.733570  mrr@5=0.769339  mrr@10=0.773399  mrr@20=0.774248
f1@1=0.568341  f1@2=0.555651  f1@5=0.379740  f1@10=0.228295  f1@20=0.125971

Epoch 65/100: 100%|██████████| 820/820 [00:11<00:00, 73.29it/s, bpr=0.0721, c=2.62, loss=0.177]

[VAL]
recall@1=0.506491  recall@2=0.703132  recall@5=0.911050  recall@10=0.961077  recall@20=0.984547
precision@1=0.615081  precision@2=0.454556  precision@5=0.247758  precision@10=0.132661  precision@20=0.068544
ndcg@1=0.615081  ndcg@2=0.683093  ndcg@5=0.771271  ndcg@10=0.790078  ndcg@20=0.797013
hit_rate@1=0.615081  hit_rate@2=0.786532  hit_rate@5=0.945403  hit_rate@10=0.977097  hit_rate@20=0.992097
map@1=0.615081  map@2=0.652198  map@5=0.711082  map@10=0.722139  map@20=0.724902
mrr@1=0.615081  mrr@2=0.700806  mrr@5=0.742613  mrr@10=0.747159  mrr@20=0.748251
f1@1=0.538483  f1@2=0.530605  f1@5=0.375343  f1@10=0.226903  f1@20=0.125909

[TEST]
recall@1=0.512636  recall@2=0.705494  recall@5=0.914818  recall@10=0.963960  recall@20=0.985609
precision@1=0.623470  precision@2=0.456830  precision@5=0.248792  precision@10=0.133038  precision@20=0.068520
ndcg@1=0.623470  ndcg@2=0.687599  ndcg@5=0.776366  ndcg@10=0.794691  ndcg@20=0.801037
hit_rate@1=0.623470  hit_rate@2=0.787210  hit_rate@5=0.947648  hit_rate@10=0.978979  hit_rate@20=0.992268
map@1=0.623470  map@2=0.657780  map@5=0.717033  map@10=0.727733  map@20=0.730248
mrr@1=0.623470  mrr@2=0.705340  mrr@5=0.747589  mrr@10=0.751953  mrr@20=0.752913
f1@1=0.545217  f1@2=0.532915  f1@5=0.377118  f1@10=0.227640  f1@20=0.125939

Epoch 66/100: 100%|██████████| 820/820 [00:11<00:00, 73.80it/s, bpr=0.0442, c=2.53, loss=0.145]

[VAL]
recall@1=0.513397  recall@2=0.713383  recall@5=0.915126  recall@10=0.963147  recall@20=0.984125
precision@1=0.622581  precision@2=0.460645  precision@5=0.248774  precision@10=0.132944  precision@20=0.068552
ndcg@1=0.622581  ndcg@2=0.692520  ndcg@5=0.777890  ndcg@10=0.796031  ndcg@20=0.802248
hit_rate@1=0.622581  hit_rate@2=0.796774  hit_rate@5=0.949032  hit_rate@10=0.978629  hit_rate@20=0.991694
map@1=0.622581  map@2=0.661371  map@5=0.718702  map@10=0.729495  map@20=0.731968
mrr@1=0.622581  mrr@2=0.709677  mrr@5=0.749739  mrr@10=0.753968  mrr@20=0.754911
f1@1=0.545528  f1@2=0.538025  f1@5=0.376963  f1@10=0.227399  f1@20=0.125905

[TEST]
recall@1=0.514517  recall@2=0.714886  recall@5=0.919168  recall@10=0.965552  recall@20=0.985928
precision@1=0.625161  precision@2=0.462186  precision@5=0.249936  precision@10=0.133255  precision@20=0.068512
ndcg@1=0.625161  ndcg@2=0.694246  ndcg@5=0.781166  ndcg@10=0.798576  ndcg@20=0.804514
hit_rate@1=0.625161  hit_rate@2=0.796553  hit_rate@5=0.951434  hit_rate@10=0.980106  hit_rate@20=0.992349
map@1=0.625161  map@2=0.663579  map@5=0.722126  map@10=0.732423  map@20=0.734754
mrr@1=0.625161  mrr@2=0.710857  mrr@5=0.751874  mrr@10=0.755888  mrr@20=0.756753
f1@1=0.547106  f1@2=0.539702  f1@5=0.378894  f1@10=0.228034  f1@20=0.125955

Epoch 67/100: 100%|██████████| 820/820 [00:11<00:00, 73.53it/s, bpr=0.0447, c=2.59, loss=0.148]

[VAL]
recall@1=0.508278  recall@2=0.704821  recall@5=0.913067  recall@10=0.961741  recall@20=0.984041
precision@1=0.616532  precision@2=0.455565  precision@5=0.248306  precision@10=0.132790  precision@20=0.068492
ndcg@1=0.616532  ndcg@2=0.684885  ndcg@5=0.773181  ndcg@10=0.791521  ndcg@20=0.798089
hit_rate@1=0.616532  hit_rate@2=0.788548  hit_rate@5=0.946129  hit_rate@10=0.977661  hit_rate@20=0.991613
map@1=0.616532  map@2=0.653992  map@5=0.713195  map@10=0.723957  map@20=0.726565
mrr@1=0.616532  mrr@2=0.702581  mrr@5=0.744043  mrr@10=0.748573  mrr@20=0.749575
f1@1=0.540142  f1@2=0.531807  f1@5=0.376229  f1@10=0.227098  f1@20=0.125831

[TEST]
recall@1=0.515724  recall@2=0.708330  recall@5=0.916748  recall@10=0.964089  recall@20=0.985234
precision@1=0.625966  precision@2=0.457957  precision@5=0.249227  precision@10=0.133014  precision@20=0.068533
ndcg@1=0.625966  ndcg@2=0.690248  ndcg@5=0.778877  ndcg@10=0.796555  ndcg@20=0.802809
hit_rate@1=0.625966  hit_rate@2=0.790995  hit_rate@5=0.949823  hit_rate@10=0.979059  hit_rate@20=0.991704
map@1=0.625966  map@2=0.660176  map@5=0.719693  map@10=0.730066  map@20=0.732585
mrr@1=0.625966  mrr@2=0.708441  mrr@5=0.750306  mrr@10=0.754356  mrr@20=0.755276
f1@1=0.548150  f1@2=0.534669  f1@5=0.377805  f1@10=0.227630  f1@20=0.125949

Epoch 68/100: 100%|██████████| 820/820 [00:11<00:00, 73.20it/s, bpr=0.101, c=2.53, loss=0.202]

[VAL]
recall@1=0.522470  recall@2=0.723942  recall@5=0.915223  recall@10=0.962032  recall@20=0.984289
precision@1=0.632419  precision@2=0.465685  precision@5=0.248758  precision@10=0.132782  precision@20=0.068504
ndcg@1=0.632419  ndcg@2=0.702391  ndcg@5=0.783909  ndcg@10=0.801618  ndcg@20=0.808167
hit_rate@1=0.632419  hit_rate@2=0.806532  hit_rate@5=0.949032  hit_rate@10=0.977500  hit_rate@20=0.991532
map@1=0.632419  map@2=0.671129  map@5=0.726512  map@10=0.737127  map@20=0.739702
mrr@1=0.632419  mrr@2=0.719476  mrr@5=0.757641  mrr@10=0.761713  mrr@20=0.762732
f1@1=0.554867  f1@2=0.544997  f1@5=0.376956  f1@10=0.227126  f1@20=0.125853

[TEST]
recall@1=0.525884  recall@2=0.729182  recall@5=0.918072  recall@10=0.965637  recall@20=0.985724
precision@1=0.637645  precision@2=0.470643  precision@5=0.249613  precision@10=0.133272  precision@20=0.068565
ndcg@1=0.637645  ndcg@2=0.708125  ndcg@5=0.787942  ndcg@10=0.805830  ndcg@20=0.811743
hit_rate@1=0.637645  hit_rate@2=0.810648  hit_rate@5=0.950145  hit_rate@10=0.980026  hit_rate@20=0.992268
map@1=0.637645  map@2=0.677332  map@5=0.731411  map@10=0.741914  map@20=0.744272
mrr@1=0.637645  mrr@2=0.724146  mrr@5=0.761418  mrr@10=0.765678  mrr@20=0.766551
f1@1=0.558794  f1@2=0.549957  f1@5=0.378469  f1@10=0.228070  f1@20=0.126003

Epoch 69/100: 100%|██████████| 820/820 [00:11<00:00, 73.63it/s, bpr=0.0536, c=2.56, loss=0.156]

[VAL]
recall@1=0.528265  recall@2=0.733319  recall@5=0.920230  recall@10=0.964652  recall@20=0.985075
precision@1=0.639677  precision@2=0.472258  precision@5=0.250258  precision@10=0.133202  precision@20=0.068565
ndcg@1=0.639677  ndcg@2=0.711361  ndcg@5=0.790653  ndcg@10=0.807508  ndcg@20=0.813530
hit_rate@1=0.639677  hit_rate@2=0.817177  hit_rate@5=0.952500  hit_rate@10=0.979839  hit_rate@20=0.992097
map@1=0.639677  map@2=0.679637  map@5=0.734005  map@10=0.744109  map@20=0.746525
mrr@1=0.639677  mrr@2=0.728427  mrr@5=0.764706  mrr@10=0.768630  mrr@20=0.769515
f1@1=0.561066  f1@2=0.552371  f1@5=0.379166  f1@10=0.227840  f1@20=0.125968

[TEST]
recall@1=0.534685  recall@2=0.739265  recall@5=0.921004  recall@10=0.966925  recall@20=0.986252
precision@1=0.646505  precision@2=0.475999  precision@5=0.250499  precision@10=0.133481  precision@20=0.068553
ndcg@1=0.646505  ndcg@2=0.717621  ndcg@5=0.795034  ndcg@10=0.812369  ndcg@20=0.818038
hit_rate@1=0.646505  hit_rate@2=0.822004  hit_rate@5=0.952239  hit_rate@10=0.980751  hit_rate@20=0.992912
map@1=0.646505  map@2=0.686352  map@5=0.739861  map@10=0.750157  map@20=0.752391
mrr@1=0.646505  mrr@2=0.734254  mrr@5=0.769545  mrr@10=0.773618  mrr@20=0.774495
f1@1=0.567721  f1@2=0.557014  f1@5=0.379773  f1@10=0.228403  f1@20=0.126004

Epoch 70/100: 100%|██████████| 820/820 [00:11<00:00, 73.66it/s, bpr=0.0383, c=2.81, loss=0.151]

[VAL]
recall@1=0.525670  recall@2=0.728660  recall@5=0.916309  recall@10=0.962379  recall@20=0.985315
precision@1=0.635806  precision@2=0.469355  precision@5=0.249161  precision@10=0.132871  precision@20=0.068625
ndcg@1=0.635806  ndcg@2=0.707123  ndcg@5=0.786519  ndcg@10=0.803948  ndcg@20=0.810713
hit_rate@1=0.635806  hit_rate@2=0.812177  hit_rate@5=0.949839  hit_rate@10=0.978226  hit_rate@20=0.992339
map@1=0.635806  map@2=0.675706  map@5=0.729625  map@10=0.740053  map@20=0.742757
mrr@1=0.635806  mrr@2=0.723992  mrr@5=0.760716  mrr@10=0.764790  mrr@20=0.765806
f1@1=0.558100  f1@2=0.548881  f1@5=0.377483  f1@10=0.227256  f1@20=0.126058

[TEST]
recall@1=0.530473  recall@2=0.729654  recall@5=0.917944  recall@10=0.965562  recall@20=0.986239
precision@1=0.642236  precision@2=0.469596  precision@5=0.249404  precision@10=0.133247  precision@20=0.068589
ndcg@1=0.642236  ndcg@2=0.709576  ndcg@5=0.789830  ndcg@10=0.807751  ndcg@20=0.813835
hit_rate@1=0.642236  hit_rate@2=0.812017  hit_rate@5=0.949984  hit_rate@10=0.979623  hit_rate@20=0.992590
map@1=0.642236  map@2=0.678802  map@5=0.733768  map@10=0.744324  map@20=0.746735
mrr@1=0.642236  mrr@2=0.727126  mrr@5=0.764307  mrr@10=0.768494  mrr@20=0.769436
f1@1=0.563436  f1@2=0.549551  f1@5=0.378269  f1@10=0.228024  f1@20=0.126054

Epoch 71/100: 100%|██████████| 820/820 [00:11<00:00, 74.14it/s, bpr=0.0735, c=2.49, loss=0.173]

[VAL]
recall@1=0.519131  recall@2=0.721207  recall@5=0.917707  recall@10=0.962969  recall@20=0.985117
precision@1=0.629839  precision@2=0.465202  precision@5=0.249548  precision@10=0.132952  precision@20=0.068609
ndcg@1=0.629839  ndcg@2=0.699958  ndcg@5=0.783247  ndcg@10=0.800392  ndcg@20=0.806931
hit_rate@1=0.629839  hit_rate@2=0.805000  hit_rate@5=0.950887  hit_rate@10=0.978387  hit_rate@20=0.992258
map@1=0.629839  map@2=0.668488  map@5=0.724930  map@10=0.735224  map@20=0.737818
mrr@1=0.629839  mrr@2=0.717419  mrr@5=0.756110  mrr@10=0.760047  mrr@20=0.761050
f1@1=0.551692  f1@2=0.543667  f1@5=0.378089  f1@10=0.227392  f1@20=0.126030

[TEST]
recall@1=0.524816  recall@2=0.727270  recall@5=0.919552  recall@10=0.966165  recall@20=0.986396
precision@1=0.635229  precision@2=0.469274  precision@5=0.250161  precision@10=0.133441  precision@20=0.068625
ndcg@1=0.635229  ndcg@2=0.706068  ndcg@5=0.787823  ndcg@10=0.805372  ndcg@20=0.811275
hit_rate@1=0.635229  hit_rate@2=0.809601  hit_rate@5=0.951273  hit_rate@10=0.980348  hit_rate@20=0.992751
map@1=0.635229  map@2=0.675117  map@5=0.730891  map@10=0.741220  map@20=0.743543
mrr@1=0.635229  mrr@2=0.722415  mrr@5=0.760190  mrr@10=0.764332  mrr@20=0.765217
f1@1=0.557429  f1@2=0.548510  f1@5=0.379201  f1@10=0.228296  f1@20=0.126116

Epoch 72/100: 100%|██████████| 820/820 [00:11<00:00, 73.52it/s, bpr=0.0226, c=2.72, loss=0.131]

[VAL]
recall@1=0.513465  recall@2=0.714374  recall@5=0.915048  recall@10=0.962592  recall@20=0.984293
precision@1=0.622984  precision@2=0.460806  precision@5=0.248774  precision@10=0.132935  precision@20=0.068556
ndcg@1=0.622984  ndcg@2=0.693060  ndcg@5=0.778051  ndcg@10=0.796086  ndcg@20=0.802495
hit_rate@1=0.622984  hit_rate@2=0.797823  hit_rate@5=0.948387  hit_rate@10=0.977903  hit_rate@20=0.991452
map@1=0.622984  map@2=0.661653  map@5=0.718819  map@10=0.729608  map@20=0.732151
mrr@1=0.622984  mrr@2=0.710403  mrr@5=0.750073  mrr@10=0.754326  mrr@20=0.755308
f1@1=0.545756  f1@2=0.538476  f1@5=0.376925  f1@10=0.227356  f1@20=0.125925

[TEST]
recall@1=0.519406  recall@2=0.717711  recall@5=0.918083  recall@10=0.964704  recall@20=0.985832
precision@1=0.630235  precision@2=0.463394  precision@5=0.249613  precision@10=0.133175  precision@20=0.068553
ndcg@1=0.630235  ndcg@2=0.697920  ndcg@5=0.782958  ndcg@10=0.800535  ndcg@20=0.806716
hit_rate@1=0.630235  hit_rate@2=0.799372  hit_rate@5=0.950387  hit_rate@10=0.979301  hit_rate@20=0.992268
map@1=0.630235  map@2=0.667465  map@5=0.724767  map@10=0.735135  map@20=0.737583
mrr@1=0.630235  mrr@2=0.714803  mrr@5=0.754842  mrr@10=0.758949  mrr@20=0.759886
f1@1=0.552057  f1@2=0.541346  f1@5=0.378451  f1@10=0.227850  f1@20=0.125992

Epoch 73/100: 100%|██████████| 820/820 [00:11<00:00, 73.30it/s, bpr=0.0369, c=2.58, loss=0.14]

[VAL]
recall@1=0.519448  recall@2=0.720982  recall@5=0.916077  recall@10=0.962536  recall@20=0.984513
precision@1=0.628548  precision@2=0.464919  precision@5=0.248790  precision@10=0.132903  precision@20=0.068544
ndcg@1=0.628548  ndcg@2=0.699768  ndcg@5=0.782140  ndcg@10=0.799833  ndcg@20=0.806324
hit_rate@1=0.628548  hit_rate@2=0.805081  hit_rate@5=0.950081  hit_rate@10=0.977984  hit_rate@20=0.991855
map@1=0.628548  map@2=0.668367  map@5=0.723892  map@10=0.734597  map@20=0.737173
mrr@1=0.628548  mrr@2=0.716815  mrr@5=0.755144  mrr@10=0.759140  mrr@20=0.760148
f1@1=0.551509  f1@2=0.543363  f1@5=0.377072  f1@10=0.227298  f1@20=0.125916

[TEST]
recall@1=0.525045  recall@2=0.723513  recall@5=0.916528  recall@10=0.965262  recall@20=0.986630
precision@1=0.636598  precision@2=0.467018  precision@5=0.249259  precision@10=0.133183  precision@20=0.068613
ndcg@1=0.636598  ndcg@2=0.704012  ndcg@5=0.785659  ndcg@10=0.803857  ndcg@20=0.810117
hit_rate@1=0.636598  hit_rate@2=0.805090  hit_rate@5=0.949259  hit_rate@10=0.979704  hit_rate@20=0.993396
map@1=0.636598  map@2=0.673687  map@5=0.728790  map@10=0.739454  map@20=0.741894
mrr@1=0.636598  mrr@2=0.720844  mrr@5=0.759195  mrr@10=0.763469  mrr@20=0.764451
f1@1=0.557869  f1@2=0.545658  f1@5=0.377853  f1@10=0.227942  f1@20=0.126099

Epoch 74/100: 100%|██████████| 820/820 [00:11<00:00, 73.80it/s, bpr=0.041, c=2.57, loss=0.144]

[VAL]
recall@1=0.524500  recall@2=0.726076  recall@5=0.916939  recall@10=0.962739  recall@20=0.984132
precision@1=0.633871  precision@2=0.467419  precision@5=0.249403  precision@10=0.132944  precision@20=0.068488
ndcg@1=0.633871  ndcg@2=0.704733  ndcg@5=0.785844  ndcg@10=0.803303  ndcg@20=0.809603
hit_rate@1=0.633871  hit_rate@2=0.809597  hit_rate@5=0.950000  hit_rate@10=0.978226  hit_rate@20=0.991532
map@1=0.633871  map@2=0.673407  map@5=0.728719  map@10=0.739238  map@20=0.741728
mrr@1=0.633871  mrr@2=0.721734  mrr@5=0.759160  mrr@10=0.763278  mrr@20=0.764255
f1@1=0.556726  f1@2=0.546810  f1@5=0.377794  f1@10=0.227372  f1@20=0.125826

[TEST]
recall@1=0.527670  recall@2=0.728715  recall@5=0.919568  recall@10=0.965738  recall@20=0.985499
precision@1=0.638450  precision@2=0.469475  precision@5=0.250097  precision@10=0.133368  precision@20=0.068541
ndcg@1=0.638450  ndcg@2=0.708047  ndcg@5=0.789433  ndcg@10=0.806854  ndcg@20=0.812623
hit_rate@1=0.638450  hit_rate@2=0.811775  hit_rate@5=0.951756  hit_rate@10=0.979784  hit_rate@20=0.992026
map@1=0.638450  map@2=0.677010  map@5=0.732889  map@10=0.743252  map@20=0.745513
mrr@1=0.638450  mrr@2=0.725113  mrr@5=0.762638  mrr@10=0.766628  mrr@20=0.767511
f1@1=0.560292  f1@2=0.549068  f1@5=0.379141  f1@10=0.228197  f1@20=0.125961

Epoch 75/100: 100%|██████████| 820/820 [00:11<00:00, 73.61it/s, bpr=0.0399, c=2.61, loss=0.144]

[VAL]
recall@1=0.514999  recall@2=0.712335  recall@5=0.915607  recall@10=0.963576  recall@20=0.985504
precision@1=0.625645  precision@2=0.459960  precision@5=0.249097  precision@10=0.133040  precision@20=0.068621
ndcg@1=0.625645  ndcg@2=0.692481  ndcg@5=0.778685  ndcg@10=0.796776  ndcg@20=0.803254
hit_rate@1=0.625645  hit_rate@2=0.795565  hit_rate@5=0.948871  hit_rate@10=0.978871  hit_rate@20=0.992177
map@1=0.625645  map@2=0.661573  map@5=0.719536  map@10=0.730304  map@20=0.732892
mrr@1=0.625645  mrr@2=0.710605  mrr@5=0.750980  mrr@10=0.755233  mrr@20=0.756191
f1@1=0.547612  f1@2=0.537267  f1@5=0.377302  f1@10=0.227547  f1@20=0.126061

[TEST]
recall@1=0.510968  recall@2=0.714365  recall@5=0.918811  recall@10=0.965374  recall@20=0.986423
precision@1=0.621617  precision@2=0.461904  precision@5=0.249839  precision@10=0.133207  precision@20=0.068577
ndcg@1=0.621617  ndcg@2=0.692673  ndcg@5=0.779730  ndcg@10=0.797201  ndcg@20=0.803405
hit_rate@1=0.621617  hit_rate@2=0.797036  hit_rate@5=0.950870  hit_rate@10=0.980187  hit_rate@20=0.992832
map@1=0.621617  map@2=0.661364  map@5=0.720255  map@10=0.730519  map@20=0.733001
mrr@1=0.621617  mrr@2=0.709327  mrr@5=0.750180  mrr@10=0.754325  mrr@20=0.755243
f1@1=0.543536  f1@2=0.539293  f1@5=0.378799  f1@10=0.227948  f1@20=0.126046

Epoch 76/100: 100%|██████████| 820/820 [00:11<00:00, 73.48it/s, bpr=0.0393, c=2.59, loss=0.143]

[VAL]
recall@1=0.521090  recall@2=0.722560  recall@5=0.918203  recall@10=0.963223  recall@20=0.984759
precision@1=0.631935  precision@2=0.465806  precision@5=0.249726  precision@10=0.133032  precision@20=0.068565
ndcg@1=0.631935  ndcg@2=0.701368  ndcg@5=0.784621  ndcg@10=0.801694  ndcg@20=0.808025
hit_rate@1=0.631935  hit_rate@2=0.806290  hit_rate@5=0.950968  hit_rate@10=0.978387  hit_rate@20=0.992016
map@1=0.631935  map@2=0.669899  map@5=0.726534  map@10=0.736778  map@20=0.739281
mrr@1=0.631935  mrr@2=0.719113  mrr@5=0.757753  mrr@10=0.761669  mrr@20=0.762647
f1@1=0.553821  f1@2=0.544551  f1@5=0.378291  f1@10=0.227518  f1@20=0.125953

[TEST]
recall@1=0.521272  recall@2=0.727343  recall@5=0.918976  recall@10=0.965650  recall@20=0.985714
precision@1=0.633779  precision@2=0.469233  precision@5=0.249984  precision@10=0.133296  precision@20=0.068537
ndcg@1=0.633779  ndcg@2=0.705193  ndcg@5=0.786530  ndcg@10=0.804085  ndcg@20=0.809971
hit_rate@1=0.633779  hit_rate@2=0.809037  hit_rate@5=0.950789  hit_rate@10=0.979784  hit_rate@20=0.992429
map@1=0.633779  map@2=0.673808  map@5=0.729064  map@10=0.739429  map@20=0.741749
mrr@1=0.633779  mrr@2=0.721408  mrr@5=0.759384  mrr@10=0.763529  mrr@20=0.764445
f1@1=0.554475  f1@2=0.548448  f1@5=0.378902  f1@10=0.228090  f1@20=0.125963

Epoch 77/100: 100%|██████████| 820/820 [00:11<00:00, 73.55it/s, bpr=0.0434, c=2.58, loss=0.147]

[VAL]
recall@1=0.510390  recall@2=0.708094  recall@5=0.916953  recall@10=0.963427  recall@20=0.985206
precision@1=0.619597  precision@2=0.457016  precision@5=0.249452  precision@10=0.133073  precision@20=0.068613
ndcg@1=0.619597  ndcg@2=0.687740  ndcg@5=0.776702  ndcg@10=0.794290  ndcg@20=0.800689
hit_rate@1=0.619597  hit_rate@2=0.791774  hit_rate@5=0.950565  hit_rate@10=0.978790  hit_rate@20=0.992581
map@1=0.619597  map@2=0.656633  map@5=0.716374  map@10=0.726952  map@20=0.729480
mrr@1=0.619597  mrr@2=0.705685  mrr@5=0.747638  mrr@10=0.751686  mrr@20=0.752670
f1@1=0.542477  f1@2=0.533904  f1@5=0.377813  f1@10=0.227562  f1@20=0.126023

[TEST]
recall@1=0.514715  recall@2=0.711370  recall@5=0.918291  recall@10=0.965092  recall@20=0.986222
precision@1=0.624597  precision@2=0.459890  precision@5=0.249774  precision@10=0.133223  precision@20=0.068581
ndcg@1=0.624597  ndcg@2=0.691946  ndcg@5=0.779962  ndcg@10=0.797577  ndcg@20=0.803739
hit_rate@1=0.624597  hit_rate@2=0.793653  hit_rate@5=0.950789  hit_rate@10=0.979462  hit_rate@20=0.992912
map@1=0.624597  map@2=0.661546  map@5=0.720766  map@10=0.731186  map@20=0.733588
mrr@1=0.624597  mrr@2=0.709125  mrr@5=0.750701  mrr@10=0.754786  mrr@20=0.755743
f1@1=0.547067  f1@2=0.536896  f1@5=0.378634  f1@10=0.227960  f1@20=0.126039

Epoch 78/100: 100%|██████████| 820/820 [00:11<00:00, 73.50it/s, bpr=0.0333, c=2.66, loss=0.14]

[VAL]
recall@1=0.528909  recall@2=0.731304  recall@5=0.918957  recall@10=0.964262  recall@20=0.985544
precision@1=0.640242  precision@2=0.470847  precision@5=0.249984  precision@10=0.133194  precision@20=0.068629
ndcg@1=0.640242  ndcg@2=0.710131  ndcg@5=0.789848  ndcg@10=0.807007  ndcg@20=0.813277
hit_rate@1=0.640242  hit_rate@2=0.815968  hit_rate@5=0.951613  hit_rate@10=0.979113  hit_rate@20=0.992500
map@1=0.640242  map@2=0.678448  map@5=0.733238  map@10=0.743561  map@20=0.746041
mrr@1=0.640242  mrr@2=0.728105  mrr@5=0.764376  mrr@10=0.768280  mrr@20=0.769239
f1@1=0.561751  f1@2=0.550751  f1@5=0.378654  f1@10=0.227785  f1@20=0.126075

[TEST]
recall@1=0.528901  recall@2=0.736214  recall@5=0.921442  recall@10=0.965898  recall@20=0.986403
precision@1=0.640625  precision@2=0.474509  precision@5=0.250644  precision@10=0.133320  precision@20=0.068601
ndcg@1=0.640625  ndcg@2=0.713733  ndcg@5=0.792396  ndcg@10=0.809162  ndcg@20=0.815157
hit_rate@1=0.640625  hit_rate@2=0.818863  hit_rate@5=0.952803  hit_rate@10=0.979865  hit_rate@20=0.992832
map@1=0.640625  map@2=0.682204  map@5=0.736196  map@10=0.746180  map@20=0.748519
mrr@1=0.640625  mrr@2=0.729744  mrr@5=0.765860  mrr@10=0.769725  mrr@20=0.770655
f1@1=0.561807  f1@2=0.554959  f1@5=0.379927  f1@10=0.228147  f1@20=0.126074

Epoch 79/100: 100%|██████████| 820/820 [00:11<00:00, 73.60it/s, bpr=0.0362, c=2.75, loss=0.146]

[VAL]
recall@1=0.516866  recall@2=0.717242  recall@5=0.916842  recall@10=0.963084  recall@20=0.984764
precision@1=0.626613  precision@2=0.462863  precision@5=0.249387  precision@10=0.132984  precision@20=0.068569
ndcg@1=0.626613  ndcg@2=0.696368  ndcg@5=0.781131  ndcg@10=0.798662  ndcg@20=0.805065
hit_rate@1=0.626613  hit_rate@2=0.799919  hit_rate@5=0.949919  hit_rate@10=0.978306  hit_rate@20=0.991935
map@1=0.626613  map@2=0.665363  map@5=0.722630  map@10=0.733165  map@20=0.735706
mrr@1=0.626613  mrr@2=0.713306  mrr@5=0.752969  mrr@10=0.757078  mrr@20=0.758069
f1@1=0.549200  f1@2=0.540811  f1@5=0.377800  f1@10=0.227435  f1@20=0.125954

[TEST]
recall@1=0.521850  recall@2=0.722330  recall@5=0.919365  recall@10=0.965179  recall@20=0.985907
precision@1=0.634262  precision@2=0.466616  precision@5=0.250177  precision@10=0.133207  precision@20=0.068557
ndcg@1=0.634262  ndcg@2=0.702119  ndcg@5=0.785890  ndcg@10=0.803082  ndcg@20=0.809159
hit_rate@1=0.634262  hit_rate@2=0.804365  hit_rate@5=0.951031  hit_rate@10=0.979704  hit_rate@20=0.992188
map@1=0.634262  map@2=0.671392  map@5=0.728219  map@10=0.738369  map@20=0.740779
mrr@1=0.634262  mrr@2=0.719274  mrr@5=0.758430  mrr@10=0.762468  mrr@20=0.763361
f1@1=0.554944  f1@2=0.545069  f1@5=0.379164  f1@10=0.227945  f1@20=0.126005

Epoch 80/100: 100%|██████████| 820/820 [00:11<00:00, 73.71it/s, bpr=0.028, c=2.8, loss=0.14]

[VAL]
recall@1=0.523583  recall@2=0.728404  recall@5=0.918465  recall@10=0.963461  recall@20=0.984411
precision@1=0.634516  precision@2=0.469798  precision@5=0.249984  precision@10=0.133145  precision@20=0.068593
ndcg@1=0.634516  ndcg@2=0.706328  ndcg@5=0.787170  ndcg@10=0.804236  ndcg@20=0.810394
hit_rate@1=0.634516  hit_rate@2=0.812339  hit_rate@5=0.950806  hit_rate@10=0.978306  hit_rate@20=0.991694
map@1=0.634516  map@2=0.674577  map@5=0.729989  map@10=0.740224  map@20=0.742643
mrr@1=0.634516  mrr@2=0.723427  mrr@5=0.760524  mrr@10=0.764489  mrr@20=0.765459
f1@1=0.556401  f1@2=0.549154  f1@5=0.378624  f1@10=0.227670  f1@20=0.125971

[TEST]
recall@1=0.525768  recall@2=0.731957  recall@5=0.922543  recall@10=0.966301  recall@20=0.985679
precision@1=0.637162  precision@2=0.472092  precision@5=0.250918  precision@10=0.133400  precision@20=0.068565
ndcg@1=0.637162  ndcg@2=0.709668  ndcg@5=0.791083  ndcg@10=0.807615  ndcg@20=0.813307
hit_rate@1=0.637162  hit_rate@2=0.815158  hit_rate@5=0.953769  hit_rate@10=0.980106  hit_rate@20=0.992349
map@1=0.637162  map@2=0.678077  map@5=0.734120  map@10=0.743990  map@20=0.746229
mrr@1=0.637162  mrr@2=0.726160  mrr@5=0.763590  mrr@10=0.767358  mrr@20=0.768244
f1@1=0.558608  f1@2=0.551942  f1@5=0.380410  f1@10=0.228278  f1@20=0.126000

Epoch 81/100: 100%|██████████| 820/820 [00:11<00:00, 73.97it/s, bpr=0.0376, c=2.64, loss=0.143]

[VAL]
recall@1=0.508738  recall@2=0.707694  recall@5=0.913753  recall@10=0.961796  recall@20=0.984901
precision@1=0.617903  precision@2=0.457056  precision@5=0.248403  precision@10=0.132798  precision@20=0.068573
ndcg@1=0.617903  ndcg@2=0.686880  ndcg@5=0.774587  ndcg@10=0.792767  ndcg@20=0.799606
hit_rate@1=0.617903  hit_rate@2=0.791452  hit_rate@5=0.947984  hit_rate@10=0.977500  hit_rate@20=0.991935
map@1=0.617903  map@2=0.655585  map@5=0.714555  map@10=0.725460  map@20=0.728203
mrr@1=0.617903  mrr@2=0.704677  mrr@5=0.746069  mrr@10=0.750294  mrr@20=0.751368
f1@1=0.540930  f1@2=0.533784  f1@5=0.376348  f1@10=0.227108  f1@20=0.125973

[TEST]
recall@1=0.516637  recall@2=0.712957  recall@5=0.916625  recall@10=0.964119  recall@20=0.986040
precision@1=0.628222  precision@2=0.461501  precision@5=0.249178  precision@10=0.133078  precision@20=0.068577
ndcg@1=0.628222  ndcg@2=0.694152  ndcg@5=0.780086  ndcg@10=0.797967  ndcg@20=0.804393
hit_rate@1=0.628222  hit_rate@2=0.794700  hit_rate@5=0.949017  hit_rate@10=0.978576  hit_rate@20=0.992268
map@1=0.628222  map@2=0.664002  map@5=0.721451  map@10=0.731978  map@20=0.734515
mrr@1=0.628222  mrr@2=0.711461  mrr@5=0.752030  mrr@10=0.756219  mrr@20=0.757213
f1@1=0.549481  f1@2=0.538474  f1@5=0.377813  f1@10=0.227736  f1@20=0.126042

Epoch 82/100: 100%|██████████| 820/820 [00:11<00:00, 73.04it/s, bpr=0.0332, c=2.7, loss=0.141]

[VAL]
recall@1=0.515449  recall@2=0.715594  recall@5=0.915435  recall@10=0.963418  recall@20=0.984098
precision@1=0.624516  precision@2=0.461895  precision@5=0.248806  precision@10=0.133024  precision@20=0.068548
ndcg@1=0.624516  ndcg@2=0.694587  ndcg@5=0.779584  ndcg@10=0.797774  ndcg@20=0.803898
hit_rate@1=0.624516  hit_rate@2=0.799113  hit_rate@5=0.948952  hit_rate@10=0.978871  hit_rate@20=0.991452
map@1=0.624516  map@2=0.663407  map@5=0.720973  map@10=0.731854  map@20=0.734305
mrr@1=0.624516  mrr@2=0.711815  mrr@5=0.751513  mrr@10=0.755782  mrr@20=0.756672
f1@1=0.547594  f1@2=0.539692  f1@5=0.377043  f1@10=0.227498  f1@20=0.125899

[TEST]
recall@1=0.522571  recall@2=0.720094  recall@5=0.917531  recall@10=0.965220  recall@20=0.986021
precision@1=0.634423  precision@2=0.465045  precision@5=0.249452  precision@10=0.133264  precision@20=0.068601
ndcg@1=0.634423  ndcg@2=0.700762  ndcg@5=0.784658  ndcg@10=0.802592  ndcg@20=0.808702
hit_rate@1=0.634423  hit_rate@2=0.802513  hit_rate@5=0.949259  hit_rate@10=0.979543  hit_rate@20=0.992188
map@1=0.634423  map@2=0.670244  map@5=0.727246  map@10=0.737727  map@20=0.740129
mrr@1=0.634423  mrr@2=0.718468  mrr@5=0.757454  mrr@10=0.761766  mrr@20=0.762686
f1@1=0.555530  f1@2=0.543263  f1@5=0.378176  f1@10=0.228007  f1@20=0.126077

Epoch 83/100: 100%|██████████| 820/820 [00:11<00:00, 72.53it/s, bpr=0.055, c=2.66, loss=0.161]

[VAL]
recall@1=0.522305  recall@2=0.720123  recall@5=0.915787  recall@10=0.962888  recall@20=0.984026
precision@1=0.632823  precision@2=0.464516  precision@5=0.248903  precision@10=0.133000  precision@20=0.068565
ndcg@1=0.632823  ndcg@2=0.700418  ndcg@5=0.783134  ndcg@10=0.801022  ndcg@20=0.807310
hit_rate@1=0.632823  hit_rate@2=0.804274  hit_rate@5=0.949194  hit_rate@10=0.978226  hit_rate@20=0.991452
map@1=0.632823  map@2=0.669395  map@5=0.725253  map@10=0.735975  map@20=0.738516
mrr@1=0.632823  mrr@2=0.718548  mrr@5=0.757017  mrr@10=0.761172  mrr@20=0.762144
f1@1=0.554827  f1@2=0.542798  f1@5=0.377193  f1@10=0.227454  f1@20=0.125924

[TEST]
recall@1=0.523501  recall@2=0.724971  recall@5=0.917210  recall@10=0.965623  recall@20=0.986063
precision@1=0.634021  precision@2=0.467461  precision@5=0.249388  precision@10=0.133255  precision@20=0.068557
ndcg@1=0.634021  ndcg@2=0.703992  ndcg@5=0.785722  ndcg@10=0.803954  ndcg@20=0.809957
hit_rate@1=0.634021  hit_rate@2=0.806782  hit_rate@5=0.949984  hit_rate@10=0.980509  hit_rate@20=0.992671
map@1=0.634021  map@2=0.673164  map@5=0.728641  map@10=0.739371  map@20=0.741762
mrr@1=0.634021  mrr@2=0.720401  mrr@5=0.758638  mrr@10=0.763010  mrr@20=0.763879
f1@1=0.556137  f1@2=0.546559  f1@5=0.378073  f1@10=0.228040  f1@20=0.126004

Epoch 84/100: 100%|██████████| 820/820 [00:11<00:00, 72.36it/s, bpr=0.0421, c=2.58, loss=0.145]

[VAL]
recall@1=0.518767  recall@2=0.721629  recall@5=0.916384  recall@10=0.963664  recall@20=0.985305
precision@1=0.629758  precision@2=0.465282  precision@5=0.249065  precision@10=0.133073  precision@20=0.068577
ndcg@1=0.629758  ndcg@2=0.700089  ndcg@5=0.782487  ndcg@10=0.800369  ndcg@20=0.806721
hit_rate@1=0.629758  hit_rate@2=0.806371  hit_rate@5=0.949677  hit_rate@10=0.978710  hit_rate@20=0.992339
map@1=0.629758  map@2=0.668226  map@5=0.724100  map@10=0.734824  map@20=0.737319
mrr@1=0.629758  mrr@2=0.718024  mrr@5=0.756050  mrr@10=0.760123  mrr@20=0.761111
f1@1=0.551430  f1@2=0.543843  f1@5=0.377437  f1@10=0.227586  f1@20=0.125976

[TEST]
recall@1=0.523149  recall@2=0.725502  recall@5=0.919227  recall@10=0.965966  recall@20=0.986637
precision@1=0.634182  precision@2=0.467059  precision@5=0.249823  precision@10=0.133272  precision@20=0.068629
ndcg@1=0.634182  ndcg@2=0.703966  ndcg@5=0.786603  ndcg@10=0.804236  ndcg@20=0.810298
hit_rate@1=0.634182  hit_rate@2=0.807506  hit_rate@5=0.951756  hit_rate@10=0.980348  hit_rate@20=0.992590
map@1=0.634182  map@2=0.672801  map@5=0.729078  map@10=0.739574  map@20=0.741978
mrr@1=0.634182  mrr@2=0.720884  mrr@5=0.759359  mrr@10=0.763462  mrr@20=0.764324
f1@1=0.555911  f1@2=0.546518  f1@5=0.378809  f1@10=0.228086  f1@20=0.126125

Epoch 85/100: 100%|██████████| 820/820 [00:11<00:00, 72.81it/s, bpr=0.0355, c=2.73, loss=0.145]

[VAL]
recall@1=0.518501  recall@2=0.725947  recall@5=0.917856  recall@10=0.962989  recall@20=0.984652
precision@1=0.628710  precision@2=0.467984  precision@5=0.249548  precision@10=0.132968  precision@20=0.068560
ndcg@1=0.628710  ndcg@2=0.702754  ndcg@5=0.784444  ndcg@10=0.801593  ndcg@20=0.807974
hit_rate@1=0.628710  hit_rate@2=0.810565  hit_rate@5=0.950887  hit_rate@10=0.978629  hit_rate@20=0.992258
map@1=0.628710  map@2=0.670484  map@5=0.726419  map@10=0.736688  map@20=0.739215
mrr@1=0.628710  mrr@2=0.719637  mrr@5=0.757347  mrr@10=0.761337  mrr@20=0.762305
f1@1=0.550914  f1@2=0.547122  f1@5=0.378113  f1@10=0.227400  f1@20=0.125947

[TEST]
recall@1=0.530999  recall@2=0.730283  recall@5=0.920179  recall@10=0.965598  recall@20=0.986010
precision@1=0.643363  precision@2=0.470925  precision@5=0.250419  precision@10=0.133312  precision@20=0.068565
ndcg@1=0.643363  ndcg@2=0.710620  ndcg@5=0.791260  ndcg@10=0.808313  ndcg@20=0.814273
hit_rate@1=0.643363  hit_rate@2=0.812017  hit_rate@5=0.951595  hit_rate@10=0.980026  hit_rate@20=0.992590
map@1=0.643363  map@2=0.680151  map@5=0.735117  map@10=0.745158  map@20=0.747494
mrr@1=0.643363  mrr@2=0.727690  mrr@5=0.765080  mrr@10=0.769109  mrr@20=0.770009
f1@1=0.564203  f1@2=0.550533  f1@5=0.379532  f1@10=0.228095  f1@20=0.126008

Epoch 86/100: 100%|██████████| 820/820 [00:11<00:00, 73.55it/s, bpr=0.041, c=2.76, loss=0.151]

[VAL]
recall@1=0.528771  recall@2=0.736081  recall@5=0.920368  recall@10=0.961854  recall@20=0.984874
precision@1=0.640726  precision@2=0.473468  precision@5=0.250258  precision@10=0.132847  precision@20=0.068552
ndcg@1=0.640726  ndcg@2=0.713164  ndcg@5=0.791640  ndcg@10=0.807577  ndcg@20=0.814333
hit_rate@1=0.640726  hit_rate@2=0.821048  hit_rate@5=0.952984  hit_rate@10=0.977500  hit_rate@20=0.992339
map@1=0.640726  map@2=0.680786  map@5=0.735019  map@10=0.744784  map@20=0.747432
mrr@1=0.640726  mrr@2=0.730887  mrr@5=0.766466  mrr@10=0.770034  mrr@20=0.771136
f1@1=0.561769  f1@2=0.554196  f1@5=0.379173  f1@10=0.227196  f1@20=0.125937

[TEST]
recall@1=0.532112  recall@2=0.739695  recall@5=0.921840  recall@10=0.965793  recall@20=0.986745
precision@1=0.643202  precision@2=0.476079  precision@5=0.250773  precision@10=0.133360  precision@20=0.068621
ndcg@1=0.643202  ndcg@2=0.717102  ndcg@5=0.794685  ndcg@10=0.811268  ndcg@20=0.817330
hit_rate@1=0.643202  hit_rate@2=0.823534  hit_rate@5=0.953769  hit_rate@10=0.980026  hit_rate@20=0.993073
map@1=0.643202  map@2=0.685245  map@5=0.738930  map@10=0.748821  map@20=0.751170
mrr@1=0.643202  mrr@2=0.733368  mrr@5=0.768762  mrr@10=0.772491  mrr@20=0.773411
f1@1=0.564814  f1@2=0.557057  f1@5=0.380128  f1@10=0.228181  f1@20=0.126101

Epoch 87/100: 100%|██████████| 820/820 [00:11<00:00, 72.74it/s, bpr=0.0361, c=2.61, loss=0.141]

[VAL]
recall@1=0.536782  recall@2=0.741678  recall@5=0.920094  recall@10=0.963491  recall@20=0.984540
precision@1=0.649355  precision@2=0.477460  precision@5=0.250129  precision@10=0.133081  precision@20=0.068540
ndcg@1=0.649355  ndcg@2=0.720303  ndcg@5=0.795569  ndcg@10=0.812131  ndcg@20=0.818313
hit_rate@1=0.649355  hit_rate@2=0.825645  hit_rate@5=0.952258  hit_rate@10=0.978629  hit_rate@20=0.991855
map@1=0.649355  map@2=0.688730  map@5=0.740485  map@10=0.750510  map@20=0.752941
mrr@1=0.649355  mrr@2=0.737500  mrr@5=0.771630  mrr@10=0.775428  mrr@20=0.776391
f1@1=0.569903  f1@2=0.558550  f1@5=0.379035  f1@10=0.227604  f1@20=0.125906

[TEST]
recall@1=0.532717  recall@2=0.740333  recall@5=0.920854  recall@10=0.966161  recall@20=0.986056
precision@1=0.642961  precision@2=0.476120  precision@5=0.250612  precision@10=0.133425  precision@20=0.068585
ndcg@1=0.642961  ndcg@2=0.717331  ndcg@5=0.794574  ndcg@10=0.811661  ndcg@20=0.817468
hit_rate@1=0.642961  hit_rate@2=0.822407  hit_rate@5=0.952239  hit_rate@10=0.979945  hit_rate@20=0.992671
map@1=0.642961  map@2=0.685849  map@5=0.739394  map@10=0.749566  map@20=0.751826
mrr@1=0.642961  mrr@2=0.732684  mrr@5=0.768063  mrr@10=0.772025  mrr@20=0.772933
f1@1=0.565294  f1@2=0.557428  f1@5=0.379810  f1@10=0.228272  f1@20=0.126036

Epoch 88/100: 100%|██████████| 820/820 [00:11<00:00, 73.24it/s, bpr=0.0437, c=2.54, loss=0.145]

[VAL]
recall@1=0.540431  recall@2=0.745401  recall@5=0.919123  recall@10=0.963583  recall@20=0.985127
precision@1=0.652742  precision@2=0.479194  precision@5=0.250000  precision@10=0.133073  precision@20=0.068589
ndcg@1=0.652742  ndcg@2=0.723753  ndcg@5=0.797331  ndcg@10=0.814178  ndcg@20=0.820523
hit_rate@1=0.652742  hit_rate@2=0.829839  hit_rate@5=0.951210  hit_rate@10=0.978710  hit_rate@20=0.992339
map@1=0.652742  map@2=0.691996  map@5=0.743092  map@10=0.753181  map@20=0.755686
mrr@1=0.652742  mrr@2=0.741290  mrr@5=0.774171  mrr@10=0.778105  mrr@20=0.779098
f1@1=0.573575  f1@2=0.561051  f1@5=0.378731  f1@10=0.227588  f1@20=0.125995

[TEST]
recall@1=0.536273  recall@2=0.747452  recall@5=0.921366  recall@10=0.965180  recall@20=0.985417
precision@1=0.647793  precision@2=0.480227  precision@5=0.250677  precision@10=0.133296  precision@20=0.068545
ndcg@1=0.647793  ndcg@2=0.723596  ndcg@5=0.797621  ndcg@10=0.814143  ndcg@20=0.820067
hit_rate@1=0.647793  hit_rate@2=0.830219  hit_rate@5=0.952642  hit_rate@10=0.979220  hit_rate@20=0.991865
map@1=0.647793  map@2=0.691587  map@5=0.743101  map@10=0.752949  map@20=0.755281
mrr@1=0.647793  mrr@2=0.739006  mrr@5=0.772458  mrr@10=0.776244  mrr@20=0.777167
f1@1=0.569062  f1@2=0.562461  f1@5=0.379964  f1@10=0.228065  f1@20=0.125971

Epoch 89/100: 100%|██████████| 820/820 [00:11<00:00, 73.25it/s, bpr=0.0363, c=2.64, loss=0.142]

[VAL]
recall@1=0.511126  recall@2=0.709229  recall@5=0.915733  recall@10=0.961726  recall@20=0.985116
precision@1=0.620806  precision@2=0.458589  precision@5=0.248919  precision@10=0.132750  precision@20=0.068589
ndcg@1=0.620806  ndcg@2=0.689066  ndcg@5=0.776718  ndcg@10=0.794160  ndcg@20=0.801053
hit_rate@1=0.620806  hit_rate@2=0.791935  hit_rate@5=0.949194  hit_rate@10=0.977661  hit_rate@20=0.992500
map@1=0.620806  map@2=0.658266  map@5=0.717055  map@10=0.727513  map@20=0.730219
mrr@1=0.620806  mrr@2=0.706371  mrr@5=0.747827  mrr@10=0.751908  mrr@20=0.752985
f1@1=0.543485  f1@2=0.535270  f1@5=0.377181  f1@10=0.227054  f1@20=0.125986

[TEST]
recall@1=0.512279  recall@2=0.710717  recall@5=0.918946  recall@10=0.964293  recall@20=0.985925
precision@1=0.623067  precision@2=0.459407  precision@5=0.249936  precision@10=0.133070  precision@20=0.068577
ndcg@1=0.623067  ndcg@2=0.690601  ndcg@5=0.779445  ndcg@10=0.796486  ndcg@20=0.802818
hit_rate@1=0.623067  hit_rate@2=0.791479  hit_rate@5=0.951273  hit_rate@10=0.979059  hit_rate@20=0.992349
map@1=0.623067  map@2=0.660257  map@5=0.719848  map@10=0.729969  map@20=0.732459
mrr@1=0.623067  mrr@2=0.707273  mrr@5=0.749742  mrr@10=0.753675  mrr@20=0.754621
f1@1=0.544905  f1@2=0.536447  f1@5=0.378852  f1@10=0.227724  f1@20=0.126027

Epoch 90/100: 100%|██████████| 820/820 [00:11<00:00, 73.43it/s, bpr=0.0448, c=2.56, loss=0.147]

[VAL]
recall@1=0.515558  recall@2=0.710110  recall@5=0.913556  recall@10=0.961966  recall@20=0.984421
precision@1=0.625806  precision@2=0.458387  precision@5=0.248161  precision@10=0.132871  precision@20=0.068548
ndcg@1=0.625806  ndcg@2=0.691062  ndcg@5=0.777151  ndcg@10=0.795555  ndcg@20=0.802093
hit_rate@1=0.625806  hit_rate@2=0.793145  hit_rate@5=0.947258  hit_rate@10=0.977419  hit_rate@20=0.991935
map@1=0.625806  map@2=0.660524  map@5=0.718149  map@10=0.729145  map@20=0.731645
mrr@1=0.625806  mrr@2=0.709435  mrr@5=0.749961  mrr@10=0.754294  mrr@20=0.755305
f1@1=0.547966  f1@2=0.535539  f1@5=0.376106  f1@10=0.227216  f1@20=0.125918

[TEST]
recall@1=0.513348  recall@2=0.710726  recall@5=0.915528  recall@10=0.963389  recall@20=0.986115
precision@1=0.623309  precision@2=0.458964  precision@5=0.248840  precision@10=0.133022  precision@20=0.068577
ndcg@1=0.623309  ndcg@2=0.690886  ndcg@5=0.778007  ndcg@10=0.796102  ndcg@20=0.802734
hit_rate@1=0.623309  hit_rate@2=0.792848  hit_rate@5=0.948373  hit_rate@10=0.977851  hit_rate@20=0.992751
map@1=0.623309  map@2=0.660337  map@5=0.718915  map@10=0.729655  map@20=0.732249
mrr@1=0.623309  mrr@2=0.708119  mrr@5=0.749276  mrr@10=0.753502  mrr@20=0.754616
f1@1=0.545656  f1@2=0.536118  f1@5=0.377253  f1@10=0.227594  f1@20=0.126021

Epoch 91/100: 100%|██████████| 820/820 [00:11<00:00, 72.94it/s, bpr=0.0424, c=2.6, loss=0.147]

[VAL]
recall@1=0.522288  recall@2=0.719484  recall@5=0.915211  recall@10=0.962354  recall@20=0.984726
precision@1=0.632419  precision@2=0.464274  precision@5=0.248903  precision@10=0.132919  precision@20=0.068548
ndcg@1=0.632419  ndcg@2=0.699903  ndcg@5=0.782711  ndcg@10=0.800604  ndcg@20=0.807153
hit_rate@1=0.632419  hit_rate@2=0.802581  hit_rate@5=0.948871  hit_rate@10=0.977581  hit_rate@20=0.992097
map@1=0.632419  map@2=0.669234  map@5=0.725114  map@10=0.735861  map@20=0.738430
mrr@1=0.632419  mrr@2=0.717500  mrr@5=0.756125  mrr@10=0.760275  mrr@20=0.761324
f1@1=0.554762  f1@2=0.542493  f1@5=0.377047  f1@10=0.227331  f1@20=0.125925

[TEST]
recall@1=0.517843  recall@2=0.722096  recall@5=0.917292  recall@10=0.965757  recall@20=0.985912
precision@1=0.628383  precision@2=0.465891  precision@5=0.249275  precision@10=0.133360  precision@20=0.068545
ndcg@1=0.628383  ndcg@2=0.700066  ndcg@5=0.782924  ndcg@10=0.801224  ndcg@20=0.807078
hit_rate@1=0.628383  hit_rate@2=0.802996  hit_rate@5=0.949098  hit_rate@10=0.979865  hit_rate@20=0.992751
map@1=0.628383  map@2=0.669116  map@5=0.725149  map@10=0.735929  map@20=0.738203
mrr@1=0.628383  mrr@2=0.715689  mrr@5=0.754540  mrr@10=0.758919  mrr@20=0.759839
f1@1=0.550383  f1@2=0.544550  f1@5=0.377982  f1@10=0.228164  f1@20=0.125976

Epoch 92/100: 100%|██████████| 820/820 [00:11<00:00, 73.48it/s, bpr=0.0371, c=2.65, loss=0.143]

[VAL]
recall@1=0.518541  recall@2=0.714066  recall@5=0.916251  recall@10=0.962432  recall@20=0.985215
precision@1=0.627661  precision@2=0.460484  precision@5=0.249290  precision@10=0.132863  precision@20=0.068613
ndcg@1=0.627661  ndcg@2=0.694554  ndcg@5=0.780643  ndcg@10=0.798038  ndcg@20=0.804761
hit_rate@1=0.627661  hit_rate@2=0.797097  hit_rate@5=0.949839  hit_rate@10=0.978306  hit_rate@20=0.992500
map@1=0.627661  map@2=0.663952  map@5=0.722002  map@10=0.732369  map@20=0.735045
mrr@1=0.627661  mrr@2=0.712379  mrr@5=0.752792  mrr@10=0.756834  mrr@20=0.757845
f1@1=0.550703  f1@2=0.538241  f1@5=0.377581  f1@10=0.227216  f1@20=0.126027

[TEST]
recall@1=0.518444  recall@2=0.716456  recall@5=0.917517  recall@10=0.964254  recall@20=0.985735
precision@1=0.628785  precision@2=0.463193  precision@5=0.249533  precision@10=0.133151  precision@20=0.068516
ndcg@1=0.628785  ndcg@2=0.696859  ndcg@5=0.782024  ndcg@10=0.799642  ndcg@20=0.805894
hit_rate@1=0.628785  hit_rate@2=0.798486  hit_rate@5=0.949662  hit_rate@10=0.978818  hit_rate@20=0.992510
map@1=0.628785  map@2=0.666499  map@5=0.723757  map@10=0.734164  map@20=0.736588
mrr@1=0.628785  mrr@2=0.713636  mrr@5=0.753655  mrr@10=0.757814  mrr@20=0.758820
f1@1=0.550877  f1@2=0.540763  f1@5=0.378271  f1@10=0.227811  f1@20=0.125937

Epoch 93/100: 100%|██████████| 820/820 [00:11<00:00, 73.51it/s, bpr=0.0566, c=2.49, loss=0.156]

[VAL]
recall@1=0.510246  recall@2=0.701621  recall@5=0.910905  recall@10=0.961911  recall@20=0.984879
precision@1=0.619032  precision@2=0.453508  precision@5=0.247516  precision@10=0.132798  precision@20=0.068565
ndcg@1=0.619032  ndcg@2=0.683450  ndcg@5=0.772176  ndcg@10=0.791476  ndcg@20=0.798247
hit_rate@1=0.619032  hit_rate@2=0.784677  hit_rate@5=0.945887  hit_rate@10=0.977661  hit_rate@20=0.992339
map@1=0.619032  map@2=0.653266  map@5=0.712276  map@10=0.723769  map@20=0.726444
mrr@1=0.619032  mrr@2=0.701855  mrr@5=0.744238  mrr@10=0.748819  mrr@20=0.749889
f1@1=0.542253  f1@2=0.529389  f1@5=0.375045  f1@10=0.227137  f1@20=0.125955

[TEST]
recall@1=0.509772  recall@2=0.707473  recall@5=0.913848  recall@10=0.963218  recall@20=0.985885
precision@1=0.618154  precision@2=0.457434  precision@5=0.248373  precision@10=0.132957  precision@20=0.068573
ndcg@1=0.618154  ndcg@2=0.687363  ndcg@5=0.774758  ndcg@10=0.793315  ndcg@20=0.799971
hit_rate@1=0.618154  hit_rate@2=0.789465  hit_rate@5=0.947648  hit_rate@10=0.977851  hit_rate@20=0.992268
map@1=0.618154  map@2=0.656894  map@5=0.715195  map@10=0.726156  map@20=0.728772
mrr@1=0.618154  mrr@2=0.703810  mrr@5=0.745283  mrr@10=0.749566  mrr@20=0.750628
f1@1=0.541656  f1@2=0.533976  f1@5=0.376586  f1@10=0.227512  f1@20=0.126027

Epoch 94/100: 100%|██████████| 820/820 [00:11<00:00, 73.07it/s, bpr=0.0285, c=2.65, loss=0.135]

[VAL]
recall@1=0.525225  recall@2=0.726432  recall@5=0.916889  recall@10=0.963464  recall@20=0.985098
precision@1=0.635242  precision@2=0.467500  precision@5=0.249194  precision@10=0.133065  precision@20=0.068589
ndcg@1=0.635242  ndcg@2=0.705278  ndcg@5=0.786016  ndcg@10=0.803729  ndcg@20=0.810078
hit_rate@1=0.635242  hit_rate@2=0.810081  hit_rate@5=0.950403  hit_rate@10=0.978629  hit_rate@20=0.992500
map@1=0.635242  map@2=0.673911  map@5=0.728702  map@10=0.739389  map@20=0.741881
mrr@1=0.635242  mrr@2=0.722661  mrr@5=0.760081  mrr@10=0.764126  mrr@20=0.765115
f1@1=0.557634  f1@2=0.546957  f1@5=0.377605  f1@10=0.227572  f1@20=0.125993

[TEST]
recall@1=0.530124  recall@2=0.731557  recall@5=0.919667  recall@10=0.966110  recall@20=0.986075
precision@1=0.641269  precision@2=0.471448  precision@5=0.250113  precision@10=0.133409  precision@20=0.068573
ndcg@1=0.641269  ndcg@2=0.710923  ndcg@5=0.790556  ndcg@10=0.808064  ndcg@20=0.813871
hit_rate@1=0.641269  hit_rate@2=0.814111  hit_rate@5=0.951514  hit_rate@10=0.979945  hit_rate@20=0.992429
map@1=0.641269  map@2=0.680050  map@5=0.734324  map@10=0.744714  map@20=0.746972
mrr@1=0.641269  mrr@2=0.727690  mrr@5=0.764252  mrr@10=0.768291  mrr@20=0.769177
f1@1=0.562862  f1@2=0.551362  f1@5=0.379159  f1@10=0.228269  f1@20=0.126028

Epoch 95/100: 100%|██████████| 820/820 [00:11<00:00, 73.60it/s, bpr=0.0505, c=2.51, loss=0.151]

[VAL]
recall@1=0.515316  recall@2=0.717032  recall@5=0.914398  recall@10=0.962678  recall@20=0.985316
precision@1=0.624274  precision@2=0.462419  precision@5=0.248581  precision@10=0.132952  precision@20=0.068593
ndcg@1=0.624274  ndcg@2=0.695394  ndcg@5=0.779201  ndcg@10=0.797474  ndcg@20=0.804146
hit_rate@1=0.624274  hit_rate@2=0.800081  hit_rate@5=0.947823  hit_rate@10=0.978065  hit_rate@20=0.992581
map@1=0.624274  map@2=0.664113  map@5=0.720707  map@10=0.731591  map@20=0.734233
mrr@1=0.624274  mrr@2=0.712177  mrr@5=0.751378  mrr@10=0.755708  mrr@20=0.756779
f1@1=0.547357  f1@2=0.540488  f1@5=0.376632  f1@10=0.227372  f1@20=0.126007

[TEST]
recall@1=0.520837  recall@2=0.719357  recall@5=0.916663  recall@10=0.965175  recall@20=0.986530
precision@1=0.631443  precision@2=0.464119  precision@5=0.249114  precision@10=0.133223  precision@20=0.068585
ndcg@1=0.631443  ndcg@2=0.699307  ndcg@5=0.783232  ndcg@10=0.801506  ndcg@20=0.807753
hit_rate@1=0.631443  hit_rate@2=0.801144  hit_rate@5=0.949017  hit_rate@10=0.979462  hit_rate@20=0.992912
map@1=0.631443  map@2=0.668774  map@5=0.725617  map@10=0.736358  map@20=0.738825
mrr@1=0.631443  mrr@2=0.716293  mrr@5=0.755615  mrr@10=0.759953  mrr@20=0.760916
f1@1=0.553435  f1@2=0.542460  f1@5=0.377789  f1@10=0.227962  f1@20=0.126060

Epoch 96/100: 100%|██████████| 820/820 [00:11<00:00, 73.70it/s, bpr=0.0462, c=2.64, loss=0.152]

[VAL]
recall@1=0.517509  recall@2=0.718418  recall@5=0.916286  recall@10=0.963198  recall@20=0.985607
precision@1=0.626935  precision@2=0.462944  precision@5=0.248823  precision@10=0.133008  precision@20=0.068633
ndcg@1=0.626935  ndcg@2=0.697155  ndcg@5=0.780985  ndcg@10=0.798903  ndcg@20=0.805486
hit_rate@1=0.626935  hit_rate@2=0.802419  hit_rate@5=0.950242  hit_rate@10=0.978629  hit_rate@20=0.992419
map@1=0.626935  map@2=0.665665  map@5=0.722196  map@10=0.733045  map@20=0.735637
mrr@1=0.626935  mrr@2=0.714677  mrr@5=0.753817  mrr@10=0.757902  mrr@20=0.758901
f1@1=0.549723  f1@2=0.541218  f1@5=0.377152  f1@10=0.227474  f1@20=0.126077

[TEST]
recall@1=0.523896  recall@2=0.720674  recall@5=0.918181  recall@10=0.964551  recall@20=0.985972
precision@1=0.634987  precision@2=0.465085  precision@5=0.249791  precision@10=0.133094  precision@20=0.068545
ndcg@1=0.634987  ndcg@2=0.701554  ndcg@5=0.785414  ndcg@10=0.802845  ndcg@20=0.809127
hit_rate@1=0.634987  hit_rate@2=0.804043  hit_rate@5=0.950950  hit_rate@10=0.979301  hit_rate@20=0.992590
map@1=0.634987  map@2=0.670909  map@5=0.727722  map@10=0.738061  map@20=0.740553
mrr@1=0.634987  mrr@2=0.719515  mrr@5=0.758511  mrr@10=0.762563  mrr@20=0.763526
f1@1=0.556598  f1@2=0.543473  f1@5=0.378577  f1@10=0.227780  f1@20=0.125990

Epoch 97/100: 100%|██████████| 820/820 [00:11<00:00, 73.10it/s, bpr=0.0351, c=2.66, loss=0.142]

[VAL]
recall@1=0.514399  recall@2=0.710614  recall@5=0.916216  recall@10=0.962058  recall@20=0.985553
precision@1=0.622742  precision@2=0.458831  precision@5=0.249000  precision@10=0.132831  precision@20=0.068617
ndcg@1=0.622742  ndcg@2=0.690843  ndcg@5=0.778100  ndcg@10=0.795542  ndcg@20=0.802437
hit_rate@1=0.622742  hit_rate@2=0.793871  hit_rate@5=0.949355  hit_rate@10=0.977903  hit_rate@20=0.992903
map@1=0.622742  map@2=0.660181  map@5=0.718824  map@10=0.729268  map@20=0.731992
mrr@1=0.622742  mrr@2=0.708306  mrr@5=0.749229  mrr@10=0.753313  mrr@20=0.754393
f1@1=0.546283  f1@2=0.535954  f1@5=0.377308  f1@10=0.227196  f1@20=0.126046

[TEST]
recall@1=0.516257  recall@2=0.715015  recall@5=0.917071  recall@10=0.964519  recall@20=0.986168
precision@1=0.627416  precision@2=0.462226  precision@5=0.249533  precision@10=0.133094  precision@20=0.068561
ndcg@1=0.627416  ndcg@2=0.695129  ndcg@5=0.780873  ndcg@10=0.798632  ndcg@20=0.804992
hit_rate@1=0.627416  hit_rate@2=0.796553  hit_rate@5=0.949017  hit_rate@10=0.979381  hit_rate@20=0.992590
map@1=0.627416  map@2=0.664667  map@5=0.722437  map@10=0.732797  map@20=0.735319
mrr@1=0.627416  mrr@2=0.711985  mrr@5=0.752306  mrr@10=0.756628  mrr@20=0.757584
f1@1=0.548998  f1@2=0.539679  f1@5=0.378182  f1@10=0.227769  f1@20=0.126015

Epoch 98/100: 100%|██████████| 820/820 [00:11<00:00, 73.53it/s, bpr=0.0585, c=2.55, loss=0.161]

[VAL]
recall@1=0.525817  recall@2=0.724765  recall@5=0.918105  recall@10=0.963501  recall@20=0.985116
precision@1=0.636290  precision@2=0.467097  precision@5=0.249645  precision@10=0.133073  precision@20=0.068601
ndcg@1=0.636290  ndcg@2=0.704596  ndcg@5=0.786544  ndcg@10=0.803798  ndcg@20=0.810172
hit_rate@1=0.636290  hit_rate@2=0.807823  hit_rate@5=0.950726  hit_rate@10=0.978468  hit_rate@20=0.992016
map@1=0.636290  map@2=0.673730  map@5=0.729288  map@10=0.739654  map@20=0.742169
mrr@1=0.636290  mrr@2=0.722056  mrr@5=0.760106  mrr@10=0.764083  mrr@20=0.765076
f1@1=0.558379  f1@2=0.546155  f1@5=0.378266  f1@10=0.227603  f1@20=0.126019

[TEST]
recall@1=0.523414  recall@2=0.727085  recall@5=0.920394  recall@10=0.965379  recall@20=0.985744
precision@1=0.632974  precision@2=0.468992  precision@5=0.250322  precision@10=0.133328  precision@20=0.068565
ndcg@1=0.632974  ndcg@2=0.705463  ndcg@5=0.787758  ndcg@10=0.804726  ndcg@20=0.810701
hit_rate@1=0.632974  hit_rate@2=0.809117  hit_rate@5=0.951756  hit_rate@10=0.979059  hit_rate@20=0.992107
map@1=0.632974  map@2=0.674493  map@5=0.730618  map@10=0.740695  map@20=0.743050
mrr@1=0.632974  mrr@2=0.721045  mrr@5=0.759292  mrr@10=0.763171  mrr@20=0.764131
f1@1=0.555679  f1@2=0.548171  f1@5=0.379461  f1@10=0.228118  f1@20=0.126007

Epoch 99/100: 100%|██████████| 820/820 [00:11<00:00, 73.65it/s, bpr=0.0356, c=2.73, loss=0.145]

[VAL]
recall@1=0.527821  recall@2=0.732727  recall@5=0.922012  recall@10=0.964469  recall@20=0.985190
precision@1=0.638387  precision@2=0.471774  precision@5=0.250710  precision@10=0.133185  precision@20=0.068593
ndcg@1=0.638387  ndcg@2=0.710631  ndcg@5=0.791133  ndcg@10=0.807398  ndcg@20=0.813531
hit_rate@1=0.638387  hit_rate@2=0.816694  hit_rate@5=0.954355  hit_rate@10=0.979758  hit_rate@20=0.992581
map@1=0.638387  map@2=0.678911  map@5=0.734108  map@10=0.744043  map@20=0.746480
mrr@1=0.638387  mrr@2=0.727540  mrr@5=0.764495  mrr@10=0.768163  mrr@20=0.769099
f1@1=0.560391  f1@2=0.551889  f1@5=0.379876  f1@10=0.227802  f1@20=0.126005

[TEST]
recall@1=0.530695  recall@2=0.737758  recall@5=0.924243  recall@10=0.967116  recall@20=0.985538
precision@1=0.642316  precision@2=0.475314  precision@5=0.251546  precision@10=0.133473  precision@20=0.068549
ndcg@1=0.642316  ndcg@2=0.715413  ndcg@5=0.794819  ndcg@10=0.810912  ndcg@20=0.816385
hit_rate@1=0.642316  hit_rate@2=0.820151  hit_rate@5=0.955300  hit_rate@10=0.981153  hit_rate@20=0.992349
map@1=0.642316  map@2=0.683976  map@5=0.738628  map@10=0.748200  map@20=0.750402
mrr@1=0.642316  mrr@2=0.731234  mrr@5=0.767664  mrr@10=0.771305  mrr@20=0.772123
f1@1=0.563599  f1@2=0.555957  f1@5=0.381234  f1@10=0.228416  f1@20=0.125977

Epoch 100/100: 100%|██████████| 820/820 [00:11<00:00, 73.09it/s, bpr=0.0284, c=2.66, loss=0.135]

[VAL]
recall@1=0.525813  recall@2=0.728932  recall@5=0.917700  recall@10=0.963634  recall@20=0.984658
precision@1=0.636613  precision@2=0.468831  precision@5=0.249548  precision@10=0.133153  precision@20=0.068548
ndcg@1=0.636613  ndcg@2=0.707196  ndcg@5=0.787251  ndcg@10=0.804717  ndcg@20=0.810904
hit_rate@1=0.636613  hit_rate@2=0.812823  hit_rate@5=0.950887  hit_rate@10=0.978710  hit_rate@20=0.991935
map@1=0.636613  map@2=0.675484  map@5=0.730042  map@10=0.740583  map@20=0.743035
mrr@1=0.636613  mrr@2=0.724718  mrr@5=0.761487  mrr@10=0.765470  mrr@20=0.766453
f1@1=0.558462  f1@2=0.548669  f1@5=0.378058  f1@10=0.227683  f1@20=0.125919

[TEST]
recall@1=0.524650  recall@2=0.730813  recall@5=0.919472  recall@10=0.965324  recall@20=0.985728
precision@1=0.636276  precision@2=0.471368  precision@5=0.250113  precision@10=0.133304  precision@20=0.068549
ndcg@1=0.636276  ndcg@2=0.708633  ndcg@5=0.788790  ndcg@10=0.806059  ndcg@20=0.812015
hit_rate@1=0.636276  hit_rate@2=0.813628  hit_rate@5=0.951514  hit_rate@10=0.979059  hit_rate@20=0.992429
map@1=0.636276  map@2=0.677090  map@5=0.732025  map@10=0.742248  map@20=0.744557
mrr@1=0.636276  mrr@2=0.724952  mrr@5=0.761939  mrr@10=0.765859  mrr@20=0.766835
f1@1=0.557572  f1@2=0.550981  f1@5=0.379102  f1@10=0.228081  f1@20=0.125983

,epoch,val_recall@1,val_recall@2,val_recall@5,val_recall@10,val_recall@20,val_precision@1,val_precision@2,val_precision@5,val_precision@10,...,test_mrr@1,test_mrr@2,test_mrr@5,test_mrr@10,test_mrr@20,test_f1@1,test_f1@2,test_f1@5,test_f1@10,test_f1@20
0,1,0.335721,0.478756,0.817926,0.941038,0.977361,0.434113,0.328669,0.222935,0.129976,...,0.431540,0.496053,0.573535,0.586829,0.588606,0.361516,0.376378,0.338593,0.222602,0.125101
1,2,0.390247,0.546512,0.850609,0.949690,0.979880,0.493629,0.368427,0.231968,0.131056,...,0.483086,0.553439,0.623484,0.633702,0.635284,0.410456,0.417765,0.352196,0.224401,0.125372
2,3,0.404761,0.562623,0.857423,0.953509,0.982531,0.508952,0.376411,0.234048,0.131629,...,0.498470,0.572688,0.638599,0.648392,0.649803,0.424901,0.433591,0.355287,0.225359,0.125531
3,4,0.462694,0.633195,0.875433,0.956241,0.982363,0.570242,0.416008,0.239177,0.132073,...,0.558231,0.639054,0.690750,0.699194,0.700408,0.482398,0.483491,0.362461,0.226336,0.125681
4,5,0.477018,0.654747,0.883318,0.957218,0.982886,0.585161,0.428145,0.241032,0.132169,...,0.579736,0.660519,0.708470,0.716102,0.717327,0.503921,0.497870,0.365358,0.226384,0.125728
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,0.517509,0.718418,0.916286,0.963198,0.985607,0.626935,0.462944,0.248823,0.133008,...,0.634987,0.719515,0.758511,0.762563,0.763526,0.556598,0.543473,0.378577,0.227780,0.125990
96,97,0.514399,0.710614,0.916216,0.962058,0.985553,0.622742,0.458831,0.249000,0.132831,...,0.627416,0.711985,0.752306,0.756628,0.757584,0.548998,0.539679,0.378182,0.227769,0.126015
97,98,0.525817,0.724765,0.918105,0.963501,0.985116,0.636290,0.467097,0.249645,0.133073,...,0.632974,0.721045,0.759292,0.763171,0.764131,0.555679,0.548171,0.379461,0.228118,0.126007
98,99,0.527821,0.732727,0.922012,0.964469,0.985190,0.638387,0.471774,0.250710,0.133185,...,0.642316,0.731234,0.767664,0.771305,0.772123,0.563599,0.555957,0.381234,0.228416,0.125977
99,100,0.525813,0.728932,0.917700,0.963634,0.984658,0.636613,0.468831,0.249548,0.133153,...,0.636276,0.724952,0.761939,0.765859,0.766835,0.557572,0.550981,0.379102,0.228081,0.125983

## Run global attention experiment

In [11]:
global_attention_conf = make_experiment_conf(
    base_conf,
    attention_type="global",
    fusion_type="none",
    epochs=100,
)

global_attention_output = train_notebook(
    global_attention_conf,
    experiment_name="step1a_global_attention"
)

global_attention_output["history_df"]

>>>>>>>>>>B-I statistics>>>>>>>>>>
Average interactions 5.757723808288574
Non-zero rows 0.9967479674796748
Non-zero columns 1.0
Matrix density 0.002042470229597649
>>>>>>>>>>U-I statistics>>>>>>>>>>
Average interactions 30.47064208984375
Non-zero rows 1.0
Non-zero columns 0.5001773678609436
Matrix density 0.010809025126048253
>>>>>>>>>>U-B statistics in train>>>>>>>>>>
Average interactions 1.7729297876358032
Non-zero rows 0.8142673955591551
Non-zero columns 0.3382113821138211
Matrix density 0.0028828125900210205
>>>>>>>>>>U-B statistics in tune>>>>>>>>>>
Average interactions 0.5909765958786011
Non-zero rows 0.41843828035364783
Non-zero columns 0.27479674796747966
Matrix density 0.0009609375300070068
>>>>>>>>>>U-B statistics in test>>>>>>>>>>
Average interactions 0.5909765958786011
Non-zero rows 0.4189782007153945
Non-zero columns 0.2780487804878049
Matrix density 0.0009609375300070068

Epoch 1/100: 100%|██████████| 820/820 [00:21<00:00, 37.41it/s, bpr=0.119, c=3.42, loss=0.256]

[VAL]
recall@1=0.393726  recall@2=0.559011  recall@5=0.805930  recall@10=0.939555  recall@20=0.976257
precision@1=0.496855  precision@2=0.371048  precision@5=0.219032  precision@10=0.129629  precision@20=0.067883
ndcg@1=0.496855  ndcg@2=0.545739  ndcg@5=0.648289  ndcg@10=0.696659  ndcg@20=0.707318
hit_rate@1=0.496855  hit_rate@2=0.646774  hit_rate@5=0.859194  hit_rate@10=0.960000  hit_rate@20=0.986210
map@1=0.496855  map@2=0.515746  map@5=0.578940  map@10=0.604638  map@20=0.608676
mrr@1=0.496855  mrr@2=0.571815  mrr@5=0.624792  mrr@10=0.638988  mrr@20=0.640950
f1@1=0.424071  f1@2=0.427527  f1@5=0.331969  f1@10=0.221799  f1@20=0.124747

[TEST]
recall@1=0.388874  recall@2=0.559708  recall@5=0.807011  recall@10=0.939672  recall@20=0.977304
precision@1=0.491382  precision@2=0.373228  precision@5=0.219749  precision@10=0.129679  precision@20=0.067856
ndcg@1=0.491382  ndcg@2=0.545220  ndcg@5=0.647428  ndcg@10=0.695154  ndcg@20=0.706002
hit_rate@1=0.491382  hit_rate@2=0.647229  hit_rate@5=0.859375  hit_rate@10=0.959971  hit_rate@20=0.986227
map@1=0.491382  map@2=0.515061  map@5=0.577768  map@10=0.602896  map@20=0.607010
mrr@1=0.491382  mrr@2=0.569306  mrr@5=0.622019  mrr@10=0.636170  mrr@20=0.638153
f1@1=0.418937  f1@2=0.429004  f1@5=0.332936  f1@10=0.221910  f1@20=0.124761

Saved new best checkpoint at epoch 1

Epoch 2/100: 100%|██████████| 820/820 [00:21<00:00, 37.39it/s, bpr=0.0579, c=3.18, loss=0.185]

[VAL]
recall@1=0.480969  recall@2=0.653415  recall@5=0.858813  recall@10=0.950231  recall@20=0.979047
precision@1=0.591129  precision@2=0.426290  precision@5=0.234387  precision@10=0.131129  precision@20=0.068137
ndcg@1=0.591129  ndcg@2=0.641213  ndcg@5=0.727277  ndcg@10=0.760713  ndcg@20=0.769210
hit_rate@1=0.591129  hit_rate@2=0.741210  hit_rate@5=0.901935  hit_rate@10=0.969435  hit_rate@20=0.988065
map@1=0.591129  map@2=0.611552  map@5=0.667694  map@10=0.685922  map@20=0.689284
mrr@1=0.591129  mrr@2=0.666169  mrr@5=0.707860  mrr@10=0.717634  mrr@20=0.719044
f1@1=0.513454  f1@2=0.495407  f1@5=0.354760  f1@10=0.224302  f1@20=0.125186

[TEST]
recall@1=0.476981  recall@2=0.655029  recall@5=0.860164  recall@10=0.950822  recall@20=0.980329
precision@1=0.587065  precision@2=0.428721  precision@5=0.234584  precision@10=0.131322  precision@20=0.068146
ndcg@1=0.587065  ndcg@2=0.641443  ndcg@5=0.726877  ndcg@10=0.759990  ndcg@20=0.768536
hit_rate@1=0.587065  hit_rate@2=0.743396  hit_rate@5=0.902384  hit_rate@10=0.968589  hit_rate@20=0.988402
map@1=0.587065  map@2=0.611268  map@5=0.667076  map@10=0.685046  map@20=0.688336
mrr@1=0.587065  mrr@2=0.665230  mrr@5=0.706151  mrr@10=0.715707  mrr@20=0.717190
f1@1=0.509439  f1@2=0.497445  f1@5=0.355261  f1@10=0.224646  f1@20=0.125245

Saved new best checkpoint at epoch 2

Epoch 3/100: 100%|██████████| 820/820 [00:21<00:00, 37.67it/s, bpr=0.0673, c=2.88, loss=0.183]

[VAL]
recall@1=0.536070  recall@2=0.717269  recall@5=0.888246  recall@10=0.953289  recall@20=0.980303
precision@1=0.647984  precision@2=0.461613  precision@5=0.242016  precision@10=0.131613  precision@20=0.068238
ndcg@1=0.647984  ndcg@2=0.703039  ndcg@5=0.775986  ndcg@10=0.799990  ndcg@20=0.807961
hit_rate@1=0.647984  hit_rate@2=0.805161  hit_rate@5=0.926048  hit_rate@10=0.971694  hit_rate@20=0.989113
map@1=0.647984  map@2=0.672762  map@5=0.723346  map@10=0.736798  map@20=0.739980
mrr@1=0.647984  mrr@2=0.726573  mrr@5=0.759960  mrr@10=0.766475  mrr@20=0.767791
f1@1=0.569170  f1@2=0.540120  f1@5=0.366424  f1@10=0.225090  f1@20=0.125360

[TEST]
recall@1=0.528791  recall@2=0.714833  recall@5=0.890119  recall@10=0.955863  recall@20=0.982421
precision@1=0.641994  precision@2=0.460656  precision@5=0.242445  precision@10=0.131910  precision@20=0.068343
ndcg@1=0.641994  ndcg@2=0.699046  ndcg@5=0.773694  ndcg@10=0.797924  ndcg@20=0.805697
hit_rate@1=0.641994  hit_rate@2=0.803238  hit_rate@5=0.926385  hit_rate@10=0.973180  hit_rate@20=0.989610
map@1=0.641994  map@2=0.668009  map@5=0.719681  map@10=0.733156  map@20=0.736238
mrr@1=0.641994  mrr@2=0.722616  mrr@5=0.756308  mrr@10=0.763048  mrr@20=0.764254
f1@1=0.562269  f1@2=0.538752  f1@5=0.367315  f1@10=0.225716  f1@20=0.125595

Saved new best checkpoint at epoch 3

Epoch 4/100: 100%|██████████| 820/820 [00:21<00:00, 37.64it/s, bpr=0.0746, c=2.78, loss=0.186]

[VAL]
recall@1=0.555337  recall@2=0.741309  recall@5=0.905640  recall@10=0.957361  recall@20=0.982297
precision@1=0.667258  precision@2=0.474435  precision@5=0.246548  precision@10=0.132177  precision@20=0.068415
ndcg@1=0.667258  ndcg@2=0.725424  ndcg@5=0.796785  ndcg@10=0.816035  ndcg@20=0.823426
hit_rate@1=0.667258  hit_rate@2=0.828952  hit_rate@5=0.940565  hit_rate@10=0.974677  hit_rate@20=0.990484
map@1=0.667258  map@2=0.694738  map@5=0.745696  map@10=0.756835  map@20=0.759806
mrr@1=0.667258  mrr@2=0.748105  mrr@5=0.779991  mrr@10=0.784754  mrr@20=0.785931
f1@1=0.588455  f1@2=0.556754  f1@5=0.373432  f1@10=0.226056  f1@20=0.125669

[TEST]
recall@1=0.543308  recall@2=0.739541  recall@5=0.906896  recall@10=0.959901  recall@20=0.983463
precision@1=0.654317  precision@2=0.473421  precision@5=0.246843  precision@10=0.132498  precision@20=0.068420
ndcg@1=0.654317  ndcg@2=0.719944  ndcg@5=0.792910  ndcg@10=0.812527  ndcg@20=0.819459
hit_rate@1=0.654317  hit_rate@2=0.826031  hit_rate@5=0.940963  hit_rate@10=0.976079  hit_rate@20=0.990335
map@1=0.654317  map@2=0.688285  map@5=0.740317  map@10=0.751566  map@20=0.754357
mrr@1=0.654317  mrr@2=0.740174  mrr@5=0.773152  mrr@10=0.778091  mrr@20=0.779136
f1@1=0.576136  f1@2=0.555459  f1@5=0.374062  f1@10=0.226689  f1@20=0.125730

Saved new best checkpoint at epoch 4

Epoch 5/100: 100%|██████████| 820/820 [00:21<00:00, 37.53it/s, bpr=0.0511, c=2.71, loss=0.159]

[VAL]
recall@1=0.556700  recall@2=0.747001  recall@5=0.914106  recall@10=0.958971  recall@20=0.981927
precision@1=0.668306  precision@2=0.476613  precision@5=0.248726  precision@10=0.132403  precision@20=0.068375
ndcg@1=0.668306  ndcg@2=0.729225  ndcg@5=0.802626  ndcg@10=0.819474  ndcg@20=0.826228
hit_rate@1=0.668306  hit_rate@2=0.832419  hit_rate@5=0.947016  hit_rate@10=0.975645  hit_rate@20=0.990000
map@1=0.668306  map@2=0.698427  map@5=0.751145  map@10=0.761062  map@20=0.763754
mrr@1=0.668306  mrr@2=0.750363  mrr@5=0.783538  mrr@10=0.787550  mrr@20=0.788588
f1@1=0.589665  f1@2=0.560162  f1@5=0.376849  f1@10=0.226457  f1@20=0.125597

[TEST]
recall@1=0.543980  recall@2=0.744802  recall@5=0.914209  recall@10=0.960710  recall@20=0.983541
precision@1=0.654317  precision@2=0.476482  precision@5=0.249082  precision@10=0.132547  precision@20=0.068380
ndcg@1=0.654317  ndcg@2=0.723480  ndcg@5=0.798323  ndcg@10=0.815479  ndcg@20=0.822177
hit_rate@1=0.654317  hit_rate@2=0.830622  hit_rate@5=0.946037  hit_rate@10=0.976804  hit_rate@20=0.990979
map@1=0.654317  map@2=0.691487  map@5=0.745580  map@10=0.755442  map@20=0.758088
mrr@1=0.654317  mrr@2=0.742469  mrr@5=0.776278  mrr@10=0.780551  mrr@20=0.781588
f1@1=0.576666  f1@2=0.559284  f1@5=0.377345  f1@10=0.226818  f1@20=0.125663

Epoch 6/100: 100%|██████████| 820/820 [00:21<00:00, 37.51it/s, bpr=0.0396, c=2.6, loss=0.144]

[VAL]
recall@1=0.559629  recall@2=0.748538  recall@5=0.919106  recall@10=0.960634  recall@20=0.983098
precision@1=0.670806  precision@2=0.476976  precision@5=0.250065  precision@10=0.132589  precision@20=0.068435
ndcg@1=0.670806  ndcg@2=0.731021  ndcg@5=0.806640  ndcg@10=0.822340  ndcg@20=0.828962
hit_rate@1=0.670806  hit_rate@2=0.834032  hit_rate@5=0.951129  hit_rate@10=0.977016  hit_rate@20=0.990887
map@1=0.670806  map@2=0.700302  map@5=0.754879  map@10=0.764298  map@20=0.766921
mrr@1=0.670806  mrr@2=0.752419  mrr@5=0.786743  mrr@10=0.790386  mrr@20=0.791384
f1@1=0.592527  f1@2=0.560937  f1@5=0.378867  f1@10=0.226807  f1@20=0.125729

[TEST]
recall@1=0.548504  recall@2=0.744814  recall@5=0.919231  recall@10=0.962274  recall@20=0.984514
precision@1=0.658747  precision@2=0.476401  precision@5=0.249968  precision@10=0.132869  precision@20=0.068488
ndcg@1=0.658747  ndcg@2=0.725102  ndcg@5=0.802530  ndcg@10=0.818730  ndcg@20=0.825236
hit_rate@1=0.658747  hit_rate@2=0.830219  hit_rate@5=0.950387  hit_rate@10=0.977448  hit_rate@20=0.991140
map@1=0.658747  map@2=0.693822  map@5=0.749726  map@10=0.759275  map@20=0.761840
mrr@1=0.658747  mrr@2=0.744483  mrr@5=0.780070  mrr@10=0.783869  mrr@20=0.784868
f1@1=0.581078  f1@2=0.559286  f1@5=0.379002  f1@10=0.227304  f1@20=0.125857

Saved new best checkpoint at epoch 6

Epoch 7/100: 100%|██████████| 820/820 [00:21<00:00, 37.58it/s, bpr=0.031, c=2.83, loss=0.144]

[VAL]
recall@1=0.552812  recall@2=0.747292  recall@5=0.918845  recall@10=0.960480  recall@20=0.983200
precision@1=0.662984  precision@2=0.476613  precision@5=0.249887  precision@10=0.132605  precision@20=0.068464
ndcg@1=0.662984  ndcg@2=0.727689  ndcg@5=0.803762  ndcg@10=0.819564  ndcg@20=0.826275
hit_rate@1=0.662984  hit_rate@2=0.831371  hit_rate@5=0.950645  hit_rate@10=0.976613  hit_rate@20=0.991210
map@1=0.662984  map@2=0.696694  map@5=0.751301  map@10=0.760796  map@20=0.763462
mrr@1=0.662984  mrr@2=0.747177  mrr@5=0.782298  mrr@10=0.785947  mrr@20=0.787012
f1@1=0.585456  f1@2=0.560283  f1@5=0.378648  f1@10=0.226809  f1@20=0.125762

[TEST]
recall@1=0.551934  recall@2=0.745636  recall@5=0.919696  recall@10=0.962131  recall@20=0.984188
precision@1=0.664143  precision@2=0.477529  precision@5=0.250209  precision@10=0.132821  precision@20=0.068436
ndcg@1=0.664143  ndcg@2=0.727475  ndcg@5=0.804350  ndcg@10=0.820246  ndcg@20=0.826672
hit_rate@1=0.664143  hit_rate@2=0.830944  hit_rate@5=0.950548  hit_rate@10=0.977368  hit_rate@20=0.991221
map@1=0.664143  map@2=0.696621  map@5=0.751969  map@10=0.761295  map@20=0.763816
mrr@1=0.664143  mrr@2=0.747543  mrr@5=0.782865  mrr@10=0.786583  mrr@20=0.787585
f1@1=0.585038  f1@2=0.560201  f1@5=0.379283  f1@10=0.227251  f1@20=0.125766

Epoch 8/100: 100%|██████████| 820/820 [00:21<00:00, 37.45it/s, bpr=0.0295, c=2.69, loss=0.137]

[VAL]
recall@1=0.555918  recall@2=0.748646  recall@5=0.919643  recall@10=0.961195  recall@20=0.983706
precision@1=0.665887  precision@2=0.476411  precision@5=0.249952  precision@10=0.132710  precision@20=0.068484
ndcg@1=0.665887  ndcg@2=0.729296  ndcg@5=0.805564  ndcg@10=0.821347  ndcg@20=0.827969
hit_rate@1=0.665887  hit_rate@2=0.833145  hit_rate@5=0.951613  hit_rate@10=0.977339  hit_rate@20=0.991613
map@1=0.665887  map@2=0.698266  map@5=0.753376  map@10=0.762848  map@20=0.765470
mrr@1=0.665887  mrr@2=0.749516  mrr@5=0.784630  mrr@10=0.788223  mrr@20=0.789242
f1@1=0.588440  f1@2=0.560690  f1@5=0.378864  f1@10=0.227008  f1@20=0.125804

[TEST]
recall@1=0.551353  recall@2=0.746796  recall@5=0.922206  recall@10=0.962516  recall@20=0.984789
precision@1=0.661324  precision@2=0.476764  precision@5=0.250741  precision@10=0.132877  precision@20=0.068496
ndcg@1=0.661324  ndcg@2=0.727073  ndcg@5=0.805290  ndcg@10=0.820539  ndcg@20=0.827033
hit_rate@1=0.661324  hit_rate@2=0.830863  hit_rate@5=0.952964  hit_rate@10=0.977851  hit_rate@20=0.991946
map@1=0.661324  map@2=0.696078  map@5=0.752518  map@10=0.761622  map@20=0.764160
mrr@1=0.661324  mrr@2=0.746094  mrr@5=0.782278  mrr@10=0.785775  mrr@20=0.786795
f1@1=0.583933  f1@2=0.560192  f1@5=0.380114  f1@10=0.227343  f1@20=0.125870

Epoch 9/100: 100%|██████████| 820/820 [00:21<00:00, 37.45it/s, bpr=0.0495, c=2.52, loss=0.15]

[VAL]
recall@1=0.549789  recall@2=0.750385  recall@5=0.923187  recall@10=0.962195  recall@20=0.984591
precision@1=0.660565  precision@2=0.478024  precision@5=0.251016  precision@10=0.132960  precision@20=0.068544
ndcg@1=0.660565  ndcg@2=0.728670  ndcg@5=0.805113  ndcg@10=0.820075  ndcg@20=0.826589
hit_rate@1=0.660565  hit_rate@2=0.835000  hit_rate@5=0.953710  hit_rate@10=0.977823  hit_rate@20=0.992097
map@1=0.660565  map@2=0.696714  map@5=0.751736  map@10=0.760854  map@20=0.763393
mrr@1=0.660565  mrr@2=0.747782  mrr@5=0.782435  mrr@10=0.785845  mrr@20=0.786857
f1@1=0.582533  f1@2=0.562206  f1@5=0.380404  f1@10=0.227374  f1@20=0.125931

[TEST]
recall@1=0.553903  recall@2=0.752004  recall@5=0.923900  recall@10=0.963314  recall@20=0.985837
precision@1=0.666640  precision@2=0.480187  precision@5=0.251240  precision@10=0.133006  precision@20=0.068585
ndcg@1=0.666640  ndcg@2=0.731897  ndcg@5=0.807860  ndcg@10=0.822840  ndcg@20=0.829399
hit_rate@1=0.666640  hit_rate@2=0.836501  hit_rate@5=0.954575  hit_rate@10=0.978254  hit_rate@20=0.992510
map@1=0.666640  map@2=0.700467  map@5=0.755224  map@10=0.764309  map@20=0.766870
mrr@1=0.666640  mrr@2=0.751571  mrr@5=0.786023  mrr@10=0.789359  mrr@20=0.790379
f1@1=0.587262  f1@2=0.564197  f1@5=0.380899  f1@10=0.227558  f1@20=0.126017

Epoch 10/100: 100%|██████████| 820/820 [00:21<00:00, 37.30it/s, bpr=0.0393, c=2.56, loss=0.142]

[VAL]
recall@1=0.540989  recall@2=0.747480  recall@5=0.922241  recall@10=0.961448  recall@20=0.983498
precision@1=0.651048  precision@2=0.476452  precision@5=0.250742  precision@10=0.132806  precision@20=0.068456
ndcg@1=0.651048  ndcg@2=0.723578  ndcg@5=0.800735  ndcg@10=0.815734  ndcg@20=0.822182
hit_rate@1=0.651048  hit_rate@2=0.833548  hit_rate@5=0.953065  hit_rate@10=0.977177  hit_rate@20=0.991210
map@1=0.651048  map@2=0.690524  map@5=0.745989  map@10=0.755090  map@20=0.757613
mrr@1=0.651048  mrr@2=0.742298  mrr@5=0.777148  mrr@10=0.780574  mrr@20=0.781574
f1@1=0.573478  f1@2=0.560129  f1@5=0.380022  f1@10=0.227128  f1@20=0.125777

[TEST]
recall@1=0.547762  recall@2=0.746445  recall@5=0.922408  recall@10=0.962042  recall@20=0.983729
precision@1=0.659552  precision@2=0.476321  precision@5=0.250966  precision@10=0.132772  precision@20=0.068404
ndcg@1=0.659552  ndcg@2=0.725780  ndcg@5=0.803719  ndcg@10=0.818629  ndcg@20=0.824989
hit_rate@1=0.659552  hit_rate@2=0.831508  hit_rate@5=0.952883  hit_rate@10=0.977287  hit_rate@20=0.990979
map@1=0.659552  map@2=0.693984  map@5=0.750050  map@10=0.758931  map@20=0.761438
mrr@1=0.659552  mrr@2=0.745530  mrr@5=0.781066  mrr@10=0.784468  mrr@20=0.785472
f1@1=0.580801  f1@2=0.559722  f1@5=0.380402  f1@10=0.227186  f1@20=0.125702

Epoch 11/100: 100%|██████████| 820/820 [00:21<00:00, 37.57it/s, bpr=0.0214, c=2.83, loss=0.135]

[VAL]
recall@1=0.547193  recall@2=0.751640  recall@5=0.923250  recall@10=0.962615  recall@20=0.983514
precision@1=0.658710  precision@2=0.479315  precision@5=0.250903  precision@10=0.133016  precision@20=0.068472
ndcg@1=0.658710  ndcg@2=0.728887  ndcg@5=0.804230  ndcg@10=0.819288  ndcg@20=0.825404
hit_rate@1=0.658710  hit_rate@2=0.839597  hit_rate@5=0.954435  hit_rate@10=0.978226  hit_rate@20=0.991210
map@1=0.658710  map@2=0.695685  map@5=0.750088  map@10=0.759248  map@20=0.761667
mrr@1=0.658710  mrr@2=0.749153  mrr@5=0.782418  mrr@10=0.785760  mrr@20=0.786681
f1@1=0.580149  f1@2=0.563385  f1@5=0.380292  f1@10=0.227469  f1@20=0.125797

[TEST]
recall@1=0.545530  recall@2=0.748502  recall@5=0.924148  recall@10=0.962989  recall@20=0.985002
precision@1=0.655203  precision@2=0.477167  precision@5=0.251256  precision@10=0.132982  precision@20=0.068524
ndcg@1=0.655203  ndcg@2=0.725776  ndcg@5=0.803883  ndcg@10=0.818640  ndcg@20=0.825039
hit_rate@1=0.655203  hit_rate@2=0.834246  hit_rate@5=0.953930  hit_rate@10=0.977771  hit_rate@20=0.992026
map@1=0.655203  map@2=0.693299  map@5=0.749910  map@10=0.758791  map@20=0.761267
mrr@1=0.655203  mrr@2=0.744725  mrr@5=0.779779  mrr@10=0.783141  mrr@20=0.784161
f1@1=0.578005  f1@2=0.561089  f1@5=0.380968  f1@10=0.227516  f1@20=0.125910

Epoch 12/100: 100%|██████████| 820/820 [00:21<00:00, 37.60it/s, bpr=0.0413, c=2.61, loss=0.146]

[VAL]
recall@1=0.542440  recall@2=0.747550  recall@5=0.921791  recall@10=0.962559  recall@20=0.983758
precision@1=0.652500  precision@2=0.475685  precision@5=0.250500  precision@10=0.132976  precision@20=0.068520
ndcg@1=0.652500  ndcg@2=0.723726  ndcg@5=0.800874  ndcg@10=0.816448  ndcg@20=0.822660
hit_rate@1=0.652500  hit_rate@2=0.834274  hit_rate@5=0.953145  hit_rate@10=0.977903  hit_rate@20=0.991210
map@1=0.652500  map@2=0.690504  map@5=0.746164  map@10=0.755616  map@20=0.758053
mrr@1=0.652500  mrr@2=0.743387  mrr@5=0.777917  mrr@10=0.781421  mrr@20=0.782366
f1@1=0.574962  f1@2=0.559747  f1@5=0.379703  f1@10=0.227426  f1@20=0.125852

[TEST]
recall@1=0.545118  recall@2=0.746027  recall@5=0.923308  recall@10=0.962305  recall@20=0.984694
precision@1=0.657055  precision@2=0.476603  precision@5=0.251015  precision@10=0.132917  precision@20=0.068468
ndcg@1=0.657055  ndcg@2=0.724795  ndcg@5=0.802934  ndcg@10=0.817809  ndcg@20=0.824289
hit_rate@1=0.657055  hit_rate@2=0.831910  hit_rate@5=0.953769  hit_rate@10=0.977368  hit_rate@20=0.991624
map@1=0.657055  map@2=0.692594  map@5=0.748637  map@10=0.757660  map@20=0.760190
mrr@1=0.657055  mrr@2=0.744483  mrr@5=0.779937  mrr@10=0.783263  mrr@20=0.784288
f1@1=0.578208  f1@2=0.559713  f1@5=0.380631  f1@10=0.227398  f1@20=0.125827

Epoch 13/100: 100%|██████████| 820/820 [00:21<00:00, 37.70it/s, bpr=0.0326, c=2.75, loss=0.143]

[VAL]
recall@1=0.542003  recall@2=0.750398  recall@5=0.920745  recall@10=0.960443  recall@20=0.983714
precision@1=0.653226  precision@2=0.478710  precision@5=0.250194  precision@10=0.132702  precision@20=0.068492
ndcg@1=0.653226  ndcg@2=0.726167  ndcg@5=0.801002  ndcg@10=0.816232  ndcg@20=0.822999
hit_rate@1=0.653226  hit_rate@2=0.837500  hit_rate@5=0.952823  hit_rate@10=0.976371  hit_rate@20=0.991452
map@1=0.653226  map@2=0.692722  map@5=0.746591  map@10=0.755939  map@20=0.758545
mrr@1=0.653226  mrr@2=0.745363  mrr@5=0.778895  mrr@10=0.782237  mrr@20=0.783315
f1@1=0.574815  f1@2=0.562633  f1@5=0.379258  f1@10=0.226929  f1@20=0.125823

[TEST]
recall@1=0.546379  recall@2=0.747570  recall@5=0.923594  recall@10=0.961873  recall@20=0.985091
precision@1=0.659230  precision@2=0.477972  precision@5=0.251369  precision@10=0.132788  precision@20=0.068529
ndcg@1=0.659230  ndcg@2=0.726541  ndcg@5=0.804189  ndcg@10=0.818684  ndcg@20=0.825427
hit_rate@1=0.659230  hit_rate@2=0.833763  hit_rate@5=0.953930  hit_rate@10=0.977126  hit_rate@20=0.991946
map@1=0.659230  map@2=0.694286  map@5=0.750191  map@10=0.758944  map@20=0.761558
mrr@1=0.659230  mrr@2=0.746496  mrr@5=0.781565  mrr@10=0.784848  mrr@20=0.785907
f1@1=0.579774  f1@2=0.561093  f1@5=0.380966  f1@10=0.227202  f1@20=0.125928

Epoch 14/100: 100%|██████████| 820/820 [00:21<00:00, 37.36it/s, bpr=0.0372, c=2.6, loss=0.141]

[VAL]
recall@1=0.542048  recall@2=0.749545  recall@5=0.924924  recall@10=0.963486  recall@20=0.983666
precision@1=0.652903  precision@2=0.478952  precision@5=0.251516  precision@10=0.133129  precision@20=0.068500
ndcg@1=0.652903  ndcg@2=0.725703  ndcg@5=0.803178  ndcg@10=0.817930  ndcg@20=0.823839
hit_rate@1=0.652903  hit_rate@2=0.835645  hit_rate@5=0.955806  hit_rate@10=0.978871  hit_rate@20=0.991371
map@1=0.652903  map@2=0.692762  map@5=0.748480  map@10=0.757538  map@20=0.759856
mrr@1=0.652903  mrr@2=0.744274  mrr@5=0.779402  mrr@10=0.782647  mrr@20=0.783518
f1@1=0.574809  f1@2=0.562561  f1@5=0.381131  f1@10=0.227648  f1@20=0.125832

[TEST]
recall@1=0.546708  recall@2=0.749735  recall@5=0.925873  recall@10=0.964286  recall@20=0.985114
precision@1=0.659552  precision@2=0.480469  precision@5=0.251933  precision@10=0.133151  precision@20=0.068545
ndcg@1=0.659552  ndcg@2=0.728474  ndcg@5=0.806061  ndcg@10=0.820611  ndcg@20=0.826681
hit_rate@1=0.659552  hit_rate@2=0.834166  hit_rate@5=0.955300  hit_rate@10=0.978898  hit_rate@20=0.992107
map@1=0.659552  map@2=0.696722  map@5=0.752318  map@10=0.761092  map@20=0.763459
mrr@1=0.659552  mrr@2=0.746859  mrr@5=0.782453  mrr@10=0.785757  mrr@20=0.786696
f1@1=0.580107  f1@2=0.563464  f1@5=0.381900  f1@10=0.227796  f1@20=0.125935

Epoch 15/100: 100%|██████████| 820/820 [00:22<00:00, 37.21it/s, bpr=0.0361, c=2.65, loss=0.142]

[VAL]
recall@1=0.539831  recall@2=0.747187  recall@5=0.921148  recall@10=0.960943  recall@20=0.983429
precision@1=0.650000  precision@2=0.476532  precision@5=0.250500  precision@10=0.132766  precision@20=0.068496
ndcg@1=0.650000  ndcg@2=0.722956  ndcg@5=0.799708  ndcg@10=0.814906  ndcg@20=0.821498
hit_rate@1=0.650000  hit_rate@2=0.833790  hit_rate@5=0.952903  hit_rate@10=0.976855  hit_rate@20=0.990968
map@1=0.650000  map@2=0.689657  map@5=0.744875  map@10=0.754159  map@20=0.756746
mrr@1=0.650000  mrr@2=0.741895  mrr@5=0.776449  mrr@10=0.779828  mrr@20=0.780834
f1@1=0.572440  f1@2=0.560094  f1@5=0.379581  f1@10=0.227031  f1@20=0.125823

[TEST]
recall@1=0.544395  recall@2=0.741985  recall@5=0.921163  recall@10=0.961449  recall@20=0.985292
precision@1=0.656411  precision@2=0.474348  precision@5=0.250467  precision@10=0.132708  precision@20=0.068565
ndcg@1=0.656411  ndcg@2=0.721944  ndcg@5=0.800942  ndcg@10=0.816230  ndcg@20=0.823193
hit_rate@1=0.656411  hit_rate@2=0.827722  hit_rate@5=0.951917  hit_rate@10=0.976885  hit_rate@20=0.991865
map@1=0.656411  map@2=0.690158  map@5=0.746558  map@10=0.755780  map@20=0.758510
mrr@1=0.656411  mrr@2=0.742067  mrr@5=0.778254  mrr@10=0.781790  mrr@20=0.782875
f1@1=0.577505  f1@2=0.556833  f1@5=0.379752  f1@10=0.227066  f1@20=0.125974

Epoch 16/100: 100%|██████████| 820/820 [00:21<00:00, 37.42it/s, bpr=0.0263, c=2.67, loss=0.133]

[VAL]
recall@1=0.539465  recall@2=0.745768  recall@5=0.922714  recall@10=0.961422  recall@20=0.985187
precision@1=0.649839  precision@2=0.474960  precision@5=0.250903  precision@10=0.132855  precision@20=0.068617
ndcg@1=0.649839  ndcg@2=0.721633  ndcg@5=0.799875  ndcg@10=0.814742  ndcg@20=0.821666
hit_rate@1=0.649839  hit_rate@2=0.831694  hit_rate@5=0.953306  hit_rate@10=0.976532  hit_rate@20=0.992258
map@1=0.649839  map@2=0.688488  map@5=0.744697  map@10=0.753797  map@20=0.756473
mrr@1=0.649839  mrr@2=0.740766  mrr@5=0.776023  mrr@10=0.779348  mrr@20=0.780481
f1@1=0.572052  f1@2=0.558673  f1@5=0.380229  f1@10=0.227189  f1@20=0.126039

[TEST]
recall@1=0.543232  recall@2=0.743765  recall@5=0.923564  recall@10=0.963247  recall@20=0.985388
precision@1=0.654720  precision@2=0.475274  precision@5=0.251111  precision@10=0.133022  precision@20=0.068529
ndcg@1=0.654720  ndcg@2=0.722556  ndcg@5=0.802054  ndcg@10=0.817209  ndcg@20=0.823626
hit_rate@1=0.654720  hit_rate@2=0.829253  hit_rate@5=0.953689  hit_rate@10=0.978093  hit_rate@20=0.992349
map@1=0.654720  map@2=0.690480  map@5=0.747426  map@10=0.756635  map@20=0.759113
mrr@1=0.654720  mrr@2=0.741986  mrr@5=0.778369  mrr@10=0.781865  mrr@20=0.782889
f1@1=0.576197  f1@2=0.558060  f1@5=0.380752  f1@10=0.227569  f1@20=0.125927

Epoch 17/100: 100%|██████████| 820/820 [00:21<00:00, 37.49it/s, bpr=0.0317, c=2.58, loss=0.135]

[VAL]
recall@1=0.537455  recall@2=0.741009  recall@5=0.917739  recall@10=0.958585  recall@20=0.983038
precision@1=0.648306  precision@2=0.473226  precision@5=0.249581  precision@10=0.132460  precision@20=0.068456
ndcg@1=0.648306  ndcg@2=0.718323  ndcg@5=0.796094  ndcg@10=0.811714  ndcg@20=0.818836
hit_rate@1=0.648306  hit_rate@2=0.827661  hit_rate@5=0.949758  hit_rate@10=0.975000  hit_rate@20=0.990645
map@1=0.648306  map@2=0.685484  map@5=0.741077  map@10=0.750524  map@20=0.753299
mrr@1=0.648306  mrr@2=0.737984  mrr@5=0.773446  mrr@10=0.777051  mrr@20=0.778186
f1@1=0.570146  f1@2=0.555809  f1@5=0.378169  f1@10=0.226501  f1@20=0.125748

[TEST]
recall@1=0.545162  recall@2=0.739524  recall@5=0.919346  recall@10=0.960134  recall@20=0.984100
precision@1=0.657861  precision@2=0.473139  precision@5=0.249903  precision@10=0.132563  precision@20=0.068492
ndcg@1=0.657861  ndcg@2=0.720703  ndcg@5=0.799928  ndcg@10=0.815399  ndcg@20=0.822406
hit_rate@1=0.657861  hit_rate@2=0.825789  hit_rate@5=0.951111  hit_rate@10=0.975435  hit_rate@20=0.991140
map@1=0.657861  map@2=0.689171  map@5=0.745710  map@10=0.755029  map@20=0.757771
mrr@1=0.657861  mrr@2=0.741825  mrr@5=0.778258  mrr@10=0.781676  mrr@20=0.782816
f1@1=0.578478  f1@2=0.555236  f1@5=0.378945  f1@10=0.226807  f1@20=0.125829

Epoch 18/100: 100%|██████████| 820/820 [00:21<00:00, 37.34it/s, bpr=0.0272, c=2.58, loss=0.13]

[VAL]
recall@1=0.538481  recall@2=0.742613  recall@5=0.921322  recall@10=0.961631  recall@20=0.984266
precision@1=0.649516  precision@2=0.473548  precision@5=0.250258  precision@10=0.132895  precision@20=0.068552
ndcg@1=0.649516  ndcg@2=0.719501  ndcg@5=0.798365  ndcg@10=0.813889  ndcg@20=0.820509
hit_rate@1=0.649516  hit_rate@2=0.829516  hit_rate@5=0.953306  hit_rate@10=0.977339  hit_rate@20=0.991774
map@1=0.649516  map@2=0.686391  map@5=0.742773  map@10=0.752342  map@20=0.754914
mrr@1=0.649516  mrr@2=0.739516  mrr@5=0.775526  mrr@10=0.778935  mrr@20=0.779979
f1@1=0.571256  f1@2=0.556598  f1@5=0.379368  f1@10=0.227229  f1@20=0.125916

[TEST]
recall@1=0.544392  recall@2=0.739894  recall@5=0.923779  recall@10=0.961921  recall@20=0.985088
precision@1=0.655928  precision@2=0.472213  precision@5=0.251256  precision@10=0.132885  precision@20=0.068537
ndcg@1=0.655928  ndcg@2=0.719965  ndcg@5=0.801815  ndcg@10=0.816392  ndcg@20=0.823135
hit_rate@1=0.655928  hit_rate@2=0.825064  hit_rate@5=0.954977  hit_rate@10=0.976643  hit_rate@20=0.991865
map@1=0.655928  map@2=0.688386  map@5=0.746830  map@10=0.755844  map@20=0.758488
mrr@1=0.655928  mrr@2=0.740496  mrr@5=0.778414  mrr@10=0.781471  mrr@20=0.782573
f1@1=0.577365  f1@2=0.554915  f1@5=0.380880  f1@10=0.227325  f1@20=0.125941

Epoch 19/100: 100%|██████████| 820/820 [00:21<00:00, 37.64it/s, bpr=0.038, c=2.58, loss=0.141]

[VAL]
recall@1=0.537344  recall@2=0.732297  recall@5=0.917567  recall@10=0.957903  recall@20=0.983048
precision@1=0.647661  precision@2=0.467621  precision@5=0.249242  precision@10=0.132298  precision@20=0.068435
ndcg@1=0.647661  ndcg@2=0.712238  ndcg@5=0.794248  ndcg@10=0.809656  ndcg@20=0.817041
hit_rate@1=0.647661  hit_rate@2=0.818065  hit_rate@5=0.949597  hit_rate@10=0.974355  hit_rate@20=0.990645
map@1=0.647661  map@2=0.680484  map@5=0.738730  map@10=0.748046  map@20=0.750931
mrr@1=0.647661  mrr@2=0.732863  mrr@5=0.771167  mrr@10=0.774638  mrr@20=0.775850
f1@1=0.569943  f1@2=0.549255  f1@5=0.377863  f1@10=0.226243  f1@20=0.125723

[TEST]
recall@1=0.541662  recall@2=0.730707  recall@5=0.918091  recall@10=0.958929  recall@20=0.984134
precision@1=0.653270  precision@2=0.467341  precision@5=0.249549  precision@10=0.132418  precision@20=0.068420
ndcg@1=0.653270  ndcg@2=0.713170  ndcg@5=0.796394  ndcg@10=0.811905  ndcg@20=0.819203
hit_rate@1=0.653270  hit_rate@2=0.814352  hit_rate@5=0.950064  hit_rate@10=0.974146  hit_rate@20=0.991382
map@1=0.653270  map@2=0.682768  map@5=0.741584  map@10=0.750937  map@20=0.753738
mrr@1=0.653270  mrr@2=0.733811  mrr@5=0.773385  mrr@10=0.776809  mrr@20=0.778079
f1@1=0.574619  f1@2=0.548550  f1@5=0.378349  f1@10=0.226574  f1@20=0.125733

Epoch 20/100: 100%|██████████| 820/820 [00:21<00:00, 37.44it/s, bpr=0.0294, c=2.57, loss=0.132]

[VAL]
recall@1=0.539598  recall@2=0.737189  recall@5=0.917131  recall@10=0.957936  recall@20=0.983633
precision@1=0.649516  precision@2=0.470323  precision@5=0.249210  precision@10=0.132347  precision@20=0.068496
ndcg@1=0.649516  ndcg@2=0.716140  ndcg@5=0.795571  ndcg@10=0.811195  ndcg@20=0.818712
hit_rate@1=0.649516  hit_rate@2=0.823387  hit_rate@5=0.949677  hit_rate@10=0.974597  hit_rate@20=0.991048
map@1=0.649516  map@2=0.684012  map@5=0.740596  map@10=0.750048  map@20=0.753001
mrr@1=0.649516  mrr@2=0.736452  mrr@5=0.773043  mrr@10=0.776589  mrr@20=0.777796
f1@1=0.572057  f1@2=0.552698  f1@5=0.377722  f1@10=0.226318  f1@20=0.125824

[TEST]
recall@1=0.542031  recall@2=0.735121  recall@5=0.917027  recall@10=0.958795  recall@20=0.984704
precision@1=0.653592  precision@2=0.469716  precision@5=0.249307  precision@10=0.132410  precision@20=0.068512
ndcg@1=0.653592  ndcg@2=0.716189  ndcg@5=0.796582  ndcg@10=0.812445  ndcg@20=0.819975
hit_rate@1=0.653592  hit_rate@2=0.820312  hit_rate@5=0.949340  hit_rate@10=0.974307  hit_rate@20=0.991865
map@1=0.653592  map@2=0.684903  map@5=0.741969  map@10=0.751515  map@20=0.754436
mrr@1=0.653592  mrr@2=0.736952  mrr@5=0.774401  mrr@10=0.777955  mrr@20=0.779235
f1@1=0.575011  f1@2=0.551559  f1@5=0.378015  f1@10=0.226530  f1@20=0.125879

Epoch 21/100: 100%|██████████| 820/820 [00:21<00:00, 37.41it/s, bpr=0.0268, c=2.71, loss=0.135]

[VAL]
recall@1=0.539026  recall@2=0.737570  recall@5=0.918284  recall@10=0.960664  recall@20=0.984067
precision@1=0.650161  precision@2=0.471411  precision@5=0.249710  precision@10=0.132758  precision@20=0.068565
ndcg@1=0.650161  ndcg@2=0.716732  ndcg@5=0.796217  ndcg@10=0.812341  ndcg@20=0.819197
hit_rate@1=0.650161  hit_rate@2=0.824597  hit_rate@5=0.950484  hit_rate@10=0.976613  hit_rate@20=0.991371
map@1=0.650161  map@2=0.684395  map@5=0.740972  map@10=0.750711  map@20=0.753395
mrr@1=0.650161  mrr@2=0.737379  mrr@5=0.773785  mrr@10=0.777488  mrr@20=0.778558
f1@1=0.571822  f1@2=0.553422  f1@5=0.378341  f1@10=0.226998  f1@20=0.125925

[TEST]
recall@1=0.542639  recall@2=0.736006  recall@5=0.920336  recall@10=0.960057  recall@20=0.985708
precision@1=0.653914  precision@2=0.470482  precision@5=0.250258  precision@10=0.132676  precision@20=0.068577
ndcg@1=0.653914  ndcg@2=0.716914  ndcg@5=0.798823  ndcg@10=0.814026  ndcg@20=0.821420
hit_rate@1=0.653914  hit_rate@2=0.820715  hit_rate@5=0.952239  hit_rate@10=0.975274  hit_rate@20=0.992349
map@1=0.653914  map@2=0.685768  map@5=0.744033  map@10=0.753347  map@20=0.756194
mrr@1=0.653914  mrr@2=0.737315  mrr@5=0.775741  mrr@10=0.779027  mrr@20=0.780260
f1@1=0.575607  f1@2=0.552456  f1@5=0.379437  f1@10=0.226952  f1@20=0.126012

Epoch 22/100: 100%|██████████| 820/820 [00:21<00:00, 37.52it/s, bpr=0.0213, c=2.78, loss=0.132]

[VAL]
recall@1=0.541911  recall@2=0.738402  recall@5=0.917580  recall@10=0.958935  recall@20=0.984267
precision@1=0.653387  precision@2=0.470806  precision@5=0.249194  precision@10=0.132476  precision@20=0.068556
ndcg@1=0.653387  ndcg@2=0.717820  ndcg@5=0.796882  ndcg@10=0.812734  ndcg@20=0.820120
hit_rate@1=0.653387  hit_rate@2=0.824355  hit_rate@5=0.950000  hit_rate@10=0.975323  hit_rate@20=0.991532
map@1=0.653387  map@2=0.685746  map@5=0.742057  map@10=0.751632  map@20=0.754519
mrr@1=0.653387  mrr@2=0.738871  mrr@5=0.775296  mrr@10=0.778882  mrr@20=0.780036
f1@1=0.574902  f1@2=0.553451  f1@5=0.377830  f1@10=0.226537  f1@20=0.125929

[TEST]
recall@1=0.537803  recall@2=0.736144  recall@5=0.917383  recall@10=0.958311  recall@20=0.984351
precision@1=0.648599  precision@2=0.470482  precision@5=0.249291  precision@10=0.132426  precision@20=0.068492
ndcg@1=0.648599  ndcg@2=0.715200  ndcg@5=0.795389  ndcg@10=0.811000  ndcg@20=0.818550
hit_rate@1=0.648599  hit_rate@2=0.821521  hit_rate@5=0.949501  hit_rate@10=0.973905  hit_rate@20=0.991382
map@1=0.648599  map@2=0.683272  map@5=0.740364  map@10=0.749815  map@20=0.752722
mrr@1=0.648599  mrr@2=0.735060  mrr@5=0.772213  mrr@10=0.775672  mrr@20=0.776970
f1@1=0.570558  f1@2=0.552444  f1@5=0.377994  f1@10=0.226528  f1@20=0.125848

Epoch 23/100: 100%|██████████| 820/820 [00:21<00:00, 37.38it/s, bpr=0.0293, c=2.62, loss=0.134]

[VAL]
recall@1=0.546650  recall@2=0.737854  recall@5=0.917735  recall@10=0.959087  recall@20=0.984157
precision@1=0.657984  precision@2=0.471935  precision@5=0.249339  precision@10=0.132468  precision@20=0.068512
ndcg@1=0.657984  ndcg@2=0.719657  ndcg@5=0.799026  ndcg@10=0.814852  ndcg@20=0.822248
hit_rate@1=0.657984  hit_rate@2=0.823145  hit_rate@5=0.950161  hit_rate@10=0.975484  hit_rate@20=0.991613
map@1=0.657984  map@2=0.688750  map@5=0.745107  map@10=0.754711  map@20=0.757632
mrr@1=0.657984  mrr@2=0.740565  mrr@5=0.777672  mrr@10=0.781267  mrr@20=0.782478
f1@1=0.579600  f1@2=0.554033  f1@5=0.378002  f1@10=0.226549  f1@20=0.125856

[TEST]
recall@1=0.541486  recall@2=0.735667  recall@5=0.918692  recall@10=0.960176  recall@20=0.985096
precision@1=0.652142  precision@2=0.470884  precision@5=0.249887  precision@10=0.132611  precision@20=0.068488
ndcg@1=0.652142  ndcg@2=0.716512  ndcg@5=0.797455  ndcg@10=0.813129  ndcg@20=0.820355
hit_rate@1=0.652142  hit_rate@2=0.820151  hit_rate@5=0.950226  hit_rate@10=0.975515  hit_rate@20=0.992107
map@1=0.652142  map@2=0.685507  map@5=0.742946  map@10=0.752332  map@20=0.755130
mrr@1=0.652142  mrr@2=0.736147  mrr@5=0.774039  mrr@10=0.777544  mrr@20=0.778767
f1@1=0.574203  f1@2=0.552522  f1@5=0.378812  f1@10=0.226877  f1@20=0.125864

Epoch 24/100: 100%|██████████| 820/820 [00:21<00:00, 37.47it/s, bpr=0.03, c=2.7, loss=0.138]

[VAL]
recall@1=0.537561  recall@2=0.738627  recall@5=0.917685  recall@10=0.959036  recall@20=0.983451
precision@1=0.647903  precision@2=0.471250  precision@5=0.249306  precision@10=0.132516  precision@20=0.068492
ndcg@1=0.647903  ndcg@2=0.716414  ndcg@5=0.795034  ndcg@10=0.810885  ndcg@20=0.818072
hit_rate@1=0.647903  hit_rate@2=0.824919  hit_rate@5=0.950000  hit_rate@10=0.975161  hit_rate@20=0.991210
map@1=0.647903  map@2=0.683831  map@5=0.739606  map@10=0.749236  map@20=0.752049
mrr@1=0.647903  mrr@2=0.736411  mrr@5=0.772368  mrr@10=0.775952  mrr@20=0.777151
f1@1=0.570144  f1@2=0.553772  f1@5=0.377917  f1@10=0.226607  f1@20=0.125808

[TEST]
recall@1=0.541654  recall@2=0.735647  recall@5=0.917759  recall@10=0.960195  recall@20=0.985389
precision@1=0.651740  precision@2=0.469958  precision@5=0.249517  precision@10=0.132611  precision@20=0.068565
ndcg@1=0.651740  ndcg@2=0.716143  ndcg@5=0.796601  ndcg@10=0.812672  ndcg@20=0.820013
hit_rate@1=0.651740  hit_rate@2=0.822004  hit_rate@5=0.950387  hit_rate@10=0.975596  hit_rate@20=0.992188
map@1=0.651740  map@2=0.684500  map@5=0.741754  map@10=0.751457  map@20=0.754302
mrr@1=0.651740  mrr@2=0.736872  mrr@5=0.773910  mrr@10=0.777458  mrr@20=0.778683
f1@1=0.574243  f1@2=0.551913  f1@5=0.378272  f1@10=0.226867  f1@20=0.125983

Epoch 25/100: 100%|██████████| 820/820 [00:21<00:00, 37.50it/s, bpr=0.0308, c=2.62, loss=0.135]

[VAL]
recall@1=0.540406  recall@2=0.737435  recall@5=0.917121  recall@10=0.957580  recall@20=0.984141
precision@1=0.651774  precision@2=0.471411  precision@5=0.249274  precision@10=0.132315  precision@20=0.068516
ndcg@1=0.651774  ndcg@2=0.717277  ndcg@5=0.796409  ndcg@10=0.811820  ndcg@20=0.819533
hit_rate@1=0.651774  hit_rate@2=0.824597  hit_rate@5=0.949677  hit_rate@10=0.974435  hit_rate@20=0.991694
map@1=0.651774  map@2=0.685141  map@5=0.741673  map@10=0.750934  map@20=0.753921
mrr@1=0.651774  mrr@2=0.738185  mrr@5=0.774583  mrr@10=0.778057  mrr@20=0.779301
f1@1=0.573240  f1@2=0.553376  f1@5=0.377827  f1@10=0.226258  f1@20=0.125865

[TEST]
recall@1=0.540097  recall@2=0.735108  recall@5=0.916147  recall@10=0.958618  recall@20=0.985812
precision@1=0.652062  precision@2=0.470441  precision@5=0.249243  precision@10=0.132434  precision@20=0.068565
ndcg@1=0.652062  ndcg@2=0.715696  ndcg@5=0.795726  ndcg@10=0.811795  ndcg@20=0.819594
hit_rate@1=0.652062  hit_rate@2=0.820554  hit_rate@5=0.948776  hit_rate@10=0.974468  hit_rate@20=0.992832
map@1=0.652062  map@2=0.684218  map@5=0.741075  map@10=0.750712  map@20=0.753663
mrr@1=0.652062  mrr@2=0.736308  mrr@5=0.773620  mrr@10=0.777258  mrr@20=0.778576
f1@1=0.573203  f1@2=0.552080  f1@5=0.377790  f1@10=0.226575  f1@20=0.125999

Epoch 26/100: 100%|██████████| 820/820 [00:22<00:00, 37.26it/s, bpr=0.0435, c=2.6, loss=0.147]

[VAL]
recall@1=0.541374  recall@2=0.738262  recall@5=0.919448  recall@10=0.959885  recall@20=0.984539
precision@1=0.652500  precision@2=0.471976  precision@5=0.249887  precision@10=0.132710  precision@20=0.068581
ndcg@1=0.652500  ndcg@2=0.718086  ndcg@5=0.797836  ndcg@10=0.813373  ndcg@20=0.820524
hit_rate@1=0.652500  hit_rate@2=0.824274  hit_rate@5=0.951694  hit_rate@10=0.975565  hit_rate@20=0.991935
map@1=0.652500  map@2=0.686290  map@5=0.742876  map@10=0.752429  map@20=0.755179
mrr@1=0.652500  mrr@2=0.738387  mrr@5=0.775371  mrr@10=0.778760  mrr@20=0.779940
f1@1=0.574138  f1@2=0.554090  f1@5=0.378749  f1@10=0.226890  f1@20=0.125960

[TEST]
recall@1=0.539596  recall@2=0.737159  recall@5=0.919319  recall@10=0.960783  recall@20=0.985818
precision@1=0.649807  precision@2=0.471569  precision@5=0.250016  precision@10=0.132740  precision@20=0.068541
ndcg@1=0.649807  ndcg@2=0.716563  ndcg@5=0.797393  ndcg@10=0.813231  ndcg@20=0.820417
hit_rate@1=0.649807  hit_rate@2=0.822729  hit_rate@5=0.951192  hit_rate@10=0.975918  hit_rate@20=0.992751
map@1=0.649807  map@2=0.684822  map@5=0.742502  map@10=0.752143  map@20=0.754859
mrr@1=0.649807  mrr@2=0.736268  mrr@5=0.773791  mrr@10=0.777355  mrr@20=0.778571
f1@1=0.572251  f1@2=0.553535  f1@5=0.379013  f1@10=0.227096  f1@20=0.125961

Epoch 27/100: 100%|██████████| 820/820 [00:21<00:00, 37.39it/s, bpr=0.0288, c=2.7, loss=0.137]

[VAL]
recall@1=0.537862  recall@2=0.738979  recall@5=0.920009  recall@10=0.959621  recall@20=0.983737
precision@1=0.647823  precision@2=0.471129  precision@5=0.250048  precision@10=0.132621  precision@20=0.068520
ndcg@1=0.647823  ndcg@2=0.716626  ndcg@5=0.796569  ndcg@10=0.811786  ndcg@20=0.818839
hit_rate@1=0.647823  hit_rate@2=0.824516  hit_rate@5=0.952016  hit_rate@10=0.975323  hit_rate@20=0.991210
map@1=0.647823  map@2=0.684214  map@5=0.741047  map@10=0.750407  map@20=0.753154
mrr@1=0.647823  mrr@2=0.736169  mrr@5=0.773046  mrr@10=0.776369  mrr@20=0.777536
f1@1=0.570263  f1@2=0.553859  f1@5=0.379005  f1@10=0.226787  f1@20=0.125858

[TEST]
recall@1=0.538894  recall@2=0.735755  recall@5=0.921115  recall@10=0.960814  recall@20=0.984710
precision@1=0.649243  precision@2=0.468871  precision@5=0.250419  precision@10=0.132764  precision@20=0.068500
ndcg@1=0.649243  ndcg@2=0.714597  ndcg@5=0.797486  ndcg@10=0.812715  ndcg@20=0.819608
hit_rate@1=0.649243  hit_rate@2=0.820554  hit_rate@5=0.952239  hit_rate@10=0.975757  hit_rate@20=0.991624
map@1=0.649243  map@2=0.682708  map@5=0.742067  map@10=0.751383  map@20=0.754033
mrr@1=0.649243  mrr@2=0.734939  mrr@5=0.773274  mrr@10=0.776643  mrr@20=0.777760
f1@1=0.571587  f1@2=0.551467  f1@5=0.379734  f1@10=0.227118  f1@20=0.125869

Epoch 28/100: 100%|██████████| 820/820 [00:21<00:00, 37.47it/s, bpr=0.0327, c=2.72, loss=0.142]

[VAL]
recall@1=0.539848  recall@2=0.743859  recall@5=0.921370  recall@10=0.961033  recall@20=0.984676
precision@1=0.651129  precision@2=0.474274  precision@5=0.250484  precision@10=0.132750  precision@20=0.068565
ndcg@1=0.651129  ndcg@2=0.720739  ndcg@5=0.799110  ndcg@10=0.814281  ndcg@20=0.821190
hit_rate@1=0.651129  hit_rate@2=0.830806  hit_rate@5=0.953065  hit_rate@10=0.976694  hit_rate@20=0.991935
map@1=0.651129  map@2=0.687601  map@5=0.743842  map@10=0.753125  map@20=0.755823
mrr@1=0.651129  mrr@2=0.740968  mrr@5=0.776345  mrr@10=0.779697  mrr@20=0.780782
f1@1=0.572765  f1@2=0.557562  f1@5=0.379655  f1@10=0.227039  f1@20=0.125945

[TEST]
recall@1=0.543909  recall@2=0.740148  recall@5=0.920598  recall@10=0.961814  recall@20=0.985184
precision@1=0.656572  precision@2=0.473019  precision@5=0.250548  precision@10=0.132949  precision@20=0.068508
ndcg@1=0.656572  ndcg@2=0.720363  ndcg@5=0.800431  ndcg@10=0.816072  ndcg@20=0.822807
hit_rate@1=0.656572  hit_rate@2=0.826192  hit_rate@5=0.952159  hit_rate@10=0.976401  hit_rate@20=0.991946
map@1=0.656572  map@2=0.688507  map@5=0.745905  map@10=0.755386  map@20=0.757958
mrr@1=0.656572  mrr@2=0.741382  mrr@5=0.778144  mrr@10=0.781591  mrr@20=0.782733
f1@1=0.577299  f1@2=0.555442  f1@5=0.379673  f1@10=0.227383  f1@20=0.125896

Epoch 29/100: 100%|██████████| 820/820 [00:21<00:00, 37.48it/s, bpr=0.0261, c=2.71, loss=0.135]

[VAL]
recall@1=0.539675  recall@2=0.745079  recall@5=0.921598  recall@10=0.960029  recall@20=0.984920
precision@1=0.651210  precision@2=0.475081  precision@5=0.250565  precision@10=0.132677  precision@20=0.068617
ndcg@1=0.651210  ndcg@2=0.721552  ndcg@5=0.799424  ndcg@10=0.814196  ndcg@20=0.821444
hit_rate@1=0.651210  hit_rate@2=0.831048  hit_rate@5=0.953387  hit_rate@10=0.975887  hit_rate@20=0.992097
map@1=0.651210  map@2=0.688508  map@5=0.744201  map@10=0.753311  map@20=0.756124
mrr@1=0.651210  mrr@2=0.741129  mrr@5=0.776566  mrr@10=0.779749  mrr@20=0.780907
f1@1=0.572675  f1@2=0.558496  f1@5=0.379735  f1@10=0.226870  f1@20=0.126028

[TEST]
recall@1=0.542151  recall@2=0.741543  recall@5=0.922525  recall@10=0.961413  recall@20=0.986266
precision@1=0.654156  precision@2=0.473824  precision@5=0.251128  precision@10=0.132933  precision@20=0.068625
ndcg@1=0.654156  ndcg@2=0.720549  ndcg@5=0.800651  ndcg@10=0.815438  ndcg@20=0.822572
hit_rate@1=0.654156  hit_rate@2=0.827400  hit_rate@5=0.953367  hit_rate@10=0.976160  hit_rate@20=0.992912
map@1=0.654156  map@2=0.688426  map@5=0.745686  map@10=0.754703  map@20=0.757415
mrr@1=0.654156  mrr@2=0.740778  mrr@5=0.777318  mrr@10=0.780533  mrr@20=0.781748
f1@1=0.575249  f1@2=0.556477  f1@5=0.380608  f1@10=0.227369  f1@20=0.126094

Epoch 30/100: 100%|██████████| 820/820 [00:21<00:00, 37.28it/s, bpr=0.0449, c=2.51, loss=0.145]

[VAL]
recall@1=0.539431  recall@2=0.742068  recall@5=0.919279  recall@10=0.958723  recall@20=0.985081
precision@1=0.650726  precision@2=0.473024  precision@5=0.249806  precision@10=0.132476  precision@20=0.068609
ndcg@1=0.650726  ndcg@2=0.719361  ndcg@5=0.797479  ndcg@10=0.812683  ndcg@20=0.820338
hit_rate@1=0.650726  hit_rate@2=0.828790  hit_rate@5=0.952016  hit_rate@10=0.974919  hit_rate@20=0.992500
map@1=0.650726  map@2=0.686411  map@5=0.742178  map@10=0.751612  map@20=0.754558
mrr@1=0.650726  mrr@2=0.739798  mrr@5=0.775364  mrr@10=0.778659  mrr@20=0.779919
f1@1=0.572324  f1@2=0.556147  f1@5=0.378649  f1@10=0.226537  f1@20=0.126016

[TEST]
recall@1=0.539225  recall@2=0.739240  recall@5=0.920625  recall@10=0.960041  recall@20=0.985514
precision@1=0.651337  precision@2=0.472294  precision@5=0.250419  precision@10=0.132700  precision@20=0.068529
ndcg@1=0.651337  ndcg@2=0.717910  ndcg@5=0.798069  ndcg@10=0.813060  ndcg@20=0.820350
hit_rate@1=0.651337  hit_rate@2=0.825789  hit_rate@5=0.952722  hit_rate@10=0.975113  hit_rate@20=0.992268
map@1=0.651337  map@2=0.685446  map@5=0.742600  map@10=0.751742  map@20=0.754495
mrr@1=0.651337  mrr@2=0.738523  mrr@5=0.775267  mrr@10=0.778396  mrr@20=0.779647
f1@1=0.572368  f1@2=0.554689  f1@5=0.379583  f1@10=0.226988  f1@20=0.125934

Epoch 31/100: 100%|██████████| 820/820 [00:21<00:00, 37.37it/s, bpr=0.0323, c=2.61, loss=0.137]

[VAL]
recall@1=0.534863  recall@2=0.738190  recall@5=0.916612  recall@10=0.958842  recall@20=0.983803
precision@1=0.645968  precision@2=0.471250  precision@5=0.249161  precision@10=0.132548  precision@20=0.068516
ndcg@1=0.645968  ndcg@2=0.715268  ndcg@5=0.793881  ndcg@10=0.810078  ndcg@20=0.817316
hit_rate@1=0.645968  hit_rate@2=0.824597  hit_rate@5=0.949274  hit_rate@10=0.974758  hit_rate@20=0.991452
map@1=0.645968  map@2=0.682359  map@5=0.738341  map@10=0.748172  map@20=0.750942
mrr@1=0.645968  mrr@2=0.735282  mrr@5=0.771395  mrr@10=0.775053  mrr@20=0.776251
f1@1=0.567666  f1@2=0.553686  f1@5=0.377619  f1@10=0.226654  f1@20=0.125857

[TEST]
recall@1=0.539068  recall@2=0.732620  recall@5=0.919464  recall@10=0.959647  recall@20=0.985203
precision@1=0.650773  precision@2=0.468146  precision@5=0.250097  precision@10=0.132619  precision@20=0.068549
ndcg@1=0.650773  ndcg@2=0.713404  ndcg@5=0.796425  ndcg@10=0.811694  ndcg@20=0.819045
hit_rate@1=0.650773  hit_rate@2=0.819265  hit_rate@5=0.951756  hit_rate@10=0.974871  hit_rate@20=0.992107
map@1=0.650773  map@2=0.681600  map@5=0.740734  map@10=0.750016  map@20=0.752822
mrr@1=0.650773  mrr@2=0.735019  mrr@5=0.773646  mrr@10=0.776899  mrr@20=0.778140
f1@1=0.572107  f1@2=0.549692  f1@5=0.379108  f1@10=0.226834  f1@20=0.125952

Epoch 32/100: 100%|██████████| 820/820 [00:21<00:00, 37.28it/s, bpr=0.0528, c=2.43, loss=0.15]

[VAL]
recall@1=0.541117  recall@2=0.742297  recall@5=0.919615  recall@10=0.960677  recall@20=0.984533
precision@1=0.651855  precision@2=0.474637  precision@5=0.250032  precision@10=0.132710  precision@20=0.068581
ndcg@1=0.651855  ndcg@2=0.720674  ndcg@5=0.798674  ndcg@10=0.814350  ndcg@20=0.821352
hit_rate@1=0.651855  hit_rate@2=0.827339  hit_rate@5=0.951210  hit_rate@10=0.976290  hit_rate@20=0.991855
map@1=0.651855  map@2=0.688690  map@5=0.744172  map@10=0.753692  map@20=0.756438
mrr@1=0.651855  mrr@2=0.739597  mrr@5=0.775696  mrr@10=0.779251  mrr@20=0.780384
f1@1=0.573834  f1@2=0.557176  f1@5=0.378941  f1@10=0.226955  f1@20=0.125966

[TEST]
recall@1=0.544999  recall@2=0.737834  recall@5=0.918996  recall@10=0.960304  recall@20=0.985542
precision@1=0.657136  precision@2=0.472374  precision@5=0.250145  precision@10=0.132684  precision@20=0.068553
ndcg@1=0.657136  ndcg@2=0.719510  ndcg@5=0.799758  ndcg@10=0.815390  ndcg@20=0.822681
hit_rate@1=0.657136  hit_rate@2=0.822568  hit_rate@5=0.950306  hit_rate@10=0.975354  hit_rate@20=0.992510
map@1=0.657136  map@2=0.688607  map@5=0.745836  map@10=0.755223  map@20=0.758010
mrr@1=0.657136  mrr@2=0.739852  mrr@5=0.777261  mrr@10=0.780812  mrr@20=0.782063
f1@1=0.578146  f1@2=0.554205  f1@5=0.379110  f1@10=0.226976  f1@20=0.125965

Epoch 33/100: 100%|██████████| 820/820 [00:21<00:00, 37.37it/s, bpr=0.0241, c=2.63, loss=0.129]

[VAL]
recall@1=0.537252  recall@2=0.736938  recall@5=0.920032  recall@10=0.959371  recall@20=0.983837
precision@1=0.648306  precision@2=0.470202  precision@5=0.250113  precision@10=0.132589  precision@20=0.068524
ndcg@1=0.648306  ndcg@2=0.715135  ndcg@5=0.796366  ndcg@10=0.811482  ndcg@20=0.818649
hit_rate@1=0.648306  hit_rate@2=0.822823  hit_rate@5=0.952016  hit_rate@10=0.975484  hit_rate@20=0.991290
map@1=0.648306  map@2=0.682742  map@5=0.740684  map@10=0.749965  map@20=0.752759
mrr@1=0.648306  mrr@2=0.735565  mrr@5=0.773173  mrr@10=0.776477  mrr@20=0.777653
f1@1=0.570054  f1@2=0.552628  f1@5=0.379092  f1@10=0.226730  f1@20=0.125872

[TEST]
recall@1=0.541870  recall@2=0.736922  recall@5=0.921692  recall@10=0.960596  recall@20=0.985814
precision@1=0.653431  precision@2=0.471005  precision@5=0.250660  precision@10=0.132837  precision@20=0.068589
ndcg@1=0.653431  ndcg@2=0.717296  ndcg@5=0.799394  ndcg@10=0.814334  ndcg@20=0.821573
hit_rate@1=0.653431  hit_rate@2=0.822809  hit_rate@5=0.953044  hit_rate@10=0.975193  hit_rate@20=0.992510
map@1=0.653431  map@2=0.685627  map@5=0.744247  map@10=0.753474  map@20=0.756217
mrr@1=0.653431  mrr@2=0.738120  mrr@5=0.776136  mrr@10=0.779287  mrr@20=0.780550
f1@1=0.574917  f1@2=0.553068  f1@5=0.379993  f1@10=0.227194  f1@20=0.126030

Epoch 34/100: 100%|██████████| 820/820 [00:21<00:00, 37.47it/s, bpr=0.038, c=2.68, loss=0.145]

[VAL]
recall@1=0.536752  recall@2=0.738364  recall@5=0.919018  recall@10=0.960324  recall@20=0.984820
precision@1=0.647177  precision@2=0.471694  precision@5=0.249629  precision@10=0.132669  precision@20=0.068585
ndcg@1=0.647177  ndcg@2=0.716285  ndcg@5=0.795880  ndcg@10=0.811749  ndcg@20=0.818916
hit_rate@1=0.647177  hit_rate@2=0.825081  hit_rate@5=0.951452  hit_rate@10=0.976210  hit_rate@20=0.992258
map@1=0.647177  map@2=0.683669  map@5=0.740394  map@10=0.750082  map@20=0.752860
mrr@1=0.647177  mrr@2=0.736129  mrr@5=0.772902  mrr@10=0.776447  mrr@20=0.777630
f1@1=0.569304  f1@2=0.553895  f1@5=0.378432  f1@10=0.226880  f1@20=0.125978

[TEST]
recall@1=0.545883  recall@2=0.736678  recall@5=0.921137  recall@10=0.961272  recall@20=0.985186
precision@1=0.658264  precision@2=0.471126  precision@5=0.250612  precision@10=0.132813  precision@20=0.068496
ndcg@1=0.658264  ndcg@2=0.718789  ndcg@5=0.800733  ndcg@10=0.815999  ndcg@20=0.822901
hit_rate@1=0.658264  hit_rate@2=0.822245  hit_rate@5=0.952320  hit_rate@10=0.976079  hit_rate@20=0.992268
map@1=0.658264  map@2=0.687762  map@5=0.746244  map@10=0.755511  map@20=0.758158
mrr@1=0.658264  mrr@2=0.740255  mrr@5=0.778298  mrr@10=0.781668  mrr@20=0.782854
f1@1=0.579146  f1@2=0.553072  f1@5=0.379923  f1@10=0.227197  f1@20=0.125879

Epoch 35/100: 100%|██████████| 820/820 [00:21<00:00, 37.46it/s, bpr=0.0316, c=2.65, loss=0.137]

[VAL]
recall@1=0.540138  recall@2=0.739712  recall@5=0.918557  recall@10=0.959078  recall@20=0.984638
precision@1=0.651532  precision@2=0.472097  precision@5=0.249581  precision@10=0.132556  precision@20=0.068560
ndcg@1=0.651532  ndcg@2=0.718384  ndcg@5=0.797136  ndcg@10=0.812703  ndcg@20=0.820116
hit_rate@1=0.651532  hit_rate@2=0.825806  hit_rate@5=0.950968  hit_rate@10=0.975484  hit_rate@20=0.992097
map@1=0.651532  map@2=0.686069  map@5=0.742143  map@10=0.751650  map@20=0.754507
mrr@1=0.651532  mrr@2=0.738669  mrr@5=0.774987  mrr@10=0.778436  mrr@20=0.779636
f1@1=0.572983  f1@2=0.554668  f1@5=0.378312  f1@10=0.226660  f1@20=0.125946

[TEST]
recall@1=0.542612  recall@2=0.738751  recall@5=0.919539  recall@10=0.958323  recall@20=0.984734
precision@1=0.653431  precision@2=0.471851  precision@5=0.250048  precision@10=0.132490  precision@20=0.068524
ndcg@1=0.653431  ndcg@2=0.718641  ndcg@5=0.798737  ndcg@10=0.813630  ndcg@20=0.821201
hit_rate@1=0.653431  hit_rate@2=0.824581  hit_rate@5=0.951756  hit_rate@10=0.973421  hit_rate@20=0.991704
map@1=0.653431  map@2=0.686896  map@5=0.744073  map@10=0.753250  map@20=0.756097
mrr@1=0.653431  mrr@2=0.739006  mrr@5=0.776019  mrr@10=0.779117  mrr@20=0.780438
f1@1=0.575401  f1@2=0.554225  f1@5=0.379074  f1@10=0.226605  f1@20=0.125913

Epoch 36/100: 100%|██████████| 820/820 [00:21<00:00, 37.37it/s, bpr=0.025, c=2.64, loss=0.131]

[VAL]
recall@1=0.534164  recall@2=0.732355  recall@5=0.915163  recall@10=0.955870  recall@20=0.984098
precision@1=0.643871  precision@2=0.466855  precision@5=0.248629  precision@10=0.132105  precision@20=0.068573
ndcg@1=0.643871  ndcg@2=0.710667  ndcg@5=0.791743  ndcg@10=0.807390  ndcg@20=0.815641
hit_rate@1=0.643871  hit_rate@2=0.819032  hit_rate@5=0.948468  hit_rate@10=0.972500  hit_rate@20=0.991694
map@1=0.643871  map@2=0.678145  map@5=0.735926  map@10=0.745480  map@20=0.748669
mrr@1=0.643871  mrr@2=0.731452  mrr@5=0.769055  mrr@10=0.772486  mrr@20=0.773922
f1@1=0.566521  f1@2=0.548842  f1@5=0.376906  f1@10=0.225864  f1@20=0.125932

[TEST]
recall@1=0.538117  recall@2=0.732128  recall@5=0.916876  recall@10=0.957948  recall@20=0.984629
precision@1=0.649323  precision@2=0.468267  precision@5=0.249211  precision@10=0.132386  precision@20=0.068504
ndcg@1=0.649323  ndcg@2=0.712891  ndcg@5=0.794369  ndcg@10=0.810039  ndcg@20=0.817716
hit_rate@1=0.649323  hit_rate@2=0.817977  hit_rate@5=0.949662  hit_rate@10=0.973824  hit_rate@20=0.991543
map@1=0.649323  map@2=0.681379  map@5=0.738939  map@10=0.748491  map@20=0.751413
mrr@1=0.649323  mrr@2=0.733650  mrr@5=0.771675  mrr@10=0.775107  mrr@20=0.776395
f1@1=0.570920  f1@2=0.549569  f1@5=0.377826  f1@10=0.226456  f1@20=0.125885

Epoch 37/100: 100%|██████████| 820/820 [00:21<00:00, 37.39it/s, bpr=0.0694, c=2.5, loss=0.169]

[VAL]
recall@1=0.540184  recall@2=0.737882  recall@5=0.919946  recall@10=0.958894  recall@20=0.984897
precision@1=0.650806  precision@2=0.471169  precision@5=0.250048  precision@10=0.132516  precision@20=0.068597
ndcg@1=0.650806  ndcg@2=0.716985  ndcg@5=0.797500  ndcg@10=0.812390  ndcg@20=0.819996
hit_rate@1=0.650806  hit_rate@2=0.823710  hit_rate@5=0.952016  hit_rate@10=0.975161  hit_rate@20=0.992339
map@1=0.650806  map@2=0.684980  map@5=0.742268  map@10=0.751342  map@20=0.754313
mrr@1=0.650806  mrr@2=0.737258  mrr@5=0.774587  mrr@10=0.777811  mrr@20=0.779090
f1@1=0.572876  f1@2=0.553505  f1@5=0.378989  f1@10=0.226595  f1@20=0.125991

[TEST]
recall@1=0.543009  recall@2=0.734118  recall@5=0.919018  recall@10=0.959998  recall@20=0.985356
precision@1=0.654720  precision@2=0.470119  precision@5=0.250048  precision@10=0.132676  precision@20=0.068545
ndcg@1=0.654720  ndcg@2=0.716292  ndcg@5=0.798343  ndcg@10=0.813902  ndcg@20=0.821210
hit_rate@1=0.654720  hit_rate@2=0.819990  hit_rate@5=0.950709  hit_rate@10=0.975677  hit_rate@20=0.992349
map@1=0.654720  map@2=0.685285  map@5=0.743721  map@10=0.753077  map@20=0.755900
mrr@1=0.654720  mrr@2=0.737355  mrr@5=0.775766  mrr@10=0.779308  mrr@20=0.780513
f1@1=0.576010  f1@2=0.551427  f1@5=0.379013  f1@10=0.226919  f1@20=0.125952

Epoch 38/100: 100%|██████████| 820/820 [00:21<00:00, 37.40it/s, bpr=0.0439, c=2.62, loss=0.149]

[VAL]
recall@1=0.538604  recall@2=0.737218  recall@5=0.918471  recall@10=0.959531  recall@20=0.985191
precision@1=0.648790  precision@2=0.470403  precision@5=0.249565  precision@10=0.132589  precision@20=0.068629
ndcg@1=0.648790  ndcg@2=0.715795  ndcg@5=0.796028  ndcg@10=0.811798  ndcg@20=0.819269
hit_rate@1=0.648790  hit_rate@2=0.823871  hit_rate@5=0.951048  hit_rate@10=0.975887  hit_rate@20=0.992258
map@1=0.648790  map@2=0.683407  map@5=0.740710  map@10=0.750332  map@20=0.753222
mrr@1=0.648790  mrr@2=0.736331  mrr@5=0.773331  mrr@10=0.776859  mrr@20=0.778040
f1@1=0.571165  f1@2=0.552782  f1@5=0.378279  f1@10=0.226722  f1@20=0.126060

[TEST]
recall@1=0.545080  recall@2=0.735690  recall@5=0.921024  recall@10=0.960050  recall@20=0.985141
precision@1=0.656814  precision@2=0.470321  precision@5=0.250548  precision@10=0.132651  precision@20=0.068520
ndcg@1=0.656814  ndcg@2=0.717689  ndcg@5=0.800102  ndcg@10=0.814938  ndcg@20=0.822165
hit_rate@1=0.656814  hit_rate@2=0.821521  hit_rate@5=0.952722  hit_rate@10=0.975274  hit_rate@20=0.991704
map@1=0.656814  map@2=0.686614  map@5=0.745441  map@10=0.754498  map@20=0.757265
mrr@1=0.656814  mrr@2=0.739167  mrr@5=0.777439  mrr@10=0.780604  mrr@20=0.781800
f1@1=0.578118  f1@2=0.552231  f1@5=0.379778  f1@10=0.226928  f1@20=0.125914

Epoch 39/100: 100%|██████████| 820/820 [00:21<00:00, 37.38it/s, bpr=0.0209, c=2.7, loss=0.129]

[VAL]
recall@1=0.538596  recall@2=0.732074  recall@5=0.914456  recall@10=0.956702  recall@20=0.984188
precision@1=0.649435  precision@2=0.467177  precision@5=0.248306  precision@10=0.132145  precision@20=0.068548
ndcg@1=0.649435  ndcg@2=0.712321  ndcg@5=0.793004  ndcg@10=0.809251  ndcg@20=0.817276
hit_rate@1=0.649435  hit_rate@2=0.817823  hit_rate@5=0.947742  hit_rate@10=0.973548  hit_rate@20=0.991855
map@1=0.649435  map@2=0.680645  map@5=0.737879  map@10=0.747759  map@20=0.750860
mrr@1=0.649435  mrr@2=0.733629  mrr@5=0.771339  mrr@10=0.775053  mrr@20=0.776385
f1@1=0.571356  f1@2=0.549017  f1@5=0.376526  f1@10=0.225981  f1@20=0.125907

[TEST]
recall@1=0.538196  recall@2=0.729264  recall@5=0.915600  recall@10=0.958308  recall@20=0.985098
precision@1=0.648840  precision@2=0.466575  precision@5=0.248872  precision@10=0.132426  precision@20=0.068516
ndcg@1=0.648840  ndcg@2=0.710949  ndcg@5=0.793651  ndcg@10=0.809865  ndcg@20=0.817546
hit_rate@1=0.648840  hit_rate@2=0.815238  hit_rate@5=0.948293  hit_rate@10=0.973985  hit_rate@20=0.992429
map@1=0.648840  map@2=0.679748  map@5=0.738501  map@10=0.748270  map@20=0.751166
mrr@1=0.648840  mrr@2=0.732039  mrr@5=0.770849  mrr@10=0.774478  mrr@20=0.775807
f1@1=0.570883  f1@2=0.547473  f1@5=0.377307  f1@10=0.226507  f1@20=0.125903

Epoch 40/100: 100%|██████████| 820/820 [00:21<00:00, 37.35it/s, bpr=0.041, c=2.62, loss=0.146]

[VAL]
recall@1=0.545073  recall@2=0.742267  recall@5=0.917069  recall@10=0.958791  recall@20=0.984169
precision@1=0.656935  precision@2=0.473992  precision@5=0.249323  precision@10=0.132484  precision@20=0.068540
ndcg@1=0.656935  ndcg@2=0.721958  ndcg@5=0.798772  ndcg@10=0.814724  ndcg@20=0.822149
hit_rate@1=0.656935  hit_rate@2=0.827581  hit_rate@5=0.949839  hit_rate@10=0.975323  hit_rate@20=0.991694
map@1=0.656935  map@2=0.690222  map@5=0.744882  map@10=0.754558  map@20=0.757469
mrr@1=0.656935  mrr@2=0.742258  mrr@5=0.777590  mrr@10=0.781219  mrr@20=0.782421
f1@1=0.578126  f1@2=0.556825  f1@5=0.377873  f1@10=0.226521  f1@20=0.125894

[TEST]
recall@1=0.541035  recall@2=0.739417  recall@5=0.918109  recall@10=0.959469  recall@20=0.985308
precision@1=0.651740  precision@2=0.473139  precision@5=0.249597  precision@10=0.132555  precision@20=0.068520
ndcg@1=0.651740  ndcg@2=0.718903  ndcg@5=0.797713  ndcg@10=0.813433  ndcg@20=0.820870
hit_rate@1=0.651740  hit_rate@2=0.824501  hit_rate@5=0.950628  hit_rate@10=0.974952  hit_rate@20=0.992188
map@1=0.651740  map@2=0.687279  map@5=0.743320  map@10=0.752830  map@20=0.755669
mrr@1=0.651740  mrr@2=0.738120  mrr@5=0.774852  mrr@10=0.778306  mrr@20=0.779549
f1@1=0.573755  f1@2=0.555196  f1@5=0.378428  f1@10=0.226745  f1@20=0.125917

Epoch 41/100: 100%|██████████| 820/820 [00:21<00:00, 37.55it/s, bpr=0.0447, c=2.6, loss=0.149]

[VAL]
recall@1=0.540456  recall@2=0.740648  recall@5=0.917601  recall@10=0.958949  recall@20=0.983951
precision@1=0.650968  precision@2=0.473024  precision@5=0.249500  precision@10=0.132427  precision@20=0.068552
ndcg@1=0.650968  ndcg@2=0.719210  ndcg@5=0.796959  ndcg@10=0.812657  ndcg@20=0.820023
hit_rate@1=0.650968  hit_rate@2=0.827581  hit_rate@5=0.950081  hit_rate@10=0.975484  hit_rate@20=0.991129
map@1=0.650968  map@2=0.686754  map@5=0.742215  map@10=0.751691  map@20=0.754595
mrr@1=0.650968  mrr@2=0.739274  mrr@5=0.774694  mrr@10=0.778275  mrr@20=0.779429
f1@1=0.573051  f1@2=0.555496  f1@5=0.378077  f1@10=0.226484  f1@20=0.125910

[TEST]
recall@1=0.541697  recall@2=0.739859  recall@5=0.918404  recall@10=0.960110  recall@20=0.985004
precision@1=0.652867  precision@2=0.472133  precision@5=0.249613  precision@10=0.132619  precision@20=0.068468
ndcg@1=0.652867  ndcg@2=0.718851  ndcg@5=0.797810  ndcg@10=0.813695  ndcg@20=0.820884
hit_rate@1=0.652867  hit_rate@2=0.825548  hit_rate@5=0.950789  hit_rate@10=0.975596  hit_rate@20=0.991624
map@1=0.652867  map@2=0.686775  map@5=0.743245  map@10=0.752802  map@20=0.755572
mrr@1=0.652867  mrr@2=0.739207  mrr@5=0.775389  mrr@10=0.778899  mrr@20=0.780083
f1@1=0.574621  f1@2=0.554876  f1@5=0.378542  f1@10=0.226905  f1@20=0.125851

Epoch 42/100: 100%|██████████| 820/820 [00:21<00:00, 37.37it/s, bpr=0.0209, c=2.66, loss=0.127]

[VAL]
recall@1=0.540687  recall@2=0.740808  recall@5=0.920081  recall@10=0.961200  recall@20=0.985037
precision@1=0.651371  precision@2=0.471976  precision@5=0.249887  precision@10=0.132774  precision@20=0.068585
ndcg@1=0.651371  ndcg@2=0.718887  ndcg@5=0.798070  ndcg@10=0.813811  ndcg@20=0.820777
hit_rate@1=0.651371  hit_rate@2=0.827339  hit_rate@5=0.952500  hit_rate@10=0.976855  hit_rate@20=0.992500
map@1=0.651371  map@2=0.686290  map@5=0.742838  map@10=0.752455  map@20=0.755155
mrr@1=0.651371  mrr@2=0.739355  mrr@5=0.775609  mrr@10=0.779040  mrr@20=0.780183
f1@1=0.573313  f1@2=0.555021  f1@5=0.378862  f1@10=0.227042  f1@20=0.125979

[TEST]
recall@1=0.541131  recall@2=0.739076  recall@5=0.920683  recall@10=0.961490  recall@20=0.985408
precision@1=0.651498  precision@2=0.471931  precision@5=0.250306  precision@10=0.132845  precision@20=0.068516
ndcg@1=0.651498  ndcg@2=0.718231  ndcg@5=0.798659  ndcg@10=0.814229  ndcg@20=0.821139
hit_rate@1=0.651498  hit_rate@2=0.825145  hit_rate@5=0.952561  hit_rate@10=0.975918  hit_rate@20=0.992188
map@1=0.651498  map@2=0.686191  map@5=0.743610  map@10=0.753135  map@20=0.755777
mrr@1=0.651498  mrr@2=0.738322  mrr@5=0.775309  mrr@10=0.778637  mrr@20=0.779828
f1@1=0.573811  f1@2=0.554404  f1@5=0.379497  f1@10=0.227267  f1@20=0.125924

Epoch 43/100: 100%|██████████| 820/820 [00:21<00:00, 37.36it/s, bpr=0.0371, c=2.48, loss=0.136]

[VAL]
recall@1=0.534318  recall@2=0.737832  recall@5=0.919996  recall@10=0.959577  recall@20=0.984674
precision@1=0.645484  precision@2=0.470968  precision@5=0.250000  precision@10=0.132605  precision@20=0.068548
ndcg@1=0.645484  ndcg@2=0.714858  ndcg@5=0.795438  ndcg@10=0.810653  ndcg@20=0.817931
hit_rate@1=0.645484  hit_rate@2=0.823952  hit_rate@5=0.952419  hit_rate@10=0.975887  hit_rate@20=0.992581
map@1=0.645484  map@2=0.681956  map@5=0.739331  map@10=0.748666  map@20=0.751449
mrr@1=0.645484  mrr@2=0.734677  mrr@5=0.772138  mrr@10=0.775451  mrr@20=0.776629
f1@1=0.567176  f1@2=0.553313  f1@5=0.378928  f1@10=0.226749  f1@20=0.125912

[TEST]
recall@1=0.541920  recall@2=0.735945  recall@5=0.919142  recall@10=0.960927  recall@20=0.985281
precision@1=0.653753  precision@2=0.470683  precision@5=0.250097  precision@10=0.132853  precision@20=0.068529
ndcg@1=0.653753  ndcg@2=0.716934  ndcg@5=0.798089  ndcg@10=0.814005  ndcg@20=0.821003
hit_rate@1=0.653753  hit_rate@2=0.822165  hit_rate@5=0.951192  hit_rate@10=0.975757  hit_rate@20=0.991865
map@1=0.653753  map@2=0.685366  map@5=0.743222  map@10=0.752880  map@20=0.755567
mrr@1=0.653753  mrr@2=0.737999  mrr@5=0.775557  mrr@10=0.779074  mrr@20=0.780283
f1@1=0.574988  f1@2=0.552440  f1@5=0.379068  f1@10=0.227225  f1@20=0.125943

Epoch 44/100: 100%|██████████| 820/820 [00:21<00:00, 37.36it/s, bpr=0.0465, c=2.6, loss=0.151]

[VAL]
recall@1=0.535639  recall@2=0.737319  recall@5=0.916981  recall@10=0.955584  recall@20=0.984343
precision@1=0.646210  precision@2=0.470323  precision@5=0.249355  precision@10=0.132065  precision@20=0.068577
ndcg@1=0.646210  ndcg@2=0.714798  ndcg@5=0.794224  ndcg@10=0.809010  ndcg@20=0.817419
hit_rate@1=0.646210  hit_rate@2=0.823629  hit_rate@5=0.949274  hit_rate@10=0.972500  hit_rate@20=0.991694
map@1=0.646210  map@2=0.682056  map@5=0.738629  map@10=0.747658  map@20=0.750917
mrr@1=0.646210  mrr@2=0.734919  mrr@5=0.771488  mrr@10=0.774776  mrr@20=0.776224
f1@1=0.568279  f1@2=0.552757  f1@5=0.377916  f1@10=0.225808  f1@20=0.125946

[TEST]
recall@1=0.537523  recall@2=0.734527  recall@5=0.915925  recall@10=0.957578  recall@20=0.984882
precision@1=0.647390  precision@2=0.468790  precision@5=0.249323  precision@10=0.132305  precision@20=0.068549
ndcg@1=0.647390  ndcg@2=0.713620  ndcg@5=0.794420  ndcg@10=0.810160  ndcg@20=0.818077
hit_rate@1=0.647390  hit_rate@2=0.820151  hit_rate@5=0.948212  hit_rate@10=0.973582  hit_rate@20=0.991785
map@1=0.647390  map@2=0.681681  map@5=0.739404  map@10=0.748827  map@20=0.751886
mrr@1=0.647390  mrr@2=0.733771  mrr@5=0.771291  mrr@10=0.774897  mrr@20=0.776230
f1@1=0.570006  f1@2=0.550869  f1@5=0.377868  f1@10=0.226312  f1@20=0.125944

Epoch 45/100: 100%|██████████| 820/820 [00:21<00:00, 37.32it/s, bpr=0.0336, c=2.6, loss=0.137]

[VAL]
recall@1=0.538969  recall@2=0.738289  recall@5=0.917155  recall@10=0.957343  recall@20=0.984237
precision@1=0.649516  precision@2=0.471210  precision@5=0.249129  precision@10=0.132234  precision@20=0.068548
ndcg@1=0.649516  ndcg@2=0.716604  ndcg@5=0.795574  ndcg@10=0.811009  ndcg@20=0.818909
hit_rate@1=0.649516  hit_rate@2=0.824435  hit_rate@5=0.949919  hit_rate@10=0.973871  hit_rate@20=0.991774
map@1=0.649516  map@2=0.684274  map@5=0.740592  map@10=0.750017  map@20=0.753099
mrr@1=0.649516  mrr@2=0.736935  mrr@5=0.773226  mrr@10=0.776632  mrr@20=0.777949
f1@1=0.571658  f1@2=0.553750  f1@5=0.377685  f1@10=0.226151  f1@20=0.125904

[TEST]
recall@1=0.542680  recall@2=0.732854  recall@5=0.917348  recall@10=0.959775  recall@20=0.985228
precision@1=0.653753  precision@2=0.468750  precision@5=0.249468  precision@10=0.132619  precision@20=0.068520
ndcg@1=0.653753  ndcg@2=0.714899  ndcg@5=0.796594  ndcg@10=0.812694  ndcg@20=0.820064
hit_rate@1=0.653753  hit_rate@2=0.818621  hit_rate@5=0.949823  hit_rate@10=0.975274  hit_rate@20=0.992268
map@1=0.653753  map@2=0.683876  map@5=0.742004  map@10=0.751672  map@20=0.754521
mrr@1=0.653753  mrr@2=0.736227  mrr@5=0.774188  mrr@10=0.777761  mrr@20=0.779046
f1@1=0.575590  f1@2=0.550224  f1@5=0.378210  f1@10=0.226878  f1@20=0.125918

Epoch 46/100: 100%|██████████| 820/820 [00:21<00:00, 37.38it/s, bpr=0.0282, c=2.7, loss=0.136]

[VAL]
recall@1=0.542204  recall@2=0.738854  recall@5=0.919771  recall@10=0.959469  recall@20=0.985098
precision@1=0.652258  precision@2=0.471492  precision@5=0.249726  precision@10=0.132492  precision@20=0.068609
ndcg@1=0.652258  ndcg@2=0.718312  ndcg@5=0.798383  ndcg@10=0.813662  ndcg@20=0.821241
hit_rate@1=0.652258  hit_rate@2=0.824194  hit_rate@5=0.951935  hit_rate@10=0.976210  hit_rate@20=0.992258
map@1=0.652258  map@2=0.686613  map@5=0.743637  map@10=0.752988  map@20=0.755995
mrr@1=0.652258  mrr@2=0.738226  mrr@5=0.775526  mrr@10=0.778965  mrr@20=0.780170
f1@1=0.574648  f1@2=0.554012  f1@5=0.378623  f1@10=0.226588  f1@20=0.126022

[TEST]
recall@1=0.544362  recall@2=0.734003  recall@5=0.919876  recall@10=0.960899  recall@20=0.986370
precision@1=0.655525  precision@2=0.469878  precision@5=0.250097  precision@10=0.132788  precision@20=0.068605
ndcg@1=0.655525  ndcg@2=0.716549  ndcg@5=0.798897  ndcg@10=0.814587  ndcg@20=0.821913
hit_rate@1=0.655525  hit_rate@2=0.818702  hit_rate@5=0.951514  hit_rate@10=0.975354  hit_rate@20=0.993073
map@1=0.655525  map@2=0.686010  map@5=0.744467  map@10=0.754025  map@20=0.756798
mrr@1=0.655525  mrr@2=0.737113  mrr@5=0.775761  mrr@10=0.779181  mrr@20=0.780469
f1@1=0.577230  f1@2=0.551270  f1@5=0.379174  f1@10=0.227159  f1@20=0.126071

Epoch 47/100: 100%|██████████| 820/820 [00:21<00:00, 37.28it/s, bpr=0.0339, c=2.65, loss=0.14]

[VAL]
recall@1=0.544734  recall@2=0.739536  recall@5=0.920941  recall@10=0.961222  recall@20=0.984494
precision@1=0.655887  precision@2=0.472500  precision@5=0.250339  precision@10=0.132782  precision@20=0.068544
ndcg@1=0.655887  ndcg@2=0.719980  ndcg@5=0.800158  ndcg@10=0.815553  ndcg@20=0.822394
hit_rate@1=0.655887  hit_rate@2=0.825323  hit_rate@5=0.952097  hit_rate@10=0.977097  hit_rate@20=0.992016
map@1=0.655887  map@2=0.688448  map@5=0.745655  map@10=0.754986  map@20=0.757678
mrr@1=0.655887  mrr@2=0.740605  mrr@5=0.777583  mrr@10=0.781126  mrr@20=0.782216
f1@1=0.577586  f1@2=0.554912  f1@5=0.379449  f1@10=0.227068  f1@20=0.125919

[TEST]
recall@1=0.544647  recall@2=0.740152  recall@5=0.919668  recall@10=0.961626  recall@20=0.985813
precision@1=0.657136  precision@2=0.474509  precision@5=0.250306  precision@10=0.132893  precision@20=0.068581
ndcg@1=0.657136  ndcg@2=0.721430  ndcg@5=0.800289  ndcg@10=0.816174  ndcg@20=0.823166
hit_rate@1=0.657136  hit_rate@2=0.825950  hit_rate@5=0.951192  hit_rate@10=0.976562  hit_rate@20=0.992590
map@1=0.657136  map@2=0.690138  map@5=0.746181  map@10=0.755736  map@20=0.758427
mrr@1=0.657136  mrr@2=0.741543  mrr@5=0.778039  mrr@10=0.781649  mrr@20=0.782824
f1@1=0.577847  f1@2=0.556211  f1@5=0.379308  f1@10=0.227328  f1@20=0.126013

Epoch 48/100: 100%|██████████| 820/820 [00:21<00:00, 37.49it/s, bpr=0.0287, c=2.69, loss=0.136]

[VAL]
recall@1=0.541188  recall@2=0.747132  recall@5=0.922338  recall@10=0.961369  recall@20=0.984935
precision@1=0.652339  precision@2=0.476935  precision@5=0.250823  precision@10=0.132871  precision@20=0.068649
ndcg@1=0.652339  ndcg@2=0.723654  ndcg@5=0.800966  ndcg@10=0.815922  ndcg@20=0.822849
hit_rate@1=0.652339  hit_rate@2=0.833306  hit_rate@5=0.953306  hit_rate@10=0.976935  hit_rate@20=0.991694
map@1=0.652339  map@2=0.690685  map@5=0.746302  map@10=0.755413  map@20=0.758122
mrr@1=0.652339  mrr@2=0.742823  mrr@5=0.777676  mrr@10=0.781051  mrr@20=0.782147
f1@1=0.574075  f1@2=0.560366  f1@5=0.380114  f1@10=0.227192  f1@20=0.126079

[TEST]
recall@1=0.544389  recall@2=0.742780  recall@5=0.922254  recall@10=0.960896  recall@20=0.986034
precision@1=0.656492  precision@2=0.474750  precision@5=0.250966  precision@10=0.132804  precision@20=0.068589
ndcg@1=0.656492  ndcg@2=0.722267  ndcg@5=0.801965  ndcg@10=0.816759  ndcg@20=0.824016
hit_rate@1=0.656492  hit_rate@2=0.828447  hit_rate@5=0.953286  hit_rate@10=0.975918  hit_rate@20=0.992590
map@1=0.656492  map@2=0.690359  map@5=0.747586  map@10=0.756675  map@20=0.759448
mrr@1=0.656492  mrr@2=0.742469  mrr@5=0.779110  mrr@10=0.782347  mrr@20=0.783564
f1@1=0.577605  f1@2=0.557489  f1@5=0.380379  f1@10=0.227140  f1@20=0.126038

Epoch 49/100: 100%|██████████| 820/820 [00:21<00:00, 37.32it/s, bpr=0.0421, c=2.64, loss=0.148]

[VAL]
recall@1=0.537425  recall@2=0.737149  recall@5=0.917441  recall@10=0.959805  recall@20=0.984794
precision@1=0.647984  precision@2=0.472298  precision@5=0.249226  precision@10=0.132548  precision@20=0.068569
ndcg@1=0.647984  ndcg@2=0.716135  ndcg@5=0.795046  ndcg@10=0.811204  ndcg@20=0.818538
hit_rate@1=0.647984  hit_rate@2=0.822419  hit_rate@5=0.949677  hit_rate@10=0.976129  hit_rate@20=0.992500
map@1=0.647984  map@2=0.684355  map@5=0.740092  map@10=0.749836  map@20=0.752689
mrr@1=0.647984  mrr@2=0.735202  mrr@5=0.771929  mrr@10=0.775697  mrr@20=0.776904
f1@1=0.570054  f1@2=0.553867  f1@5=0.377833  f1@10=0.226667  f1@20=0.125943

[TEST]
recall@1=0.543962  recall@2=0.735703  recall@5=0.918220  recall@10=0.960282  recall@20=0.986191
precision@1=0.656733  precision@2=0.472012  precision@5=0.249855  precision@10=0.132692  precision@20=0.068605
ndcg@1=0.656733  ndcg@2=0.718106  ndcg@5=0.798309  ndcg@10=0.814272  ndcg@20=0.821733
hit_rate@1=0.656733  hit_rate@2=0.820876  hit_rate@5=0.949501  hit_rate@10=0.975032  hit_rate@20=0.992671
map@1=0.656733  map@2=0.687359  map@5=0.744172  map@10=0.753721  map@20=0.756553
mrr@1=0.656733  mrr@2=0.738805  mrr@5=0.776106  mrr@10=0.779755  mrr@20=0.781025
f1@1=0.577315  f1@2=0.553246  f1@5=0.378682  f1@10=0.226996  f1@20=0.126074

Epoch 50/100: 100%|██████████| 820/820 [00:21<00:00, 37.28it/s, bpr=0.0528, c=2.55, loss=0.155]

[VAL]
recall@1=0.538101  recall@2=0.740009  recall@5=0.919164  recall@10=0.959659  recall@20=0.984446
precision@1=0.648548  precision@2=0.472500  precision@5=0.249919  precision@10=0.132694  precision@20=0.068617
ndcg@1=0.648548  ndcg@2=0.717629  ndcg@5=0.796701  ndcg@10=0.812181  ndcg@20=0.819448
hit_rate@1=0.648548  hit_rate@2=0.826290  hit_rate@5=0.951129  hit_rate@10=0.975645  hit_rate@20=0.991532
map@1=0.648548  map@2=0.685020  map@5=0.741477  map@10=0.750889  map@20=0.753729
mrr@1=0.648548  mrr@2=0.737419  mrr@5=0.773618  mrr@10=0.777070  mrr@20=0.778251
f1@1=0.570770  f1@2=0.555083  f1@5=0.378712  f1@10=0.226831  f1@20=0.126014

[TEST]
recall@1=0.542275  recall@2=0.736773  recall@5=0.921477  recall@10=0.960870  recall@20=0.985205
precision@1=0.654800  precision@2=0.470965  precision@5=0.250483  precision@10=0.132804  precision@20=0.068557
ndcg@1=0.654800  ndcg@2=0.717521  ndcg@5=0.799308  ndcg@10=0.814408  ndcg@20=0.821481
hit_rate@1=0.654800  hit_rate@2=0.823534  hit_rate@5=0.952883  hit_rate@10=0.975596  hit_rate@20=0.991865
map@1=0.654800  map@2=0.685668  map@5=0.744046  map@10=0.753308  map@20=0.756044
mrr@1=0.654800  mrr@2=0.739167  mrr@5=0.776789  mrr@10=0.780024  mrr@20=0.781236
f1@1=0.575583  f1@2=0.552979  f1@5=0.379835  f1@10=0.227188  f1@20=0.125970

Epoch 51/100: 100%|██████████| 820/820 [00:21<00:00, 37.37it/s, bpr=0.0407, c=2.7, loss=0.149]

[VAL]
recall@1=0.538558  recall@2=0.737182  recall@5=0.916736  recall@10=0.957800  recall@20=0.984801
precision@1=0.649435  precision@2=0.470685  precision@5=0.249306  precision@10=0.132315  precision@20=0.068609
ndcg@1=0.649435  ndcg@2=0.716015  ndcg@5=0.795384  ndcg@10=0.811005  ndcg@20=0.818908
hit_rate@1=0.649435  hit_rate@2=0.822903  hit_rate@5=0.949274  hit_rate@10=0.974435  hit_rate@20=0.992016
map@1=0.649435  map@2=0.683911  map@5=0.740369  map@10=0.749856  map@20=0.752930
mrr@1=0.649435  mrr@2=0.736169  mrr@5=0.773026  mrr@10=0.776590  mrr@20=0.777885
f1@1=0.571257  f1@2=0.552924  f1@5=0.377697  f1@10=0.226258  f1@20=0.126006

[TEST]
recall@1=0.541077  recall@2=0.737096  recall@5=0.917952  recall@10=0.958503  recall@20=0.985564
precision@1=0.652787  precision@2=0.471529  precision@5=0.249485  precision@10=0.132361  precision@20=0.068541
ndcg@1=0.652787  ndcg@2=0.717444  ndcg@5=0.797004  ndcg@10=0.812461  ndcg@20=0.820297
hit_rate@1=0.652787  hit_rate@2=0.823293  hit_rate@5=0.949823  hit_rate@10=0.974468  hit_rate@20=0.992349
map@1=0.652787  map@2=0.685688  map@5=0.742251  map@10=0.751625  map@20=0.754642
mrr@1=0.652787  mrr@2=0.738040  mrr@5=0.774630  mrr@10=0.778106  mrr@20=0.779420
f1@1=0.574111  f1@2=0.553356  f1@5=0.378362  f1@10=0.226453  f1@20=0.125956

Epoch 52/100: 100%|██████████| 820/820 [00:21<00:00, 37.37it/s, bpr=0.0281, c=2.71, loss=0.137]

[VAL]
recall@1=0.535701  recall@2=0.738821  recall@5=0.918371  recall@10=0.960425  recall@20=0.985466
precision@1=0.645323  precision@2=0.470806  precision@5=0.249403  precision@10=0.132718  precision@20=0.068649
ndcg@1=0.645323  ndcg@2=0.715460  ndcg@5=0.794942  ndcg@10=0.811085  ndcg@20=0.818417
hit_rate@1=0.645323  hit_rate@2=0.825726  hit_rate@5=0.951452  hit_rate@10=0.976290  hit_rate@20=0.992500
map@1=0.645323  map@2=0.682379  map@5=0.739147  map@10=0.749022  map@20=0.751883
mrr@1=0.645323  mrr@2=0.735524  mrr@5=0.771940  mrr@10=0.775469  mrr@20=0.776648
f1@1=0.568080  f1@2=0.553687  f1@5=0.378091  f1@10=0.226947  f1@20=0.126090

[TEST]
recall@1=0.539764  recall@2=0.735343  recall@5=0.919340  recall@10=0.961037  recall@20=0.985519
precision@1=0.651256  precision@2=0.469596  precision@5=0.250032  precision@10=0.132732  precision@20=0.068533
ndcg@1=0.651256  ndcg@2=0.715476  ndcg@5=0.797123  ndcg@10=0.812890  ndcg@20=0.819993
hit_rate@1=0.651256  hit_rate@2=0.821762  hit_rate@5=0.951273  hit_rate@10=0.976160  hit_rate@20=0.992349
map@1=0.651256  map@2=0.683533  map@5=0.741851  map@10=0.751315  map@20=0.754085
mrr@1=0.651256  mrr@2=0.736509  mrr@5=0.774251  mrr@10=0.777753  mrr@20=0.778937
f1@1=0.572670  f1@2=0.551543  f1@5=0.379059  f1@10=0.227103  f1@20=0.125953

Epoch 53/100: 100%|██████████| 820/820 [00:21<00:00, 37.36it/s, bpr=0.0479, c=2.55, loss=0.15]

[VAL]
recall@1=0.535307  recall@2=0.736289  recall@5=0.915662  recall@10=0.956627  recall@20=0.984549
precision@1=0.645000  precision@2=0.469274  precision@5=0.248774  precision@10=0.132177  precision@20=0.068548
ndcg@1=0.645000  ndcg@2=0.713696  ndcg@5=0.793078  ndcg@10=0.808802  ndcg@20=0.816904
hit_rate@1=0.645000  hit_rate@2=0.822339  hit_rate@5=0.948710  hit_rate@10=0.973387  hit_rate@20=0.991935
map@1=0.645000  map@2=0.681028  map@5=0.737597  map@10=0.747191  map@20=0.750303
mrr@1=0.645000  mrr@2=0.733669  mrr@5=0.770329  mrr@10=0.773853  mrr@20=0.775203
f1@1=0.567734  f1@2=0.551721  f1@5=0.377108  f1@10=0.226010  f1@20=0.125925

[TEST]
recall@1=0.541421  recall@2=0.733043  recall@5=0.918090  recall@10=0.956937  recall@20=0.985038
precision@1=0.652223  precision@2=0.467341  precision@5=0.249678  precision@10=0.132249  precision@20=0.068537
ndcg@1=0.652223  ndcg@2=0.713973  ndcg@5=0.796535  ndcg@10=0.811395  ndcg@20=0.819498
hit_rate@1=0.652223  hit_rate@2=0.818541  hit_rate@5=0.950387  hit_rate@10=0.972938  hit_rate@20=0.991865
map@1=0.652223  map@2=0.682567  map@5=0.741551  map@10=0.750635  map@20=0.753727
mrr@1=0.652223  mrr@2=0.735382  mrr@5=0.773774  mrr@10=0.776978  mrr@20=0.778370
f1@1=0.574160  f1@2=0.549460  f1@5=0.378488  f1@10=0.226212  f1@20=0.125933

Epoch 54/100: 100%|██████████| 820/820 [00:21<00:00, 37.27it/s, bpr=0.0232, c=2.65, loss=0.129]

[VAL]
recall@1=0.539961  recall@2=0.738062  recall@5=0.920522  recall@10=0.959404  recall@20=0.984476
precision@1=0.651210  precision@2=0.470887  precision@5=0.250145  precision@10=0.132516  precision@20=0.068581
ndcg@1=0.651210  ndcg@2=0.716943  ndcg@5=0.797599  ndcg@10=0.812550  ndcg@20=0.819902
hit_rate@1=0.651210  hit_rate@2=0.824355  hit_rate@5=0.952581  hit_rate@10=0.975484  hit_rate@20=0.991855
map@1=0.651210  map@2=0.684657  map@5=0.742236  map@10=0.751379  map@20=0.754233
mrr@1=0.651210  mrr@2=0.737782  mrr@5=0.774786  mrr@10=0.778063  mrr@20=0.779257
f1@1=0.572820  f1@2=0.553405  f1@5=0.379159  f1@10=0.226619  f1@20=0.125964

[TEST]
recall@1=0.540960  recall@2=0.735709  recall@5=0.920090  recall@10=0.960176  recall@20=0.985175
precision@1=0.652142  precision@2=0.469958  precision@5=0.250419  precision@10=0.132635  precision@20=0.068516
ndcg@1=0.652142  ndcg@2=0.716059  ndcg@5=0.798057  ndcg@10=0.813316  ndcg@20=0.820536
hit_rate@1=0.652142  hit_rate@2=0.820957  hit_rate@5=0.951353  hit_rate@10=0.975596  hit_rate@20=0.991865
map@1=0.652142  map@2=0.684540  map@5=0.743119  map@10=0.752368  map@20=0.755136
mrr@1=0.652142  mrr@2=0.736550  mrr@5=0.774519  mrr@10=0.777977  mrr@20=0.779159
f1@1=0.573860  f1@2=0.551948  f1@5=0.379514  f1@10=0.226887  f1@20=0.125914

Epoch 55/100: 100%|██████████| 820/820 [00:21<00:00, 37.28it/s, bpr=0.0323, c=2.59, loss=0.136]

[VAL]
recall@1=0.535711  recall@2=0.732090  recall@5=0.916855  recall@10=0.958151  recall@20=0.984394
precision@1=0.645242  precision@2=0.466976  precision@5=0.249000  precision@10=0.132218  precision@20=0.068496
ndcg@1=0.645242  ndcg@2=0.711092  ndcg@5=0.793135  ndcg@10=0.808865  ndcg@20=0.816577
hit_rate@1=0.645242  hit_rate@2=0.818226  hit_rate@5=0.949516  hit_rate@10=0.974839  hit_rate@20=0.992097
map@1=0.645242  map@2=0.678992  map@5=0.737398  map@10=0.746913  map@20=0.749911
mrr@1=0.645242  mrr@2=0.731734  mrr@5=0.769987  mrr@10=0.773560  mrr@20=0.774826
f1@1=0.568067  f1@2=0.548889  f1@5=0.377518  f1@10=0.226179  f1@20=0.125840

[TEST]
recall@1=0.542447  recall@2=0.731198  recall@5=0.917925  recall@10=0.959575  recall@20=0.985475
precision@1=0.654156  precision@2=0.467743  precision@5=0.249613  precision@10=0.132547  precision@20=0.068545
ndcg@1=0.654156  ndcg@2=0.713888  ndcg@5=0.796697  ndcg@10=0.812495  ndcg@20=0.819984
hit_rate@1=0.654156  hit_rate@2=0.816849  hit_rate@5=0.950226  hit_rate@10=0.975113  hit_rate@20=0.992349
map@1=0.654156  map@2=0.683030  map@5=0.741786  map@10=0.751292  map@20=0.754162
mrr@1=0.654156  mrr@2=0.735503  mrr@5=0.774383  mrr@10=0.777921  mrr@20=0.779187
f1@1=0.575475  f1@2=0.548892  f1@5=0.378405  f1@10=0.226752  f1@20=0.125947

Epoch 56/100: 100%|██████████| 820/820 [00:21<00:00, 37.28it/s, bpr=0.0218, c=2.74, loss=0.132]

[VAL]
recall@1=0.536382  recall@2=0.739999  recall@5=0.917456  recall@10=0.956918  recall@20=0.983951
precision@1=0.647097  precision@2=0.472218  precision@5=0.249290  precision@10=0.132226  precision@20=0.068528
ndcg@1=0.647097  ndcg@2=0.716978  ndcg@5=0.795111  ndcg@10=0.810336  ndcg@20=0.818244
hit_rate@1=0.647097  hit_rate@2=0.826613  hit_rate@5=0.950000  hit_rate@10=0.973871  hit_rate@20=0.991371
map@1=0.647097  map@2=0.684012  map@5=0.739774  map@10=0.749094  map@20=0.752174
mrr@1=0.647097  mrr@2=0.736855  mrr@5=0.772577  mrr@10=0.775996  mrr@20=0.777290
f1@1=0.569092  f1@2=0.554902  f1@5=0.377880  f1@10=0.226093  f1@20=0.125880

[TEST]
recall@1=0.542473  recall@2=0.735717  recall@5=0.919794  recall@10=0.958420  recall@20=0.984904
precision@1=0.655686  precision@2=0.470321  precision@5=0.250145  precision@10=0.132458  precision@20=0.068508
ndcg@1=0.655686  ndcg@2=0.716944  ndcg@5=0.798499  ndcg@10=0.813267  ndcg@20=0.820902
hit_rate@1=0.655686  hit_rate@2=0.821843  hit_rate@5=0.951836  hit_rate@10=0.973824  hit_rate@20=0.991704
map@1=0.655686  map@2=0.685366  map@5=0.743487  map@10=0.752554  map@20=0.755485
mrr@1=0.655686  mrr@2=0.738764  mrr@5=0.776463  mrr@10=0.779616  mrr@20=0.780938
f1@1=0.575911  f1@2=0.552190  f1@5=0.379255  f1@10=0.226580  f1@20=0.125880

Epoch 57/100: 100%|██████████| 820/820 [00:21<00:00, 37.48it/s, bpr=0.0426, c=2.64, loss=0.148]

[VAL]
recall@1=0.538869  recall@2=0.739205  recall@5=0.917885  recall@10=0.958266  recall@20=0.984506
precision@1=0.649758  precision@2=0.471976  precision@5=0.249403  precision@10=0.132355  precision@20=0.068573
ndcg@1=0.649758  ndcg@2=0.717448  ndcg@5=0.796129  ndcg@10=0.811559  ndcg@20=0.819243
hit_rate@1=0.649758  hit_rate@2=0.825645  hit_rate@5=0.950242  hit_rate@10=0.974677  hit_rate@20=0.991774
map@1=0.649758  map@2=0.684960  map@5=0.741007  map@10=0.750355  map@20=0.753340
mrr@1=0.649758  mrr@2=0.737702  mrr@5=0.773806  mrr@10=0.777256  mrr@20=0.778514
f1@1=0.571656  f1@2=0.554455  f1@5=0.378034  f1@10=0.226359  f1@20=0.125963

[TEST]
recall@1=0.542029  recall@2=0.736659  recall@5=0.918463  recall@10=0.958552  recall@20=0.985194
precision@1=0.654559  precision@2=0.471408  precision@5=0.249807  precision@10=0.132442  precision@20=0.068557
ndcg@1=0.654559  ndcg@2=0.717570  ndcg@5=0.797867  ndcg@10=0.813151  ndcg@20=0.820851
hit_rate@1=0.654559  hit_rate@2=0.822568  hit_rate@5=0.950789  hit_rate@10=0.973985  hit_rate@20=0.991946
map@1=0.654559  map@2=0.686030  map@5=0.743127  map@10=0.752450  map@20=0.755383
mrr@1=0.654559  mrr@2=0.738563  mrr@5=0.775851  mrr@10=0.779156  mrr@20=0.780484
f1@1=0.575309  f1@2=0.553180  f1@5=0.378693  f1@10=0.226570  f1@20=0.125966

Epoch 58/100: 100%|██████████| 820/820 [00:21<00:00, 37.40it/s, bpr=0.0203, c=2.77, loss=0.131]

[VAL]
recall@1=0.544844  recall@2=0.741818  recall@5=0.918865  recall@10=0.959410  recall@20=0.985209
precision@1=0.657419  precision@2=0.473226  precision@5=0.249694  precision@10=0.132597  precision@20=0.068621
ndcg@1=0.657419  ndcg@2=0.721467  ndcg@5=0.799555  ndcg@10=0.815101  ndcg@20=0.822630
hit_rate@1=0.657419  hit_rate@2=0.828629  hit_rate@5=0.950968  hit_rate@10=0.975565  hit_rate@20=0.992258
map@1=0.657419  map@2=0.689214  map@5=0.745049  map@10=0.754518  map@20=0.757423
mrr@1=0.657419  mrr@2=0.743024  mrr@5=0.778659  mrr@10=0.782153  mrr@20=0.783387
f1@1=0.578124  f1@2=0.556181  f1@5=0.378479  f1@10=0.226711  f1@20=0.126040

[TEST]
recall@1=0.537170  recall@2=0.738767  recall@5=0.921502  recall@10=0.960108  recall@20=0.985376
precision@1=0.647390  precision@2=0.472173  precision@5=0.250709  precision@10=0.132619  precision@20=0.068524
ndcg@1=0.647390  ndcg@2=0.716786  ndcg@5=0.798008  ndcg@10=0.812659  ndcg@20=0.819979
hit_rate@1=0.647390  hit_rate@2=0.825467  hit_rate@5=0.953125  hit_rate@10=0.975354  hit_rate@20=0.992107
map@1=0.647390  map@2=0.684238  map@5=0.742499  map@10=0.751426  map@20=0.754241
mrr@1=0.647390  mrr@2=0.736429  mrr@5=0.773820  mrr@10=0.776929  mrr@20=0.778165
f1@1=0.569728  f1@2=0.554390  f1@5=0.380031  f1@10=0.226902  f1@20=0.125931

Epoch 59/100: 100%|██████████| 820/820 [00:21<00:00, 37.36it/s, bpr=0.0542, c=2.52, loss=0.155]

[VAL]
recall@1=0.539408  recall@2=0.736403  recall@5=0.918960  recall@10=0.959544  recall@20=0.984652
precision@1=0.649919  precision@2=0.469073  precision@5=0.249613  precision@10=0.132629  precision@20=0.068605
ndcg@1=0.649919  ndcg@2=0.715333  ndcg@5=0.796274  ndcg@10=0.811893  ndcg@20=0.819251
hit_rate@1=0.649919  hit_rate@2=0.822742  hit_rate@5=0.951452  hit_rate@10=0.975645  hit_rate@20=0.991694
map@1=0.649919  map@2=0.683044  map@5=0.740748  map@10=0.750315  map@20=0.753192
mrr@1=0.649919  mrr@2=0.736331  mrr@5=0.773720  mrr@10=0.777155  mrr@20=0.778340
f1@1=0.572002  f1@2=0.551651  f1@5=0.378415  f1@10=0.226778  f1@20=0.126011

[TEST]
recall@1=0.537999  recall@2=0.731437  recall@5=0.920295  recall@10=0.961066  recall@20=0.985654
precision@1=0.647552  precision@2=0.466817  precision@5=0.250306  precision@10=0.132821  precision@20=0.068573
ndcg@1=0.647552  ndcg@2=0.711707  ndcg@5=0.796161  ndcg@10=0.811674  ndcg@20=0.818773
hit_rate@1=0.647552  hit_rate@2=0.817977  hit_rate@5=0.952481  hit_rate@10=0.976240  hit_rate@20=0.992268
map@1=0.647552  map@2=0.679909  map@5=0.740318  map@10=0.749721  map@20=0.752468
mrr@1=0.647552  mrr@2=0.732764  mrr@5=0.772106  mrr@10=0.775470  mrr@20=0.776647
f1@1=0.570414  f1@2=0.548474  f1@5=0.379442  f1@10=0.227173  f1@20=0.125997

Epoch 60/100: 100%|██████████| 820/820 [00:21<00:00, 37.28it/s, bpr=0.0331, c=2.85, loss=0.147]

[VAL]
recall@1=0.538256  recall@2=0.738332  recall@5=0.919010  recall@10=0.958794  recall@20=0.984942
precision@1=0.649113  precision@2=0.470766  precision@5=0.249726  precision@10=0.132395  precision@20=0.068597
ndcg@1=0.649113  ndcg@2=0.716392  ndcg@5=0.796375  ndcg@10=0.811580  ndcg@20=0.819275
hit_rate@1=0.649113  hit_rate@2=0.824758  hit_rate@5=0.951048  hit_rate@10=0.975161  hit_rate@20=0.992258
map@1=0.649113  map@2=0.683770  map@5=0.740951  map@10=0.750192  map@20=0.753186
mrr@1=0.649113  mrr@2=0.736935  mrr@5=0.773621  mrr@10=0.777042  mrr@20=0.778310
f1@1=0.571036  f1@2=0.553374  f1@5=0.378508  f1@10=0.226441  f1@20=0.126010

[TEST]
recall@1=0.538991  recall@2=0.735287  recall@5=0.919934  recall@10=0.960328  recall@20=0.985556
precision@1=0.650451  precision@2=0.470159  precision@5=0.250177  precision@10=0.132748  precision@20=0.068577
ndcg@1=0.650451  ndcg@2=0.715305  ndcg@5=0.797307  ndcg@10=0.812656  ndcg@20=0.819922
hit_rate@1=0.650451  hit_rate@2=0.821118  hit_rate@5=0.951353  hit_rate@10=0.975515  hit_rate@20=0.992026
map@1=0.650451  map@2=0.683513  map@5=0.742056  map@10=0.751298  map@20=0.754084
mrr@1=0.650451  mrr@2=0.735784  mrr@5=0.773962  mrr@10=0.777358  mrr@20=0.778559
f1@1=0.571944  f1@2=0.551884  f1@5=0.379297  f1@10=0.227035  f1@20=0.126006

Epoch 61/100: 100%|██████████| 820/820 [00:21<00:00, 37.44it/s, bpr=0.033, c=2.74, loss=0.143]

[VAL]
recall@1=0.531674  recall@2=0.733592  recall@5=0.915784  recall@10=0.957017  recall@20=0.984987
precision@1=0.640968  precision@2=0.467702  precision@5=0.248774  precision@10=0.132266  precision@20=0.068613
ndcg@1=0.640968  ndcg@2=0.710454  ndcg@5=0.791238  ndcg@10=0.807064  ndcg@20=0.815227
hit_rate@1=0.640968  hit_rate@2=0.820081  hit_rate@5=0.948790  hit_rate@10=0.973790  hit_rate@20=0.992339
map@1=0.640968  map@2=0.677520  map@5=0.735127  map@10=0.744750  map@20=0.747893
mrr@1=0.640968  mrr@2=0.730524  mrr@5=0.767837  mrr@10=0.771367  mrr@20=0.772748
f1@1=0.564019  f1@2=0.549879  f1@5=0.377102  f1@10=0.226142  f1@20=0.126028

[TEST]
recall@1=0.539924  recall@2=0.730072  recall@5=0.916649  recall@10=0.957950  recall@20=0.985283
precision@1=0.651901  precision@2=0.466616  precision@5=0.249404  precision@10=0.132337  precision@20=0.068541
ndcg@1=0.651901  ndcg@2=0.712172  ndcg@5=0.794766  ndcg@10=0.810411  ndcg@20=0.818301
hit_rate@1=0.651901  hit_rate@2=0.816930  hit_rate@5=0.948856  hit_rate@10=0.973663  hit_rate@20=0.992188
map@1=0.651901  map@2=0.680735  map@5=0.739504  map@10=0.748875  map@20=0.751901
mrr@1=0.651901  mrr@2=0.734415  mrr@5=0.772651  mrr@10=0.776164  mrr@20=0.777517
f1@1=0.572941  f1@2=0.547767  f1@5=0.378044  f1@10=0.226400  f1@20=0.125948

Epoch 62/100: 100%|██████████| 820/820 [00:21<00:00, 37.35it/s, bpr=0.0198, c=2.71, loss=0.128]

[VAL]
recall@1=0.541594  recall@2=0.740115  recall@5=0.918685  recall@10=0.959641  recall@20=0.984301
precision@1=0.651855  precision@2=0.472621  precision@5=0.249548  precision@10=0.132605  precision@20=0.068589
ndcg@1=0.651855  ndcg@2=0.718945  ndcg@5=0.797811  ndcg@10=0.813547  ndcg@20=0.820786
hit_rate@1=0.651855  hit_rate@2=0.826532  hit_rate@5=0.951210  hit_rate@10=0.975887  hit_rate@20=0.991694
map@1=0.651855  map@2=0.686794  map@5=0.743149  map@10=0.752786  map@20=0.755589
mrr@1=0.651855  mrr@2=0.739194  mrr@5=0.775372  mrr@10=0.778864  mrr@20=0.780035
f1@1=0.574173  f1@2=0.555250  f1@5=0.378298  f1@10=0.226764  f1@20=0.125967

[TEST]
recall@1=0.543625  recall@2=0.737426  recall@5=0.919797  recall@10=0.959731  recall@20=0.985403
precision@1=0.655847  precision@2=0.472576  precision@5=0.250290  precision@10=0.132635  precision@20=0.068537
ndcg@1=0.655847  ndcg@2=0.719016  ndcg@5=0.799242  ndcg@10=0.814455  ndcg@20=0.821850
hit_rate@1=0.655847  hit_rate@2=0.823695  hit_rate@5=0.951434  hit_rate@10=0.974791  hit_rate@20=0.992188
map@1=0.655847  map@2=0.687721  map@5=0.744718  map@10=0.753955  map@20=0.756781
mrr@1=0.655847  mrr@2=0.739771  mrr@5=0.776883  mrr@10=0.780214  mrr@20=0.781496
f1@1=0.576745  f1@2=0.554126  f1@5=0.379378  f1@10=0.226913  f1@20=0.125952

Epoch 63/100: 100%|██████████| 820/820 [00:21<00:00, 37.38it/s, bpr=0.0326, c=2.66, loss=0.139]

[VAL]
recall@1=0.537382  recall@2=0.733593  recall@5=0.919032  recall@10=0.959270  recall@20=0.984974
precision@1=0.647177  precision@2=0.467863  precision@5=0.249516  precision@10=0.132565  precision@20=0.068637
ndcg@1=0.647177  ndcg@2=0.712747  ndcg@5=0.795259  ndcg@10=0.810754  ndcg@20=0.818266
hit_rate@1=0.647177  hit_rate@2=0.818629  hit_rate@5=0.951935  hit_rate@10=0.975726  hit_rate@20=0.992097
map@1=0.647177  map@2=0.680948  map@5=0.739531  map@10=0.749076  map@20=0.752012
mrr@1=0.647177  mrr@2=0.732903  mrr@5=0.771864  mrr@10=0.775209  mrr@20=0.776404
f1@1=0.569833  f1@2=0.549935  f1@5=0.378319  f1@10=0.226652  f1@20=0.126054

[TEST]
recall@1=0.542661  recall@2=0.734265  recall@5=0.920921  recall@10=0.959937  recall@20=0.985529
precision@1=0.653270  precision@2=0.469394  precision@5=0.250596  precision@10=0.132732  precision@20=0.068549
ndcg@1=0.653270  ndcg@2=0.715892  ndcg@5=0.798878  ndcg@10=0.813759  ndcg@20=0.821070
hit_rate@1=0.653270  hit_rate@2=0.819668  hit_rate@5=0.952481  hit_rate@10=0.974871  hit_rate@20=0.992349
map@1=0.653270  map@2=0.684862  map@5=0.743970  map@10=0.753036  map@20=0.755799
mrr@1=0.653270  mrr@2=0.736469  mrr@5=0.775293  mrr@10=0.778489  mrr@20=0.779754
f1@1=0.575262  f1@2=0.551031  f1@5=0.379834  f1@10=0.227024  f1@20=0.125969

Epoch 64/100: 100%|██████████| 820/820 [00:21<00:00, 37.40it/s, bpr=0.0247, c=2.71, loss=0.133]

[VAL]
recall@1=0.541760  recall@2=0.741035  recall@5=0.920420  recall@10=0.960750  recall@20=0.984769
precision@1=0.652500  precision@2=0.472823  precision@5=0.250016  precision@10=0.132653  precision@20=0.068585
ndcg@1=0.652500  ndcg@2=0.719652  ndcg@5=0.798889  ndcg@10=0.814365  ndcg@20=0.821456
hit_rate@1=0.652500  hit_rate@2=0.827258  hit_rate@5=0.951613  hit_rate@10=0.976855  hit_rate@20=0.992177
map@1=0.652500  map@2=0.687399  map@5=0.744100  map@10=0.753502  map@20=0.756292
mrr@1=0.652500  mrr@2=0.739879  mrr@5=0.776077  mrr@10=0.779667  mrr@20=0.780794
f1@1=0.574402  f1@2=0.555664  f1@5=0.379036  f1@10=0.226883  f1@20=0.125982

[TEST]
recall@1=0.540592  recall@2=0.739277  recall@5=0.921753  recall@10=0.961828  recall@20=0.985311
precision@1=0.651015  precision@2=0.472737  precision@5=0.250741  precision@10=0.132941  precision@20=0.068553
ndcg@1=0.651015  ndcg@2=0.718519  ndcg@5=0.799346  ndcg@10=0.814628  ndcg@20=0.821402
hit_rate@1=0.651015  hit_rate@2=0.825064  hit_rate@5=0.953367  hit_rate@10=0.976562  hit_rate@20=0.991946
map@1=0.651015  map@2=0.686614  map@5=0.744376  map@10=0.753679  map@20=0.756252
mrr@1=0.651015  mrr@2=0.738040  mrr@5=0.775473  mrr@10=0.778743  mrr@20=0.779868
f1@1=0.573256  f1@2=0.554880  f1@5=0.380085  f1@10=0.227395  f1@20=0.125972

Epoch 65/100: 100%|██████████| 820/820 [00:21<00:00, 37.29it/s, bpr=0.0244, c=2.55, loss=0.126]

[VAL]
recall@1=0.545325  recall@2=0.746571  recall@5=0.922852  recall@10=0.962393  recall@20=0.984776
precision@1=0.657742  precision@2=0.476331  precision@5=0.250790  precision@10=0.132927  precision@20=0.068593
ndcg@1=0.657742  ndcg@2=0.724892  ndcg@5=0.802535  ndcg@10=0.817679  ndcg@20=0.824269
hit_rate@1=0.657742  hit_rate@2=0.831452  hit_rate@5=0.953790  hit_rate@10=0.977984  hit_rate@20=0.992258
map@1=0.657742  map@2=0.692742  map@5=0.748145  map@10=0.757364  map@20=0.759963
mrr@1=0.657742  mrr@2=0.744597  mrr@5=0.780169  mrr@10=0.783608  mrr@20=0.784643
f1@1=0.578519  f1@2=0.559783  f1@5=0.380170  f1@10=0.227330  f1@20=0.125987

[TEST]
recall@1=0.540718  recall@2=0.744486  recall@5=0.922608  recall@10=0.962030  recall@20=0.985678
precision@1=0.651659  precision@2=0.476160  precision@5=0.251031  precision@10=0.132941  precision@20=0.068593
ndcg@1=0.651659  ndcg@2=0.722222  ndcg@5=0.800824  ndcg@10=0.815868  ndcg@20=0.822710
hit_rate@1=0.651659  hit_rate@2=0.830461  hit_rate@5=0.953930  hit_rate@10=0.976804  hit_rate@20=0.992349
map@1=0.651659  map@2=0.689755  map@5=0.746052  map@10=0.755248  map@20=0.757891
mrr@1=0.651659  mrr@2=0.741060  mrr@5=0.777008  mrr@10=0.780252  mrr@20=0.781380
f1@1=0.573528  f1@2=0.558894  f1@5=0.380484  f1@10=0.227413  f1@20=0.126029

Epoch 66/100: 100%|██████████| 820/820 [00:21<00:00, 37.30it/s, bpr=0.0445, c=2.55, loss=0.147]

[VAL]
recall@1=0.537653  recall@2=0.734443  recall@5=0.917899  recall@10=0.959825  recall@20=0.984449
precision@1=0.648306  precision@2=0.469355  precision@5=0.249597  precision@10=0.132629  precision@20=0.068560
ndcg@1=0.648306  ndcg@2=0.714004  ndcg@5=0.795141  ndcg@10=0.811060  ndcg@20=0.818281
hit_rate@1=0.648306  hit_rate@2=0.819435  hit_rate@5=0.950242  hit_rate@10=0.976048  hit_rate@20=0.991935
map@1=0.648306  map@2=0.682339  map@5=0.739928  map@10=0.749483  map@20=0.752303
mrr@1=0.648306  mrr@2=0.733871  mrr@5=0.771948  mrr@10=0.775574  mrr@20=0.776752
f1@1=0.570305  f1@2=0.551054  f1@5=0.378203  f1@10=0.226793  f1@20=0.125937

[TEST]
recall@1=0.544691  recall@2=0.735932  recall@5=0.917805  recall@10=0.960748  recall@20=0.985328
precision@1=0.657055  precision@2=0.471247  precision@5=0.249662  precision@10=0.132716  precision@20=0.068553
ndcg@1=0.657055  ndcg@2=0.718228  ndcg@5=0.798535  ndcg@10=0.814811  ndcg@20=0.821982
hit_rate@1=0.657055  hit_rate@2=0.821118  hit_rate@5=0.949903  hit_rate@10=0.975999  hit_rate@20=0.991865
map@1=0.657055  map@2=0.687379  map@5=0.744414  map@10=0.754159  map@20=0.756966
mrr@1=0.657055  mrr@2=0.739087  mrr@5=0.776716  mrr@10=0.780426  mrr@20=0.781596
f1@1=0.577910  f1@2=0.552773  f1@5=0.378480  f1@10=0.227043  f1@20=0.125967

Epoch 67/100: 100%|██████████| 820/820 [00:22<00:00, 37.19it/s, bpr=0.0273, c=2.61, loss=0.132]

[VAL]
recall@1=0.537104  recall@2=0.737515  recall@5=0.918981  recall@10=0.959562  recall@20=0.984508
precision@1=0.646694  precision@2=0.470766  precision@5=0.249855  precision@10=0.132613  precision@20=0.068625
ndcg@1=0.646694  ndcg@2=0.715428  ndcg@5=0.795762  ndcg@10=0.811243  ndcg@20=0.818597
hit_rate@1=0.646694  hit_rate@2=0.823226  hit_rate@5=0.950726  hit_rate@10=0.975887  hit_rate@20=0.991694
map@1=0.646694  map@2=0.683105  map@5=0.740377  map@10=0.749742  map@20=0.752636
mrr@1=0.646694  mrr@2=0.734960  mrr@5=0.772043  mrr@10=0.775590  mrr@20=0.776763
f1@1=0.569522  f1@2=0.553100  f1@5=0.378659  f1@10=0.226756  f1@20=0.126024

[TEST]
recall@1=0.542066  recall@2=0.733883  recall@5=0.918064  recall@10=0.960406  recall@20=0.985252
precision@1=0.654478  precision@2=0.469676  precision@5=0.249662  precision@10=0.132740  precision@20=0.068529
ndcg@1=0.654478  ndcg@2=0.715712  ndcg@5=0.797324  ndcg@10=0.813392  ndcg@20=0.820552
hit_rate@1=0.654478  hit_rate@2=0.819749  hit_rate@5=0.950226  hit_rate@10=0.975515  hit_rate@20=0.992107
map@1=0.654478  map@2=0.684480  map@5=0.742511  map@10=0.752179  map@20=0.754918
mrr@1=0.654478  mrr@2=0.737113  mrr@5=0.775318  mrr@10=0.778887  mrr@20=0.780095
f1@1=0.575318  f1@2=0.551097  f1@5=0.378483  f1@10=0.227047  f1@20=0.125936

Epoch 68/100: 100%|██████████| 820/820 [00:22<00:00, 37.14it/s, bpr=0.0197, c=2.77, loss=0.13]

[VAL]
recall@1=0.542509  recall@2=0.738987  recall@5=0.916412  recall@10=0.958855  recall@20=0.984737
precision@1=0.654113  precision@2=0.471250  precision@5=0.248968  precision@10=0.132355  precision@20=0.068556
ndcg@1=0.654113  ndcg@2=0.718316  ndcg@5=0.796664  ndcg@10=0.812791  ndcg@20=0.820392
hit_rate@1=0.654113  hit_rate@2=0.825403  hit_rate@5=0.948710  hit_rate@10=0.975726  hit_rate@20=0.992016
map@1=0.654113  map@2=0.686129  map@5=0.742155  map@10=0.751762  map@20=0.754738
mrr@1=0.654113  mrr@2=0.739718  mrr@5=0.775485  mrr@10=0.779299  mrr@20=0.780463
f1@1=0.575546  f1@2=0.554043  f1@5=0.377455  f1@10=0.226398  f1@20=0.125941

[TEST]
recall@1=0.537115  recall@2=0.735918  recall@5=0.917494  recall@10=0.960822  recall@20=0.986112
precision@1=0.649082  precision@2=0.471086  precision@5=0.249694  precision@10=0.132780  precision@20=0.068613
ndcg@1=0.649082  ndcg@2=0.715388  ndcg@5=0.795391  ndcg@10=0.811724  ndcg@20=0.819022
hit_rate@1=0.649082  hit_rate@2=0.821923  hit_rate@5=0.949259  hit_rate@10=0.975838  hit_rate@20=0.992590
map@1=0.649082  map@2=0.683372  map@5=0.740206  map@10=0.749929  map@20=0.752714
mrr@1=0.649082  mrr@2=0.735503  mrr@5=0.772490  mrr@10=0.776267  mrr@20=0.777488
f1@1=0.570138  f1@2=0.552636  f1@5=0.378407  f1@10=0.227122  f1@20=0.126085

Epoch 69/100: 100%|██████████| 820/820 [00:22<00:00, 37.25it/s, bpr=0.0378, c=2.51, loss=0.138]

[VAL]
recall@1=0.544621  recall@2=0.742487  recall@5=0.919501  recall@10=0.958945  recall@20=0.984926
precision@1=0.655887  precision@2=0.474839  precision@5=0.249952  precision@10=0.132435  precision@20=0.068593
ndcg@1=0.655887  ndcg@2=0.722078  ndcg@5=0.800081  ndcg@10=0.815203  ndcg@20=0.822810
hit_rate@1=0.655887  hit_rate@2=0.827823  hit_rate@5=0.950565  hit_rate@10=0.975242  hit_rate@20=0.992258
map@1=0.655887  map@2=0.690423  map@5=0.746203  map@10=0.755374  map@20=0.758315
mrr@1=0.655887  mrr@2=0.741855  mrr@5=0.777656  mrr@10=0.781172  mrr@20=0.782426
f1@1=0.577543  f1@2=0.557447  f1@5=0.378876  f1@10=0.226506  f1@20=0.125997

[TEST]
recall@1=0.541753  recall@2=0.742426  recall@5=0.919618  recall@10=0.960229  recall@20=0.986544
precision@1=0.653351  precision@2=0.475838  precision@5=0.250274  precision@10=0.132595  precision@20=0.068637
ndcg@1=0.653351  ndcg@2=0.721653  ndcg@5=0.799913  ndcg@10=0.815272  ndcg@20=0.822863
hit_rate@1=0.653351  hit_rate@2=0.828689  hit_rate@5=0.950548  hit_rate@10=0.975515  hit_rate@20=0.992993
map@1=0.653351  map@2=0.689654  map@5=0.745884  map@10=0.755088  map@20=0.757984
mrr@1=0.653351  mrr@2=0.741020  mrr@5=0.776885  mrr@10=0.780421  mrr@20=0.781683
f1@1=0.574697  f1@2=0.557929  f1@5=0.379320  f1@10=0.226867  f1@20=0.126117

Epoch 70/100: 100%|██████████| 820/820 [00:21<00:00, 37.43it/s, bpr=0.0166, c=2.7, loss=0.124]

[VAL]
recall@1=0.538813  recall@2=0.731415  recall@5=0.917908  recall@10=0.959577  recall@20=0.985367
precision@1=0.650806  precision@2=0.468024  precision@5=0.249323  precision@10=0.132556  precision@20=0.068605
ndcg@1=0.650806  ndcg@2=0.712522  ndcg@5=0.794799  ndcg@10=0.810753  ndcg@20=0.818278
hit_rate@1=0.650806  hit_rate@2=0.815323  hit_rate@5=0.950403  hit_rate@10=0.975726  hit_rate@20=0.992581
map@1=0.650806  map@2=0.681593  map@5=0.739404  map@10=0.749091  map@20=0.752018
mrr@1=0.650806  mrr@2=0.733065  mrr@5=0.772254  mrr@10=0.775831  mrr@20=0.777057
f1@1=0.571934  f1@2=0.549294  f1@5=0.377980  f1@10=0.226674  f1@20=0.126027

[TEST]
recall@1=0.537406  recall@2=0.730322  recall@5=0.918109  recall@10=0.961323  recall@20=0.985675
precision@1=0.649001  precision@2=0.468589  precision@5=0.249581  precision@10=0.132788  precision@20=0.068569
ndcg@1=0.649001  ndcg@2=0.711900  ndcg@5=0.794550  ndcg@10=0.810943  ndcg@20=0.818003
hit_rate@1=0.649001  hit_rate@2=0.814191  hit_rate@5=0.950789  hit_rate@10=0.976160  hit_rate@20=0.992107
map@1=0.649001  map@2=0.681238  map@5=0.738975  map@10=0.748927  map@20=0.751635
mrr@1=0.649001  mrr@2=0.731596  mrr@5=0.771294  mrr@10=0.774863  mrr@20=0.776032
f1@1=0.570388  f1@2=0.549172  f1@5=0.378388  f1@10=0.227176  f1@20=0.126006

Epoch 71/100: 100%|██████████| 820/820 [00:22<00:00, 37.20it/s, bpr=0.0342, c=2.65, loss=0.14]

[VAL]
recall@1=0.539394  recall@2=0.736574  recall@5=0.919396  recall@10=0.958522  recall@20=0.984728
precision@1=0.650403  precision@2=0.469718  precision@5=0.249823  precision@10=0.132411  precision@20=0.068565
ndcg@1=0.650403  ndcg@2=0.715531  ndcg@5=0.796637  ndcg@10=0.811658  ndcg@20=0.819315
hit_rate@1=0.650403  hit_rate@2=0.821855  hit_rate@5=0.951613  hit_rate@10=0.975081  hit_rate@20=0.992419
map@1=0.650403  map@2=0.683528  map@5=0.741231  map@10=0.750406  map@20=0.753390
mrr@1=0.650403  mrr@2=0.736129  mrr@5=0.773874  mrr@10=0.777203  mrr@20=0.778469
f1@1=0.572219  f1@2=0.552221  f1@5=0.378697  f1@10=0.226421  f1@20=0.125946

[TEST]
recall@1=0.542413  recall@2=0.734811  recall@5=0.918297  recall@10=0.959397  recall@20=0.985227
precision@1=0.653673  precision@2=0.470079  precision@5=0.249646  precision@10=0.132563  precision@20=0.068516
ndcg@1=0.653673  ndcg@2=0.716335  ndcg@5=0.797423  ndcg@10=0.813126  ndcg@20=0.820576
hit_rate@1=0.653673  hit_rate@2=0.819910  hit_rate@5=0.950628  hit_rate@10=0.974871  hit_rate@20=0.992268
map@1=0.653673  map@2=0.685305  map@5=0.742801  map@10=0.752371  map@20=0.755206
mrr@1=0.653673  mrr@2=0.736791  mrr@5=0.774784  mrr@10=0.778240  mrr@20=0.779518
f1@1=0.575273  f1@2=0.551663  f1@5=0.378491  f1@10=0.226785  f1@20=0.125918

Epoch 72/100: 100%|██████████| 820/820 [00:22<00:00, 37.25it/s, bpr=0.0547, c=2.59, loss=0.158]

[VAL]
recall@1=0.539169  recall@2=0.738582  recall@5=0.917407  recall@10=0.959258  recall@20=0.984972
precision@1=0.650565  precision@2=0.471008  precision@5=0.249419  precision@10=0.132500  precision@20=0.068565
ndcg@1=0.650565  ndcg@2=0.716949  ndcg@5=0.796063  ndcg@10=0.811996  ndcg@20=0.819517
hit_rate@1=0.650565  hit_rate@2=0.824597  hit_rate@5=0.949758  hit_rate@10=0.975484  hit_rate@20=0.992581
map@1=0.650565  map@2=0.684516  map@5=0.740978  map@10=0.750568  map@20=0.753488
mrr@1=0.650565  mrr@2=0.737581  mrr@5=0.774023  mrr@10=0.777698  mrr@20=0.778944
f1@1=0.572084  f1@2=0.553662  f1@5=0.378038  f1@10=0.226610  f1@20=0.125961

[TEST]
recall@1=0.539871  recall@2=0.738282  recall@5=0.917989  recall@10=0.959028  recall@20=0.985129
precision@1=0.651337  precision@2=0.471770  precision@5=0.249630  precision@10=0.132474  precision@20=0.068504
ndcg@1=0.651337  ndcg@2=0.717519  ndcg@5=0.796978  ndcg@10=0.812631  ndcg@20=0.820193
hit_rate@1=0.651337  hit_rate@2=0.824178  hit_rate@5=0.949903  hit_rate@10=0.974468  hit_rate@20=0.992188
map@1=0.651337  map@2=0.685466  map@5=0.742224  map@10=0.751685  map@20=0.754599
mrr@1=0.651337  mrr@2=0.737758  mrr@5=0.774294  mrr@10=0.777819  mrr@20=0.779131
f1@1=0.572826  f1@2=0.553988  f1@5=0.378424  f1@10=0.226634  f1@20=0.125896

Epoch 73/100: 100%|██████████| 820/820 [00:21<00:00, 37.29it/s, bpr=0.0354, c=2.7, loss=0.143]

[VAL]
recall@1=0.540706  recall@2=0.741423  recall@5=0.916872  recall@10=0.960657  recall@20=0.985471
precision@1=0.650968  precision@2=0.472581  precision@5=0.249161  precision@10=0.132694  precision@20=0.068653
ndcg@1=0.650968  ndcg@2=0.719170  ndcg@5=0.796691  ndcg@10=0.813391  ndcg@20=0.820677
hit_rate@1=0.650968  hit_rate@2=0.827177  hit_rate@5=0.949597  hit_rate@10=0.976855  hit_rate@20=0.992419
map@1=0.650968  map@2=0.686714  map@5=0.742054  map@10=0.752109  map@20=0.754981
mrr@1=0.650968  mrr@2=0.739073  mrr@5=0.774672  mrr@10=0.778570  mrr@20=0.779698
f1@1=0.573345  f1@2=0.555673  f1@5=0.377684  f1@10=0.226910  f1@20=0.126103

[TEST]
recall@1=0.542784  recall@2=0.737510  recall@5=0.919040  recall@10=0.960671  recall@20=0.985772
precision@1=0.653834  precision@2=0.470602  precision@5=0.249839  precision@10=0.132756  precision@20=0.068585
ndcg@1=0.653834  ndcg@2=0.717786  ndcg@5=0.798271  ndcg@10=0.814099  ndcg@20=0.821359
hit_rate@1=0.653834  hit_rate@2=0.824420  hit_rate@5=0.951836  hit_rate@10=0.975596  hit_rate@20=0.992268
map@1=0.653834  map@2=0.685809  map@5=0.743322  map@10=0.752960  map@20=0.755740
mrr@1=0.653834  mrr@2=0.739127  mrr@5=0.776171  mrr@10=0.779530  mrr@20=0.780753
f1@1=0.575620  f1@2=0.552981  f1@5=0.378724  f1@10=0.227101  f1@20=0.126028

Epoch 74/100: 100%|██████████| 820/820 [00:22<00:00, 37.23it/s, bpr=0.0259, c=2.72, loss=0.135]

[VAL]
recall@1=0.537858  recall@2=0.738730  recall@5=0.917039  recall@10=0.956844  recall@20=0.985370
precision@1=0.648145  precision@2=0.470484  precision@5=0.249097  precision@10=0.132113  precision@20=0.068625
ndcg@1=0.648145  ndcg@2=0.716229  ndcg@5=0.795208  ndcg@10=0.810476  ndcg@20=0.818804
hit_rate@1=0.648145  hit_rate@2=0.824597  hit_rate@5=0.949919  hit_rate@10=0.974113  hit_rate@20=0.992500
map@1=0.648145  map@2=0.683609  map@5=0.740042  map@10=0.749369  map@20=0.752586
mrr@1=0.648145  mrr@2=0.736371  mrr@5=0.772812  mrr@10=0.776244  mrr@20=0.777586
f1@1=0.570395  f1@2=0.553407  f1@5=0.377658  f1@10=0.225945  f1@20=0.126057

[TEST]
recall@1=0.541752  recall@2=0.734722  recall@5=0.917060  recall@10=0.958174  recall@20=0.985136
precision@1=0.652948  precision@2=0.469596  precision@5=0.249452  precision@10=0.132337  precision@20=0.068512
ndcg@1=0.652948  ndcg@2=0.715831  ndcg@5=0.796679  ndcg@10=0.812282  ndcg@20=0.820070
hit_rate@1=0.652948  hit_rate@2=0.819910  hit_rate@5=0.949098  hit_rate@10=0.973744  hit_rate@20=0.991785
map@1=0.652948  map@2=0.684601  map@5=0.742183  map@10=0.751590  map@20=0.754540
mrr@1=0.652948  mrr@2=0.736429  mrr@5=0.774149  mrr@10=0.777654  mrr@20=0.778984
f1@1=0.574633  f1@2=0.551339  f1@5=0.378140  f1@10=0.226408  f1@20=0.125909

Epoch 75/100: 100%|██████████| 820/820 [00:21<00:00, 37.28it/s, bpr=0.0256, c=2.61, loss=0.13]

[VAL]
recall@1=0.539215  recall@2=0.742281  recall@5=0.918237  recall@10=0.959061  recall@20=0.984824
precision@1=0.649032  precision@2=0.473226  precision@5=0.249452  precision@10=0.132452  precision@20=0.068552
ndcg@1=0.649032  ndcg@2=0.719103  ndcg@5=0.796937  ndcg@10=0.812588  ndcg@20=0.820115
hit_rate@1=0.649032  hit_rate@2=0.828468  hit_rate@5=0.950968  hit_rate@10=0.975726  hit_rate@20=0.992581
map@1=0.649032  map@2=0.686270  map@5=0.742016  map@10=0.751575  map@20=0.754497
mrr@1=0.649032  mrr@2=0.738750  mrr@5=0.774313  mrr@10=0.777830  mrr@20=0.779052
f1@1=0.571799  f1@2=0.556443  f1@5=0.378152  f1@10=0.226506  f1@20=0.125936

[TEST]
recall@1=0.542983  recall@2=0.738514  recall@5=0.919684  recall@10=0.959459  recall@20=0.984937
precision@1=0.655525  precision@2=0.472415  precision@5=0.250064  precision@10=0.132595  precision@20=0.068537
ndcg@1=0.655525  ndcg@2=0.719287  ndcg@5=0.799177  ndcg@10=0.814422  ndcg@20=0.821788
hit_rate@1=0.655525  hit_rate@2=0.824742  hit_rate@5=0.951514  hit_rate@10=0.974791  hit_rate@20=0.991463
map@1=0.655525  map@2=0.687581  map@5=0.744483  map@10=0.753829  map@20=0.756663
mrr@1=0.655525  mrr@2=0.740134  mrr@5=0.777063  mrr@10=0.780393  mrr@20=0.781614
f1@1=0.576246  f1@2=0.554340  f1@5=0.379107  f1@10=0.226826  f1@20=0.125932

Epoch 76/100: 100%|██████████| 820/820 [00:22<00:00, 37.20it/s, bpr=0.0449, c=2.62, loss=0.15]

[VAL]
recall@1=0.537870  recall@2=0.731504  recall@5=0.916863  recall@10=0.958181  recall@20=0.984403
precision@1=0.647903  precision@2=0.467097  precision@5=0.249065  precision@10=0.132323  precision@20=0.068548
ndcg@1=0.647903  ndcg@2=0.711841  ndcg@5=0.793964  ndcg@10=0.809799  ndcg@20=0.817467
hit_rate@1=0.647903  hit_rate@2=0.817339  hit_rate@5=0.949435  hit_rate@10=0.974839  hit_rate@20=0.991935
map@1=0.647903  map@2=0.680222  map@5=0.738497  map@10=0.748105  map@20=0.751081
mrr@1=0.647903  mrr@2=0.732621  mrr@5=0.771077  mrr@10=0.774733  mrr@20=0.775986
f1@1=0.570394  f1@2=0.548621  f1@5=0.377562  f1@10=0.226325  f1@20=0.125921

[TEST]
recall@1=0.540766  recall@2=0.730568  recall@5=0.918370  recall@10=0.959187  recall@20=0.984933
precision@1=0.651659  precision@2=0.466535  precision@5=0.249646  precision@10=0.132579  precision@20=0.068516
ndcg@1=0.651659  ndcg@2=0.712400  ndcg@5=0.796023  ndcg@10=0.811683  ndcg@20=0.819085
hit_rate@1=0.651659  hit_rate@2=0.816044  hit_rate@5=0.950467  hit_rate@10=0.974630  hit_rate@20=0.991865
map@1=0.651659  map@2=0.681318  map@5=0.740751  map@10=0.750309  map@20=0.753102
mrr@1=0.651659  mrr@2=0.733851  mrr@5=0.773115  mrr@10=0.776608  mrr@20=0.777869
f1@1=0.573529  f1@2=0.548002  f1@5=0.378535  f1@10=0.226751  f1@20=0.125907

Epoch 77/100: 100%|██████████| 820/820 [00:22<00:00, 36.92it/s, bpr=0.0333, c=2.56, loss=0.136]

[VAL]
recall@1=0.535314  recall@2=0.734625  recall@5=0.917749  recall@10=0.958945  recall@20=0.985036
precision@1=0.645887  precision@2=0.469153  precision@5=0.249339  precision@10=0.132524  precision@20=0.068637
ndcg@1=0.645887  ndcg@2=0.712980  ndcg@5=0.793922  ndcg@10=0.809711  ndcg@20=0.817349
hit_rate@1=0.645887  hit_rate@2=0.821774  hit_rate@5=0.950806  hit_rate@10=0.975081  hit_rate@20=0.992339
map@1=0.645887  map@2=0.680343  map@5=0.737969  map@10=0.747621  map@20=0.750577
mrr@1=0.645887  mrr@2=0.733831  mrr@5=0.771179  mrr@10=0.774618  mrr@20=0.775892
f1@1=0.568037  f1@2=0.551089  f1@5=0.377956  f1@10=0.226607  f1@20=0.126059

[TEST]
recall@1=0.542714  recall@2=0.734612  recall@5=0.919234  recall@10=0.960481  recall@20=0.985997
precision@1=0.655525  precision@2=0.469998  precision@5=0.249984  precision@10=0.132724  precision@20=0.068557
ndcg@1=0.655525  ndcg@2=0.716523  ndcg@5=0.798043  ndcg@10=0.813747  ndcg@20=0.821085
hit_rate@1=0.655525  hit_rate@2=0.820715  hit_rate@5=0.950709  hit_rate@10=0.975354  hit_rate@20=0.992590
map@1=0.655525  map@2=0.685205  map@5=0.743197  map@10=0.752673  map@20=0.755457
mrr@1=0.655525  mrr@2=0.738120  mrr@5=0.775879  mrr@10=0.779377  mrr@20=0.780646
f1@1=0.576057  f1@2=0.551517  f1@5=0.379053  f1@10=0.227059  f1@20=0.125996

Epoch 78/100: 100%|██████████| 820/820 [00:22<00:00, 36.54it/s, bpr=0.0209, c=2.78, loss=0.132]

[VAL]
recall@1=0.537028  recall@2=0.735121  recall@5=0.918560  recall@10=0.959646  recall@20=0.985198
precision@1=0.645806  precision@2=0.468185  precision@5=0.249226  precision@10=0.132605  precision@20=0.068633
ndcg@1=0.645806  ndcg@2=0.713131  ndcg@5=0.794900  ndcg@10=0.810794  ndcg@20=0.818267
hit_rate@1=0.645806  hit_rate@2=0.821935  hit_rate@5=0.952016  hit_rate@10=0.975645  hit_rate@20=0.992016
map@1=0.645806  map@2=0.680565  map@5=0.739041  map@10=0.748866  map@20=0.751777
mrr@1=0.645806  mrr@2=0.733871  mrr@5=0.771800  mrr@10=0.775168  mrr@20=0.776374
f1@1=0.569249  f1@2=0.550769  f1@5=0.377994  f1@10=0.226770  f1@20=0.126062

[TEST]
recall@1=0.540008  recall@2=0.731266  recall@5=0.919316  recall@10=0.961959  recall@20=0.986250
precision@1=0.651095  precision@2=0.467260  precision@5=0.250032  precision@10=0.132909  precision@20=0.068581
ndcg@1=0.651095  ndcg@2=0.712782  ndcg@5=0.796527  ndcg@10=0.812713  ndcg@20=0.819698
hit_rate@1=0.651095  hit_rate@2=0.817655  hit_rate@5=0.951353  hit_rate@10=0.976804  hit_rate@20=0.992912
map@1=0.651095  map@2=0.681339  map@5=0.741076  map@10=0.750851  map@20=0.753513
mrr@1=0.651095  mrr@2=0.734375  mrr@5=0.773415  mrr@10=0.777034  mrr@20=0.778204
f1@1=0.572847  f1@2=0.548639  f1@5=0.379000  f1@10=0.227358  f1@20=0.126037

Epoch 79/100: 100%|██████████| 820/820 [00:22<00:00, 37.16it/s, bpr=0.0445, c=2.52, loss=0.145]

[VAL]
recall@1=0.538758  recall@2=0.742173  recall@5=0.918626  recall@10=0.959937  recall@20=0.984460
precision@1=0.649919  precision@2=0.473427  precision@5=0.249726  precision@10=0.132637  precision@20=0.068569
ndcg@1=0.649919  ndcg@2=0.719340  ndcg@5=0.797341  ndcg@10=0.813129  ndcg@20=0.820314
hit_rate@1=0.649919  hit_rate@2=0.828871  hit_rate@5=0.950484  hit_rate@10=0.975806  hit_rate@20=0.991935
map@1=0.649919  map@2=0.686411  map@5=0.742498  map@10=0.752023  map@20=0.754816
mrr@1=0.649919  mrr@2=0.739395  mrr@5=0.774839  mrr@10=0.778457  mrr@20=0.779645
f1@1=0.571520  f1@2=0.556449  f1@5=0.378470  f1@10=0.226817  f1@20=0.125942

[TEST]
recall@1=0.543301  recall@2=0.740977  recall@5=0.920910  recall@10=0.961659  recall@20=0.985534
precision@1=0.655445  precision@2=0.473905  precision@5=0.250596  precision@10=0.132837  precision@20=0.068553
ndcg@1=0.655445  ndcg@2=0.720833  ndcg@5=0.800485  ndcg@10=0.815994  ndcg@20=0.822881
hit_rate@1=0.655445  hit_rate@2=0.827159  hit_rate@5=0.951997  hit_rate@10=0.976885  hit_rate@20=0.992510
map@1=0.655445  map@2=0.688909  map@5=0.745955  map@10=0.755358  map@20=0.758000
mrr@1=0.655445  mrr@2=0.741302  mrr@5=0.777788  mrr@10=0.781369  mrr@20=0.782478
f1@1=0.576498  f1@2=0.556248  f1@5=0.379795  f1@10=0.227237  f1@20=0.125967

Epoch 80/100: 100%|██████████| 820/820 [00:21<00:00, 37.37it/s, bpr=0.0245, c=2.62, loss=0.129]

[VAL]
recall@1=0.538821  recall@2=0.737109  recall@5=0.918766  recall@10=0.959494  recall@20=0.985135
precision@1=0.648871  precision@2=0.470524  precision@5=0.249452  precision@10=0.132565  precision@20=0.068605
ndcg@1=0.648871  ndcg@2=0.715756  ndcg@5=0.796286  ndcg@10=0.811984  ndcg@20=0.819473
hit_rate@1=0.648871  hit_rate@2=0.822823  hit_rate@5=0.951129  hit_rate@10=0.975806  hit_rate@20=0.992419
map@1=0.648871  map@2=0.683690  map@5=0.741112  map@10=0.750720  map@20=0.753629
mrr@1=0.648871  mrr@2=0.735847  mrr@5=0.773273  mrr@10=0.776767  mrr@20=0.777982
f1@1=0.571344  f1@2=0.552906  f1@5=0.378268  f1@10=0.226682  f1@20=0.126024

[TEST]
recall@1=0.545789  recall@2=0.735926  recall@5=0.920704  recall@10=0.960123  recall@20=0.985899
precision@1=0.657700  precision@2=0.471045  precision@5=0.250435  precision@10=0.132700  precision@20=0.068585
ndcg@1=0.657700  ndcg@2=0.718429  ndcg@5=0.800453  ndcg@10=0.815482  ndcg@20=0.822886
hit_rate@1=0.657700  hit_rate@2=0.821923  hit_rate@5=0.952642  hit_rate@10=0.975032  hit_rate@20=0.992590
map@1=0.657700  map@2=0.687480  map@5=0.746012  map@10=0.755219  map@20=0.758004
mrr@1=0.657700  mrr@2=0.739812  mrr@5=0.778071  mrr@10=0.781228  mrr@20=0.782513
f1@1=0.578903  f1@2=0.552637  f1@5=0.379570  f1@10=0.226973  f1@20=0.126026

Epoch 81/100: 100%|██████████| 820/820 [00:21<00:00, 37.30it/s, bpr=0.028, c=2.75, loss=0.138]

[VAL]
recall@1=0.535591  recall@2=0.739907  recall@5=0.916924  recall@10=0.958002  recall@20=0.985026
precision@1=0.646290  precision@2=0.472097  precision@5=0.249306  precision@10=0.132339  precision@20=0.068657
ndcg@1=0.646290  ndcg@2=0.716622  ndcg@5=0.794570  ndcg@10=0.810174  ndcg@20=0.818114
hit_rate@1=0.646290  hit_rate@2=0.827016  hit_rate@5=0.949274  hit_rate@10=0.974839  hit_rate@20=0.991935
map@1=0.646290  map@2=0.683448  map@5=0.739193  map@10=0.748560  map@20=0.751676
mrr@1=0.646290  mrr@2=0.736653  mrr@5=0.771976  mrr@10=0.775568  mrr@20=0.776831
f1@1=0.568245  f1@2=0.554809  f1@5=0.377811  f1@10=0.226300  f1@20=0.126090

[TEST]
recall@1=0.537855  recall@2=0.737288  recall@5=0.917808  recall@10=0.958796  recall@20=0.985389
precision@1=0.648921  precision@2=0.471690  precision@5=0.249517  precision@10=0.132490  precision@20=0.068537
ndcg@1=0.648921  ndcg@2=0.716303  ndcg@5=0.795829  ndcg@10=0.811443  ndcg@20=0.819120
hit_rate@1=0.648921  hit_rate@2=0.823695  hit_rate@5=0.950226  hit_rate@10=0.974388  hit_rate@20=0.992107
map@1=0.648921  map@2=0.684097  map@5=0.740757  map@10=0.750188  map@20=0.753125
mrr@1=0.648921  mrr@2=0.736308  mrr@5=0.772923  mrr@10=0.776336  mrr@20=0.777641
f1@1=0.570700  f1@2=0.553544  f1@5=0.378318  f1@10=0.226647  f1@20=0.125956

Epoch 82/100: 100%|██████████| 820/820 [00:21<00:00, 37.44it/s, bpr=0.0447, c=2.56, loss=0.147]

[VAL]
recall@1=0.536448  recall@2=0.736380  recall@5=0.919831  recall@10=0.960000  recall@20=0.984740
precision@1=0.646290  precision@2=0.469556  precision@5=0.250032  precision@10=0.132653  precision@20=0.068581
ndcg@1=0.646290  ndcg@2=0.714332  ndcg@5=0.795698  ndcg@10=0.811134  ndcg@20=0.818376
hit_rate@1=0.646290  hit_rate@2=0.822581  hit_rate@5=0.951774  hit_rate@10=0.975968  hit_rate@20=0.992016
map@1=0.646290  map@2=0.681835  map@5=0.739952  map@10=0.749390  map@20=0.752218
mrr@1=0.646290  mrr@2=0.734435  mrr@5=0.771895  mrr@10=0.775357  mrr@20=0.776541
f1@1=0.568868  f1@2=0.551966  f1@5=0.378945  f1@10=0.226841  f1@20=0.125972

[TEST]
recall@1=0.542444  recall@2=0.734839  recall@5=0.921753  recall@10=0.960606  recall@20=0.985436
precision@1=0.654800  precision@2=0.470321  precision@5=0.250822  precision@10=0.132732  precision@20=0.068557
ndcg@1=0.654800  ndcg@2=0.716490  ndcg@5=0.799312  ndcg@10=0.814103  ndcg@20=0.821270
hit_rate@1=0.654800  hit_rate@2=0.819427  hit_rate@5=0.952722  hit_rate@10=0.975838  hit_rate@20=0.992349
map@1=0.654800  map@2=0.685547  map@5=0.744254  map@10=0.753252  map@20=0.755978
mrr@1=0.654800  mrr@2=0.737113  mrr@5=0.775930  mrr@10=0.779211  mrr@20=0.780409
f1@1=0.575682  f1@2=0.551837  f1@5=0.380167  f1@10=0.227059  f1@20=0.125975

Epoch 83/100: 100%|██████████| 820/820 [00:21<00:00, 37.32it/s, bpr=0.0243, c=2.64, loss=0.13]

[VAL]
recall@1=0.535073  recall@2=0.736015  recall@5=0.918171  recall@10=0.957721  recall@20=0.984997
precision@1=0.646129  precision@2=0.469839  precision@5=0.249597  precision@10=0.132339  precision@20=0.068601
ndcg@1=0.646129  ndcg@2=0.713843  ndcg@5=0.794351  ndcg@10=0.809455  ndcg@20=0.817450
hit_rate@1=0.646129  hit_rate@2=0.822339  hit_rate@5=0.950484  hit_rate@10=0.974435  hit_rate@20=0.992016
map@1=0.646129  map@2=0.681190  map@5=0.738491  map@10=0.747666  map@20=0.750787
mrr@1=0.646129  mrr@2=0.734194  mrr@5=0.771336  mrr@10=0.774712  mrr@20=0.776029
f1@1=0.567865  f1@2=0.552006  f1@5=0.378246  f1@10=0.226283  f1@20=0.126013

[TEST]
recall@1=0.539896  recall@2=0.734020  recall@5=0.917474  recall@10=0.959194  recall@20=0.985255
precision@1=0.651418  precision@2=0.469072  precision@5=0.249533  precision@10=0.132523  precision@20=0.068516
ndcg@1=0.651418  ndcg@2=0.714650  ndcg@5=0.795966  ndcg@10=0.811849  ndcg@20=0.819396
hit_rate@1=0.651418  hit_rate@2=0.819507  hit_rate@5=0.949017  hit_rate@10=0.974227  hit_rate@20=0.992349
map@1=0.651418  map@2=0.683131  map@5=0.741124  map@10=0.750673  map@20=0.753554
mrr@1=0.651418  mrr@2=0.735503  mrr@5=0.773087  mrr@10=0.776721  mrr@20=0.778076
f1@1=0.572864  f1@2=0.550781  f1@5=0.378308  f1@10=0.226710  f1@20=0.125912

Epoch 84/100: 100%|██████████| 820/820 [00:22<00:00, 37.18it/s, bpr=0.0335, c=2.59, loss=0.137]

[VAL]
recall@1=0.541644  recall@2=0.744082  recall@5=0.921019  recall@10=0.960893  recall@20=0.984985
precision@1=0.651855  precision@2=0.474315  precision@5=0.250355  precision@10=0.132742  precision@20=0.068597
ndcg@1=0.651855  ndcg@2=0.721331  ndcg@5=0.799681  ndcg@10=0.814950  ndcg@20=0.822026
hit_rate@1=0.651855  hit_rate@2=0.830323  hit_rate@5=0.952903  hit_rate@10=0.976855  hit_rate@20=0.992177
map@1=0.651855  map@2=0.688609  map@5=0.744860  map@10=0.754191  map@20=0.756975
mrr@1=0.651855  mrr@2=0.741089  mrr@5=0.776715  mrr@10=0.780112  mrr@20=0.781231
f1@1=0.574278  f1@2=0.557692  f1@5=0.379395  f1@10=0.226990  f1@20=0.126003

[TEST]
recall@1=0.542397  recall@2=0.739394  recall@5=0.921294  recall@10=0.961810  recall@20=0.985681
precision@1=0.653914  precision@2=0.472052  precision@5=0.250564  precision@10=0.132941  precision@20=0.068557
ndcg@1=0.653914  ndcg@2=0.719089  ndcg@5=0.800083  ndcg@10=0.815570  ndcg@20=0.822421
hit_rate@1=0.653914  hit_rate@2=0.824742  hit_rate@5=0.952320  hit_rate@10=0.976643  hit_rate@20=0.992510
map@1=0.653914  map@2=0.687299  map@5=0.745465  map@10=0.754872  map@20=0.757476
mrr@1=0.653914  mrr@2=0.739328  mrr@5=0.776787  mrr@10=0.780244  mrr@20=0.781384
f1@1=0.575351  f1@2=0.554537  f1@5=0.379911  f1@10=0.227380  f1@20=0.125978

Epoch 85/100: 100%|██████████| 820/820 [00:21<00:00, 37.34it/s, bpr=0.0519, c=2.5, loss=0.152]

[VAL]
recall@1=0.533672  recall@2=0.739209  recall@5=0.922525  recall@10=0.962223  recall@20=0.984872
precision@1=0.643952  precision@2=0.471492  precision@5=0.250661  precision@10=0.132919  precision@20=0.068589
ndcg@1=0.643952  ndcg@2=0.715219  ndcg@5=0.796702  ndcg@10=0.811950  ndcg@20=0.818628
hit_rate@1=0.643952  hit_rate@2=0.826129  hit_rate@5=0.954919  hit_rate@10=0.977984  hit_rate@20=0.992097
map@1=0.643952  map@2=0.681855  map@5=0.740162  map@10=0.749556  map@20=0.752201
mrr@1=0.643952  mrr@2=0.735040  mrr@5=0.772630  mrr@10=0.775907  mrr@20=0.776945
f1@1=0.566284  f1@2=0.554207  f1@5=0.379949  f1@10=0.227304  f1@20=0.125989

[TEST]
recall@1=0.535076  recall@2=0.734332  recall@5=0.922972  recall@10=0.962796  recall@20=0.986002
precision@1=0.646263  precision@2=0.468951  precision@5=0.251160  precision@10=0.133143  precision@20=0.068577
ndcg@1=0.646263  ndcg@2=0.712979  ndcg@5=0.797188  ndcg@10=0.812348  ndcg@20=0.818997
hit_rate@1=0.646263  hit_rate@2=0.820876  hit_rate@5=0.953850  hit_rate@10=0.977207  hit_rate@20=0.992832
map@1=0.646263  map@2=0.680513  map@5=0.740929  map@10=0.750155  map@20=0.752654
mrr@1=0.646263  mrr@2=0.733570  mrr@5=0.772427  mrr@10=0.775714  mrr@20=0.776848
f1@1=0.567890  f1@2=0.550801  f1@5=0.380668  f1@10=0.227709  f1@20=0.126021

Epoch 86/100: 100%|██████████| 820/820 [00:22<00:00, 37.20it/s, bpr=0.0307, c=2.62, loss=0.135]

[VAL]
recall@1=0.541763  recall@2=0.739588  recall@5=0.918086  recall@10=0.958899  recall@20=0.985266
precision@1=0.652581  precision@2=0.471411  precision@5=0.249516  precision@10=0.132500  precision@20=0.068613
ndcg@1=0.652581  ndcg@2=0.718391  ndcg@5=0.797422  ndcg@10=0.813052  ndcg@20=0.820738
hit_rate@1=0.652581  hit_rate@2=0.825726  hit_rate@5=0.950081  hit_rate@10=0.975403  hit_rate@20=0.992500
map@1=0.652581  map@2=0.686149  map@5=0.742662  map@10=0.752118  map@20=0.755098
mrr@1=0.652581  mrr@2=0.739153  mrr@5=0.775356  mrr@10=0.778960  mrr@20=0.780212
f1@1=0.574521  f1@2=0.554304  f1@5=0.378191  f1@10=0.226561  f1@20=0.126040

[TEST]
recall@1=0.540246  recall@2=0.738648  recall@5=0.918687  recall@10=0.960281  recall@20=0.985653
precision@1=0.650612  precision@2=0.471770  precision@5=0.249968  precision@10=0.132668  precision@20=0.068601
ndcg@1=0.650612  ndcg@2=0.717778  ndcg@5=0.797694  ndcg@10=0.813411  ndcg@20=0.820776
hit_rate@1=0.650612  hit_rate@2=0.823937  hit_rate@5=0.949823  hit_rate@10=0.975757  hit_rate@20=0.992188
map@1=0.650612  map@2=0.685929  map@5=0.743154  map@10=0.752535  map@20=0.755386
mrr@1=0.650612  mrr@2=0.737274  mrr@5=0.774156  mrr@10=0.777807  mrr@20=0.779008
f1@1=0.572834  f1@2=0.554077  f1@5=0.378865  f1@10=0.226929  f1@20=0.126046

Epoch 87/100: 100%|██████████| 820/820 [00:21<00:00, 37.40it/s, bpr=0.0455, c=2.55, loss=0.148]

[VAL]
recall@1=0.537586  recall@2=0.738976  recall@5=0.917436  recall@10=0.959105  recall@20=0.985187
precision@1=0.648065  precision@2=0.471613  precision@5=0.249210  precision@10=0.132556  precision@20=0.068657
ndcg@1=0.648065  ndcg@2=0.716720  ndcg@5=0.795316  ndcg@10=0.811309  ndcg@20=0.818955
hit_rate@1=0.648065  hit_rate@2=0.825484  hit_rate@5=0.950000  hit_rate@10=0.975484  hit_rate@20=0.992097
map@1=0.648065  map@2=0.684073  map@5=0.740053  map@10=0.749801  map@20=0.752784
mrr@1=0.648065  mrr@2=0.736774  mrr@5=0.772876  mrr@10=0.776451  mrr@20=0.777683
f1@1=0.570227  f1@2=0.554191  f1@5=0.377790  f1@10=0.226644  f1@20=0.126097

[TEST]
recall@1=0.543295  recall@2=0.737131  recall@5=0.918851  recall@10=0.960566  recall@20=0.985666
precision@1=0.655122  precision@2=0.471247  precision@5=0.250064  precision@10=0.132732  precision@20=0.068585
ndcg@1=0.655122  ndcg@2=0.718155  ndcg@5=0.798698  ndcg@10=0.814520  ndcg@20=0.821772
hit_rate@1=0.655122  hit_rate@2=0.822729  hit_rate@5=0.950064  hit_rate@10=0.975596  hit_rate@20=0.992349
map@1=0.655122  map@2=0.686775  map@5=0.744426  map@10=0.753948  map@20=0.756711
mrr@1=0.655122  mrr@2=0.738926  mrr@5=0.775987  mrr@10=0.779644  mrr@20=0.780870
f1@1=0.576326  f1@2=0.553244  f1@5=0.378976  f1@10=0.227062  f1@20=0.126018

Epoch 88/100: 100%|██████████| 820/820 [00:22<00:00, 37.13it/s, bpr=0.0384, c=2.66, loss=0.145]

[VAL]
recall@1=0.539490  recall@2=0.739235  recall@5=0.920473  recall@10=0.959825  recall@20=0.984647
precision@1=0.651129  precision@2=0.471250  precision@5=0.250177  precision@10=0.132669  precision@20=0.068565
ndcg@1=0.651129  ndcg@2=0.717551  ndcg@5=0.797704  ndcg@10=0.812865  ndcg@20=0.820086
hit_rate@1=0.651129  hit_rate@2=0.825323  hit_rate@5=0.952339  hit_rate@10=0.975806  hit_rate@20=0.992177
map@1=0.651129  map@2=0.685020  map@5=0.742202  map@10=0.751515  map@20=0.754293
mrr@1=0.651129  mrr@2=0.738226  mrr@5=0.775060  mrr@10=0.778410  mrr@20=0.779614
f1@1=0.572507  f1@2=0.553998  f1@5=0.379209  f1@10=0.226842  f1@20=0.125938

[TEST]
recall@1=0.537187  recall@2=0.737121  recall@5=0.921091  recall@10=0.961088  recall@20=0.985535
precision@1=0.646988  precision@2=0.470764  precision@5=0.250596  precision@10=0.132788  precision@20=0.068573
ndcg@1=0.646988  ndcg@2=0.715454  ndcg@5=0.797351  ndcg@10=0.812587  ndcg@20=0.819663
hit_rate@1=0.646988  hit_rate@2=0.823856  hit_rate@5=0.952481  hit_rate@10=0.976240  hit_rate@20=0.992268
map@1=0.646988  map@2=0.683010  map@5=0.741776  map@10=0.751068  map@20=0.753789
mrr@1=0.646988  mrr@2=0.735422  mrr@5=0.772985  mrr@10=0.776365  mrr@20=0.777542
f1@1=0.569616  f1@2=0.552948  f1@5=0.379822  f1@10=0.227157  f1@20=0.125998

Epoch 89/100: 100%|██████████| 820/820 [00:22<00:00, 36.78it/s, bpr=0.0232, c=2.67, loss=0.13]

[VAL]
recall@1=0.544535  recall@2=0.742667  recall@5=0.920715  recall@10=0.960809  recall@20=0.984757
precision@1=0.655000  precision@2=0.474798  precision@5=0.250097  precision@10=0.132766  precision@20=0.068585
ndcg@1=0.655000  ndcg@2=0.721923  ndcg@5=0.800470  ndcg@10=0.815934  ndcg@20=0.822949
hit_rate@1=0.655000  hit_rate@2=0.827581  hit_rate@5=0.952823  hit_rate@10=0.976935  hit_rate@20=0.992016
map@1=0.655000  map@2=0.690343  map@5=0.746279  map@10=0.755771  map@20=0.758535
mrr@1=0.655000  mrr@2=0.741290  mrr@5=0.777769  mrr@10=0.781193  mrr@20=0.782289
f1@1=0.577246  f1@2=0.557540  f1@5=0.379176  f1@10=0.227043  f1@20=0.125981

[TEST]
recall@1=0.546688  recall@2=0.740559  recall@5=0.922005  recall@10=0.960936  recall@20=0.985956
precision@1=0.658988  precision@2=0.474307  precision@5=0.250902  precision@10=0.132772  precision@20=0.068605
ndcg@1=0.658988  ndcg@2=0.722118  ndcg@5=0.802393  ndcg@10=0.817192  ndcg@20=0.824395
hit_rate@1=0.658988  hit_rate@2=0.826595  hit_rate@5=0.953206  hit_rate@10=0.975838  hit_rate@20=0.992349
map@1=0.658988  map@2=0.690883  map@5=0.748357  map@10=0.757363  map@20=0.760109
mrr@1=0.658988  mrr@2=0.742792  mrr@5=0.779804  mrr@10=0.783011  mrr@20=0.784210
f1@1=0.579852  f1@2=0.556324  f1@5=0.380293  f1@10=0.227146  f1@20=0.126063

Epoch 90/100: 100%|██████████| 820/820 [00:22<00:00, 36.90it/s, bpr=0.0535, c=2.59, loss=0.157]

[VAL]
recall@1=0.537359  recall@2=0.736725  recall@5=0.920771  recall@10=0.961674  recall@20=0.985441
precision@1=0.646774  precision@2=0.471210  precision@5=0.250355  precision@10=0.132831  precision@20=0.068649
ndcg@1=0.646774  ndcg@2=0.715260  ndcg@5=0.796601  ndcg@10=0.812229  ndcg@20=0.819237
hit_rate@1=0.646774  hit_rate@2=0.821774  hit_rate@5=0.952419  hit_rate@10=0.977500  hit_rate@20=0.992419
map@1=0.646774  map@2=0.683448  map@5=0.741220  map@10=0.750707  map@20=0.753472
mrr@1=0.646774  mrr@2=0.734274  mrr@5=0.772128  mrr@10=0.775690  mrr@20=0.776787
f1@1=0.569706  f1@2=0.553173  f1@5=0.379439  f1@10=0.227169  f1@20=0.126093

[TEST]
recall@1=0.544526  recall@2=0.736731  recall@5=0.923088  recall@10=0.962266  recall@20=0.986128
precision@1=0.657055  precision@2=0.472012  precision@5=0.251256  precision@10=0.132949  precision@20=0.068593
ndcg@1=0.657055  ndcg@2=0.718839  ndcg@5=0.801316  ndcg@10=0.816226  ndcg@20=0.823115
hit_rate@1=0.657055  hit_rate@2=0.822084  hit_rate@5=0.953930  hit_rate@10=0.976885  hit_rate@20=0.992832
map@1=0.657055  map@2=0.687923  map@5=0.746525  map@10=0.755629  map@20=0.758255
mrr@1=0.657055  mrr@2=0.739570  mrr@5=0.778114  mrr@10=0.781392  mrr@20=0.782557
f1@1=0.577710  f1@2=0.553509  f1@5=0.380778  f1@10=0.227438  f1@20=0.126046

Epoch 91/100: 100%|██████████| 820/820 [00:22<00:00, 36.79it/s, bpr=0.0757, c=2.69, loss=0.183]

[VAL]
recall@1=0.543428  recall@2=0.743350  recall@5=0.917946  recall@10=0.959432  recall@20=0.984898
precision@1=0.653871  precision@2=0.475645  precision@5=0.249823  precision@10=0.132613  precision@20=0.068589
ndcg@1=0.653871  ndcg@2=0.722201  ndcg@5=0.799235  ndcg@10=0.814965  ndcg@20=0.822404
hit_rate@1=0.653871  hit_rate@2=0.829758  hit_rate@5=0.949919  hit_rate@10=0.975403  hit_rate@20=0.992419
map@1=0.653871  map@2=0.690121  map@5=0.745499  map@10=0.754924  map@20=0.757801
mrr@1=0.653871  mrr@2=0.741815  mrr@5=0.776892  mrr@10=0.780508  mrr@20=0.781767
f1@1=0.576143  f1@2=0.558241  f1@5=0.378481  f1@10=0.226736  f1@20=0.125980

[TEST]
recall@1=0.549277  recall@2=0.744232  recall@5=0.919863  recall@10=0.959676  recall@20=0.985333
precision@1=0.663096  precision@2=0.476885  precision@5=0.250467  precision@10=0.132627  precision@20=0.068561
ndcg@1=0.663096  ndcg@2=0.725827  ndcg@5=0.803191  ndcg@10=0.818236  ndcg@20=0.825659
hit_rate@1=0.663096  hit_rate@2=0.830300  hit_rate@5=0.951111  hit_rate@10=0.975113  hit_rate@20=0.992268
map@1=0.663096  map@2=0.694507  map@5=0.750017  map@10=0.759056  map@20=0.761921
mrr@1=0.663096  mrr@2=0.746698  mrr@5=0.782096  mrr@10=0.785445  mrr@20=0.786707
f1@1=0.582904  f1@2=0.559266  f1@5=0.379555  f1@10=0.226883  f1@20=0.125984

Epoch 92/100: 100%|██████████| 820/820 [00:22<00:00, 37.04it/s, bpr=0.0219, c=2.65, loss=0.128]

[VAL]
recall@1=0.546125  recall@2=0.744379  recall@5=0.918706  recall@10=0.960235  recall@20=0.985196
precision@1=0.657177  precision@2=0.474839  precision@5=0.249742  precision@10=0.132726  precision@20=0.068597
ndcg@1=0.657177  ndcg@2=0.723520  ndcg@5=0.800434  ndcg@10=0.816360  ndcg@20=0.823619
hit_rate@1=0.657177  hit_rate@2=0.830161  hit_rate@5=0.950726  hit_rate@10=0.976129  hit_rate@20=0.992419
map@1=0.657177  map@2=0.691532  map@5=0.746634  map@10=0.756334  map@20=0.759137
mrr@1=0.657177  mrr@2=0.743669  mrr@5=0.778790  mrr@10=0.782417  mrr@20=0.783610
f1@1=0.578940  f1@2=0.558080  f1@5=0.378485  f1@10=0.226937  f1@20=0.126005

[TEST]
recall@1=0.543114  recall@2=0.743090  recall@5=0.920424  recall@10=0.961996  recall@20=0.985746
precision@1=0.654720  precision@2=0.475072  precision@5=0.250548  precision@10=0.132885  precision@20=0.068533
ndcg@1=0.654720  ndcg@2=0.722062  ndcg@5=0.800543  ndcg@10=0.816238  ndcg@20=0.823090
hit_rate@1=0.654720  hit_rate@2=0.828125  hit_rate@5=0.951273  hit_rate@10=0.976965  hit_rate@20=0.992590
map@1=0.654720  map@2=0.690198  map@5=0.746486  map@10=0.755835  map@20=0.758455
mrr@1=0.654720  mrr@2=0.741422  mrr@5=0.777457  mrr@10=0.781082  mrr@20=0.782217
f1@1=0.576122  f1@2=0.557760  f1@5=0.379754  f1@10=0.227340  f1@20=0.125960

Epoch 93/100: 100%|██████████| 820/820 [00:21<00:00, 37.36it/s, bpr=0.0552, c=2.58, loss=0.158]

[VAL]
recall@1=0.543253  recall@2=0.735624  recall@5=0.916787  recall@10=0.958923  recall@20=0.985721
precision@1=0.655484  precision@2=0.470403  precision@5=0.249226  precision@10=0.132452  precision@20=0.068649
ndcg@1=0.655484  ndcg@2=0.717083  ndcg@5=0.796928  ndcg@10=0.812935  ndcg@20=0.820766
hit_rate@1=0.655484  hit_rate@2=0.821048  hit_rate@5=0.949435  hit_rate@10=0.975000  hit_rate@20=0.993065
map@1=0.655484  map@2=0.685847  map@5=0.742499  map@10=0.752118  map@20=0.755127
mrr@1=0.655484  mrr@2=0.738266  mrr@5=0.775591  mrr@10=0.779225  mrr@20=0.780565
f1@1=0.576453  f1@2=0.552157  f1@5=0.377698  f1@10=0.226519  f1@20=0.126091

[TEST]
recall@1=0.540779  recall@2=0.733612  recall@5=0.917871  recall@10=0.961007  recall@20=0.984774
precision@1=0.651095  precision@2=0.470119  precision@5=0.249662  precision@10=0.132813  precision@20=0.068496
ndcg@1=0.651095  ndcg@2=0.715126  ndcg@5=0.796513  ndcg@10=0.812865  ndcg@20=0.819718
hit_rate@1=0.651095  hit_rate@2=0.818541  hit_rate@5=0.949581  hit_rate@10=0.975838  hit_rate@20=0.991785
map@1=0.651095  map@2=0.684278  map@5=0.742033  map@10=0.751832  map@20=0.754455
mrr@1=0.651095  mrr@2=0.734818  mrr@5=0.772925  mrr@10=0.776622  mrr@20=0.777779
f1@1=0.573362  f1@2=0.551246  f1@5=0.378483  f1@10=0.227193  f1@20=0.125873

Epoch 94/100: 100%|██████████| 820/820 [00:21<00:00, 37.43it/s, bpr=0.0445, c=2.63, loss=0.15]

[VAL]
recall@1=0.536909  recall@2=0.738022  recall@5=0.919689  recall@10=0.959540  recall@20=0.986009
precision@1=0.647581  precision@2=0.471532  precision@5=0.250032  precision@10=0.132597  precision@20=0.068694
ndcg@1=0.647581  ndcg@2=0.716021  ndcg@5=0.796399  ndcg@10=0.811631  ndcg@20=0.819343
hit_rate@1=0.647581  hit_rate@2=0.824516  hit_rate@5=0.951694  hit_rate@10=0.975806  hit_rate@20=0.993065
map@1=0.647581  map@2=0.683448  map@5=0.740791  map@10=0.750083  map@20=0.753064
mrr@1=0.647581  mrr@2=0.736048  mrr@5=0.773222  mrr@10=0.776592  mrr@20=0.777854
f1@1=0.569658  f1@2=0.553730  f1@5=0.378948  f1@10=0.226726  f1@20=0.126169

[TEST]
recall@1=0.543394  recall@2=0.737501  recall@5=0.920760  recall@10=0.960556  recall@20=0.986166
precision@1=0.655364  precision@2=0.471730  precision@5=0.250725  precision@10=0.132829  precision@20=0.068617
ndcg@1=0.655364  ndcg@2=0.718615  ndcg@5=0.799905  ndcg@10=0.815014  ndcg@20=0.822336
hit_rate@1=0.655364  hit_rate@2=0.823937  hit_rate@5=0.952159  hit_rate@10=0.975354  hit_rate@20=0.992751
map@1=0.655364  map@2=0.687057  map@5=0.745182  map@10=0.754388  map@20=0.757125
mrr@1=0.655364  mrr@2=0.739650  mrr@5=0.777125  mrr@10=0.780396  mrr@20=0.781662
f1@1=0.576472  f1@2=0.553637  f1@5=0.379891  f1@10=0.227171  f1@20=0.126090

Epoch 95/100: 100%|██████████| 820/820 [00:22<00:00, 37.06it/s, bpr=0.0278, c=2.64, loss=0.133]

[VAL]
recall@1=0.537135  recall@2=0.740378  recall@5=0.920236  recall@10=0.959953  recall@20=0.984998
precision@1=0.647419  precision@2=0.472581  precision@5=0.249919  precision@10=0.132629  precision@20=0.068613
ndcg@1=0.647419  ndcg@2=0.717541  ndcg@5=0.796952  ndcg@10=0.812260  ndcg@20=0.819601
hit_rate@1=0.647419  hit_rate@2=0.826452  hit_rate@5=0.951694  hit_rate@10=0.976048  hit_rate@20=0.992016
map@1=0.647419  map@2=0.684819  map@5=0.741544  map@10=0.750890  map@20=0.753768
mrr@1=0.647419  mrr@2=0.736935  mrr@5=0.773406  mrr@10=0.776834  mrr@20=0.778001
f1@1=0.569721  f1@2=0.555233  f1@5=0.378929  f1@10=0.226807  f1@20=0.126038

[TEST]
recall@1=0.542185  recall@2=0.738252  recall@5=0.922366  recall@10=0.961575  recall@20=0.985523
precision@1=0.653431  precision@2=0.471126  precision@5=0.251047  precision@10=0.132845  precision@20=0.068573
ndcg@1=0.653431  ndcg@2=0.718047  ndcg@5=0.800194  ndcg@10=0.815054  ndcg@20=0.821952
hit_rate@1=0.653431  hit_rate@2=0.824017  hit_rate@5=0.952883  hit_rate@10=0.976643  hit_rate@20=0.992429
map@1=0.653431  map@2=0.686211  map@5=0.745200  map@10=0.754185  map@20=0.756808
mrr@1=0.653431  mrr@2=0.738724  mrr@5=0.776420  mrr@10=0.779786  mrr@20=0.780917
f1@1=0.575058  f1@2=0.553593  f1@5=0.380453  f1@10=0.227236  f1@20=0.125988

Epoch 96/100: 100%|██████████| 820/820 [00:22<00:00, 36.62it/s, bpr=0.0258, c=2.68, loss=0.133]

[VAL]
recall@1=0.534860  recall@2=0.736486  recall@5=0.918046  recall@10=0.957918  recall@20=0.984551
precision@1=0.645242  precision@2=0.470403  precision@5=0.249532  precision@10=0.132347  precision@20=0.068593
ndcg@1=0.645242  ndcg@2=0.714139  ndcg@5=0.794403  ndcg@10=0.809776  ndcg@20=0.817605
hit_rate@1=0.645242  hit_rate@2=0.824032  hit_rate@5=0.950645  hit_rate@10=0.974516  hit_rate@20=0.991935
map@1=0.645242  map@2=0.681190  map@5=0.738598  map@10=0.748061  map@20=0.751115
mrr@1=0.645242  mrr@2=0.734677  mrr@5=0.771401  mrr@10=0.774860  mrr@20=0.776161
f1@1=0.567529  f1@2=0.552525  f1@5=0.378206  f1@10=0.226328  f1@20=0.125982

[TEST]
recall@1=0.541316  recall@2=0.735633  recall@5=0.918797  recall@10=0.960044  recall@20=0.985672
precision@1=0.654075  precision@2=0.471247  precision@5=0.249968  precision@10=0.132627  precision@20=0.068573
ndcg@1=0.654075  ndcg@2=0.716939  ndcg@5=0.797628  ndcg@10=0.813232  ndcg@20=0.820634
hit_rate@1=0.654075  hit_rate@2=0.822165  hit_rate@5=0.950145  hit_rate@10=0.975032  hit_rate@20=0.992510
map@1=0.654075  map@2=0.685366  map@5=0.742852  map@10=0.752220  map@20=0.755049
mrr@1=0.654075  mrr@2=0.738080  mrr@5=0.775236  mrr@10=0.778714  mrr@20=0.779978
f1@1=0.574616  f1@2=0.552610  f1@5=0.378918  f1@10=0.226914  f1@20=0.126008

Epoch 97/100: 100%|██████████| 820/820 [00:22<00:00, 36.82it/s, bpr=0.0291, c=2.68, loss=0.136]

[VAL]
recall@1=0.539688  recall@2=0.742748  recall@5=0.919877  recall@10=0.960477  recall@20=0.985636
precision@1=0.650161  precision@2=0.473629  precision@5=0.249968  precision@10=0.132581  precision@20=0.068641
ndcg@1=0.650161  ndcg@2=0.719761  ndcg@5=0.798078  ndcg@10=0.813553  ndcg@20=0.820960
hit_rate@1=0.650161  hit_rate@2=0.828790  hit_rate@5=0.952016  hit_rate@10=0.977177  hit_rate@20=0.993065
map@1=0.650161  map@2=0.686976  map@5=0.743036  map@10=0.752396  map@20=0.755331
mrr@1=0.650161  mrr@2=0.739476  mrr@5=0.775211  mrr@10=0.778766  mrr@20=0.779921
f1@1=0.572410  f1@2=0.556806  f1@5=0.378861  f1@10=0.226765  f1@20=0.126070

[TEST]
recall@1=0.543207  recall@2=0.741306  recall@5=0.921410  recall@10=0.961277  recall@20=0.985642
precision@1=0.655606  precision@2=0.473784  precision@5=0.250596  precision@10=0.132837  precision@20=0.068541
ndcg@1=0.655606  ndcg@2=0.721017  ndcg@5=0.800463  ndcg@10=0.815687  ndcg@20=0.822746
hit_rate@1=0.655606  hit_rate@2=0.827400  hit_rate@5=0.952642  hit_rate@10=0.975918  hit_rate@20=0.992429
map@1=0.655606  map@2=0.688990  map@5=0.745725  map@10=0.755018  map@20=0.757736
mrr@1=0.655606  mrr@2=0.741503  mrr@5=0.777865  mrr@10=0.781194  mrr@20=0.782412
f1@1=0.576475  f1@2=0.556248  f1@5=0.379918  f1@10=0.227241  f1@20=0.125969

Epoch 98/100: 100%|██████████| 820/820 [00:22<00:00, 37.04it/s, bpr=0.023, c=2.74, loss=0.132]

[VAL]
recall@1=0.540717  recall@2=0.734460  recall@5=0.916650  recall@10=0.959031  recall@20=0.984684
precision@1=0.652258  precision@2=0.469435  precision@5=0.248952  precision@10=0.132532  precision@20=0.068597
ndcg@1=0.652258  ndcg@2=0.715072  ndcg@5=0.795425  ndcg@10=0.811670  ndcg@20=0.819192
hit_rate@1=0.652258  hit_rate@2=0.820323  hit_rate@5=0.949758  hit_rate@10=0.975645  hit_rate@20=0.991935
map@1=0.652258  map@2=0.683508  map@5=0.740401  map@10=0.750261  map@20=0.753231
mrr@1=0.652258  mrr@2=0.736290  mrr@5=0.773808  mrr@10=0.777460  mrr@20=0.778668
f1@1=0.573699  f1@2=0.551250  f1@5=0.377439  f1@10=0.226611  f1@20=0.125984

[TEST]
recall@1=0.538688  recall@2=0.731817  recall@5=0.917212  recall@10=0.959333  recall@20=0.985870
precision@1=0.649887  precision@2=0.468226  precision@5=0.249420  precision@10=0.132523  precision@20=0.068549
ndcg@1=0.649887  ndcg@2=0.712805  ndcg@5=0.795207  ndcg@10=0.811260  ndcg@20=0.818905
hit_rate@1=0.649887  hit_rate@2=0.817010  hit_rate@5=0.949823  hit_rate@10=0.974710  hit_rate@20=0.992671
map@1=0.649887  map@2=0.681560  map@5=0.740116  map@10=0.749809  map@20=0.752736
mrr@1=0.649887  mrr@2=0.733449  mrr@5=0.772366  mrr@10=0.775944  mrr@20=0.777254
f1@1=0.571585  f1@2=0.549519  f1@5=0.378173  f1@10=0.226737  f1@20=0.125979

Epoch 99/100: 100%|██████████| 820/820 [00:22<00:00, 37.12it/s, bpr=0.0363, c=2.62, loss=0.141]

[VAL]
recall@1=0.539166  recall@2=0.739532  recall@5=0.921223  recall@10=0.960055  recall@20=0.984540
precision@1=0.649758  precision@2=0.472218  precision@5=0.250177  precision@10=0.132677  precision@20=0.068621
ndcg@1=0.649758  ndcg@2=0.717603  ndcg@5=0.797977  ndcg@10=0.812996  ndcg@20=0.820222
hit_rate@1=0.649758  hit_rate@2=0.824919  hit_rate@5=0.952661  hit_rate@10=0.976048  hit_rate@20=0.991694
map@1=0.649758  map@2=0.685383  map@5=0.742639  map@10=0.751884  map@20=0.754716
mrr@1=0.649758  mrr@2=0.737339  mrr@5=0.774507  mrr@10=0.777830  mrr@20=0.778997
f1@1=0.571910  f1@2=0.554825  f1@5=0.379322  f1@10=0.226851  f1@20=0.126029

[TEST]
recall@1=0.541551  recall@2=0.733449  recall@5=0.921653  recall@10=0.961787  recall@20=0.985481
precision@1=0.652626  precision@2=0.469354  precision@5=0.250789  precision@10=0.132780  precision@20=0.068529
ndcg@1=0.652626  ndcg@2=0.715088  ndcg@5=0.798805  ndcg@10=0.813944  ndcg@20=0.820824
hit_rate@1=0.652626  hit_rate@2=0.818702  hit_rate@5=0.952642  hit_rate@10=0.976885  hit_rate@20=0.992590
map@1=0.652626  map@2=0.684077  map@5=0.743665  map@10=0.752749  map@20=0.755419
mrr@1=0.652626  mrr@2=0.735664  mrr@5=0.774929  mrr@10=0.778350  mrr@20=0.779476
f1@1=0.574376  f1@2=0.550708  f1@5=0.380126  f1@10=0.227192  f1@20=0.125925

Epoch 100/100: 100%|██████████| 820/820 [00:21<00:00, 37.33it/s, bpr=0.042, c=2.55, loss=0.144]

[VAL]
recall@1=0.539684  recall@2=0.740385  recall@5=0.919931  recall@10=0.959561  recall@20=0.984956
precision@1=0.650323  precision@2=0.471855  precision@5=0.249935  precision@10=0.132589  precision@20=0.068569
ndcg@1=0.650323  ndcg@2=0.718179  ndcg@5=0.797883  ndcg@10=0.813130  ndcg@20=0.820510
hit_rate@1=0.650323  hit_rate@2=0.827500  hit_rate@5=0.951694  hit_rate@10=0.975806  hit_rate@20=0.992581
map@1=0.650323  map@2=0.685363  map@5=0.742670  map@10=0.751992  map@20=0.754831
mrr@1=0.650323  mrr@2=0.738911  mrr@5=0.775253  mrr@10=0.778686  mrr@20=0.779900
f1@1=0.572339  f1@2=0.554872  f1@5=0.378913  f1@10=0.226713  f1@20=0.125960

[TEST]
recall@1=0.542855  recall@2=0.739221  recall@5=0.921461  recall@10=0.960382  recall@20=0.986032
precision@1=0.654720  precision@2=0.472737  precision@5=0.250822  precision@10=0.132700  precision@20=0.068593
ndcg@1=0.654720  ndcg@2=0.719431  ndcg@5=0.800238  ndcg@10=0.814986  ndcg@20=0.822336
hit_rate@1=0.654720  hit_rate@2=0.824259  hit_rate@5=0.952642  hit_rate@10=0.975596  hit_rate@20=0.992590
map@1=0.654720  map@2=0.687943  map@5=0.745606  map@10=0.754567  map@20=0.757349
mrr@1=0.654720  mrr@2=0.739489  mrr@5=0.776956  mrr@10=0.780182  mrr@20=0.781387
f1@1=0.575916  f1@2=0.554922  f1@5=0.380108  f1@10=0.226978  f1@20=0.126043

,epoch,val_recall@1,val_recall@2,val_recall@5,val_recall@10,val_recall@20,val_precision@1,val_precision@2,val_precision@5,val_precision@10,...,test_mrr@1,test_mrr@2,test_mrr@5,test_mrr@10,test_mrr@20,test_f1@1,test_f1@2,test_f1@5,test_f1@10,test_f1@20
0,1,0.393726,0.559011,0.805930,0.939555,0.976257,0.496855,0.371048,0.219032,0.129629,...,0.491382,0.569306,0.622019,0.636170,0.638153,0.418937,0.429004,0.332936,0.221910,0.124761
1,2,0.480969,0.653415,0.858813,0.950231,0.979047,0.591129,0.426290,0.234387,0.131129,...,0.587065,0.665230,0.706151,0.715707,0.717190,0.509439,0.497445,0.355261,0.224646,0.125245
2,3,0.536070,0.717269,0.888246,0.953289,0.980303,0.647984,0.461613,0.242016,0.131613,...,0.641994,0.722616,0.756308,0.763048,0.764254,0.562269,0.538752,0.367315,0.225716,0.125595
3,4,0.555337,0.741309,0.905640,0.957361,0.982297,0.667258,0.474435,0.246548,0.132177,...,0.654317,0.740174,0.773152,0.778091,0.779136,0.576136,0.555459,0.374062,0.226689,0.125730
4,5,0.556700,0.747001,0.914106,0.958971,0.981927,0.668306,0.476613,0.248726,0.132403,...,0.654317,0.742469,0.776278,0.780551,0.781588,0.576666,0.559284,0.377345,0.226818,0.125663
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,0.534860,0.736486,0.918046,0.957918,0.984551,0.645242,0.470403,0.249532,0.132347,...,0.654075,0.738080,0.775236,0.778714,0.779978,0.574616,0.552610,0.378918,0.226914,0.126008
96,97,0.539688,0.742748,0.919877,0.960477,0.985636,0.650161,0.473629,0.249968,0.132581,...,0.655606,0.741503,0.777865,0.781194,0.782412,0.576475,0.556248,0.379918,0.227241,0.125969
97,98,0.540717,0.734460,0.916650,0.959031,0.984684,0.652258,0.469435,0.248952,0.132532,...,0.649887,0.733449,0.772366,0.775944,0.777254,0.571585,0.549519,0.378173,0.226737,0.125979
98,99,0.539166,0.739532,0.921223,0.960055,0.984540,0.649758,0.472218,0.250177,0.132677,...,0.652626,0.735664,0.774929,0.778350,0.779476,0.574376,0.550708,0.380126,0.227192,0.125925
99,100,0.539684,0.740385,0.919931,0.959561,0.984956,0.650323,0.471855,0.249935,0.132589,...,0.654720,0.739489,0.776956,0.780182,0.781387,0.575916,0.554922,0.380108,0.226978,0.126043

## Run user-aware attention experiment

In [12]:
user_attention_conf = make_experiment_conf(
    base_conf,
    attention_type="user",
    fusion_type="none",
    epochs=100,
)

user_attention_output = train_notebook(
    user_attention_conf,
    experiment_name="step1b_user_attention"
)

user_attention_output["history_df"]

>>>>>>>>>>B-I statistics>>>>>>>>>>
Average interactions 5.757723808288574
Non-zero rows 0.9967479674796748
Non-zero columns 1.0
Matrix density 0.002042470229597649
>>>>>>>>>>U-I statistics>>>>>>>>>>
Average interactions 30.47064208984375
Non-zero rows 1.0
Non-zero columns 0.5001773678609436
Matrix density 0.010809025126048253
>>>>>>>>>>U-B statistics in train>>>>>>>>>>
Average interactions 1.7729297876358032
Non-zero rows 0.8142673955591551
Non-zero columns 0.3382113821138211
Matrix density 0.0028828125900210205
>>>>>>>>>>U-B statistics in tune>>>>>>>>>>
Average interactions 0.5909765958786011
Non-zero rows 0.41843828035364783
Non-zero columns 0.27479674796747966
Matrix density 0.0009609375300070068
>>>>>>>>>>U-B statistics in test>>>>>>>>>>
Average interactions 0.5909765958786011
Non-zero rows 0.4189782007153945
Non-zero columns 0.2780487804878049
Matrix density 0.0009609375300070068

Epoch 1/100: 100%|██████████| 820/820 [00:13<00:00, 60.96it/s, bpr=0.0983, c=3.35, loss=0.232]

[VAL]
recall@1=0.348762  recall@2=0.499190  recall@5=0.790048  recall@10=0.936783  recall@20=0.978517
precision@1=0.445887  precision@2=0.338145  precision@5=0.216613  precision@10=0.129298  precision@20=0.067992
ndcg@1=0.445887  ndcg@2=0.490003  ndcg@5=0.613449  ndcg@10=0.666876  ndcg@20=0.678915
hit_rate@1=0.445887  hit_rate@2=0.584113  hit_rate@5=0.841210  hit_rate@10=0.958387  hit_rate@20=0.987581
map@1=0.445887  map@2=0.462500  map@5=0.539021  map@10=0.567069  map@20=0.571647
mrr@1=0.445887  mrr@2=0.515000  mrr@5=0.580539  mrr@10=0.598033  mrr@20=0.600241
f1@1=0.377137  f1@2=0.385593  f1@5=0.327362  f1@10=0.221190  f1@20=0.124977

[TEST]
recall@1=0.344554  recall@2=0.496969  recall@5=0.791324  recall@10=0.939084  recall@20=0.979692
precision@1=0.441688  precision@2=0.337307  precision@5=0.217091  precision@10=0.129663  precision@20=0.068082
ndcg@1=0.441688  ndcg@2=0.487095  ndcg@5=0.612088  ndcg@10=0.665560  ndcg@20=0.677223
hit_rate@1=0.441688  hit_rate@2=0.580380  hit_rate@5=0.840770  hit_rate@10=0.959407  hit_rate@20=0.987919
map@1=0.441688  map@2=0.459750  map@5=0.537352  map@10=0.565074  map@20=0.569491
mrr@1=0.441688  mrr@2=0.511034  mrr@5=0.577141  mrr@10=0.594627  mrr@20=0.596754
f1@1=0.372991  f1@2=0.384377  f1@5=0.328272  f1@10=0.221858  f1@20=0.125136

Saved new best checkpoint at epoch 1

Epoch 2/100: 100%|██████████| 820/820 [00:13<00:00, 60.41it/s, bpr=0.0757, c=3.08, loss=0.199]

[VAL]
recall@1=0.442059  recall@2=0.620403  recall@5=0.823707  recall@10=0.941959  recall@20=0.980409
precision@1=0.544597  precision@2=0.404395  precision@5=0.225565  precision@10=0.130202  precision@20=0.068246
ndcg@1=0.544597  ndcg@2=0.603283  ndcg@5=0.692006  ndcg@10=0.735270  ndcg@20=0.746356
hit_rate@1=0.544597  hit_rate@2=0.711129  hit_rate@5=0.871129  hit_rate@10=0.962258  hit_rate@20=0.989194
map@1=0.544597  map@2=0.571492  map@5=0.630821  map@10=0.653988  map@20=0.658186
mrr@1=0.544597  mrr@2=0.627863  mrr@5=0.673132  mrr@10=0.686759  mrr@20=0.688787
f1@1=0.472118  f1@2=0.470018  f1@5=0.341048  f1@10=0.222649  f1@20=0.125372

[TEST]
recall@1=0.441041  recall@2=0.620797  recall@5=0.824275  recall@10=0.942585  recall@20=0.981375
precision@1=0.545506  precision@2=0.404438  precision@5=0.225693  precision@10=0.130292  precision@20=0.068251
ndcg@1=0.545506  ndcg@2=0.602963  ndcg@5=0.692204  ndcg@10=0.735387  ndcg@20=0.746542
hit_rate@1=0.545506  hit_rate@2=0.710535  hit_rate@5=0.870973  hit_rate@10=0.961985  hit_rate@20=0.989288
map@1=0.545506  map@2=0.570997  map@5=0.631000  map@10=0.654045  map@20=0.658280
mrr@1=0.545506  mrr@2=0.628020  mrr@5=0.673207  mrr@10=0.686737  mrr@20=0.688803
f1@1=0.471866  f1@2=0.470422  f1@5=0.341374  f1@10=0.222837  f1@20=0.125421

Saved new best checkpoint at epoch 2

Epoch 3/100: 100%|██████████| 820/820 [00:13<00:00, 59.97it/s, bpr=0.0525, c=2.93, loss=0.17]

[VAL]
recall@1=0.439178  recall@2=0.665954  recall@5=0.864406  recall@10=0.946239  recall@20=0.981651
precision@1=0.537581  precision@2=0.427339  precision@5=0.234645  precision@10=0.130790  precision@20=0.068351
ndcg@1=0.537581  ndcg@2=0.630352  ndcg@5=0.717613  ndcg@10=0.747835  ndcg@20=0.758087
hit_rate@1=0.537581  hit_rate@2=0.756855  hit_rate@5=0.909194  hit_rate@10=0.965726  hit_rate@20=0.989919
map@1=0.537581  map@2=0.592419  map@5=0.651856  map@10=0.668815  map@20=0.672748
mrr@1=0.537581  mrr@2=0.647218  mrr@5=0.690235  mrr@10=0.698180  mrr@20=0.699997
f1@1=0.468120  f1@2=0.500608  f1@5=0.355687  f1@10=0.223624  f1@20=0.125566

[TEST]
recall@1=0.441835  recall@2=0.666140  recall@5=0.862662  recall@10=0.948200  recall@20=0.982604
precision@1=0.544378  precision@2=0.428922  precision@5=0.234133  precision@10=0.131113  precision@20=0.068363
ndcg@1=0.544378  ndcg@2=0.632145  ndcg@5=0.718677  ndcg@10=0.750145  ndcg@20=0.760010
hit_rate@1=0.544378  hit_rate@2=0.756041  hit_rate@5=0.905928  hit_rate@10=0.966334  hit_rate@20=0.989932
map@1=0.544378  map@2=0.594797  map@5=0.653930  map@10=0.671370  map@20=0.675124
mrr@1=0.544378  mrr@2=0.650209  mrr@5=0.692767  mrr@10=0.701262  mrr@20=0.703017
f1@1=0.472079  f1@2=0.501842  f1@5=0.355127  f1@10=0.224234  f1@20=0.125615

Saved new best checkpoint at epoch 3

Epoch 4/100: 100%|██████████| 820/820 [00:13<00:00, 59.68it/s, bpr=0.0465, c=2.71, loss=0.155]

[VAL]
recall@1=0.450093  recall@2=0.683103  recall@5=0.869028  recall@10=0.945203  recall@20=0.981151
precision@1=0.549516  precision@2=0.438589  precision@5=0.235919  precision@10=0.130669  precision@20=0.068331
ndcg@1=0.549516  ndcg@2=0.646439  ndcg@5=0.727714  ndcg@10=0.755678  ndcg@20=0.766049
hit_rate@1=0.549516  hit_rate@2=0.773387  hit_rate@5=0.912419  hit_rate@10=0.964677  hit_rate@20=0.989435
map@1=0.549516  map@2=0.608387  map@5=0.664195  map@10=0.679802  map@20=0.683750
mrr@1=0.549516  mrr@2=0.661452  mrr@5=0.701083  mrr@10=0.708261  mrr@20=0.710093
f1@1=0.479274  f1@2=0.513584  f1@5=0.357590  f1@10=0.223416  f1@20=0.125521

[TEST]
recall@1=0.450841  recall@2=0.687947  recall@5=0.867030  recall@10=0.948572  recall@20=0.982721
precision@1=0.552916  precision@2=0.441326  precision@5=0.235261  precision@10=0.131169  precision@20=0.068355
ndcg@1=0.552916  ndcg@2=0.649789  ndcg@5=0.728319  ndcg@10=0.758189  ndcg@20=0.767951
hit_rate@1=0.552916  hit_rate@2=0.776579  hit_rate@5=0.910035  hit_rate@10=0.966334  hit_rate@20=0.989852
map@1=0.552916  map@2=0.611409  map@5=0.665700  map@10=0.682225  map@20=0.685904
mrr@1=0.552916  mrr@2=0.664747  mrr@5=0.702767  mrr@10=0.710489  mrr@20=0.712244
f1@1=0.481024  f1@2=0.517224  f1@5=0.356906  f1@10=0.224333  f1@20=0.125607

Epoch 5/100: 100%|██████████| 820/820 [00:13<00:00, 60.56it/s, bpr=0.0496, c=2.68, loss=0.157]

[VAL]
recall@1=0.464018  recall@2=0.689319  recall@5=0.879969  recall@10=0.944731  recall@20=0.980593
precision@1=0.570000  precision@2=0.443992  precision@5=0.239597  precision@10=0.130661  precision@20=0.068290
ndcg@1=0.570000  ndcg@2=0.657145  ndcg@5=0.740217  ndcg@10=0.764085  ndcg@20=0.774407
hit_rate@1=0.570000  hit_rate@2=0.781210  hit_rate@5=0.920403  hit_rate@10=0.964355  hit_rate@20=0.989274
map@1=0.570000  map@2=0.619778  map@5=0.677144  map@10=0.690650  map@20=0.694558
mrr@1=0.570000  mrr@2=0.675605  mrr@5=0.715210  mrr@10=0.721313  mrr@20=0.723167
f1@1=0.495156  f1@2=0.519068  f1@5=0.362881  f1@10=0.223379  f1@20=0.125444

[TEST]
recall@1=0.466458  recall@2=0.687871  recall@5=0.882185  recall@10=0.946620  recall@20=0.982883
precision@1=0.575387  precision@2=0.443863  precision@5=0.240287  precision@10=0.130888  precision@20=0.068371
ndcg@1=0.575387  ndcg@2=0.657444  ndcg@5=0.742385  ndcg@10=0.766071  ndcg@20=0.776470
hit_rate@1=0.575387  hit_rate@2=0.778351  hit_rate@5=0.920264  hit_rate@10=0.965045  hit_rate@20=0.990255
map@1=0.575387  map@2=0.620812  map@5=0.679587  map@10=0.692798  map@20=0.696751
mrr@1=0.575387  mrr@2=0.676869  mrr@5=0.717151  mrr@10=0.723400  mrr@20=0.725281
f1@1=0.498658  f1@2=0.518668  f1@5=0.364017  f1@10=0.223852  f1@20=0.125636

Epoch 6/100: 100%|██████████| 820/820 [00:13<00:00, 60.89it/s, bpr=0.0365, c=2.79, loss=0.148]

[VAL]
recall@1=0.467074  recall@2=0.687289  recall@5=0.879936  recall@10=0.944256  recall@20=0.981710
precision@1=0.572258  precision@2=0.442500  precision@5=0.239226  precision@10=0.130548  precision@20=0.068302
ndcg@1=0.572258  ndcg@2=0.656594  ndcg@5=0.740561  ndcg@10=0.764371  ndcg@20=0.775069
hit_rate@1=0.572258  hit_rate@2=0.778145  hit_rate@5=0.920726  hit_rate@10=0.963790  hit_rate@20=0.990484
map@1=0.572258  map@2=0.620081  map@5=0.677751  map@10=0.691326  map@20=0.695296
mrr@1=0.572258  mrr@2=0.675202  mrr@5=0.715583  mrr@10=0.721553  mrr@20=0.723513
f1@1=0.498019  f1@2=0.517532  f1@5=0.362539  f1@10=0.223229  f1@20=0.125498

[TEST]
recall@1=0.463213  recall@2=0.685457  recall@5=0.880810  recall@10=0.945990  recall@20=0.983262
precision@1=0.569749  precision@2=0.442655  precision@5=0.239659  precision@10=0.130799  precision@20=0.068384
ndcg@1=0.569749  ndcg@2=0.654597  ndcg@5=0.739994  ndcg@10=0.763961  ndcg@20=0.774588
hit_rate@1=0.569749  hit_rate@2=0.774485  hit_rate@5=0.920264  hit_rate@10=0.964481  hit_rate@20=0.990738
map@1=0.569749  map@2=0.618375  map@5=0.677093  map@10=0.690552  map@20=0.694508
mrr@1=0.569749  mrr@2=0.672117  mrr@5=0.713578  mrr@10=0.719693  mrr@20=0.721641
f1@1=0.494679  f1@2=0.516930  f1@5=0.363161  f1@10=0.223701  f1@20=0.125667

Saved new best checkpoint at epoch 6

Epoch 7/100: 100%|██████████| 820/820 [00:13<00:00, 60.74it/s, bpr=0.0288, c=2.78, loss=0.14]

[VAL]
recall@1=0.463602  recall@2=0.685016  recall@5=0.884983  recall@10=0.948987  recall@20=0.981945
precision@1=0.566613  precision@2=0.440242  precision@5=0.240500  precision@10=0.131226  precision@20=0.068355
ndcg@1=0.566613  ndcg@2=0.653164  ndcg@5=0.740955  ndcg@10=0.764827  ndcg@20=0.774247
hit_rate@1=0.566613  hit_rate@2=0.775242  hit_rate@5=0.925000  hit_rate@10=0.967500  hit_rate@20=0.990403
map@1=0.566613  map@2=0.616512  map@5=0.676848  map@10=0.690625  map@20=0.694152
mrr@1=0.566613  mrr@2=0.670927  mrr@5=0.713435  mrr@10=0.719414  mrr@20=0.721061
f1@1=0.493950  f1@2=0.515318  f1@5=0.364529  f1@10=0.224360  f1@20=0.125578

[TEST]
recall@1=0.466169  recall@2=0.683333  recall@5=0.888784  recall@10=0.951720  recall@20=0.983179
precision@1=0.572165  precision@2=0.440681  precision@5=0.241318  precision@10=0.131604  precision@20=0.068371
ndcg@1=0.572165  ndcg@2=0.653681  ndcg@5=0.744020  ndcg@10=0.767423  ndcg@20=0.776366
hit_rate@1=0.572165  hit_rate@2=0.772068  hit_rate@5=0.927996  hit_rate@10=0.968589  hit_rate@20=0.990738
map@1=0.572165  map@2=0.617993  map@5=0.679879  map@10=0.693358  map@20=0.696686
mrr@1=0.572165  mrr@2=0.672117  mrr@5=0.716312  mrr@10=0.721940  mrr@20=0.723549
f1@1=0.497528  f1@2=0.515116  f1@5=0.365986  f1@10=0.225056  f1@20=0.125639

Epoch 8/100: 100%|██████████| 820/820 [00:13<00:00, 61.36it/s, bpr=0.0312, c=2.71, loss=0.14]

[VAL]
recall@1=0.461118  recall@2=0.680446  recall@5=0.886072  recall@10=0.948593  recall@20=0.983114
precision@1=0.565565  precision@2=0.437823  precision@5=0.240661  precision@10=0.131161  precision@20=0.068444
ndcg@1=0.565565  ndcg@2=0.649508  ndcg@5=0.739989  ndcg@10=0.763380  ndcg@20=0.773257
hit_rate@1=0.565565  hit_rate@2=0.769597  hit_rate@5=0.926129  hit_rate@10=0.966855  hit_rate@20=0.991129
map@1=0.565565  map@2=0.613306  map@5=0.675052  map@10=0.688659  map@20=0.692351
mrr@1=0.565565  mrr@2=0.667581  mrr@5=0.712285  mrr@10=0.718009  mrr@20=0.719774
f1@1=0.491852  f1@2=0.512195  f1@5=0.364865  f1@10=0.224269  f1@20=0.125736

[TEST]
recall@1=0.465839  recall@2=0.675993  recall@5=0.890534  recall@10=0.950822  recall@20=0.984425
precision@1=0.572568  precision@2=0.435929  precision@5=0.241736  precision@10=0.131484  precision@20=0.068452
ndcg@1=0.572568  ndcg@2=0.648691  ndcg@5=0.743746  ndcg@10=0.766231  ndcg@20=0.775770
hit_rate@1=0.572568  hit_rate@2=0.765464  hit_rate@5=0.930010  hit_rate@10=0.967784  hit_rate@20=0.991463
map@1=0.572568  map@2=0.613462  map@5=0.678652  map@10=0.691759  map@20=0.695299
mrr@1=0.572568  mrr@2=0.669016  mrr@5=0.715962  mrr@10=0.721169  mrr@20=0.722899
f1@1=0.497416  f1@2=0.509527  f1@5=0.366624  f1@10=0.224868  f1@20=0.125790

Epoch 9/100: 100%|██████████| 820/820 [00:13<00:00, 59.52it/s, bpr=0.0399, c=2.59, loss=0.143]

[VAL]
recall@1=0.462335  recall@2=0.678749  recall@5=0.886232  recall@10=0.948786  recall@20=0.981264
precision@1=0.567016  precision@2=0.437379  precision@5=0.240855  precision@10=0.131169  precision@20=0.068310
ndcg@1=0.567016  ndcg@2=0.649148  ndcg@5=0.740379  ndcg@10=0.763614  ndcg@20=0.772971
hit_rate@1=0.567016  hit_rate@2=0.769919  hit_rate@5=0.926210  hit_rate@10=0.967500  hit_rate@20=0.989677
map@1=0.567016  map@2=0.612883  map@5=0.675397  map@10=0.688827  map@20=0.692381
mrr@1=0.567016  mrr@2=0.668468  mrr@5=0.713051  mrr@10=0.718752  mrr@20=0.720374
f1@1=0.493159  f1@2=0.511240  f1@5=0.365039  f1@10=0.224262  f1@20=0.125500

[TEST]
recall@1=0.464890  recall@2=0.676945  recall@5=0.889720  recall@10=0.951034  recall@20=0.983866
precision@1=0.571360  precision@2=0.436654  precision@5=0.241318  precision@10=0.131524  precision@20=0.068460
ndcg@1=0.571360  ndcg@2=0.648949  ndcg@5=0.742794  ndcg@10=0.765698  ndcg@20=0.775106
hit_rate@1=0.571360  hit_rate@2=0.764900  hit_rate@5=0.929365  hit_rate@10=0.968186  hit_rate@20=0.991060
map@1=0.571360  map@2=0.613946  map@5=0.677907  map@10=0.691214  map@20=0.694765
mrr@1=0.571360  mrr@2=0.668130  mrr@5=0.714774  mrr@10=0.720085  mrr@20=0.721788
f1@1=0.496357  f1@2=0.510386  f1@5=0.366167  f1@10=0.224942  f1@20=0.125785

Epoch 10/100: 100%|██████████| 820/820 [00:13<00:00, 60.45it/s, bpr=0.0315, c=2.7, loss=0.139]

[VAL]
recall@1=0.463405  recall@2=0.673333  recall@5=0.884974  recall@10=0.945150  recall@20=0.982037
precision@1=0.567903  precision@2=0.433226  precision@5=0.240516  precision@10=0.130677  precision@20=0.068379
ndcg@1=0.567903  ndcg@2=0.645348  ndcg@5=0.738756  ndcg@10=0.761134  ndcg@20=0.771750
hit_rate@1=0.567903  hit_rate@2=0.763387  hit_rate@5=0.925887  hit_rate@10=0.964032  hit_rate@20=0.989758
map@1=0.567903  map@2=0.609879  map@5=0.673596  map@10=0.686641  map@20=0.690635
mrr@1=0.567903  mrr@2=0.665645  mrr@5=0.711704  mrr@10=0.716959  mrr@20=0.718877
f1@1=0.494202  f1@2=0.506882  f1@5=0.364471  f1@10=0.223467  f1@20=0.125630

[TEST]
recall@1=0.463853  recall@2=0.669807  recall@5=0.887257  recall@10=0.946734  recall@20=0.983828
precision@1=0.570312  precision@2=0.433111  precision@5=0.240883  precision@10=0.130944  precision@20=0.068404
ndcg@1=0.570312  ndcg@2=0.644150  ndcg@5=0.739893  ndcg@10=0.762094  ndcg@20=0.772702
hit_rate@1=0.570312  hit_rate@2=0.758135  hit_rate@5=0.927110  hit_rate@10=0.964562  hit_rate@20=0.990979
map@1=0.570312  map@2=0.609858  map@5=0.674807  map@10=0.687709  map@20=0.691704
mrr@1=0.570312  mrr@2=0.664224  mrr@5=0.712097  mrr@10=0.717230  mrr@20=0.719222
f1@1=0.495319  f1@2=0.505571  f1@5=0.365380  f1@10=0.223947  f1@20=0.125727

Epoch 11/100: 100%|██████████| 820/820 [00:13<00:00, 59.61it/s, bpr=0.0385, c=2.57, loss=0.141]

[VAL]
recall@1=0.462125  recall@2=0.673040  recall@5=0.884459  recall@10=0.947156  recall@20=0.981673
precision@1=0.566129  precision@2=0.432581  precision@5=0.240048  precision@10=0.130960  precision@20=0.068375
ndcg@1=0.566129  ndcg@2=0.644462  ndcg@5=0.738069  ndcg@10=0.761570  ndcg@20=0.771485
hit_rate@1=0.566129  hit_rate@2=0.762419  hit_rate@5=0.925565  hit_rate@10=0.965565  hit_rate@20=0.989516
map@1=0.566129  map@2=0.608972  map@5=0.672808  map@10=0.686520  map@20=0.690245
mrr@1=0.566129  mrr@2=0.664274  mrr@5=0.710972  mrr@10=0.716616  mrr@20=0.718368
f1@1=0.492757  f1@2=0.506372  f1@5=0.363937  f1@10=0.223922  f1@20=0.125597

[TEST]
recall@1=0.460519  recall@2=0.671241  recall@5=0.888578  recall@10=0.949613  recall@20=0.983474
precision@1=0.564594  precision@2=0.432265  precision@5=0.241092  precision@10=0.131290  precision@20=0.068424
ndcg@1=0.564594  ndcg@2=0.642887  ndcg@5=0.739354  ndcg@10=0.762135  ndcg@20=0.771854
hit_rate@1=0.564594  hit_rate@2=0.758296  hit_rate@5=0.928560  hit_rate@10=0.967381  hit_rate@20=0.990818
map@1=0.564594  map@2=0.608086  map@5=0.673717  map@10=0.686921  map@20=0.690610
mrr@1=0.564594  mrr@2=0.661445  mrr@5=0.709995  mrr@10=0.715315  mrr@20=0.717050
f1@1=0.491310  f1@2=0.505641  f1@5=0.365782  f1@10=0.224549  f1@20=0.125723

Epoch 12/100: 100%|██████████| 820/820 [00:13<00:00, 61.04it/s, bpr=0.0525, c=2.6, loss=0.156]

[VAL]
recall@1=0.459340  recall@2=0.669298  recall@5=0.886595  recall@10=0.949314  recall@20=0.981660
precision@1=0.562258  precision@2=0.430444  precision@5=0.240758  precision@10=0.131258  precision@20=0.068335
ndcg@1=0.562258  ndcg@2=0.640900  ndcg@5=0.737581  ndcg@10=0.760992  ndcg@20=0.770223
hit_rate@1=0.562258  hit_rate@2=0.757581  hit_rate@5=0.927823  hit_rate@10=0.967339  hit_rate@20=0.989839
map@1=0.562258  map@2=0.605827  map@5=0.671710  map@10=0.685417  map@20=0.688861
mrr@1=0.562258  mrr@2=0.659919  mrr@5=0.708683  mrr@10=0.714154  mrr@20=0.715766
f1@1=0.489659  f1@2=0.503685  f1@5=0.364936  f1@10=0.224418  f1@20=0.125544

[TEST]
recall@1=0.461277  recall@2=0.667549  recall@5=0.889278  recall@10=0.951499  recall@20=0.983739
precision@1=0.566124  precision@2=0.430332  precision@5=0.241044  precision@10=0.131572  precision@20=0.068424
ndcg@1=0.566124  ndcg@2=0.640922  ndcg@5=0.739564  ndcg@10=0.762908  ndcg@20=0.772071
hit_rate@1=0.566124  hit_rate@2=0.754430  hit_rate@5=0.929688  hit_rate@10=0.968508  hit_rate@20=0.991060
map@1=0.566124  map@2=0.606717  map@5=0.673772  map@10=0.687458  map@20=0.690869
mrr@1=0.566124  mrr@2=0.660277  mrr@5=0.710364  mrr@10=0.715729  mrr@20=0.717357
f1@1=0.492195  f1@2=0.503127  f1@5=0.365821  f1@10=0.225027  f1@20=0.125733

Epoch 13/100: 100%|██████████| 820/820 [00:13<00:00, 60.36it/s, bpr=0.025, c=2.61, loss=0.129]

[VAL]
recall@1=0.464696  recall@2=0.668546  recall@5=0.883339  recall@10=0.946216  recall@20=0.980947
precision@1=0.570161  precision@2=0.430484  precision@5=0.240016  precision@10=0.130847  precision@20=0.068290
ndcg@1=0.570161  ndcg@2=0.642987  ndcg@5=0.738032  ndcg@10=0.761355  ndcg@20=0.771327
hit_rate@1=0.570161  hit_rate@2=0.757742  hit_rate@5=0.924839  hit_rate@10=0.965242  hit_rate@20=0.989516
map@1=0.570161  map@2=0.608427  map@5=0.672958  map@10=0.686466  map@20=0.690223
mrr@1=0.570161  mrr@2=0.663952  mrr@5=0.711954  mrr@10=0.717466  mrr@20=0.719248
f1@1=0.495725  f1@2=0.503357  f1@5=0.363730  f1@10=0.223709  f1@20=0.125453

[TEST]
recall@1=0.465487  recall@2=0.666804  recall@5=0.884888  recall@10=0.948682  recall@20=0.983618
precision@1=0.572970  precision@2=0.431097  precision@5=0.240271  precision@10=0.131178  precision@20=0.068432
ndcg@1=0.572970  ndcg@2=0.642945  ndcg@5=0.739169  ndcg@10=0.762868  ndcg@20=0.772889
hit_rate@1=0.572970  hit_rate@2=0.753947  hit_rate@5=0.924613  hit_rate@10=0.966495  hit_rate@20=0.990738
map@1=0.572970  map@2=0.609435  map@5=0.674541  map@10=0.688131  map@20=0.691940
mrr@1=0.572970  mrr@2=0.663458  mrr@5=0.712250  mrr@10=0.718022  mrr@20=0.719839
f1@1=0.497166  f1@2=0.503182  f1@5=0.364436  f1@10=0.224335  f1@20=0.125741

Epoch 14/100: 100%|██████████| 820/820 [00:13<00:00, 60.56it/s, bpr=0.0285, c=2.54, loss=0.13]

[VAL]
recall@1=0.454176  recall@2=0.667104  recall@5=0.884660  recall@10=0.950091  recall@20=0.982378
precision@1=0.557742  precision@2=0.429032  precision@5=0.240161  precision@10=0.131395  precision@20=0.068379
ndcg@1=0.557742  ndcg@2=0.637631  ndcg@5=0.734226  ndcg@10=0.758579  ndcg@20=0.767834
hit_rate@1=0.557742  hit_rate@2=0.756290  hit_rate@5=0.926613  hit_rate@10=0.968145  hit_rate@20=0.990484
map@1=0.557742  map@2=0.601815  map@5=0.667476  map@10=0.681654  map@20=0.685140
mrr@1=0.557742  mrr@2=0.657016  mrr@5=0.705852  mrr@10=0.711552  mrr@20=0.713185
f1@1=0.484712  f1@2=0.501971  f1@5=0.364058  f1@10=0.224640  f1@20=0.125619

[TEST]
recall@1=0.456584  recall@2=0.666401  recall@5=0.885410  recall@10=0.951775  recall@20=0.984419
precision@1=0.561936  precision@2=0.429406  precision@5=0.240399  precision@10=0.131572  precision@20=0.068492
ndcg@1=0.561936  ndcg@2=0.638384  ndcg@5=0.735699  ndcg@10=0.760373  ndcg@20=0.769778
hit_rate@1=0.561936  hit_rate@2=0.753785  hit_rate@5=0.925741  hit_rate@10=0.969153  hit_rate@20=0.991624
map@1=0.561936  map@2=0.603475  map@5=0.669615  map@10=0.683776  map@20=0.687375
mrr@1=0.561936  mrr@2=0.657861  mrr@5=0.706976  mrr@10=0.713035  mrr@20=0.714701
f1@1=0.487694  f1@2=0.502148  f1@5=0.364615  f1@10=0.225082  f1@20=0.125860

Epoch 15/100: 100%|██████████| 820/820 [00:13<00:00, 60.73it/s, bpr=0.0331, c=2.53, loss=0.134]

[VAL]
recall@1=0.458389  recall@2=0.664357  recall@5=0.883590  recall@10=0.947813  recall@20=0.982984
precision@1=0.563387  precision@2=0.427056  precision@5=0.239677  precision@10=0.131105  precision@20=0.068431
ndcg@1=0.563387  ndcg@2=0.637267  ndcg@5=0.734924  ndcg@10=0.758963  ndcg@20=0.769016
hit_rate@1=0.563387  hit_rate@2=0.752500  hit_rate@5=0.925968  hit_rate@10=0.966129  hit_rate@20=0.990887
map@1=0.563387  map@2=0.602359  map@5=0.668594  map@10=0.682729  map@20=0.686481
mrr@1=0.563387  mrr@2=0.657944  mrr@5=0.707892  mrr@10=0.713420  mrr@20=0.715231
f1@1=0.489441  f1@2=0.499821  f1@5=0.363437  f1@10=0.224131  f1@20=0.125711

[TEST]
recall@1=0.457736  recall@2=0.663918  recall@5=0.887008  recall@10=0.949586  recall@20=0.985113
precision@1=0.562178  precision@2=0.427916  precision@5=0.240609  precision@10=0.131298  precision@20=0.068516
ndcg@1=0.562178  ndcg@2=0.637031  ndcg@5=0.736597  ndcg@10=0.759982  ndcg@20=0.770139
hit_rate@1=0.562178  hit_rate@2=0.752094  hit_rate@5=0.927593  hit_rate@10=0.967220  hit_rate@20=0.992268
map@1=0.562178  map@2=0.602408  map@5=0.670226  map@10=0.683864  map@20=0.687702
mrr@1=0.562178  mrr@2=0.657136  mrr@5=0.707570  mrr@10=0.713042  mrr@20=0.714891
f1@1=0.488537  f1@2=0.500360  f1@5=0.365074  f1@10=0.224601  f1@20=0.125912

Epoch 16/100: 100%|██████████| 820/820 [00:13<00:00, 61.53it/s, bpr=0.0361, c=2.53, loss=0.137]

[VAL]
recall@1=0.453494  recall@2=0.663744  recall@5=0.885791  recall@10=0.948294  recall@20=0.982614
precision@1=0.556210  precision@2=0.426935  precision@5=0.240403  precision@10=0.131137  precision@20=0.068387
ndcg@1=0.556210  ndcg@2=0.634899  ndcg@5=0.734086  ndcg@10=0.757497  ndcg@20=0.767290
hit_rate@1=0.556210  hit_rate@2=0.751613  hit_rate@5=0.926935  hit_rate@10=0.966774  hit_rate@20=0.990968
map@1=0.556210  map@2=0.599698  map@5=0.667208  map@10=0.680947  map@20=0.684601
mrr@1=0.556210  mrr@2=0.653911  mrr@5=0.704527  mrr@10=0.710025  mrr@20=0.711773
f1@1=0.483823  f1@2=0.499544  f1@5=0.364471  f1@10=0.224208  f1@20=0.125632

[TEST]
recall@1=0.462936  recall@2=0.662336  recall@5=0.888986  recall@10=0.950600  recall@20=0.984686
precision@1=0.568621  precision@2=0.427634  precision@5=0.241430  precision@10=0.131459  precision@20=0.068492
ndcg@1=0.568621  ndcg@2=0.638350  ndcg@5=0.739349  ndcg@10=0.762242  ndcg@20=0.771953
hit_rate@1=0.568621  hit_rate@2=0.749195  hit_rate@5=0.928157  hit_rate@10=0.968025  hit_rate@20=0.991704
map@1=0.568621  map@2=0.604986  map@5=0.673627  map@10=0.686802  map@20=0.690420
mrr@1=0.568621  mrr@2=0.658908  mrr@5=0.710221  mrr@10=0.715732  mrr@20=0.717463
f1@1=0.494120  f1@2=0.499551  f1@5=0.366159  f1@10=0.224835  f1@20=0.125875

Epoch 17/100: 100%|██████████| 820/820 [00:13<00:00, 61.28it/s, bpr=0.0532, c=2.43, loss=0.15]

[VAL]
recall@1=0.446398  recall@2=0.649435  recall@5=0.879234  recall@10=0.948980  recall@20=0.981567
precision@1=0.549355  precision@2=0.418790  precision@5=0.238532  precision@10=0.131169  precision@20=0.068343
ndcg@1=0.549355  ndcg@2=0.623088  ndcg@5=0.725271  ndcg@10=0.751083  ndcg@20=0.760464
hit_rate@1=0.549355  hit_rate@2=0.737984  hit_rate@5=0.922177  hit_rate@10=0.967419  hit_rate@20=0.989839
map@1=0.549355  map@2=0.588448  map@5=0.657338  map@10=0.672171  map@20=0.675723
mrr@1=0.549355  mrr@2=0.643669  mrr@5=0.696315  mrr@10=0.702422  mrr@20=0.704057
f1@1=0.476792  f1@2=0.489302  f1@5=0.361663  f1@10=0.224289  f1@20=0.125540

[TEST]
recall@1=0.448866  recall@2=0.651919  recall@5=0.880102  recall@10=0.950764  recall@20=0.982871
precision@1=0.553077  precision@2=0.420707  precision@5=0.238724  precision@10=0.131403  precision@20=0.068363
ndcg@1=0.553077  ndcg@2=0.625741  ndcg@5=0.727426  ndcg@10=0.753511  ndcg@20=0.762772
hit_rate@1=0.553077  hit_rate@2=0.738966  hit_rate@5=0.921311  hit_rate@10=0.968267  hit_rate@20=0.990335
map@1=0.553077  map@2=0.591596  map@5=0.660404  map@10=0.675189  map@20=0.678734
mrr@1=0.553077  mrr@2=0.646021  mrr@5=0.698044  mrr@10=0.704482  mrr@20=0.706132
f1@1=0.479546  f1@2=0.491589  f1@5=0.362215  f1@10=0.224777  f1@20=0.125625

Epoch 18/100: 100%|██████████| 820/820 [00:13<00:00, 61.47it/s, bpr=0.0586, c=2.6, loss=0.163]

[VAL]
recall@1=0.452033  recall@2=0.660044  recall@5=0.879501  recall@10=0.943161  recall@20=0.982421
precision@1=0.556290  precision@2=0.424879  precision@5=0.238742  precision@10=0.130524  precision@20=0.068411
ndcg@1=0.556290  ndcg@2=0.632155  ndcg@5=0.729852  ndcg@10=0.753614  ndcg@20=0.764839
hit_rate@1=0.556290  hit_rate@2=0.748226  hit_rate@5=0.922500  hit_rate@10=0.962097  hit_rate@20=0.990726
map@1=0.556290  map@2=0.597016  map@5=0.663179  map@10=0.677100  map@20=0.681276
mrr@1=0.556290  mrr@2=0.652258  mrr@5=0.702452  mrr@10=0.707851  mrr@20=0.709981
f1@1=0.482848  f1@2=0.496907  f1@5=0.361942  f1@10=0.223139  f1@20=0.125666

[TEST]
recall@1=0.452287  recall@2=0.657183  recall@5=0.882854  recall@10=0.944108  recall@20=0.983922
precision@1=0.556943  precision@2=0.423929  precision@5=0.239642  precision@10=0.130630  precision@20=0.068464
ndcg@1=0.556943  ndcg@2=0.630589  ndcg@5=0.731259  ndcg@10=0.754110  ndcg@20=0.765506
hit_rate@1=0.556943  hit_rate@2=0.744282  hit_rate@5=0.923486  hit_rate@10=0.962790  hit_rate@20=0.991302
map@1=0.556943  map@2=0.596247  map@5=0.664649  map@10=0.677892  map@20=0.682157
mrr@1=0.556943  mrr@2=0.650612  mrr@5=0.701895  mrr@10=0.707294  mrr@20=0.709452
f1@1=0.483185  f1@2=0.495449  f1@5=0.363416  f1@10=0.223366  f1@20=0.125796

Epoch 19/100: 100%|██████████| 820/820 [00:13<00:00, 60.69it/s, bpr=0.0616, c=2.55, loss=0.164]

[VAL]
recall@1=0.462176  recall@2=0.670566  recall@5=0.881225  recall@10=0.947096  recall@20=0.982135
precision@1=0.568226  precision@2=0.431694  precision@5=0.239403  precision@10=0.130952  precision@20=0.068379
ndcg@1=0.568226  ndcg@2=0.643347  ndcg@5=0.736610  ndcg@10=0.760998  ndcg@20=0.771050
hit_rate@1=0.568226  hit_rate@2=0.759677  hit_rate@5=0.922903  hit_rate@10=0.965565  hit_rate@20=0.990242
map@1=0.568226  map@2=0.608185  map@5=0.671770  map@10=0.685818  map@20=0.689605
mrr@1=0.568226  mrr@2=0.663952  mrr@5=0.710809  mrr@10=0.716653  mrr@20=0.718459
f1@1=0.493468  f1@2=0.504879  f1@5=0.362894  f1@10=0.223928  f1@20=0.125616

[TEST]
recall@1=0.465415  recall@2=0.669338  recall@5=0.884690  recall@10=0.949647  recall@20=0.983322
precision@1=0.571521  precision@2=0.432305  precision@5=0.240158  precision@10=0.131306  precision@20=0.068412
ndcg@1=0.571521  ndcg@2=0.644174  ndcg@5=0.739517  ndcg@10=0.763532  ndcg@20=0.773181
hit_rate@1=0.571521  hit_rate@2=0.757651  hit_rate@5=0.925016  hit_rate@10=0.966898  hit_rate@20=0.990577
map@1=0.571521  map@2=0.610060  map@5=0.675073  map@10=0.688835  map@20=0.692471
mrr@1=0.571521  mrr@2=0.664586  mrr@5=0.712410  mrr@10=0.718110  mrr@20=0.719872
f1@1=0.496752  f1@2=0.504925  f1@5=0.364276  f1@10=0.224584  f1@20=0.125708

Epoch 20/100: 100%|██████████| 820/820 [00:13<00:00, 61.02it/s, bpr=0.0337, c=2.75, loss=0.144]

[VAL]
recall@1=0.456606  recall@2=0.668054  recall@5=0.885188  recall@10=0.945495  recall@20=0.983473
precision@1=0.561290  precision@2=0.429234  precision@5=0.240290  precision@10=0.130750  precision@20=0.068484
ndcg@1=0.561290  ndcg@2=0.639022  ndcg@5=0.736251  ndcg@10=0.758867  ndcg@20=0.769755
hit_rate@1=0.561290  hit_rate@2=0.757903  hit_rate@5=0.926210  hit_rate@10=0.964516  hit_rate@20=0.991210
map@1=0.561290  map@2=0.603085  map@5=0.669956  map@10=0.683226  map@20=0.687343
mrr@1=0.561290  mrr@2=0.659597  mrr@5=0.708535  mrr@10=0.713825  mrr@20=0.715784
f1@1=0.487518  f1@2=0.502518  f1@5=0.364349  f1@10=0.223547  f1@20=0.125796

[TEST]
recall@1=0.458811  recall@2=0.668481  recall@5=0.886055  recall@10=0.947357  recall@20=0.984343
precision@1=0.564272  precision@2=0.430211  precision@5=0.240657  precision@10=0.131000  precision@20=0.068456
ndcg@1=0.564272  ndcg@2=0.640394  ndcg@5=0.737896  ndcg@10=0.760691  ndcg@20=0.771253
hit_rate@1=0.564272  hit_rate@2=0.757088  hit_rate@5=0.926063  hit_rate@10=0.965287  hit_rate@20=0.991382
map@1=0.564272  map@2=0.605126  map@5=0.672351  map@10=0.685498  map@20=0.689460
mrr@1=0.564272  mrr@2=0.660680  mrr@5=0.709473  mrr@10=0.714894  mrr@20=0.716833
f1@1=0.489961  f1@2=0.503394  f1@5=0.364955  f1@10=0.224078  f1@20=0.125811

Epoch 21/100: 100%|██████████| 820/820 [00:13<00:00, 60.35it/s, bpr=0.0464, c=2.6, loss=0.15]

[VAL]
recall@1=0.448731  recall@2=0.655467  recall@5=0.878370  recall@10=0.947068  recall@20=0.982667
precision@1=0.550645  precision@2=0.421694  precision@5=0.238161  precision@10=0.130984  precision@20=0.068435
ndcg@1=0.550645  ndcg@2=0.627429  ndcg@5=0.726783  ndcg@10=0.752336  ndcg@20=0.762531
hit_rate@1=0.550645  hit_rate@2=0.741855  hit_rate@5=0.921048  hit_rate@10=0.965484  hit_rate@20=0.990323
map@1=0.550645  map@2=0.592903  map@5=0.659949  map@10=0.674709  map@20=0.678518
mrr@1=0.550645  mrr@2=0.646250  mrr@5=0.697703  mrr@10=0.703763  mrr@20=0.705590
f1@1=0.478767  f1@2=0.493382  f1@5=0.361205  f1@10=0.223910  f1@20=0.125704

[TEST]
recall@1=0.455454  recall@2=0.657704  recall@5=0.882458  recall@10=0.949606  recall@20=0.983735
precision@1=0.559923  precision@2=0.424493  precision@5=0.239642  precision@10=0.131266  precision@20=0.068456
ndcg@1=0.559923  ndcg@2=0.632222  ndcg@5=0.732348  ndcg@10=0.757032  ndcg@20=0.766833
hit_rate@1=0.559923  hit_rate@2=0.745248  hit_rate@5=0.923566  hit_rate@10=0.967220  hit_rate@20=0.990899
map@1=0.559923  map@2=0.598200  map@5=0.666155  map@10=0.680202  map@20=0.683909
mrr@1=0.559923  mrr@2=0.652585  mrr@5=0.703522  mrr@10=0.709410  mrr@20=0.711158
f1@1=0.486286  f1@2=0.495943  f1@5=0.363415  f1@10=0.224544  f1@20=0.125787

Epoch 22/100: 100%|██████████| 820/820 [00:13<00:00, 61.30it/s, bpr=0.0582, c=2.59, loss=0.162]

[VAL]
recall@1=0.451868  recall@2=0.665072  recall@5=0.882055  recall@10=0.946024  recall@20=0.981793
precision@1=0.556048  precision@2=0.427702  precision@5=0.239242  precision@10=0.130887  precision@20=0.068371
ndcg@1=0.556048  ndcg@2=0.635272  ndcg@5=0.732320  ndcg@10=0.756248  ndcg@20=0.766476
hit_rate@1=0.556048  hit_rate@2=0.752661  hit_rate@5=0.924194  hit_rate@10=0.964677  hit_rate@20=0.990323
map@1=0.556048  map@2=0.599698  map@5=0.665837  map@10=0.679812  map@20=0.683624
mrr@1=0.556048  mrr@2=0.654355  mrr@5=0.704269  mrr@10=0.709801  mrr@20=0.711681
f1@1=0.482610  f1@2=0.500546  f1@5=0.362802  f1@10=0.223744  f1@20=0.125583

[TEST]
recall@1=0.456060  recall@2=0.662598  recall@5=0.883996  recall@10=0.947940  recall@20=0.983767
precision@1=0.560245  precision@2=0.427352  precision@5=0.239965  precision@10=0.131105  precision@20=0.068452
ndcg@1=0.560245  ndcg@2=0.635593  ndcg@5=0.734588  ndcg@10=0.758340  ndcg@20=0.768566
hit_rate@1=0.560245  hit_rate@2=0.749919  hit_rate@5=0.925258  hit_rate@10=0.965609  hit_rate@20=0.991140
map@1=0.560245  map@2=0.601160  map@5=0.668600  map@10=0.682332  map@20=0.686148
mrr@1=0.560245  mrr@2=0.655082  mrr@5=0.705799  mrr@10=0.711337  mrr@20=0.713225
f1@1=0.486828  f1@2=0.499498  f1@5=0.363941  f1@10=0.224214  f1@20=0.125775

Epoch 23/100: 100%|██████████| 820/820 [00:13<00:00, 61.09it/s, bpr=0.0287, c=2.6, loss=0.133]

[VAL]
recall@1=0.448081  recall@2=0.658651  recall@5=0.881232  recall@10=0.946700  recall@20=0.982749
precision@1=0.551210  precision@2=0.423871  precision@5=0.239048  precision@10=0.131000  precision@20=0.068448
ndcg@1=0.551210  ndcg@2=0.629657  ndcg@5=0.728910  ndcg@10=0.753396  ndcg@20=0.763724
hit_rate@1=0.551210  hit_rate@2=0.747339  hit_rate@5=0.924435  hit_rate@10=0.965000  hit_rate@20=0.990565
map@1=0.551210  map@2=0.594093  map@5=0.661345  map@10=0.675730  map@20=0.679592
mrr@1=0.551210  mrr@2=0.649274  mrr@5=0.700320  mrr@10=0.705919  mrr@20=0.707820
f1@1=0.478496  f1@2=0.495735  f1@5=0.362412  f1@10=0.223933  f1@20=0.125734

[TEST]
recall@1=0.452096  recall@2=0.657226  recall@5=0.882906  recall@10=0.948005  recall@20=0.984754
precision@1=0.555493  precision@2=0.423808  precision@5=0.239610  precision@10=0.131057  precision@20=0.068476
ndcg@1=0.555493  ndcg@2=0.630358  ndcg@5=0.731122  ndcg@10=0.755388  ndcg@20=0.765923
hit_rate@1=0.555493  hit_rate@2=0.744201  hit_rate@5=0.924211  hit_rate@10=0.966012  hit_rate@20=0.992107
map@1=0.555493  map@2=0.596045  map@5=0.664360  map@10=0.678425  map@20=0.682383
mrr@1=0.555493  mrr@2=0.649847  mrr@5=0.701556  mrr@10=0.707340  mrr@20=0.709293
f1@1=0.482675  f1@2=0.495385  f1@5=0.363426  f1@10=0.224176  f1@20=0.125841

Epoch 24/100: 100%|██████████| 820/820 [00:13<00:00, 61.27it/s, bpr=0.0311, c=2.49, loss=0.131]

[VAL]
recall@1=0.446564  recall@2=0.657809  recall@5=0.880752  recall@10=0.947534  recall@20=0.981962
precision@1=0.550000  precision@2=0.422903  precision@5=0.239129  precision@10=0.131097  precision@20=0.068391
ndcg@1=0.550000  ndcg@2=0.628306  ndcg@5=0.727936  ndcg@10=0.752722  ndcg@20=0.762636
hit_rate@1=0.550000  hit_rate@2=0.746613  hit_rate@5=0.923306  hit_rate@10=0.966048  hit_rate@20=0.990242
map@1=0.550000  map@2=0.592500  map@5=0.660248  map@10=0.674617  map@20=0.678360
mrr@1=0.550000  mrr@2=0.648306  mrr@5=0.699173  mrr@10=0.704993  mrr@20=0.706794
f1@1=0.477046  f1@2=0.494934  f1@5=0.362467  f1@10=0.224097  f1@20=0.125617

[TEST]
recall@1=0.453448  recall@2=0.659206  recall@5=0.881628  recall@10=0.950002  recall@20=0.983939
precision@1=0.556701  precision@2=0.424573  precision@5=0.239369  precision@10=0.131371  precision@20=0.068420
ndcg@1=0.556701  ndcg@2=0.631984  ndcg@5=0.731450  ndcg@10=0.756761  ndcg@20=0.766485
hit_rate@1=0.556701  hit_rate@2=0.746537  hit_rate@5=0.923003  hit_rate@10=0.967542  hit_rate@20=0.991463
map@1=0.556701  map@2=0.597475  map@5=0.665202  map@10=0.679690  map@20=0.683348
mrr@1=0.556701  mrr@2=0.651619  mrr@5=0.702291  mrr@10=0.708416  mrr@20=0.710208
f1@1=0.483944  f1@2=0.496569  f1@5=0.362992  f1@10=0.224679  f1@20=0.125745

Epoch 25/100: 100%|██████████| 820/820 [00:13<00:00, 61.46it/s, bpr=0.0408, c=2.59, loss=0.145]

[VAL]
recall@1=0.451451  recall@2=0.666016  recall@5=0.884605  recall@10=0.948064  recall@20=0.981524
precision@1=0.555403  precision@2=0.428185  precision@5=0.240323  precision@10=0.131194  precision@20=0.068363
ndcg@1=0.555403  ndcg@2=0.635845  ndcg@5=0.733403  ndcg@10=0.757016  ndcg@20=0.766596
hit_rate@1=0.555403  hit_rate@2=0.755000  hit_rate@5=0.925968  hit_rate@10=0.966371  hit_rate@20=0.989839
map@1=0.555403  map@2=0.599798  map@5=0.666373  map@10=0.680126  map@20=0.683726
mrr@1=0.555403  mrr@2=0.655242  mrr@5=0.704577  mrr@10=0.710153  mrr@20=0.711864
f1@1=0.482061  f1@2=0.501101  f1@5=0.364211  f1@10=0.224245  f1@20=0.125578

[TEST]
recall@1=0.455308  recall@2=0.664435  recall@5=0.885429  recall@10=0.950691  recall@20=0.984190
precision@1=0.559439  precision@2=0.427835  precision@5=0.240206  precision@10=0.131484  precision@20=0.068464
ndcg@1=0.559439  ndcg@2=0.636399  ndcg@5=0.735241  ndcg@10=0.759507  ndcg@20=0.769029
hit_rate@1=0.559439  hit_rate@2=0.753705  hit_rate@5=0.926466  hit_rate@10=0.967864  hit_rate@20=0.991543
map@1=0.559439  map@2=0.601039  map@5=0.668790  map@10=0.682799  map@20=0.686342
mrr@1=0.559439  mrr@2=0.656532  mrr@5=0.706407  mrr@10=0.712066  mrr@20=0.713793
f1@1=0.486075  f1@2=0.500353  f1@5=0.364404  f1@10=0.224872  f1@20=0.125797

Epoch 26/100: 100%|██████████| 820/820 [00:13<00:00, 61.17it/s, bpr=0.0285, c=2.6, loss=0.132]

[VAL]
recall@1=0.452941  recall@2=0.662253  recall@5=0.881683  recall@10=0.944984  recall@20=0.980255
precision@1=0.557097  precision@2=0.426492  precision@5=0.239435  precision@10=0.130718  precision@20=0.068306
ndcg@1=0.557097  ndcg@2=0.634144  ndcg@5=0.732021  ndcg@10=0.755553  ndcg@20=0.765756
hit_rate@1=0.557097  hit_rate@2=0.752581  hit_rate@5=0.923871  hit_rate@10=0.963710  hit_rate@20=0.988548
map@1=0.557097  map@2=0.598448  map@5=0.665358  map@10=0.679081  map@20=0.682951
mrr@1=0.557097  mrr@2=0.654839  mrr@5=0.704340  mrr@10=0.709769  mrr@20=0.711637
f1@1=0.483665  f1@2=0.498693  f1@5=0.362928  f1@10=0.223480  f1@20=0.125453

[TEST]
recall@1=0.457063  recall@2=0.664577  recall@5=0.884138  recall@10=0.947195  recall@20=0.982380
precision@1=0.562097  precision@2=0.429245  precision@5=0.240093  precision@10=0.130984  precision@20=0.068331
ndcg@1=0.562097  ndcg@2=0.637751  ndcg@5=0.735269  ndcg@10=0.758655  ndcg@20=0.768780
hit_rate@1=0.562097  hit_rate@2=0.753222  hit_rate@5=0.924855  hit_rate@10=0.965045  hit_rate@20=0.990174
map@1=0.562097  map@2=0.603012  map@5=0.669470  map@10=0.682958  map@20=0.686801
mrr@1=0.562097  mrr@2=0.657659  mrr@5=0.706847  mrr@10=0.712332  mrr@20=0.714239
f1@1=0.488059  f1@2=0.501285  f1@5=0.364085  f1@10=0.224031  f1@20=0.125565

Epoch 27/100: 100%|██████████| 820/820 [00:13<00:00, 60.97it/s, bpr=0.0515, c=2.52, loss=0.152]

[VAL]
recall@1=0.448716  recall@2=0.656600  recall@5=0.878632  recall@10=0.941286  recall@20=0.982102
precision@1=0.552581  precision@2=0.422903  precision@5=0.238419  precision@10=0.130298  precision@20=0.068419
ndcg@1=0.552581  ndcg@2=0.628571  ndcg@5=0.727808  ndcg@10=0.751297  ndcg@20=0.763079
hit_rate@1=0.552581  hit_rate@2=0.745081  hit_rate@5=0.921532  hit_rate@10=0.961048  hit_rate@20=0.990000
map@1=0.552581  map@2=0.593387  map@5=0.660793  map@10=0.674589  map@20=0.679060
mrr@1=0.552581  mrr@2=0.648871  mrr@5=0.699870  mrr@10=0.705343  mrr@20=0.707564
f1@1=0.479324  f1@2=0.494546  f1@5=0.361512  f1@10=0.222708  f1@20=0.125678

[TEST]
recall@1=0.455594  recall@2=0.656818  recall@5=0.882518  recall@10=0.942411  recall@20=0.983489
precision@1=0.560003  precision@2=0.424976  precision@5=0.239932  precision@10=0.130348  precision@20=0.068456
ndcg@1=0.560003  ndcg@2=0.632167  ndcg@5=0.732469  ndcg@10=0.754647  ndcg@20=0.766529
hit_rate@1=0.560003  hit_rate@2=0.744120  hit_rate@5=0.923325  hit_rate@10=0.961743  hit_rate@20=0.990818
map@1=0.560003  map@2=0.598542  map@5=0.666450  map@10=0.679211  map@20=0.683767
mrr@1=0.560003  mrr@2=0.652022  mrr@5=0.703312  mrr@10=0.708558  mrr@20=0.710797
f1@1=0.486412  f1@2=0.495836  f1@5=0.363699  f1@10=0.222908  f1@20=0.125766

Epoch 28/100: 100%|██████████| 820/820 [00:13<00:00, 61.05it/s, bpr=0.0513, c=2.54, loss=0.153]

[VAL]
recall@1=0.452720  recall@2=0.662333  recall@5=0.879292  recall@10=0.945855  recall@20=0.981452
precision@1=0.557016  precision@2=0.426290  precision@5=0.238500  precision@10=0.130831  precision@20=0.068359
ndcg@1=0.557016  ndcg@2=0.633983  ndcg@5=0.730855  ndcg@10=0.755648  ndcg@20=0.765894
hit_rate@1=0.557016  hit_rate@2=0.751371  hit_rate@5=0.922177  hit_rate@10=0.964435  hit_rate@20=0.989597
map@1=0.557016  map@2=0.598508  map@5=0.664589  map@10=0.679017  map@20=0.682890
mrr@1=0.557016  mrr@2=0.654194  mrr@5=0.703810  mrr@10=0.709567  mrr@20=0.711444
f1@1=0.483497  f1@2=0.498624  f1@5=0.361691  f1@10=0.223684  f1@20=0.125561

[TEST]
recall@1=0.455466  recall@2=0.664367  recall@5=0.883790  recall@10=0.947122  recall@20=0.983087
precision@1=0.560889  precision@2=0.429285  precision@5=0.240045  precision@10=0.130944  precision@20=0.068392
ndcg@1=0.560889  ndcg@2=0.637154  ndcg@5=0.734634  ndcg@10=0.758016  ndcg@20=0.768372
hit_rate@1=0.560889  hit_rate@2=0.752819  hit_rate@5=0.924452  hit_rate@10=0.965367  hit_rate@20=0.990577
map@1=0.560889  map@2=0.602287  map@5=0.668709  map@10=0.682099  map@20=0.686033
mrr@1=0.560889  mrr@2=0.656854  mrr@5=0.706131  mrr@10=0.711688  mrr@20=0.713588
f1@1=0.486597  f1@2=0.501233  f1@5=0.364019  f1@10=0.223956  f1@20=0.125673

Epoch 29/100: 100%|██████████| 820/820 [00:13<00:00, 60.45it/s, bpr=0.0439, c=2.47, loss=0.143]

[VAL]
recall@1=0.449237  recall@2=0.659610  recall@5=0.881462  recall@10=0.946955  recall@20=0.981587
precision@1=0.551210  precision@2=0.424032  precision@5=0.239000  precision@10=0.130976  precision@20=0.068371
ndcg@1=0.551210  ndcg@2=0.630450  ndcg@5=0.729061  ndcg@10=0.753540  ndcg@20=0.763515
hit_rate@1=0.551210  hit_rate@2=0.747177  hit_rate@5=0.923790  hit_rate@10=0.965403  hit_rate@20=0.989597
map@1=0.551210  map@2=0.595222  map@5=0.661800  map@10=0.676108  map@20=0.679894
mrr@1=0.551210  mrr@2=0.649194  mrr@5=0.699742  mrr@10=0.705436  mrr@20=0.707230
f1@1=0.479267  f1@2=0.496215  f1@5=0.362428  f1@10=0.223927  f1@20=0.125586

[TEST]
recall@1=0.455383  recall@2=0.659644  recall@5=0.884891  recall@10=0.949711  recall@20=0.983509
precision@1=0.559923  precision@2=0.425660  precision@5=0.240142  precision@10=0.131322  precision@20=0.068440
ndcg@1=0.559923  ndcg@2=0.633440  ndcg@5=0.733545  ndcg@10=0.757634  ndcg@20=0.767358
hit_rate@1=0.559923  hit_rate@2=0.747101  hit_rate@5=0.925499  hit_rate@10=0.967139  hit_rate@20=0.990818
map@1=0.559923  map@2=0.599227  map@5=0.667057  map@10=0.680926  map@20=0.684616
mrr@1=0.559923  mrr@2=0.653512  mrr@5=0.704294  mrr@10=0.710003  mrr@20=0.711773
f1@1=0.486211  f1@2=0.497432  f1@5=0.364292  f1@10=0.224597  f1@20=0.125750

Epoch 30/100: 100%|██████████| 820/820 [00:13<00:00, 61.71it/s, bpr=0.0527, c=2.53, loss=0.154]

[VAL]
recall@1=0.455483  recall@2=0.667541  recall@5=0.885820  recall@10=0.944386  recall@20=0.981051
precision@1=0.560242  precision@2=0.429677  precision@5=0.240323  precision@10=0.130589  precision@20=0.068294
ndcg@1=0.560242  ndcg@2=0.638624  ndcg@5=0.735809  ndcg@10=0.757764  ndcg@20=0.768373
hit_rate@1=0.560242  hit_rate@2=0.756694  hit_rate@5=0.926935  hit_rate@10=0.963468  hit_rate@20=0.989274
map@1=0.560242  map@2=0.602944  map@5=0.669191  map@10=0.682185  map@20=0.686206
mrr@1=0.560242  mrr@2=0.658468  mrr@5=0.707702  mrr@10=0.712706  mrr@20=0.714678
f1@1=0.486392  f1@2=0.502565  f1@5=0.364410  f1@10=0.223282  f1@20=0.125461

[TEST]
recall@1=0.463606  recall@2=0.668263  recall@5=0.889091  recall@10=0.947364  recall@20=0.983605
precision@1=0.569749  precision@2=0.431500  precision@5=0.241543  precision@10=0.130904  precision@20=0.068375
ndcg@1=0.569749  ndcg@2=0.642864  ndcg@5=0.740993  ndcg@10=0.762651  ndcg@20=0.773079
hit_rate@1=0.569749  hit_rate@2=0.757571  hit_rate@5=0.928640  hit_rate@10=0.965609  hit_rate@20=0.991221
map@1=0.569749  map@2=0.608388  map@5=0.675510  map@10=0.688052  map@20=0.692005
mrr@1=0.569749  mrr@2=0.663660  mrr@5=0.712790  mrr@10=0.717875  mrr@20=0.719804
f1@1=0.494874  f1@2=0.504001  f1@5=0.366303  f1@10=0.223930  f1@20=0.125672

Epoch 31/100: 100%|██████████| 820/820 [00:13<00:00, 60.59it/s, bpr=0.0261, c=2.63, loss=0.131]

[VAL]
recall@1=0.459885  recall@2=0.667645  recall@5=0.885779  recall@10=0.947234  recall@20=0.981860
precision@1=0.566210  precision@2=0.430403  precision@5=0.240839  precision@10=0.130935  precision@20=0.068359
ndcg@1=0.566210  ndcg@2=0.640842  ndcg@5=0.737888  ndcg@10=0.760531  ndcg@20=0.770569
hit_rate@1=0.566210  hit_rate@2=0.757097  hit_rate@5=0.925645  hit_rate@10=0.966048  hit_rate@20=0.990081
map@1=0.566210  map@2=0.605726  map@5=0.672100  map@10=0.685096  map@20=0.688932
mrr@1=0.566210  mrr@2=0.661653  mrr@5=0.710435  mrr@10=0.715917  mrr@20=0.717738
f1@1=0.491203  f1@2=0.503007  f1@5=0.364949  f1@10=0.223898  f1@20=0.125575

[TEST]
recall@1=0.458852  recall@2=0.667645  recall@5=0.884905  recall@10=0.948680  recall@20=0.983079
precision@1=0.565158  precision@2=0.431822  precision@5=0.240625  precision@10=0.131161  precision@20=0.068363
ndcg@1=0.565158  ndcg@2=0.641059  ndcg@5=0.737410  ndcg@10=0.760887  ndcg@20=0.770759
hit_rate@1=0.565158  hit_rate@2=0.756927  hit_rate@5=0.924533  hit_rate@10=0.966414  hit_rate@20=0.990577
map@1=0.565158  map@2=0.606173  map@5=0.672178  map@10=0.685489  map@20=0.689245
mrr@1=0.565158  mrr@2=0.661042  mrr@5=0.709246  mrr@10=0.714966  mrr@20=0.716779
f1@1=0.490177  f1@2=0.503912  f1@5=0.364778  f1@10=0.224317  f1@20=0.125634

Epoch 32/100: 100%|██████████| 820/820 [00:13<00:00, 60.90it/s, bpr=0.0276, c=2.67, loss=0.134]

[VAL]
recall@1=0.451000  recall@2=0.664992  recall@5=0.885059  recall@10=0.948180  recall@20=0.982014
precision@1=0.553871  precision@2=0.427419  precision@5=0.240194  precision@10=0.131113  precision@20=0.068359
ndcg@1=0.553871  ndcg@2=0.634792  ndcg@5=0.733244  ndcg@10=0.756710  ndcg@20=0.766456
hit_rate@1=0.553871  hit_rate@2=0.754355  hit_rate@5=0.925968  hit_rate@10=0.966290  hit_rate@20=0.990000
map@1=0.553871  map@2=0.598710  map@5=0.666079  map@10=0.679762  map@20=0.683427
mrr@1=0.553871  mrr@2=0.654113  mrr@5=0.703909  mrr@10=0.709378  mrr@20=0.711152
f1@1=0.481347  f1@2=0.500262  f1@5=0.364177  f1@10=0.224199  f1@20=0.125584

[TEST]
recall@1=0.459137  recall@2=0.665488  recall@5=0.888278  recall@10=0.950132  recall@20=0.983723
precision@1=0.563708  precision@2=0.428922  precision@5=0.241318  precision@10=0.131411  precision@20=0.068424
ndcg@1=0.563708  ndcg@2=0.638745  ndcg@5=0.738432  ndcg@10=0.761317  ndcg@20=0.770931
hit_rate@1=0.563708  hit_rate@2=0.753624  hit_rate@5=0.928721  hit_rate@10=0.967300  hit_rate@20=0.991140
map@1=0.563708  map@2=0.604160  map@5=0.672296  map@10=0.685505  map@20=0.689134
mrr@1=0.563708  mrr@2=0.658666  mrr@5=0.709254  mrr@10=0.714495  mrr@20=0.716275
f1@1=0.489971  f1@2=0.501458  f1@5=0.365914  f1@10=0.224752  f1@20=0.125740

Epoch 33/100: 100%|██████████| 820/820 [00:13<00:00, 60.73it/s, bpr=0.0342, c=2.64, loss=0.14]

[VAL]
recall@1=0.447786  recall@2=0.656566  recall@5=0.880312  recall@10=0.945319  recall@20=0.981730
precision@1=0.551371  precision@2=0.422218  precision@5=0.238855  precision@10=0.130702  precision@20=0.068347
ndcg@1=0.551371  ndcg@2=0.628255  ndcg@5=0.728261  ndcg@10=0.752372  ndcg@20=0.762857
hit_rate@1=0.551371  hit_rate@2=0.746290  hit_rate@5=0.922016  hit_rate@10=0.964355  hit_rate@20=0.990242
map@1=0.551371  map@2=0.592520  map@5=0.660734  map@10=0.674636  map@20=0.678589
mrr@1=0.551371  mrr@2=0.648831  mrr@5=0.699833  mrr@10=0.705574  mrr@20=0.707494
f1@1=0.478317  f1@2=0.493848  f1@5=0.362186  f1@10=0.223479  f1@20=0.125565

[TEST]
recall@1=0.447075  recall@2=0.658394  recall@5=0.883178  recall@10=0.947516  recall@20=0.983007
precision@1=0.550902  precision@2=0.424050  precision@5=0.239707  precision@10=0.130992  precision@20=0.068408
ndcg@1=0.550902  ndcg@2=0.629175  ndcg@5=0.729947  ndcg@10=0.753749  ndcg@20=0.763975
hit_rate@1=0.550902  hit_rate@2=0.744684  hit_rate@5=0.924694  hit_rate@10=0.965287  hit_rate@20=0.990577
map@1=0.550902  map@2=0.594153  map@5=0.662619  map@10=0.676367  map@20=0.680258
mrr@1=0.550902  mrr@2=0.647793  mrr@5=0.699729  mrr@10=0.705213  mrr@20=0.707110
f1@1=0.477719  f1@2=0.495979  f1@5=0.363550  f1@10=0.224047  f1@20=0.125686

Epoch 34/100: 100%|██████████| 820/820 [00:13<00:00, 61.12it/s, bpr=0.0213, c=2.84, loss=0.135]

[VAL]
recall@1=0.445963  recall@2=0.654735  recall@5=0.880616  recall@10=0.948490  recall@20=0.982415
precision@1=0.548629  precision@2=0.421290  precision@5=0.238790  precision@10=0.131185  precision@20=0.068391
ndcg@1=0.548629  ndcg@2=0.625993  ndcg@5=0.727094  ndcg@10=0.752322  ndcg@20=0.762060
hit_rate@1=0.548629  hit_rate@2=0.743387  hit_rate@5=0.922903  hit_rate@10=0.966452  hit_rate@20=0.990161
map@1=0.548629  map@2=0.590544  map@5=0.659248  map@10=0.673868  map@20=0.677527
mrr@1=0.548629  mrr@2=0.646008  mrr@5=0.697897  mrr@10=0.703804  mrr@20=0.705573
f1@1=0.476310  f1@2=0.492855  f1@5=0.362165  f1@10=0.224292  f1@20=0.125646

[TEST]
recall@1=0.451168  recall@2=0.653904  recall@5=0.880944  recall@10=0.950771  recall@20=0.984376
precision@1=0.555735  precision@2=0.422117  precision@5=0.239095  precision@10=0.131403  precision@20=0.068456
ndcg@1=0.555735  ndcg@2=0.628150  ndcg@5=0.729527  ndcg@10=0.755285  ndcg@20=0.764895
hit_rate@1=0.555735  hit_rate@2=0.741704  hit_rate@5=0.922197  hit_rate@10=0.967864  hit_rate@20=0.991865
map@1=0.555735  map@2=0.593911  map@5=0.662745  map@10=0.677411  map@20=0.681007
mrr@1=0.555735  mrr@2=0.648719  mrr@5=0.700644  mrr@10=0.706890  mrr@20=0.708659
f1@1=0.481985  f1@2=0.493101  f1@5=0.362674  f1@10=0.224780  f1@20=0.125801

Epoch 35/100: 100%|██████████| 820/820 [00:13<00:00, 60.93it/s, bpr=0.042, c=2.5, loss=0.142]

[VAL]
recall@1=0.440717  recall@2=0.652662  recall@5=0.876935  recall@10=0.947991  recall@20=0.980967
precision@1=0.542742  precision@2=0.420081  precision@5=0.237742  precision@10=0.131040  precision@20=0.068302
ndcg@1=0.542742  ndcg@2=0.622967  ndcg@5=0.723106  ndcg@10=0.749365  ndcg@20=0.758894
hit_rate@1=0.542742  hit_rate@2=0.741452  hit_rate@5=0.919839  hit_rate@10=0.966290  hit_rate@20=0.989516
map@1=0.542742  map@2=0.587177  map@5=0.655046  map@10=0.670062  map@20=0.673684
mrr@1=0.542742  mrr@2=0.642097  mrr@5=0.693929  mrr@10=0.700229  mrr@20=0.701937
f1@1=0.470656  f1@2=0.491200  f1@5=0.360578  f1@10=0.224076  f1@20=0.125472

[TEST]
recall@1=0.447931  recall@2=0.655244  recall@5=0.879596  recall@10=0.950127  recall@20=0.983377
precision@1=0.552352  precision@2=0.422519  precision@5=0.238595  precision@10=0.131290  precision@20=0.068420
ndcg@1=0.552352  ndcg@2=0.627505  ndcg@5=0.727943  ndcg@10=0.753924  ndcg@20=0.763527
hit_rate@1=0.552352  hit_rate@2=0.743073  hit_rate@5=0.921311  hit_rate@10=0.967784  hit_rate@20=0.990899
map@1=0.552352  map@2=0.592562  map@5=0.660926  map@10=0.675634  map@20=0.679313
mrr@1=0.552352  mrr@2=0.647713  mrr@5=0.699149  mrr@10=0.705474  mrr@20=0.707204
f1@1=0.478790  f1@2=0.493904  f1@5=0.361955  f1@10=0.224565  f1@20=0.125718

Epoch 36/100: 100%|██████████| 820/820 [00:13<00:00, 61.43it/s, bpr=0.0271, c=2.53, loss=0.128]

[VAL]
recall@1=0.448169  recall@2=0.663112  recall@5=0.884312  recall@10=0.947015  recall@20=0.982116
precision@1=0.551532  precision@2=0.426653  precision@5=0.240032  precision@10=0.130976  precision@20=0.068415
ndcg@1=0.551532  ndcg@2=0.632733  ndcg@5=0.731275  ndcg@10=0.754654  ndcg@20=0.764796
hit_rate@1=0.551532  hit_rate@2=0.751290  hit_rate@5=0.924839  hit_rate@10=0.965403  hit_rate@20=0.989839
map@1=0.551532  map@2=0.596855  map@5=0.663852  map@10=0.677457  map@20=0.681308
mrr@1=0.551532  mrr@2=0.651411  mrr@5=0.701499  mrr@10=0.707070  mrr@20=0.708906
f1@1=0.478608  f1@2=0.499119  f1@5=0.363969  f1@10=0.223937  f1@20=0.125671

[TEST]
recall@1=0.450868  recall@2=0.661238  recall@5=0.887069  recall@10=0.949461  recall@20=0.984282
precision@1=0.555493  precision@2=0.426869  precision@5=0.240706  precision@10=0.131290  precision@20=0.068452
ndcg@1=0.555493  ndcg@2=0.633020  ndcg@5=0.733652  ndcg@10=0.756861  ndcg@20=0.766860
hit_rate@1=0.555493  hit_rate@2=0.749356  hit_rate@5=0.927674  hit_rate@10=0.967139  hit_rate@20=0.991543
map@1=0.555493  map@2=0.597918  map@5=0.666290  map@10=0.679733  map@20=0.683541
mrr@1=0.555493  mrr@2=0.652424  mrr@5=0.703628  mrr@10=0.709021  mrr@20=0.710845
f1@1=0.481745  f1@2=0.498676  f1@5=0.365155  f1@10=0.224572  f1@20=0.125806

Epoch 37/100: 100%|██████████| 820/820 [00:13<00:00, 60.91it/s, bpr=0.0262, c=2.57, loss=0.129]

[VAL]
recall@1=0.454791  recall@2=0.662735  recall@5=0.880634  recall@10=0.944293  recall@20=0.981235
precision@1=0.560887  precision@2=0.426653  precision@5=0.239081  precision@10=0.130565  precision@20=0.068351
ndcg@1=0.560887  ndcg@2=0.635279  ndcg@5=0.732376  ndcg@10=0.755985  ndcg@20=0.766719
hit_rate@1=0.560887  hit_rate@2=0.751532  hit_rate@5=0.922903  hit_rate@10=0.963387  hit_rate@20=0.989194
map@1=0.560887  map@2=0.600000  map@5=0.666043  map@10=0.679712  map@20=0.683829
mrr@1=0.560887  mrr@2=0.656210  mrr@5=0.705848  mrr@10=0.711374  mrr@20=0.713349
f1@1=0.486095  f1@2=0.498959  f1@5=0.362449  f1@10=0.223244  f1@20=0.125556

[TEST]
recall@1=0.448579  recall@2=0.659688  recall@5=0.884341  recall@10=0.945994  recall@20=0.983533
precision@1=0.552996  precision@2=0.425701  precision@5=0.240061  precision@10=0.130783  precision@20=0.068416
ndcg@1=0.552996  ndcg@2=0.631075  ndcg@5=0.731299  ndcg@10=0.754165  ndcg@20=0.764977
hit_rate@1=0.552996  hit_rate@2=0.747584  hit_rate@5=0.924694  hit_rate@10=0.964723  hit_rate@20=0.990899
map@1=0.552996  map@2=0.595864  map@5=0.664173  map@10=0.677279  map@20=0.681440
mrr@1=0.552996  mrr@2=0.650290  mrr@5=0.701148  mrr@10=0.706604  mrr@20=0.708575
f1@1=0.479387  f1@2=0.497397  f1@5=0.364121  f1@10=0.223700  f1@20=0.125724

Epoch 38/100: 100%|██████████| 820/820 [00:13<00:00, 61.29it/s, bpr=0.0405, c=2.61, loss=0.145]

[VAL]
recall@1=0.463156  recall@2=0.666545  recall@5=0.887966  recall@10=0.946881  recall@20=0.982596
precision@1=0.568952  precision@2=0.428427  precision@5=0.241000  precision@10=0.130952  precision@20=0.068415
ndcg@1=0.568952  ndcg@2=0.640685  ndcg@5=0.739240  ndcg@10=0.761292  ndcg@20=0.771573
hit_rate@1=0.568952  hit_rate@2=0.756048  hit_rate@5=0.928226  hit_rate@10=0.965323  hit_rate@20=0.990403
map@1=0.568952  map@2=0.605827  map@5=0.672991  map@10=0.685989  map@20=0.689877
mrr@1=0.568952  mrr@2=0.662500  mrr@5=0.711981  mrr@10=0.717073  mrr@20=0.718937
f1@1=0.494369  f1@2=0.501452  f1@5=0.365415  f1@10=0.223901  f1@20=0.125678

[TEST]
recall@1=0.454433  recall@2=0.664700  recall@5=0.888969  recall@10=0.949392  recall@20=0.984832
precision@1=0.558715  precision@2=0.428560  precision@5=0.241318  precision@10=0.131266  precision@20=0.068508
ndcg@1=0.558715  ndcg@2=0.636529  ndcg@5=0.736537  ndcg@10=0.759112  ndcg@20=0.769277
hit_rate@1=0.558715  hit_rate@2=0.752497  hit_rate@5=0.928479  hit_rate@10=0.966817  hit_rate@20=0.991946
map@1=0.558715  map@2=0.601562  map@5=0.669710  map@10=0.682840  map@20=0.686698
mrr@1=0.558715  mrr@2=0.655606  mrr@5=0.706214  mrr@10=0.711544  mrr@20=0.713409
f1@1=0.485161  f1@2=0.500962  f1@5=0.366079  f1@10=0.224532  f1@20=0.125891

Epoch 39/100: 100%|██████████| 820/820 [00:13<00:00, 60.69it/s, bpr=0.0591, c=2.42, loss=0.156]

[VAL]
recall@1=0.448378  recall@2=0.662822  recall@5=0.880399  recall@10=0.944861  recall@20=0.981450
precision@1=0.552984  precision@2=0.426734  precision@5=0.239016  precision@10=0.130782  precision@20=0.068363
ndcg@1=0.552984  ndcg@2=0.632856  ndcg@5=0.729915  ndcg@10=0.753886  ndcg@20=0.764447
hit_rate@1=0.552984  hit_rate@2=0.752500  hit_rate@5=0.922581  hit_rate@10=0.963629  hit_rate@20=0.989597
map@1=0.552984  map@2=0.596613  map@5=0.662834  map@10=0.676751  map@20=0.680745
mrr@1=0.552984  mrr@2=0.652742  mrr@5=0.702214  mrr@10=0.707799  mrr@20=0.709783
f1@1=0.479246  f1@2=0.499031  f1@5=0.362322  f1@10=0.223525  f1@20=0.125564

[TEST]
recall@1=0.452964  recall@2=0.661484  recall@5=0.882538  recall@10=0.947985  recall@20=0.983480
precision@1=0.558312  precision@2=0.426909  precision@5=0.239755  precision@10=0.131081  precision@20=0.068420
ndcg@1=0.558312  ndcg@2=0.634006  ndcg@5=0.732726  ndcg@10=0.756913  ndcg@20=0.767147
hit_rate@1=0.558312  hit_rate@2=0.750242  hit_rate@5=0.923486  hit_rate@10=0.965851  hit_rate@20=0.990899
map@1=0.558312  map@2=0.598925  map@5=0.666426  map@10=0.680264  map@20=0.684173
mrr@1=0.558312  mrr@2=0.654277  mrr@5=0.704236  mrr@10=0.710045  mrr@20=0.711946
f1@1=0.484051  f1@2=0.498796  f1@5=0.363543  f1@10=0.224226  f1@20=0.125728

Epoch 40/100: 100%|██████████| 820/820 [00:13<00:00, 60.06it/s, bpr=0.0302, c=2.68, loss=0.138]

[VAL]
recall@1=0.446756  recall@2=0.661032  recall@5=0.882036  recall@10=0.944387  recall@20=0.983058
precision@1=0.552016  precision@2=0.425524  precision@5=0.239387  precision@10=0.130645  precision@20=0.068484
ndcg@1=0.552016  ndcg@2=0.631152  ndcg@5=0.729886  ndcg@10=0.753145  ndcg@20=0.764270
hit_rate@1=0.552016  hit_rate@2=0.751210  hit_rate@5=0.924516  hit_rate@10=0.963548  hit_rate@20=0.991129
map@1=0.552016  map@2=0.594738  map@5=0.662154  map@10=0.675771  map@20=0.679969
mrr@1=0.552016  mrr@2=0.651613  mrr@5=0.701935  mrr@10=0.707241  mrr@20=0.709313
f1@1=0.477737  f1@2=0.497629  f1@5=0.362959  f1@10=0.223348  f1@20=0.125785

[TEST]
recall@1=0.447572  recall@2=0.659363  recall@5=0.883628  recall@10=0.947146  recall@20=0.984405
precision@1=0.551869  precision@2=0.425540  precision@5=0.239948  precision@10=0.131041  precision@20=0.068452
ndcg@1=0.551869  ndcg@2=0.630538  ndcg@5=0.730745  ndcg@10=0.754314  ndcg@20=0.764927
hit_rate@1=0.551869  hit_rate@2=0.747503  hit_rate@5=0.924291  hit_rate@10=0.965287  hit_rate@20=0.991865
map@1=0.551869  map@2=0.595180  map@5=0.663517  map@10=0.677060  map@20=0.681047
mrr@1=0.551869  mrr@2=0.649686  mrr@5=0.700709  mrr@10=0.706319  mrr@20=0.708300
f1@1=0.478369  f1@2=0.497109  f1@5=0.363877  f1@10=0.224083  f1@20=0.125796

Epoch 41/100: 100%|██████████| 820/820 [00:13<00:00, 60.04it/s, bpr=0.0263, c=2.62, loss=0.131]

[VAL]
recall@1=0.454653  recall@2=0.659498  recall@5=0.877967  recall@10=0.945246  recall@20=0.982173
precision@1=0.560242  precision@2=0.425000  precision@5=0.238290  precision@10=0.130790  precision@20=0.068427
ndcg@1=0.560242  ndcg@2=0.633210  ndcg@5=0.730503  ndcg@10=0.755442  ndcg@20=0.766085
hit_rate@1=0.560242  hit_rate@2=0.749516  hit_rate@5=0.920645  hit_rate@10=0.964032  hit_rate@20=0.990081
map@1=0.560242  map@2=0.598105  map@5=0.664330  map@10=0.678727  map@20=0.682756
mrr@1=0.560242  mrr@2=0.654879  mrr@5=0.704469  mrr@10=0.710398  mrr@20=0.712367
f1@1=0.485721  f1@2=0.496786  f1@5=0.361288  f1@10=0.223551  f1@20=0.125683

[TEST]
recall@1=0.451520  recall@2=0.662623  recall@5=0.881713  recall@10=0.948170  recall@20=0.983662
precision@1=0.556379  precision@2=0.427916  precision@5=0.239481  precision@10=0.131049  precision@20=0.068396
ndcg@1=0.556379  ndcg@2=0.634473  ndcg@5=0.731798  ndcg@10=0.756246  ndcg@20=0.766450
hit_rate@1=0.556379  hit_rate@2=0.752416  hit_rate@5=0.922439  hit_rate@10=0.966173  hit_rate@20=0.991382
map@1=0.556379  map@2=0.598925  map@5=0.665396  map@10=0.679230  map@20=0.683128
mrr@1=0.556379  mrr@2=0.654398  mrr@5=0.703344  mrr@10=0.709281  mrr@20=0.711166
f1@1=0.482474  f1@2=0.499708  f1@5=0.363157  f1@10=0.224189  f1@20=0.125699

Epoch 42/100: 100%|██████████| 820/820 [00:13<00:00, 60.99it/s, bpr=0.0433, c=2.64, loss=0.149]

[VAL]
recall@1=0.447455  recall@2=0.657040  recall@5=0.880593  recall@10=0.945054  recall@20=0.981161
precision@1=0.552177  precision@2=0.422581  precision@5=0.239016  precision@10=0.130710  precision@20=0.068339
ndcg@1=0.552177  ndcg@2=0.628346  ndcg@5=0.728695  ndcg@10=0.752580  ndcg@20=0.763026
hit_rate@1=0.552177  hit_rate@2=0.745161  hit_rate@5=0.922581  hit_rate@10=0.964274  hit_rate@20=0.989435
map@1=0.552177  map@2=0.592843  map@5=0.661246  map@10=0.675048  map@20=0.679021
mrr@1=0.552177  mrr@2=0.648669  mrr@5=0.700352  mrr@10=0.705979  mrr@20=0.707871
f1@1=0.478369  f1@2=0.494459  f1@5=0.362361  f1@10=0.223452  f1@20=0.125544

[TEST]
recall@1=0.446763  recall@2=0.659116  recall@5=0.883167  recall@10=0.946514  recall@20=0.983812
precision@1=0.550660  precision@2=0.425540  precision@5=0.239723  precision@10=0.130807  precision@20=0.068456
ndcg@1=0.550660  ndcg@2=0.630022  ndcg@5=0.730091  ndcg@10=0.753518  ndcg@20=0.764251
hit_rate@1=0.550660  hit_rate@2=0.746215  hit_rate@5=0.924130  hit_rate@10=0.964965  hit_rate@20=0.990979
map@1=0.550660  map@2=0.594918  map@5=0.662947  map@10=0.676354  map@20=0.680427
mrr@1=0.550660  mrr@2=0.648438  mrr@5=0.699792  mrr@10=0.705355  mrr@20=0.707303
f1@1=0.477385  f1@2=0.497094  f1@5=0.363608  f1@10=0.223742  f1@20=0.125790

Epoch 43/100: 100%|██████████| 820/820 [00:13<00:00, 60.58it/s, bpr=0.0421, c=2.59, loss=0.146]

[VAL]
recall@1=0.446404  recall@2=0.654942  recall@5=0.882453  recall@10=0.946519  recall@20=0.982203
precision@1=0.550323  precision@2=0.421935  precision@5=0.239419  precision@10=0.130968  precision@20=0.068419
ndcg@1=0.550323  ndcg@2=0.626728  ndcg@5=0.728239  ndcg@10=0.752100  ndcg@20=0.762349
hit_rate@1=0.550323  hit_rate@2=0.743065  hit_rate@5=0.924032  hit_rate@10=0.964919  hit_rate@20=0.990081
map@1=0.550323  map@2=0.591492  map@5=0.660242  map@10=0.674138  map@20=0.678001
mrr@1=0.550323  mrr@2=0.646694  mrr@5=0.698804  mrr@10=0.704364  mrr@20=0.706233
f1@1=0.477092  f1@2=0.493277  f1@5=0.363023  f1@10=0.223871  f1@20=0.125669

[TEST]
recall@1=0.448680  recall@2=0.653838  recall@5=0.883625  recall@10=0.948872  recall@20=0.983852
precision@1=0.552674  precision@2=0.421754  precision@5=0.239771  precision@10=0.131169  precision@20=0.068416
ndcg@1=0.552674  ndcg@2=0.626991  ndcg@5=0.729840  ndcg@10=0.754016  ndcg@20=0.764008
hit_rate@1=0.552674  hit_rate@2=0.741785  hit_rate@5=0.925177  hit_rate@10=0.966898  hit_rate@20=0.991382
map@1=0.552674  map@2=0.592381  map@5=0.662292  map@10=0.676203  map@20=0.679976
mrr@1=0.552674  mrr@2=0.647229  mrr@5=0.699969  mrr@10=0.705631  mrr@20=0.707430
f1@1=0.479288  f1@2=0.492865  f1@5=0.363758  f1@10=0.224361  f1@20=0.125732

Epoch 44/100: 100%|██████████| 820/820 [00:13<00:00, 60.71it/s, bpr=0.0496, c=2.6, loss=0.153]

[VAL]
recall@1=0.453569  recall@2=0.656672  recall@5=0.880531  recall@10=0.944101  recall@20=0.982117
precision@1=0.558790  precision@2=0.423266  precision@5=0.239145  precision@10=0.130597  precision@20=0.068411
ndcg@1=0.558790  ndcg@2=0.630773  ndcg@5=0.730551  ndcg@10=0.754149  ndcg@20=0.765121
hit_rate@1=0.558790  hit_rate@2=0.745484  hit_rate@5=0.922339  hit_rate@10=0.963226  hit_rate@20=0.990161
map@1=0.558790  map@2=0.596089  map@5=0.663846  map@10=0.677480  map@20=0.681647
mrr@1=0.558790  mrr@2=0.652137  mrr@5=0.703180  mrr@10=0.708727  mrr@20=0.710755
f1@1=0.484673  f1@2=0.494731  f1@5=0.362520  f1@10=0.223266  f1@20=0.125660

[TEST]
recall@1=0.454553  recall@2=0.656934  recall@5=0.883514  recall@10=0.945752  recall@20=0.983253
precision@1=0.558876  precision@2=0.424291  precision@5=0.240142  precision@10=0.130775  precision@20=0.068359
ndcg@1=0.558876  ndcg@2=0.631541  ndcg@5=0.732744  ndcg@10=0.755778  ndcg@20=0.766529
hit_rate@1=0.558876  hit_rate@2=0.744282  hit_rate@5=0.923486  hit_rate@10=0.964320  hit_rate@20=0.990979
map@1=0.558876  map@2=0.597616  map@5=0.666476  map@10=0.679653  map@20=0.683723
mrr@1=0.558876  mrr@2=0.651579  mrr@5=0.703164  mrr@10=0.708782  mrr@20=0.710785
f1@1=0.485306  f1@2=0.495485  f1@5=0.364076  f1@10=0.223680  f1@20=0.125643

Epoch 45/100: 100%|██████████| 820/820 [00:13<00:00, 60.87it/s, bpr=0.0324, c=2.64, loss=0.138]

[VAL]
recall@1=0.459562  recall@2=0.661579  recall@5=0.882042  recall@10=0.947744  recall@20=0.983048
precision@1=0.564032  precision@2=0.425444  precision@5=0.239306  precision@10=0.131145  precision@20=0.068452
ndcg@1=0.564032  ndcg@2=0.635789  ndcg@5=0.734446  ndcg@10=0.758881  ndcg@20=0.768993
hit_rate@1=0.564032  hit_rate@2=0.750565  hit_rate@5=0.924274  hit_rate@10=0.966129  hit_rate@20=0.990887
map@1=0.564032  map@2=0.601190  map@5=0.668517  map@10=0.682713  map@20=0.686502
mrr@1=0.564032  mrr@2=0.657298  mrr@5=0.707688  mrr@10=0.713369  mrr@20=0.715202
f1@1=0.490420  f1@2=0.497878  f1@5=0.362878  f1@10=0.224168  f1@20=0.125743

[TEST]
recall@1=0.458681  recall@2=0.663339  recall@5=0.884684  recall@10=0.949750  recall@20=0.984284
precision@1=0.562178  precision@2=0.428197  precision@5=0.240061  precision@10=0.131314  precision@20=0.068480
ndcg@1=0.562178  ndcg@2=0.637173  ndcg@5=0.735728  ndcg@10=0.759918  ndcg@20=0.769810
hit_rate@1=0.562178  hit_rate@2=0.751289  hit_rate@5=0.925419  hit_rate@10=0.967300  hit_rate@20=0.991543
map@1=0.562178  map@2=0.602972  map@5=0.670017  map@10=0.683965  map@20=0.687700
mrr@1=0.562178  mrr@2=0.656733  mrr@5=0.706855  mrr@10=0.712609  mrr@20=0.714398
f1@1=0.489247  f1@2=0.500260  f1@5=0.364124  f1@10=0.224609  f1@20=0.125835

Epoch 46/100: 100%|██████████| 820/820 [00:13<00:00, 60.99it/s, bpr=0.0238, c=2.73, loss=0.133]

[VAL]
recall@1=0.452132  recall@2=0.665829  recall@5=0.884963  recall@10=0.944641  recall@20=0.982344
precision@1=0.556855  precision@2=0.428790  precision@5=0.240258  precision@10=0.130734  precision@20=0.068431
ndcg@1=0.556855  ndcg@2=0.636321  ndcg@5=0.734131  ndcg@10=0.756478  ndcg@20=0.767272
hit_rate@1=0.556855  hit_rate@2=0.755000  hit_rate@5=0.926048  hit_rate@10=0.963387  hit_rate@20=0.990403
map@1=0.556855  map@2=0.600403  map@5=0.667184  map@10=0.680322  map@20=0.684361
mrr@1=0.556855  mrr@2=0.655927  mrr@5=0.705667  mrr@10=0.710780  mrr@20=0.712790
f1@1=0.483042  f1@2=0.501347  f1@5=0.364211  f1@10=0.223472  f1@20=0.125694

[TEST]
recall@1=0.457564  recall@2=0.665397  recall@5=0.887112  recall@10=0.946303  recall@20=0.983202
precision@1=0.562419  precision@2=0.428278  precision@5=0.240947  precision@10=0.130807  precision@20=0.068351
ndcg@1=0.562419  ndcg@2=0.637856  ndcg@5=0.737091  ndcg@10=0.759135  ndcg@20=0.769712
hit_rate@1=0.562419  hit_rate@2=0.752738  hit_rate@5=0.926949  hit_rate@10=0.964642  hit_rate@20=0.990818
map@1=0.562419  map@2=0.603113  map@5=0.670997  map@10=0.683786  map@20=0.687777
mrr@1=0.562419  mrr@2=0.657579  mrr@5=0.707783  mrr@10=0.712965  mrr@20=0.714933
f1@1=0.488526  f1@2=0.501086  f1@5=0.365416  f1@10=0.223759  f1@20=0.125624

Epoch 47/100: 100%|██████████| 820/820 [00:13<00:00, 60.97it/s, bpr=0.0285, c=2.57, loss=0.131]

[VAL]
recall@1=0.448369  recall@2=0.660056  recall@5=0.886197  recall@10=0.948008  recall@20=0.982249
precision@1=0.551290  precision@2=0.423952  precision@5=0.240290  precision@10=0.131113  precision@20=0.068427
ndcg@1=0.551290  ndcg@2=0.630299  ndcg@5=0.731399  ndcg@10=0.754574  ndcg@20=0.764420
hit_rate@1=0.551290  hit_rate@2=0.748065  hit_rate@5=0.926774  hit_rate@10=0.966371  hit_rate@20=0.990081
map@1=0.551290  map@2=0.594637  map@5=0.663360  map@10=0.676959  map@20=0.680686
mrr@1=0.551290  mrr@2=0.649677  mrr@5=0.701190  mrr@10=0.706643  mrr@20=0.708396
f1@1=0.478717  f1@2=0.496370  f1@5=0.364477  f1@10=0.224143  f1@20=0.125681

[TEST]
recall@1=0.451423  recall@2=0.659822  recall@5=0.887687  recall@10=0.949587  recall@20=0.983076
precision@1=0.554688  precision@2=0.424895  precision@5=0.240706  precision@10=0.131226  precision@20=0.068392
ndcg@1=0.554688  ndcg@2=0.631472  ndcg@5=0.733854  ndcg@10=0.756965  ndcg@20=0.766605
hit_rate@1=0.554688  hit_rate@2=0.747181  hit_rate@5=0.928640  hit_rate@10=0.967381  hit_rate@20=0.990577
map@1=0.554688  map@2=0.596569  map@5=0.666416  map@10=0.679921  map@20=0.683604
mrr@1=0.554688  mrr@2=0.650934  mrr@5=0.703226  mrr@10=0.708537  mrr@20=0.710256
f1@1=0.481999  f1@2=0.497077  f1@5=0.365208  f1@10=0.224485  f1@20=0.125674

Epoch 48/100: 100%|██████████| 820/820 [00:13<00:00, 61.18it/s, bpr=0.0302, c=2.51, loss=0.131]

[VAL]
recall@1=0.433824  recall@2=0.647871  recall@5=0.880194  recall@10=0.947868  recall@20=0.982075
precision@1=0.535081  precision@2=0.416532  precision@5=0.238726  precision@10=0.131177  precision@20=0.068423
ndcg@1=0.535081  ndcg@2=0.616607  ndcg@5=0.720781  ndcg@10=0.745993  ndcg@20=0.755799
hit_rate@1=0.535081  hit_rate@2=0.736935  hit_rate@5=0.922742  hit_rate@10=0.966129  hit_rate@20=0.990000
map@1=0.535081  map@2=0.580202  map@5=0.650871  map@10=0.665500  map@20=0.669161
mrr@1=0.535081  mrr@2=0.635927  mrr@5=0.689567  mrr@10=0.695481  mrr@20=0.697191
f1@1=0.463607  f1@2=0.487406  f1@5=0.362002  f1@10=0.224213  f1@20=0.125684

[TEST]
recall@1=0.438801  recall@2=0.647265  recall@5=0.881763  recall@10=0.950708  recall@20=0.984481
precision@1=0.541398  precision@2=0.417445  precision@5=0.239127  precision@10=0.131451  precision@20=0.068529
ndcg@1=0.541398  ndcg@2=0.618593  ndcg@5=0.723456  ndcg@10=0.749048  ndcg@20=0.758800
hit_rate@1=0.541398  hit_rate@2=0.735180  hit_rate@5=0.923889  hit_rate@10=0.968508  hit_rate@20=0.991463
map@1=0.541398  map@2=0.583380  map@5=0.654186  map@10=0.668926  map@20=0.672685
mrr@1=0.541398  mrr@2=0.638370  mrr@5=0.692220  mrr@10=0.698322  mrr@20=0.700102
f1@1=0.469111  f1@2=0.487888  f1@5=0.362779  f1@10=0.224823  f1@20=0.125899

Epoch 49/100: 100%|██████████| 820/820 [00:13<00:00, 60.77it/s, bpr=0.0416, c=2.43, loss=0.139]

[VAL]
recall@1=0.449692  recall@2=0.658424  recall@5=0.881504  recall@10=0.945896  recall@20=0.981679
precision@1=0.553226  precision@2=0.423468  precision@5=0.239290  precision@10=0.130879  precision@20=0.068391
ndcg@1=0.553226  ndcg@2=0.630019  ndcg@5=0.729948  ndcg@10=0.753958  ndcg@20=0.764352
hit_rate@1=0.553226  hit_rate@2=0.746532  hit_rate@5=0.923306  hit_rate@10=0.964435  hit_rate@20=0.989435
map@1=0.553226  map@2=0.594778  map@5=0.662833  map@10=0.676795  map@20=0.680796
mrr@1=0.553226  mrr@2=0.649919  mrr@5=0.701219  mrr@10=0.706866  mrr@20=0.708803
f1@1=0.480188  f1@2=0.495494  f1@5=0.362775  f1@10=0.223733  f1@20=0.125628

[TEST]
recall@1=0.454671  recall@2=0.658525  recall@5=0.884987  recall@10=0.948419  recall@20=0.984087
precision@1=0.558634  precision@2=0.424613  precision@5=0.240142  precision@10=0.131169  precision@20=0.068452
ndcg@1=0.558634  ndcg@2=0.632145  ndcg@5=0.733737  ndcg@10=0.757300  ndcg@20=0.767520
hit_rate@1=0.558634  hit_rate@2=0.746053  hit_rate@5=0.925983  hit_rate@10=0.966253  hit_rate@20=0.991463
map@1=0.558634  map@2=0.597837  map@5=0.667106  map@10=0.680765  map@20=0.684629
mrr@1=0.558634  mrr@2=0.652344  mrr@5=0.704355  mrr@10=0.709806  mrr@20=0.711694
f1@1=0.485457  f1@2=0.496371  f1@5=0.364336  f1@10=0.224340  f1@20=0.125787

Epoch 50/100: 100%|██████████| 820/820 [00:13<00:00, 60.74it/s, bpr=0.0263, c=2.7, loss=0.134]

[VAL]
recall@1=0.460622  recall@2=0.670322  recall@5=0.886164  recall@10=0.943826  recall@20=0.981958
precision@1=0.566290  precision@2=0.431129  precision@5=0.240548  precision@10=0.130589  precision@20=0.068387
ndcg@1=0.566290  ndcg@2=0.642423  ndcg@5=0.738495  ndcg@10=0.760187  ndcg@20=0.771175
hit_rate@1=0.566290  hit_rate@2=0.760645  hit_rate@5=0.927419  hit_rate@10=0.962903  hit_rate@20=0.990000
map@1=0.566290  map@2=0.606694  map@5=0.672493  map@10=0.685344  map@20=0.689507
mrr@1=0.566290  mrr@2=0.663468  mrr@5=0.711647  mrr@10=0.716553  mrr@20=0.718591
f1@1=0.491840  f1@2=0.504431  f1@5=0.364677  f1@10=0.223229  f1@20=0.125629

[TEST]
recall@1=0.461736  recall@2=0.667209  recall@5=0.887013  recall@10=0.947172  recall@20=0.983583
precision@1=0.567252  precision@2=0.429486  precision@5=0.240802  precision@10=0.130944  precision@20=0.068432
ndcg@1=0.567252  ndcg@2=0.640770  ndcg@5=0.739347  ndcg@10=0.761753  ndcg@20=0.772246
hit_rate@1=0.567252  hit_rate@2=0.755557  hit_rate@5=0.927352  hit_rate@10=0.965287  hit_rate@20=0.990899
map@1=0.567252  map@2=0.606133  map@5=0.673830  map@10=0.686830  map@20=0.690826
mrr@1=0.567252  mrr@2=0.661405  mrr@5=0.711370  mrr@10=0.716580  mrr@20=0.718503
f1@1=0.492856  f1@2=0.502471  f1@5=0.365212  f1@10=0.223983  f1@20=0.125745

Epoch 51/100: 100%|██████████| 820/820 [00:13<00:00, 60.71it/s, bpr=0.0582, c=2.52, loss=0.159]

[VAL]
recall@1=0.454179  recall@2=0.662579  recall@5=0.885387  recall@10=0.946177  recall@20=0.982625
precision@1=0.558790  precision@2=0.426290  precision@5=0.240323  precision@10=0.130887  precision@20=0.068427
ndcg@1=0.558790  ndcg@2=0.634601  ndcg@5=0.733988  ndcg@10=0.756800  ndcg@20=0.767298
hit_rate@1=0.558790  hit_rate@2=0.751613  hit_rate@5=0.926935  hit_rate@10=0.964839  hit_rate@20=0.990565
map@1=0.558790  map@2=0.599214  map@5=0.666774  map@10=0.680259  map@20=0.684231
mrr@1=0.558790  mrr@2=0.655202  mrr@5=0.705704  mrr@10=0.710983  mrr@20=0.712910
f1@1=0.485087  f1@2=0.498718  f1@5=0.364360  f1@10=0.223768  f1@20=0.125698

[TEST]
recall@1=0.458465  recall@2=0.659305  recall@5=0.887585  recall@10=0.947891  recall@20=0.984157
precision@1=0.562983  precision@2=0.424573  precision@5=0.240867  precision@10=0.131097  precision@20=0.068460
ndcg@1=0.562983  ndcg@2=0.633958  ndcg@5=0.736310  ndcg@10=0.758928  ndcg@20=0.769362
hit_rate@1=0.562983  hit_rate@2=0.746215  hit_rate@5=0.928318  hit_rate@10=0.965689  hit_rate@20=0.991302
map@1=0.562983  map@2=0.600093  map@5=0.669752  map@10=0.683047  map@20=0.687013
mrr@1=0.562983  mrr@2=0.654599  mrr@5=0.706908  mrr@10=0.712092  mrr@20=0.714031
f1@1=0.489387  f1@2=0.496661  f1@5=0.365424  f1@10=0.224238  f1@20=0.125814

Epoch 52/100: 100%|██████████| 820/820 [00:13<00:00, 61.05it/s, bpr=0.0449, c=2.55, loss=0.147]

[VAL]
recall@1=0.450691  recall@2=0.657528  recall@5=0.884484  recall@10=0.947410  recall@20=0.981929
precision@1=0.553145  precision@2=0.422903  precision@5=0.239758  precision@10=0.131056  precision@20=0.068407
ndcg@1=0.553145  ndcg@2=0.629525  ndcg@5=0.731513  ndcg@10=0.755161  ndcg@20=0.765125
hit_rate@1=0.553145  hit_rate@2=0.745323  hit_rate@5=0.926129  hit_rate@10=0.965806  hit_rate@20=0.990161
map@1=0.553145  map@2=0.594597  map@5=0.664075  map@10=0.678013  map@20=0.681794
mrr@1=0.553145  mrr@2=0.649234  mrr@5=0.701895  mrr@10=0.707367  mrr@20=0.709177
f1@1=0.480982  f1@2=0.494853  f1@5=0.363677  f1@10=0.224056  f1@20=0.125647

[TEST]
recall@1=0.458225  recall@2=0.660540  recall@5=0.888563  recall@10=0.949448  recall@20=0.983356
precision@1=0.563708  precision@2=0.425580  precision@5=0.240979  precision@10=0.131274  precision@20=0.068363
ndcg@1=0.563708  ndcg@2=0.634969  ndcg@5=0.736964  ndcg@10=0.759645  ndcg@20=0.769353
hit_rate@1=0.563708  hit_rate@2=0.748470  hit_rate@5=0.929204  hit_rate@10=0.966898  hit_rate@20=0.991060
map@1=0.563708  map@2=0.600737  map@5=0.670104  map@10=0.683341  map@20=0.686994
mrr@1=0.563708  mrr@2=0.656089  mrr@5=0.708137  mrr@10=0.713247  mrr@20=0.715050
f1@1=0.489294  f1@2=0.497705  f1@5=0.365657  f1@10=0.224550  f1@20=0.125646

Epoch 53/100: 100%|██████████| 820/820 [00:13<00:00, 61.09it/s, bpr=0.0274, c=2.68, loss=0.135]

[VAL]
recall@1=0.455831  recall@2=0.662349  recall@5=0.885948  recall@10=0.944661  recall@20=0.982624
precision@1=0.560726  precision@2=0.426371  precision@5=0.240452  precision@10=0.130718  precision@20=0.068472
ndcg@1=0.560726  ndcg@2=0.635245  ndcg@5=0.735089  ndcg@10=0.757126  ndcg@20=0.768088
hit_rate@1=0.560726  hit_rate@2=0.751371  hit_rate@5=0.927419  hit_rate@10=0.963306  hit_rate@20=0.990323
map@1=0.560726  map@2=0.600161  map@5=0.668116  map@10=0.681214  map@20=0.685362
mrr@1=0.560726  mrr@2=0.656048  mrr@5=0.707028  mrr@10=0.711944  mrr@20=0.713984
f1@1=0.486764  f1@2=0.498680  f1@5=0.364566  f1@10=0.223466  f1@20=0.125758

[TEST]
recall@1=0.458899  recall@2=0.660884  recall@5=0.886818  recall@10=0.946626  recall@20=0.983876
precision@1=0.564030  precision@2=0.426466  precision@5=0.240706  precision@10=0.130871  precision@20=0.068444
ndcg@1=0.564030  ndcg@2=0.635695  ndcg@5=0.736754  ndcg@10=0.759122  ndcg@20=0.769862
hit_rate@1=0.564030  hit_rate@2=0.748550  hit_rate@5=0.927030  hit_rate@10=0.964884  hit_rate@20=0.990899
map@1=0.564030  map@2=0.601683  map@5=0.670520  map@10=0.683547  map@20=0.687656
mrr@1=0.564030  mrr@2=0.656290  mrr@5=0.708003  mrr@10=0.713240  mrr@20=0.715214
f1@1=0.490016  f1@2=0.498314  f1@5=0.365138  f1@10=0.223870  f1@20=0.125787

Epoch 54/100: 100%|██████████| 820/820 [00:13<00:00, 60.88it/s, bpr=0.034, c=2.69, loss=0.141]

[VAL]
recall@1=0.453055  recall@2=0.658774  recall@5=0.882101  recall@10=0.946530  recall@20=0.982029
precision@1=0.556452  precision@2=0.423831  precision@5=0.239258  precision@10=0.130960  precision@20=0.068391
ndcg@1=0.556452  ndcg@2=0.631401  ndcg@5=0.731080  ndcg@10=0.755223  ndcg@20=0.765466
hit_rate@1=0.556452  hit_rate@2=0.746613  hit_rate@5=0.924435  hit_rate@10=0.964919  hit_rate@20=0.990161
map@1=0.556452  map@2=0.596633  map@5=0.664077  map@10=0.678279  map@20=0.682145
mrr@1=0.556452  mrr@2=0.651532  mrr@5=0.702946  mrr@10=0.708503  mrr@20=0.710406
f1@1=0.483577  f1@2=0.495897  f1@5=0.362849  f1@10=0.223889  f1@20=0.125638

[TEST]
recall@1=0.453596  recall@2=0.656320  recall@5=0.884618  recall@10=0.948692  recall@20=0.984379
precision@1=0.557668  precision@2=0.423446  precision@5=0.239948  precision@10=0.131202  precision@20=0.068496
ndcg@1=0.557668  ndcg@2=0.630537  ndcg@5=0.732382  ndcg@10=0.756277  ndcg@20=0.766508
hit_rate@1=0.557668  hit_rate@2=0.743637  hit_rate@5=0.926466  hit_rate@10=0.966253  hit_rate@20=0.991382
map@1=0.557668  map@2=0.596468  map@5=0.665327  map@10=0.679249  map@20=0.683124
mrr@1=0.557668  mrr@2=0.650652  mrr@5=0.703081  mrr@10=0.708538  mrr@20=0.710414
f1@1=0.484299  f1@2=0.494823  f1@5=0.364030  f1@10=0.224380  f1@20=0.125865

Epoch 55/100: 100%|██████████| 820/820 [00:13<00:00, 60.63it/s, bpr=0.0436, c=2.57, loss=0.146]

[VAL]
recall@1=0.447145  recall@2=0.655707  recall@5=0.879594  recall@10=0.942532  recall@20=0.980716
precision@1=0.550323  precision@2=0.422500  precision@5=0.238726  precision@10=0.130379  precision@20=0.068294
ndcg@1=0.550323  ndcg@2=0.627454  ndcg@5=0.727466  ndcg@10=0.750862  ndcg@20=0.761931
hit_rate@1=0.550323  hit_rate@2=0.744032  hit_rate@5=0.921855  hit_rate@10=0.961935  hit_rate@20=0.988952
map@1=0.550323  map@2=0.592278  map@5=0.660155  map@10=0.673738  map@20=0.677934
mrr@1=0.550323  mrr@2=0.647177  mrr@5=0.698663  mrr@10=0.704086  mrr@20=0.706185
f1@1=0.477552  f1@2=0.493901  f1@5=0.361939  f1@10=0.222895  f1@20=0.125461

[TEST]
recall@1=0.455246  recall@2=0.654627  recall@5=0.879919  recall@10=0.944991  recall@20=0.984034
precision@1=0.560728  precision@2=0.423486  precision@5=0.239014  precision@10=0.130614  precision@20=0.068472
ndcg@1=0.560728  ndcg@2=0.630567  ndcg@5=0.731061  ndcg@10=0.755000  ndcg@20=0.766270
hit_rate@1=0.560728  hit_rate@2=0.741221  hit_rate@5=0.921231  hit_rate@10=0.963918  hit_rate@20=0.991060
map@1=0.560728  map@2=0.597233  map@5=0.665182  map@10=0.678798  map@20=0.683104
mrr@1=0.560728  mrr@2=0.650975  mrr@5=0.703034  mrr@10=0.708807  mrr@20=0.710875
f1@1=0.486330  f1@2=0.494212  f1@5=0.362438  f1@10=0.223437  f1@20=0.125817

Epoch 56/100: 100%|██████████| 820/820 [00:13<00:00, 60.81it/s, bpr=0.0224, c=2.67, loss=0.129]

[VAL]
recall@1=0.445917  recall@2=0.657798  recall@5=0.881731  recall@10=0.945330  recall@20=0.982348
precision@1=0.549677  precision@2=0.423266  precision@5=0.239403  precision@10=0.130823  precision@20=0.068440
ndcg@1=0.549677  ndcg@2=0.628210  ndcg@5=0.728602  ndcg@10=0.752299  ndcg@20=0.762926
hit_rate@1=0.549677  hit_rate@2=0.746532  hit_rate@5=0.923468  hit_rate@10=0.964113  hit_rate@20=0.990565
map@1=0.549677  map@2=0.592399  map@5=0.660864  map@10=0.674691  map@20=0.678680
mrr@1=0.549677  mrr@2=0.648105  mrr@5=0.699413  mrr@10=0.704952  mrr@20=0.706917
f1@1=0.476496  f1@2=0.495199  f1@5=0.362870  f1@10=0.223615  f1@20=0.125696

[TEST]
recall@1=0.450826  recall@2=0.659395  recall@5=0.884041  recall@10=0.947476  recall@20=0.983353
precision@1=0.555171  precision@2=0.425660  precision@5=0.240013  precision@10=0.131008  precision@20=0.068412
ndcg@1=0.555171  ndcg@2=0.631837  ndcg@5=0.732056  ndcg@10=0.755577  ndcg@20=0.765879
hit_rate@1=0.555171  hit_rate@2=0.747584  hit_rate@5=0.925660  hit_rate@10=0.965609  hit_rate@20=0.990899
map@1=0.555171  map@2=0.596952  map@5=0.665019  map@10=0.678647  map@20=0.682552
mrr@1=0.555171  mrr@2=0.651377  mrr@5=0.702742  mrr@10=0.708167  mrr@20=0.710055
f1@1=0.481536  f1@2=0.497222  f1@5=0.364041  f1@10=0.224074  f1@20=0.125710

Epoch 57/100: 100%|██████████| 820/820 [00:13<00:00, 61.01it/s, bpr=0.0175, c=2.73, loss=0.127]

[VAL]
recall@1=0.449664  recall@2=0.659745  recall@5=0.883337  recall@10=0.940742  recall@20=0.981551
precision@1=0.553871  precision@2=0.424315  precision@5=0.239871  precision@10=0.130226  precision@20=0.068343
ndcg@1=0.553871  ndcg@2=0.630708  ndcg@5=0.731247  ndcg@10=0.752867  ndcg@20=0.764607
hit_rate@1=0.553871  hit_rate@2=0.748226  hit_rate@5=0.925403  hit_rate@10=0.960081  hit_rate@20=0.989839
map@1=0.553871  map@2=0.595121  map@5=0.663809  map@10=0.676685  map@20=0.681093
mrr@1=0.553871  mrr@2=0.651048  mrr@5=0.702597  mrr@10=0.707402  mrr@20=0.709688
f1@1=0.480487  f1@2=0.496594  f1@5=0.363615  f1@10=0.222601  f1@20=0.125540

[TEST]
recall@1=0.451897  recall@2=0.657565  recall@5=0.885255  recall@10=0.942916  recall@20=0.983537
precision@1=0.556379  precision@2=0.424332  precision@5=0.240287  precision@10=0.130493  precision@20=0.068428
ndcg@1=0.556379  ndcg@2=0.630857  ndcg@5=0.733075  ndcg@10=0.754665  ndcg@20=0.766308
hit_rate@1=0.556379  hit_rate@2=0.745248  hit_rate@5=0.926305  hit_rate@10=0.961501  hit_rate@20=0.990979
map@1=0.556379  map@2=0.596327  map@5=0.666123  map@10=0.678810  map@20=0.683175
mrr@1=0.556379  mrr@2=0.650813  mrr@5=0.703375  mrr@10=0.708220  mrr@20=0.710473
f1@1=0.482736  f1@2=0.495764  f1@5=0.364469  f1@10=0.223170  f1@20=0.125737

Epoch 58/100: 100%|██████████| 820/820 [00:13<00:00, 60.50it/s, bpr=0.0189, c=2.69, loss=0.127]

[VAL]
recall@1=0.457328  recall@2=0.668496  recall@5=0.887979  recall@10=0.943095  recall@20=0.981664
precision@1=0.562339  precision@2=0.429194  precision@5=0.241306  precision@10=0.130540  precision@20=0.068399
ndcg@1=0.562339  ndcg@2=0.639486  ndcg@5=0.738073  ndcg@10=0.758738  ndcg@20=0.769837
hit_rate@1=0.562339  hit_rate@2=0.757903  hit_rate@5=0.927742  hit_rate@10=0.962419  hit_rate@20=0.989839
map@1=0.562339  map@2=0.603629  map@5=0.671589  map@10=0.683786  map@20=0.687962
mrr@1=0.562339  mrr@2=0.660121  mrr@5=0.709594  mrr@10=0.714351  mrr@20=0.716426
f1@1=0.488309  f1@2=0.502704  f1@5=0.365696  f1@10=0.223105  f1@20=0.125609

[TEST]
recall@1=0.459210  recall@2=0.667593  recall@5=0.889769  recall@10=0.944547  recall@20=0.983105
precision@1=0.564272  precision@2=0.430171  precision@5=0.241575  precision@10=0.130622  precision@20=0.068375
ndcg@1=0.564272  ndcg@2=0.640171  ndcg@5=0.739697  ndcg@10=0.760204  ndcg@20=0.771290
hit_rate@1=0.564272  hit_rate@2=0.755638  hit_rate@5=0.929526  hit_rate@10=0.963112  hit_rate@20=0.990657
map@1=0.564272  map@2=0.605328  map@5=0.673589  map@10=0.685680  map@20=0.689890
mrr@1=0.564272  mrr@2=0.659955  mrr@5=0.710348  mrr@10=0.714911  mrr@20=0.716996
f1@1=0.490269  f1@2=0.503013  f1@5=0.366432  f1@10=0.223417  f1@20=0.125654

Epoch 59/100: 100%|██████████| 820/820 [00:13<00:00, 60.24it/s, bpr=0.0438, c=2.59, loss=0.147]

[VAL]
recall@1=0.438516  recall@2=0.651481  recall@5=0.878092  recall@10=0.946658  recall@20=0.982305
precision@1=0.540726  precision@2=0.419637  precision@5=0.238129  precision@10=0.130895  precision@20=0.068395
ndcg@1=0.540726  ndcg@2=0.621171  ndcg@5=0.722203  ndcg@10=0.747691  ndcg@20=0.757933
hit_rate@1=0.540726  hit_rate@2=0.740968  hit_rate@5=0.920323  hit_rate@10=0.965161  hit_rate@20=0.990484
map@1=0.540726  map@2=0.585020  map@5=0.653587  map@10=0.668266  map@20=0.672116
mrr@1=0.540726  mrr@2=0.640847  mrr@5=0.692276  mrr@10=0.698417  mrr@20=0.700294
f1@1=0.468660  f1@2=0.490660  f1@5=0.361163  f1@10=0.223820  f1@20=0.125643

[TEST]
recall@1=0.440911  recall@2=0.649958  recall@5=0.878528  recall@10=0.948890  recall@20=0.983222
precision@1=0.544781  precision@2=0.419378  precision@5=0.238483  precision@10=0.131186  precision@20=0.068432
ndcg@1=0.544781  ndcg@2=0.621493  ndcg@5=0.723800  ndcg@10=0.749776  ndcg@20=0.759682
hit_rate@1=0.544781  hit_rate@2=0.738805  hit_rate@5=0.920909  hit_rate@10=0.966736  hit_rate@20=0.990657
map@1=0.544781  map@2=0.586038  map@5=0.655587  map@10=0.670400  map@20=0.674212
mrr@1=0.544781  mrr@2=0.641793  mrr@5=0.694155  mrr@10=0.700450  mrr@20=0.702245
f1@1=0.471536  f1@2=0.490010  f1@5=0.361677  f1@10=0.224379  f1@20=0.125725

Epoch 60/100: 100%|██████████| 820/820 [00:13<00:00, 60.01it/s, bpr=0.057, c=2.51, loss=0.157]

[VAL]
recall@1=0.449018  recall@2=0.656823  recall@5=0.882057  recall@10=0.948326  recall@20=0.982377
precision@1=0.553387  precision@2=0.422823  precision@5=0.239355  precision@10=0.131153  precision@20=0.068440
ndcg@1=0.553387  ndcg@2=0.628784  ndcg@5=0.729532  ndcg@10=0.754204  ndcg@20=0.764031
hit_rate@1=0.553387  hit_rate@2=0.745726  hit_rate@5=0.923790  hit_rate@10=0.966855  hit_rate@20=0.990403
map@1=0.553387  map@2=0.593407  map@5=0.661905  map@10=0.676229  map@20=0.679961
mrr@1=0.553387  mrr@2=0.649556  mrr@5=0.701125  mrr@10=0.707022  mrr@20=0.708757
f1@1=0.479831  f1@2=0.494556  f1@5=0.362949  f1@10=0.224216  f1@20=0.125707

[TEST]
recall@1=0.451819  recall@2=0.659540  recall@5=0.884514  recall@10=0.950152  recall@20=0.983792
precision@1=0.557023  precision@2=0.425862  precision@5=0.240110  precision@10=0.131355  precision@20=0.068428
ndcg@1=0.557023  ndcg@2=0.632447  ndcg@5=0.732501  ndcg@10=0.756841  ndcg@20=0.766518
hit_rate@1=0.557023  hit_rate@2=0.747262  hit_rate@5=0.925499  hit_rate@10=0.967864  hit_rate@20=0.991221
map@1=0.557023  map@2=0.597757  map@5=0.665444  map@10=0.679467  map@20=0.683155
mrr@1=0.557023  mrr@2=0.652142  mrr@5=0.703393  mrr@10=0.709228  mrr@20=0.710964
f1@1=0.482798  f1@2=0.497383  f1@5=0.364175  f1@10=0.224694  f1@20=0.125760

Epoch 61/100: 100%|██████████| 820/820 [00:13<00:00, 60.72it/s, bpr=0.0208, c=2.7, loss=0.129]

[VAL]
recall@1=0.458165  recall@2=0.662155  recall@5=0.884669  recall@10=0.944283  recall@20=0.982033
precision@1=0.562742  precision@2=0.426129  precision@5=0.240065  precision@10=0.130694  precision@20=0.068379
ndcg@1=0.562742  ndcg@2=0.635883  ndcg@5=0.735004  ndcg@10=0.757451  ndcg@20=0.768295
hit_rate@1=0.562742  hit_rate@2=0.750242  hit_rate@5=0.926694  hit_rate@10=0.962903  hit_rate@20=0.990484
map@1=0.562742  map@2=0.601351  map@5=0.668409  map@10=0.681833  map@20=0.685904
mrr@1=0.562742  mrr@2=0.656492  mrr@5=0.707243  mrr@10=0.712254  mrr@20=0.714332
f1@1=0.489004  f1@2=0.498458  f1@5=0.363958  f1@10=0.223423  f1@20=0.125613

[TEST]
recall@1=0.459131  recall@2=0.663056  recall@5=0.888072  recall@10=0.946012  recall@20=0.984288
precision@1=0.563628  precision@2=0.426667  precision@5=0.240802  precision@10=0.130936  precision@20=0.068476
ndcg@1=0.563628  ndcg@2=0.636594  ndcg@5=0.737224  ndcg@10=0.759130  ndcg@20=0.770066
hit_rate@1=0.563628  hit_rate@2=0.749436  hit_rate@5=0.929607  hit_rate@10=0.964159  hit_rate@20=0.991624
map@1=0.563628  map@2=0.602509  map@5=0.670690  map@10=0.683778  map@20=0.687879
mrr@1=0.563628  mrr@2=0.656532  mrr@5=0.708268  mrr@10=0.713077  mrr@20=0.715149
f1@1=0.490012  f1@2=0.499313  f1@5=0.365361  f1@10=0.223875  f1@20=0.125831

Epoch 62/100: 100%|██████████| 820/820 [00:13<00:00, 60.53it/s, bpr=0.0382, c=2.54, loss=0.14]

[VAL]
recall@1=0.448809  recall@2=0.659990  recall@5=0.883174  recall@10=0.943952  recall@20=0.982124
precision@1=0.552984  precision@2=0.425000  precision@5=0.239677  precision@10=0.130653  precision@20=0.068379
ndcg@1=0.552984  ndcg@2=0.630960  ndcg@5=0.730641  ndcg@10=0.753452  ndcg@20=0.764388
hit_rate@1=0.552984  hit_rate@2=0.749032  hit_rate@5=0.925161  hit_rate@10=0.962903  hit_rate@20=0.990242
map@1=0.552984  map@2=0.595262  map@5=0.663100  map@10=0.676573  map@20=0.680689
mrr@1=0.552984  mrr@2=0.651008  mrr@5=0.701902  mrr@10=0.707067  mrr@20=0.709109
f1@1=0.479535  f1@2=0.497040  f1@5=0.363443  f1@10=0.223327  f1@20=0.125614

[TEST]
recall@1=0.455577  recall@2=0.658237  recall@5=0.883307  recall@10=0.946645  recall@20=0.982883
precision@1=0.560164  precision@2=0.424493  precision@5=0.239659  precision@10=0.130928  precision@20=0.068388
ndcg@1=0.560164  ndcg@2=0.632444  ndcg@5=0.733144  ndcg@10=0.756815  ndcg@20=0.767231
hit_rate@1=0.560164  hit_rate@2=0.746859  hit_rate@5=0.924613  hit_rate@10=0.964642  hit_rate@20=0.990335
map@1=0.560164  map@2=0.597978  map@5=0.666720  map@10=0.680502  map@20=0.684456
mrr@1=0.560164  mrr@2=0.653512  mrr@5=0.704686  mrr@10=0.710228  mrr@20=0.712153
f1@1=0.486551  f1@2=0.496140  f1@5=0.363553  f1@10=0.223918  f1@20=0.125669

Epoch 63/100: 100%|██████████| 820/820 [00:13<00:00, 61.02it/s, bpr=0.0152, c=2.8, loss=0.127]

[VAL]
recall@1=0.446944  recall@2=0.661526  recall@5=0.881682  recall@10=0.943484  recall@20=0.982344
precision@1=0.551290  precision@2=0.425927  precision@5=0.239419  precision@10=0.130532  precision@20=0.068431
ndcg@1=0.551290  ndcg@2=0.631466  ndcg@5=0.729722  ndcg@10=0.752690  ndcg@20=0.763896
hit_rate@1=0.551290  hit_rate@2=0.751855  hit_rate@5=0.923548  hit_rate@10=0.962823  hit_rate@20=0.990161
map@1=0.551290  map@2=0.595060  map@5=0.662318  map@10=0.675664  map@20=0.679918
mrr@1=0.551290  mrr@2=0.651573  mrr@5=0.701198  mrr@10=0.706506  mrr@20=0.708575
f1@1=0.477668  f1@2=0.498093  f1@5=0.362926  f1@10=0.223153  f1@20=0.125702

[TEST]
recall@1=0.451322  recall@2=0.660878  recall@5=0.881683  recall@10=0.946288  recall@20=0.983640
precision@1=0.557829  precision@2=0.426707  precision@5=0.239594  precision@10=0.130880  precision@20=0.068428
ndcg@1=0.557829  ndcg@2=0.633320  ndcg@5=0.731636  ndcg@10=0.755471  ndcg@20=0.766205
hit_rate@1=0.557829  hit_rate@2=0.749597  hit_rate@5=0.922519  hit_rate@10=0.964803  hit_rate@20=0.990979
map@1=0.557829  map@2=0.598099  map@5=0.665220  map@10=0.678772  map@20=0.682862
mrr@1=0.557829  mrr@2=0.653713  mrr@5=0.703416  mrr@10=0.709195  mrr@20=0.711168
f1@1=0.482686  f1@2=0.498373  f1@5=0.363219  f1@10=0.223824  f1@20=0.125745

Epoch 64/100: 100%|██████████| 820/820 [00:13<00:00, 60.85it/s, bpr=0.0411, c=2.55, loss=0.143]

[VAL]
recall@1=0.450324  recall@2=0.658823  recall@5=0.882412  recall@10=0.947774  recall@20=0.981862
precision@1=0.554032  precision@2=0.424153  precision@5=0.239371  precision@10=0.131153  precision@20=0.068383
ndcg@1=0.554032  ndcg@2=0.630833  ndcg@5=0.730504  ndcg@10=0.754807  ndcg@20=0.764597
hit_rate@1=0.554032  hit_rate@2=0.746694  hit_rate@5=0.923790  hit_rate@10=0.966129  hit_rate@20=0.990000
map@1=0.554032  map@2=0.595786  map@5=0.663348  map@10=0.677446  map@20=0.681122
mrr@1=0.554032  mrr@2=0.650363  mrr@5=0.701612  mrr@10=0.707312  mrr@20=0.709079
f1@1=0.480861  f1@2=0.495964  f1@5=0.363002  f1@10=0.224161  f1@20=0.125615

[TEST]
recall@1=0.452658  recall@2=0.659497  recall@5=0.883917  recall@10=0.948968  recall@20=0.983779
precision@1=0.555976  precision@2=0.425499  precision@5=0.239852  precision@10=0.131186  precision@20=0.068432
ndcg@1=0.555976  ndcg@2=0.632186  ndcg@5=0.732516  ndcg@10=0.756635  ndcg@20=0.766636
hit_rate@1=0.555976  hit_rate@2=0.746617  hit_rate@5=0.925177  hit_rate@10=0.966736  hit_rate@20=0.991140
map@1=0.555976  map@2=0.597757  map@5=0.665853  map@10=0.679804  map@20=0.683601
mrr@1=0.555976  mrr@2=0.651297  mrr@5=0.702818  mrr@10=0.708495  mrr@20=0.710310
f1@1=0.483168  f1@2=0.497272  f1@5=0.363847  f1@10=0.224399  f1@20=0.125755

Epoch 65/100: 100%|██████████| 820/820 [00:13<00:00, 60.43it/s, bpr=0.0393, c=2.66, loss=0.146]

[VAL]
recall@1=0.451145  recall@2=0.659846  recall@5=0.879600  recall@10=0.944275  recall@20=0.982325
precision@1=0.556129  precision@2=0.425081  precision@5=0.238790  precision@10=0.130589  precision@20=0.068407
ndcg@1=0.556129  ndcg@2=0.631941  ndcg@5=0.730011  ndcg@10=0.754027  ndcg@20=0.765010
hit_rate@1=0.556129  hit_rate@2=0.749516  hit_rate@5=0.921048  hit_rate@10=0.963468  hit_rate@20=0.990242
map@1=0.556129  map@2=0.596371  map@5=0.663411  map@10=0.677233  map@20=0.681413
mrr@1=0.556129  mrr@2=0.652823  mrr@5=0.702493  mrr@10=0.708304  mrr@20=0.710323
f1@1=0.482166  f1@2=0.496958  f1@5=0.362025  f1@10=0.223253  f1@20=0.125667

[TEST]
recall@1=0.451192  recall@2=0.659291  recall@5=0.882051  recall@10=0.946791  recall@20=0.983540
precision@1=0.557184  precision@2=0.425902  precision@5=0.239594  precision@10=0.130823  precision@20=0.068428
ndcg@1=0.557184  ndcg@2=0.632032  ndcg@5=0.731327  ndcg@10=0.755165  ndcg@20=0.765781
hit_rate@1=0.557184  hit_rate@2=0.748470  hit_rate@5=0.922439  hit_rate@10=0.965206  hit_rate@20=0.990899
map@1=0.557184  map@2=0.596891  map@5=0.664793  map@10=0.678324  map@20=0.682382
mrr@1=0.557184  mrr@2=0.652827  mrr@5=0.702670  mrr@10=0.708499  mrr@20=0.710438
f1@1=0.482443  f1@2=0.497427  f1@5=0.363299  f1@10=0.223803  f1@20=0.125740

Epoch 66/100: 100%|██████████| 820/820 [00:13<00:00, 60.56it/s, bpr=0.0272, c=2.56, loss=0.13]

[VAL]
recall@1=0.449303  recall@2=0.661228  recall@5=0.883657  recall@10=0.943345  recall@20=0.982027
precision@1=0.553306  precision@2=0.425403  precision@5=0.239968  precision@10=0.130468  precision@20=0.068415
ndcg@1=0.553306  ndcg@2=0.631823  ndcg@5=0.731271  ndcg@10=0.753577  ndcg@20=0.764755
hit_rate@1=0.553306  hit_rate@2=0.749919  hit_rate@5=0.923871  hit_rate@10=0.962984  hit_rate@20=0.989919
map@1=0.553306  map@2=0.596089  map@5=0.663981  map@10=0.676972  map@20=0.681232
mrr@1=0.553306  mrr@2=0.651613  mrr@5=0.701935  mrr@10=0.707296  mrr@20=0.709326
f1@1=0.479959  f1@2=0.497722  f1@5=0.363793  f1@10=0.223061  f1@20=0.125670

[TEST]
recall@1=0.451165  recall@2=0.658889  recall@5=0.885208  recall@10=0.945336  recall@20=0.984201
precision@1=0.555976  precision@2=0.426063  precision@5=0.240528  precision@10=0.130710  precision@20=0.068448
ndcg@1=0.555976  ndcg@2=0.631982  ndcg@5=0.732733  ndcg@10=0.754978  ndcg@20=0.766103
hit_rate@1=0.555976  hit_rate@2=0.746698  hit_rate@5=0.925580  hit_rate@10=0.964079  hit_rate@20=0.991543
map@1=0.555976  map@2=0.597394  map@5=0.665787  map@10=0.678596  map@20=0.682799
mrr@1=0.555976  mrr@2=0.651337  mrr@5=0.702799  mrr@10=0.708025  mrr@20=0.710094
f1@1=0.482050  f1@2=0.497229  f1@5=0.364701  f1@10=0.223572  f1@20=0.125781

Epoch 67/100: 100%|██████████| 820/820 [00:13<00:00, 60.38it/s, bpr=0.0298, c=2.46, loss=0.128]

[VAL]
recall@1=0.457551  recall@2=0.666687  recall@5=0.886074  recall@10=0.947364  recall@20=0.982726
precision@1=0.561290  precision@2=0.428468  precision@5=0.240452  precision@10=0.131089  precision@20=0.068460
ndcg@1=0.561290  ndcg@2=0.638413  ndcg@5=0.736538  ndcg@10=0.759547  ndcg@20=0.769719
hit_rate@1=0.561290  hit_rate@2=0.755323  hit_rate@5=0.927258  hit_rate@10=0.965887  hit_rate@20=0.990726
map@1=0.561290  map@2=0.603165  map@5=0.670225  map@10=0.683737  map@20=0.687584
mrr@1=0.561290  mrr@2=0.658306  mrr@5=0.708187  mrr@10=0.713520  mrr@20=0.715376
f1@1=0.488122  f1@2=0.501604  f1@5=0.364556  f1@10=0.224090  f1@20=0.125749

[TEST]
recall@1=0.461012  recall@2=0.666853  recall@5=0.889968  recall@10=0.950147  recall@20=0.984467
precision@1=0.566124  precision@2=0.430090  precision@5=0.241463  precision@10=0.131371  precision@20=0.068464
ndcg@1=0.566124  ndcg@2=0.640435  ndcg@5=0.739952  ndcg@10=0.762462  ndcg@20=0.772286
hit_rate@1=0.566124  hit_rate@2=0.755235  hit_rate@5=0.930412  hit_rate@10=0.967381  hit_rate@20=0.991463
map@1=0.566124  map@2=0.605892  map@5=0.673811  map@10=0.687004  map@20=0.690726
mrr@1=0.566124  mrr@2=0.660680  mrr@5=0.711019  mrr@10=0.716116  mrr@20=0.717911
f1@1=0.492084  f1@2=0.502689  f1@5=0.366329  f1@10=0.224718  f1@20=0.125817

Epoch 68/100: 100%|██████████| 820/820 [00:13<00:00, 60.34it/s, bpr=0.0209, c=2.69, loss=0.129]

[VAL]
recall@1=0.447766  recall@2=0.656727  recall@5=0.877898  recall@10=0.944994  recall@20=0.981693
precision@1=0.552581  precision@2=0.423024  precision@5=0.238129  precision@10=0.130629  precision@20=0.068415
ndcg@1=0.552581  ndcg@2=0.628587  ndcg@5=0.727466  ndcg@10=0.752301  ndcg@20=0.762961
hit_rate@1=0.552581  hit_rate@2=0.747258  hit_rate@5=0.920242  hit_rate@10=0.964032  hit_rate@20=0.989677
map@1=0.552581  map@2=0.592681  map@5=0.660347  map@10=0.674607  map@20=0.678686
mrr@1=0.552581  mrr@2=0.649919  mrr@5=0.700183  mrr@10=0.706135  mrr@20=0.708070
f1@1=0.478698  f1@2=0.494519  f1@5=0.361101  f1@10=0.223355  f1@20=0.125647

[TEST]
recall@1=0.446244  recall@2=0.659386  recall@5=0.880201  recall@10=0.948083  recall@20=0.983872
precision@1=0.551144  precision@2=0.425781  precision@5=0.238966  precision@10=0.131008  precision@20=0.068424
ndcg@1=0.551144  ndcg@2=0.630147  ndcg@5=0.728662  ndcg@10=0.753613  ndcg@20=0.763909
hit_rate@1=0.551144  hit_rate@2=0.747825  hit_rate@5=0.922036  hit_rate@10=0.966092  hit_rate@20=0.991140
map@1=0.551144  map@2=0.594535  map@5=0.661669  map@10=0.675853  map@20=0.679755
mrr@1=0.551144  mrr@2=0.649485  mrr@5=0.699758  mrr@10=0.705717  mrr@20=0.707592
f1@1=0.477226  f1@2=0.497300  f1@5=0.362434  f1@10=0.224109  f1@20=0.125752

Epoch 69/100: 100%|██████████| 820/820 [00:13<00:00, 60.48it/s, bpr=0.0466, c=2.62, loss=0.152]

[VAL]
recall@1=0.451923  recall@2=0.652680  recall@5=0.882495  recall@10=0.944084  recall@20=0.982123
precision@1=0.555806  precision@2=0.420766  precision@5=0.239323  precision@10=0.130621  precision@20=0.068411
ndcg@1=0.555806  ndcg@2=0.627406  ndcg@5=0.729509  ndcg@10=0.752688  ndcg@20=0.763664
hit_rate@1=0.555806  hit_rate@2=0.740645  hit_rate@5=0.924919  hit_rate@10=0.962903  hit_rate@20=0.990323
map@1=0.555806  map@2=0.593226  map@5=0.661890  map@10=0.675620  map@20=0.679770
mrr@1=0.555806  mrr@2=0.648226  mrr@5=0.700950  mrr@10=0.706192  mrr@20=0.708273
f1@1=0.482582  f1@2=0.491675  f1@5=0.362936  f1@10=0.223314  f1@20=0.125657

[TEST]
recall@1=0.450179  recall@2=0.652284  recall@5=0.885078  recall@10=0.947558  recall@20=0.983998
precision@1=0.553157  precision@2=0.421593  precision@5=0.240110  precision@10=0.131097  precision@20=0.068428
ndcg@1=0.553157  ndcg@2=0.626690  ndcg@5=0.730340  ndcg@10=0.753710  ndcg@20=0.764131
hit_rate@1=0.553157  hit_rate@2=0.739771  hit_rate@5=0.925902  hit_rate@10=0.965448  hit_rate@20=0.991302
map@1=0.553157  map@2=0.592743  map@5=0.662720  map@10=0.676302  map@20=0.680242
mrr@1=0.553157  mrr@2=0.646464  mrr@5=0.699754  mrr@10=0.705207  mrr@20=0.707145
f1@1=0.480601  f1@2=0.492160  f1@5=0.364284  f1@10=0.224182  f1@20=0.125764

Epoch 70/100: 100%|██████████| 820/820 [00:13<00:00, 60.56it/s, bpr=0.0415, c=2.72, loss=0.15]

[VAL]
recall@1=0.452162  recall@2=0.661797  recall@5=0.883439  recall@10=0.945355  recall@20=0.982112
precision@1=0.557419  precision@2=0.425323  precision@5=0.239629  precision@10=0.130806  precision@20=0.068407
ndcg@1=0.557419  ndcg@2=0.633267  ndcg@5=0.732500  ndcg@10=0.755718  ndcg@20=0.766265
hit_rate@1=0.557419  hit_rate@2=0.750806  hit_rate@5=0.925484  hit_rate@10=0.964274  hit_rate@20=0.990242
map@1=0.557419  map@2=0.597581  map@5=0.665316  map@10=0.678963  map@20=0.682927
mrr@1=0.557419  mrr@2=0.654113  mrr@5=0.704759  mrr@10=0.710092  mrr@20=0.712025
f1@1=0.483216  f1@2=0.497842  f1@5=0.363376  f1@10=0.223589  f1@20=0.125644

[TEST]
recall@1=0.449324  recall@2=0.659437  recall@5=0.885127  recall@10=0.948065  recall@20=0.983017
precision@1=0.552996  precision@2=0.425056  precision@5=0.240061  precision@10=0.131129  precision@20=0.068351
ndcg@1=0.552996  ndcg@2=0.630828  ndcg@5=0.732149  ndcg@10=0.755655  ndcg@20=0.765676
hit_rate@1=0.552996  hit_rate@2=0.747745  hit_rate@5=0.926063  hit_rate@10=0.965528  hit_rate@20=0.990496
map@1=0.552996  map@2=0.595562  map@5=0.664855  map@10=0.678539  map@20=0.682317
mrr@1=0.552996  mrr@2=0.650370  mrr@5=0.702095  mrr@10=0.707550  mrr@20=0.709436
f1@1=0.479941  f1@2=0.496949  f1@5=0.364219  f1@10=0.224279  f1@20=0.125626

Epoch 71/100: 100%|██████████| 820/820 [00:13<00:00, 60.63it/s, bpr=0.03, c=2.47, loss=0.129]

[VAL]
recall@1=0.448908  recall@2=0.653285  recall@5=0.881363  recall@10=0.945156  recall@20=0.981644
precision@1=0.552984  precision@2=0.420927  precision@5=0.239177  precision@10=0.130742  precision@20=0.068379
ndcg@1=0.552984  ndcg@2=0.626576  ndcg@5=0.728524  ndcg@10=0.752274  ndcg@20=0.762796
hit_rate@1=0.552984  hit_rate@2=0.741935  hit_rate@5=0.923629  hit_rate@10=0.963952  hit_rate@20=0.989758
map@1=0.552984  map@2=0.591734  map@5=0.660841  map@10=0.674692  map@20=0.678672
mrr@1=0.552984  mrr@2=0.647460  mrr@5=0.699919  mrr@10=0.705408  mrr@20=0.707352
f1@1=0.479570  f1@2=0.492058  f1@5=0.362625  f1@10=0.223514  f1@20=0.125601

[TEST]
recall@1=0.452817  recall@2=0.656206  recall@5=0.884417  recall@10=0.947259  recall@20=0.983772
precision@1=0.557426  precision@2=0.423083  precision@5=0.240174  precision@10=0.131000  precision@20=0.068440
ndcg@1=0.557426  ndcg@2=0.629992  ndcg@5=0.732139  ndcg@10=0.755431  ndcg@20=0.765900
hit_rate@1=0.557426  hit_rate@2=0.743879  hit_rate@5=0.925338  hit_rate@10=0.965448  hit_rate@20=0.991302
map@1=0.557426  map@2=0.595602  map@5=0.665027  map@10=0.678463  map@20=0.682429
mrr@1=0.557426  mrr@2=0.650652  mrr@5=0.702873  mrr@10=0.708335  mrr@20=0.710271
f1@1=0.483754  f1@2=0.494569  f1@5=0.364239  f1@10=0.224048  f1@20=0.125763

Epoch 72/100: 100%|██████████| 820/820 [00:13<00:00, 60.46it/s, bpr=0.0314, c=2.73, loss=0.141]

[VAL]
recall@1=0.454911  recall@2=0.661758  recall@5=0.878857  recall@10=0.943680  recall@20=0.981424
precision@1=0.559516  precision@2=0.426048  precision@5=0.238726  precision@10=0.130548  precision@20=0.068359
ndcg@1=0.559516  ndcg@2=0.634484  ndcg@5=0.731221  ndcg@10=0.755228  ndcg@20=0.766155
hit_rate@1=0.559516  hit_rate@2=0.750323  hit_rate@5=0.920726  hit_rate@10=0.963065  hit_rate@20=0.989677
map@1=0.559516  map@2=0.599496  map@5=0.665392  map@10=0.679191  map@20=0.683360
mrr@1=0.559516  mrr@2=0.654919  mrr@5=0.704222  mrr@10=0.709967  mrr@20=0.711996
f1@1=0.485724  f1@2=0.498275  f1@5=0.361829  f1@10=0.223163  f1@20=0.125567

[TEST]
recall@1=0.457636  recall@2=0.660518  recall@5=0.881349  recall@10=0.946152  recall@20=0.982525
precision@1=0.562097  precision@2=0.426707  precision@5=0.239401  precision@10=0.130831  precision@20=0.068380
ndcg@1=0.562097  ndcg@2=0.635174  ndcg@5=0.733635  ndcg@10=0.757529  ndcg@20=0.768042
hit_rate@1=0.562097  hit_rate@2=0.748792  hit_rate@5=0.922117  hit_rate@10=0.964079  hit_rate@20=0.990013
map@1=0.562097  map@2=0.601079  map@5=0.668258  map@10=0.681901  map@20=0.685914
mrr@1=0.562097  mrr@2=0.655445  mrr@5=0.705395  mrr@10=0.711097  mrr@20=0.713089
f1@1=0.488446  f1@2=0.498303  f1@5=0.363005  f1@10=0.223753  f1@20=0.125644

Epoch 73/100: 100%|██████████| 820/820 [00:13<00:00, 60.68it/s, bpr=0.0422, c=2.49, loss=0.142]

[VAL]
recall@1=0.444181  recall@2=0.650946  recall@5=0.878095  recall@10=0.948576  recall@20=0.982650
precision@1=0.545887  precision@2=0.418468  precision@5=0.238339  precision@10=0.131177  precision@20=0.068435
ndcg@1=0.545887  ndcg@2=0.622593  ndcg@5=0.724826  ndcg@10=0.750864  ndcg@20=0.760676
hit_rate@1=0.545887  hit_rate@2=0.739274  hit_rate@5=0.920806  hit_rate@10=0.967177  hit_rate@20=0.990645
map@1=0.545887  map@2=0.587379  map@5=0.657070  map@10=0.671992  map@20=0.675701
mrr@1=0.545887  mrr@2=0.642581  mrr@5=0.695409  mrr@10=0.701705  mrr@20=0.703429
f1@1=0.474157  f1@2=0.489685  f1@5=0.361293  f1@10=0.224267  f1@20=0.125710

[TEST]
recall@1=0.448510  recall@2=0.654892  recall@5=0.881276  recall@10=0.951173  recall@20=0.983730
precision@1=0.552513  precision@2=0.422680  precision@5=0.238998  precision@10=0.131476  precision@20=0.068440
ndcg@1=0.552513  ndcg@2=0.627724  ndcg@5=0.728863  ndcg@10=0.754670  ndcg@20=0.764022
hit_rate@1=0.552513  hit_rate@2=0.742832  hit_rate@5=0.923727  hit_rate@10=0.968669  hit_rate@20=0.990979
map@1=0.552513  map@2=0.593025  map@5=0.661531  map@10=0.676312  map@20=0.679879
mrr@1=0.552513  mrr@2=0.647672  mrr@5=0.699875  mrr@10=0.705963  mrr@20=0.707614
f1@1=0.479150  f1@2=0.493811  f1@5=0.362598  f1@10=0.224878  f1@20=0.125764

Epoch 74/100: 100%|██████████| 820/820 [00:13<00:00, 60.33it/s, bpr=0.0448, c=2.6, loss=0.149]

[VAL]
recall@1=0.441538  recall@2=0.656614  recall@5=0.882194  recall@10=0.945158  recall@20=0.982210
precision@1=0.543710  precision@2=0.423065  precision@5=0.239226  precision@10=0.130790  precision@20=0.068395
ndcg@1=0.543710  ndcg@2=0.625954  ndcg@5=0.726623  ndcg@10=0.750165  ndcg@20=0.760832
hit_rate@1=0.543710  hit_rate@2=0.745242  hit_rate@5=0.924274  hit_rate@10=0.964355  hit_rate@20=0.990484
map@1=0.543710  map@2=0.589960  map@5=0.658206  map@10=0.671987  map@20=0.676009
mrr@1=0.543710  mrr@2=0.644476  mrr@5=0.696277  mrr@10=0.701715  mrr@20=0.703681
f1@1=0.471596  f1@2=0.494549  f1@5=0.362815  f1@10=0.223573  f1@20=0.125645

[TEST]
recall@1=0.453264  recall@2=0.658520  recall@5=0.884515  recall@10=0.947489  recall@20=0.983511
precision@1=0.557909  precision@2=0.424734  precision@5=0.240013  precision@10=0.131057  precision@20=0.068432
ndcg@1=0.557909  ndcg@2=0.631841  ndcg@5=0.732977  ndcg@10=0.756431  ndcg@20=0.766758
hit_rate@1=0.557909  hit_rate@2=0.746778  hit_rate@5=0.925741  hit_rate@10=0.965206  hit_rate@20=0.990738
map@1=0.557909  map@2=0.597173  map@5=0.666055  map@10=0.679673  map@20=0.683589
mrr@1=0.557909  mrr@2=0.652344  mrr@5=0.704036  mrr@10=0.709444  mrr@20=0.711357
f1@1=0.484188  f1@2=0.496400  f1@5=0.364101  f1@10=0.224149  f1@20=0.125748

Epoch 75/100: 100%|██████████| 820/820 [00:13<00:00, 60.72it/s, bpr=0.0404, c=2.6, loss=0.144]

[VAL]
recall@1=0.448760  recall@2=0.661691  recall@5=0.884211  recall@10=0.947935  recall@20=0.981852
precision@1=0.551855  precision@2=0.425161  precision@5=0.239871  precision@10=0.131113  precision@20=0.068399
ndcg@1=0.551855  ndcg@2=0.631725  ndcg@5=0.731482  ndcg@10=0.755284  ndcg@20=0.765035
hit_rate@1=0.551855  hit_rate@2=0.749435  hit_rate@5=0.925645  hit_rate@10=0.966290  hit_rate@20=0.990081
map@1=0.551855  map@2=0.596048  map@5=0.663984  map@10=0.677914  map@20=0.681586
mrr@1=0.551855  mrr@2=0.650605  mrr@5=0.702019  mrr@10=0.707566  mrr@20=0.709283
f1@1=0.479149  f1@2=0.497648  f1@5=0.363733  f1@10=0.224148  f1@20=0.125640

[TEST]
recall@1=0.453668  recall@2=0.661065  recall@5=0.887182  recall@10=0.949810  recall@20=0.983631
precision@1=0.557668  precision@2=0.425499  precision@5=0.240673  precision@10=0.131459  precision@20=0.068484
ndcg@1=0.557668  ndcg@2=0.633352  ndcg@5=0.734964  ndcg@10=0.758312  ndcg@20=0.768006
hit_rate@1=0.557668  hit_rate@2=0.747745  hit_rate@5=0.927835  hit_rate@10=0.966817  hit_rate@20=0.990818
map@1=0.557668  map@2=0.598744  map@5=0.668053  map@10=0.681672  map@20=0.685327
mrr@1=0.557668  mrr@2=0.652746  mrr@5=0.704933  mrr@10=0.710246  mrr@20=0.712076
f1@1=0.484384  f1@2=0.497807  f1@5=0.365095  f1@10=0.224788  f1@20=0.125824

Epoch 76/100: 100%|██████████| 820/820 [00:13<00:00, 61.37it/s, bpr=0.0365, c=2.5, loss=0.137]

[VAL]
recall@1=0.450510  recall@2=0.661251  recall@5=0.881689  recall@10=0.944529  recall@20=0.982029
precision@1=0.555161  precision@2=0.425605  precision@5=0.239597  precision@10=0.130637  precision@20=0.068399
ndcg@1=0.555161  ndcg@2=0.632502  ndcg@5=0.731267  ndcg@10=0.754547  ndcg@20=0.765381
hit_rate@1=0.555161  hit_rate@2=0.751452  hit_rate@5=0.923226  hit_rate@10=0.963871  hit_rate@20=0.989839
map@1=0.555161  map@2=0.596552  map@5=0.664315  map@10=0.677755  map@20=0.681889
mrr@1=0.555161  mrr@2=0.653306  mrr@5=0.703306  mrr@10=0.708843  mrr@20=0.710809
f1@1=0.481344  f1@2=0.497783  f1@5=0.363127  f1@10=0.223325  f1@20=0.125643

[TEST]
recall@1=0.453075  recall@2=0.660394  recall@5=0.882929  recall@10=0.946253  recall@20=0.983751
precision@1=0.557506  precision@2=0.426426  precision@5=0.239820  precision@10=0.130831  precision@20=0.068440
ndcg@1=0.557506  ndcg@2=0.633348  ndcg@5=0.732941  ndcg@10=0.756319  ndcg@20=0.767137
hit_rate@1=0.557506  hit_rate@2=0.749436  hit_rate@5=0.923889  hit_rate@10=0.965045  hit_rate@20=0.990979
map@1=0.557506  map@2=0.598421  map@5=0.666722  map@10=0.680068  map@20=0.684216
mrr@1=0.557506  mrr@2=0.653471  mrr@5=0.704006  mrr@10=0.709573  mrr@20=0.711541
f1@1=0.483882  f1@2=0.498048  f1@5=0.363670  f1@10=0.223771  f1@20=0.125773

Epoch 77/100: 100%|██████████| 820/820 [00:13<00:00, 60.25it/s, bpr=0.0322, c=2.65, loss=0.138]

[VAL]
recall@1=0.446951  recall@2=0.661911  recall@5=0.882773  recall@10=0.948427  recall@20=0.982050
precision@1=0.550323  precision@2=0.425524  precision@5=0.239516  precision@10=0.131137  precision@20=0.068383
ndcg@1=0.550323  ndcg@2=0.631467  ndcg@5=0.730496  ndcg@10=0.754899  ndcg@20=0.764624
hit_rate@1=0.550323  hit_rate@2=0.751371  hit_rate@5=0.924355  hit_rate@10=0.966774  hit_rate@20=0.990081
map@1=0.550323  map@2=0.595181  map@5=0.662970  map@10=0.677131  map@20=0.680839
mrr@1=0.550323  mrr@2=0.650847  mrr@5=0.701487  mrr@10=0.707289  mrr@20=0.709024
f1@1=0.477340  f1@2=0.497898  f1@5=0.363194  f1@10=0.224212  f1@20=0.125623

[TEST]
recall@1=0.454922  recall@2=0.662356  recall@5=0.885904  recall@10=0.951387  recall@20=0.983466
precision@1=0.559681  precision@2=0.426909  precision@5=0.240383  precision@10=0.131508  precision@20=0.068380
ndcg@1=0.559681  ndcg@2=0.634955  ndcg@5=0.735496  ndcg@10=0.759722  ndcg@20=0.768928
hit_rate@1=0.559681  hit_rate@2=0.751691  hit_rate@5=0.927271  hit_rate@10=0.968750  hit_rate@20=0.990899
map@1=0.559681  map@2=0.599811  map@5=0.668910  map@10=0.682852  map@20=0.686338
mrr@1=0.559681  mrr@2=0.655686  mrr@5=0.706795  mrr@10=0.712420  mrr@20=0.714070
f1@1=0.485836  f1@2=0.499197  f1@5=0.364653  f1@10=0.224955  f1@20=0.125680

Epoch 78/100: 100%|██████████| 820/820 [00:13<00:00, 60.18it/s, bpr=0.0221, c=2.59, loss=0.126]

[VAL]
recall@1=0.455906  recall@2=0.662323  recall@5=0.878626  recall@10=0.946111  recall@20=0.982138
precision@1=0.561452  precision@2=0.426734  precision@5=0.238645  precision@10=0.130944  precision@20=0.068415
ndcg@1=0.561452  ndcg@2=0.635588  ndcg@5=0.731702  ndcg@10=0.756648  ndcg@20=0.766988
hit_rate@1=0.561452  hit_rate@2=0.751855  hit_rate@5=0.920887  hit_rate@10=0.964597  hit_rate@20=0.990161
map@1=0.561452  map@2=0.600464  map@5=0.665962  map@10=0.680235  map@20=0.684133
mrr@1=0.561452  mrr@2=0.656653  mrr@5=0.705517  mrr@10=0.711442  mrr@20=0.713343
f1@1=0.486966  f1@2=0.498797  f1@5=0.361702  f1@10=0.223823  f1@20=0.125670

[TEST]
recall@1=0.460391  recall@2=0.662411  recall@5=0.878265  recall@10=0.947970  recall@20=0.983141
precision@1=0.567010  precision@2=0.428520  precision@5=0.238740  precision@10=0.131105  precision@20=0.068412
ndcg@1=0.567010  ndcg@2=0.637991  ndcg@5=0.733730  ndcg@10=0.759312  ndcg@20=0.769429
hit_rate@1=0.567010  hit_rate@2=0.750564  hit_rate@5=0.919459  hit_rate@10=0.965689  hit_rate@20=0.990496
map@1=0.567010  map@2=0.604079  map@5=0.669227  map@10=0.683656  map@20=0.687504
mrr@1=0.567010  mrr@2=0.658787  mrr@5=0.707374  mrr@10=0.713663  mrr@20=0.715545
f1@1=0.491864  f1@2=0.500055  f1@5=0.361914  f1@10=0.224211  f1@20=0.125703

Epoch 79/100: 100%|██████████| 820/820 [00:13<00:00, 59.52it/s, bpr=0.0399, c=2.64, loss=0.146]

[VAL]
recall@1=0.453963  recall@2=0.663954  recall@5=0.884211  recall@10=0.946762  recall@20=0.981889
precision@1=0.559758  precision@2=0.427661  precision@5=0.240161  precision@10=0.130960  precision@20=0.068407
ndcg@1=0.559758  ndcg@2=0.636060  ndcg@5=0.734292  ndcg@10=0.757533  ndcg@20=0.767684
hit_rate@1=0.559758  hit_rate@2=0.753871  hit_rate@5=0.925081  hit_rate@10=0.965726  hit_rate@20=0.990000
map@1=0.559758  map@2=0.600403  map@5=0.667565  map@10=0.681033  map@20=0.684909
mrr@1=0.559758  mrr@2=0.656815  mrr@5=0.706616  mrr@10=0.712197  mrr@20=0.714007
f1@1=0.485041  f1@2=0.499922  f1@5=0.364006  f1@10=0.223866  f1@20=0.125651

[TEST]
recall@1=0.457568  recall@2=0.665939  recall@5=0.887587  recall@10=0.949348  recall@20=0.983510
precision@1=0.563869  precision@2=0.429446  precision@5=0.241237  precision@10=0.131339  precision@20=0.068428
ndcg@1=0.563869  ndcg@2=0.638617  ndcg@5=0.737769  ndcg@10=0.760627  ndcg@20=0.770421
hit_rate@1=0.563869  hit_rate@2=0.754027  hit_rate@5=0.927191  hit_rate@10=0.966575  hit_rate@20=0.990979
map@1=0.563869  map@2=0.603697  map@5=0.671717  map@10=0.684824  map@20=0.688520
mrr@1=0.563869  mrr@2=0.658948  mrr@5=0.708798  mrr@10=0.714200  mrr@20=0.716022
f1@1=0.489031  f1@2=0.502015  f1@5=0.365768  f1@10=0.224580  f1@20=0.125732

Epoch 80/100: 100%|██████████| 820/820 [00:13<00:00, 60.70it/s, bpr=0.0264, c=2.5, loss=0.126]

[VAL]
recall@1=0.454734  recall@2=0.663455  recall@5=0.880024  recall@10=0.944572  recall@20=0.981711
precision@1=0.560000  precision@2=0.427097  precision@5=0.239000  precision@10=0.130653  precision@20=0.068379
ndcg@1=0.560000  ndcg@2=0.635581  ndcg@5=0.732071  ndcg@10=0.755997  ndcg@20=0.766708
hit_rate@1=0.560000  hit_rate@2=0.752661  hit_rate@5=0.921613  hit_rate@10=0.963952  hit_rate@20=0.990081
map@1=0.560000  map@2=0.600161  map@5=0.665987  map@10=0.679741  map@20=0.683797
mrr@1=0.560000  mrr@2=0.656331  mrr@5=0.705175  mrr@10=0.710949  mrr@20=0.712911
f1@1=0.485810  f1@2=0.499534  f1@5=0.362289  f1@10=0.223351  f1@20=0.125598

[TEST]
recall@1=0.459334  recall@2=0.662585  recall@5=0.881513  recall@10=0.946766  recall@20=0.982770
precision@1=0.565480  precision@2=0.427593  precision@5=0.239336  precision@10=0.130904  precision@20=0.068375
ndcg@1=0.565480  ndcg@2=0.637179  ndcg@5=0.734664  ndcg@10=0.758815  ndcg@20=0.769191
hit_rate@1=0.565480  hit_rate@2=0.750886  hit_rate@5=0.921956  hit_rate@10=0.965045  hit_rate@20=0.990335
map@1=0.565480  map@2=0.602871  map@5=0.669352  map@10=0.683135  map@20=0.687092
mrr@1=0.565480  mrr@2=0.658183  mrr@5=0.707572  mrr@10=0.713464  mrr@20=0.715371
f1@1=0.490690  f1@2=0.499634  f1@5=0.363004  f1@10=0.223880  f1@20=0.125640

Epoch 81/100: 100%|██████████| 820/820 [00:13<00:00, 60.75it/s, bpr=0.0608, c=2.62, loss=0.166]

[VAL]
recall@1=0.449878  recall@2=0.662061  recall@5=0.882233  recall@10=0.945606  recall@20=0.981840
precision@1=0.555081  precision@2=0.426089  precision@5=0.239516  precision@10=0.130839  precision@20=0.068395
ndcg@1=0.555081  ndcg@2=0.632871  ndcg@5=0.731475  ndcg@10=0.755127  ndcg@20=0.765591
hit_rate@1=0.555081  hit_rate@2=0.751694  hit_rate@5=0.923871  hit_rate@10=0.964274  hit_rate@20=0.990000
map@1=0.555081  map@2=0.596835  map@5=0.664390  map@10=0.678199  map@20=0.682148
mrr@1=0.555081  mrr@2=0.653387  mrr@5=0.703559  mrr@10=0.709118  mrr@20=0.711062
f1@1=0.480915  f1@2=0.498367  f1@5=0.363091  f1@10=0.223654  f1@20=0.125626

[TEST]
recall@1=0.446723  recall@2=0.658320  recall@5=0.885118  recall@10=0.946891  recall@20=0.983808
precision@1=0.550177  precision@2=0.424654  precision@5=0.240319  precision@10=0.130984  precision@20=0.068432
ndcg@1=0.550177  ndcg@2=0.629278  ndcg@5=0.731215  ndcg@10=0.754180  ndcg@20=0.764741
hit_rate@1=0.550177  hit_rate@2=0.746859  hit_rate@5=0.925097  hit_rate@10=0.965045  hit_rate@20=0.991221
map@1=0.550177  map@2=0.593810  map@5=0.663773  map@10=0.677006  map@20=0.680986
mrr@1=0.550177  mrr@2=0.648518  mrr@5=0.700415  mrr@10=0.705872  mrr@20=0.707828
f1@1=0.477305  f1@2=0.496232  f1@5=0.364470  f1@10=0.223992  f1@20=0.125755

Epoch 82/100: 100%|██████████| 820/820 [00:13<00:00, 60.83it/s, bpr=0.0367, c=2.41, loss=0.133]

[VAL]
recall@1=0.441306  recall@2=0.650098  recall@5=0.880271  recall@10=0.945993  recall@20=0.981961
precision@1=0.544032  precision@2=0.418790  precision@5=0.238823  precision@10=0.130831  precision@20=0.068395
ndcg@1=0.544032  ndcg@2=0.621364  ndcg@5=0.724661  ndcg@10=0.749003  ndcg@20=0.759422
hit_rate@1=0.544032  hit_rate@2=0.738306  hit_rate@5=0.921532  hit_rate@10=0.965000  hit_rate@20=0.990242
map@1=0.544032  map@2=0.586028  map@5=0.656347  map@10=0.670304  map@20=0.674298
mrr@1=0.544032  mrr@2=0.641210  mrr@5=0.694359  mrr@10=0.700216  mrr@20=0.702140
f1@1=0.471583  f1@2=0.489646  f1@5=0.362154  f1@10=0.223679  f1@20=0.125632

[TEST]
recall@1=0.446643  recall@2=0.650725  recall@5=0.881167  recall@10=0.948142  recall@20=0.983190
precision@1=0.548969  precision@2=0.420103  precision@5=0.239143  precision@10=0.131113  precision@20=0.068420
ndcg@1=0.548969  ndcg@2=0.623901  ndcg@5=0.727428  ndcg@10=0.752236  ndcg@20=0.762273
hit_rate@1=0.548969  hit_rate@2=0.738483  hit_rate@5=0.922600  hit_rate@10=0.966092  hit_rate@20=0.990818
map@1=0.548969  map@2=0.589522  map@5=0.660084  map@10=0.674303  map@20=0.678112
mrr@1=0.548969  mrr@2=0.643686  mrr@5=0.696931  mrr@10=0.702847  mrr@20=0.704636
f1@1=0.476853  f1@2=0.490801  f1@5=0.362717  f1@10=0.224226  f1@20=0.125709

Epoch 83/100: 100%|██████████| 820/820 [00:13<00:00, 60.31it/s, bpr=0.0563, c=2.51, loss=0.157]

[VAL]
recall@1=0.440186  recall@2=0.649824  recall@5=0.878721  recall@10=0.945364  recall@20=0.982769
precision@1=0.541371  precision@2=0.417823  precision@5=0.238258  precision@10=0.130766  precision@20=0.068464
ndcg@1=0.541371  ndcg@2=0.620267  ndcg@5=0.722560  ndcg@10=0.747417  ndcg@20=0.758197
hit_rate@1=0.541371  hit_rate@2=0.737177  hit_rate@5=0.921613  hit_rate@10=0.964355  hit_rate@20=0.990645
map@1=0.541371  map@2=0.584919  map@5=0.654023  map@10=0.668477  map@20=0.672563
mrr@1=0.541371  mrr@2=0.639274  mrr@5=0.692067  mrr@10=0.697896  mrr@20=0.699852
f1@1=0.470038  f1@2=0.488913  f1@5=0.361333  f1@10=0.223551  f1@20=0.125756

[TEST]
recall@1=0.449132  recall@2=0.650573  recall@5=0.881687  recall@10=0.947977  recall@20=0.984655
precision@1=0.552835  precision@2=0.419741  precision@5=0.238982  precision@10=0.131153  precision@20=0.068488
ndcg@1=0.552835  ndcg@2=0.624765  ndcg@5=0.727987  ndcg@10=0.752768  ndcg@20=0.763244
hit_rate@1=0.552835  hit_rate@2=0.737355  hit_rate@5=0.924050  hit_rate@10=0.965689  hit_rate@20=0.991785
map@1=0.552835  map@2=0.590810  map@5=0.660420  map@10=0.674821  map@20=0.678772
mrr@1=0.552835  mrr@2=0.645095  mrr@5=0.698515  mrr@10=0.704234  mrr@20=0.706192
f1@1=0.479787  f1@2=0.490540  f1@5=0.362628  f1@10=0.224292  f1@20=0.125852

Epoch 84/100: 100%|██████████| 820/820 [00:13<00:00, 60.86it/s, bpr=0.0245, c=2.68, loss=0.132]

[VAL]
recall@1=0.460036  recall@2=0.669153  recall@5=0.886719  recall@10=0.944817  recall@20=0.982176
precision@1=0.567258  precision@2=0.430605  precision@5=0.240839  precision@10=0.130677  precision@20=0.068411
ndcg@1=0.567258  ndcg@2=0.641839  ndcg@5=0.738567  ndcg@10=0.760211  ndcg@20=0.770996
hit_rate@1=0.567258  hit_rate@2=0.757984  hit_rate@5=0.926613  hit_rate@10=0.964113  hit_rate@20=0.990484
map@1=0.567258  map@2=0.606552  map@5=0.672540  map@10=0.685161  map@20=0.689256
mrr@1=0.567258  mrr@2=0.662621  mrr@5=0.711504  mrr@10=0.716589  mrr@20=0.718570
f1@1=0.491564  f1@2=0.503638  f1@5=0.365106  f1@10=0.223420  f1@20=0.125650

[TEST]
recall@1=0.458622  recall@2=0.670181  recall@5=0.888068  recall@10=0.947452  recall@20=0.983706
precision@1=0.564111  precision@2=0.432587  precision@5=0.241044  precision@10=0.131016  precision@20=0.068408
ndcg@1=0.564111  ndcg@2=0.642059  ndcg@5=0.739107  ndcg@10=0.761159  ndcg@20=0.771547
hit_rate@1=0.564111  hit_rate@2=0.758537  hit_rate@5=0.928077  hit_rate@10=0.965770  hit_rate@20=0.991302
map@1=0.564111  map@2=0.606918  map@5=0.673317  map@10=0.686108  map@20=0.690041
mrr@1=0.564111  mrr@2=0.661324  mrr@5=0.710231  mrr@10=0.715325  mrr@20=0.717236
f1@1=0.489844  f1@2=0.505390  f1@5=0.365626  f1@10=0.224076  f1@20=0.125716

Epoch 85/100: 100%|██████████| 820/820 [00:13<00:00, 60.22it/s, bpr=0.0227, c=2.71, loss=0.131]

[VAL]
recall@1=0.450763  recall@2=0.656623  recall@5=0.880826  recall@10=0.944395  recall@20=0.980577
precision@1=0.555242  precision@2=0.422742  precision@5=0.238984  precision@10=0.130581  precision@20=0.068294
ndcg@1=0.555242  ndcg@2=0.629467  ndcg@5=0.729978  ndcg@10=0.753589  ndcg@20=0.764068
hit_rate@1=0.555242  hit_rate@2=0.744919  hit_rate@5=0.922500  hit_rate@10=0.963871  hit_rate@20=0.988952
map@1=0.555242  map@2=0.594476  map@5=0.662972  map@10=0.676649  map@20=0.680648
mrr@1=0.555242  mrr@2=0.650081  mrr@5=0.701802  mrr@10=0.707392  mrr@20=0.709286
f1@1=0.481667  f1@2=0.494309  f1@5=0.362372  f1@10=0.223257  f1@20=0.125442

[TEST]
recall@1=0.454178  recall@2=0.656991  recall@5=0.884533  recall@10=0.946883  recall@20=0.982535
precision@1=0.560084  precision@2=0.424170  precision@5=0.240206  precision@10=0.130888  precision@20=0.068319
ndcg@1=0.560084  ndcg@2=0.631425  ndcg@5=0.733451  ndcg@10=0.756468  ndcg@20=0.766683
hit_rate@1=0.560084  hit_rate@2=0.744845  hit_rate@5=0.924936  hit_rate@10=0.965287  hit_rate@20=0.990255
map@1=0.560084  map@2=0.597153  map@5=0.666795  map@10=0.679981  map@20=0.683839
mrr@1=0.560084  mrr@2=0.652465  mrr@5=0.704604  mrr@10=0.710073  mrr@20=0.711929
f1@1=0.485462  f1@2=0.495523  f1@5=0.364341  f1@10=0.223898  f1@20=0.125559

Epoch 86/100: 100%|██████████| 820/820 [00:13<00:00, 60.66it/s, bpr=0.0597, c=2.55, loss=0.162]

[VAL]
recall@1=0.461041  recall@2=0.663106  recall@5=0.883927  recall@10=0.947199  recall@20=0.982508
precision@1=0.567339  precision@2=0.427177  precision@5=0.240097  precision@10=0.131016  precision@20=0.068468
ndcg@1=0.567339  ndcg@2=0.638117  ndcg@5=0.736474  ndcg@10=0.759929  ndcg@20=0.770135
hit_rate@1=0.567339  hit_rate@2=0.751855  hit_rate@5=0.924839  hit_rate@10=0.966129  hit_rate@20=0.990484
map@1=0.567339  map@2=0.603730  map@5=0.670703  map@10=0.684244  map@20=0.688142
mrr@1=0.567339  mrr@2=0.659597  mrr@5=0.709672  mrr@10=0.715298  mrr@20=0.717109
f1@1=0.492331  f1@2=0.499345  f1@5=0.363929  f1@10=0.223963  f1@20=0.125743

[TEST]
recall@1=0.451975  recall@2=0.661654  recall@5=0.885921  recall@10=0.948589  recall@20=0.984048
precision@1=0.556540  precision@2=0.427956  precision@5=0.240657  precision@10=0.131137  precision@20=0.068444
ndcg@1=0.556540  ndcg@2=0.633987  ndcg@5=0.733945  ndcg@10=0.757162  ndcg@20=0.767344
hit_rate@1=0.556540  hit_rate@2=0.749839  hit_rate@5=0.926144  hit_rate@10=0.966495  hit_rate@20=0.991463
map@1=0.556540  map@2=0.599166  map@5=0.667295  map@10=0.680653  map@20=0.684523
mrr@1=0.556540  mrr@2=0.653189  mrr@5=0.703957  mrr@10=0.709482  mrr@20=0.711345
f1@1=0.482804  f1@2=0.499540  f1@5=0.364947  f1@10=0.224310  f1@20=0.125777

Epoch 87/100: 100%|██████████| 820/820 [00:13<00:00, 61.03it/s, bpr=0.0245, c=2.51, loss=0.125]

[VAL]
recall@1=0.446073  recall@2=0.656909  recall@5=0.881931  recall@10=0.946908  recall@20=0.981404
precision@1=0.549274  precision@2=0.422742  precision@5=0.239242  precision@10=0.131016  precision@20=0.068367
ndcg@1=0.549274  ndcg@2=0.627774  ndcg@5=0.728221  ndcg@10=0.752512  ndcg@20=0.762441
hit_rate@1=0.549274  hit_rate@2=0.745968  hit_rate@5=0.924355  hit_rate@10=0.965161  hit_rate@20=0.989516
map@1=0.549274  map@2=0.592036  map@5=0.660251  map@10=0.674467  map@20=0.678224
mrr@1=0.549274  mrr@2=0.647621  mrr@5=0.699069  mrr@10=0.704677  mrr@20=0.706488
f1@1=0.476482  f1@2=0.494424  f1@5=0.362765  f1@10=0.223980  f1@20=0.125577

[TEST]
recall@1=0.450605  recall@2=0.655938  recall@5=0.883982  recall@10=0.949112  recall@20=0.983836
precision@1=0.553802  precision@2=0.422640  precision@5=0.239868  precision@10=0.131226  precision@20=0.068444
ndcg@1=0.553802  ndcg@2=0.628707  ndcg@5=0.730877  ndcg@10=0.755138  ndcg@20=0.765057
hit_rate@1=0.553802  hit_rate@2=0.743798  hit_rate@5=0.925580  hit_rate@10=0.966736  hit_rate@20=0.991302
map@1=0.553802  map@2=0.594032  map@5=0.663530  map@10=0.677610  map@20=0.681344
mrr@1=0.553802  mrr@2=0.648800  mrr@5=0.700997  mrr@10=0.706675  mrr@20=0.708477
f1@1=0.481128  f1@2=0.494218  f1@5=0.363836  f1@10=0.224450  f1@20=0.125772

Epoch 88/100: 100%|██████████| 820/820 [00:13<00:00, 60.40it/s, bpr=0.0326, c=2.61, loss=0.137]

[VAL]
recall@1=0.454929  recall@2=0.661979  recall@5=0.882743  recall@10=0.946251  recall@20=0.981872
precision@1=0.558871  precision@2=0.426008  precision@5=0.239581  precision@10=0.130839  precision@20=0.068391
ndcg@1=0.558871  ndcg@2=0.634569  ndcg@5=0.733159  ndcg@10=0.756828  ndcg@20=0.767113
hit_rate@1=0.558871  hit_rate@2=0.750565  hit_rate@5=0.924435  hit_rate@10=0.965323  hit_rate@20=0.990000
map@1=0.558871  map@2=0.599536  map@5=0.666637  map@10=0.680426  map@20=0.684330
mrr@1=0.558871  mrr@2=0.654718  mrr@5=0.705161  mrr@10=0.710777  mrr@20=0.712614
f1@1=0.485613  f1@2=0.498249  f1@5=0.363214  f1@10=0.223685  f1@20=0.125629

[TEST]
recall@1=0.452204  recall@2=0.659844  recall@5=0.885419  recall@10=0.948708  recall@20=0.983933
precision@1=0.557184  precision@2=0.425177  precision@5=0.240303  precision@10=0.131169  precision@20=0.068476
ndcg@1=0.557184  ndcg@2=0.632250  ndcg@5=0.733371  ndcg@10=0.756894  ndcg@20=0.767001
hit_rate@1=0.557184  hit_rate@2=0.747423  hit_rate@5=0.926546  hit_rate@10=0.966656  hit_rate@20=0.991140
map@1=0.557184  map@2=0.597435  map@5=0.666381  map@10=0.680003  map@20=0.683841
mrr@1=0.557184  mrr@2=0.652303  mrr@5=0.704014  mrr@10=0.709503  mrr@20=0.711327
f1@1=0.483124  f1@2=0.497220  f1@5=0.364544  f1@10=0.224365  f1@20=0.125817

Epoch 89/100: 100%|██████████| 820/820 [00:13<00:00, 60.57it/s, bpr=0.046, c=2.52, loss=0.147]

[VAL]
recall@1=0.457170  recall@2=0.663526  recall@5=0.885138  recall@10=0.944696  recall@20=0.982273
precision@1=0.560726  precision@2=0.426532  precision@5=0.240194  precision@10=0.130782  precision@20=0.068435
ndcg@1=0.560726  ndcg@2=0.636202  ndcg@5=0.735328  ndcg@10=0.757679  ndcg@20=0.768510
hit_rate@1=0.560726  hit_rate@2=0.751774  hit_rate@5=0.926290  hit_rate@10=0.963226  hit_rate@20=0.990000
map@1=0.560726  map@2=0.601351  map@5=0.668997  map@10=0.682185  map@20=0.686278
mrr@1=0.560726  mrr@2=0.656250  mrr@5=0.706833  mrr@10=0.711897  mrr@20=0.713938
f1@1=0.487669  f1@2=0.499198  f1@5=0.364200  f1@10=0.223529  f1@20=0.125695

[TEST]
recall@1=0.463050  recall@2=0.667634  recall@5=0.886724  recall@10=0.946323  recall@20=0.983988
precision@1=0.567332  precision@2=0.430533  precision@5=0.240754  precision@10=0.130815  precision@20=0.068452
ndcg@1=0.567332  ndcg@2=0.641681  ndcg@5=0.739226  ndcg@10=0.761433  ndcg@20=0.772275
hit_rate@1=0.567332  hit_rate@2=0.754913  hit_rate@5=0.927593  hit_rate@10=0.965045  hit_rate@20=0.991382
map@1=0.567332  map@2=0.607663  map@5=0.674023  map@10=0.686987  map@20=0.691124
mrr@1=0.567332  mrr@2=0.661123  mrr@5=0.710746  mrr@10=0.715868  mrr@20=0.717851
f1@1=0.493822  f1@2=0.503224  f1@5=0.365188  f1@10=0.223766  f1@20=0.125787

Epoch 90/100: 100%|██████████| 820/820 [00:13<00:00, 60.82it/s, bpr=0.0313, c=2.6, loss=0.135]

[VAL]
recall@1=0.457256  recall@2=0.670987  recall@5=0.887387  recall@10=0.947795  recall@20=0.982410
precision@1=0.563065  precision@2=0.431573  precision@5=0.241000  precision@10=0.131161  precision@20=0.068423
ndcg@1=0.563065  ndcg@2=0.641740  ndcg@5=0.738369  ndcg@10=0.760955  ndcg@20=0.770933
hit_rate@1=0.563065  hit_rate@2=0.760565  hit_rate@5=0.927581  hit_rate@10=0.966210  hit_rate@20=0.990565
map@1=0.563065  map@2=0.605746  map@5=0.672014  map@10=0.685275  map@20=0.689051
mrr@1=0.563065  mrr@2=0.661815  mrr@5=0.710480  mrr@10=0.715792  mrr@20=0.717616
f1@1=0.488399  f1@2=0.504954  f1@5=0.365340  f1@10=0.224204  f1@20=0.125692

[TEST]
recall@1=0.459882  recall@2=0.672618  recall@5=0.890415  recall@10=0.949650  recall@20=0.984089
precision@1=0.565883  precision@2=0.433835  precision@5=0.241833  precision@10=0.131371  precision@20=0.068464
ndcg@1=0.565883  ndcg@2=0.644223  ndcg@5=0.741517  ndcg@10=0.763622  ndcg@20=0.773470
hit_rate@1=0.565883  hit_rate@2=0.762162  hit_rate@5=0.929768  hit_rate@10=0.966978  hit_rate@20=0.991221
map@1=0.565883  map@2=0.608670  map@5=0.675685  map@10=0.688537  map@20=0.692245
mrr@1=0.565883  mrr@2=0.664022  mrr@5=0.712786  mrr@10=0.717922  mrr@20=0.719729
f1@1=0.491127  f1@2=0.507039  f1@5=0.366792  f1@10=0.224661  f1@20=0.125811

Epoch 91/100: 100%|██████████| 820/820 [00:13<00:00, 61.01it/s, bpr=0.0526, c=2.64, loss=0.158]

[VAL]
recall@1=0.450620  recall@2=0.660213  recall@5=0.884926  recall@10=0.946374  recall@20=0.982685
precision@1=0.553790  precision@2=0.424234  precision@5=0.240274  precision@10=0.130976  precision@20=0.068448
ndcg@1=0.553790  ndcg@2=0.631469  ndcg@5=0.732284  ndcg@10=0.755300  ndcg@20=0.765749
hit_rate@1=0.553790  hit_rate@2=0.748629  hit_rate@5=0.926129  hit_rate@10=0.964919  hit_rate@20=0.990645
map@1=0.553790  map@2=0.596008  map@5=0.664893  map@10=0.678378  map@20=0.682326
mrr@1=0.553790  mrr@2=0.651210  mrr@5=0.702745  mrr@10=0.708123  mrr@20=0.710053
f1@1=0.481060  f1@2=0.496537  f1@5=0.364204  f1@10=0.223882  f1@20=0.125732

[TEST]
recall@1=0.453250  recall@2=0.662814  recall@5=0.887809  recall@10=0.948894  recall@20=0.983862
precision@1=0.557506  precision@2=0.427030  precision@5=0.240818  precision@10=0.131250  precision@20=0.068444
ndcg@1=0.557506  ndcg@2=0.634578  ndcg@5=0.735359  ndcg@10=0.758195  ndcg@20=0.768178
hit_rate@1=0.557506  hit_rate@2=0.750161  hit_rate@5=0.928721  hit_rate@10=0.966495  hit_rate@20=0.991221
map@1=0.557506  map@2=0.599650  map@5=0.668394  map@10=0.681741  map@20=0.685494
mrr@1=0.557506  mrr@2=0.653834  mrr@5=0.705308  mrr@10=0.710487  mrr@20=0.712319
f1@1=0.484031  f1@2=0.499355  f1@5=0.365349  f1@10=0.224461  f1@20=0.125773

Epoch 92/100: 100%|██████████| 820/820 [00:13<00:00, 60.54it/s, bpr=0.0406, c=2.56, loss=0.143]

[VAL]
recall@1=0.449764  recall@2=0.662564  recall@5=0.884623  recall@10=0.945204  recall@20=0.983045
precision@1=0.552742  precision@2=0.425927  precision@5=0.240387  precision@10=0.130823  precision@20=0.068460
ndcg@1=0.552742  ndcg@2=0.632839  ndcg@5=0.732707  ndcg@10=0.755301  ndcg@20=0.766101
hit_rate@1=0.552742  hit_rate@2=0.751774  hit_rate@5=0.925323  hit_rate@10=0.963790  hit_rate@20=0.990887
map@1=0.552742  map@2=0.596915  map@5=0.665499  map@10=0.678755  map@20=0.682753
mrr@1=0.552742  mrr@2=0.652258  mrr@5=0.703122  mrr@10=0.708392  mrr@20=0.710391
f1@1=0.480068  f1@2=0.498431  f1@5=0.364312  f1@10=0.223620  f1@20=0.125752

[TEST]
recall@1=0.455509  recall@2=0.665152  recall@5=0.887505  recall@10=0.947951  recall@20=0.983239
precision@1=0.560406  precision@2=0.428721  precision@5=0.241092  precision@10=0.131113  precision@20=0.068408
ndcg@1=0.560406  ndcg@2=0.637193  ndcg@5=0.736777  ndcg@10=0.759264  ndcg@20=0.769372
hit_rate@1=0.560406  hit_rate@2=0.753866  hit_rate@5=0.927513  hit_rate@10=0.965851  hit_rate@20=0.990577
map@1=0.560406  map@2=0.601965  map@5=0.670287  map@10=0.683313  map@20=0.687141
mrr@1=0.560406  mrr@2=0.657136  mrr@5=0.707434  mrr@10=0.712698  mrr@20=0.714552
f1@1=0.486539  f1@2=0.501181  f1@5=0.365596  f1@10=0.224236  f1@20=0.125707

Epoch 93/100: 100%|██████████| 820/820 [00:13<00:00, 60.73it/s, bpr=0.0426, c=2.52, loss=0.144]

[VAL]
recall@1=0.448464  recall@2=0.658665  recall@5=0.881015  recall@10=0.944736  recall@20=0.981919
precision@1=0.551129  precision@2=0.423750  precision@5=0.239065  precision@10=0.130694  precision@20=0.068355
ndcg@1=0.551129  ndcg@2=0.629618  ndcg@5=0.729431  ndcg@10=0.753252  ndcg@20=0.763956
hit_rate@1=0.551129  hit_rate@2=0.747339  hit_rate@5=0.923145  hit_rate@10=0.963790  hit_rate@20=0.990000
map@1=0.551129  map@2=0.594093  map@5=0.662264  map@10=0.676218  map@20=0.680257
mrr@1=0.551129  mrr@2=0.649234  mrr@5=0.700484  mrr@10=0.706035  mrr@20=0.708003
f1@1=0.478790  f1@2=0.495757  f1@5=0.362452  f1@10=0.223432  f1@20=0.125581

[TEST]
recall@1=0.454213  recall@2=0.660287  recall@5=0.883956  recall@10=0.947463  recall@20=0.984027
precision@1=0.559681  precision@2=0.426426  precision@5=0.239836  precision@10=0.131041  precision@20=0.068468
ndcg@1=0.559681  ndcg@2=0.633862  ndcg@5=0.733718  ndcg@10=0.757386  ndcg@20=0.767863
hit_rate@1=0.559681  hit_rate@2=0.748228  hit_rate@5=0.925741  hit_rate@10=0.965689  hit_rate@20=0.991463
map@1=0.559681  map@2=0.599348  map@5=0.667170  map@10=0.680922  map@20=0.684886
mrr@1=0.559681  mrr@2=0.653955  mrr@5=0.705412  mrr@10=0.710898  mrr@20=0.712819
f1@1=0.485283  f1@2=0.498025  f1@5=0.363859  f1@10=0.224118  f1@20=0.125816

Epoch 94/100: 100%|██████████| 820/820 [00:13<00:00, 60.47it/s, bpr=0.074, c=2.66, loss=0.18]

[VAL]
recall@1=0.459256  recall@2=0.668837  recall@5=0.885605  recall@10=0.945589  recall@20=0.982676
precision@1=0.565081  precision@2=0.430927  precision@5=0.240774  precision@10=0.130823  precision@20=0.068427
ndcg@1=0.565081  ndcg@2=0.641261  ndcg@5=0.737807  ndcg@10=0.760133  ndcg@20=0.770784
hit_rate@1=0.565081  hit_rate@2=0.759113  hit_rate@5=0.925726  hit_rate@10=0.964516  hit_rate@20=0.990726
map@1=0.565081  map@2=0.605706  map@5=0.671949  map@10=0.684934  map@20=0.688944
mrr@1=0.565081  mrr@2=0.662097  mrr@5=0.710464  mrr@10=0.715780  mrr@20=0.717738
f1@1=0.490438  f1@2=0.503790  f1@5=0.364884  f1@10=0.223653  f1@20=0.125697

[TEST]
recall@1=0.460149  recall@2=0.669421  recall@5=0.888998  recall@10=0.948611  recall@20=0.983808
precision@1=0.567252  precision@2=0.432587  precision@5=0.241640  precision@10=0.131153  precision@20=0.068468
ndcg@1=0.567252  ndcg@2=0.642479  ndcg@5=0.740402  ndcg@10=0.762411  ndcg@20=0.772512
hit_rate@1=0.567252  hit_rate@2=0.759423  hit_rate@5=0.927996  hit_rate@10=0.966575  hit_rate@20=0.991140
map@1=0.567252  map@2=0.607200  map@5=0.674689  map@10=0.687305  map@20=0.691130
mrr@1=0.567252  mrr@2=0.663338  mrr@5=0.712013  mrr@10=0.717258  mrr@20=0.719079
f1@1=0.491863  f1@2=0.505086  f1@5=0.366366  f1@10=0.224320  f1@20=0.125797

Epoch 95/100: 100%|██████████| 820/820 [00:13<00:00, 60.60it/s, bpr=0.0262, c=2.62, loss=0.131]

[VAL]
recall@1=0.454336  recall@2=0.659282  recall@5=0.881541  recall@10=0.944164  recall@20=0.981804
precision@1=0.559758  precision@2=0.424516  precision@5=0.239339  precision@10=0.130629  precision@20=0.068391
ndcg@1=0.559758  ndcg@2=0.632700  ndcg@5=0.732101  ndcg@10=0.755486  ndcg@20=0.766379
hit_rate@1=0.559758  hit_rate@2=0.749194  hit_rate@5=0.923710  hit_rate@10=0.963306  hit_rate@20=0.989597
map@1=0.559758  map@2=0.597480  map@5=0.665413  map@10=0.679063  map@20=0.683214
mrr@1=0.559758  mrr@2=0.654516  mrr@5=0.705126  mrr@10=0.710580  mrr@20=0.712592
f1@1=0.485467  f1@2=0.496403  f1@5=0.362835  f1@10=0.223325  f1@20=0.125633

[TEST]
recall@1=0.449929  recall@2=0.661987  recall@5=0.883096  recall@10=0.946093  recall@20=0.982931
precision@1=0.554365  precision@2=0.427956  precision@5=0.239771  precision@10=0.130815  precision@20=0.068424
ndcg@1=0.554365  ndcg@2=0.633620  ndcg@5=0.731703  ndcg@10=0.755090  ndcg@20=0.765743
hit_rate@1=0.554365  hit_rate@2=0.749597  hit_rate@5=0.924130  hit_rate@10=0.964562  hit_rate@20=0.990416
map@1=0.554365  map@2=0.598643  map@5=0.665123  map@10=0.678580  map@20=0.682673
mrr@1=0.554365  mrr@2=0.651941  mrr@5=0.702138  mrr@10=0.707667  mrr@20=0.709631
f1@1=0.480650  f1@2=0.499488  f1@5=0.363635  f1@10=0.223709  f1@20=0.125711

Epoch 96/100: 100%|██████████| 820/820 [00:13<00:00, 61.28it/s, bpr=0.0438, c=2.49, loss=0.144]

[VAL]
recall@1=0.457105  recall@2=0.659107  recall@5=0.885114  recall@10=0.946684  recall@20=0.981931
precision@1=0.560968  precision@2=0.424073  precision@5=0.240226  precision@10=0.130944  precision@20=0.068415
ndcg@1=0.560968  ndcg@2=0.633348  ndcg@5=0.734452  ndcg@10=0.757555  ndcg@20=0.767714
hit_rate@1=0.560968  hit_rate@2=0.746935  hit_rate@5=0.925645  hit_rate@10=0.965565  hit_rate@20=0.990000
map@1=0.560968  map@2=0.599073  map@5=0.667833  map@10=0.681375  map@20=0.685216
mrr@1=0.560968  mrr@2=0.653952  mrr@5=0.705695  mrr@10=0.711264  mrr@20=0.713079
f1@1=0.487738  f1@2=0.496047  f1@5=0.364243  f1@10=0.223850  f1@20=0.125668

[TEST]
recall@1=0.456949  recall@2=0.661720  recall@5=0.888560  recall@10=0.949198  recall@20=0.983554
precision@1=0.562258  precision@2=0.426909  precision@5=0.241334  precision@10=0.131274  precision@20=0.068464
ndcg@1=0.562258  ndcg@2=0.635502  ndcg@5=0.737058  ndcg@10=0.759577  ndcg@20=0.769434
hit_rate@1=0.562258  hit_rate@2=0.748792  hit_rate@5=0.927674  hit_rate@10=0.966736  hit_rate@20=0.990899
map@1=0.562258  map@2=0.601301  map@5=0.670583  map@10=0.683582  map@20=0.687317
mrr@1=0.562258  mrr@2=0.655525  mrr@5=0.707163  mrr@10=0.712524  mrr@20=0.714313
f1@1=0.488036  f1@2=0.498911  f1@5=0.366003  f1@10=0.224486  f1@20=0.125775

Epoch 97/100: 100%|██████████| 820/820 [00:13<00:00, 60.44it/s, bpr=0.0362, c=2.62, loss=0.141]

[VAL]
recall@1=0.454512  recall@2=0.659757  recall@5=0.884839  recall@10=0.946849  recall@20=0.982078
precision@1=0.559355  precision@2=0.424274  precision@5=0.240210  precision@10=0.130879  precision@20=0.068395
ndcg@1=0.559355  ndcg@2=0.632748  ndcg@5=0.733713  ndcg@10=0.756805  ndcg@20=0.767008
hit_rate@1=0.559355  hit_rate@2=0.748710  hit_rate@5=0.925806  hit_rate@10=0.965726  hit_rate@20=0.990323
map@1=0.559355  map@2=0.597641  map@5=0.666567  map@10=0.680063  map@20=0.683939
mrr@1=0.559355  mrr@2=0.654032  mrr@5=0.705508  mrr@10=0.710981  mrr@20=0.712827
f1@1=0.485484  f1@2=0.496438  f1@5=0.364129  f1@10=0.223804  f1@20=0.125635

[TEST]
recall@1=0.451583  recall@2=0.660950  recall@5=0.886741  recall@10=0.948547  recall@20=0.983962
precision@1=0.555412  precision@2=0.426385  precision@5=0.240544  precision@10=0.131250  precision@20=0.068444
ndcg@1=0.555412  ndcg@2=0.632890  ndcg@5=0.733617  ndcg@10=0.756737  ndcg@20=0.766840
hit_rate@1=0.555412  hit_rate@2=0.748631  hit_rate@5=0.928238  hit_rate@10=0.966495  hit_rate@20=0.991624
map@1=0.555412  map@2=0.597999  map@5=0.666275  map@10=0.679816  map@20=0.683636
mrr@1=0.555412  mrr@2=0.652022  mrr@5=0.703747  mrr@10=0.708963  mrr@20=0.710829
f1@1=0.482254  f1@2=0.498276  f1@5=0.364923  f1@10=0.224410  f1@20=0.125770

Epoch 98/100: 100%|██████████| 820/820 [00:13<00:00, 59.88it/s, bpr=0.0503, c=2.6, loss=0.154]

[VAL]
recall@1=0.446659  recall@2=0.656347  recall@5=0.877202  recall@10=0.943702  recall@20=0.982631
precision@1=0.550968  precision@2=0.422661  precision@5=0.237968  precision@10=0.130500  precision@20=0.068435
ndcg@1=0.550968  ndcg@2=0.627719  ndcg@5=0.726308  ndcg@10=0.751013  ndcg@20=0.762251
hit_rate@1=0.550968  hit_rate@2=0.745645  hit_rate@5=0.920000  hit_rate@10=0.963145  hit_rate@20=0.990645
map@1=0.550968  map@2=0.592016  map@5=0.659065  map@10=0.673348  map@20=0.677602
mrr@1=0.550968  mrr@2=0.648306  mrr@5=0.698761  mrr@10=0.704640  mrr@20=0.706720
f1@1=0.477450  f1@2=0.494211  f1@5=0.360850  f1@10=0.223127  f1@20=0.125714

[TEST]
recall@1=0.450165  recall@2=0.654370  recall@5=0.878008  recall@10=0.946388  recall@20=0.984078
precision@1=0.554688  precision@2=0.422882  precision@5=0.238515  precision@10=0.130863  precision@20=0.068472
ndcg@1=0.554688  ndcg@2=0.628203  ndcg@5=0.727974  ndcg@10=0.753084  ndcg@20=0.763896
hit_rate@1=0.554688  hit_rate@2=0.742429  hit_rate@5=0.919459  hit_rate@10=0.964884  hit_rate@20=0.991382
map@1=0.554688  map@2=0.593790  map@5=0.661643  map@10=0.675843  map@20=0.679926
mrr@1=0.554688  mrr@2=0.648558  mrr@5=0.699464  mrr@10=0.705580  mrr@20=0.707561
f1@1=0.481046  f1@2=0.493765  f1@5=0.361662  f1@10=0.223795  f1@20=0.125819

Epoch 99/100: 100%|██████████| 820/820 [00:13<00:00, 59.66it/s, bpr=0.0442, c=2.53, loss=0.145]

[VAL]
recall@1=0.456607  recall@2=0.661802  recall@5=0.884386  recall@10=0.943506  recall@20=0.981163
precision@1=0.562177  precision@2=0.426573  precision@5=0.240097  precision@10=0.130508  precision@20=0.068363
ndcg@1=0.562177  ndcg@2=0.635500  ndcg@5=0.735027  ndcg@10=0.757086  ndcg@20=0.767986
hit_rate@1=0.562177  hit_rate@2=0.750806  hit_rate@5=0.925645  hit_rate@10=0.962581  hit_rate@20=0.989274
map@1=0.562177  map@2=0.600665  map@5=0.668549  map@10=0.681499  map@20=0.685638
mrr@1=0.562177  mrr@2=0.656492  mrr@5=0.707473  mrr@10=0.712499  mrr@20=0.714527
f1@1=0.487721  f1@2=0.498565  f1@5=0.363962  f1@10=0.223125  f1@20=0.125569

[TEST]
recall@1=0.458895  recall@2=0.663030  recall@5=0.885760  recall@10=0.945949  recall@20=0.982453
precision@1=0.564433  precision@2=0.428359  precision@5=0.240512  precision@10=0.130799  precision@20=0.068327
ndcg@1=0.564433  ndcg@2=0.637459  ndcg@5=0.736947  ndcg@10=0.759278  ndcg@20=0.769781
hit_rate@1=0.564433  hit_rate@2=0.750966  hit_rate@5=0.925499  hit_rate@10=0.964320  hit_rate@20=0.990255
map@1=0.564433  map@2=0.603294  map@5=0.671269  map@10=0.684166  map@20=0.688129
mrr@1=0.564433  mrr@2=0.657700  mrr@5=0.708328  mrr@10=0.713605  mrr@20=0.715576
f1@1=0.490029  f1@2=0.500218  f1@5=0.364812  f1@10=0.223693  f1@20=0.125563

Epoch 100/100: 100%|██████████| 820/820 [00:13<00:00, 60.88it/s, bpr=0.0228, c=2.64, loss=0.128]

[VAL]
recall@1=0.456372  recall@2=0.663456  recall@5=0.880958  recall@10=0.945416  recall@20=0.982192
precision@1=0.560806  precision@2=0.427097  precision@5=0.239097  precision@10=0.130710  precision@20=0.068411
ndcg@1=0.560806  ndcg@2=0.636153  ndcg@5=0.733205  ndcg@10=0.757067  ndcg@20=0.767652
hit_rate@1=0.560806  hit_rate@2=0.752984  hit_rate@5=0.922661  hit_rate@10=0.964435  hit_rate@20=0.990403
map@1=0.560806  map@2=0.600907  map@5=0.667171  map@10=0.680985  map@20=0.684962
mrr@1=0.560806  mrr@2=0.656895  mrr@5=0.706222  mrr@10=0.711829  mrr@20=0.713742
f1@1=0.487246  f1@2=0.499500  f1@5=0.362495  f1@10=0.223484  f1@20=0.125656

[TEST]
recall@1=0.457007  recall@2=0.665210  recall@5=0.883754  recall@10=0.948248  recall@20=0.982950
precision@1=0.562097  precision@2=0.429607  precision@5=0.239997  precision@10=0.131169  precision@20=0.068351
ndcg@1=0.562097  ndcg@2=0.638259  ndcg@5=0.735157  ndcg@10=0.758978  ndcg@20=0.768921
hit_rate@1=0.562097  hit_rate@2=0.753947  hit_rate@5=0.924694  hit_rate@10=0.965609  hit_rate@20=0.990577
map@1=0.562097  map@2=0.603435  map@5=0.669234  map@10=0.682952  map@20=0.686698
mrr@1=0.562097  mrr@2=0.658022  mrr@5=0.707050  mrr@10=0.712597  mrr@20=0.714482
f1@1=0.487989  f1@2=0.501684  f1@5=0.363936  f1@10=0.224317  f1@20=0.125616

,epoch,val_recall@1,val_recall@2,val_recall@5,val_recall@10,val_recall@20,val_precision@1,val_precision@2,val_precision@5,val_precision@10,...,test_mrr@1,test_mrr@2,test_mrr@5,test_mrr@10,test_mrr@20,test_f1@1,test_f1@2,test_f1@5,test_f1@10,test_f1@20
0,1,0.348762,0.499190,0.790048,0.936783,0.978517,0.445887,0.338145,0.216613,0.129298,...,0.441688,0.511034,0.577141,0.594627,0.596754,0.372991,0.384377,0.328272,0.221858,0.125136
1,2,0.442059,0.620403,0.823707,0.941959,0.980409,0.544597,0.404395,0.225565,0.130202,...,0.545506,0.628020,0.673207,0.686737,0.688803,0.471866,0.470422,0.341374,0.222837,0.125421
2,3,0.439178,0.665954,0.864406,0.946239,0.981651,0.537581,0.427339,0.234645,0.130790,...,0.544378,0.650209,0.692767,0.701262,0.703017,0.472079,0.501842,0.355127,0.224234,0.125615
3,4,0.450093,0.683103,0.869028,0.945203,0.981151,0.549516,0.438589,0.235919,0.130669,...,0.552916,0.664747,0.702767,0.710489,0.712244,0.481024,0.517224,0.356906,0.224333,0.125607
4,5,0.464018,0.689319,0.879969,0.944731,0.980593,0.570000,0.443992,0.239597,0.130661,...,0.575387,0.676869,0.717151,0.723400,0.725281,0.498658,0.518668,0.364017,0.223852,0.125636
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,0.457105,0.659107,0.885114,0.946684,0.981931,0.560968,0.424073,0.240226,0.130944,...,0.562258,0.655525,0.707163,0.712524,0.714313,0.488036,0.498911,0.366003,0.224486,0.125775
96,97,0.454512,0.659757,0.884839,0.946849,0.982078,0.559355,0.424274,0.240210,0.130879,...,0.555412,0.652022,0.703747,0.708963,0.710829,0.482254,0.498276,0.364923,0.224410,0.125770
97,98,0.446659,0.656347,0.877202,0.943702,0.982631,0.550968,0.422661,0.237968,0.130500,...,0.554688,0.648558,0.699464,0.705580,0.707561,0.481046,0.493765,0.361662,0.223795,0.125819
98,99,0.456607,0.661802,0.884386,0.943506,0.981163,0.562177,0.426573,0.240097,0.130508,...,0.564433,0.657700,0.708328,0.713605,0.715576,0.490029,0.500218,0.364812,0.223693,0.125563
99,100,0.456372,0.663456,0.880958,0.945416,0.982192,0.560806,0.427097,0.239097,0.130710,...,0.562097,0.658022,0.707050,0.712597,0.714482,0.487989,0.501684,0.363936,0.224317,0.125616

## Run full PAL model

In [13]:
full_model_conf = make_experiment_conf(
    base_conf,
    attention_type="user",
    fusion_type="user",
    epochs=100,
)

full_model_output = train_notebook(
    full_model_conf,
    experiment_name="step2_full_model"
)

full_model_output["history_df"]

>>>>>>>>>>B-I statistics>>>>>>>>>>
Average interactions 5.757723808288574
Non-zero rows 0.9967479674796748
Non-zero columns 1.0
Matrix density 0.002042470229597649
>>>>>>>>>>U-I statistics>>>>>>>>>>
Average interactions 30.47064208984375
Non-zero rows 1.0
Non-zero columns 0.5001773678609436
Matrix density 0.010809025126048253
>>>>>>>>>>U-B statistics in train>>>>>>>>>>
Average interactions 1.7729297876358032
Non-zero rows 0.8142673955591551
Non-zero columns 0.3382113821138211
Matrix density 0.0028828125900210205
>>>>>>>>>>U-B statistics in tune>>>>>>>>>>
Average interactions 0.5909765958786011
Non-zero rows 0.41843828035364783
Non-zero columns 0.27479674796747966
Matrix density 0.0009609375300070068
>>>>>>>>>>U-B statistics in test>>>>>>>>>>
Average interactions 0.5909765958786011
Non-zero rows 0.4189782007153945
Non-zero columns 0.2780487804878049
Matrix density 0.0009609375300070068

Epoch 1/100: 100%|██████████| 820/820 [00:14<00:00, 58.27it/s, bpr=0.0904, c=2.85, loss=0.205]

[VAL]
recall@1=0.342584  recall@2=0.543274  recall@5=0.787423  recall@10=0.926022  recall@20=0.979068
precision@1=0.431290  precision@2=0.356290  precision@5=0.213823  precision@10=0.127879  precision@20=0.068069
ndcg@1=0.431290  ndcg@2=0.512910  ndcg@5=0.619999  ndcg@10=0.670202  ndcg@20=0.685495
hit_rate@1=0.431290  hit_rate@2=0.633548  hit_rate@5=0.843387  hit_rate@10=0.949435  hit_rate@20=0.988306
map@1=0.431290  map@2=0.477157  map@5=0.546696  map@10=0.573037  map@20=0.578785
mrr@1=0.431290  mrr@2=0.532500  mrr@5=0.589831  mrr@10=0.604965  mrr@20=0.607962
f1@1=0.368486  f1@2=0.412753  f1@5=0.324088  f1@10=0.218747  f1@20=0.125105

[TEST]
recall@1=0.337319  recall@2=0.536505  recall@5=0.788232  recall@10=0.928056  recall@20=0.979832
precision@1=0.422600  precision@2=0.352771  precision@5=0.213982  precision@10=0.128141  precision@20=0.068017
ndcg@1=0.422600  ndcg@2=0.506112  ndcg@5=0.617203  ndcg@10=0.667801  ndcg@20=0.682594
hit_rate@1=0.422600  hit_rate@2=0.628947  hit_rate@5=0.842703  hit_rate@10=0.950467  hit_rate@20=0.988805
map@1=0.422600  map@2=0.470180  map@5=0.543204  map@10=0.569699  map@20=0.575174
mrr@1=0.422600  mrr@2=0.525693  mrr@5=0.584081  mrr@10=0.599378  mrr@20=0.602249
f1@1=0.362224  f1@2=0.408263  f1@5=0.324524  f1@10=0.219296  f1@20=0.125046

Saved new best checkpoint at epoch 1

Epoch 2/100: 100%|██████████| 820/820 [00:13<00:00, 58.94it/s, bpr=0.0435, c=2.83, loss=0.157]

[VAL]
recall@1=0.386088  recall@2=0.599191  recall@5=0.855508  recall@10=0.939571  recall@20=0.982032
precision@1=0.471452  precision@2=0.380565  precision@5=0.229887  precision@10=0.129645  precision@20=0.068294
ndcg@1=0.471452  ndcg@2=0.562046  ndcg@5=0.680892  ndcg@10=0.712378  ndcg@20=0.724663
hit_rate@1=0.471452  hit_rate@2=0.681855  hit_rate@5=0.903629  hit_rate@10=0.959919  hit_rate@20=0.990403
map@1=0.471452  map@2=0.525887  map@5=0.606255  map@10=0.624246  map@20=0.628876
mrr@1=0.471452  mrr@2=0.576694  mrr@5=0.642020  mrr@10=0.649806  mrr@20=0.652091
f1@1=0.411109  f1@2=0.447946  f1@5=0.349628  f1@10=0.221796  f1@20=0.125505

[TEST]
recall@1=0.377718  recall@2=0.593013  recall@5=0.854872  recall@10=0.941692  recall@20=0.982445
precision@1=0.461260  precision@2=0.376409  precision@5=0.229639  precision@10=0.129913  precision@20=0.068202
ndcg@1=0.461260  ndcg@2=0.553944  ndcg@5=0.676568  ndcg@10=0.708830  ndcg@20=0.720594
hit_rate@1=0.461260  hit_rate@2=0.677835  hit_rate@5=0.902867  hit_rate@10=0.960938  hit_rate@20=0.990496
map@1=0.461260  map@2=0.516773  map@5=0.600684  map@10=0.618916  map@20=0.623334
mrr@1=0.461260  mrr@2=0.569507  mrr@5=0.635989  mrr@10=0.643825  mrr@20=0.646094
f1@1=0.402320  f1@2=0.443522  f1@5=0.349549  f1@10=0.222377  f1@20=0.125390

Saved new best checkpoint at epoch 2

Epoch 3/100: 100%|██████████| 820/820 [00:14<00:00, 58.39it/s, bpr=0.0352, c=2.67, loss=0.142]

[VAL]
recall@1=0.451094  recall@2=0.675944  recall@5=0.877964  recall@10=0.944046  recall@20=0.982930
precision@1=0.552823  precision@2=0.432903  precision@5=0.237435  precision@10=0.130339  precision@20=0.068379
ndcg@1=0.552823  ndcg@2=0.641533  ndcg@5=0.731304  ndcg@10=0.756081  ndcg@20=0.767289
hit_rate@1=0.552823  hit_rate@2=0.762581  hit_rate@5=0.920161  hit_rate@10=0.963710  hit_rate@20=0.991129
map@1=0.552823  map@2=0.604798  map@5=0.666095  map@10=0.680437  map@20=0.684651
mrr@1=0.552823  mrr@2=0.657823  mrr@5=0.703382  mrr@10=0.709529  mrr@20=0.711550
f1@1=0.481123  f1@2=0.507666  f1@5=0.360441  f1@10=0.222930  f1@20=0.125654

[TEST]
recall@1=0.446788  recall@2=0.674596  recall@5=0.877262  recall@10=0.946546  recall@20=0.983402
precision@1=0.548164  precision@2=0.432547  precision@5=0.237017  precision@10=0.130630  precision@20=0.068311
ndcg@1=0.548164  ndcg@2=0.638663  ndcg@5=0.729171  ndcg@10=0.754805  ndcg@20=0.765344
hit_rate@1=0.548164  hit_rate@2=0.762323  hit_rate@5=0.919217  hit_rate@10=0.964079  hit_rate@20=0.990899
map@1=0.548164  map@2=0.601321  map@5=0.663590  map@10=0.678240  map@20=0.682109
mrr@1=0.548164  mrr@2=0.655122  mrr@5=0.700592  mrr@10=0.706475  mrr@20=0.708464
f1@1=0.476741  f1@2=0.507271  f1@5=0.360087  f1@10=0.223559  f1@20=0.125585

Saved new best checkpoint at epoch 3

Epoch 4/100: 100%|██████████| 820/820 [00:13<00:00, 59.09it/s, bpr=0.0617, c=2.56, loss=0.164]

[VAL]
recall@1=0.470468  recall@2=0.695941  recall@5=0.891355  recall@10=0.948619  recall@20=0.985479
precision@1=0.576452  precision@2=0.445161  precision@5=0.241468  precision@10=0.131089  precision@20=0.068528
ndcg@1=0.576452  ndcg@2=0.662584  ndcg@5=0.749149  ndcg@10=0.770961  ndcg@20=0.781312
hit_rate@1=0.576452  hit_rate@2=0.783871  hit_rate@5=0.930081  hit_rate@10=0.966855  hit_rate@20=0.992903
map@1=0.576452  map@2=0.625706  map@5=0.685569  map@10=0.698573  map@20=0.702285
mrr@1=0.576452  mrr@2=0.680161  mrr@5=0.722422  mrr@10=0.727934  mrr@20=0.729445
f1@1=0.501693  f1@2=0.522435  f1@5=0.366328  f1@10=0.224156  f1@20=0.125936

[TEST]
recall@1=0.464065  recall@2=0.693799  recall@5=0.891597  recall@10=0.950422  recall@20=0.984945
precision@1=0.567091  precision@2=0.442896  precision@5=0.241334  precision@10=0.131137  precision@20=0.068408
ndcg@1=0.567091  ndcg@2=0.657569  ndcg@5=0.746585  ndcg@10=0.768355  ndcg@20=0.778500
hit_rate@1=0.567091  hit_rate@2=0.781089  hit_rate@5=0.928721  hit_rate@10=0.967542  hit_rate@20=0.991865
map@1=0.567091  map@2=0.620087  map@5=0.682635  map@10=0.695048  map@20=0.699040
mrr@1=0.567091  mrr@2=0.674090  mrr@5=0.717279  mrr@10=0.722231  mrr@20=0.724372
f1@1=0.494621  f1@2=0.520546  f1@5=0.366514  f1@10=0.224462  f1@20=0.125775

Saved new best checkpoint at epoch 4

Epoch 5/100: 100%|██████████| 820/820 [00:13<00:00, 58.81it/s, bpr=0.033, c=2.47, loss=0.132]

[VAL]
recall@1=0.488718  recall@2=0.716913  recall@5=0.902518  recall@10=0.948135  recall@20=0.984958
precision@1=0.596774  precision@2=0.457944  precision@5=0.244694  precision@10=0.130968  precision@20=0.068556
ndcg@1=0.596774  ndcg@2=0.683174  ndcg@5=0.765567  ndcg@10=0.782870  ndcg@20=0.793370
hit_rate@1=0.596774  hit_rate@2=0.805161  hit_rate@5=0.939032  hit_rate@10=0.966855  hit_rate@20=0.992258
map@1=0.596774  map@2=0.646028  map@5=0.704095  map@10=0.714512  map@20=0.718369
mrr@1=0.596774  mrr@2=0.700565  mrr@5=0.739813  mrr@10=0.743503  mrr@20=0.745178
f1@1=0.520763  f1@2=0.537806  f1@5=0.371139  f1@10=0.223977  f1@20=0.125972

[TEST]
recall@1=0.487973  recall@2=0.719397  recall@5=0.900186  recall@10=0.950987  recall@20=0.985047
precision@1=0.597294  precision@2=0.459810  precision@5=0.243976  precision@10=0.131218  precision@20=0.068400
ndcg@1=0.597294  ndcg@2=0.685059  ndcg@5=0.764916  ndcg@10=0.784209  ndcg@20=0.794049
hit_rate@1=0.597294  hit_rate@2=0.806298  hit_rate@5=0.935648  hit_rate@10=0.967622  hit_rate@20=0.992429
map@1=0.597294  map@2=0.648015  map@5=0.704311  map@10=0.715841  map@20=0.719546
mrr@1=0.597294  mrr@2=0.702199  mrr@5=0.739405  mrr@10=0.743976  mrr@20=0.745994
f1@1=0.520424  f1@2=0.540147  f1@5=0.370402  f1@10=0.224624  f1@20=0.125752

Epoch 6/100: 100%|██████████| 820/820 [00:13<00:00, 58.97it/s, bpr=0.0268, c=2.61, loss=0.131]

[VAL]
recall@1=0.492199  recall@2=0.702077  recall@5=0.905938  recall@10=0.952212  recall@20=0.984349
precision@1=0.598306  precision@2=0.448065  precision@5=0.245645  precision@10=0.131605  precision@20=0.068520
ndcg@1=0.598306  ndcg@2=0.674517  ndcg@5=0.765860  ndcg@10=0.783606  ndcg@20=0.792748
hit_rate@1=0.598306  hit_rate@2=0.790161  hit_rate@5=0.941129  hit_rate@10=0.969597  hit_rate@20=0.991855
map@1=0.598306  map@2=0.639577  map@5=0.703592  map@10=0.714450  map@20=0.717778
mrr@1=0.598306  mrr@2=0.694315  mrr@5=0.738479  mrr@10=0.742562  mrr@20=0.744122
f1@1=0.523480  f1@2=0.526305  f1@5=0.372592  f1@10=0.225054  f1@20=0.125892

[TEST]
recall@1=0.494616  recall@2=0.703287  recall@5=0.904608  recall@10=0.953669  recall@20=0.984604
precision@1=0.600354  precision@2=0.448655  precision@5=0.245055  precision@10=0.131620  precision@20=0.068367
ndcg@1=0.600354  ndcg@2=0.675517  ndcg@5=0.766290  ndcg@10=0.784754  ndcg@20=0.793642
hit_rate@1=0.600354  hit_rate@2=0.791318  hit_rate@5=0.939836  hit_rate@10=0.969636  hit_rate@20=0.992026
map@1=0.600354  map@2=0.640645  map@5=0.704796  map@10=0.715832  map@20=0.719127
mrr@1=0.600354  mrr@2=0.695755  mrr@5=0.739209  mrr@10=0.743102  mrr@20=0.744833
f1@1=0.525968  f1@2=0.527478  f1@5=0.372050  f1@10=0.225295  f1@20=0.125700

Epoch 7/100: 100%|██████████| 820/820 [00:13<00:00, 59.19it/s, bpr=0.0291, c=2.49, loss=0.129]

[VAL]
recall@1=0.491412  recall@2=0.704288  recall@5=0.906262  recall@10=0.951519  recall@20=0.984300
precision@1=0.600968  precision@2=0.449476  precision@5=0.245258  precision@10=0.131452  precision@20=0.068476
ndcg@1=0.600968  ndcg@2=0.675798  ndcg@5=0.765630  ndcg@10=0.783221  ndcg@20=0.792570
hit_rate@1=0.600968  hit_rate@2=0.794274  hit_rate@5=0.942742  hit_rate@10=0.968710  hit_rate@20=0.991774
map@1=0.600968  map@2=0.639798  map@5=0.702535  map@10=0.713569  map@20=0.717006
mrr@1=0.600968  mrr@2=0.697419  mrr@5=0.740468  mrr@10=0.744091  mrr@20=0.745677
f1@1=0.523745  f1@2=0.528093  f1@5=0.372252  f1@10=0.224813  f1@20=0.125824

[TEST]
recall@1=0.489045  recall@2=0.701690  recall@5=0.906196  recall@10=0.954318  recall@20=0.984060
precision@1=0.597133  precision@2=0.448333  precision@5=0.245345  precision@10=0.131709  precision@20=0.068343
ndcg@1=0.597133  ndcg@2=0.673179  ndcg@5=0.764505  ndcg@10=0.782976  ndcg@20=0.791574
hit_rate@1=0.597133  hit_rate@2=0.790834  hit_rate@5=0.941447  hit_rate@10=0.969958  hit_rate@20=0.991704
map@1=0.597133  map@2=0.637504  map@5=0.701556  map@10=0.712881  map@20=0.716108
mrr@1=0.597133  mrr@2=0.694185  mrr@5=0.737442  mrr@10=0.741466  mrr@20=0.743178
f1@1=0.521151  f1@2=0.526611  f1@5=0.372593  f1@10=0.225451  f1@20=0.125646

Epoch 8/100: 100%|██████████| 820/820 [00:13<00:00, 59.29it/s, bpr=0.0416, c=2.4, loss=0.138]

[VAL]
recall@1=0.484174  recall@2=0.705475  recall@5=0.906777  recall@10=0.950619  recall@20=0.985411
precision@1=0.591855  precision@2=0.451371  precision@5=0.246113  precision@10=0.131427  precision@20=0.068585
ndcg@1=0.591855  ndcg@2=0.674055  ndcg@5=0.763897  ndcg@10=0.780673  ndcg@20=0.790615
hit_rate@1=0.591855  hit_rate@2=0.797016  hit_rate@5=0.941774  hit_rate@10=0.967984  hit_rate@20=0.992661
map@1=0.591855  map@2=0.636855  map@5=0.700337  map@10=0.710620  map@20=0.714309
mrr@1=0.591855  mrr@2=0.694315  mrr@5=0.736435  mrr@10=0.740052  mrr@20=0.741867
f1@1=0.516118  f1@2=0.529674  f1@5=0.373146  f1@10=0.224694  f1@20=0.126010

[TEST]
recall@1=0.490302  recall@2=0.707209  recall@5=0.905484  recall@10=0.953772  recall@20=0.985239
precision@1=0.598341  precision@2=0.452279  precision@5=0.245715  precision@10=0.131653  precision@20=0.068444
ndcg@1=0.598341  ndcg@2=0.677660  ndcg@5=0.766078  ndcg@10=0.784359  ndcg@20=0.793349
hit_rate@1=0.598341  hit_rate@2=0.797358  hit_rate@5=0.939030  hit_rate@10=0.969797  hit_rate@20=0.992107
map@1=0.598341  map@2=0.641451  map@5=0.704123  map@10=0.714997  map@20=0.718337
mrr@1=0.598341  mrr@2=0.697970  mrr@5=0.738994  mrr@10=0.743334  mrr@20=0.744925
f1@1=0.522286  f1@2=0.530950  f1@5=0.372892  f1@10=0.225342  f1@20=0.125837

Epoch 9/100: 100%|██████████| 820/820 [00:13<00:00, 58.84it/s, bpr=0.0372, c=2.48, loss=0.137]

[VAL]
recall@1=0.503409  recall@2=0.713175  recall@5=0.909870  recall@10=0.953756  recall@20=0.984249
precision@1=0.614758  precision@2=0.456815  precision@5=0.247032  precision@10=0.131806  precision@20=0.068480
ndcg@1=0.614758  ndcg@2=0.687234  ndcg@5=0.774502  ndcg@10=0.791276  ndcg@20=0.799950
hit_rate@1=0.614758  hit_rate@2=0.804032  hit_rate@5=0.944435  hit_rate@10=0.970887  hit_rate@20=0.992177
map@1=0.614758  map@2=0.651915  map@5=0.713512  map@10=0.723794  map@20=0.726975
mrr@1=0.614758  mrr@2=0.709355  mrr@5=0.750202  mrr@10=0.753864  mrr@20=0.755334
f1@1=0.536350  f1@2=0.535740  f1@5=0.374498  f1@10=0.225371  f1@20=0.125829

[TEST]
recall@1=0.497555  recall@2=0.717086  recall@5=0.910434  recall@10=0.956307  recall@20=0.985583
precision@1=0.606798  precision@2=0.458964  precision@5=0.247084  precision@10=0.131951  precision@20=0.068456
ndcg@1=0.606798  ndcg@2=0.687254  ndcg@5=0.773118  ndcg@10=0.790504  ndcg@20=0.798895
hit_rate@1=0.606798  hit_rate@2=0.807587  hit_rate@5=0.942574  hit_rate@10=0.971569  hit_rate@20=0.992751
map@1=0.606798  map@2=0.650894  map@5=0.712005  map@10=0.722456  map@20=0.725564
mrr@1=0.606798  mrr@2=0.707233  mrr@5=0.746317  mrr@10=0.750370  mrr@20=0.751946
f1@1=0.529945  f1@2=0.538636  f1@5=0.374996  f1@10=0.225894  f1@20=0.125851

Epoch 10/100: 100%|██████████| 820/820 [00:13<00:00, 59.11it/s, bpr=0.0182, c=2.53, loss=0.119]

[VAL]
recall@1=0.523099  recall@2=0.750519  recall@5=0.918218  recall@10=0.955883  recall@20=0.983282
precision@1=0.637581  precision@2=0.479758  precision@5=0.249677  precision@10=0.132129  precision@20=0.068440
ndcg@1=0.637581  ndcg@2=0.720009  ndcg@5=0.793346  ndcg@10=0.807659  ndcg@20=0.815462
hit_rate@1=0.637581  hit_rate@2=0.839274  hit_rate@5=0.950242  hit_rate@10=0.972742  hit_rate@20=0.991210
map@1=0.637581  map@2=0.683629  map@5=0.736586  map@10=0.745338  map@20=0.748191
mrr@1=0.637581  mrr@2=0.738266  mrr@5=0.770708  mrr@10=0.773791  mrr@20=0.774963
f1@1=0.556892  f1@2=0.563195  f1@5=0.378335  f1@10=0.225911  f1@20=0.125741

[TEST]
recall@1=0.521363  recall@2=0.747637  recall@5=0.917967  recall@10=0.957956  recall@20=0.984599
precision@1=0.634907  precision@2=0.478214  precision@5=0.249597  precision@10=0.132225  precision@20=0.068367
ndcg@1=0.634907  ndcg@2=0.717237  ndcg@5=0.792293  ndcg@10=0.807420  ndcg@20=0.815176
hit_rate@1=0.634907  hit_rate@2=0.835132  hit_rate@5=0.948212  hit_rate@10=0.973099  hit_rate@20=0.992188
map@1=0.634907  map@2=0.681318  map@5=0.735613  map@10=0.744727  map@20=0.747706
mrr@1=0.634907  mrr@2=0.735180  mrr@5=0.768311  mrr@10=0.771736  mrr@20=0.773305
f1@1=0.555122  f1@2=0.561517  f1@5=0.378523  f1@10=0.226308  f1@20=0.125697

Epoch 11/100: 100%|██████████| 820/820 [00:13<00:00, 58.86it/s, bpr=0.0486, c=2.44, loss=0.146]

[VAL]
recall@1=0.504123  recall@2=0.729660  recall@5=0.917426  recall@10=0.958741  recall@20=0.985485
precision@1=0.614194  precision@2=0.464960  precision@5=0.248935  precision@10=0.132629  precision@20=0.068593
ndcg@1=0.614194  ndcg@2=0.697724  ndcg@5=0.780842  ndcg@10=0.796815  ndcg@20=0.804500
hit_rate@1=0.614194  hit_rate@2=0.819274  hit_rate@5=0.951452  hit_rate@10=0.974919  hit_rate@20=0.992500
map@1=0.614194  map@2=0.660706  map@5=0.719609  map@10=0.729613  map@20=0.732523
mrr@1=0.614194  mrr@2=0.716734  mrr@5=0.754996  mrr@10=0.758191  mrr@20=0.759577
f1@1=0.536685  f1@2=0.546674  f1@5=0.377487  f1@10=0.226700  f1@20=0.126042

[TEST]
recall@1=0.501666  recall@2=0.725354  recall@5=0.915707  recall@10=0.960517  recall@20=0.986239
precision@1=0.611791  precision@2=0.462065  precision@5=0.248131  precision@10=0.132514  precision@20=0.068549
ndcg@1=0.611791  ndcg@2=0.693474  ndcg@5=0.778695  ndcg@10=0.795929  ndcg@20=0.803325
hit_rate@1=0.611791  hit_rate@2=0.814594  hit_rate@5=0.948534  hit_rate@10=0.975274  hit_rate@20=0.992832
map@1=0.611791  map@2=0.656572  map@5=0.717613  map@10=0.728209  map@20=0.730936
mrr@1=0.611791  mrr@2=0.713193  mrr@5=0.752112  mrr@10=0.755971  mrr@20=0.757176
f1@1=0.534361  f1@2=0.543649  f1@5=0.376759  f1@10=0.226868  f1@20=0.126011

Saved new best checkpoint at epoch 11

Epoch 12/100: 100%|██████████| 820/820 [00:13<00:00, 59.19it/s, bpr=0.0281, c=2.53, loss=0.129]

[VAL]
recall@1=0.510659  recall@2=0.730397  recall@5=0.916046  recall@10=0.955891  recall@20=0.986206
precision@1=0.623790  precision@2=0.467016  precision@5=0.248645  precision@10=0.132089  precision@20=0.068629
ndcg@1=0.623790  ndcg@2=0.701693  ndcg@5=0.783338  ndcg@10=0.798644  ndcg@20=0.807332
hit_rate@1=0.623790  hit_rate@2=0.820565  hit_rate@5=0.950081  hit_rate@10=0.972742  hit_rate@20=0.993306
map@1=0.623790  map@2=0.665484  map@5=0.723320  map@10=0.732877  map@20=0.736132
mrr@1=0.623790  mrr@2=0.722137  mrr@5=0.759665  mrr@10=0.762803  mrr@20=0.764283
f1@1=0.544044  f1@2=0.548092  f1@5=0.376982  f1@10=0.225852  f1@20=0.126104

[TEST]
recall@1=0.514095  recall@2=0.734262  recall@5=0.917938  recall@10=0.959150  recall@20=0.986065
precision@1=0.628785  precision@2=0.470643  precision@5=0.249146  precision@10=0.132386  precision@20=0.068492
ndcg@1=0.628785  ndcg@2=0.706080  ndcg@5=0.786489  ndcg@10=0.802198  ndcg@20=0.809957
hit_rate@1=0.628785  hit_rate@2=0.824017  hit_rate@5=0.949501  hit_rate@10=0.974227  hit_rate@20=0.992912
map@1=0.628785  map@2=0.670163  map@5=0.727291  map@10=0.736899  map@20=0.739835
mrr@1=0.628785  mrr@2=0.726442  mrr@5=0.762665  mrr@10=0.766030  mrr@20=0.767413
f1@1=0.548100  f1@2=0.551928  f1@5=0.378101  f1@10=0.226599  f1@20=0.125930

Saved new best checkpoint at epoch 12

Epoch 13/100: 100%|██████████| 820/820 [00:13<00:00, 58.58it/s, bpr=0.0214, c=2.37, loss=0.116]

[VAL]
recall@1=0.503546  recall@2=0.727340  recall@5=0.921284  recall@10=0.957938  recall@20=0.985519
precision@1=0.614274  precision@2=0.464435  precision@5=0.250435  precision@10=0.132444  precision@20=0.068613
ndcg@1=0.614274  ndcg@2=0.696533  ndcg@5=0.782961  ndcg@10=0.797055  ndcg@20=0.804984
hit_rate@1=0.614274  hit_rate@2=0.817177  hit_rate@5=0.953710  hit_rate@10=0.974274  hit_rate@20=0.992581
map@1=0.614274  map@2=0.659819  map@5=0.721333  map@10=0.730259  map@20=0.733240
mrr@1=0.614274  mrr@2=0.715927  mrr@5=0.755805  mrr@10=0.758730  mrr@20=0.760044
f1@1=0.536228  f1@2=0.545449  f1@5=0.379509  f1@10=0.226427  f1@20=0.126073

[TEST]
recall@1=0.500854  recall@2=0.727528  recall@5=0.921278  recall@10=0.960887  recall@20=0.985459
precision@1=0.611147  precision@2=0.464199  precision@5=0.250048  precision@10=0.132571  precision@20=0.068456
ndcg@1=0.611147  ndcg@2=0.694818  ndcg@5=0.781858  ndcg@10=0.797004  ndcg@20=0.804102
hit_rate@1=0.611147  hit_rate@2=0.817413  hit_rate@5=0.952159  hit_rate@10=0.975757  hit_rate@20=0.992832
map@1=0.611147  map@2=0.657559  map@5=0.720198  map@10=0.729532  map@20=0.732211
mrr@1=0.611147  mrr@2=0.714079  mrr@5=0.753764  mrr@10=0.756926  mrr@20=0.758153
f1@1=0.533604  f1@2=0.545775  f1@5=0.379525  f1@10=0.226958  f1@20=0.125848

Epoch 14/100: 100%|██████████| 820/820 [00:13<00:00, 59.04it/s, bpr=0.0529, c=2.61, loss=0.157]

[VAL]
recall@1=0.525483  recall@2=0.756186  recall@5=0.922630  recall@10=0.956582  recall@20=0.984943
precision@1=0.640403  precision@2=0.483750  precision@5=0.251129  precision@10=0.132145  precision@20=0.068524
ndcg@1=0.640403  ndcg@2=0.725043  ndcg@5=0.797391  ndcg@10=0.810293  ndcg@20=0.818451
hit_rate@1=0.640403  hit_rate@2=0.843468  hit_rate@5=0.952823  hit_rate@10=0.973790  hit_rate@20=0.992823
map@1=0.640403  map@2=0.688851  map@5=0.741031  map@10=0.748903  map@20=0.751967
mrr@1=0.640403  mrr@2=0.741976  mrr@5=0.773609  mrr@10=0.776561  mrr@20=0.777917
f1@1=0.559380  f1@2=0.567702  f1@5=0.380455  f1@10=0.225992  f1@20=0.125909

[TEST]
recall@1=0.524639  recall@2=0.757078  recall@5=0.922737  recall@10=0.958827  recall@20=0.984954
precision@1=0.641028  precision@2=0.485301  precision@5=0.251031  precision@10=0.132257  precision@20=0.068400
ndcg@1=0.641028  ndcg@2=0.725615  ndcg@5=0.797809  ndcg@10=0.811405  ndcg@20=0.818991
hit_rate@1=0.641028  hit_rate@2=0.842703  hit_rate@5=0.951514  hit_rate@10=0.974307  hit_rate@20=0.992188
map@1=0.641028  map@2=0.689675  map@5=0.741812  map@10=0.749972  map@20=0.752872
mrr@1=0.641028  mrr@2=0.741825  mrr@5=0.773707  mrr@10=0.776766  mrr@20=0.778085
f1@1=0.559214  f1@2=0.569209  f1@5=0.380684  f1@10=0.226413  f1@20=0.125764

Epoch 15/100: 100%|██████████| 820/820 [00:13<00:00, 59.44it/s, bpr=0.0465, c=2.43, loss=0.144]

[VAL]
recall@1=0.510956  recall@2=0.739619  recall@5=0.914606  recall@10=0.959453  recall@20=0.985264
precision@1=0.622823  precision@2=0.472137  precision@5=0.248258  precision@10=0.132581  precision@20=0.068560
ndcg@1=0.622823  ndcg@2=0.707691  ndcg@5=0.784300  ndcg@10=0.801374  ndcg@20=0.808777
hit_rate@1=0.622823  hit_rate@2=0.827177  hit_rate@5=0.948065  hit_rate@10=0.976048  hit_rate@20=0.992581
map@1=0.622823  map@2=0.671190  map@5=0.725635  map@10=0.736013  map@20=0.738798
mrr@1=0.622823  mrr@2=0.725040  mrr@5=0.759968  mrr@10=0.763868  mrr@20=0.764964
f1@1=0.543964  f1@2=0.554635  f1@5=0.376385  f1@10=0.226692  f1@20=0.125986

[TEST]
recall@1=0.514213  recall@2=0.741445  recall@5=0.917052  recall@10=0.961676  recall@20=0.985442
precision@1=0.627577  precision@2=0.475234  precision@5=0.248776  precision@10=0.132708  precision@20=0.068440
ndcg@1=0.627577  ndcg@2=0.710820  ndcg@5=0.787454  ndcg@10=0.804311  ndcg@20=0.811268
hit_rate@1=0.627577  hit_rate@2=0.829897  hit_rate@5=0.949259  hit_rate@10=0.976079  hit_rate@20=0.992510
map@1=0.627577  map@2=0.674593  map@5=0.729133  map@10=0.739284  map@20=0.741986
mrr@1=0.627577  mrr@2=0.728697  mrr@5=0.763354  mrr@10=0.766969  mrr@20=0.768253
f1@1=0.547812  f1@2=0.557356  f1@5=0.377628  f1@10=0.227195  f1@20=0.125844

Epoch 16/100: 100%|██████████| 820/820 [00:14<00:00, 58.26it/s, bpr=0.0346, c=2.47, loss=0.133]

[VAL]
recall@1=0.514436  recall@2=0.742918  recall@5=0.922876  recall@10=0.960178  recall@20=0.985509
precision@1=0.626694  precision@2=0.473831  precision@5=0.250677  precision@10=0.132798  precision@20=0.068605
ndcg@1=0.626694  ndcg@2=0.711001  ndcg@5=0.790743  ndcg@10=0.805331  ndcg@20=0.812547
hit_rate@1=0.626694  hit_rate@2=0.830968  hit_rate@5=0.954677  hit_rate@10=0.976048  hit_rate@20=0.992823
map@1=0.626694  map@2=0.674375  map@5=0.731608  map@10=0.740878  map@20=0.743537
mrr@1=0.626694  mrr@2=0.728952  mrr@5=0.765114  mrr@10=0.768342  mrr@20=0.769462
f1@1=0.547627  f1@2=0.556947  f1@5=0.380008  f1@10=0.227028  f1@20=0.126052

[TEST]
recall@1=0.513474  recall@2=0.742869  recall@5=0.924092  recall@10=0.961166  recall@20=0.985597
precision@1=0.625403  precision@2=0.474146  precision@5=0.250870  precision@10=0.132692  precision@20=0.068468
ndcg@1=0.625403  ndcg@2=0.710253  ndcg@5=0.791055  ndcg@10=0.805214  ndcg@20=0.812293
hit_rate@1=0.625403  hit_rate@2=0.830622  hit_rate@5=0.954575  hit_rate@10=0.975596  hit_rate@20=0.992671
map@1=0.625403  map@2=0.673546  map@5=0.731880  map@10=0.740667  map@20=0.743365
mrr@1=0.625403  mrr@2=0.727891  mrr@5=0.764300  mrr@10=0.766998  mrr@20=0.768294
f1@1=0.546749  f1@2=0.557352  f1@5=0.380691  f1@10=0.227119  f1@20=0.125879

Epoch 17/100: 100%|██████████| 820/820 [00:13<00:00, 58.69it/s, bpr=0.077, c=2.41, loss=0.173]

[VAL]
recall@1=0.513282  recall@2=0.741035  recall@5=0.916532  recall@10=0.957672  recall@20=0.984749
precision@1=0.626935  precision@2=0.473548  precision@5=0.248968  precision@10=0.132274  precision@20=0.068524
ndcg@1=0.626935  ndcg@2=0.709776  ndcg@5=0.786838  ndcg@10=0.802533  ndcg@20=0.810292
hit_rate@1=0.626935  hit_rate@2=0.831613  hit_rate@5=0.948548  hit_rate@10=0.974274  hit_rate@20=0.992339
map@1=0.626935  map@2=0.672621  map@5=0.728082  map@10=0.737629  map@20=0.740513
mrr@1=0.626935  mrr@2=0.729395  mrr@5=0.763379  mrr@10=0.767171  mrr@20=0.768273
f1@1=0.546905  f1@2=0.556040  f1@5=0.377411  f1@10=0.226222  f1@20=0.125919

[TEST]
recall@1=0.510917  recall@2=0.740277  recall@5=0.916576  recall@10=0.959735  recall@20=0.984923
precision@1=0.624839  precision@2=0.474509  precision@5=0.249130  precision@10=0.132418  precision@20=0.068404
ndcg@1=0.624839  ndcg@2=0.708963  ndcg@5=0.786234  ndcg@10=0.802265  ndcg@20=0.809721
hit_rate@1=0.624839  hit_rate@2=0.830219  hit_rate@5=0.946762  hit_rate@10=0.974388  hit_rate@20=0.992268
map@1=0.624839  map@2=0.672056  map@5=0.727802  map@10=0.737164  map@20=0.740099
mrr@1=0.624839  mrr@2=0.727408  mrr@5=0.761532  mrr@10=0.765036  mrr@20=0.766584
f1@1=0.544588  f1@2=0.556448  f1@5=0.377875  f1@10=0.226683  f1@20=0.125762

Epoch 18/100: 100%|██████████| 820/820 [00:14<00:00, 58.21it/s, bpr=0.024, c=2.53, loss=0.125]

[VAL]
recall@1=0.525822  recall@2=0.758323  recall@5=0.921640  recall@10=0.956817  recall@20=0.983748
precision@1=0.639113  precision@2=0.483387  precision@5=0.250758  precision@10=0.132202  precision@20=0.068452
ndcg@1=0.639113  ndcg@2=0.725720  ndcg@5=0.797203  ndcg@10=0.810634  ndcg@20=0.818381
hit_rate@1=0.639113  hit_rate@2=0.845887  hit_rate@5=0.952016  hit_rate@10=0.973710  hit_rate@20=0.991774
map@1=0.639113  map@2=0.688992  map@5=0.740938  map@10=0.749198  map@20=0.752075
mrr@1=0.639113  mrr@2=0.742581  mrr@5=0.773410  mrr@10=0.776484  mrr@20=0.777777
f1@1=0.559308  f1@2=0.568305  f1@5=0.379907  f1@10=0.226048  f1@20=0.125769

[TEST]
recall@1=0.529853  recall@2=0.759847  recall@5=0.924888  recall@10=0.958114  recall@20=0.983340
precision@1=0.644491  precision@2=0.486308  precision@5=0.251514  precision@10=0.132152  precision@20=0.068239
ndcg@1=0.644491  ndcg@2=0.728971  ndcg@5=0.801120  ndcg@10=0.813747  ndcg@20=0.821067
hit_rate@1=0.644491  hit_rate@2=0.846891  hit_rate@5=0.953689  hit_rate@10=0.973260  hit_rate@20=0.991463
map@1=0.644491  map@2=0.693037  map@5=0.745441  map@10=0.753251  map@20=0.756016
mrr@1=0.644491  mrr@2=0.745611  mrr@5=0.776984  mrr@10=0.779625  mrr@20=0.780977
f1@1=0.563889  f1@2=0.570752  f1@5=0.381423  f1@10=0.226271  f1@20=0.125475

Epoch 19/100: 100%|██████████| 820/820 [00:14<00:00, 57.10it/s, bpr=0.0192, c=2.56, loss=0.122]

[VAL]
recall@1=0.518363  recall@2=0.742214  recall@5=0.920710  recall@10=0.957172  recall@20=0.983914
precision@1=0.630806  precision@2=0.473145  precision@5=0.250226  precision@10=0.132274  precision@20=0.068456
ndcg@1=0.630806  ndcg@2=0.711848  ndcg@5=0.790496  ndcg@10=0.804510  ndcg@20=0.812151
hit_rate@1=0.630806  hit_rate@2=0.831371  hit_rate@5=0.952016  hit_rate@10=0.973871  hit_rate@20=0.991774
map@1=0.630806  map@2=0.675363  map@5=0.731898  map@10=0.740602  map@20=0.743401
mrr@1=0.630806  mrr@2=0.731089  mrr@5=0.765860  mrr@10=0.768963  mrr@20=0.770178
f1@1=0.551672  f1@2=0.556147  f1@5=0.379211  f1@10=0.226181  f1@20=0.125798

[TEST]
recall@1=0.513197  recall@2=0.739453  recall@5=0.921626  recall@10=0.958848  recall@20=0.984138
precision@1=0.627014  precision@2=0.473019  precision@5=0.250338  precision@10=0.132297  precision@20=0.068371
ndcg@1=0.627014  ndcg@2=0.708685  ndcg@5=0.789083  ndcg@10=0.803251  ndcg@20=0.810661
hit_rate@1=0.627014  hit_rate@2=0.826675  hit_rate@5=0.951756  hit_rate@10=0.973985  hit_rate@20=0.991624
map@1=0.627014  map@2=0.672560  map@5=0.730123  map@10=0.738787  map@20=0.741646
mrr@1=0.627014  mrr@2=0.726844  mrr@5=0.763241  mrr@10=0.766195  mrr@20=0.767590
f1@1=0.547041  f1@2=0.555323  f1@5=0.379813  f1@10=0.226471  f1@20=0.125690

Epoch 20/100: 100%|██████████| 820/820 [00:14<00:00, 56.73it/s, bpr=0.0318, c=2.56, loss=0.134]

[VAL]
recall@1=0.514696  recall@2=0.748243  recall@5=0.920712  recall@10=0.956512  recall@20=0.985471
precision@1=0.628065  precision@2=0.478750  precision@5=0.250371  precision@10=0.132202  precision@20=0.068589
ndcg@1=0.628065  ndcg@2=0.715543  ndcg@5=0.790740  ndcg@10=0.804626  ndcg@20=0.812930
hit_rate@1=0.628065  hit_rate@2=0.836774  hit_rate@5=0.951210  hit_rate@10=0.973145  hit_rate@20=0.992823
map@1=0.628065  map@2=0.678569  map@5=0.732675  map@10=0.741289  map@20=0.744406
mrr@1=0.628065  mrr@2=0.732460  mrr@5=0.765484  mrr@10=0.768717  mrr@20=0.770050
f1@1=0.548214  f1@2=0.561752  f1@5=0.379342  f1@10=0.226056  f1@20=0.126022

[TEST]
recall@1=0.509615  recall@2=0.747016  recall@5=0.922348  recall@10=0.958252  recall@20=0.985525
precision@1=0.623872  precision@2=0.478375  precision@5=0.250757  precision@10=0.132297  precision@20=0.068504
ndcg@1=0.623872  ndcg@2=0.712839  ndcg@5=0.789870  ndcg@10=0.803550  ndcg@20=0.811517
hit_rate@1=0.623872  hit_rate@2=0.834085  hit_rate@5=0.951997  hit_rate@10=0.973421  hit_rate@20=0.992349
map@1=0.623872  map@2=0.675681  map@5=0.731208  map@10=0.739533  map@20=0.742625
mrr@1=0.623872  mrr@2=0.728938  mrr@5=0.763284  mrr@10=0.766160  mrr@20=0.767650
f1@1=0.543467  f1@2=0.561328  f1@5=0.380292  f1@10=0.226423  f1@20=0.125924

Epoch 21/100: 100%|██████████| 820/820 [00:14<00:00, 57.87it/s, bpr=0.0193, c=2.49, loss=0.119]

[VAL]
recall@1=0.509198  recall@2=0.745310  recall@5=0.919226  recall@10=0.957145  recall@20=0.986112
precision@1=0.622177  precision@2=0.476290  precision@5=0.249935  precision@10=0.132202  precision@20=0.068609
ndcg@1=0.622177  ndcg@2=0.711424  ndcg@5=0.787554  ndcg@10=0.802026  ndcg@20=0.810413
hit_rate@1=0.622177  hit_rate@2=0.834194  hit_rate@5=0.950726  hit_rate@10=0.974274  hit_rate@20=0.993226
map@1=0.622177  map@2=0.673831  map@5=0.728549  map@10=0.737388  map@20=0.740607
mrr@1=0.622177  mrr@2=0.728387  mrr@5=0.762114  mrr@10=0.765475  mrr@20=0.766929
f1@1=0.542551  f1@2=0.559095  f1@5=0.378704  f1@10=0.226075  f1@20=0.126078

[TEST]
recall@1=0.507836  recall@2=0.743587  recall@5=0.921573  recall@10=0.958529  recall@20=0.984821
precision@1=0.620973  precision@2=0.476683  precision@5=0.250451  precision@10=0.132168  precision@20=0.068363
ndcg@1=0.620973  ndcg@2=0.709878  ndcg@5=0.787986  ndcg@10=0.802050  ndcg@20=0.809591
hit_rate@1=0.620973  hit_rate@2=0.832474  hit_rate@5=0.951111  hit_rate@10=0.973905  hit_rate@20=0.992026
map@1=0.620973  map@2=0.672499  map@5=0.728775  map@10=0.737326  map@20=0.740129
mrr@1=0.620973  mrr@2=0.726522  mrr@5=0.761245  mrr@10=0.764361  mrr@20=0.765556
f1@1=0.541387  f1@2=0.559012  f1@5=0.379934  f1@10=0.226305  f1@20=0.125711

Epoch 22/100: 100%|██████████| 820/820 [00:14<00:00, 57.18it/s, bpr=0.0219, c=2.42, loss=0.119]

[VAL]
recall@1=0.511396  recall@2=0.749978  recall@5=0.924131  recall@10=0.959173  recall@20=0.986310
precision@1=0.625645  precision@2=0.479919  precision@5=0.251484  precision@10=0.132613  precision@20=0.068641
ndcg@1=0.625645  ndcg@2=0.715632  ndcg@5=0.791749  ndcg@10=0.805184  ndcg@20=0.812926
hit_rate@1=0.625645  hit_rate@2=0.838710  hit_rate@5=0.954113  hit_rate@10=0.975161  hit_rate@20=0.993548
map@1=0.625645  map@2=0.677964  map@5=0.732716  map@10=0.741104  map@20=0.743978
mrr@1=0.625645  mrr@2=0.731976  mrr@5=0.765641  mrr@10=0.768548  mrr@20=0.769740
f1@1=0.545066  f1@2=0.563042  f1@5=0.380960  f1@10=0.226732  f1@20=0.126122

[TEST]
recall@1=0.513395  recall@2=0.749275  recall@5=0.926184  recall@10=0.961180  recall@20=0.985599
precision@1=0.627819  precision@2=0.481194  precision@5=0.251724  precision@10=0.132659  precision@20=0.068424
ndcg@1=0.627819  ndcg@2=0.716607  ndcg@5=0.793751  ndcg@10=0.807246  ndcg@20=0.814389
hit_rate@1=0.627819  hit_rate@2=0.836582  hit_rate@5=0.955219  hit_rate@10=0.975918  hit_rate@20=0.992590
map@1=0.627819  map@2=0.679949  map@5=0.735121  map@10=0.743529  map@20=0.746342
mrr@1=0.627819  mrr@2=0.732402  mrr@5=0.766928  mrr@10=0.769864  mrr@20=0.771211
f1@1=0.547387  f1@2=0.563749  f1@5=0.381836  f1@10=0.227068  f1@20=0.125827

Saved new best checkpoint at epoch 22

Epoch 23/100: 100%|██████████| 820/820 [00:13<00:00, 58.76it/s, bpr=0.0543, c=2.37, loss=0.149]

[VAL]
recall@1=0.496452  recall@2=0.735090  recall@5=0.921567  recall@10=0.958893  recall@20=0.985985
precision@1=0.606048  precision@2=0.468185  precision@5=0.250500  precision@10=0.132613  precision@20=0.068649
ndcg@1=0.606048  ndcg@2=0.698698  ndcg@5=0.781900  ndcg@10=0.796360  ndcg@20=0.804153
hit_rate@1=0.606048  hit_rate@2=0.826048  hit_rate@5=0.952903  hit_rate@10=0.975161  hit_rate@20=0.993145
map@1=0.606048  map@2=0.659859  map@5=0.720008  map@10=0.729079  map@20=0.732031
mrr@1=0.606048  mrr@2=0.716210  mrr@5=0.753300  mrr@10=0.756555  mrr@20=0.757769
f1@1=0.528820  f1@2=0.550530  f1@5=0.379602  f1@10=0.226693  f1@20=0.126120

[TEST]
recall@1=0.499461  recall@2=0.733651  recall@5=0.923404  recall@10=0.961423  recall@20=0.985584
precision@1=0.610100  precision@2=0.468267  precision@5=0.250773  precision@10=0.132716  precision@20=0.068416
ndcg@1=0.610100  ndcg@2=0.698777  ndcg@5=0.783901  ndcg@10=0.798322  ndcg@20=0.805442
hit_rate@1=0.610100  hit_rate@2=0.823293  hit_rate@5=0.954414  hit_rate@10=0.976401  hit_rate@20=0.992832
map@1=0.610100  map@2=0.660821  map@5=0.722274  map@10=0.731084  map@20=0.733944
mrr@1=0.610100  mrr@2=0.716535  mrr@5=0.755336  mrr@10=0.758214  mrr@20=0.759538
f1@1=0.532300  f1@2=0.550372  f1@5=0.380482  f1@10=0.227165  f1@20=0.125812

Epoch 24/100: 100%|██████████| 820/820 [00:14<00:00, 57.62it/s, bpr=0.0415, c=2.51, loss=0.142]

[VAL]
recall@1=0.509238  recall@2=0.745316  recall@5=0.920748  recall@10=0.957575  recall@20=0.984790
precision@1=0.620726  precision@2=0.476250  precision@5=0.250419  precision@10=0.132339  precision@20=0.068569
ndcg@1=0.620726  ndcg@2=0.711040  ndcg@5=0.788201  ndcg@10=0.802399  ndcg@20=0.810203
hit_rate@1=0.620726  hit_rate@2=0.834919  hit_rate@5=0.951613  hit_rate@10=0.973952  hit_rate@20=0.992258
map@1=0.620726  map@2=0.673327  map@5=0.729160  map@10=0.737948  map@20=0.740842
mrr@1=0.620726  mrr@2=0.727702  mrr@5=0.761754  mrr@10=0.764996  mrr@20=0.766166
f1@1=0.542118  f1@2=0.559134  f1@5=0.379452  f1@10=0.226286  f1@20=0.125967

[TEST]
recall@1=0.513064  recall@2=0.743460  recall@5=0.923371  recall@10=0.960720  recall@20=0.984963
precision@1=0.626450  precision@2=0.475797  precision@5=0.250805  precision@10=0.132555  precision@20=0.068400
ndcg@1=0.626450  ndcg@2=0.711471  ndcg@5=0.790692  ndcg@10=0.805017  ndcg@20=0.812153
hit_rate@1=0.626450  hit_rate@2=0.831508  hit_rate@5=0.953930  hit_rate@10=0.976160  hit_rate@20=0.991865
map@1=0.626450  map@2=0.674835  map@5=0.731623  map@10=0.740450  map@20=0.743308
mrr@1=0.626450  mrr@2=0.729100  mrr@5=0.764637  mrr@10=0.767686  mrr@20=0.768991
f1@1=0.546759  f1@2=0.558520  f1@5=0.380493  f1@10=0.226905  f1@20=0.125781

Epoch 25/100: 100%|██████████| 820/820 [00:14<00:00, 57.73it/s, bpr=0.0208, c=2.45, loss=0.119]

[VAL]
recall@1=0.508286  recall@2=0.736536  recall@5=0.913848  recall@10=0.957274  recall@20=0.986250
precision@1=0.620242  precision@2=0.471573  precision@5=0.248597  precision@10=0.132347  precision@20=0.068653
ndcg@1=0.620242  ndcg@2=0.705253  ndcg@5=0.782939  ndcg@10=0.799285  ndcg@20=0.807677
hit_rate@1=0.620242  hit_rate@2=0.826290  hit_rate@5=0.946290  hit_rate@10=0.973790  hit_rate@20=0.993387
map@1=0.620242  map@2=0.668488  map@5=0.724007  map@10=0.733791  map@20=0.736998
mrr@1=0.620242  mrr@2=0.723226  mrr@5=0.758247  mrr@10=0.762017  mrr@20=0.763450
f1@1=0.541277  f1@2=0.553042  f1@5=0.376654  f1@10=0.226260  f1@20=0.126137

[TEST]
recall@1=0.510920  recall@2=0.737758  recall@5=0.913286  recall@10=0.959662  recall@20=0.986031
precision@1=0.624597  precision@2=0.472898  precision@5=0.248164  precision@10=0.132458  precision@20=0.068496
ndcg@1=0.624597  ndcg@2=0.707133  ndcg@5=0.783794  ndcg@10=0.801351  ndcg@20=0.809046
hit_rate@1=0.624597  hit_rate@2=0.826353  hit_rate@5=0.945876  hit_rate@10=0.974952  hit_rate@20=0.992510
map@1=0.624597  map@2=0.670808  map@5=0.725302  map@10=0.735809  map@20=0.738826
mrr@1=0.624597  mrr@2=0.725515  mrr@5=0.760159  mrr@10=0.764243  mrr@20=0.765561
f1@1=0.544663  f1@2=0.554650  f1@5=0.376415  f1@10=0.226732  f1@20=0.125938

Epoch 26/100: 100%|██████████| 820/820 [00:13<00:00, 58.57it/s, bpr=0.0317, c=2.55, loss=0.133]

[VAL]
recall@1=0.509910  recall@2=0.745479  recall@5=0.917618  recall@10=0.956316  recall@20=0.986641
precision@1=0.622903  precision@2=0.476653  precision@5=0.249629  precision@10=0.132210  precision@20=0.068669
ndcg@1=0.622903  ndcg@2=0.711442  ndcg@5=0.787019  ndcg@10=0.801736  ndcg@20=0.810365
hit_rate@1=0.622903  hit_rate@2=0.834839  hit_rate@5=0.949355  hit_rate@10=0.973145  hit_rate@20=0.993468
map@1=0.622903  map@2=0.673770  map@5=0.728322  map@10=0.737247  map@20=0.740438
mrr@1=0.622903  mrr@2=0.728427  mrr@5=0.762149  mrr@10=0.765410  mrr@20=0.766622
f1@1=0.543267  f1@2=0.559489  f1@5=0.378242  f1@10=0.226069  f1@20=0.126186

[TEST]
recall@1=0.508388  recall@2=0.742616  recall@5=0.919317  recall@10=0.958482  recall@20=0.986440
precision@1=0.622664  precision@2=0.475878  precision@5=0.249774  precision@10=0.132329  precision@20=0.068549
ndcg@1=0.622664  ndcg@2=0.709815  ndcg@5=0.786967  ndcg@10=0.801986  ndcg@20=0.810255
hit_rate@1=0.622664  hit_rate@2=0.831024  hit_rate@5=0.949984  hit_rate@10=0.973744  hit_rate@20=0.993154
map@1=0.622664  map@2=0.672701  map@5=0.727838  map@10=0.737024  map@20=0.740286
mrr@1=0.622664  mrr@2=0.727287  mrr@5=0.761546  mrr@10=0.764949  mrr@20=0.766719
f1@1=0.542236  f1@2=0.558143  f1@5=0.378891  f1@10=0.226496  f1@20=0.126018

Epoch 27/100: 100%|██████████| 820/820 [00:13<00:00, 58.67it/s, bpr=0.0337, c=2.48, loss=0.133]

[VAL]
recall@1=0.509323  recall@2=0.743136  recall@5=0.919691  recall@10=0.956690  recall@20=0.986495
precision@1=0.622339  precision@2=0.474677  precision@5=0.250048  precision@10=0.132194  precision@20=0.068685
ndcg@1=0.622339  ndcg@2=0.709582  ndcg@5=0.787270  ndcg@10=0.801492  ndcg@20=0.809965
hit_rate@1=0.622339  hit_rate@2=0.833145  hit_rate@5=0.950565  hit_rate@10=0.973387  hit_rate@20=0.993468
map@1=0.622339  map@2=0.671835  map@5=0.728063  map@10=0.736799  map@20=0.739875
mrr@1=0.622339  mrr@2=0.727540  mrr@5=0.761750  mrr@10=0.764998  mrr@20=0.766199
f1@1=0.542625  f1@2=0.557431  f1@5=0.378990  f1@10=0.226058  f1@20=0.126189

[TEST]
recall@1=0.508046  recall@2=0.742284  recall@5=0.921415  recall@10=0.959288  recall@20=0.985619
precision@1=0.621215  precision@2=0.475435  precision@5=0.250548  precision@10=0.132386  precision@20=0.068436
ndcg@1=0.621215  ndcg@2=0.709140  ndcg@5=0.787751  ndcg@10=0.802116  ndcg@20=0.809900
hit_rate@1=0.621215  hit_rate@2=0.831830  hit_rate@5=0.951836  hit_rate@10=0.974227  hit_rate@20=0.992751
map@1=0.621215  map@2=0.671714  map@5=0.728305  map@10=0.737063  map@20=0.740141
mrr@1=0.621215  mrr@2=0.726724  mrr@5=0.761325  mrr@10=0.764394  mrr@20=0.766068
f1@1=0.541616  f1@2=0.557792  f1@5=0.379930  f1@10=0.226611  f1@20=0.125837

Epoch 28/100: 100%|██████████| 820/820 [00:14<00:00, 57.68it/s, bpr=0.0187, c=2.49, loss=0.118]

[VAL]
recall@1=0.494463  recall@2=0.729321  recall@5=0.915625  recall@10=0.956923  recall@20=0.985956
precision@1=0.605968  precision@2=0.466573  precision@5=0.248694  precision@10=0.132258  precision@20=0.068625
ndcg@1=0.605968  ndcg@2=0.694932  ndcg@5=0.776630  ndcg@10=0.792419  ndcg@20=0.800801
hit_rate@1=0.605968  hit_rate@2=0.819677  hit_rate@5=0.948306  hit_rate@10=0.973468  hit_rate@20=0.993145
map@1=0.605968  map@2=0.656794  map@5=0.714733  map@10=0.724328  map@20=0.727509
mrr@1=0.605968  mrr@2=0.712863  mrr@5=0.749871  mrr@10=0.753483  mrr@20=0.754878
f1@1=0.527425  f1@2=0.547424  f1@5=0.377011  f1@10=0.226161  f1@20=0.126087

[TEST]
recall@1=0.498104  recall@2=0.728130  recall@5=0.914491  recall@10=0.959337  recall@20=0.984880
precision@1=0.609617  precision@2=0.466656  precision@5=0.248067  precision@10=0.132337  precision@20=0.068396
ndcg@1=0.609617  ndcg@2=0.695518  ndcg@5=0.777632  ndcg@10=0.794640  ndcg@20=0.802152
hit_rate@1=0.609617  hit_rate@2=0.817252  hit_rate@5=0.946601  hit_rate@10=0.974791  hit_rate@20=0.991785
map@1=0.609617  map@2=0.658445  map@5=0.716863  map@10=0.726973  map@20=0.729947
mrr@1=0.609617  mrr@2=0.713394  mrr@5=0.750949  mrr@10=0.754838  mrr@20=0.756144
f1@1=0.531138  f1@2=0.547344  f1@5=0.376514  f1@10=0.226539  f1@20=0.125761

Epoch 29/100: 100%|██████████| 820/820 [00:14<00:00, 57.82it/s, bpr=0.0267, c=2.61, loss=0.131]

[VAL]
recall@1=0.505155  recall@2=0.741801  recall@5=0.921572  recall@10=0.956728  recall@20=0.986908
precision@1=0.617339  precision@2=0.473226  precision@5=0.250742  precision@10=0.132234  precision@20=0.068710
ndcg@1=0.617339  ndcg@2=0.706771  ndcg@5=0.786892  ndcg@10=0.800252  ndcg@20=0.808812
hit_rate@1=0.617339  hit_rate@2=0.830161  hit_rate@5=0.952258  hit_rate@10=0.973790  hit_rate@20=0.993790
map@1=0.617339  map@2=0.668911  map@5=0.726974  map@10=0.735151  map@20=0.738299
mrr@1=0.617339  mrr@2=0.723427  mrr@5=0.759710  mrr@10=0.762643  mrr@20=0.763813
f1@1=0.538328  f1@2=0.556019  f1@5=0.379854  f1@10=0.226096  f1@20=0.126232

[TEST]
recall@1=0.500329  recall@2=0.745023  recall@5=0.923419  recall@10=0.959202  recall@20=0.986089
precision@1=0.611952  precision@2=0.476562  precision@5=0.250999  precision@10=0.132410  precision@20=0.068512
ndcg@1=0.611952  ndcg@2=0.707793  ndcg@5=0.786374  ndcg@10=0.800032  ndcg@20=0.807962
hit_rate@1=0.611952  hit_rate@2=0.832877  hit_rate@5=0.953367  hit_rate@10=0.974307  hit_rate@20=0.992590
map@1=0.611952  map@2=0.669499  map@5=0.725995  map@10=0.734410  map@20=0.737541
mrr@1=0.611952  mrr@2=0.722737  mrr@5=0.757665  mrr@10=0.760565  mrr@20=0.762207
f1@1=0.533364  f1@2=0.559470  f1@5=0.380748  f1@10=0.226642  f1@20=0.125966

Epoch 30/100: 100%|██████████| 820/820 [00:14<00:00, 57.59it/s, bpr=0.0983, c=2.4, loss=0.194]

[VAL]
recall@1=0.494512  recall@2=0.735424  recall@5=0.918181  recall@10=0.959529  recall@20=0.986750
precision@1=0.603710  precision@2=0.469032  precision@5=0.249435  precision@10=0.132516  precision@20=0.068661
ndcg@1=0.603710  ndcg@2=0.698454  ndcg@5=0.779137  ndcg@10=0.794805  ndcg@20=0.802755
hit_rate@1=0.603710  hit_rate@2=0.825161  hit_rate@5=0.950081  hit_rate@10=0.975887  hit_rate@20=0.993871
map@1=0.603710  map@2=0.659798  map@5=0.717677  map@10=0.727121  map@20=0.730202
mrr@1=0.603710  mrr@2=0.714395  mrr@5=0.750687  mrr@10=0.754244  mrr@20=0.755531
f1@1=0.526681  f1@2=0.551118  f1@5=0.378088  f1@10=0.226656  f1@20=0.126170

[TEST]
recall@1=0.494310  recall@2=0.733077  recall@5=0.920070  recall@10=0.962574  recall@20=0.985718
precision@1=0.603093  precision@2=0.467421  precision@5=0.249581  precision@10=0.132853  precision@20=0.068464
ndcg@1=0.603093  ndcg@2=0.696364  ndcg@5=0.780022  ndcg@10=0.796207  ndcg@20=0.803000
hit_rate@1=0.603093  hit_rate@2=0.822326  hit_rate@5=0.951836  hit_rate@10=0.976885  hit_rate@20=0.992510
map@1=0.603093  map@2=0.658002  map@5=0.718291  map@10=0.728188  map@20=0.730860
mrr@1=0.603093  mrr@2=0.712750  mrr@5=0.750769  mrr@10=0.754201  mrr@20=0.755414
f1@1=0.526480  f1@2=0.549618  f1@5=0.378821  f1@10=0.227407  f1@20=0.125881

Epoch 31/100: 100%|██████████| 820/820 [00:14<00:00, 57.95it/s, bpr=0.035, c=2.55, loss=0.137]

[VAL]
recall@1=0.514296  recall@2=0.750950  recall@5=0.922844  recall@10=0.961308  recall@20=0.986351
precision@1=0.626452  precision@2=0.479516  precision@5=0.251016  precision@10=0.132806  precision@20=0.068625
ndcg@1=0.626452  ndcg@2=0.716605  ndcg@5=0.792449  ndcg@10=0.807066  ndcg@20=0.814229
hit_rate@1=0.626452  hit_rate@2=0.839597  hit_rate@5=0.953871  hit_rate@10=0.977500  hit_rate@20=0.993710
map@1=0.626452  map@2=0.679093  map@5=0.734025  map@10=0.743029  map@20=0.745674
mrr@1=0.626452  mrr@2=0.732944  mrr@5=0.766641  mrr@10=0.769931  mrr@20=0.770883
f1@1=0.547423  f1@2=0.563243  f1@5=0.380369  f1@10=0.227118  f1@20=0.126107

[TEST]
recall@1=0.513340  recall@2=0.748298  recall@5=0.926825  recall@10=0.964193  recall@20=0.985404
precision@1=0.624839  precision@2=0.478173  precision@5=0.251724  precision@10=0.133111  precision@20=0.068452
ndcg@1=0.624839  ndcg@2=0.714277  ndcg@5=0.793158  ndcg@10=0.807445  ndcg@20=0.813805
hit_rate@1=0.624839  hit_rate@2=0.837065  hit_rate@5=0.956508  hit_rate@10=0.978334  hit_rate@20=0.992590
map@1=0.624839  map@2=0.676949  map@5=0.733985  map@10=0.742824  map@20=0.745422
mrr@1=0.624839  mrr@2=0.731033  mrr@5=0.765672  mrr@10=0.768600  mrr@20=0.769924
f1@1=0.546463  f1@2=0.561764  f1@5=0.381978  f1@10=0.227847  f1@20=0.125857

Saved new best checkpoint at epoch 31

Epoch 32/100: 100%|██████████| 820/820 [00:14<00:00, 57.25it/s, bpr=0.0199, c=2.53, loss=0.121]

[VAL]
recall@1=0.511516  recall@2=0.747070  recall@5=0.919232  recall@10=0.955658  recall@20=0.986298
precision@1=0.624355  precision@2=0.478024  precision@5=0.249871  precision@10=0.132097  precision@20=0.068649
ndcg@1=0.624355  ndcg@2=0.713444  ndcg@5=0.788708  ndcg@10=0.802683  ndcg@20=0.811521
hit_rate@1=0.624355  hit_rate@2=0.834919  hit_rate@5=0.951210  hit_rate@10=0.972419  hit_rate@20=0.993306
map@1=0.624355  map@2=0.676331  map@5=0.730104  map@10=0.738794  map@20=0.742118
mrr@1=0.624355  mrr@2=0.729476  mrr@5=0.763565  mrr@10=0.766508  mrr@20=0.767960
f1@1=0.544810  f1@2=0.560857  f1@5=0.378702  f1@10=0.225868  f1@20=0.126138

[TEST]
recall@1=0.511982  recall@2=0.744663  recall@5=0.919974  recall@10=0.959879  recall@20=0.986199
precision@1=0.625564  precision@2=0.477448  precision@5=0.250193  precision@10=0.132571  precision@20=0.068508
ndcg@1=0.625564  ndcg@2=0.712422  ndcg@5=0.789359  ndcg@10=0.804406  ndcg@20=0.812112
hit_rate@1=0.625564  hit_rate@2=0.832394  hit_rate@5=0.950306  hit_rate@10=0.974710  hit_rate@20=0.992912
map@1=0.625564  map@2=0.675781  map@5=0.730972  map@10=0.740066  map@20=0.743081
mrr@1=0.625564  mrr@2=0.729140  mrr@5=0.763672  mrr@10=0.766999  mrr@20=0.768495
f1@1=0.545728  f1@2=0.559842  f1@5=0.379394  f1@10=0.226851  f1@20=0.125951

Epoch 33/100: 100%|██████████| 820/820 [00:14<00:00, 57.94it/s, bpr=0.0251, c=2.45, loss=0.123]

[VAL]
recall@1=0.512152  recall@2=0.744296  recall@5=0.919117  recall@10=0.959256  recall@20=0.986400
precision@1=0.625000  precision@2=0.477016  precision@5=0.250032  precision@10=0.132508  precision@20=0.068605
ndcg@1=0.625000  ndcg@2=0.712231  ndcg@5=0.788455  ndcg@10=0.803609  ndcg@20=0.811476
hit_rate@1=0.625000  hit_rate@2=0.833145  hit_rate@5=0.950323  hit_rate@10=0.975806  hit_rate@20=0.993548
map@1=0.625000  map@2=0.675423  map@5=0.729898  map@10=0.738977  map@20=0.742005
mrr@1=0.625000  mrr@2=0.729073  mrr@5=0.763223  mrr@10=0.766826  mrr@20=0.768113
f1@1=0.545420  f1@2=0.559204  f1@5=0.378849  f1@10=0.226603  f1@20=0.126079

[TEST]
recall@1=0.510161  recall@2=0.744236  recall@5=0.921619  recall@10=0.961349  recall@20=0.985276
precision@1=0.623067  precision@2=0.476764  precision@5=0.250258  precision@10=0.132708  precision@20=0.068416
ndcg@1=0.623067  ndcg@2=0.711075  ndcg@5=0.788909  ndcg@10=0.804209  ndcg@20=0.811177
hit_rate@1=0.623067  hit_rate@2=0.832233  hit_rate@5=0.952159  hit_rate@10=0.975999  hit_rate@20=0.992188
map@1=0.623067  map@2=0.674090  map@5=0.729835  map@10=0.739253  map@20=0.741961
mrr@1=0.623067  mrr@2=0.727650  mrr@5=0.762743  mrr@10=0.766080  mrr@20=0.767297
f1@1=0.543758  f1@2=0.559308  f1@5=0.379746  f1@10=0.227147  f1@20=0.125803

Epoch 34/100: 100%|██████████| 820/820 [00:14<00:00, 58.25it/s, bpr=0.0149, c=2.57, loss=0.118]

[VAL]
recall@1=0.507705  recall@2=0.757021  recall@5=0.924807  recall@10=0.961062  recall@20=0.986160
precision@1=0.619435  precision@2=0.483911  precision@5=0.251790  precision@10=0.132831  precision@20=0.068609
ndcg@1=0.619435  ndcg@2=0.718624  ndcg@5=0.792182  ndcg@10=0.805921  ndcg@20=0.813204
hit_rate@1=0.619435  hit_rate@2=0.845161  hit_rate@5=0.954516  hit_rate@10=0.976613  hit_rate@20=0.993306
map@1=0.619435  map@2=0.679960  map@5=0.733537  map@10=0.741864  map@20=0.744639
mrr@1=0.619435  mrr@2=0.732218  mrr@5=0.764387  mrr@10=0.767430  mrr@20=0.768686
f1@1=0.540566  f1@2=0.568034  f1@5=0.381415  f1@10=0.227126  f1@20=0.126082

[TEST]
recall@1=0.508144  recall@2=0.758138  recall@5=0.928262  recall@10=0.963836  recall@20=0.985500
precision@1=0.620168  precision@2=0.484536  precision@5=0.252336  precision@10=0.133111  precision@20=0.068488
ndcg@1=0.620168  ndcg@2=0.719132  ndcg@5=0.794357  ndcg@10=0.808077  ndcg@20=0.814367
hit_rate@1=0.620168  hit_rate@2=0.843428  hit_rate@5=0.957313  hit_rate@10=0.977771  hit_rate@20=0.992268
map@1=0.620168  map@2=0.680956  map@5=0.735662  map@10=0.744214  map@20=0.746621
mrr@1=0.620168  mrr@2=0.731878  mrr@5=0.765259  mrr@10=0.768175  mrr@20=0.769204
f1@1=0.541462  f1@2=0.569207  f1@5=0.382729  f1@10=0.227816  f1@20=0.125910

Epoch 35/100: 100%|██████████| 820/820 [00:14<00:00, 57.71it/s, bpr=0.0308, c=2.56, loss=0.133]

[VAL]
recall@1=0.501328  recall@2=0.737006  recall@5=0.920386  recall@10=0.958633  recall@20=0.986320
precision@1=0.612984  precision@2=0.471492  precision@5=0.250419  precision@10=0.132484  precision@20=0.068633
ndcg@1=0.612984  ndcg@2=0.702793  ndcg@5=0.783750  ndcg@10=0.798300  ndcg@20=0.806329
hit_rate@1=0.612984  hit_rate@2=0.826774  hit_rate@5=0.951532  hit_rate@10=0.974758  hit_rate@20=0.993468
map@1=0.612984  map@2=0.664980  map@5=0.723011  map@10=0.731914  map@20=0.734990
mrr@1=0.612984  mrr@2=0.719879  mrr@5=0.756508  mrr@10=0.759812  mrr@20=0.761141
f1@1=0.534242  f1@2=0.553161  f1@5=0.379421  f1@10=0.226563  f1@20=0.126123

[TEST]
recall@1=0.500496  recall@2=0.739120  recall@5=0.924038  recall@10=0.961330  recall@20=0.985310
precision@1=0.611227  precision@2=0.473019  precision@5=0.251015  precision@10=0.132732  precision@20=0.068428
ndcg@1=0.611227  ndcg@2=0.703787  ndcg@5=0.785535  ndcg@10=0.799828  ndcg@20=0.806846
hit_rate@1=0.611227  hit_rate@2=0.828286  hit_rate@5=0.954333  hit_rate@10=0.975999  hit_rate@20=0.992349
map@1=0.611227  map@2=0.665875  map@5=0.724555  map@10=0.733416  map@20=0.736150
mrr@1=0.611227  mrr@2=0.719757  mrr@5=0.756629  mrr@10=0.759603  mrr@20=0.760888
f1@1=0.533253  f1@2=0.555088  f1@5=0.380759  f1@10=0.227148  f1@20=0.125817

Epoch 36/100: 100%|██████████| 820/820 [00:14<00:00, 57.35it/s, bpr=0.0196, c=2.46, loss=0.118]

[VAL]
recall@1=0.504623  recall@2=0.734948  recall@5=0.920068  recall@10=0.960790  recall@20=0.986582
precision@1=0.615484  precision@2=0.470161  precision@5=0.250081  precision@10=0.132871  precision@20=0.068665
ndcg@1=0.615484  ndcg@2=0.702279  ndcg@5=0.783854  ndcg@10=0.799584  ndcg@20=0.807083
hit_rate@1=0.615484  hit_rate@2=0.825242  hit_rate@5=0.952581  hit_rate@10=0.976774  hit_rate@20=0.993548
map@1=0.615484  map@2=0.664960  map@5=0.723114  map@10=0.732864  map@20=0.735802
mrr@1=0.615484  mrr@2=0.720202  mrr@5=0.757302  mrr@10=0.760882  mrr@20=0.762078
f1@1=0.537337  f1@2=0.551719  f1@5=0.379062  f1@10=0.227169  f1@20=0.126173

[TEST]
recall@1=0.505427  recall@2=0.735158  recall@5=0.921915  recall@10=0.962325  recall@20=0.985908
precision@1=0.616785  precision@2=0.470280  precision@5=0.250209  precision@10=0.132885  precision@20=0.068524
ndcg@1=0.616785  ndcg@2=0.702822  ndcg@5=0.785189  ndcg@10=0.800696  ndcg@20=0.807610
hit_rate@1=0.616785  hit_rate@2=0.824098  hit_rate@5=0.953608  hit_rate@10=0.976643  hit_rate@20=0.992349
map@1=0.616785  map@2=0.665915  map@5=0.724426  map@10=0.734064  map@20=0.736792
mrr@1=0.616785  mrr@2=0.720602  mrr@5=0.758143  mrr@10=0.761267  mrr@20=0.762434
f1@1=0.538497  f1@2=0.552039  f1@5=0.379676  f1@10=0.227422  f1@20=0.125975

Epoch 37/100: 100%|██████████| 820/820 [00:14<00:00, 57.91it/s, bpr=0.0239, c=2.53, loss=0.125]

[VAL]
recall@1=0.500900  recall@2=0.739872  recall@5=0.919882  recall@10=0.961618  recall@20=0.986150
precision@1=0.612500  precision@2=0.473911  precision@5=0.250258  precision@10=0.132847  precision@20=0.068617
ndcg@1=0.612500  ndcg@2=0.704886  ndcg@5=0.783621  ndcg@10=0.799506  ndcg@20=0.806676
hit_rate@1=0.612500  hit_rate@2=0.828710  hit_rate@5=0.951613  hit_rate@10=0.977661  hit_rate@20=0.993468
map@1=0.612500  map@2=0.667117  map@5=0.723101  map@10=0.732717  map@20=0.735519
mrr@1=0.612500  mrr@2=0.720847  mrr@5=0.756368  mrr@10=0.760186  mrr@20=0.761350
f1@1=0.533891  f1@2=0.555764  f1@5=0.379204  f1@10=0.227221  f1@20=0.126091

[TEST]
recall@1=0.506064  recall@2=0.739418  recall@5=0.920769  recall@10=0.962471  recall@20=0.985478
precision@1=0.619040  precision@2=0.473220  precision@5=0.250129  precision@10=0.132909  precision@20=0.068460
ndcg@1=0.619040  ndcg@2=0.705943  ndcg@5=0.785719  ndcg@10=0.801658  ndcg@20=0.808338
hit_rate@1=0.619040  hit_rate@2=0.828689  hit_rate@5=0.951192  hit_rate@10=0.976562  hit_rate@20=0.992429
map@1=0.619040  map@2=0.668492  map@5=0.725641  map@10=0.735356  map@20=0.737910
mrr@1=0.619040  mrr@2=0.723623  mrr@5=0.759305  mrr@10=0.762771  mrr@20=0.763946
f1@1=0.539546  f1@2=0.555411  f1@5=0.379442  f1@10=0.227475  f1@20=0.125865

Epoch 38/100: 100%|██████████| 820/820 [00:14<00:00, 57.63it/s, bpr=0.0134, c=2.56, loss=0.116]

[VAL]
recall@1=0.498600  recall@2=0.735658  recall@5=0.923132  recall@10=0.960564  recall@20=0.986857
precision@1=0.608065  precision@2=0.467944  precision@5=0.250597  precision@10=0.132726  precision@20=0.068669
ndcg@1=0.608065  ndcg@2=0.699050  ndcg@5=0.783085  ndcg@10=0.797595  ndcg@20=0.804914
hit_rate@1=0.608065  hit_rate@2=0.823145  hit_rate@5=0.955081  hit_rate@10=0.976694  hit_rate@20=0.994032
map@1=0.608065  map@2=0.661048  map@5=0.721242  map@10=0.730363  map@20=0.732884
mrr@1=0.608065  mrr@2=0.715040  mrr@5=0.754301  mrr@10=0.757244  mrr@20=0.758043
f1@1=0.530886  f1@2=0.550698  f1@5=0.379977  f1@10=0.226994  f1@20=0.126177

[TEST]
recall@1=0.489542  recall@2=0.736754  recall@5=0.924594  recall@10=0.963236  recall@20=0.985220
precision@1=0.596488  precision@2=0.469394  precision@5=0.250773  precision@10=0.133006  precision@20=0.068420
ndcg@1=0.596488  ndcg@2=0.696761  ndcg@5=0.781013  ndcg@10=0.796061  ndcg@20=0.802656
hit_rate@1=0.596488  hit_rate@2=0.823695  hit_rate@5=0.954736  hit_rate@10=0.977287  hit_rate@20=0.992188
map@1=0.596488  map@2=0.657982  map@5=0.718595  map@10=0.727981  map@20=0.730718
mrr@1=0.596488  mrr@2=0.710656  mrr@5=0.748942  mrr@10=0.752297  mrr@20=0.753793
f1@1=0.521245  f1@2=0.552253  f1@5=0.380661  f1@10=0.227644  f1@20=0.125807

Epoch 39/100: 100%|██████████| 820/820 [00:14<00:00, 57.86it/s, bpr=0.0241, c=2.4, loss=0.12]

[VAL]
recall@1=0.493502  recall@2=0.723782  recall@5=0.915411  recall@10=0.959706  recall@20=0.986485
precision@1=0.604758  precision@2=0.463911  precision@5=0.248661  precision@10=0.132556  precision@20=0.068629
ndcg@1=0.604758  ndcg@2=0.690910  ndcg@5=0.775395  ndcg@10=0.792260  ndcg@20=0.799774
hit_rate@1=0.604758  hit_rate@2=0.814435  hit_rate@5=0.947823  hit_rate@10=0.976290  hit_rate@20=0.993468
map@1=0.604758  map@2=0.653266  map@5=0.713257  map@10=0.723386  map@20=0.726034
mrr@1=0.604758  mrr@2=0.709355  mrr@5=0.748218  mrr@10=0.752384  mrr@20=0.753246
f1@1=0.526386  f1@2=0.543778  f1@5=0.376925  f1@10=0.226713  f1@20=0.126118

[TEST]
recall@1=0.487934  recall@2=0.722327  recall@5=0.916275  recall@10=0.961328  recall@20=0.985194
precision@1=0.597616  precision@2=0.462709  precision@5=0.248631  precision@10=0.132619  precision@20=0.068416
ndcg@1=0.597616  ndcg@2=0.687794  ndcg@5=0.773318  ndcg@10=0.790483  ndcg@20=0.797731
hit_rate@1=0.597616  hit_rate@2=0.812097  hit_rate@5=0.948856  hit_rate@10=0.976160  hit_rate@20=0.992026
map@1=0.597616  map@2=0.649968  map@5=0.710383  map@10=0.720817  map@20=0.723855
mrr@1=0.597616  mrr@2=0.705098  mrr@5=0.744398  mrr@10=0.748094  mrr@20=0.749695
f1@1=0.520429  f1@2=0.542778  f1@5=0.377320  f1@10=0.227044  f1@20=0.125807

Epoch 40/100: 100%|██████████| 820/820 [00:14<00:00, 57.67it/s, bpr=0.0238, c=2.53, loss=0.125]

[VAL]
recall@1=0.499835  recall@2=0.743270  recall@5=0.924444  recall@10=0.962260  recall@20=0.987177
precision@1=0.611290  precision@2=0.474556  precision@5=0.251726  precision@10=0.132992  precision@20=0.068698
ndcg@1=0.611290  ndcg@2=0.706067  ndcg@5=0.786528  ndcg@10=0.800971  ndcg@20=0.808078
hit_rate@1=0.611290  hit_rate@2=0.833710  hit_rate@5=0.954919  hit_rate@10=0.978306  hit_rate@20=0.993790
map@1=0.611290  map@2=0.667036  map@5=0.725605  map@10=0.734437  map@20=0.737099
mrr@1=0.611290  mrr@2=0.722460  mrr@5=0.757977  mrr@10=0.761432  mrr@20=0.762288
f1@1=0.532757  f1@2=0.557365  f1@5=0.381281  f1@10=0.227398  f1@20=0.126233

[TEST]
recall@1=0.495224  recall@2=0.742183  recall@5=0.924357  recall@10=0.965028  recall@20=0.986147
precision@1=0.606153  precision@2=0.473703  precision@5=0.251401  precision@10=0.133183  precision@20=0.068444
ndcg@1=0.606153  ndcg@2=0.703286  ndcg@5=0.784495  ndcg@10=0.799785  ndcg@20=0.806061
hit_rate@1=0.606153  hit_rate@2=0.831910  hit_rate@5=0.953930  hit_rate@10=0.978898  hit_rate@20=0.992912
map@1=0.606153  map@2=0.663922  map@5=0.723061  map@10=0.732250  map@20=0.734796
mrr@1=0.606153  mrr@2=0.719072  mrr@5=0.754784  mrr@10=0.758049  mrr@20=0.759359
f1@1=0.528086  f1@2=0.556724  f1@5=0.381327  f1@10=0.228012  f1@20=0.125870

Epoch 41/100: 100%|██████████| 820/820 [00:14<00:00, 57.95it/s, bpr=0.044, c=2.38, loss=0.139]

[VAL]
recall@1=0.501291  recall@2=0.739564  recall@5=0.921912  recall@10=0.960504  recall@20=0.986138
precision@1=0.613387  precision@2=0.473306  precision@5=0.250645  precision@10=0.132758  precision@20=0.068585
ndcg@1=0.613387  ndcg@2=0.704657  ndcg@5=0.784537  ndcg@10=0.799367  ndcg@20=0.806694
hit_rate@1=0.613387  hit_rate@2=0.830242  hit_rate@5=0.953065  hit_rate@10=0.976371  hit_rate@20=0.993548
map@1=0.613387  map@2=0.666331  map@5=0.723438  map@10=0.732601  map@20=0.735310
mrr@1=0.613387  mrr@2=0.721815  mrr@5=0.757481  mrr@10=0.760860  mrr@20=0.761992
f1@1=0.534392  f1@2=0.555178  f1@5=0.379819  f1@10=0.226997  f1@20=0.126045

[TEST]
recall@1=0.501049  recall@2=0.732876  recall@5=0.922062  recall@10=0.961567  recall@20=0.984612
precision@1=0.613724  precision@2=0.468831  precision@5=0.250290  precision@10=0.132692  precision@20=0.068388
ndcg@1=0.613724  ndcg@2=0.699743  ndcg@5=0.783367  ndcg@10=0.798598  ndcg@20=0.805405
hit_rate@1=0.613724  hit_rate@2=0.820232  hit_rate@5=0.952642  hit_rate@10=0.976079  hit_rate@20=0.991624
map@1=0.613724  map@2=0.662814  map@5=0.722241  map@10=0.731723  map@20=0.734396
mrr@1=0.613724  mrr@2=0.716978  mrr@5=0.755355  mrr@10=0.758618  mrr@20=0.759909
f1@1=0.534379  f1@2=0.550367  f1@5=0.379802  f1@10=0.227173  f1@20=0.125748

Epoch 42/100: 100%|██████████| 820/820 [00:14<00:00, 57.68it/s, bpr=0.0545, c=2.43, loss=0.152]

[VAL]
recall@1=0.509525  recall@2=0.749633  recall@5=0.922796  recall@10=0.959587  recall@20=0.986124
precision@1=0.623226  precision@2=0.479476  precision@5=0.251129  precision@10=0.132581  precision@20=0.068613
ndcg@1=0.623226  ndcg@2=0.714657  ndcg@5=0.790204  ndcg@10=0.804288  ndcg@20=0.812034
hit_rate@1=0.623226  hit_rate@2=0.839032  hit_rate@5=0.953468  hit_rate@10=0.975806  hit_rate@20=0.993468
map@1=0.623226  map@2=0.676593  map@5=0.730937  map@10=0.739602  map@20=0.742620
mrr@1=0.623226  mrr@2=0.731250  mrr@5=0.764398  mrr@10=0.767652  mrr@20=0.768996
f1@1=0.543066  f1@2=0.562687  f1@5=0.380451  f1@10=0.226718  f1@20=0.126078

[TEST]
recall@1=0.513084  recall@2=0.749218  recall@5=0.924425  recall@10=0.961541  recall@20=0.985416
precision@1=0.628463  precision@2=0.480267  precision@5=0.251160  precision@10=0.132700  precision@20=0.068440
ndcg@1=0.628463  ndcg@2=0.715909  ndcg@5=0.792486  ndcg@10=0.806704  ndcg@20=0.813648
hit_rate@1=0.628463  hit_rate@2=0.837951  hit_rate@5=0.954897  hit_rate@10=0.976482  hit_rate@20=0.992268
map@1=0.628463  map@2=0.678500  map@5=0.733420  map@10=0.742270  map@20=0.744967
mrr@1=0.628463  mrr@2=0.733086  mrr@5=0.767271  mrr@10=0.770195  mrr@20=0.771281
f1@1=0.547371  f1@2=0.563199  f1@5=0.380960  f1@10=0.227157  f1@20=0.125847

Epoch 43/100: 100%|██████████| 820/820 [00:14<00:00, 57.91it/s, bpr=0.0166, c=2.45, loss=0.114]

[VAL]
recall@1=0.495120  recall@2=0.737042  recall@5=0.918579  recall@10=0.957416  recall@20=0.986455
precision@1=0.606855  precision@2=0.471169  precision@5=0.250113  precision@10=0.132298  precision@20=0.068637
ndcg@1=0.606855  ndcg@2=0.700113  ndcg@5=0.780402  ndcg@10=0.795140  ndcg@20=0.803508
hit_rate@1=0.606855  hit_rate@2=0.825887  hit_rate@5=0.950081  hit_rate@10=0.973629  hit_rate@20=0.993629
map@1=0.606855  map@2=0.661573  map@5=0.719099  map@10=0.728032  map@20=0.731179
mrr@1=0.606855  mrr@2=0.716290  mrr@5=0.752636  mrr@10=0.756012  mrr@20=0.757381
f1@1=0.528136  f1@2=0.553160  f1@5=0.378847  f1@10=0.226234  f1@20=0.126129

[TEST]
recall@1=0.493932  recall@2=0.732355  recall@5=0.919134  recall@10=0.961187  recall@20=0.985602
precision@1=0.605026  precision@2=0.468629  precision@5=0.249630  precision@10=0.132579  precision@20=0.068444
ndcg@1=0.605026  ndcg@2=0.696662  ndcg@5=0.779472  ndcg@10=0.795454  ndcg@20=0.802691
hit_rate@1=0.605026  hit_rate@2=0.820554  hit_rate@5=0.950628  hit_rate@10=0.976160  hit_rate@20=0.992429
map@1=0.605026  map@2=0.658787  map@5=0.717865  map@10=0.727597  map@20=0.730483
mrr@1=0.605026  mrr@2=0.712870  mrr@5=0.750899  mrr@10=0.754415  mrr@20=0.755770
f1@1=0.526782  f1@2=0.550061  f1@5=0.378733  f1@10=0.226985  f1@20=0.125862

Epoch 44/100: 100%|██████████| 820/820 [00:14<00:00, 58.16it/s, bpr=0.05, c=2.5, loss=0.15]

[VAL]
recall@1=0.510665  recall@2=0.753335  recall@5=0.925036  recall@10=0.961031  recall@20=0.986692
precision@1=0.624194  precision@2=0.481492  precision@5=0.251677  precision@10=0.132831  precision@20=0.068645
ndcg@1=0.624194  ndcg@2=0.717432  ndcg@5=0.792572  ndcg@10=0.806325  ndcg@20=0.813820
hit_rate@1=0.624194  hit_rate@2=0.842097  hit_rate@5=0.955161  hit_rate@10=0.977016  hit_rate@20=0.993790
map@1=0.624194  map@2=0.679234  map@5=0.733505  map@10=0.741981  map@20=0.744913
mrr@1=0.624194  mrr@2=0.733347  mrr@5=0.766239  mrr@10=0.769338  mrr@20=0.770662
f1@1=0.544171  f1@2=0.565270  f1@5=0.381327  f1@10=0.227131  f1@20=0.126143

[TEST]
recall@1=0.511939  recall@2=0.750870  recall@5=0.927940  recall@10=0.962928  recall@20=0.985562
precision@1=0.626369  precision@2=0.480871  precision@5=0.252384  precision@10=0.132917  precision@20=0.068448
ndcg@1=0.626369  ndcg@2=0.716307  ndcg@5=0.794341  ndcg@10=0.807675  ndcg@20=0.814221
hit_rate@1=0.626369  hit_rate@2=0.838595  hit_rate@5=0.956347  hit_rate@10=0.977368  hit_rate@20=0.992429
map@1=0.626369  map@2=0.678822  map@5=0.735280  map@10=0.743473  map@20=0.745970
mrr@1=0.626369  mrr@2=0.732281  mrr@5=0.766959  mrr@10=0.769784  mrr@20=0.770814
f1@1=0.545925  f1@2=0.564219  f1@5=0.382758  f1@10=0.227504  f1@20=0.125857

Epoch 45/100: 100%|██████████| 820/820 [00:14<00:00, 58.00it/s, bpr=0.0421, c=2.47, loss=0.141]

[VAL]
recall@1=0.495418  recall@2=0.727493  recall@5=0.916065  recall@10=0.959787  recall@20=0.986027
precision@1=0.605081  precision@2=0.464839  precision@5=0.248710  precision@10=0.132685  precision@20=0.068617
ndcg@1=0.605081  ndcg@2=0.693385  ndcg@5=0.777026  ndcg@10=0.793811  ndcg@20=0.801242
hit_rate@1=0.605081  hit_rate@2=0.816774  hit_rate@5=0.949919  hit_rate@10=0.975806  hit_rate@20=0.993145
map@1=0.605081  map@2=0.655806  map@5=0.715085  map@10=0.725431  map@20=0.728120
mrr@1=0.605081  mrr@2=0.710645  mrr@5=0.749859  mrr@10=0.753558  mrr@20=0.754533
f1@1=0.527776  f1@2=0.545778  f1@5=0.377044  f1@10=0.226878  f1@20=0.126088

[TEST]
recall@1=0.495335  recall@2=0.727946  recall@5=0.917408  recall@10=0.961167  recall@20=0.985722
precision@1=0.606637  precision@2=0.465770  precision@5=0.248744  precision@10=0.132651  precision@20=0.068468
ndcg@1=0.606637  ndcg@2=0.694300  ndcg@5=0.777849  ndcg@10=0.794630  ndcg@20=0.802004
hit_rate@1=0.606637  hit_rate@2=0.816608  hit_rate@5=0.949581  hit_rate@10=0.976160  hit_rate@20=0.992510
map@1=0.606637  map@2=0.656914  map@5=0.715942  map@10=0.726209  map@20=0.729232
mrr@1=0.606637  mrr@2=0.711904  mrr@5=0.750399  mrr@10=0.754089  mrr@20=0.755658
f1@1=0.528321  f1@2=0.546721  f1@5=0.377651  f1@10=0.227059  f1@20=0.125897

Epoch 46/100: 100%|██████████| 820/820 [00:14<00:00, 57.88it/s, bpr=0.0377, c=2.39, loss=0.133]

[VAL]
recall@1=0.496491  recall@2=0.737239  recall@5=0.919977  recall@10=0.959081  recall@20=0.985758
precision@1=0.606048  precision@2=0.471089  precision@5=0.250323  precision@10=0.132532  precision@20=0.068593
ndcg@1=0.606048  ndcg@2=0.700662  ndcg@5=0.781755  ndcg@10=0.796582  ndcg@20=0.804391
hit_rate@1=0.606048  hit_rate@2=0.824677  hit_rate@5=0.951290  hit_rate@10=0.975403  hit_rate@20=0.993145
map@1=0.606048  map@2=0.662843  map@5=0.720928  map@10=0.729957  map@20=0.732998
mrr@1=0.606048  mrr@2=0.715323  mrr@5=0.752542  mrr@10=0.755887  mrr@20=0.757176
f1@1=0.528739  f1@2=0.553100  f1@5=0.379209  f1@10=0.226599  f1@20=0.126034

[TEST]
recall@1=0.501995  recall@2=0.743078  recall@5=0.922105  recall@10=0.961205  recall@20=0.985420
precision@1=0.611550  precision@2=0.474670  precision@5=0.250451  precision@10=0.132651  precision@20=0.068428
ndcg@1=0.611550  ndcg@2=0.706428  ndcg@5=0.785454  ndcg@10=0.800489  ndcg@20=0.807599
hit_rate@1=0.611550  hit_rate@2=0.831105  hit_rate@5=0.952642  hit_rate@10=0.975757  hit_rate@20=0.992429
map@1=0.611550  map@2=0.668492  map@5=0.725206  map@10=0.734584  map@20=0.737368
mrr@1=0.611550  mrr@2=0.721368  mrr@5=0.756701  mrr@10=0.759944  mrr@20=0.761244
f1@1=0.534441  f1@2=0.557676  f1@5=0.380017  f1@10=0.227081  f1@20=0.125819

Epoch 47/100: 100%|██████████| 820/820 [00:14<00:00, 58.08it/s, bpr=0.035, c=2.58, loss=0.138]

[VAL]
recall@1=0.494398  recall@2=0.733579  recall@5=0.920386  recall@10=0.959790  recall@20=0.986850
precision@1=0.605242  precision@2=0.468548  precision@5=0.250097  precision@10=0.132694  precision@20=0.068714
ndcg@1=0.605242  ndcg@2=0.697197  ndcg@5=0.780047  ndcg@10=0.795086  ndcg@20=0.802909
hit_rate@1=0.605242  hit_rate@2=0.823226  hit_rate@5=0.952661  hit_rate@10=0.976048  hit_rate@20=0.993629
map@1=0.605242  map@2=0.658649  map@5=0.717901  map@10=0.727113  map@20=0.730092
mrr@1=0.605242  mrr@2=0.714073  mrr@5=0.751898  mrr@10=0.755087  mrr@20=0.756288
f1@1=0.527132  f1@2=0.550290  f1@5=0.379025  f1@10=0.226867  f1@20=0.126243

[TEST]
recall@1=0.496974  recall@2=0.732144  recall@5=0.921844  recall@10=0.961553  recall@20=0.985753
precision@1=0.608409  precision@2=0.467904  precision@5=0.250322  precision@10=0.132764  precision@20=0.068436
ndcg@1=0.608409  ndcg@2=0.697449  ndcg@5=0.781446  ndcg@10=0.796773  ndcg@20=0.803907
hit_rate@1=0.608409  hit_rate@2=0.820715  hit_rate@5=0.953125  hit_rate@10=0.975999  hit_rate@20=0.992751
map@1=0.608409  map@2=0.659693  map@5=0.719511  map@10=0.729055  map@20=0.731887
mrr@1=0.608409  mrr@2=0.714723  mrr@5=0.752929  mrr@10=0.756249  mrr@20=0.757622
f1@1=0.530084  f1@2=0.549530  f1@5=0.379818  f1@10=0.227231  f1@20=0.125854

Epoch 48/100: 100%|██████████| 820/820 [00:14<00:00, 58.10it/s, bpr=0.0281, c=2.66, loss=0.134]

[VAL]
recall@1=0.508317  recall@2=0.751290  recall@5=0.924248  recall@10=0.960269  recall@20=0.986015
precision@1=0.622500  precision@2=0.480484  precision@5=0.251565  precision@10=0.132637  precision@20=0.068633
ndcg@1=0.622500  ndcg@2=0.715300  ndcg@5=0.790893  ndcg@10=0.804628  ndcg@20=0.812148
hit_rate@1=0.622500  hit_rate@2=0.840887  hit_rate@5=0.955081  hit_rate@10=0.976855  hit_rate@20=0.993145
map@1=0.622500  map@2=0.676835  map@5=0.731311  map@10=0.739791  map@20=0.742728
mrr@1=0.622500  mrr@2=0.731613  mrr@5=0.764797  mrr@10=0.767925  mrr@20=0.769008
f1@1=0.541952  f1@2=0.563882  f1@5=0.381076  f1@10=0.226852  f1@20=0.126107

[TEST]
recall@1=0.502873  recall@2=0.750251  recall@5=0.926442  recall@10=0.962405  recall@20=0.986166
precision@1=0.616704  precision@2=0.481073  precision@5=0.252142  precision@10=0.132893  precision@20=0.068496
ndcg@1=0.616704  ndcg@2=0.712927  ndcg@5=0.790225  ndcg@10=0.803864  ndcg@20=0.810851
hit_rate@1=0.616704  hit_rate@2=0.838032  hit_rate@5=0.955702  hit_rate@10=0.977126  hit_rate@20=0.992832
map@1=0.616704  map@2=0.674533  map@5=0.730202  map@10=0.738560  map@20=0.741324
mrr@1=0.616704  mrr@2=0.727448  mrr@5=0.761840  mrr@10=0.764714  mrr@20=0.766042
f1@1=0.536621  f1@2=0.564096  f1@5=0.382316  f1@10=0.227427  f1@20=0.125942

Epoch 49/100: 100%|██████████| 820/820 [00:14<00:00, 58.02it/s, bpr=0.0289, c=2.47, loss=0.128]

[VAL]
recall@1=0.508513  recall@2=0.748656  recall@5=0.923289  recall@10=0.959237  recall@20=0.986349
precision@1=0.621129  precision@2=0.478427  precision@5=0.251016  precision@10=0.132468  precision@20=0.068653
ndcg@1=0.621129  ndcg@2=0.713153  ndcg@5=0.789739  ndcg@10=0.803780  ndcg@20=0.811505
hit_rate@1=0.621129  hit_rate@2=0.836613  hit_rate@5=0.954839  hit_rate@10=0.976290  hit_rate@20=0.993468
map@1=0.621129  map@2=0.675343  map@5=0.730102  map@10=0.739010  map@20=0.741845
mrr@1=0.621129  mrr@2=0.728992  mrr@5=0.763341  mrr@10=0.766773  mrr@20=0.767716
f1@1=0.541762  f1@2=0.561764  f1@5=0.380448  f1@10=0.226568  f1@20=0.126138

[TEST]
recall@1=0.508776  recall@2=0.746471  recall@5=0.924967  recall@10=0.961005  recall@20=0.985533
precision@1=0.622423  precision@2=0.478898  precision@5=0.251546  precision@10=0.132587  precision@20=0.068420
ndcg@1=0.622423  ndcg@2=0.712555  ndcg@5=0.790848  ndcg@10=0.804339  ndcg@20=0.811663
hit_rate@1=0.622423  hit_rate@2=0.834649  hit_rate@5=0.954172  hit_rate@10=0.976079  hit_rate@20=0.992671
map@1=0.622423  map@2=0.675278  map@5=0.731410  map@10=0.739543  map@20=0.742514
mrr@1=0.622423  mrr@2=0.728415  mrr@5=0.763687  mrr@10=0.766298  mrr@20=0.767872
f1@1=0.542430  f1@2=0.561357  f1@5=0.381516  f1@10=0.226988  f1@20=0.125816

Epoch 50/100: 100%|██████████| 820/820 [00:14<00:00, 57.57it/s, bpr=0.0226, c=2.55, loss=0.124]

[VAL]
recall@1=0.510252  recall@2=0.745910  recall@5=0.919112  recall@10=0.958237  recall@20=0.986078
precision@1=0.624032  precision@2=0.477581  precision@5=0.250065  precision@10=0.132403  precision@20=0.068641
ndcg@1=0.624032  ndcg@2=0.712331  ndcg@5=0.787939  ndcg@10=0.802748  ndcg@20=0.810742
hit_rate@1=0.624032  hit_rate@2=0.834516  hit_rate@5=0.950323  hit_rate@10=0.975000  hit_rate@20=0.993468
map@1=0.624032  map@2=0.674980  map@5=0.729135  map@10=0.738087  map@20=0.741071
mrr@1=0.624032  mrr@2=0.728992  mrr@5=0.762797  mrr@10=0.766120  mrr@20=0.767347
f1@1=0.543851  f1@2=0.560195  f1@5=0.378874  f1@10=0.226436  f1@20=0.126105

[TEST]
recall@1=0.505454  recall@2=0.741448  recall@5=0.920330  recall@10=0.961051  recall@20=0.985050
precision@1=0.619040  precision@2=0.475757  precision@5=0.250113  precision@10=0.132708  precision@20=0.068428
ndcg@1=0.619040  ndcg@2=0.708141  ndcg@5=0.786283  ndcg@10=0.801867  ndcg@20=0.808900
hit_rate@1=0.619040  hit_rate@2=0.830622  hit_rate@5=0.950628  hit_rate@10=0.975757  hit_rate@20=0.992026
map@1=0.619040  map@2=0.670747  map@5=0.726627  map@10=0.736154  map@20=0.738909
mrr@1=0.619040  mrr@2=0.725113  mrr@5=0.759907  mrr@10=0.763487  mrr@20=0.764836
f1@1=0.539152  f1@2=0.557584  f1@5=0.379395  f1@10=0.227129  f1@20=0.125813

Epoch 51/100: 100%|██████████| 820/820 [00:14<00:00, 57.89it/s, bpr=0.0246, c=2.52, loss=0.125]

[VAL]
recall@1=0.498577  recall@2=0.736846  recall@5=0.916226  recall@10=0.956401  recall@20=0.986180
precision@1=0.610565  precision@2=0.472177  precision@5=0.249145  precision@10=0.132113  precision@20=0.068609
ndcg@1=0.610565  ndcg@2=0.702093  ndcg@5=0.780347  ndcg@10=0.795663  ndcg@20=0.804342
hit_rate@1=0.610565  hit_rate@2=0.827177  hit_rate@5=0.948226  hit_rate@10=0.973306  hit_rate@20=0.993306
map@1=0.610565  map@2=0.663972  map@5=0.719721  map@10=0.728992  map@20=0.732357
mrr@1=0.610565  mrr@2=0.718992  mrr@5=0.753980  mrr@10=0.757664  mrr@20=0.759161
f1@1=0.531563  f1@2=0.553547  f1@5=0.377576  f1@10=0.225959  f1@20=0.126074

[TEST]
recall@1=0.498643  recall@2=0.735027  recall@5=0.915820  recall@10=0.959936  recall@20=0.986255
precision@1=0.610664  precision@2=0.471126  precision@5=0.248889  precision@10=0.132498  precision@20=0.068520
ndcg@1=0.610664  ndcg@2=0.700630  ndcg@5=0.780441  ndcg@10=0.797012  ndcg@20=0.804639
hit_rate@1=0.610664  hit_rate@2=0.824984  hit_rate@5=0.947407  hit_rate@10=0.975032  hit_rate@20=0.993073
map@1=0.610664  map@2=0.662734  map@5=0.720147  map@10=0.729983  map@20=0.732871
mrr@1=0.610664  mrr@2=0.717703  mrr@5=0.753759  mrr@10=0.757456  mrr@20=0.758814
f1@1=0.531786  f1@2=0.552461  f1@5=0.377483  f1@10=0.226763  f1@20=0.125968

Epoch 52/100: 100%|██████████| 820/820 [00:13<00:00, 58.66it/s, bpr=0.0429, c=2.5, loss=0.143]

[VAL]
recall@1=0.502506  recall@2=0.739443  recall@5=0.920656  recall@10=0.958336  recall@20=0.985835
precision@1=0.613790  precision@2=0.472218  precision@5=0.250323  precision@10=0.132468  precision@20=0.068597
ndcg@1=0.613790  ndcg@2=0.704489  ndcg@5=0.784567  ndcg@10=0.799074  ndcg@20=0.807006
hit_rate@1=0.613790  hit_rate@2=0.828145  hit_rate@5=0.952581  hit_rate@10=0.975000  hit_rate@20=0.993306
map@1=0.613790  map@2=0.666673  map@5=0.723928  map@10=0.732951  map@20=0.735959
mrr@1=0.613790  mrr@2=0.720968  mrr@5=0.757470  mrr@10=0.760727  mrr@20=0.761979
f1@1=0.535357  f1@2=0.554549  f1@5=0.379326  f1@10=0.226493  f1@20=0.126043

[TEST]
recall@1=0.501410  recall@2=0.737911  recall@5=0.922169  recall@10=0.960509  recall@20=0.985928
precision@1=0.611872  precision@2=0.471811  precision@5=0.250515  precision@10=0.132651  precision@20=0.068472
ndcg@1=0.611872  ndcg@2=0.702952  ndcg@5=0.784635  ndcg@10=0.799293  ndcg@20=0.806696
hit_rate@1=0.611872  hit_rate@2=0.826514  hit_rate@5=0.952722  hit_rate@10=0.975193  hit_rate@20=0.992671
map@1=0.611872  map@2=0.665291  map@5=0.723893  map@10=0.732943  map@20=0.735809
mrr@1=0.611872  mrr@2=0.719193  mrr@5=0.756108  mrr@10=0.759097  mrr@20=0.760537
f1@1=0.534196  f1@2=0.553961  f1@5=0.380041  f1@10=0.227005  f1@20=0.125897

Epoch 53/100: 100%|██████████| 820/820 [00:14<00:00, 58.44it/s, bpr=0.0281, c=2.52, loss=0.129]

[VAL]
recall@1=0.502029  recall@2=0.745057  recall@5=0.920621  recall@10=0.956549  recall@20=0.986773
precision@1=0.616129  precision@2=0.476371  precision@5=0.250371  precision@10=0.132129  precision@20=0.068681
ndcg@1=0.616129  ndcg@2=0.708479  ndcg@5=0.785835  ndcg@10=0.799554  ndcg@20=0.808274
hit_rate@1=0.616129  hit_rate@2=0.834839  hit_rate@5=0.952016  hit_rate@10=0.973548  hit_rate@20=0.993629
map@1=0.616129  map@2=0.669718  map@5=0.725603  map@10=0.734070  map@20=0.737353
mrr@1=0.616129  mrr@2=0.725323  mrr@5=0.759821  mrr@10=0.762798  mrr@20=0.764168
f1@1=0.535690  f1@2=0.559221  f1@5=0.379436  f1@10=0.225981  f1@20=0.126198

[TEST]
recall@1=0.500095  recall@2=0.741224  recall@5=0.918551  recall@10=0.958572  recall@20=0.986283
precision@1=0.613322  precision@2=0.475032  precision@5=0.249871  precision@10=0.132337  precision@20=0.068516
ndcg@1=0.613322  ndcg@2=0.705625  ndcg@5=0.783632  ndcg@10=0.798789  ndcg@20=0.806926
hit_rate@1=0.613322  hit_rate@2=0.830541  hit_rate@5=0.949259  hit_rate@10=0.973985  hit_rate@20=0.992671
map@1=0.613322  map@2=0.667405  map@5=0.723558  map@10=0.732714  map@20=0.735924
mrr@1=0.613322  mrr@2=0.722092  mrr@5=0.756819  mrr@10=0.760248  mrr@20=0.761781
f1@1=0.533653  f1@2=0.557130  f1@5=0.378888  f1@10=0.226488  f1@20=0.125984

Epoch 54/100: 100%|██████████| 820/820 [00:14<00:00, 57.12it/s, bpr=0.0141, c=2.51, loss=0.114]

[VAL]
recall@1=0.484145  recall@2=0.723230  recall@5=0.918941  recall@10=0.961014  recall@20=0.987193
precision@1=0.590806  precision@2=0.460968  precision@5=0.249258  precision@10=0.132742  precision@20=0.068718
ndcg@1=0.590806  ndcg@2=0.685810  ndcg@5=0.773283  ndcg@10=0.789453  ndcg@20=0.797037
hit_rate@1=0.590806  hit_rate@2=0.810323  hit_rate@5=0.950887  hit_rate@10=0.976855  hit_rate@20=0.994194
map@1=0.590806  map@2=0.647823  map@5=0.709975  map@10=0.719848  map@20=0.722780
mrr@1=0.590806  mrr@2=0.700605  mrr@5=0.741767  mrr@10=0.745472  mrr@20=0.746552
f1@1=0.515477  f1@2=0.541893  f1@5=0.378056  f1@10=0.227038  f1@20=0.126254

[TEST]
recall@1=0.484673  recall@2=0.725699  recall@5=0.920629  recall@10=0.962733  recall@20=0.986096
precision@1=0.590528  precision@2=0.462548  precision@5=0.249597  precision@10=0.132869  precision@20=0.068524
ndcg@1=0.590528  ndcg@2=0.687094  ndcg@5=0.774494  ndcg@10=0.790570  ndcg@20=0.797524
hit_rate@1=0.590528  hit_rate@2=0.813869  hit_rate@5=0.951997  hit_rate@10=0.976643  hit_rate@20=0.992751
map@1=0.590528  map@2=0.648518  map@5=0.711002  map@10=0.720870  map@20=0.723642
mrr@1=0.590528  mrr@2=0.702159  mrr@5=0.742269  mrr@10=0.745570  mrr@20=0.746928
f1@1=0.516132  f1@2=0.544011  f1@5=0.378863  f1@10=0.227423  f1@20=0.125973

Epoch 55/100: 100%|██████████| 820/820 [00:14<00:00, 57.71it/s, bpr=0.0345, c=2.35, loss=0.128]

[VAL]
recall@1=0.501018  recall@2=0.745091  recall@5=0.922335  recall@10=0.959949  recall@20=0.986044
precision@1=0.612581  precision@2=0.475444  precision@5=0.251065  precision@10=0.132685  precision@20=0.068637
ndcg@1=0.612581  ndcg@2=0.707703  ndcg@5=0.786049  ndcg@10=0.800398  ndcg@20=0.808071
hit_rate@1=0.612581  hit_rate@2=0.835403  hit_rate@5=0.953065  hit_rate@10=0.975887  hit_rate@20=0.993226
map@1=0.612581  map@2=0.668669  map@5=0.725497  map@10=0.734288  map@20=0.737311
mrr@1=0.612581  mrr@2=0.724113  mrr@5=0.758391  mrr@10=0.761640  mrr@20=0.762988
f1@1=0.533930  f1@2=0.558622  f1@5=0.380351  f1@10=0.226893  f1@20=0.126112

[TEST]
recall@1=0.507180  recall@2=0.749421  recall@5=0.924385  recall@10=0.962128  recall@20=0.985655
precision@1=0.619201  precision@2=0.479422  precision@5=0.251289  precision@10=0.132821  precision@20=0.068460
ndcg@1=0.619201  ndcg@2=0.712943  ndcg@5=0.790224  ndcg@10=0.804511  ndcg@20=0.811337
hit_rate@1=0.619201  hit_rate@2=0.837307  hit_rate@5=0.953850  hit_rate@10=0.976643  hit_rate@20=0.992751
map@1=0.619201  map@2=0.674936  map@5=0.730902  map@10=0.739525  map@20=0.742135
mrr@1=0.619201  mrr@2=0.728133  mrr@5=0.762386  mrr@10=0.765481  mrr@20=0.766652
f1@1=0.540489  f1@2=0.562830  f1@5=0.381106  f1@10=0.227338  f1@20=0.125871

Epoch 56/100: 100%|██████████| 820/820 [00:14<00:00, 57.80it/s, bpr=0.0294, c=2.52, loss=0.13]

[VAL]
recall@1=0.502097  recall@2=0.740602  recall@5=0.919489  recall@10=0.956499  recall@20=0.986896
precision@1=0.613952  precision@2=0.473024  precision@5=0.250016  precision@10=0.132185  precision@20=0.068694
ndcg@1=0.613952  ndcg@2=0.704986  ndcg@5=0.784057  ndcg@10=0.798319  ndcg@20=0.807015
hit_rate@1=0.613952  hit_rate@2=0.827581  hit_rate@5=0.950806  hit_rate@10=0.973387  hit_rate@20=0.994032
map@1=0.613952  map@2=0.667359  map@5=0.723923  map@10=0.732766  map@20=0.735962
mrr@1=0.613952  mrr@2=0.720726  mrr@5=0.756731  mrr@10=0.760012  mrr@20=0.761326
f1@1=0.535164  f1@2=0.555592  f1@5=0.378910  f1@10=0.226049  f1@20=0.126213

[TEST]
recall@1=0.497281  recall@2=0.739911  recall@5=0.920301  recall@10=0.959842  recall@20=0.985812
precision@1=0.608409  precision@2=0.472938  precision@5=0.250209  precision@10=0.132539  precision@20=0.068456
ndcg@1=0.608409  ndcg@2=0.702664  ndcg@5=0.782537  ndcg@10=0.797378  ndcg@20=0.805045
hit_rate@1=0.608409  hit_rate@2=0.826756  hit_rate@5=0.950548  hit_rate@10=0.974952  hit_rate@20=0.992751
map@1=0.608409  map@2=0.664606  map@5=0.722019  map@10=0.730856  map@20=0.733878
mrr@1=0.608409  mrr@2=0.717622  mrr@5=0.753602  mrr@10=0.756765  mrr@20=0.758353
f1@1=0.530266  f1@2=0.555482  f1@5=0.379457  f1@10=0.226805  f1@20=0.125872

Epoch 57/100: 100%|██████████| 820/820 [00:14<00:00, 57.61it/s, bpr=0.0398, c=2.28, loss=0.131]

[VAL]
recall@1=0.492340  recall@2=0.729779  recall@5=0.921625  recall@10=0.959704  recall@20=0.986926
precision@1=0.602339  precision@2=0.466290  precision@5=0.250758  precision@10=0.132734  precision@20=0.068694
ndcg@1=0.602339  ndcg@2=0.694236  ndcg@5=0.779736  ndcg@10=0.794353  ndcg@20=0.802238
hit_rate@1=0.602339  hit_rate@2=0.819919  hit_rate@5=0.953710  hit_rate@10=0.975968  hit_rate@20=0.993871
map@1=0.602339  map@2=0.655907  map@5=0.716984  map@10=0.726096  map@20=0.729148
mrr@1=0.602339  mrr@2=0.711250  mrr@5=0.750785  mrr@10=0.753969  mrr@20=0.755247
f1@1=0.524711  f1@2=0.547434  f1@5=0.379899  f1@10=0.226914  f1@20=0.126215

[TEST]
recall@1=0.490686  recall@2=0.728809  recall@5=0.920835  recall@10=0.961160  recall@20=0.985952
precision@1=0.599468  precision@2=0.465085  precision@5=0.249839  precision@10=0.132724  precision@20=0.068460
ndcg@1=0.599468  ndcg@2=0.692071  ndcg@5=0.777931  ndcg@10=0.793492  ndcg@20=0.800715
hit_rate@1=0.599468  hit_rate@2=0.817896  hit_rate@5=0.952159  hit_rate@10=0.976240  hit_rate@20=0.992751
map@1=0.599468  map@2=0.653713  map@5=0.715181  map@10=0.724815  map@20=0.727645
mrr@1=0.599468  mrr@2=0.708562  mrr@5=0.747946  mrr@10=0.751281  mrr@20=0.752527
f1@1=0.522906  f1@2=0.546659  f1@5=0.379242  f1@10=0.227147  f1@20=0.125887

Epoch 58/100: 100%|██████████| 820/820 [00:14<00:00, 57.85it/s, bpr=0.0295, c=2.56, loss=0.132]

[VAL]
recall@1=0.496074  recall@2=0.732701  recall@5=0.921510  recall@10=0.958853  recall@20=0.985696
precision@1=0.607177  precision@2=0.467581  precision@5=0.250565  precision@10=0.132500  precision@20=0.068601
ndcg@1=0.607177  ndcg@2=0.697223  ndcg@5=0.781337  ndcg@10=0.795714  ndcg@20=0.803485
hit_rate@1=0.607177  hit_rate@2=0.822742  hit_rate@5=0.953306  hit_rate@10=0.975484  hit_rate@20=0.992661
map@1=0.607177  map@2=0.658851  map@5=0.719183  map@10=0.728126  map@20=0.731084
mrr@1=0.607177  mrr@2=0.715081  mrr@5=0.753239  mrr@10=0.756495  mrr@20=0.757703
f1@1=0.528872  f1@2=0.549429  f1@5=0.379717  f1@10=0.226565  f1@20=0.126058

[TEST]
recall@1=0.494768  recall@2=0.732628  recall@5=0.922120  recall@10=0.961693  recall@20=0.985314
precision@1=0.603254  precision@2=0.468146  precision@5=0.250419  precision@10=0.132764  precision@20=0.068408
ndcg@1=0.603254  ndcg@2=0.696377  ndcg@5=0.781228  ndcg@10=0.796319  ndcg@20=0.803223
hit_rate@1=0.603254  hit_rate@2=0.823212  hit_rate@5=0.952883  hit_rate@10=0.976804  hit_rate@20=0.992510
map@1=0.603254  map@2=0.657941  map@5=0.719299  map@10=0.728558  map@20=0.731269
mrr@1=0.603254  mrr@2=0.713112  mrr@5=0.751354  mrr@10=0.754570  mrr@20=0.755821
f1@1=0.526934  f1@2=0.549899  f1@5=0.379937  f1@10=0.227248  f1@20=0.125789

Epoch 59/100: 100%|██████████| 820/820 [00:14<00:00, 57.37it/s, bpr=0.0395, c=2.65, loss=0.146]

[VAL]
recall@1=0.505859  recall@2=0.738722  recall@5=0.922091  recall@10=0.960317  recall@20=0.986990
precision@1=0.618226  precision@2=0.472823  precision@5=0.250645  precision@10=0.132710  precision@20=0.068681
ndcg@1=0.618226  ndcg@2=0.705719  ndcg@5=0.786301  ndcg@10=0.800941  ndcg@20=0.808871
hit_rate@1=0.618226  hit_rate@2=0.826774  hit_rate@5=0.952903  hit_rate@10=0.976210  hit_rate@20=0.993790
map@1=0.618226  map@2=0.668770  map@5=0.726052  map@10=0.735012  map@20=0.738294
mrr@1=0.618226  mrr@2=0.722581  mrr@5=0.759317  mrr@10=0.762615  mrr@20=0.764051
f1@1=0.539079  f1@2=0.554733  f1@5=0.379869  f1@10=0.226955  f1@20=0.126209

[TEST]
recall@1=0.497953  recall@2=0.736308  recall@5=0.923481  recall@10=0.962543  recall@20=0.985675
precision@1=0.611469  precision@2=0.471569  precision@5=0.250741  precision@10=0.132837  precision@20=0.068488
ndcg@1=0.611469  ndcg@2=0.701141  ndcg@5=0.783755  ndcg@10=0.798838  ndcg@20=0.805546
hit_rate@1=0.611469  hit_rate@2=0.824259  hit_rate@5=0.953930  hit_rate@10=0.977287  hit_rate@20=0.992429
map@1=0.611469  map@2=0.663338  map@5=0.722114  map@10=0.731483  map@20=0.734073
mrr@1=0.611469  mrr@2=0.717784  mrr@5=0.755571  mrr@10=0.758901  mrr@20=0.759856
f1@1=0.531651  f1@2=0.553288  f1@5=0.380453  f1@10=0.227394  f1@20=0.125919

Epoch 60/100: 100%|██████████| 820/820 [00:14<00:00, 57.32it/s, bpr=0.0445, c=2.55, loss=0.146]

[VAL]
recall@1=0.461380  recall@2=0.700370  recall@5=0.915132  recall@10=0.962586  recall@20=0.985165
precision@1=0.564516  precision@2=0.445323  precision@5=0.247903  precision@10=0.132992  precision@20=0.068581
ndcg@1=0.564516  ndcg@2=0.660898  ndcg@5=0.758248  ndcg@10=0.776391  ndcg@20=0.782980
hit_rate@1=0.564516  hit_rate@2=0.789919  hit_rate@5=0.949839  hit_rate@10=0.978548  hit_rate@20=0.992339
map@1=0.564516  map@2=0.621552  map@5=0.690359  map@10=0.701397  map@20=0.703975
mrr@1=0.564516  mrr@2=0.676935  mrr@5=0.724005  mrr@10=0.727966  mrr@20=0.728785
f1@1=0.491711  f1@2=0.524031  f1@5=0.376092  f1@10=0.227431  f1@20=0.126002

[TEST]
recall@1=0.466344  recall@2=0.702853  recall@5=0.916607  recall@10=0.963915  recall@20=0.985299
precision@1=0.570071  precision@2=0.446158  precision@5=0.248260  precision@10=0.133086  precision@20=0.068440
ndcg@1=0.570071  ndcg@2=0.664024  ndcg@5=0.761367  ndcg@10=0.779561  ndcg@20=0.785964
hit_rate@1=0.570071  hit_rate@2=0.794298  hit_rate@5=0.949903  hit_rate@10=0.978495  hit_rate@20=0.992188
map@1=0.570071  map@2=0.624396  map@5=0.693970  map@10=0.705131  map@20=0.707752
mrr@1=0.570071  mrr@2=0.682426  mrr@5=0.727681  mrr@10=0.731711  mrr@20=0.732956
f1@1=0.497047  f1@2=0.525837  f1@5=0.377011  f1@10=0.227751  f1@20=0.125837

Epoch 61/100: 100%|██████████| 820/820 [00:14<00:00, 57.23it/s, bpr=0.0229, c=2.51, loss=0.123]

[VAL]
recall@1=0.494429  recall@2=0.736253  recall@5=0.923850  recall@10=0.958736  recall@20=0.986328
precision@1=0.603952  precision@2=0.469234  precision@5=0.251274  precision@10=0.132484  precision@20=0.068657
ndcg@1=0.603952  ndcg@2=0.698657  ndcg@5=0.782292  ndcg@10=0.795748  ndcg@20=0.803693
hit_rate@1=0.603952  hit_rate@2=0.825887  hit_rate@5=0.954677  hit_rate@10=0.975081  hit_rate@20=0.993306
map@1=0.603952  map@2=0.659758  map@5=0.719825  map@10=0.728252  map@20=0.731263
mrr@1=0.603952  mrr@2=0.715000  mrr@5=0.752805  mrr@10=0.755774  mrr@20=0.757009
f1@1=0.526762  f1@2=0.551650  f1@5=0.380763  f1@10=0.226566  f1@20=0.126144

[TEST]
recall@1=0.496005  recall@2=0.733901  recall@5=0.924963  recall@10=0.961334  recall@20=0.985573
precision@1=0.604220  precision@2=0.467703  precision@5=0.251192  precision@10=0.132708  precision@20=0.068472
ndcg@1=0.604220  ndcg@2=0.697097  ndcg@5=0.782764  ndcg@10=0.796728  ndcg@20=0.803846
hit_rate@1=0.604220  hit_rate@2=0.823293  hit_rate@5=0.955702  hit_rate@10=0.975596  hit_rate@20=0.992671
map@1=0.604220  map@2=0.658686  map@5=0.720334  map@10=0.729152  map@20=0.731924
mrr@1=0.604220  mrr@2=0.713676  mrr@5=0.752487  mrr@10=0.755129  mrr@20=0.756533
f1@1=0.528146  f1@2=0.550118  f1@5=0.381084  f1@10=0.227130  f1@20=0.125880

Epoch 62/100: 100%|██████████| 820/820 [00:14<00:00, 57.51it/s, bpr=0.0276, c=2.41, loss=0.124]

[VAL]
recall@1=0.498849  recall@2=0.734642  recall@5=0.917864  recall@10=0.957423  recall@20=0.987181
precision@1=0.609677  precision@2=0.469839  precision@5=0.249435  precision@10=0.132306  precision@20=0.068694
ndcg@1=0.609677  ndcg@2=0.700066  ndcg@5=0.780544  ndcg@10=0.795793  ndcg@20=0.804221
hit_rate@1=0.609677  hit_rate@2=0.825000  hit_rate@5=0.948790  hit_rate@10=0.974113  hit_rate@20=0.994113
map@1=0.609677  map@2=0.662016  map@5=0.719639  map@10=0.728947  map@20=0.731993
mrr@1=0.609677  mrr@2=0.717298  mrr@5=0.753183  mrr@10=0.756948  mrr@20=0.758134
f1@1=0.531530  f1@2=0.551329  f1@5=0.378053  f1@10=0.226238  f1@20=0.126236

[TEST]
recall@1=0.500955  recall@2=0.733221  recall@5=0.917243  recall@10=0.960193  recall@20=0.985996
precision@1=0.614288  precision@2=0.470079  precision@5=0.249162  precision@10=0.132442  precision@20=0.068472
ndcg@1=0.614288  ndcg@2=0.700569  ndcg@5=0.781248  ndcg@10=0.797435  ndcg@20=0.805105
hit_rate@1=0.614288  hit_rate@2=0.823373  hit_rate@5=0.947809  hit_rate@10=0.975113  hit_rate@20=0.992832
map@1=0.614288  map@2=0.663096  map@5=0.720727  map@10=0.730396  map@20=0.733455
mrr@1=0.614288  mrr@2=0.718871  mrr@5=0.754945  mrr@10=0.758544  mrr@20=0.760162
f1@1=0.534509  f1@2=0.551171  f1@5=0.377964  f1@10=0.226750  f1@20=0.125900

Epoch 63/100: 100%|██████████| 820/820 [00:14<00:00, 58.11it/s, bpr=0.0177, c=2.5, loss=0.118]

[VAL]
recall@1=0.506556  recall@2=0.743317  recall@5=0.920524  recall@10=0.960023  recall@20=0.986137
precision@1=0.619194  precision@2=0.475242  precision@5=0.250081  precision@10=0.132621  precision@20=0.068645
ndcg@1=0.619194  ndcg@2=0.708922  ndcg@5=0.786584  ndcg@10=0.801754  ndcg@20=0.809399
hit_rate@1=0.619194  hit_rate@2=0.830645  hit_rate@5=0.952016  hit_rate@10=0.976371  hit_rate@20=0.993145
map@1=0.619194  map@2=0.671613  map@5=0.726987  map@10=0.736214  map@20=0.739210
mrr@1=0.619194  mrr@2=0.725040  mrr@5=0.760130  mrr@10=0.763697  mrr@20=0.764956
f1@1=0.539810  f1@2=0.557839  f1@5=0.379094  f1@10=0.226817  f1@20=0.126124

[TEST]
recall@1=0.501019  recall@2=0.742197  recall@5=0.918969  recall@10=0.961995  recall@20=0.985357
precision@1=0.612355  precision@2=0.475354  precision@5=0.249662  precision@10=0.132748  precision@20=0.068436
ndcg@1=0.612355  ndcg@2=0.706184  ndcg@5=0.783962  ndcg@10=0.800115  ndcg@20=0.807018
hit_rate@1=0.612355  hit_rate@2=0.829977  hit_rate@5=0.949984  hit_rate@10=0.976562  hit_rate@20=0.992026
map@1=0.612355  map@2=0.668392  map@5=0.724146  map@10=0.733788  map@20=0.736509
mrr@1=0.612355  mrr@2=0.721045  mrr@5=0.756402  mrr@10=0.759903  mrr@20=0.761119
f1@1=0.533969  f1@2=0.557659  f1@5=0.378754  f1@10=0.227241  f1@20=0.125835

Epoch 64/100: 100%|██████████| 820/820 [00:14<00:00, 57.49it/s, bpr=0.0229, c=2.49, loss=0.123]

[VAL]
recall@1=0.491524  recall@2=0.728221  recall@5=0.922165  recall@10=0.961130  recall@20=0.986808
precision@1=0.601855  precision@2=0.465242  precision@5=0.250629  precision@10=0.132871  precision@20=0.068673
ndcg@1=0.601855  ndcg@2=0.692615  ndcg@5=0.778942  ndcg@10=0.793925  ndcg@20=0.801319
hit_rate@1=0.601855  hit_rate@2=0.818548  hit_rate@5=0.954355  hit_rate@10=0.977339  hit_rate@20=0.993871
map@1=0.601855  map@2=0.654173  map@5=0.715793  map@10=0.725057  map@20=0.727884
mrr@1=0.601855  mrr@2=0.710161  mrr@5=0.749785  mrr@10=0.753096  mrr@20=0.754198
f1@1=0.524078  f1@2=0.546280  f1@5=0.379824  f1@10=0.227183  f1@20=0.126180

[TEST]
recall@1=0.484466  recall@2=0.725253  recall@5=0.922028  recall@10=0.964180  recall@20=0.985466
precision@1=0.594233  precision@2=0.463676  precision@5=0.250274  precision@10=0.133070  precision@20=0.068484
ndcg@1=0.594233  ndcg@2=0.688041  ndcg@5=0.775977  ndcg@10=0.792058  ndcg@20=0.798438
hit_rate@1=0.594233  hit_rate@2=0.816124  hit_rate@5=0.953850  hit_rate@10=0.978657  hit_rate@20=0.992188
map@1=0.594233  map@2=0.648961  map@5=0.711908  map@10=0.721801  map@20=0.724415
mrr@1=0.594233  mrr@2=0.705219  mrr@5=0.745569  mrr@10=0.748946  mrr@20=0.750097
f1@1=0.516966  f1@2=0.544444  f1@5=0.379771  f1@10=0.227761  f1@20=0.125902

Epoch 65/100: 100%|██████████| 820/820 [00:14<00:00, 57.65it/s, bpr=0.0277, c=2.42, loss=0.125]

[VAL]
recall@1=0.497268  recall@2=0.734762  recall@5=0.923393  recall@10=0.961941  recall@20=0.986993
precision@1=0.606613  precision@2=0.469194  precision@5=0.250871  precision@10=0.133000  precision@20=0.068677
ndcg@1=0.606613  ndcg@2=0.699271  ndcg@5=0.782914  ndcg@10=0.797868  ndcg@20=0.805113
hit_rate@1=0.606613  hit_rate@2=0.823387  hit_rate@5=0.955000  hit_rate@10=0.977500  hit_rate@20=0.994032
map@1=0.606613  map@2=0.661431  map@5=0.721098  map@10=0.730487  map@20=0.733255
mrr@1=0.606613  mrr@2=0.715161  mrr@5=0.753519  mrr@10=0.756932  mrr@20=0.758116
f1@1=0.529468  f1@2=0.550988  f1@5=0.380281  f1@10=0.227398  f1@20=0.126198

[TEST]
recall@1=0.494583  recall@2=0.735536  recall@5=0.924268  recall@10=0.963757  recall@20=0.986747
precision@1=0.603737  precision@2=0.469716  precision@5=0.250789  precision@10=0.133054  precision@20=0.068529
ndcg@1=0.603737  ndcg@2=0.698310  ndcg@5=0.782546  ndcg@10=0.797614  ndcg@20=0.804325
hit_rate@1=0.603737  hit_rate@2=0.824581  hit_rate@5=0.954816  hit_rate@10=0.977690  hit_rate@20=0.993396
map@1=0.603737  map@2=0.659854  map@5=0.720348  map@10=0.729698  map@20=0.732293
mrr@1=0.603737  mrr@2=0.713998  mrr@5=0.752461  mrr@10=0.755338  mrr@20=0.756553
f1@1=0.526928  f1@2=0.551913  f1@5=0.380633  f1@10=0.227746  f1@20=0.126008

Epoch 66/100: 100%|██████████| 820/820 [00:14<00:00, 57.20it/s, bpr=0.0389, c=2.52, loss=0.14]

[VAL]
recall@1=0.486179  recall@2=0.721112  recall@5=0.919437  recall@10=0.961518  recall@20=0.986497
precision@1=0.593226  precision@2=0.459718  precision@5=0.249290  precision@10=0.132911  precision@20=0.068669
ndcg@1=0.593226  ndcg@2=0.685352  ndcg@5=0.773614  ndcg@10=0.789985  ndcg@20=0.797301
hit_rate@1=0.593226  hit_rate@2=0.809355  hit_rate@5=0.952581  hit_rate@10=0.977903  hit_rate@20=0.993468
map@1=0.593226  map@2=0.647560  map@5=0.709852  map@10=0.719998  map@20=0.722904
mrr@1=0.593226  mrr@2=0.701452  mrr@5=0.743013  mrr@10=0.746725  mrr@20=0.747851
f1@1=0.517641  f1@2=0.540304  f1@5=0.378138  f1@10=0.227263  f1@20=0.126178

[TEST]
recall@1=0.481174  recall@2=0.719890  recall@5=0.921654  recall@10=0.963516  recall@20=0.986220
precision@1=0.587468  precision@2=0.458682  precision@5=0.249919  precision@10=0.133127  precision@20=0.068541
ndcg@1=0.587468  ndcg@2=0.681975  ndcg@5=0.772769  ndcg@10=0.788909  ndcg@20=0.795596
hit_rate@1=0.587468  hit_rate@2=0.809923  hit_rate@5=0.953286  hit_rate@10=0.977368  hit_rate@20=0.992671
map@1=0.587468  map@2=0.643082  map@5=0.708096  map@10=0.718154  map@20=0.720781
mrr@1=0.587468  mrr@2=0.698534  mrr@5=0.740357  mrr@10=0.743548  mrr@20=0.744755
f1@1=0.512650  f1@2=0.539513  f1@5=0.379358  f1@10=0.227816  f1@20=0.126015

Epoch 67/100: 100%|██████████| 820/820 [00:14<00:00, 57.65it/s, bpr=0.0489, c=2.43, loss=0.146]

[VAL]
recall@1=0.501510  recall@2=0.748481  recall@5=0.921206  recall@10=0.959435  recall@20=0.986176
precision@1=0.613065  precision@2=0.478024  precision@5=0.250710  precision@10=0.132589  precision@20=0.068661
ndcg@1=0.613065  ndcg@2=0.710027  ndcg@5=0.786035  ndcg@10=0.800465  ndcg@20=0.808203
hit_rate@1=0.613065  hit_rate@2=0.837016  hit_rate@5=0.952016  hit_rate@10=0.975726  hit_rate@20=0.992984
map@1=0.613065  map@2=0.671109  map@5=0.726037  map@10=0.734717  map@20=0.737630
mrr@1=0.613065  mrr@2=0.724758  mrr@5=0.758461  mrr@10=0.761704  mrr@20=0.762893
f1@1=0.534467  f1@2=0.561397  f1@5=0.379816  f1@10=0.226735  f1@20=0.126163

[TEST]
recall@1=0.503922  recall@2=0.747881  recall@5=0.922473  recall@10=0.960760  recall@20=0.985639
precision@1=0.616382  precision@2=0.479261  precision@5=0.250854  precision@10=0.132659  precision@20=0.068472
ndcg@1=0.616382  ndcg@2=0.711508  ndcg@5=0.788024  ndcg@10=0.802610  ndcg@20=0.809940
hit_rate@1=0.616382  hit_rate@2=0.835615  hit_rate@5=0.952078  hit_rate@10=0.975354  hit_rate@20=0.992590
map@1=0.616382  map@2=0.673526  map@5=0.728670  map@10=0.737486  map@20=0.740383
mrr@1=0.616382  mrr@2=0.726281  mrr@5=0.760244  mrr@10=0.763614  mrr@20=0.765005
f1@1=0.537261  f1@2=0.562112  f1@5=0.380382  f1@10=0.227036  f1@20=0.125883

Epoch 68/100: 100%|██████████| 820/820 [00:14<00:00, 57.12it/s, bpr=0.0128, c=2.69, loss=0.12]

[VAL]
recall@1=0.489216  recall@2=0.732127  recall@5=0.921077  recall@10=0.964627  recall@20=0.986961
precision@1=0.598548  precision@2=0.468145  precision@5=0.250306  precision@10=0.133242  precision@20=0.068690
ndcg@1=0.598548  ndcg@2=0.694617  ndcg@5=0.778138  ndcg@10=0.794721  ndcg@20=0.801235
hit_rate@1=0.598548  hit_rate@2=0.821048  hit_rate@5=0.952581  hit_rate@10=0.980161  hit_rate@20=0.993871
map@1=0.598548  map@2=0.656028  map@5=0.715433  map@10=0.725484  map@20=0.728035
mrr@1=0.598548  mrr@2=0.709637  mrr@5=0.747999  mrr@10=0.751933  mrr@20=0.752823
f1@1=0.521431  f1@2=0.549388  f1@5=0.379384  f1@10=0.227899  f1@20=0.126216

[TEST]
recall@1=0.494750  recall@2=0.734482  recall@5=0.923480  recall@10=0.966246  recall@20=0.986232
precision@1=0.605670  precision@2=0.469475  precision@5=0.250580  precision@10=0.133352  precision@20=0.068524
ndcg@1=0.605670  ndcg@2=0.698261  ndcg@5=0.782239  ndcg@10=0.798618  ndcg@20=0.804585
hit_rate@1=0.605670  hit_rate@2=0.823695  hit_rate@5=0.954091  hit_rate@10=0.979945  hit_rate@20=0.992912
map@1=0.605670  map@2=0.659955  map@5=0.720124  map@10=0.730170  map@20=0.732589
mrr@1=0.605670  mrr@2=0.714844  mrr@5=0.753058  mrr@10=0.756640  mrr@20=0.757694
f1@1=0.527537  f1@2=0.551349  f1@5=0.380299  f1@10=0.228257  f1@20=0.125985

Epoch 69/100: 100%|██████████| 820/820 [00:14<00:00, 58.23it/s, bpr=0.0477, c=2.37, loss=0.143]

[VAL]
recall@1=0.502707  recall@2=0.744184  recall@5=0.923297  recall@10=0.959858  recall@20=0.986224
precision@1=0.615242  precision@2=0.475968  precision@5=0.251226  precision@10=0.132718  precision@20=0.068649
ndcg@1=0.615242  ndcg@2=0.708305  ndcg@5=0.787178  ndcg@10=0.801275  ndcg@20=0.808815
hit_rate@1=0.615242  hit_rate@2=0.834032  hit_rate@5=0.954597  hit_rate@10=0.975968  hit_rate@20=0.993226
map@1=0.615242  map@2=0.669839  map@5=0.726725  map@10=0.735498  map@20=0.738318
mrr@1=0.615242  mrr@2=0.724597  mrr@5=0.759954  mrr@10=0.763043  mrr@20=0.764161
f1@1=0.535887  f1@2=0.558477  f1@5=0.380624  f1@10=0.226922  f1@20=0.126142

[TEST]
recall@1=0.506906  recall@2=0.745584  recall@5=0.926173  recall@10=0.962787  recall@20=0.986183
precision@1=0.621456  precision@2=0.477851  precision@5=0.251724  precision@10=0.132933  precision@20=0.068516
ndcg@1=0.621456  ndcg@2=0.711059  ndcg@5=0.790566  ndcg@10=0.804597  ndcg@20=0.811567
hit_rate@1=0.621456  hit_rate@2=0.833280  hit_rate@5=0.956024  hit_rate@10=0.977448  hit_rate@20=0.992912
map@1=0.621456  map@2=0.673566  map@5=0.730556  map@10=0.739306  map@20=0.742128
mrr@1=0.621456  mrr@2=0.727408  mrr@5=0.763277  mrr@10=0.766163  mrr@20=0.767494
f1@1=0.540944  f1@2=0.560507  f1@5=0.381812  f1@10=0.227515  f1@20=0.125978

Epoch 70/100: 100%|██████████| 820/820 [00:14<00:00, 57.71it/s, bpr=0.0179, c=2.5, loss=0.118]

[VAL]
recall@1=0.512606  recall@2=0.747845  recall@5=0.915024  recall@10=0.963288  recall@20=0.986766
precision@1=0.626774  precision@2=0.479113  precision@5=0.248855  precision@10=0.133113  precision@20=0.068665
ndcg@1=0.626774  ndcg@2=0.714806  ndcg@5=0.787185  ndcg@10=0.805264  ndcg@20=0.812004
hit_rate@1=0.626774  hit_rate@2=0.837097  hit_rate@5=0.947823  hit_rate@10=0.978952  hit_rate@20=0.993710
map@1=0.626774  map@2=0.677460  map@5=0.729263  map@10=0.739919  map@20=0.742457
mrr@1=0.626774  mrr@2=0.731774  mrr@5=0.763935  mrr@10=0.768275  mrr@20=0.769187
f1@1=0.546305  f1@2=0.561766  f1@5=0.377063  f1@10=0.227628  f1@20=0.126173

[TEST]
recall@1=0.515497  recall@2=0.745661  recall@5=0.917494  recall@10=0.964879  recall@20=0.985948
precision@1=0.631443  precision@2=0.478214  precision@5=0.249211  precision@10=0.133119  precision@20=0.068508
ndcg@1=0.631443  ndcg@2=0.714668  ndcg@5=0.789494  ndcg@10=0.807349  ndcg@20=0.813669
hit_rate@1=0.631443  hit_rate@2=0.834005  hit_rate@5=0.949420  hit_rate@10=0.979220  hit_rate@20=0.992671
map@1=0.631443  map@2=0.678137  map@5=0.731593  map@10=0.742271  map@20=0.744858
mrr@1=0.631443  mrr@2=0.732885  mrr@5=0.766359  mrr@10=0.770444  mrr@20=0.771611
f1@1=0.549924  f1@2=0.560743  f1@5=0.378089  f1@10=0.227886  f1@20=0.125958

Epoch 71/100: 100%|██████████| 820/820 [00:14<00:00, 57.58it/s, bpr=0.0243, c=2.48, loss=0.123]

[VAL]
recall@1=0.511478  recall@2=0.747482  recall@5=0.922332  recall@10=0.961313  recall@20=0.986185
precision@1=0.624113  precision@2=0.478065  precision@5=0.251016  precision@10=0.132879  precision@20=0.068605
ndcg@1=0.624113  ndcg@2=0.713712  ndcg@5=0.790645  ndcg@10=0.805523  ndcg@20=0.812695
hit_rate@1=0.624113  hit_rate@2=0.836210  hit_rate@5=0.953468  hit_rate@10=0.977177  hit_rate@20=0.993387
map@1=0.624113  map@2=0.676331  map@5=0.731759  map@10=0.740911  map@20=0.743649
mrr@1=0.624113  mrr@2=0.730282  mrr@5=0.764656  mrr@10=0.768062  mrr@20=0.769228
f1@1=0.544756  f1@2=0.561039  f1@5=0.380294  f1@10=0.227245  f1@20=0.126078

[TEST]
recall@1=0.502264  recall@2=0.748443  recall@5=0.925806  recall@10=0.963346  recall@20=0.985773
precision@1=0.614691  precision@2=0.480026  precision@5=0.251353  precision@10=0.133030  precision@20=0.068492
ndcg@1=0.614691  ndcg@2=0.711174  ndcg@5=0.788990  ndcg@10=0.803511  ndcg@20=0.810075
hit_rate@1=0.614691  hit_rate@2=0.836421  hit_rate@5=0.956186  hit_rate@10=0.977368  hit_rate@20=0.992590
map@1=0.614691  map@2=0.672962  map@5=0.728588  map@10=0.737774  map@20=0.740358
mrr@1=0.614691  mrr@2=0.725435  mrr@5=0.760801  mrr@10=0.763638  mrr@20=0.764762
f1@1=0.535579  f1@2=0.562865  f1@5=0.381407  f1@10=0.227686  f1@20=0.125916

Epoch 72/100: 100%|██████████| 820/820 [00:14<00:00, 57.94it/s, bpr=0.0315, c=2.41, loss=0.128]

[VAL]
recall@1=0.509129  recall@2=0.746677  recall@5=0.921916  recall@10=0.959143  recall@20=0.986192
precision@1=0.622339  precision@2=0.477782  precision@5=0.250742  precision@10=0.132532  precision@20=0.068633
ndcg@1=0.622339  ndcg@2=0.712417  ndcg@5=0.789045  ndcg@10=0.803337  ndcg@20=0.811162
hit_rate@1=0.622339  hit_rate@2=0.835887  hit_rate@5=0.952903  hit_rate@10=0.975726  hit_rate@20=0.993306
map@1=0.622339  map@2=0.674698  map@5=0.729773  map@10=0.738567  map@20=0.741545
mrr@1=0.622339  mrr@2=0.729153  mrr@5=0.763091  mrr@10=0.766455  mrr@20=0.767635
f1@1=0.542538  f1@2=0.560607  f1@5=0.379974  f1@10=0.226623  f1@20=0.126116

[TEST]
recall@1=0.501028  recall@2=0.743850  recall@5=0.923466  recall@10=0.961369  recall@20=0.986134
precision@1=0.613966  precision@2=0.477569  precision@5=0.251305  precision@10=0.132708  precision@20=0.068512
ndcg@1=0.613966  ndcg@2=0.707992  ndcg@5=0.786853  ndcg@10=0.801129  ndcg@20=0.808479
hit_rate@1=0.613966  hit_rate@2=0.831186  hit_rate@5=0.952481  hit_rate@10=0.975838  hit_rate@20=0.992671
map@1=0.613966  map@2=0.670325  map@5=0.726905  map@10=0.735518  map@20=0.738462
mrr@1=0.613966  mrr@2=0.722535  mrr@5=0.758106  mrr@10=0.761138  mrr@20=0.762537
f1@1=0.534455  f1@2=0.559599  f1@5=0.381032  f1@10=0.227145  f1@20=0.125975

Epoch 73/100: 100%|██████████| 820/820 [00:14<00:00, 57.29it/s, bpr=0.0216, c=2.46, loss=0.12]

[VAL]
recall@1=0.488215  recall@2=0.733177  recall@5=0.917499  recall@10=0.959695  recall@20=0.986753
precision@1=0.595403  precision@2=0.466613  precision@5=0.248871  precision@10=0.132669  precision@20=0.068665
ndcg@1=0.595403  ndcg@2=0.693484  ndcg@5=0.776007  ndcg@10=0.792033  ndcg@20=0.799921
hit_rate@1=0.595403  hit_rate@2=0.820645  hit_rate@5=0.951129  hit_rate@10=0.975887  hit_rate@20=0.993790
map@1=0.595403  map@2=0.654617  map@5=0.713678  map@10=0.723455  map@20=0.726511
mrr@1=0.595403  mrr@2=0.707823  mrr@5=0.746331  mrr@10=0.749578  mrr@20=0.750897
f1@1=0.519795  f1@2=0.549036  f1@5=0.377466  f1@10=0.226848  f1@20=0.126168

[TEST]
recall@1=0.487724  recall@2=0.728638  recall@5=0.915658  recall@10=0.961511  recall@20=0.986765
precision@1=0.596166  precision@2=0.464683  precision@5=0.248550  precision@10=0.132740  precision@20=0.068581
ndcg@1=0.596166  ndcg@2=0.690854  ndcg@5=0.774459  ndcg@10=0.791855  ndcg@20=0.799283
hit_rate@1=0.596166  hit_rate@2=0.817574  hit_rate@5=0.947729  hit_rate@10=0.975999  hit_rate@20=0.993235
map@1=0.596166  map@2=0.652122  map@5=0.712219  map@10=0.722738  map@20=0.725614
mrr@1=0.596166  mrr@2=0.707072  mrr@5=0.744966  mrr@10=0.748965  mrr@20=0.750356
f1@1=0.519893  f1@2=0.546333  f1@5=0.377166  f1@10=0.227189  f1@20=0.126069

Epoch 74/100: 100%|██████████| 820/820 [00:14<00:00, 57.81it/s, bpr=0.0274, c=2.6, loss=0.132]

[VAL]
recall@1=0.485791  recall@2=0.730254  recall@5=0.922857  recall@10=0.960583  recall@20=0.986515
precision@1=0.593468  precision@2=0.463911  precision@5=0.250597  precision@10=0.132823  precision@20=0.068677
ndcg@1=0.593468  ndcg@2=0.690296  ndcg@5=0.777232  ndcg@10=0.791821  ndcg@20=0.799232
hit_rate@1=0.593468  hit_rate@2=0.819839  hit_rate@5=0.954355  hit_rate@10=0.976613  hit_rate@20=0.993710
map@1=0.593468  map@2=0.650645  map@5=0.713445  map@10=0.722519  map@20=0.725313
mrr@1=0.593468  mrr@2=0.706613  mrr@5=0.746238  mrr@10=0.749388  mrr@20=0.750370
f1@1=0.517630  f1@2=0.546427  f1@5=0.379953  f1@10=0.227082  f1@20=0.126174

[TEST]
recall@1=0.483783  recall@2=0.727275  recall@5=0.923306  recall@10=0.962071  recall@20=0.985579
precision@1=0.590528  precision@2=0.462709  precision@5=0.250677  precision@10=0.132933  precision@20=0.068480
ndcg@1=0.590528  ndcg@2=0.687892  ndcg@5=0.776289  ndcg@10=0.791268  ndcg@20=0.798265
hit_rate@1=0.590528  hit_rate@2=0.817091  hit_rate@5=0.953367  hit_rate@10=0.976240  hit_rate@20=0.992188
map@1=0.590528  map@2=0.648458  map@5=0.712310  map@10=0.721588  map@20=0.724474
mrr@1=0.590528  mrr@2=0.703850  mrr@5=0.743879  mrr@10=0.747125  mrr@20=0.748520
f1@1=0.515384  f1@2=0.544582  f1@5=0.380358  f1@10=0.227475  f1@20=0.125907

Epoch 75/100: 100%|██████████| 820/820 [00:14<00:00, 57.53it/s, bpr=0.0438, c=2.37, loss=0.139]

[VAL]
recall@1=0.497570  recall@2=0.736766  recall@5=0.922192  recall@10=0.959242  recall@20=0.986437
precision@1=0.608548  precision@2=0.470403  precision@5=0.250661  precision@10=0.132613  precision@20=0.068694
ndcg@1=0.608548  ndcg@2=0.700625  ndcg@5=0.782890  ndcg@10=0.797189  ndcg@20=0.804988
hit_rate@1=0.608548  hit_rate@2=0.826129  hit_rate@5=0.953790  hit_rate@10=0.975806  hit_rate@20=0.993387
map@1=0.608548  map@2=0.662258  map@5=0.721131  map@10=0.730054  map@20=0.732941
mrr@1=0.608548  mrr@2=0.717218  mrr@5=0.754848  mrr@10=0.757997  mrr@20=0.759112
f1@1=0.530266  f1@2=0.552511  f1@5=0.379897  f1@10=0.226736  f1@20=0.126210

[TEST]
recall@1=0.498601  recall@2=0.734742  recall@5=0.922773  recall@10=0.961501  recall@20=0.985308
precision@1=0.609939  precision@2=0.470079  precision@5=0.250838  precision@10=0.132772  precision@20=0.068408
ndcg@1=0.609939  ndcg@2=0.700093  ndcg@5=0.783524  ndcg@10=0.798313  ndcg@20=0.805336
hit_rate@1=0.609939  hit_rate@2=0.823534  hit_rate@5=0.953286  hit_rate@10=0.975838  hit_rate@20=0.992429
map@1=0.609939  map@2=0.662391  map@5=0.722022  map@10=0.731202  map@20=0.733975
mrr@1=0.609939  mrr@2=0.716857  mrr@5=0.754862  mrr@10=0.757904  mrr@20=0.759349
f1@1=0.531660  f1@2=0.551746  f1@5=0.380372  f1@10=0.227214  f1@20=0.125790

Epoch 76/100: 100%|██████████| 820/820 [00:14<00:00, 57.78it/s, bpr=0.0214, c=2.42, loss=0.118]

[VAL]
recall@1=0.497714  recall@2=0.745745  recall@5=0.927701  recall@10=0.963969  recall@20=0.986762
precision@1=0.607177  precision@2=0.475161  precision@5=0.252065  precision@10=0.133250  precision@20=0.068706
ndcg@1=0.607177  ndcg@2=0.706429  ndcg@5=0.787101  ndcg@10=0.801138  ndcg@20=0.807905
hit_rate@1=0.607177  hit_rate@2=0.834839  hit_rate@5=0.958710  hit_rate@10=0.979758  hit_rate@20=0.993629
map@1=0.607177  map@2=0.667177  map@5=0.725326  map@10=0.734090  map@20=0.736852
mrr@1=0.607177  mrr@2=0.721250  mrr@5=0.757212  mrr@10=0.760198  mrr@20=0.761302
f1@1=0.530036  f1@2=0.558744  f1@5=0.382088  f1@10=0.227828  f1@20=0.126234

[TEST]
recall@1=0.495982  recall@2=0.743558  recall@5=0.928573  recall@10=0.965951  recall@20=0.985761
precision@1=0.606717  precision@2=0.474348  precision@5=0.252336  precision@10=0.133352  precision@20=0.068468
ndcg@1=0.606717  ndcg@2=0.704245  ndcg@5=0.787150  ndcg@10=0.801425  ndcg@20=0.807251
hit_rate@1=0.606717  hit_rate@2=0.833602  hit_rate@5=0.958199  hit_rate@10=0.979865  hit_rate@20=0.992188
map@1=0.606717  map@2=0.664707  map@5=0.725102  map@10=0.733959  map@20=0.736276
mrr@1=0.606717  mrr@2=0.719918  mrr@5=0.756917  mrr@10=0.759852  mrr@20=0.760729
f1@1=0.528757  f1@2=0.557657  f1@5=0.382770  f1@10=0.228244  f1@20=0.125898

Epoch 77/100: 100%|██████████| 820/820 [00:14<00:00, 57.03it/s, bpr=0.066, c=2.5, loss=0.166]

[VAL]
recall@1=0.499710  recall@2=0.741144  recall@5=0.921530  recall@10=0.959092  recall@20=0.987356
precision@1=0.610645  precision@2=0.473831  precision@5=0.250629  precision@10=0.132565  precision@20=0.068706
ndcg@1=0.610645  ndcg@2=0.704890  ndcg@5=0.784312  ndcg@10=0.798656  ndcg@20=0.806970
hit_rate@1=0.610645  hit_rate@2=0.830323  hit_rate@5=0.952984  hit_rate@10=0.975484  hit_rate@20=0.994113
map@1=0.610645  map@2=0.666573  map@5=0.723370  map@10=0.732211  map@20=0.735545
mrr@1=0.610645  mrr@2=0.720645  mrr@5=0.756384  mrr@10=0.759611  mrr@20=0.761102
f1@1=0.532509  f1@2=0.556105  f1@5=0.379833  f1@10=0.226691  f1@20=0.126245

[TEST]
recall@1=0.504753  recall@2=0.741642  recall@5=0.919893  recall@10=0.962009  recall@20=0.986064
precision@1=0.617510  precision@2=0.474509  precision@5=0.250048  precision@10=0.132764  precision@20=0.068512
ndcg@1=0.617510  ndcg@2=0.706836  ndcg@5=0.785934  ndcg@10=0.801616  ndcg@20=0.808637
hit_rate@1=0.617510  hit_rate@2=0.830702  hit_rate@5=0.950709  hit_rate@10=0.976965  hit_rate@20=0.992590
map@1=0.617510  map@2=0.668996  map@5=0.726214  map@10=0.735446  map@20=0.738188
mrr@1=0.617510  mrr@2=0.723945  mrr@5=0.759492  mrr@10=0.762923  mrr@20=0.763992
f1@1=0.538203  f1@2=0.557070  f1@5=0.379270  f1@10=0.227252  f1@20=0.125973

Epoch 78/100: 100%|██████████| 820/820 [00:14<00:00, 57.15it/s, bpr=0.04, c=2.34, loss=0.134]

[VAL]
recall@1=0.496561  recall@2=0.737880  recall@5=0.924497  recall@10=0.961741  recall@20=0.987064
precision@1=0.607581  precision@2=0.470081  precision@5=0.251129  precision@10=0.132927  precision@20=0.068690
ndcg@1=0.607581  ndcg@2=0.700801  ndcg@5=0.783508  ndcg@10=0.797829  ndcg@20=0.805316
hit_rate@1=0.607581  hit_rate@2=0.827823  hit_rate@5=0.956048  hit_rate@10=0.977581  hit_rate@20=0.993790
map@1=0.607581  map@2=0.661875  map@5=0.721001  map@10=0.729946  map@20=0.732957
mrr@1=0.607581  mrr@2=0.717903  mrr@5=0.755243  mrr@10=0.758207  mrr@20=0.759575
f1@1=0.529305  f1@2=0.552727  f1@5=0.380669  f1@10=0.227320  f1@20=0.126230

[TEST]
recall@1=0.497259  recall@2=0.736192  recall@5=0.924724  recall@10=0.963586  recall@20=0.986402
precision@1=0.606959  precision@2=0.469072  precision@5=0.250902  precision@10=0.133030  precision@20=0.068504
ndcg@1=0.606959  ndcg@2=0.699298  ndcg@5=0.783616  ndcg@10=0.798658  ndcg@20=0.805211
hit_rate@1=0.606959  hit_rate@2=0.825789  hit_rate@5=0.955380  hit_rate@10=0.977932  hit_rate@20=0.992912
map@1=0.606959  map@2=0.660680  map@5=0.721532  map@10=0.730962  map@20=0.733425
mrr@1=0.606959  mrr@2=0.716173  mrr@5=0.754161  mrr@10=0.757296  mrr@20=0.758247
f1@1=0.529813  f1@2=0.551769  f1@5=0.380768  f1@10=0.227676  f1@20=0.125964

Epoch 79/100: 100%|██████████| 820/820 [00:14<00:00, 57.73it/s, bpr=0.0229, c=2.47, loss=0.122]

[VAL]
recall@1=0.498553  recall@2=0.732280  recall@5=0.922235  recall@10=0.960680  recall@20=0.986596
precision@1=0.609919  precision@2=0.467823  precision@5=0.250500  precision@10=0.132831  precision@20=0.068690
ndcg@1=0.609919  ndcg@2=0.698277  ndcg@5=0.782265  ndcg@10=0.797235  ndcg@20=0.804748
hit_rate@1=0.609919  hit_rate@2=0.821774  hit_rate@5=0.954597  hit_rate@10=0.976613  hit_rate@20=0.993548
map@1=0.609919  map@2=0.660524  map@5=0.720214  map@10=0.729602  map@20=0.732489
mrr@1=0.609919  mrr@2=0.715968  mrr@5=0.754616  mrr@10=0.757835  mrr@20=0.759080
f1@1=0.531372  f1@2=0.549247  f1@5=0.379762  f1@10=0.227115  f1@20=0.126201

[TEST]
recall@1=0.495546  recall@2=0.734627  recall@5=0.924939  recall@10=0.961588  recall@20=0.985719
precision@1=0.607200  precision@2=0.469475  precision@5=0.250902  precision@10=0.132732  precision@20=0.068464
ndcg@1=0.607200  ndcg@2=0.698412  ndcg@5=0.783082  ndcg@10=0.797343  ndcg@20=0.804397
hit_rate@1=0.607200  hit_rate@2=0.822809  hit_rate@5=0.955702  hit_rate@10=0.975999  hit_rate@20=0.992429
map@1=0.607200  map@2=0.660257  map@5=0.720742  map@10=0.729764  map@20=0.732494
mrr@1=0.607200  mrr@2=0.714884  mrr@5=0.753808  mrr@10=0.756607  mrr@20=0.757863
f1@1=0.528709  f1@2=0.551406  f1@5=0.380802  f1@10=0.227193  f1@20=0.125887

Epoch 80/100: 100%|██████████| 820/820 [00:14<00:00, 57.41it/s, bpr=0.0259, c=2.54, loss=0.128]

[VAL]
recall@1=0.504489  recall@2=0.739009  recall@5=0.921060  recall@10=0.961147  recall@20=0.986616
precision@1=0.616210  precision@2=0.472903  precision@5=0.250371  precision@10=0.132758  precision@20=0.068645
ndcg@1=0.616210  ndcg@2=0.705093  ndcg@5=0.785331  ndcg@10=0.800584  ndcg@20=0.807896
hit_rate@1=0.616210  hit_rate@2=0.827339  hit_rate@5=0.952661  hit_rate@10=0.977339  hit_rate@20=0.993710
map@1=0.616210  map@2=0.667802  map@5=0.725022  map@10=0.734357  map@20=0.737084
mrr@1=0.616210  mrr@2=0.721452  mrr@5=0.758297  mrr@10=0.761720  mrr@20=0.762688
f1@1=0.537429  f1@2=0.554819  f1@5=0.379461  f1@10=0.227074  f1@20=0.126149

[TEST]
recall@1=0.495972  recall@2=0.740165  recall@5=0.921420  recall@10=0.963255  recall@20=0.986124
precision@1=0.606476  precision@2=0.473905  precision@5=0.250354  precision@10=0.132917  precision@20=0.068488
ndcg@1=0.606476  ndcg@2=0.703035  ndcg@5=0.782693  ndcg@10=0.798618  ndcg@20=0.805468
hit_rate@1=0.606476  hit_rate@2=0.829494  hit_rate@5=0.951756  hit_rate@10=0.977368  hit_rate@20=0.992751
map@1=0.606476  map@2=0.664485  map@5=0.721579  map@10=0.731235  map@20=0.734044
mrr@1=0.606476  mrr@2=0.718307  mrr@5=0.753734  mrr@10=0.757373  mrr@20=0.758766
f1@1=0.528680  f1@2=0.556034  f1@5=0.379808  f1@10=0.227539  f1@20=0.125935

Epoch 81/100: 100%|██████████| 820/820 [00:14<00:00, 57.64it/s, bpr=0.0401, c=2.39, loss=0.136]

[VAL]
recall@1=0.506906  recall@2=0.751725  recall@5=0.925527  recall@10=0.960437  recall@20=0.986566
precision@1=0.619597  precision@2=0.480242  precision@5=0.251661  precision@10=0.132750  precision@20=0.068677
ndcg@1=0.619597  ndcg@2=0.714646  ndcg@5=0.791044  ndcg@10=0.804440  ndcg@20=0.811996
hit_rate@1=0.619597  hit_rate@2=0.839597  hit_rate@5=0.956613  hit_rate@10=0.976452  hit_rate@20=0.993468
map@1=0.619597  map@2=0.676331  map@5=0.731303  map@10=0.739678  map@20=0.742549
mrr@1=0.619597  mrr@2=0.729435  mrr@5=0.763859  mrr@10=0.766617  mrr@20=0.767771
f1@1=0.540072  f1@2=0.563876  f1@5=0.381391  f1@10=0.227019  f1@20=0.126184

[TEST]
recall@1=0.510473  recall@2=0.753521  recall@5=0.926045  recall@10=0.961818  recall@20=0.986028
precision@1=0.624436  precision@2=0.482724  precision@5=0.251852  precision@10=0.132788  precision@20=0.068472
ndcg@1=0.624436  ndcg@2=0.717807  ndcg@5=0.793545  ndcg@10=0.807192  ndcg@20=0.814318
hit_rate@1=0.624436  hit_rate@2=0.841092  hit_rate@5=0.954816  hit_rate@10=0.976562  hit_rate@20=0.992751
map@1=0.624436  map@2=0.680030  map@5=0.734872  map@10=0.743199  map@20=0.746002
mrr@1=0.624436  mrr@2=0.732925  mrr@5=0.766408  mrr@10=0.769407  mrr@20=0.770760
f1@1=0.544253  f1@2=0.566296  f1@5=0.381941  f1@10=0.227277  f1@20=0.125912

Epoch 82/100: 100%|██████████| 820/820 [00:14<00:00, 57.63it/s, bpr=0.0232, c=2.6, loss=0.127]

[VAL]
recall@1=0.505989  recall@2=0.738678  recall@5=0.920687  recall@10=0.956840  recall@20=0.986403
precision@1=0.618710  precision@2=0.472097  precision@5=0.250323  precision@10=0.132274  precision@20=0.068621
ndcg@1=0.618710  ndcg@2=0.705467  ndcg@5=0.785881  ndcg@10=0.799793  ndcg@20=0.808206
hit_rate@1=0.618710  hit_rate@2=0.827903  hit_rate@5=0.952258  hit_rate@10=0.973629  hit_rate@20=0.993710
map@1=0.618710  map@2=0.668004  map@5=0.725664  map@10=0.734308  map@20=0.737397
mrr@1=0.618710  mrr@2=0.723145  mrr@5=0.759695  mrr@10=0.762685  mrr@20=0.763966
f1@1=0.539331  f1@2=0.554199  f1@5=0.379350  f1@10=0.226178  f1@20=0.126107

[TEST]
recall@1=0.501231  recall@2=0.741744  recall@5=0.920369  recall@10=0.958888  recall@20=0.985965
precision@1=0.613563  precision@2=0.474992  precision@5=0.250081  precision@10=0.132418  precision@20=0.068448
ndcg@1=0.613563  ndcg@2=0.706090  ndcg@5=0.784448  ndcg@10=0.799258  ndcg@20=0.807223
hit_rate@1=0.613563  hit_rate@2=0.830380  hit_rate@5=0.950870  hit_rate@10=0.974146  hit_rate@20=0.992510
map@1=0.613563  map@2=0.668110  map@5=0.724267  map@10=0.733373  map@20=0.736543
mrr@1=0.613563  mrr@2=0.722133  mrr@5=0.757000  mrr@10=0.760265  mrr@20=0.761867
f1@1=0.534578  f1@2=0.557336  f1@5=0.379363  f1@10=0.226626  f1@20=0.125870

Epoch 83/100: 100%|██████████| 820/820 [00:14<00:00, 57.61it/s, bpr=0.0266, c=2.55, loss=0.128]

[VAL]
recall@1=0.505557  recall@2=0.746801  recall@5=0.924448  recall@10=0.960390  recall@20=0.986561
precision@1=0.618226  precision@2=0.476855  precision@5=0.251419  precision@10=0.132702  precision@20=0.068649
ndcg@1=0.618226  ndcg@2=0.710753  ndcg@5=0.789052  ndcg@10=0.802850  ndcg@20=0.810520
hit_rate@1=0.618226  hit_rate@2=0.836532  hit_rate@5=0.955000  hit_rate@10=0.976694  hit_rate@20=0.993710
map@1=0.618226  map@2=0.672258  map@5=0.728876  map@10=0.737397  map@20=0.740416
mrr@1=0.618226  mrr@2=0.727500  mrr@5=0.762008  mrr@10=0.765063  mrr@20=0.766434
f1@1=0.538818  f1@2=0.560128  f1@5=0.380982  f1@10=0.226955  f1@20=0.126149

[TEST]
recall@1=0.511274  recall@2=0.749794  recall@5=0.925116  recall@10=0.962375  recall@20=0.986284
precision@1=0.625242  precision@2=0.479422  precision@5=0.251337  precision@10=0.132829  precision@20=0.068504
ndcg@1=0.625242  ndcg@2=0.715004  ndcg@5=0.792208  ndcg@10=0.806515  ndcg@20=0.813427
hit_rate@1=0.625242  hit_rate@2=0.839401  hit_rate@5=0.954414  hit_rate@10=0.976804  hit_rate@20=0.992832
map@1=0.625242  map@2=0.676909  map@5=0.733021  map@10=0.741826  map@20=0.744442
mrr@1=0.625242  mrr@2=0.732200  mrr@5=0.765931  mrr@10=0.769002  mrr@20=0.770089
f1@1=0.545205  f1@2=0.562921  f1@5=0.381342  f1@10=0.227357  f1@20=0.125964

Epoch 84/100: 100%|██████████| 820/820 [00:14<00:00, 57.44it/s, bpr=0.032, c=2.46, loss=0.13]

[VAL]
recall@1=0.506588  recall@2=0.741638  recall@5=0.921181  recall@10=0.958170  recall@20=0.986452
precision@1=0.619758  precision@2=0.475000  precision@5=0.250742  precision@10=0.132363  precision@20=0.068669
ndcg@1=0.619758  ndcg@2=0.708378  ndcg@5=0.787062  ndcg@10=0.801161  ndcg@20=0.809529
hit_rate@1=0.619758  hit_rate@2=0.830484  hit_rate@5=0.952177  hit_rate@10=0.975081  hit_rate@20=0.993548
map@1=0.619758  map@2=0.671069  map@5=0.727393  map@10=0.735991  map@20=0.739351
mrr@1=0.619758  mrr@2=0.725363  mrr@5=0.760499  mrr@10=0.763873  mrr@20=0.765322
f1@1=0.540023  f1@2=0.557050  f1@5=0.379835  f1@10=0.226382  f1@20=0.126168

[TEST]
recall@1=0.506948  recall@2=0.742156  recall@5=0.920850  recall@10=0.960060  recall@20=0.985981
precision@1=0.621134  precision@2=0.475838  precision@5=0.250338  precision@10=0.132490  precision@20=0.068496
ndcg@1=0.621134  ndcg@2=0.708745  ndcg@5=0.787494  ndcg@10=0.802266  ndcg@20=0.809780
hit_rate@1=0.621134  hit_rate@2=0.830139  hit_rate@5=0.951353  hit_rate@10=0.975113  hit_rate@20=0.992993
map@1=0.621134  map@2=0.671573  map@5=0.728100  map@10=0.737022  map@20=0.739898
mrr@1=0.621134  mrr@2=0.725395  mrr@5=0.761316  mrr@10=0.764397  mrr@20=0.765669
f1@1=0.540779  f1@2=0.557946  f1@5=0.379671  f1@10=0.226774  f1@20=0.125930

Epoch 85/100: 100%|██████████| 820/820 [00:14<00:00, 57.55it/s, bpr=0.0214, c=2.41, loss=0.118]

[VAL]
recall@1=0.507700  recall@2=0.751993  recall@5=0.921545  recall@10=0.958080  recall@20=0.986416
precision@1=0.620806  precision@2=0.481048  precision@5=0.250758  precision@10=0.132379  precision@20=0.068653
ndcg@1=0.620806  ndcg@2=0.715485  ndcg@5=0.789465  ndcg@10=0.803484  ndcg@20=0.811756
hit_rate@1=0.620806  hit_rate@2=0.840887  hit_rate@5=0.952097  hit_rate@10=0.974839  hit_rate@20=0.993387
map@1=0.620806  map@2=0.677117  map@5=0.730677  map@10=0.739261  map@20=0.742499
mrr@1=0.620806  mrr@2=0.730726  mrr@5=0.763128  mrr@10=0.766376  mrr@20=0.767675
f1@1=0.541091  f1@2=0.564461  f1@5=0.379928  f1@10=0.226387  f1@20=0.126154

[TEST]
recall@1=0.510273  recall@2=0.750609  recall@5=0.922772  recall@10=0.961112  recall@20=0.986704
precision@1=0.625805  precision@2=0.481153  precision@5=0.251079  precision@10=0.132748  precision@20=0.068565
ndcg@1=0.625805  ndcg@2=0.716077  ndcg@5=0.791326  ndcg@10=0.805971  ndcg@20=0.813475
hit_rate@1=0.625805  hit_rate@2=0.838515  hit_rate@5=0.952642  hit_rate@10=0.975918  hit_rate@20=0.993154
map@1=0.625805  map@2=0.678500  map@5=0.732759  map@10=0.741703  map@20=0.744685
mrr@1=0.625805  mrr@2=0.732281  mrr@5=0.765496  mrr@10=0.768717  mrr@20=0.770077
f1@1=0.544535  f1@2=0.564306  f1@5=0.380721  f1@10=0.227158  f1@20=0.126059

Epoch 86/100: 100%|██████████| 820/820 [00:14<00:00, 57.19it/s, bpr=0.0242, c=2.44, loss=0.122]

[VAL]
recall@1=0.501472  recall@2=0.731638  recall@5=0.918559  recall@10=0.958018  recall@20=0.986749
precision@1=0.611210  precision@2=0.466774  precision@5=0.249339  precision@10=0.132363  precision@20=0.068657
ndcg@1=0.611210  ndcg@2=0.698189  ndcg@5=0.781005  ndcg@10=0.796213  ndcg@20=0.804545
hit_rate@1=0.611210  hit_rate@2=0.821855  hit_rate@5=0.951290  hit_rate@10=0.974597  hit_rate@20=0.994113
map@1=0.611210  map@2=0.660665  map@5=0.719790  map@10=0.729232  map@20=0.732417
mrr@1=0.611210  mrr@2=0.716250  mrr@5=0.754105  mrr@10=0.757272  mrr@20=0.758760
f1@1=0.533775  f1@2=0.548521  f1@5=0.378092  f1@10=0.226373  f1@20=0.126156

[TEST]
recall@1=0.498693  recall@2=0.727678  recall@5=0.920847  recall@10=0.960360  recall@20=0.985501
precision@1=0.609133  precision@2=0.464401  precision@5=0.249936  precision@10=0.132603  precision@20=0.068436
ndcg@1=0.609133  ndcg@2=0.694796  ndcg@5=0.780628  ndcg@10=0.795999  ndcg@20=0.803276
hit_rate@1=0.609133  hit_rate@2=0.816527  hit_rate@5=0.952481  hit_rate@10=0.975193  hit_rate@20=0.992429
map@1=0.609133  map@2=0.657639  map@5=0.718649  map@10=0.728338  map@20=0.731134
mrr@1=0.609133  mrr@2=0.713112  mrr@5=0.752250  mrr@10=0.755589  mrr@20=0.756830
f1@1=0.531464  f1@2=0.545745  f1@5=0.379213  f1@10=0.226934  f1@20=0.125835

Epoch 87/100: 100%|██████████| 820/820 [00:14<00:00, 56.99it/s, bpr=0.0404, c=2.42, loss=0.137]

[VAL]
recall@1=0.492769  recall@2=0.730500  recall@5=0.920425  recall@10=0.960496  recall@20=0.986533
precision@1=0.603790  precision@2=0.466129  precision@5=0.249968  precision@10=0.132750  precision@20=0.068690
ndcg@1=0.603790  ndcg@2=0.694661  ndcg@5=0.778588  ndcg@10=0.794096  ndcg@20=0.801663
hit_rate@1=0.603790  hit_rate@2=0.821290  hit_rate@5=0.952742  hit_rate@10=0.976613  hit_rate@20=0.993629
map@1=0.603790  map@2=0.655907  map@5=0.715697  map@10=0.725352  map@20=0.728245
mrr@1=0.603790  mrr@2=0.712621  mrr@5=0.750669  mrr@10=0.754143  mrr@20=0.755368
f1@1=0.525528  f1@2=0.547599  f1@5=0.379012  f1@10=0.227033  f1@20=0.126206

[TEST]
recall@1=0.492776  recall@2=0.727671  recall@5=0.922153  recall@10=0.962877  recall@20=0.985601
precision@1=0.603012  precision@2=0.464481  precision@5=0.250306  precision@10=0.132966  precision@20=0.068452
ndcg@1=0.603012  ndcg@2=0.692303  ndcg@5=0.779022  ndcg@10=0.794745  ndcg@20=0.801378
hit_rate@1=0.603012  hit_rate@2=0.818057  hit_rate@5=0.953689  hit_rate@10=0.977610  hit_rate@20=0.992510
map@1=0.603012  map@2=0.653934  map@5=0.715929  map@10=0.725723  map@20=0.728321
mrr@1=0.603012  mrr@2=0.710454  mrr@5=0.749852  mrr@10=0.753132  mrr@20=0.754297
f1@1=0.525507  f1@2=0.545856  f1@5=0.379781  f1@10=0.227546  f1@20=0.125862

Epoch 88/100: 100%|██████████| 820/820 [00:14<00:00, 57.55it/s, bpr=0.0157, c=2.57, loss=0.119]

[VAL]
recall@1=0.508426  recall@2=0.739419  recall@5=0.922196  recall@10=0.959312  recall@20=0.986503
precision@1=0.622823  precision@2=0.473065  precision@5=0.250758  precision@10=0.132532  precision@20=0.068629
ndcg@1=0.622823  ndcg@2=0.707137  ndcg@5=0.787788  ndcg@10=0.801991  ndcg@20=0.809778
hit_rate@1=0.622823  hit_rate@2=0.828952  hit_rate@5=0.953226  hit_rate@10=0.975484  hit_rate@20=0.993790
map@1=0.622823  map@2=0.669819  map@5=0.727727  map@10=0.736504  map@20=0.739369
mrr@1=0.622823  mrr@2=0.725685  mrr@5=0.762087  mrr@10=0.765209  mrr@20=0.766361
f1@1=0.542280  f1@2=0.555074  f1@5=0.380028  f1@10=0.226668  f1@20=0.126118

[TEST]
recall@1=0.505815  recall@2=0.737194  recall@5=0.922160  recall@10=0.962584  recall@20=0.986109
precision@1=0.619604  precision@2=0.472495  precision@5=0.250741  precision@10=0.132877  precision@20=0.068484
ndcg@1=0.619604  ndcg@2=0.705020  ndcg@5=0.786581  ndcg@10=0.801903  ndcg@20=0.808858
hit_rate@1=0.619604  hit_rate@2=0.825950  hit_rate@5=0.952320  hit_rate@10=0.977046  hit_rate@20=0.992912
map@1=0.619604  map@2=0.668049  map@5=0.726436  map@10=0.735781  map@20=0.738557
mrr@1=0.619604  mrr@2=0.722978  mrr@5=0.759674  mrr@10=0.763062  mrr@20=0.764447
f1@1=0.539544  f1@2=0.554138  f1@5=0.380262  f1@10=0.227421  f1@20=0.125921

Epoch 89/100: 100%|██████████| 820/820 [00:14<00:00, 57.69it/s, bpr=0.0499, c=2.51, loss=0.15]

[VAL]
recall@1=0.493326  recall@2=0.737722  recall@5=0.918617  recall@10=0.957898  recall@20=0.986275
precision@1=0.604758  precision@2=0.470484  precision@5=0.249565  precision@10=0.132427  precision@20=0.068645
ndcg@1=0.604758  ndcg@2=0.700030  ndcg@5=0.779555  ndcg@10=0.794691  ndcg@20=0.803037
hit_rate@1=0.604758  hit_rate@2=0.827419  hit_rate@5=0.951613  hit_rate@10=0.974274  hit_rate@20=0.993468
map@1=0.604758  map@2=0.660927  map@5=0.717555  map@10=0.726989  map@20=0.730313
mrr@1=0.604758  mrr@2=0.716331  mrr@5=0.752363  mrr@10=0.755619  mrr@20=0.757196
f1@1=0.526097  f1@2=0.552769  f1@5=0.378282  f1@10=0.226450  f1@20=0.126139

[TEST]
recall@1=0.497693  recall@2=0.732022  recall@5=0.920193  recall@10=0.960581  recall@20=0.985499
precision@1=0.608167  precision@2=0.466696  precision@5=0.249630  precision@10=0.132635  precision@20=0.068468
ndcg@1=0.608167  ndcg@2=0.696742  ndcg@5=0.780887  ndcg@10=0.796508  ndcg@20=0.803613
hit_rate@1=0.608167  hit_rate@2=0.820715  hit_rate@5=0.951675  hit_rate@10=0.975677  hit_rate@20=0.992268
map@1=0.608167  map@2=0.658807  map@5=0.719296  map@10=0.728991  map@20=0.731581
mrr@1=0.608167  mrr@2=0.714199  mrr@5=0.752690  mrr@10=0.756003  mrr@20=0.757082
f1@1=0.530478  f1@2=0.548839  f1@5=0.378873  f1@10=0.226991  f1@20=0.125882

Epoch 90/100: 100%|██████████| 820/820 [00:14<00:00, 57.66it/s, bpr=0.0237, c=2.54, loss=0.125]

[VAL]
recall@1=0.513732  recall@2=0.763088  recall@5=0.927964  recall@10=0.962704  recall@20=0.987102
precision@1=0.626774  precision@2=0.487540  precision@5=0.252532  precision@10=0.132984  precision@20=0.068710
ndcg@1=0.626774  ndcg@2=0.724907  ndcg@5=0.797136  ndcg@10=0.810349  ndcg@20=0.817491
hit_rate@1=0.626774  hit_rate@2=0.850000  hit_rate@5=0.957903  hit_rate@10=0.978387  hit_rate@20=0.993710
map@1=0.626774  map@2=0.686552  map@5=0.739067  map@10=0.747241  map@20=0.750024
mrr@1=0.626774  mrr@2=0.738387  mrr@5=0.770020  mrr@10=0.772831  mrr@20=0.773951
f1@1=0.547120  f1@2=0.572530  f1@5=0.382585  f1@10=0.227450  f1@20=0.126248

[TEST]
recall@1=0.515634  recall@2=0.760802  recall@5=0.929941  recall@10=0.963765  recall@20=0.986733
precision@1=0.630557  precision@2=0.487234  precision@5=0.252803  precision@10=0.133014  precision@20=0.068569
ndcg@1=0.630557  ndcg@2=0.724431  ndcg@5=0.798784  ndcg@10=0.811814  ndcg@20=0.818557
hit_rate@1=0.630557  hit_rate@2=0.846811  hit_rate@5=0.958119  hit_rate@10=0.977771  hit_rate@20=0.993154
map@1=0.630557  map@2=0.686836  map@5=0.740778  map@10=0.748955  map@20=0.751605
mrr@1=0.630557  mrr@2=0.738684  mrr@5=0.771577  mrr@10=0.774326  mrr@20=0.775460
f1@1=0.549799  f1@2=0.571812  f1@5=0.383474  f1@10=0.227683  f1@20=0.126067

Saved new best checkpoint at epoch 90

Epoch 91/100: 100%|██████████| 820/820 [00:14<00:00, 56.84it/s, bpr=0.0497, c=2.6, loss=0.154]

[VAL]
recall@1=0.494523  recall@2=0.739001  recall@5=0.921018  recall@10=0.958965  recall@20=0.987520
precision@1=0.603790  precision@2=0.471169  precision@5=0.250371  precision@10=0.132556  precision@20=0.068738
ndcg@1=0.603790  ndcg@2=0.700883  ndcg@5=0.781710  ndcg@10=0.796215  ndcg@20=0.804629
hit_rate@1=0.603790  hit_rate@2=0.827903  hit_rate@5=0.952661  hit_rate@10=0.975081  hit_rate@20=0.994032
map@1=0.603790  map@2=0.662036  map@5=0.720193  map@10=0.729144  map@20=0.732472
mrr@1=0.603790  mrr@2=0.716008  mrr@5=0.752597  mrr@10=0.755686  mrr@20=0.757312
f1@1=0.526711  f1@2=0.553742  f1@5=0.379424  f1@10=0.226674  f1@20=0.126305

[TEST]
recall@1=0.500436  recall@2=0.739696  recall@5=0.922232  recall@10=0.962313  recall@20=0.986935
precision@1=0.610341  precision@2=0.471972  precision@5=0.250370  precision@10=0.132788  precision@20=0.068593
ndcg@1=0.610341  ndcg@2=0.703147  ndcg@5=0.784491  ndcg@10=0.799785  ndcg@20=0.806872
hit_rate@1=0.610341  hit_rate@2=0.828206  hit_rate@5=0.952642  hit_rate@10=0.976482  hit_rate@20=0.993235
map@1=0.610341  map@2=0.665009  map@5=0.723718  map@10=0.733085  map@20=0.735711
mrr@1=0.610341  mrr@2=0.719112  mrr@5=0.755794  mrr@10=0.759089  mrr@20=0.760148
f1@1=0.532991  f1@2=0.554815  f1@5=0.379935  f1@10=0.227307  f1@20=0.126106

Epoch 92/100: 100%|██████████| 820/820 [00:14<00:00, 57.36it/s, bpr=0.0753, c=2.4, loss=0.171]

[VAL]
recall@1=0.494964  recall@2=0.744419  recall@5=0.917815  recall@10=0.963483  recall@20=0.987007
precision@1=0.603145  precision@2=0.475323  precision@5=0.249306  precision@10=0.133089  precision@20=0.068730
ndcg@1=0.603145  ndcg@2=0.704455  ndcg@5=0.780826  ndcg@10=0.798022  ndcg@20=0.804760
hit_rate@1=0.603145  hit_rate@2=0.831774  hit_rate@5=0.949516  hit_rate@10=0.979274  hit_rate@20=0.993790
map@1=0.603145  map@2=0.665645  map@5=0.720716  map@10=0.730862  map@20=0.733376
mrr@1=0.603145  mrr@2=0.716976  mrr@5=0.751511  mrr@10=0.755620  mrr@20=0.756258
f1@1=0.526814  f1@2=0.558280  f1@5=0.377915  f1@10=0.227603  f1@20=0.126270

[TEST]
recall@1=0.497921  recall@2=0.744706  recall@5=0.922430  recall@10=0.965299  recall@20=0.986492
precision@1=0.608892  precision@2=0.477126  precision@5=0.250499  precision@10=0.133135  precision@20=0.068549
ndcg@1=0.608892  ndcg@2=0.706974  ndcg@5=0.784658  ndcg@10=0.800849  ndcg@20=0.807408
hit_rate@1=0.608892  hit_rate@2=0.830380  hit_rate@5=0.951595  hit_rate@10=0.979704  hit_rate@20=0.993154
map@1=0.608892  map@2=0.669217  map@5=0.724730  map@10=0.734274  map@20=0.737138
mrr@1=0.608892  mrr@2=0.720119  mrr@5=0.754583  mrr@10=0.758515  mrr@20=0.759966
f1@1=0.530743  f1@2=0.559774  f1@5=0.380063  f1@10=0.227908  f1@20=0.126025

Epoch 93/100: 100%|██████████| 820/820 [00:14<00:00, 57.21it/s, bpr=0.0249, c=2.52, loss=0.126]

[VAL]
recall@1=0.502745  recall@2=0.743115  recall@5=0.921125  recall@10=0.959523  recall@20=0.986701
precision@1=0.614516  precision@2=0.474677  precision@5=0.250613  precision@10=0.132629  precision@20=0.068673
ndcg@1=0.614516  ndcg@2=0.707234  ndcg@5=0.785569  ndcg@10=0.800370  ndcg@20=0.808193
hit_rate@1=0.614516  hit_rate@2=0.832742  hit_rate@5=0.952339  hit_rate@10=0.975403  hit_rate@20=0.993790
map@1=0.614516  map@2=0.668851  map@5=0.725217  map@10=0.734390  map@20=0.737327
mrr@1=0.614516  mrr@2=0.723831  mrr@5=0.758532  mrr@10=0.761923  mrr@20=0.763217
f1@1=0.535776  f1@2=0.557403  f1@5=0.379669  f1@10=0.226770  f1@20=0.126183

[TEST]
recall@1=0.505539  recall@2=0.742513  recall@5=0.925268  recall@10=0.962644  recall@20=0.986075
precision@1=0.619201  precision@2=0.475032  precision@5=0.251369  precision@10=0.132829  precision@20=0.068500
ndcg@1=0.619201  ndcg@2=0.707865  ndcg@5=0.788743  ndcg@10=0.803095  ndcg@20=0.809967
hit_rate@1=0.619201  hit_rate@2=0.830541  hit_rate@5=0.954736  hit_rate@10=0.977368  hit_rate@20=0.992912
map@1=0.619201  map@2=0.670244  map@5=0.728500  map@10=0.737323  map@20=0.740027
mrr@1=0.619201  mrr@2=0.724670  mrr@5=0.761053  mrr@10=0.764139  mrr@20=0.765319
f1@1=0.539296  f1@2=0.557687  f1@5=0.381385  f1@10=0.227378  f1@20=0.125941

Epoch 94/100: 100%|██████████| 820/820 [00:14<00:00, 57.10it/s, bpr=0.0129, c=2.6, loss=0.117]

[VAL]
recall@1=0.507727  recall@2=0.742745  recall@5=0.920347  recall@10=0.958475  recall@20=0.985850
precision@1=0.621694  precision@2=0.475121  precision@5=0.250387  precision@10=0.132452  precision@20=0.068613
ndcg@1=0.621694  ndcg@2=0.709101  ndcg@5=0.787243  ndcg@10=0.801785  ndcg@20=0.809567
hit_rate@1=0.621694  hit_rate@2=0.833065  hit_rate@5=0.951774  hit_rate@10=0.975000  hit_rate@20=0.993065
map@1=0.621694  map@2=0.671210  map@5=0.727580  map@10=0.736466  map@20=0.739290
mrr@1=0.621694  mrr@2=0.727218  mrr@5=0.761960  mrr@10=0.765274  mrr@20=0.766274
f1@1=0.541339  f1@2=0.557563  f1@5=0.379317  f1@10=0.226491  f1@20=0.126074

[TEST]
recall@1=0.505949  recall@2=0.740439  recall@5=0.922623  recall@10=0.961583  recall@20=0.986117
precision@1=0.619523  precision@2=0.474468  precision@5=0.250934  precision@10=0.132796  precision@20=0.068553
ndcg@1=0.619523  ndcg@2=0.707168  ndcg@5=0.787534  ndcg@10=0.802308  ndcg@20=0.809703
hit_rate@1=0.619523  hit_rate@2=0.830300  hit_rate@5=0.951836  hit_rate@10=0.976079  hit_rate@20=0.992832
map@1=0.619523  map@2=0.669559  map@5=0.727569  map@10=0.736494  map@20=0.739555
mrr@1=0.619523  mrr@2=0.725072  mrr@5=0.760528  mrr@10=0.763808  mrr@20=0.765428
f1@1=0.539717  f1@2=0.556511  f1@5=0.380547  f1@10=0.227247  f1@20=0.126016

Epoch 95/100: 100%|██████████| 820/820 [00:14<00:00, 56.87it/s, bpr=0.0484, c=2.35, loss=0.143]

[VAL]
recall@1=0.492563  recall@2=0.724484  recall@5=0.908890  recall@10=0.957004  recall@20=0.986280
precision@1=0.603145  precision@2=0.464113  precision@5=0.247129  precision@10=0.132242  precision@20=0.068629
ndcg@1=0.603145  ndcg@2=0.690995  ndcg@5=0.772135  ndcg@10=0.790208  ndcg@20=0.798539
hit_rate@1=0.603145  hit_rate@2=0.815968  hit_rate@5=0.943065  hit_rate@10=0.973871  hit_rate@20=0.993306
map@1=0.603145  map@2=0.653024  map@5=0.710682  map@10=0.721408  map@20=0.724463
mrr@1=0.603145  mrr@2=0.709315  mrr@5=0.746527  mrr@10=0.750857  mrr@20=0.752059
f1@1=0.525147  f1@2=0.544156  f1@5=0.374492  f1@10=0.226146  f1@20=0.126112

[TEST]
recall@1=0.497802  recall@2=0.724927  recall@5=0.909062  recall@10=0.958427  recall@20=0.985689
precision@1=0.609294  precision@2=0.464320  precision@5=0.246714  precision@10=0.132233  precision@20=0.068424
ndcg@1=0.609294  ndcg@2=0.693274  ndcg@5=0.774191  ndcg@10=0.792750  ndcg@20=0.800835
hit_rate@1=0.609294  hit_rate@2=0.816527  hit_rate@5=0.943621  hit_rate@10=0.973744  hit_rate@20=0.992671
map@1=0.609294  map@2=0.655847  map@5=0.713293  map@10=0.724344  map@20=0.727610
mrr@1=0.609294  mrr@2=0.713152  mrr@5=0.749741  mrr@10=0.753849  mrr@20=0.755467
f1@1=0.530882  f1@2=0.544742  f1@5=0.374377  f1@10=0.226367  f1@20=0.125823

Epoch 96/100: 100%|██████████| 820/820 [00:14<00:00, 57.05it/s, bpr=0.0728, c=2.41, loss=0.169]

[VAL]
recall@1=0.503423  recall@2=0.741053  recall@5=0.919366  recall@10=0.960188  recall@20=0.987191
precision@1=0.614435  precision@2=0.473226  precision@5=0.250032  precision@10=0.132831  precision@20=0.068742
ndcg@1=0.614435  ndcg@2=0.705684  ndcg@5=0.784271  ndcg@10=0.799886  ndcg@20=0.807713
hit_rate@1=0.614435  hit_rate@2=0.829355  hit_rate@5=0.951048  hit_rate@10=0.976048  hit_rate@20=0.994113
map@1=0.614435  map@2=0.667903  map@5=0.724259  map@10=0.733776  map@20=0.736788
mrr@1=0.614435  mrr@2=0.721976  mrr@5=0.757206  mrr@10=0.760823  mrr@20=0.762114
f1@1=0.536290  f1@2=0.555888  f1@5=0.378854  f1@10=0.227077  f1@20=0.126288

[TEST]
recall@1=0.502264  recall@2=0.738529  recall@5=0.921349  recall@10=0.962885  recall@20=0.985618
precision@1=0.612919  precision@2=0.471851  precision@5=0.250226  precision@10=0.132966  precision@20=0.068468
ndcg@1=0.612919  ndcg@2=0.703335  ndcg@5=0.784495  ndcg@10=0.800368  ndcg@20=0.807066
hit_rate@1=0.612919  hit_rate@2=0.827159  hit_rate@5=0.952642  hit_rate@10=0.977529  hit_rate@20=0.992268
map@1=0.612919  map@2=0.665613  map@5=0.723932  map@10=0.733701  map@20=0.736374
mrr@1=0.612919  mrr@2=0.719958  mrr@5=0.756496  mrr@10=0.759849  mrr@20=0.761011
f1@1=0.535139  f1@2=0.554360  f1@5=0.379621  f1@10=0.227540  f1@20=0.125889

Epoch 97/100: 100%|██████████| 820/820 [00:14<00:00, 57.54it/s, bpr=0.0437, c=2.58, loss=0.147]

[VAL]
recall@1=0.498029  recall@2=0.737692  recall@5=0.916404  recall@10=0.958032  recall@20=0.986117
precision@1=0.609677  precision@2=0.471855  precision@5=0.249065  precision@10=0.132435  precision@20=0.068673
ndcg@1=0.609677  ndcg@2=0.701762  ndcg@5=0.779988  ndcg@10=0.795839  ndcg@20=0.803942
hit_rate@1=0.609677  hit_rate@2=0.827339  hit_rate@5=0.949032  hit_rate@10=0.974516  hit_rate@20=0.992984
map@1=0.609677  map@2=0.663407  map@5=0.719236  map@10=0.728855  map@20=0.731913
mrr@1=0.609677  mrr@2=0.718347  mrr@5=0.753551  mrr@10=0.757055  mrr@20=0.758281
f1@1=0.531037  f1@2=0.553780  f1@5=0.377487  f1@10=0.226424  f1@20=0.126164

[TEST]
recall@1=0.503142  recall@2=0.736758  recall@5=0.916957  recall@10=0.960847  recall@20=0.985363
precision@1=0.616221  precision@2=0.472374  precision@5=0.248985  precision@10=0.132619  precision@20=0.068424
ndcg@1=0.616221  ndcg@2=0.703718  ndcg@5=0.782533  ndcg@10=0.799331  ndcg@20=0.806503
hit_rate@1=0.616221  hit_rate@2=0.826675  hit_rate@5=0.948534  hit_rate@10=0.975677  hit_rate@20=0.992429
map@1=0.616221  map@2=0.666237  map@5=0.722512  map@10=0.732726  map@20=0.735522
mrr@1=0.616221  mrr@2=0.721609  mrr@5=0.756799  mrr@10=0.760662  mrr@20=0.762034
f1@1=0.536619  f1@2=0.553911  f1@5=0.377762  f1@10=0.227005  f1@20=0.125814

Epoch 98/100: 100%|██████████| 820/820 [00:14<00:00, 57.81it/s, bpr=0.0131, c=2.55, loss=0.115]

[VAL]
recall@1=0.496746  recall@2=0.729308  recall@5=0.921949  recall@10=0.960545  recall@20=0.987178
precision@1=0.608306  precision@2=0.467056  precision@5=0.250823  precision@10=0.132782  precision@20=0.068726
ndcg@1=0.608306  ndcg@2=0.695918  ndcg@5=0.781391  ndcg@10=0.796070  ndcg@20=0.803808
hit_rate@1=0.608306  hit_rate@2=0.819516  hit_rate@5=0.953629  hit_rate@10=0.976452  hit_rate@20=0.993871
map@1=0.608306  map@2=0.658266  map@5=0.719232  map@10=0.728243  map@20=0.731239
mrr@1=0.608306  mrr@2=0.713790  mrr@5=0.753101  mrr@10=0.756249  mrr@20=0.757464
f1@1=0.529669  f1@2=0.547735  f1@5=0.379992  f1@10=0.227034  f1@20=0.126277

[TEST]
recall@1=0.494527  recall@2=0.728596  recall@5=0.923581  recall@10=0.963438  recall@20=0.986467
precision@1=0.606556  precision@2=0.465770  precision@5=0.250918  precision@10=0.133014  precision@20=0.068541
ndcg@1=0.606556  ndcg@2=0.694164  ndcg@5=0.781104  ndcg@10=0.796431  ndcg@20=0.803208
hit_rate@1=0.606556  hit_rate@2=0.818702  hit_rate@5=0.954172  hit_rate@10=0.978012  hit_rate@20=0.993073
map@1=0.606556  map@2=0.656069  map@5=0.718323  map@10=0.727777  map@20=0.730482
mrr@1=0.606556  mrr@2=0.712750  mrr@5=0.752250  mrr@10=0.755625  mrr@20=0.756819
f1@1=0.527776  f1@2=0.546999  f1@5=0.380653  f1@10=0.227640  f1@20=0.126012

Epoch 99/100: 100%|██████████| 820/820 [00:14<00:00, 57.29it/s, bpr=0.0323, c=2.53, loss=0.134]

[VAL]
recall@1=0.496345  recall@2=0.732617  recall@5=0.919153  recall@10=0.960413  recall@20=0.986436
precision@1=0.608790  precision@2=0.469153  precision@5=0.250048  precision@10=0.132645  precision@20=0.068694
ndcg@1=0.608790  ndcg@2=0.698032  ndcg@5=0.780377  ndcg@10=0.795960  ndcg@20=0.803329
hit_rate@1=0.608790  hit_rate@2=0.824032  hit_rate@5=0.950323  hit_rate@10=0.976774  hit_rate@20=0.993145
map@1=0.608790  map@2=0.659597  map@5=0.718670  map@10=0.728030  map@20=0.730675
mrr@1=0.608790  mrr@2=0.716089  mrr@5=0.753108  mrr@10=0.756788  mrr@20=0.757575
f1@1=0.529465  f1@2=0.550208  f1@5=0.378823  f1@10=0.226851  f1@20=0.126212

[TEST]
recall@1=0.497433  recall@2=0.732167  recall@5=0.921670  recall@10=0.962995  recall@20=0.985539
precision@1=0.609617  precision@2=0.469112  precision@5=0.250515  precision@10=0.132917  precision@20=0.068452
ndcg@1=0.609617  ndcg@2=0.698391  ndcg@5=0.782099  ndcg@10=0.797900  ndcg@20=0.804664
hit_rate@1=0.609617  hit_rate@2=0.822487  hit_rate@5=0.951997  hit_rate@10=0.977126  hit_rate@20=0.992268
map@1=0.609617  map@2=0.660519  map@5=0.720458  map@10=0.730141  map@20=0.732902
mrr@1=0.609617  mrr@2=0.716374  mrr@5=0.753883  mrr@10=0.757487  mrr@20=0.758994
f1@1=0.530698  f1@2=0.550187  f1@5=0.379948  f1@10=0.227510  f1@20=0.125861

Epoch 100/100: 100%|██████████| 820/820 [00:14<00:00, 57.10it/s, bpr=0.0292, c=2.63, loss=0.134]

[VAL]
recall@1=0.500367  recall@2=0.742304  recall@5=0.921325  recall@10=0.958991  recall@20=0.986818
precision@1=0.611855  precision@2=0.474395  precision@5=0.250516  precision@10=0.132516  precision@20=0.068685
ndcg@1=0.611855  ndcg@2=0.705631  ndcg@5=0.784875  ndcg@10=0.799463  ndcg@20=0.807296
hit_rate@1=0.611855  hit_rate@2=0.831855  hit_rate@5=0.952258  hit_rate@10=0.975000  hit_rate@20=0.993710
map@1=0.611855  map@2=0.667036  map@5=0.724417  map@10=0.733488  map@20=0.736251
mrr@1=0.611855  mrr@2=0.721532  mrr@5=0.757020  mrr@10=0.760485  mrr@20=0.761412
f1@1=0.533281  f1@2=0.556921  f1@5=0.379682  f1@10=0.226612  f1@20=0.126208

[TEST]
recall@1=0.502058  recall@2=0.744782  recall@5=0.923779  recall@10=0.962178  recall@20=0.986007
precision@1=0.614852  precision@2=0.476120  precision@5=0.251111  precision@10=0.132708  precision@20=0.068488
ndcg@1=0.614852  ndcg@2=0.708218  ndcg@5=0.787288  ndcg@10=0.801720  ndcg@20=0.809007
hit_rate@1=0.614852  hit_rate@2=0.832474  hit_rate@5=0.953206  hit_rate@10=0.976562  hit_rate@20=0.992429
map@1=0.614852  map@2=0.670063  map@5=0.727108  map@10=0.735786  map@20=0.738895
mrr@1=0.614852  mrr@2=0.723985  mrr@5=0.759133  mrr@10=0.762129  mrr@20=0.763781
f1@1=0.535536  f1@2=0.559153  f1@5=0.380857  f1@10=0.227210  f1@20=0.125928

,epoch,val_recall@1,val_recall@2,val_recall@5,val_recall@10,val_recall@20,val_precision@1,val_precision@2,val_precision@5,val_precision@10,...,test_mrr@1,test_mrr@2,test_mrr@5,test_mrr@10,test_mrr@20,test_f1@1,test_f1@2,test_f1@5,test_f1@10,test_f1@20
0,1,0.342584,0.543274,0.787423,0.926022,0.979068,0.431290,0.356290,0.213823,0.127879,...,0.422600,0.525693,0.584081,0.599378,0.602249,0.362224,0.408263,0.324524,0.219296,0.125046
1,2,0.386088,0.599191,0.855508,0.939571,0.982032,0.471452,0.380565,0.229887,0.129645,...,0.461260,0.569507,0.635989,0.643825,0.646094,0.402320,0.443522,0.349549,0.222377,0.125390
2,3,0.451094,0.675944,0.877964,0.944046,0.982930,0.552823,0.432903,0.237435,0.130339,...,0.548164,0.655122,0.700592,0.706475,0.708464,0.476741,0.507271,0.360087,0.223559,0.125585
3,4,0.470468,0.695941,0.891355,0.948619,0.985479,0.576452,0.445161,0.241468,0.131089,...,0.567091,0.674090,0.717279,0.722231,0.724372,0.494621,0.520546,0.366514,0.224462,0.125775
4,5,0.488718,0.716913,0.902518,0.948135,0.984958,0.596774,0.457944,0.244694,0.130968,...,0.597294,0.702199,0.739405,0.743976,0.745994,0.520424,0.540147,0.370402,0.224624,0.125752
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,0.503423,0.741053,0.919366,0.960188,0.987191,0.614435,0.473226,0.250032,0.132831,...,0.612919,0.719958,0.756496,0.759849,0.761011,0.535139,0.554360,0.379621,0.227540,0.125889
96,97,0.498029,0.737692,0.916404,0.958032,0.986117,0.609677,0.471855,0.249065,0.132435,...,0.616221,0.721609,0.756799,0.760662,0.762034,0.536619,0.553911,0.377762,0.227005,0.125814
97,98,0.496746,0.729308,0.921949,0.960545,0.987178,0.608306,0.467056,0.250823,0.132782,...,0.606556,0.712750,0.752250,0.755625,0.756819,0.527776,0.546999,0.380653,0.227640,0.126012
98,99,0.496345,0.732617,0.919153,0.960413,0.986436,0.608790,0.469153,0.250048,0.132645,...,0.609617,0.716374,0.753883,0.757487,0.758994,0.530698,0.550187,0.379948,0.227510,0.125861
99,100,0.500367,0.742304,0.921325,0.958991,0.986818,0.611855,0.474395,0.250516,0.132516,...,0.614852,0.723985,0.759133,0.762129,0.763781,0.535536,0.559153,0.380857,0.227210,0.125928

## Compare final rows of all experiments

In [14]:
import pandas as pd

def get_last_row(output, experiment_name):
    df = output["history_df"].copy()
    row = df.iloc[-1].to_dict()
    row["experiment"] = experiment_name
    return row

compare_df = pd.DataFrame([
    get_last_row(baseline_output, "step0_baseline"),
    get_last_row(global_attention_output, "step1a_global_attention"),
    get_last_row(user_attention_output, "step1b_user_attention"),
    get_last_row(full_model_output, "step2_full_model"),
])

cols = ["experiment"] + [c for c in compare_df.columns if c != "experiment"]
compare_df = compare_df[cols]
compare_df

,experiment,epoch,val_recall@1,val_recall@2,val_recall@5,val_recall@10,val_recall@20,val_precision@1,val_precision@2,val_precision@5,...,test_mrr@1,test_mrr@2,test_mrr@5,test_mrr@10,test_mrr@20,test_f1@1,test_f1@2,test_f1@5,test_f1@10,test_f1@20
0,step0_baseline,100.0,0.525813,0.728932,0.917700,0.963634,0.984658,0.636613,0.468831,0.249548,...,0.636276,0.724952,0.761939,0.765859,0.766835,0.557572,0.550981,0.379102,0.228081,0.125983
1,step1a_global_attention,100.0,0.539684,0.740385,0.919931,0.959561,0.984956,0.650323,0.471855,0.249935,...,0.654720,0.739489,0.776956,0.780182,0.781387,0.575916,0.554922,0.380108,0.226978,0.126043
2,step1b_user_attention,100.0,0.456372,0.663456,0.880958,0.945416,0.982192,0.560806,0.427097,0.239097,...,0.562097,0.658022,0.707050,0.712597,0.714482,0.487989,0.501684,0.363936,0.224317,0.125616
3,step2_full_model,100.0,0.500367,0.742304,0.921325,0.958991,0.986818,0.611855,0.474395,0.250516,...,0.614852,0.723985,0.759133,0.762129,0.763781,0.535536,0.559153,0.380857,0.227210,0.125928

## Export explanations from the best full-model checkpoint

In [15]:
!python export_explanations.py \
  --checkpoint "/content/drive/MyDrive/BT4222/PAL/checkpoints/SteamDebug/PAL/model/step2_full_model" \
  --conf "/content/drive/MyDrive/BT4222/PAL/checkpoints/SteamDebug/PAL/conf/step2_full_model" \
  --topn 5 \
  --top-items 3 \
  --split test

>>>>>>>>>>B-I statistics>>>>>>>>>>
Average interactions 5.757723808288574
Non-zero rows 0.9967479674796748
Non-zero columns 1.0
Matrix density 0.002042470229597649
>>>>>>>>>>U-I statistics>>>>>>>>>>
Average interactions 30.47064208984375
Non-zero rows 1.0
Non-zero columns 0.5001773678609436
Matrix density 0.010809025126048253
>>>>>>>>>>U-B statistics in train>>>>>>>>>>
Average interactions 1.7729297876358032
Non-zero rows 0.8142673955591551
Non-zero columns 0.3382113821138211
Matrix density 0.0028828125900210205
>>>>>>>>>>U-B statistics in tune>>>>>>>>>>
Average interactions 0.5909765958786011
Non-zero rows 0.41843828035364783
Non-zero columns 0.27479674796747966
Matrix density 0.0009609375300070068
>>>>>>>>>>U-B statistics in test>>>>>>>>>>
Average interactions 0.5909765958786011
Non-zero rows 0.4189782007153945
Non-zero columns 0.2780487804878049
Matrix density 0.0009609375300070068
Saved explanations to results/explanations_step2_full_model.csv